### ISSUE TITLE
Please implement flags for dm/co-op; also run at 320x240; and misc

### ISSUE THREAD

**Issue by Steroid-King** [fabiangreffrath/crispy-doom#100]
I copied this over from a request I made over in Chocolate Doom with one additional request:

There is a flag that I would like to request, and that would be the ability upon death in a co-op game, to keep all weapons, ammo, etc upon respawn. Or, to turn off team damage or adjust team damage scalar. Or, to activate cheats in a multiplayer game. Maybe this could be implemented as a command line argument.
Me and my buds play co-op in chocolate doom and we (that means me) have a nasty habit of team killing my buds in close quarters with a shotgun. It sort of sucks to have to go back through the entire level and pick up or find whatever weapons are available with what little ammo is still available for them.

Also, since this is Crispy Doom, I would also like the ability to switch back to 320x240 resolution and not have it run at the default 640x480. Thanks.

**Comment by Steroid-King** [comment]
If I may, if there could be an option to revert to full "stock" mode in setup, to behave identically to Chocolate Doom in form & function, not only in terms of gameplay but also menus, no menu background fade, default health/armor/ammo number colors, no enemy sprite horizontal flips when upon death, etc . . . that would be well acknowledged as well. Not sure if that'd be too much to ask for.

**Comment by plumsinus** [comment]
>Also, since this is Crispy Doom, I would also like the ability to switch back to 320x240 resolution and not have it run at the default 640x480. Thanks.

If you switch to low-detail mode, the renderer behaves as if in 320x200 resolution.

**Comment by fabiangreffrath** [comment]
Hi there,

> There is a flag that I would like to request, and that would be the ability upon death in a co-op game, to keep all weapons, ammo, etc upon respawn. Or, to turn off team damage or adjust team damage scalar. Or, to activate cheats in a multiplayer game. Maybe this could be implemented as a command line argument.

Sorry, but network gaming rules aren't going to change.

> Also, since this is Crispy Doom, I would also like the ability to switch back to 320x240 resolution and not have it run at the default 640x480. Thanks.

As @plumsinus already pointed out, the original 320x200 resolution is emulated in the "Graphic Detail: Low" mode.

> If I may, if there could be an option to revert to full "stock" mode in setup, to behave identically to Chocolate Doom in form & function, not only in terms of gameplay but also menus, no menu background fade, default health/armor/ammo number colors, no enemy sprite horizontal flips when upon death, etc . . . that would be well acknowledged as well. Not sure if that'd be too much to ask for.

The first time you start Crispy Doom, all of the optional additional features are already disabled. So, this mode is already there. Regarding all the other small changes that you mention, there are literally thousands of them and i am not going to add a switch for all of them. If you want to be more Vanilla than Crispy, there is still Choco for you. If Choco is *too* Vanilla, you can enable Crispy's features ony-by-one, but there is no finer granularity, sorry.

**Comment by Steroid-King** [comment]
Thanks
