### ISSUE TITLE
When switching away from 'Status bar' level stats setting the Kills line stays at the status bar

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#1002]
### Background

Version of Crispy Doom: Feb 3, 2023 latest build

Operating System and version: Win 10

Game: Doom 2

### Bug description

Observed behavior: When switching away from 'Status bar' level stats setting the Kills line stays at the status bar

Expected behavior: the Kills line should move above the Items line

https://www.youtube.com/watch?v=Sdx6bRW1Lyo

**Comment by SoDOOManiac** [comment]
Looks like there should be a == instead of & in **else** branch
`    if (crispy->automapstats == WIDGETS_STBAR && (!automapactive || w_title.y != HU_TITLEY))
    {
	HUlib_drawTextLine(&w_kills, false);
    }
    else
    if ((crispy->automapstats & WIDGETS_ALWAYS) || (automapactive && crispy->automapstats == WIDGETS_AUTOMAP))`

**Comment by fabiangreffrath** [comment]
Has apparently been introduced by this commit:
https://github.com/fabiangreffrath/crispy-doom/commit/35dc15ec4175d8d46997276953604e24e053a2fa
