### ISSUE TITLE
Hexen: Crash when swinging cleric's mace after changing aspect ratio, with uncapped framerate

### ISSUE THREAD

**Issue by jackrjli** [fabiangreffrath/crispy-doom#1004]
### Background

Version of Crispy Doom: Latest master (bug appears after 94ebb0cba2eb12c122438a684f1dd1326fb1b966)

Operating System and version: Fedora 37

Game: Hexen

Any loaded WADs and mods (please include full command line): hexen.wad (simply launched crispy-hexen with hexen.wad in the same directory)

### Bug description

Crispy Hexen crashes with a message like `R_DrawColumn: 1 to 199 at 640` after the following steps:

1. Launch Crispy Hexen with uncapped framerate and widescreen aspect ratio
2. Switch to the original aspect ratio in the Crispness menu (I think anything narrower than the starting aspect ratio will also do)
3. Start a new game as the Cleric
4. Swing the mace

**Comment by mikeday0** [comment]
Thanks @jackrjli!
