### ISSUE TITLE
For future: implement full mouselook from up to down

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#101]
As far as I remember, when the SDL2 branch of ChocoDoom is merged, there will be OpenGL rendering and full mouselook will be possible.

**Comment by fabiangreffrath** [comment]
Well, it seems some facts have been mixed up here.

Even with the switch to the SDL2 branch, the game will still be drawn with the software renderer. There is no magic switch to OpenGL rendering once the SDL2 branch is merged, everything will still be the good old renderer even Vanilla Doom already used.

What will change, however, is the way the original framebuffer (i.e. the "canvas" if you like) is stretched and scaled to screen. The palette-based integer-multiples-only approach that is currently used will get replaced by actual hardware-accelerated routines. And these actually make use of OpenGL.

So, given the limitations of the software renderer, full 180° mouselook is out of question for Crispy Doom, sorry.
