### ISSUE TITLE
Crispy HUD: in some DEHACKED-appying cases when player dies, animation of the dying player is played in the health section.

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#1011]
### Background

Version of Crispy Doom: Any since 5.8.0

Operating System and version: Win 10

Game: Doom 2

Any loaded WADs and mods (please include full command line): Struggle `crispy-doom -merge strg.wad`
You can download the WAD here https://www.doomworld.com/files/file/19194-struggle-antaresian-legacy/

### Bug description

Observed behavior: when player dies with Crispy HUD on, animation of the dying player is played in the health section, regardless of the player having been gibbed or not.
![DOOM0011](https://user-images.githubusercontent.com/15119473/218445707-69c9815f-4da9-4b36-b3e2-13df6f767335.png)

Expected behavior: if the player isn't gibbed, only the health amount (maybe negative if respective setting is enabled) should be displayed in the Crispy HUD's health section.
If the player is gibbed, the gibbing animation should be displayed there.

Generally speaking, how it behaves in Vanilla Doom.

**Comment by fabiangreffrath** [comment]
This is again specific to the Struggle WAD, right?

**Comment by SoDOOManiac** [comment]
In Batman Doom it's the same
![DOOM0012](https://user-images.githubusercontent.com/15119473/218455353-768f461b-01bf-4af9-a5cc-cdc059e658a9.png)
![DOOM0013](https://user-images.githubusercontent.com/15119473/218455358-5ec4bec2-e00e-4133-a6d0-e469cc89768f.png)

**Comment by fabiangreffrath** [comment]
I am currently only checking if the player state is past the initial gibb state, not taking into account that custom states may have been used after that.

Does this help?

```patch
diff --git a/src/doom/st_stuff.c b/src/doom/st_stuff.c
index 6b8758558..a4cf64b26 100644
--- a/src/doom/st_stuff.c
+++ b/src/doom/st_stuff.c
@@ -1879,6 +1879,15 @@ static byte* ST_WidgetColor(int i)

 // [crispy] draw the gibbed death state frames in the Health widget
 // in sync with the actual player sprite
+static inline boolean ST_PlayerIsGibbed (void)
+{
+       const int state = plyr->mo->state - states;
+
+       return (plyr->health <= 0 &&
+               ((state >= S_PLAY_XDIE1 && state <= S_PLAY_XDIE9) ||
+               state == S_GIBS))
+}
+
 static inline void ST_DrawGibbedPlayerSprites (void)
 {
        state_t const *state = plyr->mo->state;
@@ -1952,10 +1961,9 @@ void ST_drawWidgets(boolean refresh)

        // [crispy] draw the gibbed death state frames in the Health widget
        // in sync with the actual player sprite
-       if (plyr->health <= 0 && plyr->mo->state - states >= mobjinfo[plyr->mo->type].xdeathstate)
+       if ((gibbed = ST_PlayerIsGibbed()))
        {
                ST_DrawGibbedPlayerSprites();
-               gibbed = true;
        }
    }

```

**Comment by SoDOOManiac** [comment]
Thank you, this solves the problem :)

You have forgotten the semicolon after this return 

```
       return (plyr->health <= 0 &&
               ((state >= S_PLAY_XDIE1 && state <= S_PLAY_XDIE9) ||
               state == S_GIBS));
```

**Comment by fabiangreffrath** [comment]
> You have forgotten the semicolon after this return

Oh sure, thanks!
