### ISSUE TITLE
Doom - new Crispness Physical menu item: fix Doom 2 - exclusive monster projectiles triggering special linedefs

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#1015]
According to this wiki https://doomwiki.org/wiki/Projectiles_triggering_linedefs and [this discussion](https://www.doomworld.com/forum/topic/67168-crispy-doom-5120-update-sep-01-2022/?do=findComment&comment=2607646)
the Doom 2 - exclusive monster projectiles (those of arachnotrons, revenants and mancubi) were not included in the list of things that shouldn't trigger special linedefs:

```
    if (gameversion <= exe_doom_1_2)
    {
        if (line->special > 98 && line->special != 104)
        {
            return;
        }
    }
    else
    {
        //	Triggers that other things can activate
        if (!thing->player)
        {
            // Things that should NOT trigger specials...
            switch(thing->type)
            {
                case MT_ROCKET:
                case MT_PLASMA:
                case MT_BFG:
                case MT_TROOPSHOT:
                case MT_HEADSHOT:
                case MT_BRUISERSHOT:
                    return;

                default: break;
            }
        }
    }
```

I think it would be logical to introduce a Crispness menu item with the following wording (it fits, I checked):

Doom 2-only shots trigger lines: yes (1, set default in crispy.c)/no (0)

**Comment by fabiangreffrath** [comment]
He, no! This would insta-desync. We are not here to fix game-logic bugs.

**Comment by SoDOOManiac** [comment]
I initially suggested this to be a physical option, like walking over/under monsters that is neither demo/netgame compatible like all other physical options.
