### ISSUE TITLE
Video recording option

### ISSUE THREAD

**Issue by marespiaut** [fabiangreffrath/crispy-doom#102]
Hello,

I would like to know if a lossless video recording option would fit in the philosophy of Crispy Doom.
It would be interesting to have a launch parameter  `--record-video` or a key-press in-game to start the recording of the game into a lossless video file. Something like DOSBox have.

**Comment by fabiangreffrath** [comment]
As I have already stated in https://github.com/chocolate-doom/chocolate-doom/issues/715 this feature is already considered for Chocolate Doom, but some details still need to get figured out. If this ever gets implemented, it will be in Choco first and then merged from there into Crispy. I am closing this as a duplicate thus.
