### ISSUE TITLE
Quad resolution?

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#1024]
@JNechaevsky implemented 1280x800 framebuffer in InterDoom.

Will this also be a goal for Crispy?
If not, I will just aim at implementing it in my own fork separately.

**Comment by fabiangreffrath** [comment]
Nope, sorry, I don't have such goals for Crispy. Also, I don't think that the next logical step after double resolution should be quadruple resolution. It should be *any* resolution, but I don't have such plans either.
