### ISSUE TITLE
(request) Strife support

### ISSUE THREAD

**Issue by Ike120** [fabiangreffrath/crispy-doom#1027]
Upon looking through the repository i see that theres no version that supports strife and this is just a suggestion but maybe you can include crispy strife as an alternative for veteran edition due to the fact that veteran edition has a hard time running on low end computers due to all the screen effects

**Comment by fabiangreffrath** [comment]
@ceski-1 just finished adding back full strife support last month:
https://github.com/fabiangreffrath/crispy-doom/commit/7f2a6518b1e834a4d7c88cfc8602a3c204b872df
