### ISSUE TITLE
heretic, hexen and strife are not build - failure at autoreconf

### ISSUE THREAD

**Issue by tednilsen** [fabiangreffrath/crispy-doom#103]
Building the source goes well and doom runs fine, but heretic, hexen and strife are not build, the error comes from here:
`~/src/crispy-doom $ autoreconf -fi

src/Makefile.am:166: warning: variable '@PROGRAM_PREFIX@heretic_SOURCES' is defined but no program or
src/Makefile.am:166: library has '@PROGRAM_PREFIX@heretic' as canonical name (possible typo)
src/Makefile.am:174: warning: variable '@PROGRAM_PREFIX@hexen_SOURCES' is defined but no program or
src/Makefile.am:174: library has '@PROGRAM_PREFIX@hexen' as canonical name (possible typo)
src/Makefile.am:182: warning: variable '@PROGRAM_PREFIX@strife_SOURCES' is defined but no program or
src/Makefile.am:182: library has '@PROGRAM_PREFIX@strife' as canonical name (possible typo)
src/Makefile.am:171: warning: variable '@PROGRAM_PREFIX@heretic_LDADD' is defined but no program or
src/Makefile.am:171: library has '@PROGRAM_PREFIX@heretic' as canonical name (possible typo)
src/Makefile.am:179: warning: variable '@PROGRAM_PREFIX@hexen_LDADD' is defined but no program or
src/Makefile.am:179: library has '@PROGRAM_PREFIX@hexen' as canonical name (possible typo)
src/Makefile.am:187: warning: variable '@PROGRAM_PREFIX@strife_LDADD' is defined but no program or
src/Makefile.am:187: library has '@PROGRAM_PREFIX@strife' as canonical name (possible typo)
`
I'm building on raspberry pi 2, using Debian Jessie 4.4.9-v7+, gcc (Raspbian 4.9.2-10) 4.9.2
Everything builds fine using v2.2 at https://github.com/vanfanel/crispy-doom

**Comment by plumsinus** [comment]
As of Crispy Doom 3.3, games other than Doom are no longer supported, due to lack of development and lack of interest. They should work fine in 3.2.

**Comment by fabiangreffrath** [comment]
Just as @plumsinus pointed out, I do not carry around the non-Doom games as dead freight anymore -- at least as long as nobody steps up to take over their maintenance.

You are right about the automake warnings, though, I have fixed them in my last commit. Thanks for that!

https://github.com/fabiangreffrath/crispy-doom/commit/7388540beceda56948a6da92562a96b6fe9737cf
