### ISSUE TITLE
[Question] Anything need to be done in `msys2.yml` for FluidSynth?

### ISSUE THREAD

**Issue by mikeday0** [fabiangreffrath/crispy-doom#1032]
It appears that the Windows msys2 builds are automatically picking up FluidSynth support due to FluidSynth being a dependency of SDL_mixer. Is this desired? If so, should FluidSynth be added to the list [here](https://github.com/fabiangreffrath/crispy-doom/blob/846b721c4a7a20c2ca5e459bf20d02f41052b7d6/.github/workflows/msys2.yml#L43-L51)?

Otherwise if you don't want FluidSynth included in the Windows builds, I'm guessing we should pass `--without-fluidsynth` as a configuration option?

**Comment by fabiangreffrath** [comment]
> So the next release of Crispy will have FluidSynth. 

Even Choco will, we have just inherited from there.

> Should we add a soundfont?

I don't think so. This isn't supposed to work ad-hoc when enabled through an in-game menu. Instead, you'll have to explicitly set it up in the separate setup tool and will be prompted to give the path to a soundfont there.

**Comment by rfomin** [comment]
> Even Choco will, we have just inherited from there.

Not yet, chocopkg has an old FluidSynth 1.x.

**Comment by mikeday0** [comment]
> Not yet, chocopkg has an old FluidSynth 1.x.

One challenge I see with updating chocpkg to a newer version is that FluidSynth appears to have dropped autotools support some time ago. So if you wanted to build it from source (as is the chocpkg way) then you would also need to bring in cmake capability to that platform.

**Comment by mikeday0** [comment]
This has been addressed by 3b77ee1.
