### ISSUE TITLE
WADs with custom MP3 music sound extremely loud

### ISSUE THREAD

**Issue by Vitoria90** [fabiangreffrath/crispy-doom#1035]
### Background

Version of Crispy Doom:  5.12

Operating System and version: Windows 10 Pro

Game: (Doom/Heretic/Hexen/Strife/other): Ultimate Doom (v1.9), with Sigil_v1_21.wad and Sigil_shreds.wad

Any loaded WADs and mods (please include full command line):  CrispyDoom\crispy-doom.exe -iwad wads\vanilla\doom.wad -file wads\sigil\sigil_v1_21.wad wads\sigil\sigil_shreds.wad -savedir saves\sigil

### Bug description

Observed behavior: Volume of the MP3 songs in Sigil and other WADs with custom MP3 music is extremely loud. I have to set it to 1 on the audio config menu to hear the game.

Expected behavior: The music sounds normal.

If there's a way to set a custom config telling CrispyDoom to run with lowered music volume, it would be enough of a fix. As it stands, if I decide to play a WAD using MIDI soundtracks, those are practically inaudible with the volume at 1 and I have to manually set it back to a higher value. I don't have any WADs with .ogg music in them that are vanilla compatible to check if this is only an issue of the .mp3 format.

**Comment by rfomin** [comment]
> If there's a way to set a custom config telling CrispyDoom to run with lowered music volume, it would be enough of a fix.

There is `-config <file>` command line option.

I suspect you are using OPL emulation for MIDI music, I suggest trying Native MIDI, it is much louder than OPL.
![image](https://user-images.githubusercontent.com/5077629/228720277-e7e65368-74bb-46af-98eb-150b78341de9.png)

**Comment by mikeday0** [comment]
What are some other examples of wads w/ mp3s that have this problem?

**Comment by mikeday0** [comment]
I can't seem to reproduce this on my end. The volume on IDKFAv2.wad seems reasonable to me, and matches what I get in prboom-plus and dsda-doom.

**Comment by rfomin** [comment]
@Vitoria90 I guess it depends on which MIDI interface you are using. Both DSDA-Doom and GZDoom use FluidSynth by default, which is louder than Native MIDI and OPL. Try selecting portmidi in PrBoom+/DSDA-Doom and MS GS Wavetable in GZDoom, you should get roughly the same volume levels as in Crispy.

**Comment by fabiangreffrath** [comment]
I cannot reproduce this as well. I'm sure that you merely got used to the somewhat more silent music emitted by the OPL emulator and are surprised by the original volume of digital music in contrast.

**Comment by Vitoria90** [comment]
> @Vitoria90 I guess it depends on which MIDI interface you are using. Both DSDA-Doom and GZDoom use FluidSynth by default, which is louder than Native MIDI and OPL. Try selecting portmidi in PrBoom+/DSDA-Doom and MS GS Wavetable in GZDoom, you should get roughly the same volume levels as in Crispy.

So I do use those settings in GZDoom and PRBoom+, and yet the volume difference between MIDI and MP3/OGG is nowhere near this drastic. It's an issue I'm only finding in Crispy Doom.

**Comment by rfomin** [comment]
> boosting the audio levels of my MIDI drivers for Crispy Doom

Are you not using MS GS Wavetable Synth? Please provide more information about MIDI setup. In Crispy Doom 6.0 you can now select Native MIDI device in the setup tool, check that out as well.

**Comment by Vitoria90** [comment]
> > boosting the audio levels of my MIDI drivers for Crispy Doom
> 
> Are you not using MS GS Wavetable Synth? Please provide more information about MIDI setup. In Crispy Doom 6.0 you can now select Native MIDI device in the setup tool, check that out as well.

I have been using Native MIDI setting on Crispy Doom, and I use CoolSoft VirtualMIDISynth for my MIDI device, since it's easy to set up custom soundfonts for it. I've tested the built in PortMIDI for PRBoom+, FluidSynth for GZDoom, and CoolSoft VirtualMIDISynth for both of them, and the volume levels are not extremely disparate the way it is in CrispyDoom.

**Comment by rfomin** [comment]
Have you selected VirtualMIDISynth in the crispy-doom-setup?
![image](https://user-images.githubusercontent.com/5077629/229313732-ae670439-bec2-48ba-a8b1-df5b9467d41a.png)

**Comment by Vitoria90** [comment]
> Have you selected VirtualMIDISynth in the crispy-doom-setup? ![image](https://user-images.githubusercontent.com/5077629/229313732-ae670439-bec2-48ba-a8b1-df5b9467d41a.png)

No, I can't get that choice window to show up. Also, it is already going through VirtualMIDISynth regardless, as I can already control mixing and volume through it.

**Comment by rfomin** [comment]
> No, I can't get that choice window to show up.

Try upgrading to Crispy Doom 6.0, it has this window.

**Comment by Vitoria90** [comment]
> > No, I can't get that choice window to show up.
> 
> Try upgrading to Crispy Doom 6.0, it has this window.

Yup, seems the problem was specific to v5.12. While the MIDI is still quieter than the MP3 now, the difference is significantly smaller, I should be able to get them to sound okay with some adjustment.
