### ISSUE TITLE
(Hexen) Some weapon animations don't seem to be working properly

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/crispy-doom#1039]
### Background

Version of Crispy Doom: 6.0.0

Operating System and version: Windows 7 Home Premium x64

Game: Hexen

Any loaded WADs and mods (please include full command line): None

### Bug description

Observed behavior: I'm not sure how to explain this properly, but I'll try. In any case, you can try it yourselves and compare against DOS or Chocolate Hexen.

The Fighter and Cleric's starting weapons (mace and fist respectively, sorry if I got the names wrong) have certain frames that I believe are supposed to maintain one given sprite but be moved constantly until they're offscreen (in the case of the Fighter's fist, this seemingly happens upon dealing three consecutive hits). However, this effect is not present, and the weapon sprite remains static for a bit until you can attack again.

Expected behavior: Same behavior as in DOS/Chocolate.

**Comment by mikeday0** [comment]
I assume  you have Weapon Attack Alignment set to either Bobbing or Centered?

**Comment by MrAlaux** [comment]
Yes, on "Centered". The same thing happens on "Bobbing", and with the setting disabled it works as expected.

**Comment by mikeday0** [comment]
Thanks for bringing this to my attention!
