### ISSUE TITLE
Reset midi info on track change?

### ISSUE THREAD

**Issue by plumsinus** [fabiangreffrath/crispy-doom#104]
Hi Fabian. I posted about this at https://www.doomworld.com/vb/source-ports/88062-midi-reset-on-new-music/ but it didn't get any response -- perhaps you didn't see it yet, but in any case I might as well bring it up here.

A lot of music in wads assumes a default state for midi info (panning, reverb, etc.) which is not guaranteed if the previous music track set those values to something else.

One way to fix this would be for the Doom port to reset all relevant midi data whenever the music changes. ZDoom does this already, I think; Crispy (and Chocolate) Doom, PrBoom+, and likely other ports don't. 

Is this something you'd consider adding to Crispy Doom? I don't know if it belongs in Chocolate Doom or not -- I'll cook up some examples later today and test them in vanilla to see what happens.

**Comment by plumsinus** [comment]
Hm, I was wrong -- Crispy Doom does this properly I think! Seems like it's only PrBoom+. Sorry for the false report.

**Comment by fabiangreffrath** [comment]
Thanks for recording this anyway! I am only reading through the DW forums very occasionally at the moment and thus might easily miss some issues that are discussed (only) there.

**Comment by plumsinus** [comment]
I figured as much. I was originally hoping for some reply from others having the same problem, otherwise I would have just posted here in the first place. But since my assumption was wrong it's no surprise there wasn't much interest.
