### ISSUE TITLE
Create a dedicated homepage for Crispy Doom

### ISSUE THREAD

**Issue by kiwphi** [fabiangreffrath/crispy-doom#1041]
I'm proposing the below after a discussion with @fabiangreffrath.

Currently, the source of information about crispy-doom comes from either the [page hosted at chocolate-doom.org](https://www.chocolate-doom.org/wiki/index.php/Crispy_Doom), or the [github readme](https://github.com/fabiangreffrath/crispy-doom).

I thought it would be a good idea to have a dedicated homepage for the project, in order to:
- Offer this information in a better format instead of being condensed in a huge readme.
- Attract non tech-savvy users. We might be used to the github interface, but it's not the best place to offer binaries to a random person who just wants to play doom.
- Having a dedicated homepage gives more value to the project.
- Easier to share once it gets its own domain name

[Link to the repo](https://github.com/kiwphi/crispy-homepage) | [Live Preview](https://kiwphi.github.io/crispy-homepage/)

**Comment by kiwphi** [comment]
- Updated the homepage's content to reflect crispy-doom's features (added gifs showing the enhanced resolution, widescreen support & crispness menu)
- Added on-scroll transparency effect to pixelated background (this greatly improves the text's readability)
- Added a preliminary footer

Next step is adding a modal for the gifs (to show a larger version of the image after being clicked on)

**Comment by fabiangreffrath** [comment]
Sorry, but it currently looks completely borked on my phone. 

![Screenshot_20230404_192540_Chrome](https://user-images.githubusercontent.com/6449237/229870626-6ec58eba-e581-4e0d-9dfa-88f0f2107269.jpg)

**Comment by kiwphi** [comment]
@fabiangreffrath, I still didn't optimize for mobile and smaller screens since the content is still subject to change in this early stage.

**Comment by kiwphi** [comment]
@fabiangreffrath, could you please test it now. I added media queries that should match most screen.

<img width="600" alt="mobile" src="https://user-images.githubusercontent.com/120708663/230031194-fac0f006-65a7-4d80-8f6e-3405fba6d3e6.png">

**Comment by fabiangreffrath** [comment]
A whole lot better already, thank you very much!

**Comment by JNechaevsky** [comment]
Do we have a favicon yet? 🙂 Please, do not use icon from [source code](https://github.com/fabiangreffrath/crispy-doom/blob/master/data/doom.ico), it's a bit too big (104 kb), while it can be mush smaller for optimization, errrr, for banwidth saving purposes. I will be able to compose an icon with needed sizes in the evening.

**Comment by JNechaevsky** [comment]
Here, I've deleted 256x256 and 128x128 icons, leaving only 64x64, 48x48, 32x32 and 16x16 sizes, now it's just 31 kb ([favicon.zip](https://github.com/fabiangreffrath/crispy-doom/files/11160479/favicon.zip)). These sizes should be enough for common cases, but googling "[favicon sizes 2023](https://www.google.ru/search?q=favicon+sizes+2023&newwindow=1&sxsrf=APwXEdf9PveW4kxdKUzoRIulQB2l_8Jlkw%3A1680708393890&iflsig=AOEireoAAAAAZC2hOVH4Uqti04jYre69xvTI_iEIiv3m&sclient=gws-wiz)" shows that big sizes are actually used nowadays. 

Hmm... Maybe we should still use version with bigger sizes from [source code](https://github.com/fabiangreffrath/crispy-doom/blob/master/data/doom.ico)? Not sure if ~70 kilobytes is the size that matters, plus standard browser cache should do it's thing.

**Comment by kiwphi** [comment]
Thanks! I'm not sure there's much use for larger than 64x64. I guess these are only used when links to URLs are created outside of the browser, which I don't assume happens often.

**Comment by kiwphi** [comment]
- Added modals for images 
- Added favicon (thanks @JNechaevsky). We might check the (dreaded) meta-tags and revise the icon at a later stage if needed
- Re-written all Javascript from scratch (refactored all of the first-draft code into proper maintainable classes)

What I'm planning next are the content of the Features & Downloads pages.
Features is currently a wall of text, we need to fix that
Download page is boring, could use some make-up

**Comment by fabiangreffrath** [comment]
Just a nitpick, but the screenshots showing the "double the resolution" feature are a bit misaligned.

**Comment by kiwphi** [comment]
- Merged background changes. Backdrop is randomly picked - before page load - and only this one is loaded. I'll add new backdrops over time. 
- Revamp "Downloads" page. I assumed that 64-bit windows is the most wanted, so the big button downloads this version. Any feedback?
- Fixed resolution-comparison gif alignment

**Comment by fabiangreffrath** [comment]
Wow, it's getting better and better. Nice work, thank you!

**Comment by fabiangreffrath** [comment]
Mobile browser again: When I scroll down, the screenshot background realigns itself a bit.

**Comment by kiwphi** [comment]
Do you mean the pixelated background, or the resolution/widescreen screenshots? I can't seem to spot it, any chance you could capture it?

**Comment by fabiangreffrath** [comment]
I tried, hope you can see it. Keep watching the red flame of the torch.


https://user-images.githubusercontent.com/6449237/230371740-31dac9fa-99f4-46c5-bbc2-1b0585c090c3.mp4

**Comment by kiwphi** [comment]
I'm guessing that the scrollbar (although not always visible) is affecting the viewport. I can't reproduce it on both chrome & firefox on my phone, but I've added "overflow: hidden" to the div in an attempt to fix it - could you please try it now?

**Comment by fabiangreffrath** [comment]
Works now, thanks! 👍

**Comment by kiwphi** [comment]
Latest iteration of the downloads page:

![image](https://user-images.githubusercontent.com/120708663/230388941-468bd363-c74f-4757-97b7-996c4bfda2f1.png)

**Comment by kiwphi** [comment]
- Merged "about" & "features" pages in order to reduce redundancy. To avoid having a wall of text by having all of the features just "pasted" into one page , we are now showing the "Synopsis", followed by the "Core Features" and a "Show more features" button that will display the additional features if one desires to see them. It seems like a good reading flow to me.

- Added "Usage" page (i've thought about naming it "guide" or "help" too... any feedback on the name?).
It has all the command-line parameters & cheats. The challenge was to present all this information in a readable way, I'm happy with the current result. Might still be subject to some tweaks if need be. The whole page is still WIP

- Added build-instructions to the Download page.

**Comment by fabiangreffrath** [comment]
Impressive! Please credit yourself in the first line.

**Comment by kiwphi** [comment]
Thanks, will do!
On another note, are you the one maintaining the flatpak? It seems like when flathub's new website comes out of beta, flatpaks that are published by the developers themselves will have a "verified" checkmark to prove that these are the official distributions.
It seems like [crispy's flatpak](https://beta.flathub.org/apps/io.github.fabiangreffrath.Doom) is not yet verified. I just noticed when adding a flatpak link to the website.
 
Here's how firefox looks like for example, and [here](https://beta.flathub.org/apps/collection/verified/1)'s a list of verified apps.
![image](https://user-images.githubusercontent.com/120708663/230604338-cfadf471-9004-4b7b-a392-a8d3d5386147.png)

**Comment by kiwphi** [comment]
Added icons to download page:
![image](https://user-images.githubusercontent.com/120708663/230607422-d7bfddab-363c-4a9a-9a5a-80f494877089.png)

Improve usage page:
![image](https://user-images.githubusercontent.com/120708663/230607566-01cef266-a095-4b10-b8be-873340a0c80f.png)

**Comment by fabiangreffrath** [comment]
No, I don't have *anything* to do with the flatpack packaging! The Download and Usage pages look great now, thanks again!

**Comment by kiwphi** [comment]
@fabiangreffrath, I think I'm done transfering the content. Please feel free to proofread the website.
Below is a summary of the information that I found, transferred and improved:

**From the readme**
- Synopsis
- Features
- New commandline params
- New cheats
- Download
- Sources

**From the wiki on Github**
Crispness Menu - copied in full (needs updating though, i'll do this later)

**What was not copied**
- Building on windows/macos: These are lengthy instructions. These can be kept on github with a link to them from the website's download page for those who would like to read them.
- New Controls - is there a need to have this on the website?
- Compatibilty & FAQ from the wiki: Are those updated? Shall I transfer them?

**Comment by kiwphi** [comment]
- Re-styled expandable sections & added ability to expand/collapse.
I'm using vanilla javascript for everything, so we're using zero external libraries in order to keep the code-base simple & minimal

[Screencast from 2023-04-08 15-27-17.webm](https://user-images.githubusercontent.com/120708663/230721053-34067b61-87de-4bd2-b338-6cfd1c6e378a.webm)

**Comment by kiwphi** [comment]
One thing to think of is how to maintain this content and keep it up to date, without having out-of-sync information between the Gihub repo MD files and the website (cheats, commands etc...). So every time there is a change/update, it would be more reasonable to update it in one place instead of having to change the MD files on the repo and also the website. I can suggest 2 ways to tackle this:
- Either the website becomes the only source of documentation and these pages are removed from the repo. Documentation is maintained in one place, which is the website
- The MD files all remain in the repo, and I can fetch & parse them to display them on the website. This way once a MD file changes on the repo, the website gets automatically updated. But we'll have to organize things in order for this to work without going into regex hell. For example, we can have "cheats.md", "commands.md", all still in the repo, but better organized instead of having 1 huge readme.

**Comment by kiwphi** [comment]
Ahh, I always forget about the non-doom games! If you could submit a PR that would be great!
Regarding WADs, are you implying that we should provide wads that don't require the licensed games, similar to freedoom? Just so that everyone is able to play?

**Comment by mikeday0** [comment]
> Regarding WADs, are you implying that we should provide wads that don't require the licensed games, similar to freedoom? Just so that everyone is able to play?

I'm referring specifically to WADs which provide widescreen-compatible replacement assets which have updated status bars, weapon sprites and full-screen graphics. (The kind posted in this [thread](https://www.doomworld.com/forum/topic/121385-widescreen-assets-pack-and-appreciation-thread/).)

**Comment by rfomin** [comment]
I think we can host official Bethesda ones: https://bethesda.net/en/game/doom-widescreen-mods

**Comment by mikeday0** [comment]
I was thinking we could make an asset pack based on [these](https://github.com/nashmuhandes/WidePix/).

**Comment by kiwphi** [comment]
I think it's beyond the current scope of the homepage. For the time being, the goal is to keep things simple and straight to the point without much extras, unless really necessary. There might be room for those at a later point, but for now the goal is to get the core content & functionality of the homepage polished and complete.

**Comment by rfomin** [comment]
> * "docs" directory in the root of the project (it would be under version control, so no wiki), which contains all the documentation carefully split into many files (cheats.md, commands.md, crispness-menu.md, building-on-windows.md etc...).

We can also update the wiki using github actions like this: https://github.com/fabiangreffrath/woof/blob/master/.github/workflows/update_wiki.yml

**Comment by kiwphi** [comment]
ah, thanks for sharing that. so i assume we'll have to put the docs under version control anyway, and with github actions they can be transfered to the wiki and then updated on each push for example, is that correct?

**Comment by rfomin** [comment]
> we'll have to put the docs under version control anyway, and with github actions they can be transfered to the wiki and then updated on each push for example, is that correct?

Yes, at least I will try to make it work.

**Comment by kiwphi** [comment]
I have created an issue for the documentation #1047

**Comment by mikeday0** [comment]
> I, for example, do never play with widescreen assets. Instead, I always load DoomMetal.wad and a custom palette in my autoload directory. Should we link to them, too? 😉

The non-Doom games all have some number of psprites that are broken in widescreen. (Hexen is the worst offender.) For that reason other source ports (GZDoom and Interational Doom come to mind) actually ship with these updated assets. 

I'm not trying to force a particular mod preference on anyone, just trying to improve the experience for new users. The nice thing about the WidePix assets is that they were developed such that they preserve the original 4:3 experience when you play in that aspect ratio. So in that sense I would argue they are different than music replacement, "smooth" mods, etc.

**Comment by kiwphi** [comment]
@JNechaevsky, any chance you could take care of managing the meta tags?

**Comment by JNechaevsky** [comment]
On my way. Will post an example after I got more or less acceptable result, it's not that easy as filling few tags.

**Comment by JNechaevsky** [comment]
Allright, attempt number seven, looks likes it's working: https://socialsharepreview.com/?url=https://jnechaevsky.github.io/cr/
Added meta tags are here: https://github.com/JNechaevsky/jnechaevsky.github.io/blob/main/cr/index.html#L6-L14

Some remarks:
* I can't get Twitter preview working. Facebook and LinkedIn (erm..) seems to be working, as well as Discord ([screenshot](https://user-images.githubusercontent.com/21193394/232128772-bbe75a59-040f-413f-aa7b-6ddfa2694483.png)).
* Path to `og:image` must be absolute. Path like "./repo/preview.png" does not seems to be working.
* Absolutely not sure I'm doing it right, even after following recommendations. On top of that, my HTML knowledge is stopped on Web 1.0 era.

**Comment by kiwphi** [comment]
Well that's a great start, at least we've got the foundations to build upon. I'm absolutely clueless regarding this type of stuff so I'm very thankful.
After a quick search it seems like Twitter searches for "name" instead of "property", e.g. <meta **name**="twitter:title" content="Crispy Doom" /> etc... could you try it out?
Also seems like og:image path being absolute is by design, so we'll have to abide

**Comment by JNechaevsky** [comment]
Thanks! That's worked: https://socialsharepreview.com/?url=https://jnechaevsky.github.io/cr/
New code: https://github.com/JNechaevsky/jnechaevsky.github.io/blob/main/cr/index.html#L6-L15

Strangely, Twitter preview reports that "card" is set, while "image" (which is Twitter Card!) is not, and I'm not getting media preview while making post on Twitter. Hmph. :thinking:

**Comment by kiwphi** [comment]
I might be wrong, but shouldn't the <meta> tag at line 12 be self closing, and the </meta> closing tag at line 15 be discarded?

**Comment by JNechaevsky** [comment]
Oh, you right. I was thinking it will help to kick possible Twitter hash of gathering "card" image, but it doesn't worked. I have reverted it to more correct approach.

P.S. preview.png is just a filler, I was needed it for checking, so I would like to recommend do not use it for final version. However, my initial idea was slightly different... 🤭

<details>

![FLAT8](https://user-images.githubusercontent.com/21193394/232210227-3961c673-b227-4452-a90a-b8994bb9d4cf.png)

</details>

**Comment by kiwphi** [comment]
Crispy-doom preview looks great, could you optimize it and do a PR with the final tags?

**Comment by JNechaevsky** [comment]
Done in https://github.com/kiwphi/crispy-homepage/pull/6 🙂
I'll try to keep investigation, maybe there is something else with preview images. Hand with a pistol also doesn't looks likes good in preview, will need some extra time to experiment and provide different variants so everyone will be able to vote/choose better one.

**Comment by kiwphi** [comment]
Thank you very much!

**Comment by kiwphi** [comment]
- Shall we add more content related to non-doom games, besides the newly added summary on the front-page? such as screenshots for example, or do we keep it at the minimum?

- What remains to be done is to automate the content fetching process, depending on the fate of #1050

**Comment by kiwphi** [comment]
Alright it's all ready now! All of the usage page (cheats, command-line params & crispness menu) are now fetched from the repo. In case we need to change something, all we have to do is update the .md files in /docs and the website will be automatically updated.
Big thanks to @rfomin for helping with re-organizing the documentation and writing the Github Actions for the Wiki.

@fabiangreffrath, do you mind if we remove the first few lines of comments from [this file](https://raw.githubusercontent.com/fabiangreffrath/crispy-doom/master/docs/crispness.md) ? They're being parsed into the HTML and I'll have to hide them in a dirty way using CSS if they're staying. It would be cleaner to remove them from the .md if that's not an issue.

**Comment by fabiangreffrath** [comment]
> @fabiangreffrath, do you mind if we remove the first few lines of comments from [this file](https://raw.githubusercontent.com/fabiangreffrath/crispy-doom/master/docs/crispness.md) ? They're being parsed into the HTML and I'll have to hide them in a dirty way using CSS if they're staying. It would be cleaner to remove them from the .md if that's not an issue.

done.

**Comment by mikeday0** [comment]
Just a couple of minor things I noticed on the Usage page:
![image](https://user-images.githubusercontent.com/43701387/234001705-ffb4db05-a369-4ebe-9c50-1e0797e3e2b1.png)
![image](https://user-images.githubusercontent.com/43701387/234002606-f7ac355a-3e1a-4d61-8b0b-c8c8fd778f75.png)

**Comment by kiwphi** [comment]
Seems like the sound-channels issue is also not being parsed correctly in the [.md file](https://github.com/fabiangreffrath/crispy-doom/blob/master/docs/crispness.md)
![image](https://user-images.githubusercontent.com/120708663/234004286-02c1f143-70e5-4995-a46f-8a8cf3f115fd.png)

As for the <kbd> that's the markdown parser i'm using not parsing it correctly, i'll see what i can do about that.

**Comment by kiwphi** [comment]
fixed the kbd tags issue, now rendering correctly

**Comment by kiwphi** [comment]
@fabiangreffrath, any feedback or request for changes?

**Comment by fabiangreffrath** [comment]
No, all is fine, let's get this online!

**Comment by kiwphi** [comment]
it's already hosted on github pages we just need to get the domain and set the dns records.
does crispydoom.org sound good?

**Comment by fabiangreffrath** [comment]
Yes, that'd be perfect!

**Comment by fabiangreffrath** [comment]
> it's already hosted on github pages we just need to get the domain and set the dns records. does crispydoom.org sound good?

Wait a minute, chocolate-doom.org has a dash in the middle. I want that, too. 😁

**Comment by fabiangreffrath** [comment]
Thank you very much for this, the homepage is beautiful! :tada: 

And thanks to evreybody else involved in this project!

Did you have to pay for the dns registration?

**Comment by kiwphi** [comment]
standard .org domain name registration, around $10 / year.

**Comment by fabiangreffrath** [comment]
> standard .org domain name registration, around $10 / year.

I should be paying this. Do you have a paypal account?

**Comment by kiwphi** [comment]
it's ok, i'll handle it this year, not worth it.

**Comment by fabiangreffrath** [comment]
> it's ok, i'll handle it this year, not worth it.

Awesome, thank you so much!

**Comment by kiwphi** [comment]
Hello,

What do you think about updating the doomwiki's sidebar's website link to crispy-doom.org, as well as adding it to the github repo's side bar like chocolate-doom?

![image](https://user-images.githubusercontent.com/120708663/236621883-4ceffe1e-6baa-4a30-8c59-faff4813ebfd.png)

**Comment by fabiangreffrath** [comment]
Yes, very good idea.

**Comment by kiwphi** [comment]
alright, seems like this thread has achieved its purpose of bringing the website to life, i'll close it. further updates/issues can be done directly in the [website's repo](https://github.com/kiwphi/crispy-homepage) if needed
