### ISSUE TITLE
5fd8c7627adffdad220afd8fd7371bdf7a5d3eb2 makes doom hang on new game

### ISSUE THREAD

**Issue by q66** [fabiangreffrath/crispy-doom#1043]
### Background

Version of Crispy Doom: 6.0

Operating System and version: Linux ppc64le, 6.1.20

Game: Doom shareware

Any loaded WADs and mods (please include full command line): nothing, just doom1.wad

### Bug description

Observed behavior: Game hangs when I start new game, it hangs; e1m1 keeps playing until I kill the process

Expected behavior: game works

I have been seeing this issue since 5.12. Reverting https://github.com/fabiangreffrath/crispy-doom/commit/5fd8c7627adffdad220afd8fd7371bdf7a5d3eb2 on top of 6.0 makes the game work fine.

**Comment by fabiangreffrath** [comment]
> Operating System and version: Linux ppc64le, 6.1.20

> Observed behavior: Game hangs when I start new game, it hangs; e1m1 keeps playing until I kill the process

Ouch!

> I have been seeing this issue since 5.12. Reverting [5fd8c76](https://github.com/fabiangreffrath/crispy-doom/commit/5fd8c7627adffdad220afd8fd7371bdf7a5d3eb2) on top of 6.0 makes the game work fine.

Might be an endianess issue, as I cannot reproduce this on any of my systems.

The commit in question has two chunks. Could you tell which of both is causing the problems?

Also, could you run the game in gdb and see where exactly it hangs? I am curious if it hangs in the setup code or when it attempts to draw the map.

**Comment by q66** [comment]
ppc64le is a little endian system, definitely not endianness

i will try debugging the problem a bit more

**Comment by q66** [comment]
sorry, i was mostly away from my computers the last few weeks, so i couldn't actually take a look at this deeper

i think this might be a miscompilation caused by clang, related to the anglediff function; i managed to make a minimal reproducer, which enters infinite loop:

```
#include <stdio.h>

static unsigned int testfunc(unsigned int a, unsigned int b) {
    printf("%u %u %d\n", a, b, b > a);
    if (b > a) {
        return testfunc(b, a);
    }
    return a - b;
}

int main(void) {
    printf("%u\n", testfunc(0, 100));
    return 0;
}
```

basically the first branch is entered always, regardless of the condition; the output i get is like:

```
0 100 1
100 0 0
0 100 1
100 0 0
0 100 1
100 0 0
0 100 1
100 0 0
0 100 1
100 0 0
0 100 1
...
```

**Comment by q66** [comment]
confirmed with an LLVM developer, this is clang not handling tail recursion correctly in this case (i'm surprised i have not run into this before, but it seems to be an edge case, because if i e.g. add another statement into the return branch, it actually works fine) specifically on ppc64le only (i confirmed it works fine on x86_64, aarch64 and risc-v)

**Comment by q66** [comment]
I opened a ticket for it on LLVM side: https://github.com/llvm/llvm-project/issues/62294

since this is a compiler bug and not crispy-doom bug, I will close this and not bother you further with it :)
