### ISSUE TITLE
Re-organize documentation

### ISSUE THREAD

**Issue by kiwphi** [fabiangreffrath/crispy-doom#1047]
I propose re-organizing the documentation since it's currently difficult to find information with the current state of things:
- Some information is found in files scattered all around (project root, man directory etc...)
- Some information is found only in the wiki
- Some MD files are extremely outdated
- Some belong to chocolate-doom and are not applicable to crispy

**Comment by kiwphi** [comment]
I think a good first step would be to move some components of the readme into their own .md files and link to them instead such as the below screenshot. Then as proposed by @rfomin, Github Actions can be used to create the wiki entries 

[Live preview on this branch](https://github.com/kiwphi/crispy-doom/tree/docs)
(links not working yet since they're supposed to link to the currently non-existing wiki entries)

![image](https://user-images.githubusercontent.com/120708663/231122070-7e21b7ae-655b-479b-a1f8-6ddc01d1fdd0.png)

**Comment by fabiangreffrath** [comment]
Yes, this is a good idea!

**Comment by kiwphi** [comment]
[Live Preview](https://github.com/kiwphi/crispy-doom/tree/docs) of the new README.
- Trimmed readme and added links to various parts of the documentation (in the documentation section)
- Updated downloads section
- All documentation is now in the /docs folder. Github actions can be used to place these in the wiki.
- Deleted files that are strictly related to chocolate-doom, or that are obsolete. 

Note that the links in the readme are still linking to the /docs/*.md files since the updated wiki is not there yet

**Comment by rfomin** [comment]
> Note that the links in the readme are still linking to the /docs/*.md files since the updated wiki is not there yet

Will you create a pull request? Should I add a github action after merging into the main repo?

**Comment by kiwphi** [comment]
#1050

**Comment by rfomin** [comment]
> edit: it seems like i broke the man-page generator in man/

I think the problem is in `docgen` which converts Chocolate Doom documents from `.md` to `.html`. Maybe we should keep some of them, for example, about music or IWAD.

**Comment by kiwphi** [comment]
what about discarding the man pages, if they're not being updated and kept synchronized with crispy's changes? i think that a small number of docs that are regularly updated and tailored for crispy would be better than having docs all around, most of them being dragged from upstream

**Comment by rfomin** [comment]
man pages are generated from C code, they are fine. The problem is the Choco documents from the root that you deleted. I think we need to ask @fabiangreffrath what to do with them. After that I'll fix the build system.

**Comment by fabiangreffrath** [comment]
I would like to keep the original Chocolate documentation. Doesn't matter if they are outdated or irrelevant or not.

**Comment by kiwphi** [comment]
#1053 #1054 by @rfomin 

Thank you! I'll now implement automatic fetching in the website
