### ISSUE TITLE
e1m3 crashes when trying to loop roland sc-55 flac music

### ISSUE THREAD

**Issue by HardDiskDog** [fabiangreffrath/crispy-doom#1049]
### Background

Version of Crispy Doom:
6.0
Operating System and version:
Windows 11 22H2
Game: (Doom/Heretic/Hexen/Strife/other)
The Ultimate Doom
Any loaded WADs and mods (please include full command line):
doom.wad, roland sc-55 flac music pack from duke4.net
### Bug description
e1m3 crashes right after the music track finishes playing and is about to start another loop. this only happens when using the roland sc-55 flac music pack from duke4.net. it does not happen with the duke4 ogg music, nor midi/no music. both of these were the "boosted" versions of the packs; i haven't had time to test the non-boosted ones
Observed behavior:
same as bug description
Expected behavior:
gameplay continues uninterrupted as normal

**Comment by rfomin** [comment]
Looks like SDL_Mixer bug, I created an issue: https://github.com/libsdl-org/SDL_mixer/issues/511

**Comment by fabiangreffrath** [comment]
Not our bug.
