### ISSUE TITLE
Avoid using Dehacked for customizing/colorizing strings

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#105]
When trying to connect Choco and Crispy for network games, a warning is currently emitted because the Dehacked footprints of both engines differ. Crispy uses Dehacked to insert color-changing markers into some strings -- so while this warning is true, the Dehacked modifications that trigger it are completely harmless. Anyway, it would be preferable if Crispy would not need to use Dehacked for these modifications, so maybe someone has a nicer idea how to fix this.

This isn't necessarily a release goal for the next version, but certainly a nice-to-have.

**Comment by plumsinus** [comment]
Whether or not Dehacked gets replaced, I've come across a (somewhat) more serious problem. It seems Crispy's colouring takes precedence over external Dehacked, so key messages don't get replaced. See MAP05 of [kuchitsu](https://www.doomworld.com/idgames/levels/doom2/Ports/j-l/kuchitsu): just head straight and you'll see a green door to your right.

I guess one advantage of using Dehacked in this case is that someone could encode colour codes in their message strings, though I imagine it would have to be Crispy specific. 

Actually it would be really neat if Crispy could somehow colourize strings properly for recoloured keys/doors etc. I'll open a new issue if you think it's not too outlandish a request.

**Comment by fabiangreffrath** [comment]
I have applied an interim fix for this, thank you!

**Comment by Zodomaniac** [comment]
Further fix can be to colorize some more names of common basic colors: green, cyan and magenta upon detecting those names in the string (except for the text screens between chapters).

**Comment by fabiangreffrath** [comment]
Na, I cannot check any string for random color names. It is bad enough that I will have to colorize them on-the-fly now, if the Dehacked approach really confirms to be inappropriate, but checking one string for the occurrence of more than one color string is out of the question.

Also, there is only a limited number of color conversion tables prepared: red, green, blue, yellow/gold and grey. There is no such table for cyan or magenta or whatever. Is there even a single shade of cyan in Doom's palette? I think there a about three shades of "magenta", which is why Demons turn brown/grey in darker areas. Doesn't sound really colorful. ;)

**Comment by fabiangreffrath** [comment]
> checking one string for the occurrence of more than one color string is out of the question.

I forgot to mention that this is not because I don't feel like it. It is because string operations are always costly performance killers that need to be avoided whenever possible.

**Comment by fabiangreffrath** [comment]
Sorry guys, please read the commit message to 
https://github.com/fabiangreffrath/crispy-doom/commit/dd971b37fcc42ba20e6e8121df72e0120b7b2ef2

**Comment by plumsinus** [comment]
Hey, fine with me. I agree that not being dehacked-clean is pretty harmless.

**Comment by plumsinus** [comment]
I guess my only concern is that *you* are OK with this:

>I think we have to accept the fact that Crispy Doom by now has deviated quite a bit from Choco, even "under the hood".

I know small open-source projects can get abandoned if the project strays too far from what the developer actually wants for themselves, by taking on too many feature requests etc. It doesn't sound like this is the case with Crispy Doom, as far as I know, but I would hate for you to lose motivation on this project because it has gradually headed in a direction you didn't want it to go.

As a user I'm very happy with what Crispy Doom has turned into. It's definitely been my port of choice for some time now. 

And speaking of which, I'd still like to take on Crispy Heretic/Hexen at some point -- likely after the SDL2 changes are finalized, since I'm not quite ready to do it yet because of other obligations etc. and I figure waiting until the SDL2 branch is complete will probably make for a less disruptive process. (If I'm wrong about this, please say so!)

**Comment by Zodomaniac** [comment]
I wonder how the behavior after the current fix differs from the interim fix and why the interim fix was dumped)
The green key string color is still unsupported in that <a href="https://www.doomworld.com/idgames/levels/doom2/Ports/j-l/kuchitsu">kuchitsu</a>, the message for the green key is still fully red.

**Comment by plumsinus** [comment]
>The green key string color is still unsupported in that kuchitsu, the message for the green key is still fully red.
Yes, that is unlikely to change any time soon if ever. The more critical thing is that the message no longer references a yellow key.

**Comment by fabiangreffrath** [comment]
> I wonder how the behavior after the current fix differs from the interim fix and why the interim fix was dumped)

There seems to be a misunderstanding. The interim fix has been commited to the master branch and is most likely the final fix for this issue (at least until after the next release). The other fix with the long commit message was commited to a separate branch, because I want to keep it as a reference if I ever need this code. It changes the strings on-the-fly instead of hard-coding them once at engine start.

> The green key string color is still unsupported in that kuchitsu, the message for the green key is still fully red.

Yes, I only colorize the word "blue" in blue in strings in which I may reasonably expect the string "blue" to appear. I am not going to search and replace through all the possible strings for all the possible colors.

**Comment by fabiangreffrath** [comment]
> I guess my only concern is that you are OK with this:

Thank you for your concerns!

Yes, I am OK with this. I just had to realize that I had a problem with admitting the magnitude of changes that have accumulated in Crispy (most of them are really detail changes, but a thousand of them are still quite a mass). But all of these changes are there for a reason and I am not going to hide them just to make it look like there weren't any.
