### ISSUE TITLE
Option to choose between HSV and index-based blood recoloring

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#1052]
In our discussion with @JNechaevsky JN mentioned the fact that e.g. in KDiKDiZD blood color translation is awful because of the shifted palette and added that HSV-based recoloring, like the algorithm used for HUD, does that better (but at the price of entirely blue/green crushed corpses).

I think there should be a 'Blood coloring method' Crispness menu item that:
- won't toggle and have None value if Colored Blood is off
- can be switched between Index-based and HSV if Colored blood is on
(the way the 'Playback timer direction' option works depending on 'Show demo timer' setting).

**Comment by fabiangreffrath** [comment]
I guess everything would be better if we would allow to override to `green2red` and `blue2red` table with actual `crgreen` and `crblue` lumps from a PWAD, right?

**Comment by SoDOOManiac** [comment]
My suggestion is to make a new menu item:
Blood coloring:
'None' if colored blood is off
'Tables' by default, using `CRBLUE` and `CRGREEN` lumps or, in absence of those, hardcoded translation tables
'HSV' for those who prefer green-only and blue-only crushed corpses

**Comment by fabiangreffrath** [comment]
Nope. Users shouldn't even have to care about technical details like this.

**Comment by SoDOOManiac** [comment]
> Nope. Users shouldn't even have to care about technical details like this.

OK, then I just suggest a check for CRBLUE CRBLUE2 (IIRC) and CRGREEN lumps.
