### ISSUE TITLE
Game Controller (Xbox 360 And Clones) Triggers And D-Pad Don't Work In The "Button" Part Of Config

### ISSUE THREAD

**Issue by EmeraldTuxedo56** [fabiangreffrath/crispy-doom#1068]
### Background

Version of Crispy Doom: 6.0

Operating System and version: Windows 10, Windows 11

Game: N/A

Any loaded WADs and mods (please include full command line): N/A

### Bug description

Observed behavior: Cant Bind Triggers To Attack Or Use In Config

Expected behavior: Being Able To Bind Triggers To Attack And Use In Config

**Comment by fabiangreffrath** [comment]
I'm glad to tell you that Crispy has merged the "modern game controller support" feature branch from Choco. 

https://github.com/fabiangreffrath/crispy-doom/commit/6c38ffbaee9e9051e13832d8844ff841112e9fa0
