### ISSUE TITLE
Detect expansion packs more reliably than by name

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#107]
If that WAD has the map names as the inter-level screens show: The Earth Base, Pain Labs etc.
please make'em appear in the map screen the same as you did for Romero's recent additions to E1 :)

**Comment by fabiangreffrath** [comment]
NERVE.WAD is not a collection of non-consecutive, single maps, it's `pack_nerve`. It has correct map names, music and par times since Crispy Doom 1.0. Or is there anything I have missed?

**Comment by Zodomaniac** [comment]
Well, for me the map names in Nerve are the same: Entryway, Underhalls...and the music is standard DOOM2.

**Comment by plumsinus** [comment]
Confirming that nerve.wad works properly for me, using `crispy-doom.exe -file nerve.wad`. 

How are you running it, Zodomaniac?

**Comment by Zodomaniac** [comment]
Aha, I've found what the matter was! The file I downloaded had a different name, NoRestForTheLiving.wad. After renaming it to nerve.wad it shows proper map names :)

**Comment by fabiangreffrath** [comment]
Right. The NRFTL episode is currently recognized by its file name, i.e. NERVE.WAD. The NERVE.WAD PWAD contains only 9 maps and 9 intermissions screen map name lumps -- nothing else that is unique enough to distinguish it from other PWADs by content. So I have to rely on the PWAD name and thus NRFTL.WAD or anything else won't work?

What else could I do? I could introduce a check based on the checksum (MD5 or whatever) of that file. But you know what happens then? The next guy adds a single lump to the PWAD, e.g. a MAPINFO for ZDoom or a DEHACKED patch for Choco, and the checksum changes, though the other content of the PWAD is exactly the same. So this is also error-prone. :/

**Comment by fabiangreffrath** [comment]
This is one such example: https://web.archive.org/web/20141218080706/http://visionsofdoom.us/

**Comment by plumsinus** [comment]
I guess you could verify checksums of particular lumps inside the wad? I imagine you'd have to check several of them in a single wad to be sure.

**Comment by fabiangreffrath** [comment]
That doesn't sound like fun. I don't *want* to do this. :/

**Comment by plumsinus** [comment]
>That doesn't sound like fun. 

No it doesn't. Maybe implementing a file checksum, in addition to checking the name, and enabling pack_nerve if either match is good enough then.

**Comment by fabiangreffrath** [comment]
Hm, I am not sure if I am really going to support pirated and/or renamed copies of official IWADs. The only way to get a legal copy of NERVE.WAD is to buy the Doom 3 BFG Edition -- and there it is called NERVE.WAD. Whoever renames it to NRFTL.WAD or whatever.WAD or adds or removes lumps from it is going to lose full support in the engine. Or is this too narrow-minded?

**Comment by plumsinus** [comment]
>Or is this too narrow-minded?

No that's probably fair. Especially given the difficulty in properly detecting nerve.wad if it's been modified. 

Maybe you should add something like the italicized text to the Crispy Doom page:

>Full support for the "Doom Classic" WADs shipped with the "Doom 3: BFG Edition", especially the "No Rest For The Living" episode shipped in the NERVE.WAD file. *(This file must be named NERVE.WAD for proper functionality.)*

**Comment by fabiangreffrath** [comment]
I don't even think that this should be necessary. I mean, do I have to stress that you should not rename DOOM2.WAD to thisismyfavoritegame.wad in order for it to work correctly? I am a bit too strict here, I know, but sometimes I wonder what people think is supposed to work. ;)

**Comment by plumsinus** [comment]
Actually I think `crispy-doom.exe -iwad thisismyfavoritegame.wad` seems to work just fine ;)

But no, I see your point.

**Comment by Zodomaniac** [comment]
> Actually I think crispy-doom.exe -iwad thisismyfavoritegame.wad works just fine ;)

So do I. Fabian, I deem you can just leave the wad detection by name as it is.
Nice fixes of other issues, btw, thanks a lot) looking forward to playing some episodes in Crispy 3.4 with the music pack and real instrumental music)

**Comment by fabiangreffrath** [comment]
Thank you guys. So, if you both agree that WAD detection by file name should be fine, I will just close this issue until further discussion should become necessary.
