### ISSUE TITLE
Did crispy-doom 6.0 get re-tagged

### ISSUE THREAD

**Issue by chenrui333** [fabiangreffrath/crispy-doom#1073]
Per this PR update, there is [some checksum mismatch](https://github.com/Homebrew/homebrew-core/pull/133716) with 6.0 release. Raise this issue to double confirm if that is intended. Thanks!

**Comment by chenrui333** [comment]
cc @rfomin @fabiangreffrath

**Comment by fabiangreffrath** [comment]
This was the reason, CI wasn't triggered to build the release artifacts:
https://github.com/fabiangreffrath/crispy-doom/commit/593f5b97023ed39b7640073160c06895bbfc3d26

**Comment by chenrui333** [comment]
I see, thanks for confirming it.
