### ISSUE TITLE
Corners in MAP18 severe rendering bug

### ISSUE THREAD

**Issue by Scattershor** [fabiangreffrath/crispy-doom#1078]
### Background

Version of Crispy Doom: 6.0.0

Operating System and version: Windows 10 22H2

Game: Doom 2

Any loaded WADs and mods (please include full command line): crispy-doom.exe -iwad DOOM2.WAD

### Bug description

Observed behavior: Rendering bug on corners in DOOM2 level MAP18 showing last displayed elements.

Expected behavior: Corner should be complete and not buggy like this. 

![Screenshot (171)](https://github.com/fabiangreffrath/crispy-doom/assets/58623117/197c5b5c-4ed0-4af1-9b9c-addeb39d6d67)
![Screenshot (172)](https://github.com/fabiangreffrath/crispy-doom/assets/58623117/253b81b6-497c-4641-9db3-890d46c898f5)
![Screenshot (173)](https://github.com/fabiangreffrath/crispy-doom/assets/58623117/c0bf18f7-1120-4393-9650-b98be04597ad)
![Screenshot (174)](https://github.com/fabiangreffrath/crispy-doom/assets/58623117/0542a02e-8e72-42a3-b15c-120fe3c4f51c)
![Screenshot (175)](https://github.com/fabiangreffrath/crispy-doom/assets/58623117/160ac51c-3510-4d3c-b869-0e0ce27f38d2)
![Screenshot (177)](https://github.com/fabiangreffrath/crispy-doom/assets/58623117/2b0d94fd-3df6-41ab-93d1-0c56dcaff696)
![Screenshot (178)](https://github.com/fabiangreffrath/crispy-doom/assets/58623117/af777d5a-06f3-4680-81d6-5b4dad3d43f9)

**Comment by fabiangreffrath** [comment]
That's a mapping error. The lines you see in sector 15 are two-sided, but have no backsector.
