### ISSUE TITLE
[Suggestion] Add MIDI soundfont gain setting.

### ISSUE THREAD

**Issue by Vitoria90** [fabiangreffrath/crispy-doom#1087]
Hello. As someone who likes using custom soundfonts, I often find them to be really quiet or really loud, in a way that the music volume control can't compensate for all the time.
Both DSDADoom and GZDoom have gain settings for their MIDI playback (GZDoom in its menus, DSDADoom only in its .cfg file) that really help compensate for that. The gain setting could go both ways to help make quiet fonts louder and loud fonts quieter. 
Thanks for your time in advance.

**Comment by fabiangreffrath** [comment]
This should be possible for the native fluidsynth backend. It will have to get solved in Chocolate Doom first. I'll see what I can do.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/bd7be2212c4c0520cd6e5721a0d0cae32eb09c24
