### ISSUE TITLE
Stadia Controller Support

### ISSUE THREAD

**Issue by SecularSteve** [fabiangreffrath/crispy-doom#1089]
### Background

Version of Crispy Doom:

6.0.0

Operating System and version:

Raspberry Pi OS (latest)

Game: Doom

Any loaded WADs and mods (please include full command line):

freedoom.iwad
freedoom2.iwad
freedm.iwad

### Bug description

Stadia Controller (Bluetooth Mode) doesn't seem to be supported.

Observed behavior:

Won't detect it in the setup menu.

Expected behavior:

To detect it.
Do I need to use a xinput wrapper as a workaround?

**Comment by turol** [comment]
You need to configure your controller with SDL2. Try this: https://old.reddit.com/r/Stadia/comments/10muihx/linux_map_the_bluetooth_stadia_controller_to_sdl2/
