### ISSUE TITLE
Sigil 2 Support

### ISSUE THREAD

**Issue by Enator18** [fabiangreffrath/crispy-doom#1090]
Sigil 2 is going to release December of this year, and it’s gonna be an Episode 6 wad. Would it be possible to add it to the side loading system before it comes out so it can be played that way right when it comes out?

**Comment by SoDOOManiac** [comment]
Cool, with 6 episodes the VR-EKKR episode of REKKR: Sunken Land would also be playable in Crispy!

**Comment by OpenRift412** [comment]
I thought Sigil 2 was going to be for Doom II?

**Comment by Enator18** [comment]
It was originally going to be for doom 2 but then Romero decided to make the doom 2 thing a separate thing and started a new sigil 2 that is doom 1 episode 6

**Comment by fabiangreffrath** [comment]
I have to say, I am absolutely *not* looking forward to hard-coding another non-Vanilla episode into the engine. Why can't Mr. Romero just release a PWAD as everybody else does?

**Comment by Enator18** [comment]
> I have to say, I am absolutely _not_ looking forward to hard-coding another non-Vanilla episode into the engine. Why can't Mr. Romero just release a PWAD as everybody else does?

Idk man. he tests his stuff with gzdoom which supports extra episodes without modification so maybe he just thinks everybody will use that. :/ also he makes the compat version, but it’s kinda nice to be able to have the extra episode and have the intermission music only play in that one.

**Comment by NightFright2k19** [comment]
Anyway, it's out now. Map slots E6M1-E6M9 are a thing now.

**Comment by fabiangreffrath** [comment]
Yay! And yet again, Sigil 2 confronts us with sloppy design decisions (like e.g. aspect ratio squashed textures and a non-tiling sky) and an AAA marketing campagn. While it is meant to integrate seamlessly into the Doom 1 Episode menu, it includes DEHACKED modifications which introduce incompatibilities with every other mod including... Sigil 1. 😮 

Sorry guys, but there are so many better maps available without multi-hundred dollar packaging that don't require me to rewrite the engine. If you want to give a go with it, I'll be glad to review PRs - but not me this time.

**Comment by JNechaevsky** [comment]
You can try out my unofficial compat version, an replacement for episode 1 to make exit from secret level working as it should. There are no compatibility dogshit, it will work fine in Crispy Doom and/or any limit-removing source port with simple Dehacked support:

- https://drive.google.com/drive/folders/1FNjwyZT46y80SuKh5FVSS810gKg383kG?usp=sharing

**Comment by Bubbabyte** [comment]
> You can try out my unofficial compat version, an replacement for episode 1 to make exit from secret level working as it should. There are no compatibility dogshit, it will work fine in Crispy Doom and/or any limit-removing source port with simple Dehacked support:
> 
> * https://drive.google.com/drive/folders/1FNjwyZT46y80SuKh5FVSS810gKg383kG?usp=sharing

Can you repost your Sigil II Compat WAD?

**Comment by JNechaevsky** [comment]
I'm afraid I don't have that PWAD left. I deleted it shortly after the Sigil II support implementation from Michael.
