### ISSUE TITLE
Crispy squashes tall skies with mouselook on

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#1092]
The options for mouselook stretch short skies as is to be expected, however they also needlessly squash taller skies (presumably those taller than SKYSTRETCH_HEIGHT).

What the "correct" way to display a tall sky is, regarding vertical positioning, is up for debate: Woof, DSDA-Doom, and GZDoom all behave differently, with further differences in the last two depending on software/hardware rendering. But not scaling the sky would be a good start. (IMO Woof is the most accurate in regards to expected behaviour, maybe I'll start a thread on DoomWorld in the near future to solicit opinions.)

Example file, uses a 256px tall sky on MAP01 and a 384px tall sky on MAP12, made from Icon of Sin textures.
[bigsky.wad.zip](https://github.com/fabiangreffrath/crispy-doom/files/12443597/bigsky.wad.zip)

MAP 12 with mouselook off, no stretching:
![DOOM0003](https://github.com/fabiangreffrath/crispy-doom/assets/47063032/1aec7291-30e0-47d4-930d-278e621796fe)

MAP12 with mouselook on, the sky is squashed:
![DOOM0002](https://github.com/fabiangreffrath/crispy-doom/assets/47063032/41adfc9f-a18c-49b3-bedd-fd3f9fc2dcd1)

**Comment by fabiangreffrath** [comment]
I'll try to adapt the Woof solution to Crispy.

**Comment by kitchen-ace** [comment]
Woof does have its own problems with skies, mainly related to scrolling, I'll try to make an issue about that today.

Tall skies are a huge inconsistent mess across ports :(

**Comment by fabiangreffrath** [comment]
> Woof does have its own problems with skies, mainly related to scrolling, I'll try to make an issue about that today.

Thanks for the report, though that's a very different issue to the one discussed here.

**Comment by kitchen-ace** [comment]
Of course, just didn't know how much sky handling code might be intertwined.
