### ISSUE TITLE
New textures not loading in sci2023.wad

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#1093]
https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/sci2023

see discussion at https://www.doomworld.com/forum/post/2691364

Other ports load the textures fine, and Chocolate does as well if you use -merge.

~~I suspect something is weird with the TEXTURE1/PNAMES entries but I'm not sure what. Crispy gives me a bunch of R_GenerateLookup errors related to textures that are shorter in the wad than in Doom 2, but even fixing these the other textures don't load properly.~~ see next comment

```
R_GenerateLookup: column without a patch (BLODRIP1)
R_GenerateLookup: column without a patch (BLODRIP2)
R_GenerateLookup: column without a patch (BLODRIP3)
R_GenerateLookup: column without a patch (BLODRIP4)
R_GenerateLookup: column without a patch (BROWN1)
R_GenerateLookup: column without a patch (BROWNGRN)
R_GenerateLookup: column without a patch (CEMENT5)
R_GenerateLookup: column without a patch (GSTFONT1)
R_GenerateLookup: column without a patch (GSTFONT2)
R_GenerateLookup: column without a patch (GSTFONT3)
R_GenerateLookup: column without a patch (ZZWOLF7)

```

**Comment by kitchen-ace** [comment]
I think it's an issue with the patch markers -- deleting all Px_START/Px_END and Fx_START/Fx_END markers in the wad fixes the problem.

**Comment by fabiangreffrath** [comment]
I think the clulprit is that a flat section in the lump progression that is introduced with a `F_START` marker can be closed by a `FF_END` marker. There is currently no way to detect "nested" sections in `w_merge.c:DoMerge()`.

**Comment by fabiangreffrath** [comment]
Nope. It rather seems that the texture reference some patches which are between the FLAT markers and are thus sorted out by this code:

https://github.com/fabiangreffrath/crispy-doom/blob/8b40be0178fee595eaa836b42c6f731cbfcbc905/src/doom/r_data.c#L812-L820

**Comment by kitchen-ace** [comment]
> It rather seems that the texture reference some patches which are between the FLAT markers

Hmm, so I think something about FF_END being present is causing Crispy to include all the new patches and other lumps (presumably everything up to F_START in the IWAD) as being within the flat list -- if you move the whole flat section of sci2023 to the top of the wad, everything loads as it should.
