### ISSUE TITLE
Load doom/doom2.wad autoload folder AFTER sigil/masterlevels/nerve.wad to prevent TITLEPIC conflicts

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/crispy-doom#1094]
Just a small suggestion for autoload prioritization. If nerve.wad and/or masterlevels.wad is present next to Crispy's EXE, have it load the contents of the doom2.wad autoload folder last, that way Doom II's titlepic isn't overridden.

EDIT: Also a similar case for Ultimate Doom and Sigil, as it loads Sigil's autoload folder after Doom's.

**Comment by NightFright2k19** [comment]
I don't get this request. Both nerve.wad and masterlevels.wad are addons, loaded after doom2.wad. so naturally, they also need to be second in the autoload order. Same with Sigil 1+2 and doom.wad. Anything makes no sense, tbh.

**Comment by mikeday0** [comment]
@OpenRift412 If you don't mind can you test the artifact associated with [2eadcbe](https://github.com/fabiangreffrath/crispy-doom/commit/2eadcbe3df1664dc76e0dffa1bdff9b448278ccd)? I think this will resolve your issue. Thanks!

**Comment by OpenRift412** [comment]
> @OpenRift412 If you don't mind can you test the artifact associated with [2eadcbe](https://github.com/fabiangreffrath/crispy-doom/commit/2eadcbe3df1664dc76e0dffa1bdff9b448278ccd)? I think this will resolve your issue. Thanks!

Could you send me a compiled build?

**Comment by mikeday0** [comment]
Sure, here are links to the Windows artifacts:
[64-bit](https://github.com/fabiangreffrath/crispy-doom/actions/runs/7655738486/artifacts/1194945220)
[32-bit](https://github.com/fabiangreffrath/crispy-doom/actions/runs/7655738486/artifacts/1194945217)

**Comment by OpenRift412** [comment]
> Sure, here are links to the Windows artifacts: [64-bit](https://github.com/fabiangreffrath/crispy-doom/actions/runs/7655738486/artifacts/1194945220) [32-bit](https://github.com/fabiangreffrath/crispy-doom/actions/runs/7655738486/artifacts/1194945217)

Tested with Nerve, Master Levels, and Sigil 1 and 2 and it works perfectly! Thanks!
