### ISSUE TITLE
Unity-Style Master Levels Selection Screen

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/crispy-doom#1095]
I think given the rather confusing and convoluted nature of combining the Master Levels for Doom II into a single WAD, I think it would be a nice thing to have a level selector for the various Master Levels PWADs instead, akin to what the Unity port and the Eternity Engine do. 

How this would work is that Crispy would look in either its main folder or a \master subfolder to find the Master Levels PWADs and if all are detected, then provide an option in the episode select menu that brings you to a level select screen. 

I don't know if this is out of the port's scope or not, but I thought I might as well suggest it anyway.

**Comment by fabiangreffrath** [comment]
Well, what it already does is loading all separate masterlevel PWADs and combine them into a Masterlevels episode internally, based on the level progression of the PSN release. From there, each level is only a IDCLEV away.

**Comment by OpenRift412** [comment]
> Well, what it already does is loading all separate masterlevel PWADs and combine them into a Masterlevels episode internally, based on the level progression of the PSN release. From there, each level is only a IDCLEV away.

Huh, I didn't know that. Does it have to be all in the main folder or can it be put in a subfolder?

**Comment by mikeday0** [comment]
What I do is put all of the Master Levels wads in a single directory, and then add that directory to the $DOOMWADPATH environment variable. ($DOOMWADPATH is very useful as it can store a list of paths, not just one) Crispy Doom (and most other source ports) support $DOOMWADPATH.

**Comment by fabiangreffrath** [comment]
Since a solution has been presented and I am not going to add file management capabilities to Crispy, I'll close this issue.
