### ISSUE TITLE
Some brightmaps may need improvement

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#1096]
### Background

Version of Crispy Doom: latest git

Operating System and version: Win 10

Game: Doom 2

Any loaded WADs and mods (please include full command line): crispy-doom.exe -merge boomer.wad
https://www.doomworld.com/forum/topic/133495-doom2-limit-removing-boomer-beyond-vanilla-%E2%80%94-actionadventureexploration-focused-wad-v00704-2023-06-26/

### Bug description

Observed behavior: with Brightmaps enabled for Walls or Both, the red indicator in this texture is always on and doesn't blink
![DOOM0022](https://github.com/fabiangreffrath/crispy-doom/assets/15119473/5dd3becf-7043-4a6a-ba75-723dacbba570)

Expected behavior: the red indicator should blink with walls or all brightmaps on.

**Comment by JNechaevsky** [comment]
If you'll take a careful look behind the texture, you'll see that there is no "red" indicator, it's hole to switch texture which is lit by `redonly` brightmap.

![image](https://github.com/fabiangreffrath/crispy-doom/assets/21193394/9f3db70f-a9fc-4460-90be-22849e905f9b)

**Comment by SoDOOManiac** [comment]
@JNechaevsky, I just looked that up in Doom Builder, thanks :)
Will probably get myself Ultimate Doom Builder that you're using :)
