### ISSUE TITLE
XBOX360 pad triggers can't be selected on crispy-setup

### ISSUE THREAD

**Issue by vanfanel** [fabiangreffrath/crispy-doom#1098]
### Background

Version of Crispy Doom: 6.0 Stable

Operating System and version: Debian 12 Stable

Game: (Doom/Heretic/Hexen/Strife/other) All

Any loaded WADs and mods (please include full command line): None

### Bug description

Observed behavior: crispy-setup doesn't detect triggers on XBOX360 gamepads.

Expected behavior: crispy-setup should let the user select the triggers for FIRE action, since that's how they are used on modern shooter control schemes those pads are designed for.

**Comment by fabiangreffrath** [comment]
I'm glad to tell you that Crispy has merged the "modern game controller support" feature branch from Choco. 

https://github.com/fabiangreffrath/crispy-doom/commit/6c38ffbaee9e9051e13832d8844ff841112e9fa0

**Comment by vanfanel** [comment]
Ah! Great! Going git code version then! Thanks! :D
