### ISSUE TITLE
Make sure to show the proper episode names in the Doom 2 New Game menu

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#110]
Selecting 1st episode launches the standard campaign, and selecting 2nd one launches Nerve, the behavior is quite good but episode names are incorrect.
Would be nice to introduce proper episode names: 'Hell on Earth' and 'No Rest for the Living', and maybe do the same in Choco (it doesn't have support for Nerve map names and music yet).

**Comment by fabiangreffrath** [comment]
This is because the Doom 1 menu lumps are still present in the Doom 2 IWAD. Sigh...

**Comment by fabiangreffrath** [comment]
In the Doom 2 IWAD shipped with the BFG Edition, these graphics have been fixed to show the correct episode names, but in the standard Doom 2 IWAD, they still show the Doom 1 episode names.

**Comment by fabiangreffrath** [comment]
The logic seems to be like this: "If the lumps are available and they are from the IWAD, this IWAD must be DOOM2.WAD from the BFG Edition, else they must be from a PWAD". What a mess!

I think I am going to revert the change that relaxed the check for the BFG Edition. The only legal way to obtain NERVE.WAD is to buy the BFG Edition, anyway.
