### ISSUE TITLE
Implement a Visual option for selective fuzz darkening 

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#1100]
See Linguica's post with the reasoning that the original fuzz algorithm is bugged and the illustration how it looks before and after the fix
https://www.doomworld.com/forum/post/1335769

**Comment by fabiangreffrath** [comment]
It's not "bugged", it's the *original implementation*. Everything that looks different from that is a deviation from Vanilla, and if that looks better or worse is highly subjective.

**Comment by SoDOOManiac** [comment]
> It's not "bugged", it's the *original implementation*. Everything that looks different from that is a deviation from Vanilla, and if that looks better or worse is highly subjective.

Anyway, what do you think of introducing the option for switching between two different fuzz algorithms?

**Comment by SoDOOManiac** [comment]
There is room in Visual menu for this "Invisibility fuzz" setting with "Vanilla" (default, 0) or "Advanced" (1) values, with the variable name like crispy->fuzzfix.

**Comment by SoDOOManiac** [comment]
Ok, it will be another So Doom-exclusive option then :)

**Comment by JNechaevsky** [comment]
You can also experiment with fuzz drawing by making it less "patterned", i.e. drawing it not by using table driven approach, but with safe `M_Random()` or `Crispy_Random()` functions. In short words: _"random approach will make fuzz effect less drawing-scene dependent"_. Or, draw such sprites with translucency. Here's my examples: [random](https://github.com/JNechaevsky/international-doom/blob/main/src/doom/r_draw.c#L353-L356) and [translucent](https://github.com/JNechaevsky/international-doom/blob/main/src/doom/r_things.c#L441-L454).

But again, it's very subjective feature.
