### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RX7FC3SGTX** [fabiangreffrath/crispy-doom#1102]
Version of Crispy Doom: 6.0.0

Operating System and version: Windows 7 SP 1

Game: Heretic

### Bug description

https://clips.twitch.tv/CarelessObliqueAppleImGlitch-NagMWR9fm5UAonvb

**Comment by fabiangreffrath** [comment]
Could you provide a demo to reproduce this?

**Comment by RX7FC3SGTX** [comment]
No, it's just casual play and i don't even have saves, just entered level with "engage". Literally nothing special happened, don't have any clues why it's crashed.

**Comment by mikeday0** [comment]
Is this repeatable? If so, what are the steps to reproduce it?

**Comment by RX7FC3SGTX** [comment]
Music is ogg roland sc-55 pack, you can see steps to reproduce it in this clip, you can try to do same thing and get crash, but again there is nothing special and everyone will do same, you must stand close to this wall to trigger it. I don't know repeatable or not i changed version back to 5.9.2 and completed level without problems.

**Comment by fabiangreffrath** [comment]
I could not reproduce with the latest GIT head. I used the KITTY cheat to get there, though.

**Comment by fabiangreffrath** [comment]
Just timedemo'd h4f31416.lmp and h4m3-938.lmp without any issues. Is this probably a bug in the 12.0 release?

**Comment by mikeday0** [comment]
I was no able to reproduce this either on 6.0.0. I played through the level several times without any issues. I will try some demos tonight.

**Comment by fabiangreffrath** [comment]
Has anybody been able to reproduce this crash?

**Comment by ceski-1** [comment]
I could not reproduce this on both Windows 7 (VM only) and Windows 10. I used the SC-55 ogg pack as well.

**Comment by synthic** [comment]
I just opened a new issue but I see I am having a similar crash just playing regular Doom on Windows 7.

**Comment by fabiangreffrath** [comment]
Unreproducible.
