### ISSUE TITLE
add an option for 426x200 for compatibility

### ISSUE THREAD

**Issue by Swim-Swim-Hungry** [fabiangreffrath/crispy-doom#1110]
some wads come with 426x200 graphics and if it has a custom palette (new vanilla harmony) it has the side effect of that annoying border (that is not black)

**Comment by mikeday0** [comment]
Works fine for me! I'm guessing that you forgot to also load `Extras/Harm-WS.wad`?

With `Extras/Harm-WS.wad`:
![DOOM0015](https://github.com/fabiangreffrath/crispy-doom/assets/43701387/2f4fde9a-5a15-4dc8-ac08-b7b195375d7c)

Without:
![DOOM0012](https://github.com/fabiangreffrath/crispy-doom/assets/43701387/9fe8038d-e2bf-44c6-9187-a4e490bf101a)

**Comment by Swim-Swim-Hungry** [comment]
> Works fine for me! I'm guessing that you forgot to also load `Extras/Harm-WS.wad`?
> 
> With `Extras/Harm-WS.wad`: ![DOOM0015](https://user-images.githubusercontent.com/43701387/284002208-2f4fde9a-5a15-4dc8-ac08-b7b195375d7c.png)
> 
> Without: ![DOOM0012](https://user-images.githubusercontent.com/43701387/284002220-9fe8038d-e2bf-44c6-9187-a4e490bf101a.png)

me did do that, but my crispy renders 16:9 as 428x200

**Comment by mikeday0** [comment]
Do you have High Resolution Rendering set to "off"?

**Comment by Swim-Swim-Hungry** [comment]
> Do you have High Resolution Rendering set to "off"?

yes

**Comment by fabiangreffrath** [comment]
There is a reason for this exact resolution and it's explained here:

https://github.com/fabiangreffrath/woof/commit/405f6c7683baf2146115ab390e10134417f19df9

**Comment by mikeday0** [comment]
I suspect that the main complaint here is the gray pillarboxing due to the custom `PLAYPAL`. Should  we use `V_GetPaletteIndex()` to find black here?

**Comment by fabiangreffrath** [comment]
This sounds like a good idea. 👍

**Comment by fabiangreffrath** [comment]
Hm, I still fail to see what's wrong. 🤷
