### ISSUE TITLE
Potential crash with looping FLAC music

### ISSUE THREAD

**Issue by XxMiltenXx** [fabiangreffrath/crispy-doom#1132]
### Background

Version of Crispy Doom: 6.0 (both x32 and x64)

Operating System and version: Windows 11 x64

Game: Doom

Music Packs

#### Observed behavior:
Depending on the loop tags in a song, the music will crash upon trying to loop. In the d_runnin.flac (see Working [FLAC]), if the LOOP_START is set to 330750 and the LOOP_END is set to 7938000 (as is intended for this song), the song will loop just fine without crashing.
However, if I change the LOOP_END to 400000 (see Not Working [FLAC], it will crash upon trying to loop.
d_stalks will even crash with the intended loop points (LOOP_START 153391, LOOP_END 8129737).

If the files are OGG, they work just fine, regardless of how the LOOP_END is set. GZDoom also plays the FLAC files just fine.
I even tested if the FLACs itself are faulty and converted them from WAV with different programs (ffmpeg, Audacity) and compression levels (0, 5, 8), but the result is the same.

#### Files:
Not working [FLAC]: https://sc-d70.retrohost.net/test/nw/d_runnin.flac
Not working [FLAC]: https://sc-d70.retrohost.net/test/nw/d_stalks.flac
Working [FLAC]: https://sc-d70.retrohost.net/test/w/d_runnin.flac
Working [OGG]: https://sc-d70.retrohost.net/test/w/d_runnin.ogg
Working [OGG]: https://sc-d70.retrohost.net/test/w/d_stalks.ogg

### Additional Info
The isn't any error message, the game just freezes for a second, then shuts down.

**Comment by mikeday0** [comment]
Sorry for the trouble. This is a well-known issue with SDL Mixer. It has been fixed by that team some time ago but there hasn't been a new SDL Mixer release as of yet. (Supposed to be soon.) In the meantime, please use OGG as a workaround.
