### ISSUE TITLE
Heretic & Hexen: multipatch 2S midtex causes medusa

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#1146]
Looks like PR #861 was maybe meant to address this, but didn't actually fix it properly? In any case, multi-patch 2S midtextures cause the same problems they do in vanilla.

Test wad for Heretic and Hexen (contains both E1M1 and MAP01 entries), 2S linedefs are behind the player to not cause problems immediately on level load.
[raven_midtex.zip](https://github.com/fabiangreffrath/crispy-doom/files/14060125/raven_midtex.zip)

**Comment by JNechaevsky** [comment]
Drawing functions must be okay, but looks likes `R_DrawColumnInCache()`, `R_GenerateComposite()` and `R_GenerateLookup()` must be updated as well, just like in [Doom](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_data.c#L240-L242). After that, `R_GetColumnMod()` should be used [here](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/heretic/r_segs.c#L279).

**Comment by mikeday0** [comment]
Yep, my bad! I’ll take a look at it later today.

**Comment by mikeday0** [comment]
Almost there, just need to figure out why the medusa fixes break the sky texture:
![HTIC03](https://github.com/fabiangreffrath/crispy-doom/assets/43701387/fc47d730-437a-4b00-a0e2-3b11f4147a09)

**Comment by kitchen-ace** [comment]
Yeah Heretic skies are weird, the actual texture is 128px tall but the patch is 200px and they're special-cased to read the whole patch when used as a sky. Wouldn't be surprised if they need special handling.
