### ISSUE TITLE
Hexen: demos can desync when uncapped framerate is on

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#1147]
https://dsdarchive.com/files/demos/hexen/49452/se1f1236.zip

Recorded with "jHexen 0.99.6(se3)" so it's possible it's a malformed demo somehow. Nonetheless it works fine with uncapped framerate off, as well as in Chocolate and DSDA.

I get a desync at a different point depending on whether I have the framerate limit off or on. Even limiting it to 35 FPS still causes the desync. ~~Haven't experienced any desyncs from demos recorded in other ports (though I have only tested a few).~~ Nevermind, here's another one, recorded with DSDA-Doom: https://dsdarchive.com/files/demos/hexen/62317/hxAllf646.zip

**Comment by fabiangreffrath** [comment]
Out of the blue: could this be related to polyobj interpolation?

**Comment by mikeday0** [comment]
Is this issue on 6.0 as well?

**Comment by kitchen-ace** [comment]
>Out of the blue: could this be related to polyobj interpolation?

Seems unlikely to me, hxAllf646.lmp desyncs immediately after a teleport, the player fails to go far enough to reach the level exit.

>Is this issue on 6.0 as well?

Yes, AFAICT it's been an issue with every version of Crispy Hexen that has uncapped framerates.

**Comment by mikeday0** [comment]
> Out of the blue: could this be related to polyobj interpolation?

You are right. For reasons I don't fully understand, I can fix the desync by disabling interpolation of rotating polyobjects.

**Comment by fabiangreffrath** [comment]
I think the interpolation code changes the objects' actual coordinates during each *rendered* tic, instead of waiting for the next *calculated* tic and merely lerping in between.

**Comment by kitchen-ace** [comment]
Great work @mikeday0 and good intuition @fabiangreffrath !
