### ISSUE TITLE
No Music from Sigil Shreds wad nor Sigil 2 Shreds

### ISSUE THREAD

**Issue by Jenavieve-Rose** [fabiangreffrath/crispy-doom#1149]
So even with native midi selected I get no music playback when trying to load the sigil shred or sigil 2 shred wads. 

Version of Crispy Doom: 6.0 commit 5512899

Operating System and version: Windows 11  23H2

Game: (Doom/Heretic/Hexen/Strife/other) Doom 

Any loaded WADs and mods (please include full command line): "F:\OneDrive\Documents\Games\Sigil II\crispy-doom.exe" -file SIGIL2.WAD SIGIL2_SHREDS.wad

**Comment by mikeday0** [comment]
They work fine on my end. Did you download a build artifact from Github, or did you build Crispy yourself? The two Sigil replacement soundtracks are in MP3 format so I'm guessing something is up with the SDL_Mixer MP3 decoder.

**Comment by Jenavieve-Rose** [comment]
I was using from the nightly from https://latest.chocolate-doom.org/ but I deleted the whole folder and used an artifact here and it is working.

**Comment by mikeday0** [comment]
The nightly builds on chocolate-doom.org lack support for mp3s. Please try an artifact from Github. Here's the latest one: https://github.com/fabiangreffrath/crispy-doom/actions/runs/8000948565 Downloads are at the bottom.

**Comment by captwalsh** [comment]
Many thanks - it now works a treat😁
