### ISSUE TITLE
unclutter the "projected crosshair" code

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#115]
Crispy needs a "harmless" variant of P_SpawnMobj() that does not register its objects in the blockmap and does not call P_Random(). This way, it could be possible to render bullet puffs in outside areas and it could also potentially unclutter the "projected crosshair" code.

**Comment by Zodomaniac** [comment]
>unclutter the "projected crosshair" code

What do you mean?

**Comment by fabiangreffrath** [comment]
The projected crosshair code is a bit complicated, because I strictly had to avoid adding it as another mapthing. So, instead of spawning a map thing in `PTR_ShootTraverse()`, I simply set its coordinates there and then call a duplicate (booh!) of `R_DrawSprite()` called `R_DrawLSprite()` which renders the actual spot.

By being able to render a mapthing without its negative effects on demo compatibility, I could at least get rid of the `R_DrawLSprite()` function.

**Comment by fabiangreffrath** [comment]
Next stop: unclutter the "projected crosshair" code

**Comment by Zodomaniac** [comment]
>Next stop: unclutter the "projected crosshair" code

Does this commit fix it?
https://github.com/fabiangreffrath/crispy-doom/commit/cb3c0a1241b3914a70244af51b3b5ee8899fb96f

**Comment by fabiangreffrath** [comment]
Na, this was just some clean-up after I implemented the initial idea.

My plans for the crosshair are to convert it into a map object with the HU font '+' character as its single sprite that gets spawned at the calculated position with `P_SpawnMobjSafe()` and has a lifetime of 1 tic each.

**Comment by fabiangreffrath** [comment]
I had a shot at this last year, but wasn't satisfied with the results. The main reason is that hitscanner weapons are supposed to create the crosshair object at the intersection of the trajectory with the wall or sprite if its impact, whereas for missile weapons it is supposed to start at the weapon muzzle and follow the trajectory from there on. This makes a huge difference when hitting a floor or ceiling, and it is mostly impossible to properly implement this to get both cases right.

**Comment by fabiangreffrath** [comment]
I have a new idea for this...

**Comment by fabiangreffrath** [comment]
That is, create a static `mobj_t` object for the crosshair with an actual sprite and add this as a vissprite each tic, using existing Vanilla code exclusively.

**Comment by fabiangreffrath** [comment]
> using existing Vanilla code exclusively

*sigh* But this would mean that there must be an actual sprite for the crosshair object, in order to not fail this check: 
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_things.c#L608

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.
