### ISSUE TITLE
Broken Map Marker System

### ISSUE THREAD

**Issue by snekyo** [fabiangreffrath/crispy-doom#1158]
### Background

- `Crispy Version:` 6.0

- `OS and OS Version:` Microsoft Windows 10 Home
Version 10.0.19045 Build 19045

- `Game:` Crispy Heretic and Crispy Hexen (I don't use Crispy DOOM, but seeing as those two are modifications of it, it's possible that the same issue is in Crispy DOOM.)

- `Command Line:`
(Added to library with 'non-steam game' system, command line text placed into launch options)
Heretic: `-iwad "E:\Program Files\DOOMery\officialwads\HERETIC.WAD" -extraconfig "E:\Program Files\DOOMery\crispyHeretic\crispy-heretic.CFG"`
Hexen: `-iwad "E:\Program Files\DOOMery\officialwads\HEXEN.WAD" -extraconfig "E:\Program Files\DOOMery\crispyHexen\crispy-hexen.CFG"`

### Bug description

`Observed behavior:` After binding keys for marking spots on the map, they simply don't get placed. The keys I use for this are _number pad 1_ for placing a marker, and _number pad 3_ for removing markers.

`Expected behavior:` I'd expect these bindings to place and remove markers.

`P.S.`
Anybody know how to add labels, assignees, and any of those other side values?

**Comment by JNechaevsky** [comment]
It's not exactly a bug. Setup executable shows _mostly_ common binds for all four games, but Heretic and Hexen simply doesn't have mark drawing functions, neither vanilla games nor Crispy.

Implementation for both games is not that hard, and the result will be looks likes this ([screenshot](https://github.com/fabiangreffrath/crispy-doom/assets/21193394/a5fb3d25-eb52-4e82-bf4a-43fa5a72ed6c)). Drawing functions is fairly simple, marks could use small numbers from status bar (`PU_STATIC`!), and crosshair is absolutely necessary addition - player will see where to exactly the mark will be placed. Saving marks into save games without breaking compatibility with existing save games is not very easy, so I would like to ask @fabiangreffrath's recommendation regarding how to proceed.

**Comment by snekyo** [comment]
Alright, thanks. 

> **P.S.** There are no text labels or something like that existing for automap, in vanilla-friendly ports for sure. 🙂

One thing though: I'm talking about the port here, I'm talking about the issues system here on GitHub.

**Comment by fabiangreffrath** [comment]
> Saving marks into save games without breaking compatibility with existing save games is not very easy, so I would like to ask @fabiangreffrath's recommendation regarding how to proceed.

We will have to do it with `p_extsaveg.c`.
