### ISSUE TITLE
Make full chainsaw sound toggable

### ISSUE THREAD

**Issue by Danfun64** [fabiangreffrath/crispy-doom#116]
It's an interesting feature, but it makes switching between other source ports which lack this feature awkward.

**Comment by plumsinus** [comment]
I doubt very much that Fabian will want to make a new option just for this.

Any chance you would settle for a shortened chainsaw sound that gets auto-loaded with Crispy Doom, if I made you one?

**Comment by plumsinus** [comment]
Here's a wad with a short chainsaw, put it in the same directory as crispy-doom.cfg. (Rename it if you've already got a preload0.wad.)
[preload0.zip](https://github.com/fabiangreffrath/crispy-doom/files/313113/preload0.zip)

There's a slight gap between the end of the sawup sound and the start of the chainsaw rumble, maybe that could be removed.

**Comment by fabiangreffrath** [comment]
> switching between other source ports

Thou shalt have no other source ports before me. ;)

No, seriously, at first I was also skeptical. But once I got used to it, I couldn't stand the interrupted sounds of other source ports anymore. And I think the PWAD @plumsinus provided is a nice workaround for those who refuse this feature at all cost. Pretty sure there won't be a switch in the menus for this.

**Comment by Danfun64** [comment]
@plumsinus freedoom, chex quest, hacx versions needed

**Comment by plumsinus** [comment]
@fabiangreffrath Is there a way to automatically choose which preload wads to used, based on the other iwads that @Danfun64 listed?

**Comment by Danfun64** [comment]
There's also the matter of when pwads replace the sound...

**Comment by Zodomaniac** [comment]
>Thou shalt have no other source ports before me. ;)
Ahahahaha %)))))

>There's a slight gap between the end of the sawup sound and the start of the chainsaw rumble, regardless of whether you use this file or not. Maybe that could be fixed?
I'd also like to have this fixed if it's possible.

**Comment by fabiangreffrath** [comment]
I'll consider adding a single switch to enable/disable the chainsaw sound and the other sound extensions.

**Comment by Zodomaniac** [comment]
Nice)
I'd like to remind of this. Any chance of fixing it?
>There's a slight gap between the end of the sawup sound and the start of the chainsaw rumble, regardless of whether you use this file or not. Maybe that could be fixed?

**Comment by fabiangreffrath** [comment]
No, sorry. The sounds are played in full length until the end. If there is a gap at the end of the original sound, there is nothing I can (or am going to) do about this.

**Comment by plumsinus** [comment]
>If there is a gap at the end of the original sound, there is nothing I can (or am going to) do about this.

The gap is not in the sound itself. The truncated chainsaw sound that I posted above also plays a gap between its end and the chainsaw rumble.

**Comment by fabiangreffrath** [comment]
I guess it has to do with the duration of the chainsaw states, then. AFAICT, the sawidl sound is played in `A_WeaponReady()` which in turn is only called every 4 tics. If the full sawup sound is longer than an integer multiple of 4 tics, the remainder (i.e. sound duration % 4 tics) will be silence. Does this make sense?

**Comment by plumsinus** [comment]
Ah, yeah that does make sense.
