### ISSUE TITLE
[Crispy HeXen/Heretic] Are there any options for the -version command?

### ISSUE THREAD

**Issue by snekyo** [fabiangreffrath/crispy-doom#1161]
In Crispy DOOM, inputting `-version <DOOM version>` would select a version, right?
Like, for example, `-version ultimate` would set the version to Ultimate DOOM.

Does this command line parameter work in Crispy HeXen and Crispy Heretic?
And, if so, what are the versions that can be selected?

`P.S.` With the GitHub issue submission system I'm using, how can I select labels, assignees, projects, and some of the other stuff?

-snekyo

**Comment by rfomin** [comment]
> In Crispy DOOM, inputting `-version <DOOM version>` would select a version, right?
> Like, for example, `-version ultimate` would set the version to Ultimate DOOM.

The right parameter is `-gameversion`. Don't worry about it, it will be selected automatically depending on the IWAD you are running.

> `P.S.` With the GitHub issue submission system I'm using, how can I select labels, assignees, projects, and some of the other stuff?

I think only repository owners can set these labels.

**Comment by snekyo** [comment]
> The right parameter is `-gameversion`. Don't worry about it, it will be selected automatically depending on the IWAD you are running.

Thanks for clarifying the correct command, but just for future reference, could you give me a list of versions?

**Comment by mikeday0** [comment]
Crispy Doom is a fork of Chocolate Doom, so it inherits all of Chocolate's command-line arguments. Documentation for those can be found [here](https://www.chocolate-doom.org/wiki/index.php/Command_line_arguments).

Information on the Crispy-specific arguments can be found [here](https://crispy-doom.org/#) under Usage -> New Command-line Parameters.

The `-gameversion` argument is only applicable to Doom. Valid values are `"1.2"`, `"1.666"`, `"1.7"`, `"1.8"`, `"1.9"`, `"ultimate"`, `"final"`, `"final2"`, `"hacx"` and `"chex"`. As rfomin mentioned, you shouldn't normally need to provide this argument as the program will figure it out automatically based on the IWAD. The only time you might use it is when you're trying to play a 90s WAD that only works with earlier version of Doom.
