### ISSUE TITLE
[Heretic & HeXen (kind of)] Sound Effects are too Quiet

### ISSUE THREAD

**Issue by snekyo** [fabiangreffrath/crispy-doom#1162]
In Heretic, the sound effects are too quiet. The volume slider for it works, but even on max level, it's still too quiet. If I want the sound effects to stand out in the music, I need to set the sound effect volume slider all the way up and turn the music slider down a **ton**. And even then, they're still **very** quiet.

This is also a tiny bit of a problem in HeXen, but it's barely as bad and I can easily get past it.

Also, bonus suggestion, could you add a feature to disable autoaim on the Y axis in Heretic and HeXen (and maybe DOOM if it's not already implemented into it)? They both/all have mouselook compatibility, so it would make sense to have an option for disabling autoaim.

`P.S.` None of the three have X axis autoaim, do they?

**Comment by mikeday0** [comment]
The Raven games have quieter sound effects in general. To get some extra volume, open the crispy-h*.cfg file and change the `libsamplerate_scale` value from 0.65 to 1.0.

**Comment by snekyo** [comment]
> The Raven games have quieter sound effects in general. To get some extra volume, open the crispy-h*.cfg file and change the `libsamplerate_scale` value from 0.65 to 1.0.

Huh, alright. Maybe you could add in an option to switch `libsamplerate_scale` between 0.60 and 1.0, with the latter being the default?

**Comment by snekyo** [comment]
Just found out something.
The volume of the sound effects is relative to the volume of the music. As if the music slider is actually a "master volume" slider.
Could you guys fix this?

**Comment by mikeday0** [comment]
What have you selected for your music playback? Try Native MIDI.

**Comment by snekyo** [comment]
> What have you selected for your music playback? Try Native MIDI.

Hey, it works now.

**Comment by snekyo** [comment]
Is still think you guys should implement the feature I suggested.

> Huh, alright. Maybe you could add in an option to switch libsamplerate_scale between 0.60 and 1.0, with the latter being the default?
