### ISSUE TITLE
Incorrect IDMUS behavior in NERVE.WAD

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#118]
For example, when typing IDMUS01 in NERVE.WAD the music that plays is D_RUNNIN and not the track that normally plays in NERVE.WAD's MAP01. The.IWAD is DOOM2.WAD 1.9, not from BFG Edition.
This issue is not the case in other PWADs with replaced music, IDMUS works well in MURZIKI.WAD http://www.moddb.com/groups/doomdb/addons/murziki and OSIRIS.WAD http://www.wad-archive.com/wad/OSIRIS-Total-Conversion
UPD8: this is the same in Crispy 3.4 and June 19 daily autobuild from latest commit.

**Comment by fabiangreffrath** [comment]
The difference is that NERVE.WAD doesn't come with replacement music. Instead, it uses Vanilla's music but in a shuffled order. Thus, the semantics of the IDMUSxy cheat as in "play the music that would *normally* play in MAPxy" are still correct IMHO.

**Comment by Zodomaniac** [comment]
OK, let it be.

**Comment by fabiangreffrath** [comment]
Just for reference, the code in question is as follows:
```
	if (gamemode == commercial || gameversion < exe_ultimate)
	{
	  musnum = mus_runnin + (buf[0]-'0')*10 + buf[1]-'0' - 1;
	  
	  // [crispy] prevent crash with IDMUS00
	  if ((((buf[0]-'0')*10 + buf[1]-'0') > 35 || musnum < mus_runnin)
       && gameversion >= exe_doom_1_8)
	    plyr->message = DEH_String(STSTR_NOMUS);
	  else
	    S_ChangeMusic(musnum, 1);
	}
	else
[...]
```
So, it really just starts the music pointed to by the number you entered in the IDMUS cheat, counting from `mus_runnin`. I would have to add some really ugly special-casing here in order to support NRFTL's "native" music order.
