### ISSUE TITLE
Heretic Segault with direct door linedefs with void on other side.

### ISSUE THREAD

**Issue by Catoptromancy** [fabiangreffrath/crispy-doom#1188]
Crispy Heretic 6.0.0, 

Does not happen in Doom.

Observed behavior:
Segfault on DR and D1 linedefs on wall instead of on sector edge with lowered ceiling(door). 
 
Expected behavior:
Crispy-Doom prints message and does not segfault:
"EV_VerticalDoor: DR special type on 1-sided linedef"

**Comment by fabiangreffrath** [comment]
@JNechaevsky Anything that could probably get backported from Inter-Heretic?

**Comment by JNechaevsky** [comment]
Just checked, [this line](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_doors.c#L426-L431) straight from Crispy Doom fixes the issue, it crashes on Windows too. I'll PR this fix shortly.

P.S. Sorry for being inactive last days. A bad thing happened, please see [my comment](https://github.com/JNechaevsky/yaguar-doom/commit/d85e589fca21933aab6cfc9eca72ecec4a875fc4#commitcomment-140375273). AFAIR, there was something along with Truecolor support for Strife, but still can't focus properly to remember what exactly.

**Comment by fabiangreffrath** [comment]
> P.S. Sorry for being inactive last days. A bad thing happened, please see [my comment](https://github.com/JNechaevsky/yaguar-doom/commit/d85e589fca21933aab6cfc9eca72ecec4a875fc4#commitcomment-140375273).

😱 OMG, I'm so sorry to read that! I hope you and your wife are all safe and healthy now. It's really strange and disturbing days that we are living in. You can be proud of yourself, you have been very courageous! ✊

**Comment by JNechaevsky** [comment]
Everything will be okay, I promise. 🙂 It wasn't a very easy trial, but it could be much, _really_ much worse in current situation. At least I'm happy that this trial has been finished without losing a dignity, even a hard experience is also experience.

**Comment by mikeday0** [comment]
Julia, I am relieved to hear that you and your wife are okay. Nobody deserves such treatment for the act of peaceful protest. Your bravery in the face of injustice is to be admired.
