### ISSUE TITLE
Batman Doom total conversion revealed a bug: if NERVE.WAD is present in the directory, launching BATMAN displays NERVE title screen and offers episode selection!

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#120]
The IWAD used is DOOM2 1.9, and for some reason it offers episode selection and displays episode names 'Knee-Deep in the Dead' and 'The Shores of Hell'. When I remove nerve.wad from the directory, Batman's title screen is displayed and there is no episode selection.
UPD8: Choco doesn't have this bug and displays the correct title screen.

**Comment by fabiangreffrath** [comment]
I guess this is because the Batman Doom PWAD contains the necessary lumps to render the menu, though they were originally intended for use with Doom 1. Thus, the menu is rendered from resources provided by the PWAD file. This is exactly what I have been asked to implement several times. :/

**Comment by Zodomaniac** [comment]
OK, I'll just cut out those lumps with SLADE.

**Comment by Zodomaniac** [comment]
OK, I'll cut out those lumps with SLADE. What are their names?

**Comment by fabiangreffrath** [comment]
They are called M_EPI1, M_EPI2 and M_EPISOD.
