### ISSUE TITLE
Custom soundfonts dont work properly when setting virtualmidisynth #1 as the native midi device

### ISSUE THREAD

**Issue by ExGuestCJ** [fabiangreffrath/crispy-doom#1207]
### Background

Version of Crispy Doom: 6.0.0

Operating System and version: Windows 8.1

Game: Doom

### Bug description

Observed behavior: When setting virtualmidisynth #1 as the native midi device the music plays with the default soundfont

Expected behavior: The music should play using the custom soundfont

**Comment by ceski-1** [comment]
Works fine for me in Windows 8.1 (virtual machine). Can you share your `crispy-doom.cfg`? Add it to a zip file and attach it to your comment. Also, please share the exact command line you use to launch the game and the wads you're using.

**Comment by ceski-1** [comment]
Also, a good first troubleshooting step is seeing if you can play a midi correctly with [vanBasco MIDI player](https://web.archive.org/web/20240211073647/http://www.vanbasco.com:80/downloads/vkaraoke.exe):

![Untitled](https://github.com/user-attachments/assets/bdc7cd89-cd4d-4822-8a51-e78c4c60c121)

**Comment by ExGuestCJ** [comment]
I should also comment that vms does work on chocolate doom.
[crispy doom config.zip](https://github.com/user-attachments/files/16258074/crispy.doom.config.zip)
extract the file, the cfg file is on it

**Comment by ceski-1** [comment]
Try one of these builds: [64-bit](https://github.com/fabiangreffrath/crispy-doom/actions/runs/9587745915/artifacts/1618410295) or [32-bit](https://github.com/fabiangreffrath/crispy-doom/actions/runs/9587745915/artifacts/1618414394)

**Comment by ExGuestCJ** [comment]
Didnt work either

**Comment by ExGuestCJ** [comment]
> Also, please share the exact command line you use to launch the game and the wads you're using.

Forgot to say i dont use anny command lines afaik and i use the ultimate doom wad

**Comment by ceski-1** [comment]
Where did you download Chocolate Doom and Crispy Doom? If they are from here, then the midi implementation is identical: http://latest.chocolate-doom.org/

**Comment by ExGuestCJ** [comment]
Yea, i remember downloading them there

**Comment by ceski-1** [comment]
> Yea, i remember downloading them there

Again, the midi code is identical between Chocolate Doom and Crispy Doom so something else is going on here. There are two things you can try, otherwise this is something on your end:
1. You can try setting `winmm_complevel 0` in `crispy-doom.cfg`.
2. Make sure there isn't anything overriding the music in `C:\Users\<NAME>\AppData\Roaming\crispy-doom`.

**Comment by ExGuestCJ** [comment]
It worked!
