### ISSUE TITLE
In case of specifying -fast parameter when launching a PWAD for the first time, the parameter isn't applied

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#121]
Try Batman Doom or Army of Darkness Doom to see that.

**Comment by fabiangreffrath** [comment]
I believe this is a misconception. 

If you have a look at the output in stderr, it will say
```
P_SetupLevel: MAP01 (batman.wad), Skill Normal (fast), Time 0:00, Doom map format, normal BSP nodes.
```
So, the game *is* loaded with the `-fast` parameter. But, the `-fast` parameter isn't a general turbo. Instead, it manipulates the durations of specific states in the state table (i.e. the Demon states) and the projectile speeds of Imps, Cacodemons and Barons/Knights. However, these monsters aren't even available in Batman Doom. They are substituted by other enemies and the states in question don't apply as such anymore. In other words, the states table is mangled up by Batman Doom's Dehacked patches in such a way that you are unable to recognize the modifications of the `-fast` parameter anymore.

I hope this makes sense?

**Comment by Zodomaniac** [comment]
>I hope this makes sense?

Thanks for the explanation)
