### ISSUE TITLE
MacOS app is damaged and can't be opened

### ISSUE THREAD

**Issue by zx331645** [fabiangreffrath/crispy-doom#1216]
### Background

Version of Crispy Doom: 7.0.0

Operating System and version: MacOS 14.5 (arm64)

Game: Doom

Any loaded WADs and mods (please include full command line): None

### Bug description

Observed behavior: "Crispy Doom.app is damaged and can't be opened" appears upon opening the application bundle. (All internal Unix apps are marked as executable)

Expected behavior: The Crispy Doom launcher opening.

**Comment by rfomin** [comment]
Could this be it? https://discussions.apple.com/thread/253714860?sortBy=rank

**Comment by zx331645** [comment]
Oop, forgot about the hellish thing that is Gatekeeper! Sorry!
