### ISSUE TITLE
Fix the DEHACKED bug emulated in Choco that causes vbatman.deh patch for Batman Doom to be necessary

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#122]
I don't see any reason why this bug should be kept in Crispy. If it's fixed, then downloading and adding vbatman.deh to fix the weapon selection won't be necessary.

**Comment by fabiangreffrath** [comment]
Pending. I am sure that demo and netgame critical side effects of this special case are negligible.
