### ISSUE TITLE
Smoothed mod: Should it work? (DEHEXTRA support)

### ISSUE THREAD

**Issue by vanfanel** [fabiangreffrath/crispy-doom#1221]
### Background

Version of Crispy Doom: Latest stable (7.0.0)

Operating System and version: GNU/Linux Debian Testing

Game: Doom

Any loaded WADs and mods (please include full command line):
smoothed.wad from https://www.doomworld.com/forum/topic/85991-smoothed-smooth-monsters-for-doom-retro-and-crispy-doom/
Commandline:`
./crispy-doom -iwad doomu.wad -file doom1music.wad doomwide.wad vsmooth.wad`

### Bug description

Observed behavior: crispy-doom gives a bunch of errors and the mod changes monster animation in-game, but not the weapon animations:

[crispy-log.txt](https://github.com/user-attachments/files/16922313/crispy-log.txt)

Expected behavior: The mod should work because, as I understand, the SMOOTHED wad requires DEHEXTRA support and Crispy-doom has it. Maybe I am wrong?

**Comment by mikeday0** [comment]
I get the same warnings (they're not errors) but the mod does indeed change the monster animations in game.

**Comment by vanfanel** [comment]
> I get the same warnings (they're not errors) but the mod does indeed change the monster animations in game.

Yes, you are right, the monster animations are indeed changed, but not the weapon animations, which this mod is supposed to change too.

**Comment by fabiangreffrath** [comment]
It's called "Smooth monsters for Doom Retro and Crispy Doom" for a reason. If you want weapon animations you'll have to load the "Black Ops" mod that's linked on the same page.

**Comment by vanfanel** [comment]
> It's called "Smooth monsters for Doom Retro and Crispy Doom" for a reason. If you want weapon animations you'll have to load the "Black Ops" mod that's linked on the same page.

Ah, I see... So the warnings can be safely ignored then? I don't know the Doom internals as to be sure.

**Comment by fabiangreffrath** [comment]
Yes, they just say that the DEHACKED patch will not work with Vanilla Doom.

**Comment by vanfanel** [comment]
Understood, thanks! Closing this then :)
Sorry for the noise...
