### ISSUE TITLE
Remove the length limit for DEHACKED replaced text strings

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#123]
I was puzzled why in Batman Doom one of the messages said 'Picked a box of razordisks', while it is correct to say 'Picked up...' I added these 3 symbols and in game it became 'Picked up a box of razordis', SK and the dot getting truncated. Why not remove the length limit for dehacked strings?

**Comment by fabiangreffrath** [comment]
Actually, this limit has already been removed. Are you sure you adjusted the second number in the `Text 27 27` line to the number of characters in the substitute string?

**Comment by Zodomaniac** [comment]
>Are you sure you adjusted the second number in the Text 27 27 line to the number of characters in the substitute string?

Aha, adjusted it, it's OK now :)
