### ISSUE TITLE
SUGGESTION : Clean widescreen HUD

### ISSUE THREAD

**Issue by spychopat** [fabiangreffrath/crispy-doom#1232]
Hello
Crispy Doom is my aboslute favorite sourceport, i like how it keeps things simple and only focus on essential features.
However, when in some cases i don't want to play with status bar but rather have the game renders in fullscreen, i notice that the current transparent HUD is... not that great (it's just the default status bar, but without background, it's the text only).
I wish we could have something like my example below, taken from prboom+, it's simple, clean and pretty.

I will try to look into the code and see if it's easy enough to do it myself and make a pull request, but i don't know if i am good enough for that, and also, i would like to save myself this effort if the author doesn't actually want to implement this into his port, which i would totally understand.
Do you guys think this would fit into Crispy Doom ?

![image](https://github.com/user-attachments/assets/445c399c-bd05-4d48-b8fd-82bba70f974d)

**Comment by fabiangreffrath** [comment]
Thank you for your suggestion, I agree it looks very clean!

However, I cannot implement everybody's favorite HUD in Crispy Doom. As you stated yourself, the actual Crispy HUD is just the status bar widgets at the exact same position as on the status bar, but without the status bar background.

What you are looking for might be a user-defined HUD, as is currently offered among others by DSDA-Doom, Nugget-Doom and future releases of Woof (once SBARDEF support is implemented). I guess that Nugget-Doom with its NUGHUD lump might come closest for you.

**Comment by spychopat** [comment]
Well, i can udnerstand.
I'll look at this Nugget-Doom port, it seems like it has interesting features.
But often with doom sourceports, i like some features but i don't like how they are bloated with too many things i don't want.
Crispy Doom is definitely going to stay a favorite, it has a great balance !
