### ISSUE TITLE
[Suggestion] Hexen: Crispy Hud

### ISSUE THREAD

**Issue by Noseey** [fabiangreffrath/crispy-doom#1235]
Here a suggestion for a Hexen Crispy Hud, applying the same methodology as for the Heretic one.

The Split Line is between the Item- and the Weapon-Pieces-Widget, since alot of weapons (especially for the warrior) are off-center to the right:
![2024-11-06 21_54_39-Hexen - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/70d2f04c-15f7-457c-8aa3-06faf3e11c41)

This is how it looks like:
![2024-11-06 21_53_59-Hexen - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/d0004ab0-4e40-41ab-807d-5a4e055908db)

.. and here the item bar:
![2024-11-06 21_54_23-Hexen - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/3e8a5e47-cf47-4ff1-ba81-d29f4aba6834)

Characteristics:
- Relative height preserved
- Horizontal difference preserved between Life <-> Mana <-> Item, and Weapon-Pieces<->Armor
- Complete Hud shifted down by 6px to remove the gap created by the chain.
- Aligns with aspect ratio
- Is optional

Due to the spacing and size of the widgets, it is alot more cramped than the heretic one. In 4:3 the weapon-pieces widget tends to overlap alot of weapons. This effect disappears when going to a wider aspect ratio. 

I was thinking about not drawing the weapon-pieces widget at all, but I think there is no other place you can get the information from in-game. 

Let me know your thoughts, thanks!

**Comment by fabiangreffrath** [comment]
I like it. Any chance for the icon bar not to overdraw the underlying widgets?

**Comment by fabiangreffrath** [comment]
> I like it. Any chance for the icon bar not to partly overdraw the underlying widgets?

This is what I mean. It looks better in Heretic:

![image](https://github.com/user-attachments/assets/38931c71-fec8-43b5-b275-278a99f92906)

**Comment by fabiangreffrath** [comment]
Maybe the mana and weapon pieces widgets can be disabled as long as the icon bar is active.

**Comment by Noseey** [comment]
> I like it. Any chance for the icon bar not to partly overdraw the underlying widgets?

You are right, the widgets sticking out to the side looks a bit messy

> Maybe the mana and weapon pieces widgets can be disabled as long as the icon bar is active.

Thats a good idea! I will try to implement it and provide an update.

**Comment by Noseey** [comment]
I got it working. Basically, when the inventory is open, only the health and armor is drawn:
![2024-11-07 17_44_35-Hexen - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/3bacd4b5-67d9-4917-96b3-333c978122ae)

However, this currently applies across all aspect ratio, even for those where no overlapping occurred in the first place (21:9, 16:9):
![2024-11-07 17_45_10-Hexen - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/0e6680f8-a2c2-47e0-bf93-025fc43712b2)

Should this behavior be kept uniform or should I add a check to only apply it for 4:3 and 16:10, where the issue is present?

**Comment by fabiangreffrath** [comment]
> Should this behavior remain uniform or should I add a check to only apply it for 4:3 and 16:10, where the issue is present?

Instead of hard coding aspect ratios, I'd prefer if you could check horizontal patch positions and widths instead.

**Comment by Noseey** [comment]
> Instead of hard coding aspect ratios, I'd prefer if you could check horizontal patch positions and widths instead.

Glad you mentioned that, its the better solution. I have choosen the two widgets that would intersect first when reducing aspect ratio: ManaPatch2 and Gem1
![2024-11-07 19_12_11-Hexen - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/0c0b558f-18e2-44df-8a92-b14c7bdd5d21)

So there has to be at least 1px spacing between them in order to draw all remaining widgets, otherwise an intersect is detected.

**Comment by fabiangreffrath** [comment]
That'd be the best solution.

**Comment by Noseey** [comment]
Here the solution at work:

16:9 Inventory Bar
![2024-11-07 23_10_36-Hexen - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/55394946-bb2d-452e-95cb-379609e711e2)

16:10 Inventory Bar
![2024-11-07 23_10_57-Hexen - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/bf9383b2-b5ba-4f87-af3d-c10bb13db64d)

**Comment by fabiangreffrath** [comment]
Great, thank you!
