### ISSUE TITLE
[Suggestion] Heretic/Hexen: Quick Reverse Key

### ISSUE THREAD

**Issue by Noseey** [fabiangreffrath/crispy-doom#1239]
In the last couple of month, I played through a lot of WADs using Crispy-Doom and keyboard-only. For that, I really enjoyed having the quick reverse functionality, despite its dodgy reputation (not a speedrunner, so I don't care much). 

Now I wanted to continue with Heretic, but found it is not implemented there, neither in Hexen. Can it be added there aswell, to be consistent with Crispy-Doom and to make some keyboard players happy?

If so, I would start working on an implementation leaning on the existing solution in Crispy-Doom. 

Let me know your thoughts, thanks!

**Comment by fabiangreffrath** [comment]
He, sure, just go ahead please. 😉

**Comment by Noseey** [comment]
> He, sure, just go ahead please. 😉

Perfect! It was really easy to add, since most of the infrastructure was already in place. So I took the time to improve the button behavior a bit, especially for mouse-users to avoid continual (unwanted) turns. The PR is created!
