### ISSUE TITLE
Add 128x128 Crispy PNG icon file into the distrib instead of current 64x64 one

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#126]
and also place it at Crispy web page https://www.chocolate-doom.org/wiki/index.php/Crispy_Doom
Choco has 128x128 icon (see the same page below), why shouldn't Crispy have it?

**Comment by fabiangreffrath** [comment]
Will haver to check my resources for this. I am not even sure if I have such a high-resolution icon available at all...

**Comment by fabiangreffrath** [comment]
Sorry, but even my original icon is only 64x64. So , there won't be a higher resolution icon from my side. Which does not mean I am not open to submissions. ;)

**Comment by Zodomaniac** [comment]
Here you are ;) with some bonus fun. There is no Strawberry Doom icon anywhere on the net, the only link to it is broken, but a friend of mine showed me some Raspberry Doom! XD
![crispy-doom_128x128](https://cloud.githubusercontent.com/assets/15119473/16513974/81f4d980-3f71-11e6-8f30-af02908c5961.png)
![food doom](https://cloud.githubusercontent.com/assets/15119473/16513977/8d385c2c-3f71-11e6-9689-9e3dbc183fdd.png)
![raspberry-doom](https://cloud.githubusercontent.com/assets/15119473/16513985/952d131e-3f71-11e6-9cfb-c8bc714e30f4.jpg)

**Comment by fabiangreffrath** [comment]
Awesome, thank you very much!

Also, thank you for the fun pics. I have seen your e-mail, but haven't found time yet to reply. ;)

**Comment by fabiangreffrath** [comment]
Could you maybe also provide a setup icon in the same quality, please?

**Comment by Zodomaniac** [comment]
>Could you maybe also provide a setup icon in the same quality, please?

Here you are :)
![crispy-doom_setup_128x128](https://cloud.githubusercontent.com/assets/15119473/16544692/36859d6a-4118-11e6-91a9-bf88171d7418.png)

**Comment by Zodomaniac** [comment]
After downloading the daily build I saw that my icons lacked contrast compared to the old ones (especially the low left corner of the D was almost the same color as the crisps were), I made the crisps lighter.
Feel free to update them on the web page and in game)
BTW, why do the exe-s have my icon sized down to 64x64?
![crispy-doom_128x128_upd](https://cloud.githubusercontent.com/assets/15119473/17242199/82946f86-557e-11e6-8d41-849f5ab350b3.png)
![crispy-doom_setup_128x128_upd](https://cloud.githubusercontent.com/assets/15119473/17242207/91f80866-557e-11e6-94c5-4d5273627dad.png)
