### ISSUE TITLE
Fix ouch face code, maybe the way it's done on Strawberry Doom or PrBoom+

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#127]
http://doom.wikia.com/wiki/Ouch_face
Strawberry Doom had this fixed, and PrBoom+ even has an option to fix its behavior or not.

**Comment by fabiangreffrath** [comment]
The "Ouch!" face has been fixed since v1.1. Please check again.

**Comment by fabiangreffrath** [comment]
And, no, there will for sure be no switch for this. ;)

**Comment by Zodomaniac** [comment]
>The "Ouch!" face has been fixed since v1.1. Please check again.

Nice :)
