### ISSUE TITLE
If I try lo load a savegame from Vanilla Doom 2 while playing Batman Doom and reply Y to the Continue? question, the game freezes (while it should just exit). Both saves are extended.

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#130]
[Batman 5 D2 6.zip](https://github.com/fabiangreffrath/crispy-doom/files/568412/Batman.5.D2.6.zip)

**Comment by fabiangreffrath** [comment]
Thanks! This is actually an upstream issue, though Choco handles the error differently: It fails to allocate more memory from the zone, whereas Crispy increases its zone buffer more and more. 

Forwarded to Choco: https://github.com/chocolate-doom/chocolate-doom/issues/794

**Comment by fabiangreffrath** [comment]
Fixed in https://github.com/fabiangreffrath/crispy-doom/commit/b0c0fb1500a880c83f75a9954c9f276976ec855c
