### ISSUE TITLE
Can't Get Episode Select to Appear When Using NERVE.WAD and BFG version of DOOM2.WAD

### ISSUE THREAD

**Issue by aynrandjuggalo1** [fabiangreffrath/crispy-doom#131]
Hey guys, first off, really love the port. I think it's a great enhancement of Chocolate Doom. Okay, here's my issue:

I'm trying to play NERVE.WAD, and I'm able to, but there's a small hiccup that really bothers my sense of order. On Linux, using the version of the program I just compiled yesterday, I'm running the command:

crispy-doom -iwad DOOM2BFG.WAD -file NERVE.WAD

When the game loads, the DOOM 2 title screen has been replaced by a more generic-looking image (I think it's the one used in between levels), and there is no episode select screen. Starting a new game launches you straight into NERVE.WAD whether you want to or not.

This is okay to me, but I was wondering if there were any tweaks I could make on my end that would make it perfect, or if tweaks have to be made to the source code. How do I get the episode select screen to appear when using NERVE.WAD and the BFG version of DOOM2.WAD?

**Comment by fabiangreffrath** [comment]
Just leave away the `-file NERVE.WAD` part. Just as with every other PWAD, you instruct the engine to replace lumps in the IWAD by their counterparts in the given PWAD by this command line.

Oh, and please make sure the nerve.wad file name is lower-case.

**Comment by aynrandjuggalo1** [comment]
Okay, I did that and it works! Fantastic! I have a follow-up question:

Under this setup, is there a way to warp via the command line to a level in nerve.wad? I tried:

crispy-doom -iwad DOOM2BFG.WAD -warp 2 1

But that didn't work (it warped me to level 2 of the main campaign). Is there any way to do this correctly?

**Comment by fabiangreffrath** [comment]
It should be possible to use the `-episode 2` parameter for that.

**Comment by fabiangreffrath** [comment]
> Oh, and please make sure the nerve.wad file name is lower-case.

This shouldn't be necessary anymore once https://github.com/chocolate-doom/chocolate-doom/issues/809 is resolved.

**Comment by fabiangreffrath** [comment]
Fixed by https://github.com/fabiangreffrath/crispy-doom/commit/533e3726f0fdeb0f679fedd96ab4877f80922456
