### ISSUE TITLE
Intermission music persists when loading/restarting to same map

### ISSUE THREAD

**Issue by CapnClever** [fabiangreffrath/crispy-doom#134]
Happened to spot this oddity in the middle of a blind race of Rebirth, though it also occurs in IWADs. Tested on Win7 64-bit, Crispy Doom 3.4:

1. Start game
2. Get to end of first map
3. Start new game from intermission screen
4. Note that intermission music is still playing

This also happens when loading a saved game if it's to the map they just finished. I attempted to reproduce in Chocolate Doom 2.2.1, but the correct music starts up upon loading/restarting. Just to make sure it wasn't some dumb "native MIDI in Windows" problem, I also tested with OPL emulation and got the same results.

I'm guessing this is related to #94, based on the request therein.

**Comment by fabiangreffrath** [comment]
Yes, this is a bug in the implementation of #94 that sneaked into the 3.4 release. Fortunately, it has already been discovered and fixed immediately after: https://github.com/fabiangreffrath/crispy-doom/commit/f0bd87c6313d6c375ae8039eda4d6640364eb6ae
