### ISSUE TITLE
CMDLINE, COPYING, README and other useful docs from Chocolate Doom were not included in 3.5 build

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#136]
Maybe push them into 3.5 as an unversioned update?
BTW, daily Crispy builds do have these docs bundled.

**Comment by fabiangreffrath** [comment]
Yes, you are probably right. I once had them all in a separate `doc/` directory but got rid of this at some point. I think I'll add them back...

**Comment by fabiangreffrath** [comment]
I have added these now in an unversioned update, thanks for the idea!
