### ISSUE TITLE
Demo recorded from a savegame is played from the start of the level, not from the savegame. Why not fix it? :)

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#137]
Detailed description and discussion is here
https://github.com/chocolate-doom/chocolate-doom/issues/839
Would be nice to have proper demo recording/playback from savegames (-loadgame N -record demotest and -loadgame N -playdemo demotest, like it works in GZDoom, requiring to load the savegame from which the demo starts for the demo to be played, else saying smth like "Savegame *savename* must be loaded to play a demo from it".

Fabian, if you inplement this feature and make the next Crispy build after that to work with the soundfont, I'll record the demo and you'll see why this idea came to me!

**Comment by fabiangreffrath** [comment]
Isn't it already possible to record a demo starting from a savegame by adding e.g. `-loadgame 0 -record demo` to the command line?

Fixing the counterpart `-loadgame 0 -playdemo demo.lmp` is almost trivial, but I am not sure about the error message that you'd like to see printed. I'd have to modify the demo format for that (in a similar way I did to introduce the extended savegame format) and that's really something Iäd like to avoid.

**Comment by fabiangreffrath** [comment]
> Fabian, if you inplement this feature and make the next Crispy build after that to work with the soundfont, I'll record the demo and you'll see why this idea came to me!

Support for the soundfont needs to be compiled into the SDL_Mixer library. If you want to use the dail< snapshots, copy over the libSDL_Mixer.dll file from the Crispy 3.5 release and rename it to SDL_Mixer.dll, i.r. overwrite the file that comes with the snapshot. Then, soundfonts should work out of the box.
