### ISSUE TITLE
A very minor bug: in BFG Edition in case of selecting the NRFTL episode and starting the Hell on Earth after that, the NRFTL track continues to sound.

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#138]
A very minor bug: in BFG Edition in case of selecting the NRFTL episode and starting Hell on Earth after that, the NRFTL track continues to play.
Funny thing is that typing IDMUS01 after that sets the music to the correct Hell on Earth track again.
Maybe I am too much of a perfectionist, kind of Aggressive Perfector from that Slayer song, feel free to ignore this if you wish.

**Comment by fabiangreffrath** [comment]
> feel free to ignore this if you wish.

Never! Only a dead bug is a good bug. ;)

Really, thanks for the report!
