### ISSUE TITLE
Crispy doesn't respect the "Timidity Configuration File" value. It always uses timidity.cfg from directory with crispy-doom

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#139]
Crispy doesn't respect the "Timidity Configuration File" value. it always uses timidity.cfg from directory with crispy-doom. Choco, on the other hand, works as intended. (from StasBFG[iddqd])

**Comment by fabiangreffrath** [comment]
Hm, I am pretty sure that I have never touched any Timidity-related code (or code related to its configuration file). However, this might be related to the SDL_Mixer.dll library. Does it work as intended if you use the one from Chocolate Doom?

**Comment by Zodomaniac** [comment]
I've tested it with Choco 2.3.0, and the problem is the same: timidity.cfg is always used, even if no Timidity config file name is specified. To override it with default Windows MIDI I have to delete it.
Same with Crispy+Music Pack 2.
