### ISSUE TITLE
Suggestions for more "Observer" view modes

### ISSUE THREAD

**Issue by 3noneTwo** [fabiangreffrath/crispy-doom#142]
This is a bit of an oddball feature request, but stick with me.

Thanks to Chocolate Doom, Crispy inherited the -left and -right command line parameters, used exclusively for [three-screen mode](https://www.chocolate-doom.org/wiki/index.php/Three_screen_mode). I've come to realize that these drone clients also allow for the map to be open near-permanently on a second screen. It has its caveats of course: The map updates based on the drone's view (ie: if you used "-left", the map will only update to show what's on your left), and it reverts to player view at the start of each map (requiring a quick Alt+Tab to the drone and reenabling the map), but otherwise it works rather nicely.

So naturally, I'd like to suggest a couple new modes for drone clients.

**-front** or **-spectate** : Self-explanatory, an observer that effectively duplicates the player's forward-facing view. This could be useful for something like LAN spectating¹, allowing for view settings to be altered specifically for spectators (eg: uncapped framerate, HUD-less) without touching the player's own view settings. This also makes way for...
**-map** : Map mode, permanently enabled. This could allow for an overview of the entire map and all of its players (follow mode disabled, entire map revealed, zoomed to fit), or simply act as a regular old map on a second screen, revealing itself as players progress.

¹ There's something to be said about having the ability to switch between multiple players, but: baby steps, local use first. I've heard that Doom's netcode doesn't exactly allow for smooth multiplayer spectating. Maybe Chocolate/Crispy's netcode offers better results for this kind of thing?

---

Thoughts? Yay, nay?

**Comment by fabiangreffrath** [comment]
To be honest, this isn't something that I am going to spend time on. I mean, Automap in a separate windows may be a nice feature in the future, but everything else didn't really catch my interest. Sorry. :/

**Comment by 3noneTwo** [comment]
No problem! I knew this suggestion would be a bit of a long-shot, I was mostly just trying to think of other ways drone spectators could be useful.

I'd honestly be attempting this myself (the forward-facing drone, at least), but the info for building Chocolate/Crispy on Windows is out of date. Seems like everything's preparing for Choco's 3.0 SDL2 release at the moment.

**Comment by fabiangreffrath** [comment]
I am closing some old issues that I consider irrelevant by now. Feel free to reopen with a comment if you disagree.
