### ISSUE TITLE
If Gravis sound bank for music is selected, all the Crispness menu features are set to their defaults!

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#143]
I've caught this really strange bug :) All Crispy features become disabled, except for extended savegames, in case of selecting GUS for music. I think this is accidental resetting Crispy features to their defaults .

**Comment by fabiangreffrath** [comment]
Huh, what?! Could you please describe step-by-step what leads to the resetting of all Crispy features?

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
> Huh, what?!

I was as surprised as you are. I just changed the Native MIDI to GUS(emulated) in Setup tool, with the GUS patch path provided. When I launched the game, I discovered that all the status bar figures had turned red! I looked up to Crispness menu and found out that all the Crispy features have been set to defaults (all to Off except Extended Savegames which is on by default).
You can try that with this unzip-and-play bundle I based on the freshest daily Crispy build, having the GUS patches in classicmusic/instruments included :)
https://drive.google.com/open?id=0Bycv-h0BCyw0NWlXMWdxT1M0UDA

**Comment by Zodomaniac** [comment]
I tested more thoroughly and discovered that the Crispy vars resetting occurs in case of ANY change in music device parameter (setting/removing the Timidity config path or changing from native MIDI to OPL/GUS and vice versa etc.)

**Comment by fabiangreffrath** [comment]
You are using a daily snapshot, right? I am sure the problem occurs *whenever* you change and save something in the setup tool. Please try again with tomorrow's snapshot.

**Comment by Zodomaniac** [comment]
The bug is gone in today's snapshot, thanks a lot!

**Comment by fabiangreffrath** [comment]
Phew. Thanks for testing. :)
