### ISSUE TITLE
New Physical feature: realistic pump shotgun pellet spread and pellet count being 10

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#146]
Hello) It's a bit irritating to me that the shotgun has flat, horizontal-only pellet spread. SSG introduced in Doom 2 does have vertical spread.
Could you implement an optional Physical feature (i.e. disabled automatically in multiplayer/demo recording that require Choco-compatibility) that the shotgun shoots 10 pellets with 3-D spread having the same radius as the current linear one, total damage being the same as the standard one (10pellets x 7damage instead of 7 pellets x 10 damage, as the SSG shoots 20 pellets, so single barrel should fire 10 with the same ammo). In the hands of NPCs (shotgun guys) they should also shoot 10 pellets with 3-D spread but with the total damage being the same as the current NPC damage.

**Comment by fabiangreffrath** [comment]
Sorry my friend, but this request is clearly out of question.

I will not arbitrarily change fundamental weapon physics for personal preference.

**Comment by Zodomaniac** [comment]
As you wish. I was suggesting it as an optional, togglable feature though, like all the Physical ones.
I've seen such correction of pump shotgun spread in Brutal Doom.

**Comment by fabiangreffrath** [comment]
I see, but changing the number of bullets, their spread and damage distribution is so random.

Why 10 pellets x 7 damage and not 12 pellets x 6 damage? How should the pellets spread vertically? And, most importantly, why?

This is just too much random guess-work for my taste, sorry.

**Comment by Zodomaniac** [comment]
>Why 10 pellets x 7 damage and not 12 pellets x 6 damage? How should the pellets spread vertically? And, most importantly, why?

I can reply to all these questions of yours :)
10 pellets because the SSG fires 20 pellets with 2 barrels using the same rounds :)
and for the vertical spread, I thought the SSG code could be adopted, just with lesser spread radius.
