### ISSUE TITLE
add support for 16 sprite rotations

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#152]
The code is already there e.g. in PrBoom+ and should be pretty straightforward to port over. What I still need, though, is a minimal example WAD to properly test this.

**Comment by JNechaevsky** [comment]
Tada! It's tea time :) Here, I made this demo map and teapot with 16 rotations (also with indication of angle and sprite name):
http://jnechaevsky.users.sourceforge.net/files/teapot16.zip

It works in PrBoom+ and ZDoom, so I hope it will help.

**Comment by fabiangreffrath** [comment]
Perfect, I was hoping for something like this, thanks! ;)
