### ISSUE TITLE
If the loaded WAD contains MAP33 and beyond, support transition from MAP30 to MAP33 and further

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#157]
Crucified Dreams WAD you're already familiar with
[crudream.zip.txt](https://github.com/fabiangreffrath/crispy-doom/files/806007/crudream.zip.txt) contains also maps from 33 to 41. Maps 31 and 32 are the secret ones, exiting to map 16 (both in doom2.wad and Crucified Dreams), so it would be logical to enable transitions from MAP30 to MAP33, and from map 33 to further maps (currently the game closes when map 33 or beyond is left).

**Comment by fabiangreffrath** [comment]
Hm, interesting idea!

What happens if you quit MAP30 by using an exit switch instead of killing the brain spitter; could you find this out, please?

**Comment by Zodomaniac** [comment]
When I quit the MAP30 of Crucified Dreams, I get the final message and the enemy zoo, just like on completion of Doom 2.

**Comment by fabiangreffrath** [comment]
I see. Unfortunately, that's hard-coded behaviour. And the transition from MAP33 back to MAP03 is also reserved for the BFG Edition case. What I could offer, then, is transition to the respective next map from MAP34 onward. Does this help?

Does crudream MAP30 feature a normal or a secret exit? Maybe we could use this to distinguish between normal transition (i.e. finale cast) and special transition (i.e. next map).

**Comment by Zodomaniac** [comment]
>What I could offer, then, is transition to the respective next map from MAP34 onward. Does this help?

Yes, that would be nice :)
>Does crudream MAP30 feature a normal or a secret exit?

How can I distinguish the exit types?

**Comment by fabiangreffrath** [comment]
> How can I distinguish the exit types?

Only in a map editor.

**Comment by Zodomaniac** [comment]
I looked it up, it's a standard exit, not a secret one.
Concerning the MAP33 I thought: is it possible to define leaving MAP33 based on the IWAD loaded: if it's the IWAD from BFG Edition, go from MAP33 to MAP03, and if it's the standard IWAD, go to MAP34?

**Comment by fabiangreffrath** [comment]
> I looked it up, the CruDream MAP30 exit is a standard exit, not a secret one.

Alright, so this doesn't help.

> Concerning the MAP33 I wonder if it is possible to define leaving MAP33 based on the IWAD loaded: if it's the IWAD from BFG Edition, go from MAP33 to MAP03, and if it's the standard IWAD, go to MAP34?

Rather not. Consider there are PWADs like e.g. D2TWID which contain a MAP33 and even a corresponding secret exit switch in MAP02. It should be possible to play these as intended even with the regular DOOM2.WAD.

**Comment by Zodomaniac** [comment]
BTW, I began to try Doom and Doom 2 the way ID did yesterday :)
A little offtop: why doesn't D2TWID have its own menu pic while DTWID does?
Is it the same for you?
