### ISSUE TITLE
Bash completion script is broken

### ISSUE THREAD

**Issue by chungy** [fabiangreffrath/crispy-doom#158]
Tab complete does nothing after typing `crispy-doom`. Seems to be related to the script looking for an executable named `chocolate-doom` instead. I imagine the fix for this should involve an upstream change to use autoconf replacement variables.

**Comment by fabiangreffrath** [comment]
Yep, this should get fixed upstream in Choco.

**Comment by fabiangreffrath** [comment]
I don't even know what is required to do autoconf variable substitution in these files, any idea?

**Comment by chungy** [comment]
I played with it a bit just before reporting the issue here (I didn't want it to slip my mind completely). I might try experimenting more and sending a PR to Chocolate Doom.

I feel like I might need to introduce _another_ variable into configure.ac. If I do, I'll have fraggle decide how messy he cares for that thing to get. :-)

**Comment by fabiangreffrath** [comment]
This has been merged into Choco already!
