### ISSUE TITLE
In case of launching the game with -fast but starting the game after the in-built demo has begun, the -fast parameter is lost

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#159]
IMO the -fast command line parameter should be stored in a boolean variable (setting it to 1, default being 0) and be applied upon loading a map for playing even if the in-built demo has already begun.
I post this as a Crispy issue 'cause such a change will be non-Vanilla.

**Comment by fabiangreffrath** [comment]
I see. I currently prevent the parameters from being reset when a new game is started. However, when they have been set by a demo playback, the values given on the command line are still ignored. What I need to do is re-read the values from the command line each time a new game is started.

Also, I should consider saving these values in the extended savegame format.

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
>Also, I should consider saving these values in the extended savegame format.

I'd rather not bind the launch parameters hard to the savegame because the player might decide e.g. to try playing with parameters from the savegame made without parameters.

**Comment by fabiangreffrath** [comment]
Indeed, this would require a three-pass loading of the extend savegame data (i.e. read game parameters in first pass before P_SetupLevel(), run P_SetupLevel(), compare map lump origin in second pass, restore thinkers, restore rest of extended savegame data).

I am leaving it as it is now, i.e. the game parameters are determined on the command line and never overridden.

**Comment by Zodomaniac** [comment]
I have to re-open this, sorry.
Here's the savegame from Doom the way ID did, the WAD, DEH and TXT files comprising the level bundle and the BAT-file to load the WAD with -fast parameter.
If I load the game before the demo loop starts, the game starts properly.
If I load the game after the demo starts, the -fast parameter is lost.
[demo_still_resets_params.zip.txt](https://github.com/fabiangreffrath/crispy-doom/files/844072/demo_still_resets_params.zip.txt)

**Comment by fabiangreffrath** [comment]
I see, `G_DoLoadGame()` calls `G_InitNew()` which does not touch the game parameters, whereas `G_DoNewGame()` does. *sigh* So, the game parameters are preserved if you start a _new game_ after the in-game demos have started to play, but not if you load a game. /o\

**Comment by fabiangreffrath** [comment]
Ok, so we want to re-read the game parameters from command line when we load a game or start a new game, but not when we play a demo. Now comes the question: What do we do if we play a demo starting from a savegame? This case really makes the whole thing a lot more complicated.

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
>Now comes the question: What do we do if we play a demo starting from a savegame? This case really makes the whole thing a lot more complicated.

I deem that when starting from a savegame, the parameter should be the same that has been used recording the demo, and that one was likely applies from the command line, i.e. re-read it from command line.

**Comment by fabiangreffrath** [comment]
So you suggest:
new game --> read from command line
load savegame -- > read from command line
play demo --> read from demo
play demo from savegame --> read from command line

right?

**Comment by Zodomaniac** [comment]
@fabiangreffrath As youo say here that it's possible to read parameters from demo, I think
let it then be:

new game --> read from command line
load savegame -- > read from command line
play demo --> read from demo
play demo from savegame --> read from demo

as the savegame has no parameters stored and the demo does have.

**Comment by fabiangreffrath** [comment]
I agree, but this makes things much more complicated. ;)

**Comment by Zodomaniac** [comment]
>this makes things much more complicated. ;)

Complicated implementation-wise, maybe, but logical and expected from the player's point of view :)

**Comment by fabiangreffrath** [comment]
Absolutely! I think I have found a way to fix this "uncomplicated". ;)

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
Yeah, it works properly now, exactly as expected! Brilliant :)

**Comment by fabiangreffrath** [comment]
Phew, thanks! \o/
