### ISSUE TITLE
[Suggestion #51] Add frag statistics for Deathmatch games

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#160]
I think this is totally aesthetic "must have" feature, that must not break any compatibility, and it is possible to use only standard graphics. Here's the mockup, very first conception for non-colored texts:

![Non-colored texts](http://i.imgur.com/oyzHmSe.png)

And for colored:

![Colored texts](http://i.imgur.com/zN1kJ6E.png)
_Note: I have dimmed background pickture for better reading of mockup elements._ 

**Some additional ideas:**

- Let it be automatically show after player's death.
- Add ability to show stats on pressing button. Traditional binding is `TAB`, but it's already used for Automap, so maybe `Q` will be good? 
- Question of the day: must it be displayed only while `Q` is pressed? Or first `Q` must show stats, and second `Q` hide them? Need some brainstorming here.
- Let's try to make some additional color translations, if we don't have them (uh-oh).

**Comment by Zodomaniac** [comment]
>Traditional binding is TAB, but it's already used for Automap, so maybe Q will be good
Q is common to finish recording demo, and as netgames in Crispy don't allow jumping, let this fragstat display button be Space, I think) as Use is commonly bound to E.

**Comment by JNechaevsky** [comment]
Yep, and two additional suggestions for default binding:

- `F` since we don't have flashlight or items to use.
- `~` since it located just above `TAB`, but not recommended because of totally uncomfortable pressing by ring-finger.

**Comment by Zodomaniac** [comment]
> F since we don't have flashlight or items to use

Yes, F for Frags, you're right! And ~ is bad because there's a high chance of pressing TAB accidentally.

**Comment by fabiangreffrath** [comment]
Guys, thanks for the suggestion! It's nice that you already argue about which will be the right key to press. ;p

But I hope you are aware of the fact that this is quite a *major* request for a fork that has promised to remain as close to its ancestor as possible?

**Comment by Zodomaniac** [comment]
> But I hope you are aware of the fact that this is quite a major request for a fork that has promised to remain as close to its ancestor as possible?

IMO it's as major as existing features like Physical ones, or am I wrong?

**Comment by JNechaevsky** [comment]
@fabiangreffrath 

Hmm, well, you right. Thinking of how to make this feature optional and not to overload Crispness menu, at the moment I can offer only something like on this mockup:

![Stats](http://i.imgur.com/MJIE0qd.png)

Sorry, I can't offer something more smart now - some VERY good things happened, and I still can't focus my mind after all emotions feelings and nerves. Need some more time to concentrate. :)

**Comment by Zodomaniac** [comment]
>some VERY good things happened

Congrats!

**Comment by JNechaevsky** [comment]
Spasibo, Zodomaniac :)

Okay, I'm back on Earth (well, partially). Thinking more clearly, I can say that my previous idea with "Join multiplayer game" is totally bad, since it's also a question of keybinding, rather than only optional feature, plus, we need something more "global" for this.

Here's new suggestion:

- First of all, we need a place for keybinding. I believe that perfect place for this is right here: http://i.imgur.com/7BmUkNA.png, or maybe even better right above "Send message".
- Next, we need more common place, if want to make this feature optional (and it's only on client side, right?). Maybe here: http://i.imgur.com/UFsQEQe.png. But need to be careful, that menu is heavily loaded already and we can add only 1 new line for proper look.

I think that's better now, but more brainstorming is still necessary.

**Comment by fabiangreffrath** [comment]
But guys, Doom already has a score board, it's shown on the intermission screen after each map:

https://doomwiki.org/wiki/File:Imscrndm.png

What if I added a key to show this board in-game and also show it when the player dies?

Regarding the key, I 'd rather prefer F1, since it should be totally uncommon to search for the help screen during a multiplayer game and it is close enough to TAB as well.

**Comment by JNechaevsky** [comment]
Hmm. This is a very interesting idea, but I think vanilla board looks very bulky for in-match use. While matching, we just want to know our score, not detailed statistics. I've also have a bad feeling that even if whole board will be moved a little bit up, it will still be overlaying traditional Doom HUD which will not be nice.

Probably we need just a `TOTAL` counter, but how it should be placed, and how players should be defined there - another good questions.

Quick suggestion - while match, place `TOTAL` just like in the intermission screen, i.e. not centered with colored squares behind the digits. Or it will be better if I'll make a mockup?

**Comment by fabiangreffrath** [comment]
> Or it will be better if I'll make a mockup?

Sure, why not, this would help. Thanks!

**Comment by JNechaevsky** [comment]
Here we go, a few variants. 

**№1.** As i expected, what will happen if we will not change offsets of the board's element. Must not happen!
Mockup: http://screenshot.ru/upload/images/2017/10/12/1_asisdbd64.png

**№2.** Simple implementation of idea of using vanilla-style placement.
Mockup: http://screenshot.ru/upload/images/2017/10/12/2_righta6d26.png

Is it looks traditional and canonical? Well, yes. Is it looks modern and comfortable? Well... Let's just stop on thought that it looks vanilla stylized. Centering this column will be bad idea IMO, it simply overlays game screen.

Another idea for this placement - no need to hold `F1`. Press `F1` once, and this table will be like OSD widget. Press `F1` again and it will be gone. Transparency for colored squared may be not bad idea, especially for upcoming true color mode. The title `TOTAL` (WIMSTT) could probably replaced with `FRGS`  (WIFRGS).

**№3.** Without `TOTAL` title. Hmmm. Hm-hm-hm.
Mockup: http://screenshot.ru/upload/images/2017/10/12/3_notitle6d23f.png

**№4.** Top-centered alignment. Hmmmmph. Probably better than №3, but Isn't it looking too grotesque?
Mockup: http://screenshot.ru/upload/images/2017/10/12/4_top-centereddbc75.png

**Comment by fabiangreffrath** [comment]
I think I like mockup No. 2 the most. It is non-intrusive and the total numbers are in the expected place and order.

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.
