### ISSUE TITLE
add support for textures taller than 256 pixels

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#162]
By @fabiangreffrath request.

The engine renders well textures 512px wide, but not taller than 256px. 
Example map can be downloaded here: http://jnechaevsky.users.sourceforge.net/files/512x512.wad

**Comment by fabiangreffrath** [comment]
@JNechaevsky Thanks for the test map. could you probably provide a map with a tall mid-texture as well?
