### ISSUE TITLE
Cannot mouselook up or down in certain demos

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#163]
Cannot mouselook up or down in IWAD in-built demos or multiplayer ones like this [Altdeath demo.zip](https://github.com/chocolate-doom/chocolate-doom/files/737359/Altdeath.demo.zip)
In the Infested Outpost demo I recorded I can look up and down, though.
Looking up and down in demos is useful to know where the damage was coming from (possibly from above/below in a fight on steep stairs).

**Comment by fabiangreffrath** [comment]
Apparently it makes a difference if the demo is played via `-playdemo` or as part of the demo loop.

**Comment by Zodomaniac** [comment]
I play both the multiplayer demo and Infested Outpost demo with `-playdemo` but in the former I cannot mouselook up/down, and in the latter I can.

**Comment by fabiangreffrath** [comment]
To tell the truth, you aren't supposed to change the view when playing a demo *at all*. The real bug is that it is currently possible to do so for some demos. ;)

**Comment by Zodomaniac** [comment]
I'm glad this ambiguity has been eliminated, no matter which way ;)
