### ISSUE TITLE
different crosshair types

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#164]
Curently, Crispy uses the plus ('+') character of the built-in HUD font as a crosshair. However, we should give the choice of some additional common shapes, e.g. dot ('.'), circle ('o' or '0'), dash ('-' or '_'), cross ('x') and angle ('^').

This is @JNechaevsky suggestion # 10.

**Comment by Zodomaniac** [comment]
I think they should differ only in static mode, the projected crosshair is a laser dot so it should logically look and behave the way it does now, regardless of the symbol selected)

**Comment by JNechaevsky** [comment]
My additional two rubles:

Make health indication (green/yellow/red) for crosshair, but only if ... colored texts + hud enabled? 
Maybe not very idea, need some brainstorming here.

**Comment by fabiangreffrath** [comment]
> I think they should differ only in static mode

Although you are right logically, we should not be too strict and impose unnecessary restrictions. Just play around with it a bit, the "angle" actually looks pretty neat as a projected laser spot. And while at it, laser aims are also never "crosses" in real life. ;)

> Make health indication (green/yellow/red) for crosshair

I know this is in PrBoom+ and I actually like the idea, But I am afraid I will need a separate menu for the crosshair (again, just like PrBoom+) if I add any further options to it.

**Comment by Zodomaniac** [comment]
>And while at it, laser aims are also never "crosses" in real life. ;)

OK, I perceived it as a pixelated laser dot though, that's why I'm OK with the cross ;)
