### ISSUE TITLE
cap framerate when window inactive

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#165]
There is a variable called `screenvisible` which is set to `1` when the screen is visible and `0` otherwise. It is currently used to decide whether to render the scene or not, but we should also use it to cap the game when its inactive.

This is @JNechaevsky suggestion # 22.

**Comment by JNechaevsky** [comment]
Uh-oh, I have noticed, that SDL2 branch already have this:
https://github.com/chocolate-doom/chocolate-doom/blob/sdl2-branch/src/i_video.c#L349

I have checked it, and I think I can confirm that while minimized, Chocolate's CPU usage is equals to 0%, even if there's some activity like demo playing. Guess this is good enough. :)

**Comment by fabiangreffrath** [comment]
Perfect, this makes it easier.

**Comment by fabiangreffrath** [comment]
Since Crispy Doom is now built on SDL2, this issue has mostly fixed itself. ;)
