### ISSUE TITLE
Add texture smoothing (SDL2 only)

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#166]
Chocolate's SDL-2 branch have this two lines:

https://github.com/chocolate-doom/chocolate-doom/blob/sdl2-branch/src/i_video.c#L689
https://github.com/chocolate-doom/chocolate-doom/blob/sdl2-branch/src/i_video.c#L1280

And it easy to make an optional texture smoothing. Well, for Chocolate's traditional 320x200 it looks interesting, rather than good, but maybe for Crispy's high resolution it will looks better.

Note: despite of it's easiness, some additional work must be done in... Picture buffer or something like this (not competent enough to say for sure), because after smoothing, one pixel of frame borders are mirroring opposite side, like this (click for enlargement, it's not easy to see):

![doh](http://i.imgur.com/9dq1Fbc.png)

My suggestion here:
- Make an optional texture smoothing, an option for this should be placed in Display > Advanced. This may be considered as a step forward for players, who prefers to get smoothed picture.

I'm not going to offer this for Chocolate project since it must be absolutely unacceptable by Chocolate's Philosophy.

_(Suggestion №52)_

**Comment by fabiangreffrath** [comment]
Oh, thanks for the suggestion. I was to tell you but somehow forgot: You probably shouldn't change the scaling quality from the intermediate texture to the upscaled texture to anything but "nearest" (line 1280). The upscaled texture is really only meant to be an integer multiple of the original framebuffer. It is likely that you see the artifacts because you are creating a "washed out upscaled copy" of the original framebuffer and then scale this down to screen.

**Comment by JNechaevsky** [comment]
Thank you very much for explanation for explanation. 
Tried this, but no luck - if line 1280 changed to "nearest", there is no smoothing at all, no matter what is present in line 689 (which, I believe, stands for different function).

**Comment by fabiangreffrath** [comment]
Hm, strange. Maybe this becomes more apparent if you reduce the rendering screen size. It will be less visible on a full-HD display than in a, say, 800x600 window.

**Comment by JNechaevsky** [comment]
Seems to be so, I was trying this on my 27" full-HD monitor :) Here's three tests:
- 1920x1080, full screen: http://i.imgur.com/IAuCHtc.png
- 1920x1080, full screen, screen size reduced by one: http://i.imgur.com/iHYgOA2.png
- 800x600, windowed: http://i.imgur.com/EgWBILY.png

This problem is not appearing on reduced screen size. Maybe "blacking out" screen borders by 1px may help, but this sounds like a bad plan, rather than hack or proper solution. I need to think more, my "design creativity" is definitely not good thing here.

**Comment by fabiangreffrath** [comment]
That's sure interesting, but I was actually talking about the blurring. Does the picture look smoother if you play with a 800x600 window although you have set the scaling quality for the intermediate texture to "nearest"?

**Comment by JNechaevsky** [comment]
Not sure I'm understanding. "Nearest" scaling is default for Chocolate and the intermediate texture, and does not making any smoothing at all. 

![pic](http://i.imgur.com/l61YLx9.png)

**Comment by JNechaevsky** [comment]
So, that's how smoothing looks in 640x400 resolution with standard palette: http://i.imgur.com/WIbkFSk.png
Hard to say is it good or is it bad, actually, really no idea. But at least it's have a right for existence.
Too bad that SDL can't offer something like HQ scaling outside the box.

**Comment by JNechaevsky** [comment]
Now now this idea takes a new route: https://github.com/JNechaevsky/russian-doom/commit/d3409241dae2c056aeff8d9fe8ff15f94016e102

In general terms, completely disabled smoothing gives +1 fps and makes whole game picture more crisp and sharpen.

**Comment by fabiangreffrath** [comment]
There is already a switch to disable "smooth scaling" in Crispy Doom from release 5.0 on which circumvents the intermediate texture and renders the framebuffer plainly to screen using "nearest" scaling. There won't be any "even smoother" or "even less smooth" setting, so I consider this fixed by now.
