### ISSUE TITLE
Indication showing that the player is gibbed

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#167]
A squashed head in HUD mugshot or showing a gibbed player sprite (of respective player color) instead of health value as I siggested before - whatever, as discussed here https://github.com/fabiangreffrath/crispy-doom/commit/26fefca57289eef396133e2c5b8608d0cda241e5

**Comment by fabiangreffrath** [comment]
Where am I supposed to get a squashed head for the status bar? I will try how it looks to draw the gibbed player sprite in the health widget, though.

**Comment by fabiangreffrath** [comment]
Update: I tried it and it does barely fit. Not sure I really like this:

![doom0001](https://cloud.githubusercontent.com/assets/6449237/23811425/40b164ee-05d6-11e7-9b4f-9d8cc0d29219.png)

**Comment by Zodomaniac** [comment]
> I tried it and it does barely fit. Not sure I really like this:

I'm OK with it ;)

**Comment by Zodomaniac** [comment]
Another idea I've had: if the player is gibbed, assign him -111% health (the narrowest 3-digit number that should fit in the HUD health section).

**Comment by Zodomaniac** [comment]
P.S. In case of gibbing, the player health could also use a blooded font like the 'Nightmare!' skill menu item.

**Comment by fabiangreffrath** [comment]
This is a nice idea, but unfortunately the "Nightmare!" skill menu item is not rendered in a font that's available in-game but is a single graphic lump instead.

**Comment by Zodomaniac** [comment]
Then I suppose the gibbed player sprite instead of health value would be nice) I like the screenshot you posted here)

**Comment by fabiangreffrath** [comment]
Hey guys, i have sometihng in the pipe, but I need to know if it breaks demo compatibility. Now I need a multiplayer demo in which the players are gibbed as often as possible. The more complex the better. Preferably a co-op demo through multiple maps.

**Comment by JNechaevsky** [comment]
Hmmm... Many things I can contribute and/or suggest, but here I'm useless, sorry. Never was playing netgames much, neither looking it's demos. Googling gives me no necessary results, so all I can offer is to check DSDA archive, maybe something useful can be found there: http://doomedsda.us/deathmatch.html

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
> i have sometihng in the pipe, but I need to know if it breaks demo compatibility

The gibbed player sprite in the HUD health section won't break it, so why not use it?)

**Comment by fabiangreffrath** [comment]
You really want this, heh? ;)

What's wring with knowing that -99 health in the status bar means about the same?

**Comment by Zodomaniac** [comment]
>You really want this, heh? ;)
What's wrong with knowing that -99 health in the status bar means about the same?

Well, it adds even more dynamics to DM, showing the gibbed player his gibs as he's rolling back half a map long after a rocket to the face))

**Comment by fabiangreffrath** [comment]
I see. I have an idea that you might like, but I am not sure if it will work yet. ;)

**Comment by Zodomaniac** [comment]
Nice. thanks! Is the gibbed sprite intentionally limited to Crispy HUD and -99% still shown in Vanilla HUD?

**Comment by fabiangreffrath** [comment]
Yes, this is intentional for two reasons: First, the death animation sprites do not fit properly into the Health widget area of the status bar background and it would look really weird if it was rendered there. Second, I would like to preserve the classical status bar as a clean fallback for Vanilla purists.
