### ISSUE TITLE
Music is still playing/hearable when it's volume set to "0"

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#170]
This seems to be pure vanilla bug. It is barely possible to hear it, but setting system sound volume to higher values makes it hearable.

_Suggestion №54_

**Comment by JNechaevsky** [comment]
Take a look: https://github.com/JNechaevsky/russian-doom/commit/e2a7fcc3982f3c6ed4b82a7619456458551df148

I think it is good enough for fixing this issue.

**Comment by fabiangreffrath** [comment]
Does this happen with both OPL and "native" music?

**Comment by JNechaevsky** [comment]
Yes, it is happens with both OPL2/OPL3 modes, as well as with Vanilla Doom2 1.9 executable.

**Comment by fabiangreffrath** [comment]
Does it also happen if you select "Native MIDI" (instead of "OPL") as the music playback device in the setup tool?

**Comment by JNechaevsky** [comment]
Hm, everything seems to be okay with Native MIDI. I can't check GUS, because it does not seems to be working for me, despite of located patches from Doom III BFG.

**Comment by Zodomaniac** [comment]
@JNechaevsky 
>I can't check GUS, because it does not seems to be working for me, despite of located patches from Doom III BFG.

I've checked GUS, it's OK. The bug seems to be present with OPL only.

**Comment by fabiangreffrath** [comment]
But if it matches the behaviour of Vanilla, it's actually an adequate emulation, isn't it?

**Comment by Zodomaniac** [comment]
Well, yeah, it's what Choco team would preserve.

**Comment by fabiangreffrath** [comment]
Damn typos, it's late...

**Comment by mfrancis95** [comment]
Anything wrong with using the code by @JNechaevsky? I'd like to see this fixed.

**Comment by fabiangreffrath** [comment]
Maybe @nukeykt can help here. It is currently impossible to entirely silence OPL music even if the volume slider is set to 0 in game. Is there a simple way to fix this?

**Comment by nukeykt** [comment]
Unfortunately this is OPL chip's limitation. Ideally we should just clear mixing buffer here when music is muted:
https://github.com/fabiangreffrath/crispy-doom/blob/master/opl/opl_sdl.c#L166
But i have no idea how to tell to the driver that music is muted.
Another way is pause music when it is muted.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, but it is possible. `I_PauseSong` is doing it's purpose, just take a try my code, you'll see _(erm, hear)_ a difference. Perfectly good place for testing is MAP01 where you still can hear a music while music voluve == 0 with vanilla code.

**Comment by fabiangreffrath** [comment]
@JNechaevsky The reason why I haven't merged your code yet is (1) that it doesn't fix the code where the glitch is, i.e. in the OPL code, and (2) that I don't like the idea to unconditionally call the resume code even if the volume is changed between two non-zero levels.

**Comment by atomizer** [comment]
This still happens in 5.11.1 on startup and after a level change. Going to sound options and wiggling the music slider turns it off until the next level.
