### ISSUE TITLE
Idea for full length sounds

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#171]
Pressing `USE` key on walls and falling from height while firing breaks firing sounds. This seems to be is because of both firing and oof sounds are generated by `player->mo`. So maybe `crispy_fullsounds` can take care of this? I mean, when it's set to `1`, there will no be any breaks. Or even maybe it is worth to fix this bug at all.

The only thing that makes a big sense here is a [silent BFG trick](https://doomwiki.org/wiki/Silent_BFG), but again, this fix may be done only for single player.

Video demonstration of breaking sounds: https://youtu.be/Okt692mndQo

_Suggestion №55_

**Comment by fabiangreffrath** [comment]
Yes, sounds in Doom are indeed limited in that each sound source may only play one sound at a time.

Why would we want to change this, what would we gain? We would destroy a popular multiplayer trick and need to add another `if (singleplayer)` guard (which I don't like at all).

**Comment by JNechaevsky** [comment]
We will gain more proper and realistic logic in playing sounds. In simple words - player's mouth and player's gun are different sound sources, they must not cut off each other.

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
Sorry for derailing the discussion...
@JNechaevsky 
I guess I should write here to invite you to a bike ride as you don't respond elsewhere)
Call me on the cellphone, I'm rolling out soon)))

**Comment by fabiangreffrath** [comment]
> player's mouth and player's gun are different sound sources

This is really clever! ;)

**Comment by JNechaevsky** [comment]
Hey, don't get it too serious! But it's as a fact. 😏
I have made a simple hack for preventing in my fork, but I'm not sure it will be good enough Crispy, since it's all of `if (!singleplayer)` stuff.

**Comment by JNechaevsky** [comment]
Just a little update.

My `singleplayer` hack that prevents player's firing sounds breaked by "oof!" is working fine, I've got what I want. But since it is completely unacceptable for Crispy, I think there must be another way, without using of `singleplayer`.

Some abstract thoughts... Please consider this only as idea.

For proper prevention of breaking in single/netgame/demos, there must be some kind of additional definition, along with `player->mo`. I think, less painful it will be using something like `actor->mo` for "oof!" sounds, while `actor` will be acting just like `player` (i.e., have sound radius, distance and so on).

This way it is possible to get something like two sources for one object. One for "oof!", another for firing.

- Is it safe for in therms of possible desynchronizations? No idea honestly, I can't imagine. Possibly will require some additional defining of what the heck is `actor`.
- Is it worth at all? Only you must decide it, so as usual, only at your discretion.

**Comment by JNechaevsky** [comment]
Ahh, so this is what "sound objects" code stand for. I saw it, but have not learned, since never was working with sounds much. Glad to know, anyway!

As for BFG trick, I think it is still be possible to strictly use `S_StartSound (player->mo, sfx_bfg);`.
This must be a proper and safest solution, especially without `singleplayer`, because normally the player have no need to use this trick in single player.

**Comment by fabiangreffrath** [comment]
Hm, yes, good point. So, all gun sounds would originate from the sound object connected to the player, with the exception of the BFG which would still come from the actual player map object.

**Comment by Zodomaniac** [comment]
So how should it work now, if Full length sounds are set to 1, even the players with Choco clients won't be able to cheat me with silent BFG trick in multiplayer, right?

**Comment by fabiangreffrath** [comment]
No, the silent BFG trick is preserved on purpose, regardless of the "full length sounds" setting.

**Comment by Zodomaniac** [comment]
So what has changed at all with implementation of weapon sound sources?

**Comment by fabiangreffrath** [comment]
Sounds emitted by player's weapons do not interfere with sounds emitted by player's mouth (i.e. "oof!") anymore. Try, for example, to jump off a ledge while firing the chaingun.

Also, the chainsaw "up" sound now seamlessly transitions into the "idle"sound.
