### ISSUE TITLE
Suggestion for the quick loading

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#173]
Maybe it might be a good idea to "speed up" a little bit quick loading process by disabling confirmation dialogues. For example: confirmation dialogue must appears only on first quick saving, but further quick savings/loadings must not have it. Just press `F6` to quickly make quick save and `F9` to make a quick quickload. Maybe some simple text message like "quicksaving loaded" will be also good.

Or -- to don't break canonical Doom menu confirmations, just increase ticrate for wiping screen to *2 or *3 on quick loading, because we are making "quick" loading, right? 

_Suggestion №58_

**Comment by fabiangreffrath** [comment]
There is no way I can remove the confirmation dialog. People have "brain muscles" which are trained to certain sequences of key presses. If I break these sequences there will be angry bug reports asking me to immediately revert back to the original behaviour.

I like the idea of speeding up the wiping animation, but on the other hand it will feel weird because everyone knows this animation by heart and has a feeling for how long it is supposed to take. I am really not sure and this is admittedly low on my priority scale.

**Comment by JNechaevsky** [comment]
Ah, got it. The last thing I can suggest here - make screen wiping optional, at least as config variable.
This can be very useful for debugging: often saving/loading, loading created maps and so on.

Suggested solution here is rather simple: https://github.com/JNechaevsky/russian-doom/commit/94b66ff5d2ff27073883736bac39989cc2850c83

**Comment by JNechaevsky** [comment]
Oh, no-no-no. Here's the last one. I have found that combination of disabling wipe effect + disabling quick loading prompt gives a very interesting effect. Don't get me wrong, it's definitely not a feature(s) for gameplay, but suitable "must have" for debugging or map editing purposes.

Just for example:  https://youtu.be/Ho_ZtU4adAI

Note, that "shacking" is actually quick loading. With this speed it looks similar to saving/load states on some kind of console game emulator.

**Comment by fabiangreffrath** [comment]
> Note, that "shacking" is actually quick loading. With this speed it looks similar to saving/load states on some kind of console game emulator.

I admit this looks really impressive and might bear the potential to speed up debugging a lot. But on the other hand I am not really sure if this has a place in Crispy Doom (because it doesn't "look and feel like Doom" anymore, you know?).

**Comment by JNechaevsky** [comment]
Oh yeah, completely understandable. My way is absolutely unacceptable here, because I have two separate functions for this: one is "gameplay" feature (prompt), another is "experimental" video feature (wipe).

Maybe even having a one config variable for both of this will be bad for Crispy.
But maybe having only a command line argument like "-debugmode" will be okay. Thinking more, this argument may be good for bringing something more for the future, but no any ideas what exactly for now.

**Comment by fabiangreffrath** [comment]
Sorry, but I don't think this has a chance for inclusion in Crispy.
