### ISSUE TITLE
Suggestion for Zombiman firing frame

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#175]
I honestly don't know why it takes forever for me to note this: Zombieman have missing fullbright flag on firing frame. Here's how it looks -

Before: http://i.imgur.com/xaCts2E.png
After: http://i.imgur.com/JnSRJLg.png

Solution: absolutely simple and safe (https://github.com/JNechaevsky/russian-doom/commit/a9fa1749da93a1d7f9e94ba3e39d091db3a73004)

But. In case of accepting, I'm kindly asking you to think twice, let me please explain why. Years of playing Doom and don't notifying this bug can make some surprise for vanilla purists, despite of all logic and graphical design of the shooting sprite. This fix was okay for Cyberdemon, since he is not very often enemy in the game, and his firing flame is notably big to have fullbright flag.

Even for me it takes one minute to reorganize my feeling of the game. From another hand, vanilla purists should use Chocolate Doom.

At your discretion.

_Suggestion №60_

**Comment by fabiangreffrath** [comment]
Good catch! 

And also, good point about the "feeling" of the game and Vanilla purists. You know that I feel exactly as you do in this point. On the other hand, in a case like this, I am also in favour of game *logic* (c.f. dead players making "oof" sounds and similar issues) and I think that if firing frames are bright, they should be for all monsters.
