### ISSUE TITLE
Suggestion about Crispy icons on Windows

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#177]
I have noticed that Crispy icons for Windows binaries looks blurry. This is because icon files have only 32x32 size, take a look at this example (make sure to set web page's zooming to 100%, it's important):

![icons](http://i.imgur.com/OCJVnsd.png)

Solution: use these icons - http://jnechaevsky.users.sourceforge.net/files/crispy_icons.zip
Both of them contains all necessary sizes for Windows (128x128, 64x64, 48x48, 40x40, 32x32, 24x24, 20x20, 16x16) with bicubic reduction sharpening and should be placed in the sources subfolder data/.

The result must be like this:

![new_icons](http://i.imgur.com/cOSOOSV.png)

Also please note that Windows OS can't use PNG files as icons, so maybe it is not necessary to put PNG files into Windows binaries archive.

_Suggestion №62_

**Comment by JNechaevsky** [comment]
I was using @Zodomaniac's 128x128 PNG icon for this.

But. Looking into my SDL2 I have noticed that there is still a difference between `convert-icon` data (which is used for window title), and program icon itself. Opening my executable with icon editor, I can see this icon array: http://i.imgur.com/tMY4Ujd.png and exactly this .ico array is used by Windows to draw icons in the desktop/explorer, i.e. not in window title of running game.

**Comment by JNechaevsky** [comment]
Let me show you this visually. I will use my project which is based on January's Chocolate SDL2, since I don't have Crispy SDL2.

- For SDL icon_data I will use standard Doom logo (src/icon.c)
- For Windows icon I will use red cross (data/doom.ico)

Here's all the difference after compilation and rebuilding Windows icon cache:
![icons](http://i.imgur.com/WLloxad.png)

SDL Icon_data and Windows icon are different things, they are not embedded. That's why is is necessary to take care about .ico file.

**Comment by fabiangreffrath** [comment]
So, do you say that simply dropping these two icon files into the `data/` directory will improve the icon situation on Windows?

**Comment by JNechaevsky** [comment]
Absolutely. Just try yourself, you will see the difference. And again, this will improve Windows specific icons only, not SDL stuff (see my screenshot for the reference). SDL1 or SDL2 does not matter here, .ico files does not depend on them.

Fraggle's `convert-icon` script does not do anything with Windows-specific icons, it's only generates data for 'icon.c' file, which is used by SDL only.

**Comment by JNechaevsky** [comment]
To be 100% perfectly clear about my screenshot: red cross is .ico, doom logo is SDL data.

AFAIR, I was suffering same problem with SDL data while my project was based on Chocolate SDL1. 
SDL1 was strictly limited to 32x32 and does not having proper alpha channel / true color (32 bpp) support.

**Comment by fabiangreffrath** [comment]
The `icon.c` file is generated from the content of `doom8.ico`, c. f. https://github.com/fabiangreffrath/crispy-doom/blob/master/src/Makefile.am#L275

**Comment by JNechaevsky** [comment]
Ah.. I forgot about that, since my last work with SDL1 was in far October 2016.

Any way, my last accord here: please keep in mind that Windows must have icons with different sizes in .ico files for proper displaying. This OS knows how to up/downscale .icons, but the result will not be always looking good, since it using very simple algorithm to do this. Having having only one 128x128 size in .ico file will not give properly looking or aesthetically good result. 

Trust me, it's Windows OS + graphical design specifics.

**Comment by Zodomaniac** [comment]
If I don't do my best,
My soul will never rest,
And I will go to dwell
Eternally in hell!

Improved the icons using another portion of the crisps image, so that the yellow sharp corner of the D stands out more, and so that there is no need to make the crisps more pale.
![crispy-doom_shifted](https://cloud.githubusercontent.com/assets/15119473/25233521/b73241a2-25e7-11e7-9b39-7d20da4c513f.png)
![crispy-doom_shifted_setup](https://cloud.githubusercontent.com/assets/15119473/25233520/b72ba1f8-25e7-11e7-9ad7-9aa7a170e8b1.png)

**Comment by fabiangreffrath** [comment]
Cool, thanks! Now we need @JNechaevsky to create the multi-resolution .ICO files out of it.

**Comment by JNechaevsky** [comment]
I have a better idea - recreate these icons to make them less blurry and more perfect.

Here, recreation from scratch using Fraggle's [SVG vector sources](https://github.com/chocolate-doom/icon), Zodomaniac's idea of new background placement, and little edging shadow:

512x512:
![Crispy](http://i.imgur.com/iWmkeNB.png)
![Setup](http://i.imgur.com/eGGRuoN.png)

128x128:
![Crispy](http://i.imgur.com/UUbJCxU.png) ![Setup](http://i.imgur.com/1Zd41sY.png)

All the stuff here: http://jnechaevsky.users.sourceforge.net/files/even-crisper-full.zip

Archive includes:
- Multi-resolution .ICO files (from 8x8 to 128x128, not really sure that Windows needs 256x256).
- .PNG files of all necessary sizes (from 8x8 to 512x512). May be useful for Linux.
- 512x512 pixel .PSD source with vector icons included.

For composing ICO files I'm using [IcoFX](http://icofx.ro/). In short words, just drop PNG file to it and choose "Create a Windows icon from the image". However, it does not offer perfect enough algorithm for image downscaling. For downscaling and overall raster graphics editing I'm using Adobe Photoshop, for vector gfx editing I'm using Adobe Illustrator.

**Comment by fabiangreffrath** [comment]
Thanks, guys, these icons look *bam*!

**Comment by JNechaevsky** [comment]
I must admit that it's a long story with sad final, why I have become very sensitive with icons.

Almost five years at Paragon Software and setting up a tasks for creating electronic dictionary icons for such famous brands like PONS, Langensheidt, Duden and Wahrig, and... Well. Let's just say - it's my pleasure. I'm happy that my work is liked and accepted, as well as my skills have found good applying.

**Comment by fabiangreffrath** [comment]
> I'm happy that my work is liked and accepted

It is (both, and not only limited to the icons!), thank you very much again!
