### ISSUE TITLE
HUD weapons 1px higher ... again

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#179]
I remember there was a fix in Crispy's code for this, but looks likes it happens again:
https://youtu.be/jMCO8iO7sPk

Note, that I'm still using that fix and it still working fine.

_Suggestion №63_

**Comment by fabiangreffrath** [comment]
This?
https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/r_things.c#L735

**Comment by JNechaevsky** [comment]
Seems to be so.

**Comment by fabiangreffrath** [comment]
Fixed again in https://github.com/fabiangreffrath/crispy-doom/commit/a788f63a69382629545aec7d70717f7487a8d88e
