### ISSUE TITLE
Cannot hit switch in Brotherhood of Ruin MAP01

### ISSUE THREAD

**Issue by SenhorFlibble** [fabiangreffrath/crispy-doom#180]
In the Brotherhood of Ruin mapset, in MAP01 it appears impossible to hit the switch in the elevator that takes you to the super shotgun. This occurs in v3.5 and v4.0 (haven't tested previous versions). Other ports like MBF or Odamex don't have this problem.

**Comment by fabiangreffrath** [comment]
Hi there,

thank you for the bug report. However, there isn't much I can do about this, unfortunately. Brotherhood of Doom is a MegaWAD for Boom and simply not Vanilla-compatible. It uses so-called extended and generalized linedefs, and while I have still not yet completely given up the idea to add support for them to Crispy [1], they are simply not supported now.

[1] https://github.com/fabiangreffrath/crispy-doom/issues/56
