### ISSUE TITLE
Fix par times not being displayed after idclev (Final Doom)

### ISSUE THREAD

**Issue by AXDOOMER** [fabiangreffrath/crispy-doom#181]
I believe you only have to change the 0 for a 1 there: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/st_stuff.c#L956

This should do the trick. 

It was changed in Chocolate-Doom to emulated vanilla.

**Comment by AXDOOMER** [comment]
Final Doom doesn't have par times, so you can probably remove them. In my port, I just added more conditions so they don't show up in TNT or Plutonia here: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/wi_stuff.c#L1500

**Comment by fabiangreffrath** [comment]
I am not exactly sure what you mean? If I start in MAP01 and type IDCLEV29 and then finish the map, the par time "5:00" is displayed on the intermission screen.

**Comment by fabiangreffrath** [comment]
Regarding Final Doom, I think I'd rather set the par times to `INT_MAX` so they are displayed as "SUCKS" (only in singleplayer mode, else this change would break expected output of `-statdump`).

**Comment by AXDOOMER** [comment]
> I am not exactly sure what you mean? 

Sorry, I meant Final Doom.

**Comment by AXDOOMER** [comment]
I don't think it would break `-statdump` if you only do the two changes I suggested in my second comment. What this would do is [hide the par time and the label that says 'par'](https://github.com/AXDOOMER/doom-vanille/commit/466223f97b5ad8fdf2246343b354f856db641d99). In my edit, the other change that I suggested always makes the `cnt_par` variable always equal to `wbs->partime` like I did [here](https://github.com/AXDOOMER/doom-vanille/commit/0ed308bff3c305e220254d6b9f5bd8c5ae8cd73b). This only change what is displayed during the intermission screen, but at the end the variables contain the same thing that they would have after the incrementation of the variables is complete. 

The games that need these fixes are Final Doom and The Ultimate Doom episode 4. With this fix, no need to fix IDCLEV and `-statdump` will work as expected. 

If you set the par times to `INT_MAX`, then on every intermission screen, the player is going to see the par times increase until it reaches 60 minutes and this doesn't look very good.

**Comment by fabiangreffrath** [comment]
For demo compatibility I need to preserve that a keypress during the intermission screen counts up the par time. I will have to check if your suggested fix breaks this.

**Comment by AXDOOMER** [comment]
I didn't think about this case. Then it will break if the player presses the space bar to progress if his time is smaller than the par time and the par time is still being counted while he pressed the space bar. I will have to fix this in my own port.

**Comment by AXDOOMER** [comment]
In my port, I chose not to show them, because they are from Doom II.

In WI_STUFF.C, I changed the code so par times are simply not shown since they are irrelevant. 
```
void WI_drawStats(void)
{
    // ...
    V_DrawPatch(SP_TIMEX, SP_TIMEY, FB, time);
    WI_drawTime(SCREENWIDTH/2 - SP_TIMEX, SP_TIMEY, cnt_time);

    if (wbs->epsd < 3 && !plutonia && !tnt)
    {
	V_DrawPatch(SCREENWIDTH/2 + SP_TIMEX, SP_TIMEY, FB, par);
	WI_drawTime(SCREENWIDTH - SP_TIMEX, SP_TIMEY, cnt_par);
    }
}
```
You could also remove the incrementation sound (pistol sound) if the par time is still incrementing after the time is finished, but that would complicate the code. 

The game mustn't desync and I think it's sufficient. I don't know how far you are ready to go to fix this in 
Crispy Doom.

**Comment by fabiangreffrath** [comment]
>  I will have to fix this in my own port.

As far as I can tell you have broken demo compatibility for your port literally from the first commit on?

> In WI_STUFF.C, I changed the code so par times are simply not shown since they are irrelevant.

So you can hear them being counted up but you don't see anything? I don't find this very satisfying.

> I don't know how far you are ready to go to fix this in Crispy Doom.

Admittedly, this is pretty low on my priority scale. Preserving demo sync is far more important than not showing the wrong par times.

I've also dropped the idea of setting the par times to "SUCKS", because this will result in the same problems if the key is pressed *after* the par times have counted up while recording the demo in Choco and *during* counting them up when playing the demo in Crispy.

**Comment by AXDOOMER** [comment]
> As far as I can tell you have broken demo compatibility for your port literally from the first commit on?

At first yes, but I made it vanilla compatible again while implementing the changes from PCDoom-v2. It should have better demo compatibility than Chocolate-Doom now. 

> So you can hear them being counted up but you don't see anything? I don't find this very satisfying.

In The Ultimate Doom, the intermission screen of episode 4 behaves just like this, so it's good enough for me. I don't want to complicate my code. This is a minor bug and I don't really care about making a complete fix.

**Comment by fabiangreffrath** [comment]
> It should have better demo compatibility than Chocolate-Doom now.

Cool!

> In The Ultimate Doom, the intermission screen of episode 4 behaves just like this, so it's good enough for me

OMG! I just realize that I have single-player par times for Episode 4 in Crispy for ages, but they are never shown. That's probably because nobody ever plays this episode, me included. /o\

On the other hand, I also never realized Final Doom doesn't even have its own par times and the ones from Doom II are displayed instead. I should pay more atention to par times...

**Comment by AXDOOMER** [comment]
These are par time bugs from vanilla Doom that Chocolate-Doom emulates. It was fixed since this commit: https://github.com/chocolate-doom/chocolate-doom/commit/74e95c6130784c5c9bc5fc218e4cac9ba1e25f5e

Episode 4 doesn't have its own par times, they are hidden, but the game reads the par times from the DoomII array. It uses the par times from MAP02 to MAP10 I think. 

The Final Doom executable added a bug where the par times would disappear after using IDCLEV.

**Comment by fabiangreffrath** [comment]
The point is, I have added the par times for Episode 4 for Crispy 1.1 (I have taken them from the Doom 3 BFG Edition source release), but I have never removed the code to hide them on the intermission screen.

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/g_game.c#L1515

Regarding Final Doom: Don't forget that Crispy also supports BEX patches and it is well possible to modify par times in this format. It would be a pity if people invested time to adjust decent par times for Final Doom and they were never displayed. I will have to add a check for this...

**Comment by AXDOOMER** [comment]
> I have added the par times for Episode 4

This could cause desyncs. I sometimes play this episode, but the thing is most multi-level demos that were made were speedruns, so when the players get to the intermission screen, they hit the space bar a few times to skip this screen. In this case, it doesn't desync.

**Comment by fabiangreffrath** [comment]
It's guarded with a `if (singleplayer)` check which is `false` when recording or playing back a demo and during netgames.

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/g_game.c#L1726
