### ISSUE TITLE
Suggestion for the switches texture preserving

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#187]
While I was suffering brightmaps implementation (still no luck, but that's out of question) I have discovered an interesting thing with switches texture: despite of preserving texture in the saved game, animation itself is not preserved.

Here's how it looks: https://youtu.be/h8CY1FW4M7I

What is happening: 

- Normal position/texture of this switch is green light.
- I'm using it, it changes to red. Until it does not go back to green, I'm saving game and restoring it.
- Switch is now freezed to red, but animation is still working if I'll press use again.
- By the completely same procedure it can be freezed back to green, and again to the red color.

Suggestion:

I think that animation sequence is not preserved in saved game, while current texture is still preserved. Perhaps, some additional info about animation sequence or it's timing should be saved in extended format?

_Suggestion №65_

**Comment by fabiangreffrath** [comment]
I am not sure I entirely understand this issue? So, the switch state and the texture animation are saved in the savegame, but the texture is not restoring back when the switch resets after loading a savegame?

**Comment by JNechaevsky** [comment]
Nope, not exactly. Only texture preserved, and after loading it does not resets/changed, until is not activated again.

**Comment by fabiangreffrath** [comment]
Hm, is there even a page on Doomwiki for this bug?

**Comment by JNechaevsky** [comment]
Does not seems to be so, I don't see anything about this on the [DoomWiki](https://doomwiki.org/wiki/Category:Errors_and_bugs).

**Comment by JNechaevsky** [comment]
Digging this a bit more, I think... Savegames have `str->texture`, but also must have some kind of information about `buttonlist`? Or is it `switchlist`? Or maybe something else, presented in `P_StartButton`.
Can't say for sure ATM, still have no 100% understanding of have switches are actually works.

**Comment by jeffdoggett** [comment]
This has been fixed in my port and Doom Retro - an extra savegame structure is required.

**Comment by fabiangreffrath** [comment]
@jeffdoggett Thanks, I'll look into adding this to my text-based extended savegame format.

**Comment by jeffdoggett** [comment]
You can actually add it to the current savegame file without breaking compatibility with the current format.
You add the type 'tc_buttons' to the end of the existing enums.
Obviously an old version of the game will fail if it encounters the tc_buttons type when loading a game saved from the new version if there was a button timeout in operation at the time.

**Comment by fabiangreffrath** [comment]
This would break loading Crispy's savegames in Choco, which is a back-and-forth compatibility that I want to preserve at any cost - and which is also the reason for the hassle I introduced with the extended savegame format (which writes clear text behind the end-of-savegame byte). 

My savegame directories for Crispy and Choco are symlinked into each other. ;)
