### ISSUE TITLE
Suggestion for M_ForceLoadGame

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#189]
In case of pressing `N` in the dialogue window "This savegame requires the file ...", game goes back to the title screen, ending current game. Technically this is seems to be because of Crispy starts to load savegame even before user pressed `Y` on `N` (music is changed already), by querying `maplumpinfo->wad_file->basename`.

Perhaps it will be better, if in case of `N` it just returns to the Load Game section without ending and any attempts of loading?
For example, by querying `basename` stuff first, and all remaining stuff second.

_Suggestion №67_

**Comment by fabiangreffrath** [comment]
Sure, it would be better if this could get checked earlier, but it is really only after loading the level that I know for sure which WAD file the map has been loaded from.

**Comment by JNechaevsky** [comment]
Ah. My only suggestion then - maybe it is possible to implement some kind of "rollback", if loaded level is incorrect for loaded game?

**Comment by fabiangreffrath** [comment]
Hey, it doesn't crash anymore, how's that?

No, just kidding, this could really use some improvement... ;)

**Comment by fabiangreffrath** [comment]
An idea: I could unconditionally save a game (`if (usergame && gamestate == GS_LEVEL)`) whenever the player attempts to load a game, e.g. in slot 99 so it is "invisible". If loading succeeds, fine, the savegame will get overridden next time. If loading is canceled, the savegame from slot 99 is loaded back again and the game may continue where it was interrupted.

**Comment by fabiangreffrath** [comment]
I still like the idea I outlines one month ago, maybe worth tackling for Crispy 4.2...
