### ISSUE TITLE
Suggestion of another weapon firing position option: X-centered

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#191]
I've tried all the weapon firing position options and would like to suggest one more:
the firing weapon to center horizontally only, not protruding to the farthest point like in Centered option.
This is like a mix of Normal and Centered options: the Y-coordinate is preserved, and the X-coordinate is centered.

**Comment by JNechaevsky** [comment]
Hm, and one more from myself: reduced vanilla bobbing to 25-40% of normal. Hard to say exactly what is better, need to see it live, if is wort of any effort of course.

**Comment by fabiangreffrath** [comment]
@Zodomaniac So you mean "Normal", "Horizontal Centered", "Centered" and "Bobbing"? Why, what's the benefit of not changing the vertical weapon sprite position?

@JNechaevsky Hm, another demo breaking change, another option. What's the benefit?

**Comment by Zodomaniac** [comment]
>So you mean "Normal", "Horizontal Centered", "Centered" and "Bobbing"? Why, what's the benefit of not changing the vertical weapon sprite position?

Yes, I do mean this. In case of 'horizontal centered' setting the movement of the weapon from the bobbed and more rear position to the centered one will look not so abrupt and more natural if the Y-coordinate is defined in the bobbing cycle, the weapon moves to the center horizontally only. To make the menu item name not so long it can be called X-centered.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, I was meaning an additional option, "reduced bobbing rate while firing".
But how this local visual effect can break demo compatibility? AFAIK, firing vectors are not changed while bobbing+moving or standing. Or I'm wrong?

**Comment by fabiangreffrath** [comment]
> To make the menu item name not so long it can be called X-centered.

I see. However, I don't like "X-centered", reminds me of X-Men and such crap. How do you like "H-Centered" for _h_orizontal?

> reduced bobbing rate while firing

I see, you only want to apply it while firing. Yes, this should be safe.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, aha, only for firing while moving, and only just as additional option for bobbing of course. Just have a feeling that it may looks more realistic, instead of having full bobbing rate, but I can't imagine what exactly rate will be good enough.

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
>How do you like "H-Centered" for _h_orizontal?

OK, I'm fine with it)
