### ISSUE TITLE
Incorrect health minus position in No End In Sight

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#193]
Maybe the minus offset should be not absolute but depending on the position of other digits?
![minus too high in neis](https://cloud.githubusercontent.com/assets/15119473/25530815/4af33358-2c30-11e7-9032-9b6fdfff02ee.png)

**Comment by fabiangreffrath** [comment]
The thing is, I don't even have control about where the minus sign is drawn. I merely allow the status bar code to draw negative numbers for health values.

**Comment by fabiangreffrath** [comment]
Actually, this is a design decision by the WAD authors. Have a look at the frags counter in the status bar (captured with Choco):

![doom00](https://cloud.githubusercontent.com/assets/6449237/25578503/9f0eb174-2e6f-11e7-975d-0a2d084b3738.png)
