### ISSUE TITLE
Add the new icon data to crispy-doom\src\icon.c for proper icon when compiling with CodeBlocks

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#194]
@fabiangreffrath , when you added the icons overhauled by @JNechaevsky , you didn't update the src\icon.c file. I don't know how to extract the hex color codes from the icon.
Same for Setup icon src\setup\setup_icon.c (though CodeBlocks yields the Setup.exe without any icon at all)

**Comment by fabiangreffrath** [comment]
I did so in a later commit when I merged in some other changes from Choco (I know that's not very clean, but I had no chance to re-create the icon data in the C files on Windows before adding this change to Choco first):

https://github.com/fabiangreffrath/crispy-doom/commit/fc483eeafac4448e06911c887b7eb6453b30a641

**Comment by Zodomaniac** [comment]
Why does CodeBlocks yield an executable with the old icon then?

**Comment by fabiangreffrath** [comment]
Hm, I don't know.

Are you sure it's really the old icon? IIRC The icon embedded into the application is still 32x32 pixels and at that resolution, both icons might look rather similar... But I am really out of ideas here. :(

**Comment by Zodomaniac** [comment]
I looked up the code, must be some CodeBlocks setting.

**Comment by JNechaevsky** [comment]
This must be because of Windows icon cache displaying old icon.

@Zodomaniac, try to clean icon cache. To do this, take a look at:
https://www.sevenforums.com/tutorials/49819-icon-cache-rebuild.html

Option One with batch file working fine. Here's what I have with latest development build:
![](http://savepic.ru/13827970.png)

**Comment by Zodomaniac** [comment]
> try to clean icon cache. To do this, take a look at:
https://www.sevenforums.com/tutorials/49819-icon-cache-rebuild.html

@JNechaevsky 
The dev builds from latest.chocolate-doom.org have the correct icon (and always had), but the CodeBlocks builds still don't. I've tried launching the BAT and rebooting twice.

**Comment by JNechaevsky** [comment]
@Zodomaniac, that's odd. Everything works fine for me:
![](http://savepic.ru/13764513.png)

Try to re-download sources from GitHub and make clean recompiling. No need to update your local source codes by hand after each commit.

**Comment by Zodomaniac** [comment]
@JNechaevsky Thanks! Re-downloading the sources did the trick :)

**Comment by fabiangreffrath** [comment]
> Try to re-download sources from GitHub and make clean recompiling

Shouldn't be necessary. Maybe Windows didn't update the time stamps appropriately or CodeBlocks didn't take notice of it. Please try to open the two source files in question (i.e. icon.c and setup_icon.c) and re-save them explicitly to trigger a rebuild.

**Comment by fabiangreffrath** [comment]
Okay, whatever. ;)

**Comment by JNechaevsky** [comment]
All right, we did it! :-)

Just FYI - CodeBlocks is watching file changes properly, and always recompiling them if they are changed. I can guarantee this for sure after almost of year working on my project.
The very last thing I would like to recommend for source code editing in Windows - to use NotePad++ text editor. CodeBlocks text editor not even close to NP++ functionality and appearance.

_And sorry for this last small offtopic, but strange self-idea comes just now: to learn VIM one day. 
Heh, *that's* will be a real challenge!_

**Comment by fabiangreffrath** [comment]
Knowing VIM is a good thing if you happen to work on different computers regularly, or have to log-in yourself on a remote computer over SSH. But, really, VIM is different from VI, i.e. the original editor. I just don't master it and regularly screw up my files when I have to use it (I just remember 'I' is for insert and 'a' is for append, but everything else - even pressing a cursor key - seems to instantly kill my files.)

**Comment by JNechaevsky** [comment]
Oh, I have some basic experience with BASH, but not much of it. I saw some videos of explanation why VIM can be good, but I believe having a gui editor is the best way for gui desktop environment. Any way, `mc` and `nano` are good and simple things for the console.

The main problem of why I'm not interested much in Linux is not a laziness, nope. I'm too powerful Windows user, and all the stuff is working for me here (gfx/video/audio editing, office, etc, etc, etc). Please do not consider this as showing off! I'm really happy to apply my Windows-specific skills to make some assistance for both Chocolate and Crispy project. As far as i can see, most of the Crew using Linux/OS X, and I can add my two cents of Windows stuff. Too bad that not as a programmer... But it's a story of another day. :)
