### ISSUE TITLE
replace shaded background (menu/pause) with shadowed text

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#195]
I am playing the thought to remove the shading of the background when the menu is active or the game is paused.

I get regular requests to remove this feature or at least make it optional, and since I don't *want* to make it optional, I have to consider removing it. The reason why it was added in the first place was that the red letters of the menu would blend unfavorable with the red numbers of the Crispy HUD, thus making it hard to distinguish the menu from actual game content.

I think I can counteract this by adding shadows to the menu graphics (at least the ones representing text), so there is a clear distinction between menu text and status bar.

It would look like this:

![doom0004](https://cloud.githubusercontent.com/assets/6449237/25700284/5a13ef30-30c7-11e7-9207-2d3197a9e532.png)

What di you think, better or worse than before with the shaded background?

**Comment by JNechaevsky** [comment]
YES!!! Allow me, please! You know my sympathy to the shadows already, so I'm thinking this is absolutelly nice idea, just need some work. Couple of ideas for improving:

- Make shadows transclucent. They are looking too agressive if opaque.
- Use `y+1` and `x+1` for shadow offsets. Raven's default `+2` is not very good for menus, it's making shadows too big, especially when there are many elements.
- For big red HUD digits, I belive there is only one safe option, like it is done in ZDoom - gray color (#2f2e2e, or maybe it is using color's palette number, don't know for sure) is transclucent, it's working as shadow.
- For small HUD digits - I have a feeling that better don't touch them.
- And finally, shadows better to be optional (but let them be enabled by default), to preserve some vanilla-looking ability.

And yes, this is looking very gracefully: `tinttable = cr[CR_DARK];`
I even was not thinking that it is possible. 👍

**Comment by fabiangreffrath** [comment]
Ah, and just for the record, I am *not* going to add any shadows to any element in the status bar!

**Comment by JNechaevsky** [comment]
> they are not even recognizable anymore.

No-no-no-no-no, take a look: http://savepic.ru/13811254.png. This is `x+1` and `y+1`, i.e. shadows are moved 1px right and 1px down. This way they are not huge, but still notable.

Regarding HUD - ah yes, you right. Some hacks like `if (chexquest)` may helps, but no, it's a diffenetly bad idea to support all the games/mods for proper shadow. Let's forget about it. 

By the way, I've also haven't make any shadows for HUD, not for digits, neither for words.
M_DOOM from Doom 1&2 looking fine with shadow, but TNT's looking disgusting (it's like a vinaigrette of pixels), so I'm not recommending to use shadows for M_DOOM.

**Comment by fabiangreffrath** [comment]
If I am using the darkened color range for the shadow, this is already pretty similar to taking a monochrome translucent color (i.e. 50% black in this case).

**Comment by JNechaevsky** [comment]
CR_dark, right? Well, it may have less colors that any possible (pre)generated colormap, but yeah, I believe this is the most painless and independent from any color maps solution.  Just please, do not forget to show the results, you know how much I love shadowed menu elements. :)

**Comment by fabiangreffrath** [comment]
Yes, cr_dark. However, I should use the cr_dark table for the source pixel. What I have commited so far returns the darkened value for the source pixel * 256! I am lucky that this didn't trigger an instant segmentation fault (or, bad luck, because then I woudld have realized this mistake earlier).

I will post results as far as I have made progress. ;)

**Comment by fabiangreffrath** [comment]
So?

![doom0002](https://cloud.githubusercontent.com/assets/6449237/25823414/53379c66-343c-11e7-843b-4ae69ea71a84.png)

**Comment by JNechaevsky** [comment]
Oh yes, shadow colors looks perfect. The only thing I still wold like to suggest: make shadow 1px tall.
But again, this only my POV, if you like 2px, please leave it that way.

**Comment by fabiangreffrath** [comment]
Thanks for your feedback! Very constructive as always. I'll merge this branch right now.

> But again, this only my POV, if you like 2px, please leave it that way.

I want the menu graphics to stand out from the rest of the game scene. Please don't forget that this approach replaces the shading of the entire menu background. For now, I'll keep the menu graphics with a 2px shadow and apply a 1px shadow to the small menu font only.

> And finally, shadows better to be optional 

Well, I only introduced shadowed text as a compromise because I didn't want to add a switch for the previous (unpopular) approach. So, I will very surely not introduce a switch for this solution. ;)

**Comment by JNechaevsky** [comment]
Small but important feedback, of course I can't reject myself to take a look to the shadows. :)

- I've caught a little bug while was looking at the shadows: https://youtu.be/B-BxdatWBRg
Something goes wrong with STBAR update function. I honestly don't know, is it a aftermath of DrawPatch update, so you better take a look by yourself. 

- It possible to catch a little bit broken shadows, just like this: http://savepic.ru/13940031.png
Not very often, and this "breaking" strictly depends on background pixels. Interesting fact, that `TINTTAB` technology does not have this problem: http://savepic.ru/13929776.png. This seems to be fixable, but I can't imagine any fast ways, probably CR_dark must have some improvements, or maybe it will be better just to wait SDL2 migration and True Color rendering.

- Finally, just one little suggestion. Now texts shadows are placed on the top of the... how should I say this... On the top of the borders of borders. Take a look: http://savepic.ru/13932862.png
There is nothing critical of course, but moving text 1px higher (or borders 1px down? not sure what is more safe for mods) will make text fields a little better, just like this: http://savepic.ru/13942065.png

P.S. Now, when I saw 2px shadows live on my monitor, I must say that I like them. This is something like "own style", and I very liked idea of using 1px for text elements. Maybe it's worth to make all text elements shadowed, but maybe not! This is a question of `(perception * perfectionism) / compatibility` already, which is out of current scope.

**Comment by fabiangreffrath** [comment]
> I honestly don't know, is it a aftermath of DrawPatch update

Good catch! I think it is independent of the shadowed drawing but has to do with the removal of the shaded menu background. I need to trigger a forceful redrawing of the status bar after the Crispness menu has shown and previously, the shaded background function took care of that.

>  a little bit broken shadows

I guess this happens if there is no darker color available in Doom's palette, i.e. if the palette color that is closest to darkened version of the color in question is the color itself. this will definitely vanish with true-color rendering.

> moving text 1px higher 

Sounds like a good idea, thanks!

> Maybe it's worth to make all text elements shadowed

No, I really just want to make the menu stand out from the actual game, of which e.g. HUD messages are part of.

**Comment by fabiangreffrath** [comment]
> Something goes wrong with STBAR update function

Should be even worse if you have the screen size reduced so that the border get visible and then you leave the Crispness menu. Can you confirm this?

**Comment by JNechaevsky** [comment]
Nope. Regardless of any bordered screen size (`screenblocks`), the border works fine, even after reducing and increasing. Screenshot: http://savepic.ru/13921649.png

Some quick abstract though: you are probably remember my attempt to fix status bar update delay after closing help screen? I have rejected this idea later, because of two things: 
1. It increases unnecessary CPU usage be completely redrawing all status bar every tic. 
2. It makes Crispy HUD not working.

But. Maybe it is possible to call full update once, just after closing  Crispness menu somehow.
Maybe this is the way...

**Comment by fabiangreffrath** [comment]
Sorry, I am a moron. The border is already redrawn through checking `menuactivestate`.

The fix for the status bar was actually quite easy: I just have to pretend that the Crispness menu is a help screen, which also covers the full screen and thus needs to trigger a status bar update.
