### ISSUE TITLE
How to build against SDL2?

### ISSUE THREAD

**Issue by vanfanel** [fabiangreffrath/crispy-doom#197]
Hi!

Since Chocolate Doom has made SDL2 the default library now, is it possible to build Crispy against SDL2 too? How?
I see no mention to SDL2 on the build files.

Thanks

**Comment by fabiangreffrath** [comment]
No, SDL2 is not the default library for building Chocolate Doom yet. It is just that the deafult view on the Github project page has been changed to display the sdl2-branch. The master branch is still using SDL1, though.

I'll switch Crispy to using SDL2 as soon as Choco has merged the sdl2-branch into the master branch, or maybe even earlier once https://github.com/chocolate-doom/chocolate-doom/issues/856 has been resolved and a new beta released.
