### ISSUE TITLE
Suggestion for adding 1 extra pain and pickup palettes

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#202]
There is an interesting text in Doomwiki's [PLAYPAL article](https://doomwiki.org/wiki/PLAYPAL):

> An examination of the Doom source code reveals that the unused palettes (1 and 9) were likely intended to be the first levels of the red and yellow tinting effects, but because of the logic used in the palette code, they are never used

And a solution right below code example. If I got everything right, for us it should be like this:

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/st_stuff.c
```
    if (cnt)
    {
	palette = (cnt+7)>>3;
	
	if (palette >= NUMREDPALS)
	    palette = NUMREDPALS; // [JN] removed -1

	// [crispy] tune down a bit so the menu remains legible
	if (menuactive || paused)
	    palette >>= 1;

	palette += STARTREDPALS-1; // [JN] added -1
    }

    else if (plyr->bonuscount)
    {
	palette = (plyr->bonuscount+7)>>3;

	if (palette >= NUMBONUSPALS)
	    palette = NUMBONUSPALS; // [JN] removed -1

	palette += STARTBONUSPALS-1; // [JN] added -1
    }
```

I have tested this, it's working fine: now pickup flashes for one item is not so overpowered, as well as screen not too red while getting minor hurt. Fading after much hurt and pickups are also becomes smoother for 1 palette frame. 

This must be safe for compatibility, since PLAYPAL lump is always using 13 palettes. I'm not attaching any video or screenshots because you better check it by yourself to see - do you like it or not. 

_Speaking for myself - I like it and will commit just before some more testing. At least for item pickups, because first palette of hurt looks too "weak"._

_Suggestion №69_

**Comment by JNechaevsky** [comment]
Alright, tested it more longer and deeper. Here's my feelings, please consider them as recommendations.

**Item pickup.** Everything is okay, I liked lesser flashing of picking up one bonus and smoother fading out after picking up a lots of bonuses. 

**Pain.** Don't liked it. How to explain... For example, getting a non-critical hit (i.e. lesser damage) from sergeant to mega armor makes screen red very little. Also, contiguous crusher damage makes screen more red notably slower. This is not right. This game is about pain, not about needle spiking. Better do not change it.

**Comment by fabiangreffrath** [comment]
First, thanks for this suggestion! I knew about this bug and always wanted to check out how it looks fixed but never came to it.

That is, I just tested it and I agree. Rather severe hitscanner attacks suddenly feel like hitting my toe, so the pain palette switch will not get touched. I somehow fell the same for the item pickup, though. It doesn't really as satisfactory anymore to pickup a single item.

Remember our discussion about e.g. changing the duration of the wipe screen? These are exactly the subtle details that we got used to over the years and if you change them, it just feels wrong - even if it is actually surprisingly hard to put into words. ;)

**Comment by JNechaevsky** [comment]
Remember perfectly! I think the most suitable words will be: "Safe for compatibility, not safe for habits and feelings". Oh well, at least now we have a proper explanation why things like this should be rejected. :)

**Comment by JNechaevsky** [comment]
Hmph, my final suggestion here: if only it will be possible to use additional palette exclusively for fading out, that may looks pretty well in therms of "vanilla feeling". But is it technically possible at all?

**Comment by AXDOOMER** [comment]
It's like fixing the sky bug in Doom when the player has the invulnerability powerup. It's weird when you've been playing with these "bugs" all your life and suddenly you try a new port and it's fixed. It may not even be a bug. Sometimes developers let stuff in their files, but it's not meant to be used. 

Bug fixing depends on everyone's relative taste, but when it's relative to your own feelings, people disagree and it makes a mess because everyone wants something different. That's why I consider vanilla as the absolute way of playing Doom. It's the gold standard. The "infinitely tall monsters bug" is not a bug, it's a feature. You learn to love the game the way it is and accept that it's how the game works.

**Comment by JNechaevsky** [comment]
Generally, I'm agree, that's why I'm not good with any Doom mods of any kind.

But you know, fixing some stuff is like addiction, like sport, like hackery, and interest of "what will happen if I'll do this" and so on. It's like a building source port of own dream, by own taste, by own feelings. And of course, if the port is not a private/closed project, it is always necessary to give to player freedom of choice: want he/she see these changes or not, and/or have a Philosophy why some things are done or aren't done.

I was playing Doom from far 1994 (or was it 95?), it's a long time. And now, I finally can not only touch it's Hearth, but also obtain some definitely new experience. Hard to explain, but I know you'll understand. :) 

BTW, a little story: sometimes I'm using term "game mechanics", but it does not exactly means "canonicity", nope. This term comes to me many years ago, while I was working as game master in official Russian server of Lineage II MMO. Players often wrote petitions like "this skill is not working properly, please check" and so on. Almost in 95% cases our reply was "it's a game mechanics", meaning that "it's by design". And I believe this term is perfectly applicable for Doom - some thing are not bugs, it's by design.

**Comment by fabiangreffrath** [comment]
> Hmph, my final suggestion here: if only it will be possible to use additional palette exclusively for fading out, that may looks pretty well in therms of "vanilla feeling". But is it technically possible at all?

At first, I liked this suggestion pretty much. Then I realized that this also means the pickup flash will last twice as long.

I have tried this out by applying the fix from your first post and then modifying `p_inter.c` to add more to `player->bonuscount` and `player->damagecount` so that it enters into the second palette in `st_stuff.c:ST_doPaletteStuff()`. Then we would have a smooth transition from the second to the first shaded palette and finally back to the normal one. However, although the animation is more smooth now, it just doesn't feel right anymore, i.e. not like the Doom I am used to. :/

**Comment by JNechaevsky** [comment]
Doooh. Don't you have a remaining patch of this? I would like to check it out.

**Comment by fabiangreffrath** [comment]
This is what I've got:
[crispy-palettestuff.txt](https://github.com/fabiangreffrath/crispy-doom/files/1017030/crispy-palettestuff.txt)

**Comment by fabiangreffrath** [comment]
So, to summarize, palette shading intensity and duration of the palette effect are inevitably connected to each other.

**Comment by JNechaevsky** [comment]
Ah, hmm, I think I've got it, but will check just a little bit later.
I wonder if my yellow screen time limitation (with those hard arithmetic maths) helps here...

**Comment by JNechaevsky** [comment]
Checked out, yeah, it feels not right. Especially after picking up just one bonus it feels like it was picked up few bonuses. Okay, let's leave this "as is" for Crispy then.

**Comment by fabiangreffrath** [comment]
I think we agreed that this is not an option for Crispy.

**Comment by JNechaevsky** [comment]
Yeah-yeah. :triumph:

**Comment by JNechaevsky** [comment]
No, I'd better say: "yeah-yeah-yeah-yeah", since it's more argumentative! :stuck_out_tongue_winking_eye:

**Comment by fabiangreffrath** [comment]
He?!
