### ISSUE TITLE
Suggestion for using whole screen area

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#204]
Maybe it might be considered as "step forward", but it deffinitly should be optional and disabled by default in terms of purism blah-blah-blah. Probably it also should be done only for SDL2, since SDL2 is not using fixed window resolution.

Examples (as it looks in 1920x1080):
- Current: http://savepic.ru/14248622.png
- Wider: http://savepic.ru/14241454.png

But there are two notable problems:

1. Screen width determinates not automatically, it depends on `ORIGWIDTH`. For the screenshot I have changed it to 426, just to take a pic, but there will necessity to take care about 4:3, 5:4 and other resolutions. I.e. it must not be...static?
2. This will require many additional maths of centering some elements (menus, status bar, and so on), and most interesting part - how status bar should like looks: with or without green borders, but that's a story of another day.

_Suggestion №70 (it's getting harder)_

**Comment by fabiangreffrath** [comment]
I like the idea, but this is definitely far, far post-SDL2.

Also, maybe it should only be possible with the Crispy HUD (centered) or the statur-bar-less view at all.

**Comment by fabiangreffrath** [comment]
Ah, and in your screenshots, please note that the view is merely stretched horizontally, whereas I'd like to adapt the FOV to provide additional sight on the left and right side.

**Comment by JNechaevsky** [comment]
I see... Some additional maths should be done in FOV, but good thing that `ORIGWIDTH` does not affect sprite's aspect ratio. Alright, matters not for now. I think the most proper way for this will be using additional `screenblocks`, this will prevent overloading of both Crispness and Advanced video setting menu.

Few mockup-ideas for the future:

- `screenblocks 13` and lower should not be changed for compatibility reasons. Yep, you right, maybe it will be better if they will keep original black borders.

- `screenblocks 14`: wider screen area with borders. Borders are using only ingame graphics, so it must be safe for any kind of compatibility.
![](http://savepic.ru/14314606.png)

- `screenblocks 15`: wider screen area without borders. Not sure that it's looking good, though. For more good looking there have to be ability to scale up/down HUD size, but isn't it out of scope? Hmm.
From another hand, it is probably bad idea, since player's weapons will be hidden below HUD.
![](http://savepic.ru/14286958.png)

- `screenblocks 16`: Traditional Crispy HUD™.
![](http://savepic.ru/14326881.png)

- `screenblocks 17`: Translucent Crispy HUD™. Will look awesome in true color.
![](http://savepic.ru/14307425.png)

- `screenblocks 18`: No HUD.
![](http://savepic.ru/14288993.png)

**Comment by AnotherLife** [comment]
![img_20170608_150245](https://user-images.githubusercontent.com/7148117/27240771-cb81b240-52de-11e7-8f52-96fa19646f8a.jpg)

This is how it looks on my 22" 1680x1050 monitor  :(

**Comment by JNechaevsky** [comment]
Sadly, yeah, that's because of SDL1. On 27" it looks definitely not better.

But it will be cured once Crispy will be transferred to SDL2. For example, try to run Chocolate Doom 3.0 (it's on SDL2) in full screen - it's a colossal difference.

**Comment by fabiangreffrath** [comment]
Yes, I know, it looks similar on my screen. But all will be well soon!

**Comment by Zodomaniac** [comment]
I guess it has been handled here https://github.com/chocolate-doom/chocolate-doom/commit/bdb14111e00c37da25fbbb863d4b93088bf88469#commitcomment-28277699

**Comment by fabiangreffrath** [comment]
I understand that this request is about enhancing the field-of-view to the left and right if there is more horizontal game space than in the original 1.2:1 aspect ratio.

**Comment by fabiangreffrath** [comment]
Although I love this idea, it means I would have to re-initialize the entire rendering stack with updated framebuffer dimensions each time the window size changes...

**Comment by Zodomaniac** [comment]
@JNechaevsky As this is related to video rendering, why not suggest this upstream for Choco?

**Comment by JNechaevsky** [comment]
Sadly, it's not only rendering thing, it's a complex of different things:
- SDL renderer (outer renderer, which is giving us a viewable picture)
- Doom renderer (inner renderer, which is _forming_ a viewable picture and making all pre-processing calculations)
- GFX coords of various menu elemets, which are heavily hardcoded to original 320x200 pixel grid. 

In some aspects, it will be interesting to see pure Doom in FullHD, but there one additional problem - HUD's bezel. It would be good to follow PrBoom+ approach with it's placement, but since this will be a totally uncanonical addition, it should never happen.

**Comment by JNechaevsky** [comment]
Further implementation and discussion moved on #413. Closing this one.

_P.S. I wonder if `ORIGWIDTH_DELTA` will become a variable, not a macro. At least we have an example of how to move all the things, to make properly centered._  :smirk:
