### ISSUE TITLE
store and request full order-preserving list of loaded PWADs and Dehacked patches in extended savegames

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#206]
-Look alive! Crème de la Kremlin's arriving! Try to serve Ivan, no surviving!
(c) Epic Rap Battles of History, Alexander the Great vs Ivan the Terrible

@fabiangreffrath I tried loading my previous savegames with the SMOOTHED.WAD you showed me, to continue my walkthrough with smoothed graphics as other players also may decide.
When a game saved without SMOOTHED.WAD is loaded with SMOOTHED.WAD, the killed monsters behave like dead but look alive!

![look alive](https://user-images.githubusercontent.com/15119473/27000670-0b5cea16-4dc0-11e7-9321-933add20751b.png)

**Comment by fabiangreffrath** [comment]
I agree, this is weird but somehow expected behavior. The SMOOTHED mod shuffles around all possible states and it is pretty clear that game states with and without this mod necessarily differ.

So, what do you suggest I could do about this?

**Comment by Zodomaniac** [comment]
>So, what do you suggest I could do about this?

I think you could include the names of all the WADs loaded in the extended savegame, in the order they are actually loaded (as this makes the difference in https://github.com/fabiangreffrath/crispy-doom/issues/207), so that if some WAD is missing or extra, put up a confirmation dialog but with multiple WADs.

**Comment by fabiangreffrath** [comment]
I know that e.g. PrBoom+ does it like this, but honestly I don't like it.

I occasionally play with music replacement packs or try out harmless dehacked patches that modify one state or another and I would find it annoying if I had to confirm to load a savegame each time I have one of these additional resources loaded (or not). Most of them tend to be completely harmless and savegames load just fine -- in contrast to missing map data for which the confirmation dialog was initially introduced. Full mods like Black Ops or SMOOTHED that change about every state the game has to offer are more like the exception than the rule. 

But the game shouldn
t crash after loading that savegame, I agree!

**Comment by fabiangreffrath** [comment]
> But the game shouldn't crash after loading that savegame, I agree!

Did you even say anywhere that the game crashes after loading?!

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
>Did you even say anywhere that the game crashes after loading?!

Yes, I referenced https://github.com/fabiangreffrath/crispy-doom/issues/207:
>I think you could include the names of all the WADs loaded in the extended savegame, in the order they are actually loaded (as this makes the difference in #207)

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.
