### ISSUE TITLE
remove DOS references from quit game confirmation dialogs

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#208]
I suggest to 'quit to desktop' rather than 'quit to DOS', and the dimensional shambler is waiting at the command prompt, not DOS prompt. This also removes the reference to any specific OS pointing out Crispy being cross-platform (unlike Doom Retro that uses 'quit to Wndows').

**Comment by fabiangreffrath** [comment]
Hm, okay. Honestly, I never pay attention to these strings (I mostly quit the game with Shift + F10). Also, the are sometimes modified by Dehacked, so this should be taken care of.

**Comment by fabiangreffrath** [comment]
Now, let's get real! 

These are the strings that contain references to DOS. Please suggest a replacement for each of them:

```
doom/d_englsh.h:#define DOSY            "(press y to quit to dos.)"
doom/dstrings.c:  "i wouldn't leave if i were you.\ndos is much worse.",
doom/dstrings.c:  "you're trying to say you like dos\nbetter than me, right?",
doom/dstrings.c:  "don't go now, there's a \ndimensional shambler waiting\nat the dos prompt!",
```

**Comment by JNechaevsky** [comment]
Despite of we are living in cross-platform and non-only desktop Era, I have a bad feeling that changing _dstrings.c_ is a bad and canonicality breaking idea. Maybe it's better to change only _d_englsh.h_ as:

```
doom/d_englsh.h:#define DOSY            "(press y to quit.)"
```

**Comment by Zodomaniac** [comment]
There are also quit game messages mentioning DOS: "...you like DOS better than me, right?"
and "There's a dimensional shambler waiting at the DOS prompt!"
Please handle them if possible: 'you like desktop/console" instead of "you like DOS"
and "waiting at the desktop/console!" :)

**Comment by Zodomaniac** [comment]
There are also quit game messages mentioning DOS: "...you like DOS better than me, right?"
and "There's a dimensional shambler waiting at the DOS prompt!"
Please handle them if possible: 'you like desktop/console" instead of "you like DOS"
and "waiting at the desktop/console!" :)

**Comment by fabiangreffrath** [comment]
Once we switch to SDL2, we can replace the "dos" string with a string to the actual operating system using `SDL_GetPlatform()`. Please beat me to it if I forget about it!
