### ISSUE TITLE
Demos desync if SMOOTHED.WAD is loaded

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#210]
One can observe that clearly in Memento Mori and DooM The Way ID Did first demos. In the former the player fires lots of rounds at a wall instead of hitting imps with them, and in the latter Doomguy gets eaten by a pinkie instead of killing him.

**Comment by fabiangreffrath** [comment]
I think this is pretty much expected when loading a Dehacked patch that shuffles around nearly all possible states. Confirmed by the mod author:
https://www.doomworld.com/forum/topic/85991-smoothed-smooth-monsters-for-doom-retro/?do=findComment&comment=1755321
