### ISSUE TITLE
[Bug] Disappearing text shadows

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#211]
Text shadows are disappearing after opening quick load/save menus. This is unexpected. Dammit.

Suggestion: AFAIR, there is one function for drawing texts in both exit messages and saving/loading items. Perhaps it should be devided somehow, for strict definition of where to use shadow and where not?

- Video: https://youtu.be/La225IJhCZ4

**Comment by fabiangreffrath** [comment]
*sigh* This is because the `currentMenu` variable isn't reset when the menu is left.
