### ISSUE TITLE
Add 120 FPS refresh rate

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#212]
AFAIR, it was introduced in Doom 3 BFG Edition, and now it becomes something like a de-facto, a modern standard of gaming, especially in upcoming [Quake Champions](https://quake.bethesda.net/), as well as uncapped frame rate of course.

So maybe it is worth to add this into Crispy, as step forward and intermediate level between 70 and uncapped?

The only problem now is SDL1 using CPU only for rendering, and the more FPS it gives, the more CPU cycles it uses, despite of actual CPU load. I really hope that situation with SDL2 will be different, and frame interpolation will make a frame changing even more smooth.

_Suggestion №71_

**Comment by fabiangreffrath** [comment]
Not sure if it makes sense to implement this with the SL1 backend. Feels like beating a dead horse.

The SDL2 port will have three options: capped+vsync, uncapped+vsync and uncapped.

**Comment by JNechaevsky** [comment]
Ah, hm, yeah, agreed. Let's just close this issue then, with hopes that Chocolate Doom 3.0 will be released...soon enough.

**Comment by fabiangreffrath** [comment]
Or at least a mature-enough Choco 3.0 beta that I could merge... ;)

**Comment by JNechaevsky** [comment]
![](http://savepic.ru/14469145.png)

**Comment by fabiangreffrath** [comment]
Initially, I was waiting for a fix to https://github.com/chocolate-doom/chocolate-doom/issues/856. Then, I provided the fix myself in the hope that it would lead to the next beta release. I am still waiting for that, because I don't like merging an unreleased state from Choco. :/

**Comment by fabiangreffrath** [comment]
Rationale why I want vsync even in the capped 35fps mode:
https://github.com/chocolate-doom/chocolate-doom/commit/1aa66bd35de5843416c0de6a1c5d1a0ff0cb6fc2

**Comment by JNechaevsky** [comment]
Ah yes, I remember the video that Linguica has been posted, and agreed, in terms of perfection this vsync fix should be applied. Oh well. Guess, until then we have something more to investigate.

**Comment by fabiangreffrath** [comment]
I am not sure what you expect from it. I have introduced the code that you just merged as some kind of "poor man's vsync", because proper vsync was not available in SDL1. It was a crude hack and I am glad I could get rid of it in favor of "real" vsynv, i.e. sync with the actual video driver.

What benefit do you expect if you draw 120 fps but only half of them are actually rendered to screen? What should that bring? Why render the intermediate frames at all, they will *never* be seen?

And what do you mean with "gold standard" of 120 fps?

**Comment by JNechaevsky** [comment]
I'm expecting exactly "two things in one": I want smooth (>60 fps) framerare and I don't to hear much noise from my cooling fans, that's why I set limit of 120. 

Term "gold standard" is my play of words of course, but browsing some articles about FPS in 3D shooters making some sense. Also, for example, Doom 3 BFG edition have a strict section of either 60 or 120 fps: http://priscree.ru/img/3ac01d16569d97.png. Can't properly check DOOM (2016) and Quake Champions, though - I don't see a FPS cap there (only vsync: `on`, `off`, `adaptive`), but neither I can't get more than 20-30 fps in these games. 

As about vsync... Well, from all my life time experience, I never was happy about it, in different monitors (CRT/LCD) and different video cards. It feels wrong for my eyes. It's making framerate a little bit laggy, not sure how to explain it more technically proper.

But I have to totally disagree with you about "poor man's vsync". See, without `GetAdjustedTimeN` I'm getting 400-700 fps and higher CPU's fan noise, which I definitely don't want to have. I.e., I don't want/need to have too high CPU usage and too much noise. 

You are meaning that `GetAdjustedTimeN` does not increase real fps, but just capping it? Even if so, I still would like to have it, because I need this cap. Or there can a different way to have a real 120 fps instead of 60?

**Comment by JNechaevsky** [comment]
Another idea, which I want to annoy here. I've just made fps cap as a config variable ([here](https://github.com/JNechaevsky/russian-doom/commit/0e713fdb362c5406d6942805d974f5bac3ef206f)). Of course, everyone "loves" config file editing, but at least it's fair. I think I need to move it into Setup executable.

It's working even with <35, so I can set it to approx. 12 to play the way back in 1994. Good times!
