### ISSUE TITLE
Plasmagun allowing negative ammo and desyncing demos with Black Ops mod

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#213]
With Black Ops mod you can fire the plasma gun until -2 rounds, status bar displaying it with a red minus at the bottom, lol. Other weapons don't seem to have this bug.
![doom0000](https://user-images.githubusercontent.com/15119473/27762015-4d072ec4-5e71-11e7-87c3-9af27715155e.png)

Here's the demo involving the plasmagun that desyncs with Black Ops:
[!KILLHIM.zip](https://github.com/fabiangreffrath/crispy-doom/files/1117110/KILLHIM.zip)

**Comment by fabiangreffrath** [comment]
@AnotherLife Do you have an idea why this occurs with the BlackOps mod? @JNechaevsky already reported a similar issue with the Chaingun before in https://github.com/fabiangreffrath/crispy-doom/issues/207#issuecomment-308465049

@Zodomaniac I think we shouldn't expect demo compatibility with a mod like BlackOps loaded.

**Comment by fabiangreffrath** [comment]
It seems that `A_CheckAmmo()` isn't called for these weapon states?

**Comment by AnotherLife** [comment]
Demo compatibility is not guaranteed because. For example in the plasma rifle I made it fire bursts of 3 to make it play an animation and not look like crap like the original one. I mean even if you tap it, it fires 3 plasma shots.

The problem is that the original weapon does thisL
FirePlasma
ReFire
^ and it loops

The modded does this:
FirePlasma
FirePlasma
FirePlasma
ReFire
^ and it loops

In Doom Retro Brad made a workaround (although 1 or 2 extra shots are squeezed out even there is no ammo for them heheh), you could do the same, to keep the ammo at 0.

I also noticed that in Crispy Doom if I press 2 to change to the pistol while I am firing the Chaingun it gets screwed :(

**Comment by fabiangreffrath** [comment]
> I also noticed that in Crispy Doom if I press 2 to change to the pistol while I am firing the Chaingun it gets screwed :(

What exactly do you mean, what gets screwed? Does this only happen with the BlackOps mod or also in Vanilla gameplay?

**Comment by Zodomaniac** [comment]
I don't know what gets screwed when switching to pistol when firing the chaingun, but if you had an odd amount af ammo for chaingun, you could get -1 ammo because it shoots in bursts of 2 (like plasmagun in bursts of 3) and you can fire only an even number of shots.

**Comment by fabiangreffrath** [comment]
Then this should also be fixed by the last commit, right?

**Comment by Zodomaniac** [comment]
Yes, it is ;)

**Comment by AnotherLife** [comment]
The Chaingun needs fixing, it was working fine in Doom Retro so I didn't catch the problem. I released a new version of Black Ops and posted it in this thread:
https://www.doomworld.com/forum/topic/84859-black-ops-smooth-weapons-dehacked-mod/

👍

**Comment by Zodomaniac** [comment]
@AnotherLife 
> The chaingun needs fixing

Do you mean you didn't intend it to fire 2 rounds if tapped?

**Comment by fabiangreffrath** [comment]
What exactly needed fixing and what did you do to fix it?

**Comment by AnotherLife** [comment]
The chaingun was firing double the ammo it should. Also if you were holding down the fire button and pressed 2 to change to the pistol, it would get screwed.

I was using a FireCGun and a FirePistol pointer, now I set them both to FirePistol in its firing state. It fixed the same problems in prboom+, but prboom+ has the negative ammo problem still. I think it is for the best that this is only compatible with Doom Retro and Crispy Doom.

**Comment by Zodomaniac** [comment]
@AnotherLife 
> The chaingun was firing double the ammo it should. Also if you were holding down the fire button and pressed 2 to change to the pistol, it would get screwed.

Did I have some kind of luck that I didn't experience this in v4?

**Comment by AnotherLife** [comment]
I realised yesterday that I was mistakenly testing in v3 of the mod.  /facepalm

The only change between v4 and v5 is that I changed the FireCGun code pointer with FirePistol. Should make no difference at all.
