### ISSUE TITLE
After using the IDFA cheat, any item picked up results in the STFEVL1 status face

### ISSUE THREAD

**Issue by AnotherLife** [fabiangreffrath/crispy-doom#214]
After using the IDFA cheat, any item picked up results in the STFEVL1 status face. For example, starting MAP01, using IDFA and then picking up the health potion.

**Comment by Zodomaniac** [comment]
@AnotherLife Thanks to you I know now that is STF in STFGOD0, STFEVL1 etc. is STatus Face!
Here's a GIF including the additional STFGOD faces made by @JNechaevsky 
![anim_doomguy](https://user-images.githubusercontent.com/15119473/28301366-bceb7892-6b8e-11e7-90bd-9da81f545c6f.gif)

**Comment by fabiangreffrath** [comment]
I think I'll fix this by showing the evil grin as soon as the cheat has been entered and the weapons received. This will also update the `oldweaponsowned[]` array and not trigger the evil grin when the next random item has been picked up.

**Comment by Zodomaniac** [comment]
@fabiangreffrath nice idea)
