### ISSUE TITLE
Cannot use screen resolutions above 1920×1200 (on a 2560×1440 monitor)

### ISSUE THREAD

**Issue by Calinou** [fabiangreffrath/crispy-doom#215]
**OS:** Windows 10 Creators Update
**Crispy Doom version:** 4.1 (official binary)

This is how the setup program looks after setting an higher resolution than 1920×1200, starting the game then quitting:

![Setup](https://user-images.githubusercontent.com/180032/28783995-63c00fa6-7612-11e7-923d-66f1affac6df.png)

It will revert to 1920×1200, even if setting 2560×1440 (or 1920×1440). Editing the configuration file by hand (while the game is closed) will not work either; the screen resolution values will be reverted to 1920×1200.

**Comment by Calinou** [comment]
I just tried Crispy Doom 4.3 on Windows, and setting 2560×1440 in the Setup program (or editing the configuration file) still reverts to 1920×1200 upon starting the game.

**Comment by Zodomaniac** [comment]
@Calinou I guess I should re-open this

**Comment by fabiangreffrath** [comment]
> This only happens if aspect ratio correction is enabled. When disabled, the game can run at 2560×1440 or 1920×1440 without issues.

Sorry, but this is confusing.

You can only scale the game's original framebuffer by integer factors. If aspect ration correction is enabled, the original framebuffer is 640x480, if it's disabled it is 640x400.

So, with aspect ratio correction **disabled**, you should be able to get (640*3)x(400*3) = 1920x1200 or (640*4)x(400*4) = 2560*1600 resolutions. 

Likewise, with aspect ratio **enabled**, you should be able to get (640*3)x(480*3) = 1920x1440 or (640*4)x(400*4) = 2560*1920 resolutions.

**Comment by fabiangreffrath** [comment]
So, since you state you have a 2560×1440 screen, your vertical resolution is limited to factor 3 regardless of aspect ration correction being enabled or not, and so your horizontal resolution is limited to factor 3 as well. This means either 1920x1200 or 1920x1440 for you, but nothing more.

**Comment by Calinou** [comment]
To clarify the situation, when aspect ratio correction is disabled, Crispy Doom is able to output 2560×1440 (see the screenshot below, taken using a system screenshot tool), so that no modesetting occurs – modesetting introduces a ~3 second delay when alt-tabbing out and in of a game running in a lower-than-desktop resolution, so it should be avoided whenever possible. This *ought* to be possible with aspect ratio correction enabled as well.

![Crispy Doom at 2560×1440 with aspect ratio correction disabled](https://user-images.githubusercontent.com/180032/31183589-4ee295d4-a927-11e7-9670-76489df8720b.png)

While unrelated to this issue, I've tested Chocolate Doom 3.0.0 beta (which uses SDL 2) and it is able to render the game at the "full" display height (6× scaling compared to the original 320×240 output), while keeping the desktop resolution. My point is, Crispy Doom should be able to do so as well, with 3× scaling compared to the 640×480 output.

**Comment by fabiangreffrath** [comment]
Thanks for elaborating!

To be honest, I am not sure why your specific setup doesn't work and I am not going to invest more energy in supporting higher resolutions using the obsolete software scaling mode. The next big thing for both Choco and Crispy will be hardware-based scaling using SDL2 and that's what we should be looking forward to. The only thing that's missing is about one whole weekend of free time all for myself... which... isn't going to happen soon. ;)

**Comment by Zodomaniac** [comment]
@Calinou try the daily build at latest.chocolate-doom.org, does the issue persist?

**Comment by fabiangreffrath** [comment]
The v5.0 release should also suffice. Seems like an intense bug triage is due...

**Comment by Calinou** [comment]
It works with Crispy Doom 5.0 😄 

![crispy_doom_5 0_sdl2](https://user-images.githubusercontent.com/180032/32895078-267f6f3e-cadf-11e7-9c89-535e4c6b486d.png)
