### ISSUE TITLE
Weapon bobbing with half amplitude

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#222]
Suggesting an additional bobbing while shooting method: "with half amplitude". It looks pretty realistic and adds some natural dynamic in weapon firing. Here's a video example:

- https://youtu.be/3VLZjH-_sgo

And code example (probably can be greatly shortened/optimized), look at `src/doom/r_things.c`

- https://github.com/JNechaevsky/russian-doom/commit/e6c06299228460ed67c9f50e886ff5c91ee7bbe0

In fact, it's a copy of `R_ApplyWeaponBob` just with /2 formulas. I've also was trying to use 1/3 of amplitude but don't liked it - amplitude becomes too notably small and ceases to harmonize with standard bobbing amplitude.

_I was planning to suggest in my reply e-mail, so please consider this as a suggestion №73!_

**Comment by fabiangreffrath** [comment]
> It looks pretty realistic and adds some natural dynamic in weapon firing

Yep, that's really good, thanks for the suggestion!

**Comment by Zodomaniac** [comment]
I think 'Weapon bobbing amplitude' should be a separate setting/config variable, to be independent from weapon attack alignment.

**Comment by fabiangreffrath** [comment]
But I am not going to modify the weapon bobbing amplitude in general, but only when firing.

**Comment by JNechaevsky** [comment]
I was trying to play around just a little bit with bobbing in general. It's not hard to get different amplitude for different weapons: more for light guns and less for heavy. It is also not hard to get different bobbing style, like in Quake 1.

But all of this is interesting in terms of modding, not as a source-port feature. For example, (G)ZDoom allow modders to do this via DECORATE, but changing DEH/BEX specifics for implementing this feature is certainly very bad idea.

**Comment by fabiangreffrath** [comment]
Also, try out no horizontal bobbing if the chainsaw hits an enemy:
https://github.com/JNechaevsky/russian-doom/commit/e6c06299228460ed67c9f50e886ff5c91ee7bbe0#commitcomment-25049470
