### ISSUE TITLE
No inverted colormap for the dead player

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#224]
Same logic as in previous suggestion, but this time we have to think more. I'll try to explain how to achive this and why inverted palette should be removed...

While having INVUL sphere, player can only be killed by telefrag on MAP30. So we are selecting easiest skill and going to MAP of Hell on Earth. After picking up sphere, we are standing in spitter spawn point, waiting few seconds and poof - we are dead. But inverted colormap is still before our eyes. This is logically not right IMO, because we are dead and not invulnerable. Let game palette be normal after death.

Sounds pretty abstract and nerdy, but I'll have to explain this. Also, this is a nothing more than special condition for MAP30 only, since in any another map we can't die while having INVUL sphere.

#### Solution.

Once I have said that all the fixes are belonged to Fabian, nothing changed from that time. Here's it is:

- https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/p_inter.c#L747

#### Other powerups?

I was thinking about it, in my opinion their palettes must be changed after death. As example...

- Rad. suit. Player dies in this suit, and the suit is neither burned out nor destroyed.
- Light visor. Same as above, it's a technical, not spiritual powerup.
- Invisibility. The specters are not becoming visible after death, so why player should? Yep, it's a temporal effect for player, but since HUD weapon is going down, barely this require any changed. There is only one interesting question - what is happening with invisible dead player's body in deathmatch? Is it remains invisible, or is it appearing after some time? Hmph.
- Berserk. Since we are already have enough blood behind out eyes after death, no need remove slightly red palette. 

#### Video example

After applying solution. Let's take a look, there are three cases (INVUL only, INVUL+VISOR, VISOR only).

- https://youtu.be/3zgUi8hgWls

_Suggestion №74_

**Comment by fabiangreffrath** [comment]
Thanks for the suggestion!

Radiation suit and Berserk are not implemented by changing colormaps, but palettes, so they remain unaffected by this change anyway. ;)
