### ISSUE TITLE
Fix tutti-frutti for transparent textures

### ISSUE THREAD

**Issue by plumsinus** [fabiangreffrath/crispy-doom#23]
Since you've already fixed TF from short textures, and medusa from multi-patch textures, I think it would make sense to fix this too. Transparent textures used as an upper or lower texture, or on a 1-sided wall as a mid texture, produce visual glitches from undefined results.

![doom01](https://cloud.githubusercontent.com/assets/5642091/3702960/10ba10da-1405-11e4-915b-5037a02c6492.png)

The "usual" way that other ports handle this is to replace the transparency with black, though this isn't exactly standard - even PrBoom+ looks a bit glitchy in software mode.

example file: https://www.mediafire.com/?spsnd055tk59txm

**Comment by fabiangreffrath** [comment]
So, I have investigated this issue a bit: What we are seeing in the areas that are supposed to be black in the textures is not a Tutti-Frutti effect, i.e. it is not random pixel values read from memory. Instead, they are the actual `topdelta` and `length` bytes of the posts that the individual columns of the patches are composed of.
The reason why we see them is that Vanilla Doom renders upper and lower textures as well as middle textures on one-sided walls with the `R_DrawColumn()` function, whereas it only renders middle textures on two-sided walls with the `R_DrawMaskedColumn()` function. The former function, however, ignores the fact that a texture may contain transparent areas and may thus be composed of multiple posts -- instead, it dully draws them column by column. Only the latter function interprets the  `topdelta` and `length` bytes of the posts correctly and and thus considers transparent areas. That is, these bytes are overridden when a texture is composed of multiple patches in `R_DrawColumnInCache()` which causes the Medusa-Effect, but this is already taken care of.

**Comment by fabiangreffrath** [comment]
Alright, I am closer.

The main problem is that the engine does not even consider single-patched transparent textures. For single-patched textures, `R_GetColumn()` returns the raw patch column, whereas for multi-patched textures (strictly: for multi-patched columns) it returns the composited column. The logic is: single patch -> opaque, multiple patches -> probably transparent.

What we need here, however, are composited columns even for a single-patched textures. Else, the raw patch column is passed over to `R_DrawColumn()` and we end up with the `column->topdelta` and `column->length` bytes of the (> 1) posts that make up this column, which we see as the odd pixels in the texture rendering.

So, I need to do multiple things:
1) Create composites even for single-patched textures
2) Tell R_GetColumn() to either return the raw patch column for single-patched mid-textures on 2-sided lines (only!) or the composed column for all other textures.
3) I will need to maintain separate column offsets for both cases

And then I will have to clean up this mess. ;)
