### ISSUE TITLE
[suggestion] option to disable automatic resizing of window

### ISSUE THREAD

**Issue by Rahtgaz** [fabiangreffrath/crispy-doom#230]
The current behavior of Crispy of automatically resizing the game window, is a good and needed feature. However it isn't always a friendly feature on Linux systems running tiling window managers, where window cropping can in fact be desirable, or precise dimensioning is required.

I'd like to request a simple command line option that allows users to disable the automatic resizing of the game window.

**Comment by fabiangreffrath** [comment]
Hi there,

thank you for the suggestion. In fact, I completely agree with you and suffer from the very same issue myself (using gnome-shell on Debian). However, Crispy's scaling/rendering code is inherited from Chocolate Doom and left mostly unchanged (except for a few minor details). So, this exact problem is already present upstream in Choco and merely taken over from there.

So, could yoou please do me a favour and report this issue in Choco's bug tracker? If we'll ever get to find a solution there (but don't expect another command line parameter, though), I will merge it into Crispy's code base and thus both ports would benefit from it. Thank you!

**Comment by Rahtgaz** [comment]
Done. Thank you for your attention.
