### ISSUE TITLE
Two suggestions regarding weapon position while squatting down

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#233]
This is a more idea to think about, rather than TODO suggestion.

After falling from 32+ map units (which are declared as `-GRAVITY*8`?) player is squatting down and making an "oof" sound, while his weapon position remains constant. Maybe it will look cool if his weapon will also have some vertical movement? A little bit lowered first, then raised back to normal.

Sounds kinda unclear, so please take a look at suggested example:
https://youtu.be/P-ZQuNOs7tY

_Note: suggested version is an video edit, I haven't touched the code._

Another suggestion is to make squatting amplitude different, depending on falling height, but requires some brainstorming. All I can offer right now - is to don't squat lower than in vanilla.

Maybe these ideas will be interesting somehow? I think I saw something similar in Build engine games (Duke 3D, Blood).

_Suggestion №78_

**Comment by fabiangreffrath** [comment]
This looks really great, and I think this would make for another subtle improvement. But first I would have to find a way to trigger a "lower a bit then raise back again" movement for the weapon sprite upon hitting the ground.

**Comment by fabiangreffrath** [comment]
Insta-concept:

```
diff --git a/src/doom/d_player.h b/src/doom/d_player.h
index b719aa31..dd8c9d24 100644
--- a/src/doom/d_player.h
+++ b/src/doom/d_player.h
@@ -171,6 +171,7 @@ typedef struct player_s
     unsigned int	jumpTics;
     fixed_t	recoilpitch, oldrecoilpitch;
     mobj_t	*so;
+    fixed_t	psp_dy;
 } player_t;
 
 
diff --git a/src/doom/p_mobj.c b/src/doom/p_mobj.c
index 1b9121f3..5606621a 100644
--- a/src/doom/p_mobj.c
+++ b/src/doom/p_mobj.c
@@ -382,6 +382,7 @@ void P_ZMovement (mobj_t* mo)
 		// after hitting the ground (hard),
 		// and utter appropriate sound.
 		mo->player->deltaviewheight = mo->momz>>3;
+		mo->player->psp_dy = -1;
 		// [crispy] center view if not using permanent mouselook
 		if (!crispy_mouselook)
 		    mo->player->centering = true;
diff --git a/src/doom/p_user.c b/src/doom/p_user.c
index 567081b4..56dc37f4 100644
--- a/src/doom/p_user.c
+++ b/src/doom/p_user.c
@@ -127,6 +127,27 @@ void P_CalcHeight (player_t* player)
 	    if (!player->deltaviewheight)
 		player->deltaviewheight = 1;
 	}
+	if (player->psp_dy)
+	{
+	    if (player->psp_dy < 0)
+	    {
+		player->psp_dy -= FRACUNIT;
+
+		if (player->psp_dy < -8*GRAVITY)
+		{
+			player->psp_dy = -player->psp_dy;
+		}
+	    }
+	    else
+	    {
+		player->psp_dy -= FRACUNIT;
+
+		if (player->psp_dy < 0)
+		{
+			player->psp_dy = 0;
+		}
+	    }
+	}
     }
     player->viewz = player->mo->z + player->viewheight + bob;
 
diff --git a/src/doom/r_things.c b/src/doom/r_things.c
index 5ddcfc63..8b934c86 100644
--- a/src/doom/r_things.c
+++ b/src/doom/r_things.c
@@ -950,6 +950,7 @@ void R_DrawPSprite (pspdef_t* psp, psprnum_t psprnum) // [crispy] differentiate
                              crispy_centerweapon / CENTERWEAPON_BOB2 + 1);
         }
     }
+    psp_sy += abs(viewplayer->psp_dy);
     // calculate edges of the shape
     tx = psp_sx-(ORIGWIDTH/2)*FRACUNIT;
 	
```

**Comment by fabiangreffrath** [comment]
Wow, I really like this, although this is pretty much non-Vanilla!

**Comment by JNechaevsky** [comment]
Yeah, just checked, it's look awesome! But I've also found a little bug: catch a moment when weapon starts to lower after landing and pause the game (or enter main menu) - weapon will slowly goes down even when the game is paused. 

Everything other seems to be fine, just checked it TNT Map08 (Metal) map in huge room with stairs and different heights.

**Comment by fabiangreffrath** [comment]
Hm, not for me. Is this in a multiplayer game (where tics are getting counted even in the background)?

Currently, I consider this a bit too invasive to have it enabled by default. So, in order not to introduce another option for this minor change, I play the thought to bind it to another setting: Either jumping, weapon recoil pitch or weapon attack alignment... though, it is not really directly connected to any of them. :/

**Comment by JNechaevsky** [comment]
> Hm, not for me. Is this in a multiplayer game (where tics are getting counted even in the background)?

:speak_no_evil: My bad, for the speed checking I was testing it in my code, now checked in Crispy - everything is fine in both single player and `-solo-net`. Excuse me for this inconvenience and false alarm.

Have to agree that it should be disabled by default (just like other gameplay features). But, hm, maybe it is possible to enable this feature for _any_ selected from above? Just in case some people may not like recoling but like attack alignment and vice versa. From another side, this idea sounds like bad ethics.

**Comment by Zodomaniac** [comment]
@fabiangreffrath
>though, it is not really directly connected to any of them.
The separate option for squatting down is therefore the most reasonable solution :)

**Comment by Zodomaniac** [comment]
@fabiangreffrath
>though, it is not really directly connected to any of them.

The separate option for squatting down is therefore the most reasonable solution :)

**Comment by fabiangreffrath** [comment]
> The separate option for squatting down is therefore the most reasonable solution :)

But for me it is the least favored solution. This is really such a subtle visual improvement and I don't want to clutter the menu pages with the 100th switch that nobody really knows what it means. :/

**Comment by fabiangreffrath** [comment]
As a compromise, I could adapt the amount of squatting to the vertical momentum at impact, making it bearly noticable when jumping down the ledge at the beginnig of MAP01 and increasing it to the full (i.e. its current) intensity when e.g. jumping off a roof top in MAP15.

**Comment by fabiangreffrath** [comment]
Now it's already in a commitable state with adaptive squatting (tough I would rather mangle the `psp_sy += abs(viewplayer->psp_dy` into the `if (crispy_centerweapon)` block above.

```
diff --git a/src/doom/d_player.h b/src/doom/d_player.h
index b719aa31..15dc2ef9 100644
--- a/src/doom/d_player.h
+++ b/src/doom/d_player.h
@@ -171,6 +171,8 @@ typedef struct player_s
     unsigned int	jumpTics;
     fixed_t	recoilpitch, oldrecoilpitch;
     mobj_t	*so;
+    // [crispy] squat down weapon sprite a bit after hitting the ground
+    fixed_t	psp_dy, psp_dy_max;
 } player_t;
 
 
diff --git a/src/doom/p_mobj.c b/src/doom/p_mobj.c
index 1b9121f3..46185072 100644
--- a/src/doom/p_mobj.c
+++ b/src/doom/p_mobj.c
@@ -382,6 +382,8 @@ void P_ZMovement (mobj_t* mo)
 		// after hitting the ground (hard),
 		// and utter appropriate sound.
 		mo->player->deltaviewheight = mo->momz>>3;
+		// [crispy] squat down weapon sprite as well
+		mo->player->psp_dy_max = mo->momz>>2;
 		// [crispy] center view if not using permanent mouselook
 		if (!crispy_mouselook)
 		    mo->player->centering = true;
diff --git a/src/doom/p_user.c b/src/doom/p_user.c
index 567081b4..096068ae 100644
--- a/src/doom/p_user.c
+++ b/src/doom/p_user.c
@@ -127,6 +127,21 @@ void P_CalcHeight (player_t* player)
 	    if (!player->deltaviewheight)
 		player->deltaviewheight = 1;
 	}
+	// [crispy] squat down weapon sprite a bit after hitting the ground
+	if (player->psp_dy_max)
+	{
+		player->psp_dy -= FRACUNIT;
+
+		if (player->psp_dy < player->psp_dy_max)
+		{
+			player->psp_dy = -player->psp_dy;
+		}
+
+		if (player->psp_dy == 0)
+		{
+			player->psp_dy_max = 0;
+		}
+	}
     }
     player->viewz = player->mo->z + player->viewheight + bob;
 
diff --git a/src/doom/r_things.c b/src/doom/r_things.c
index 5ddcfc63..8f2119ae 100644
--- a/src/doom/r_things.c
+++ b/src/doom/r_things.c
@@ -950,6 +950,8 @@ void R_DrawPSprite (pspdef_t* psp, psprnum_t psprnum) // [crispy] differentiate
                              crispy_centerweapon / CENTERWEAPON_BOB2 + 1);
         }
     }
+    // [crispy] squat down weapon sprite a bit after hitting the ground
+    psp_sy += abs(viewplayer->psp_dy);
     // calculate edges of the shape
     tx = psp_sx-(ORIGWIDTH/2)*FRACUNIT;
 	
```

**Comment by JNechaevsky** [comment]
Totally lovely, and the most important thing - it's not too notable it the cases when weapon have some movement's bobbing. Ah yes, you may also wish to make it available in the jumping momentum, something like this:

- https://youtu.be/w4mMNB02ggI

**Comment by fabiangreffrath** [comment]
Another good idea. I think if this serves two purposes (squatting when jumping and squatting when landing) it may indeed deserve its own switch in the menu.

I guess squatting when jumping and then squatting again when landing should be omitted, as I am afraid it will look rather stupid.

**Comment by JNechaevsky** [comment]
> I guess squatting when jumping and then squatting again when landing should be omitted, as I am afraid it will look rather stupid.

No no no, I was not suggesting additional player's squatting before/after jumping, my idea was about lowering weapon before jump.

Not related to the implementation: I think rendering HUD weapons as 3D models may bring some real flexibility in movement. Nope, I'm not meaning real 3D recreation, just something like this:

- http://screenshot.ru/upload/images/2017/11/23/bfgb01d1.png

It could be useful to transfer some calculations to the GPU, and could allow to do some cool visual tricks, but heh, needles to say that this is completely out of scope.

P.S. Could you please approve applying of this code in my project? It's time for me to prepare release executable builds, but as I mentioned before, I prefer to have you approval first.

**Comment by fabiangreffrath** [comment]
> I was not suggesting additional player's squatting before/after jumping

That's what I meant. ;)

Anyway, I am afraid it will look stupid if the weapon sprite squats down at the beginning of a jump and then again after landing, but we will see...

> Could you please approve applying of this code in my project

Sure, go for it!

**Comment by fabiangreffrath** [comment]
And.. implemented!
