### ISSUE TITLE
automake creates but does not clean up src/{heretic,hexen,strife}/Makefile

### ISSUE THREAD

**Issue by jmtd** [fabiangreffrath/crispy-doom#234]
Before

    0:tharsis$ git status --ignored
    On branch master
    Your branch is up-to-date with 'origin/master'.
    nothing to commit, working tree clean
    0:tharsis$ ls src/*/Makefile
    ls: src/*/Makefile: No such file or directory

generate, then clean up

    0:tharsis$ ./autogen.sh >/dev/null 2>&1
    0:tharsis$ ls src/*/Makefile
    src/doom/Makefile   src/heretic/Makefile    src/hexen/Makefile      src/setup/Makefile      src/strife/Makefile
    0:tharsis$ make clean >/dev/null 2>&1
    0:tharsis$ make distclean >/dev/null 2>&1

after

    0:tharsis$ ls src/*/Makefile
    src/heretic/Makefile        src/hexen/Makefile      src/strife/Makefile

**Comment by fabiangreffrath** [comment]
Hm, I consider it a feature that it still creates `{heretic,hexen,strife}/Makefile` so it remains possible to e.g. build crispy-heretic by merely calling `make crispy-heretic`. No idea why it doesn't clean them up, though. :/

**Comment by jmtd** [comment]
Yeah my autofoo skills are not good enough, I couldn't figure it out yet either. In case you are wondering both these issues I discovered when packaging for Debian (almost done!). This one is perhaps easiest to fix with additional stuff in debian/rules for now.

**Comment by jmtd** [comment]
> Cool! Are you going to move the packaging to the pkg-games GIT repo?

Yeah or Collab-Maint. Pkg-games probably makes the most sense, I'll have to check if I'm still in the ACLs, I sort-of quit the team a few years back.

**Comment by fabiangreffrath** [comment]
@jmtd What has become of the packaging of Crispy Doom for Debian?

**Comment by jmtd** [comment]
I paused it whilst I fixed these doc issues upstream, hoping to avoid carrying those patches in the package. But there’s a bug in the changes I made upstream that I haven’t fixed yet.

**Comment by fabiangreffrath** [comment]
And this is a show-stopper for the Debian package?

**Comment by jmtd** [comment]
> And this is a show-stopper for the Debian package?

On its own, no -- it's kind of annoying to have the manpages read chocolate-doom. But I would have to at least resolve the clashing default.cfg.5.gz file in the .deb, so I felt that if I had to make at least that change I might as well wait until it's all fixed upstream-upstream. Since there wasn't a rush.

**Comment by fabiangreffrath** [comment]
Alright, I see. While at it, with both Choco and Crispy we would have two packages providing `default.cfg.5.gz`. Would we have to make both conflict with each other? I hope not and rather drop this manpage from the Crispy package.

**Comment by jmtd** [comment]
In my WIP I just prefixed crispy_ for the copy in the crispy package. I should push my work somewhere if I haven’t already! It might be on Salsa

**Comment by jmtd** [comment]
I was just checking in on this; from what I can tell, the upstream issues are all fixed (https://github.com/chocolate-doom/chocolate-doom/issues/1000 is still open but I can't reproduce it, and it's OSX specific). Are you planning to rebase 5.2 on top of chocolate master, and/or pull in the docs commits? Thanks!

**Comment by fabiangreffrath** [comment]
> Are you planning to rebase 5.2 on top of chocolate master, and/or pull in the docs commits?

I do never rebase, but merge all the commits applied to Choco's master branch.

**Comment by jmtd** [comment]
Ok. In which case I hope to have the Debian package ready to go for your next release :)

**Comment by fabiangreffrath** [comment]
So, now that Crispy 5.2 has been released, how about the Debian package?

**Comment by jmtd** [comment]
Going to try and finish tonight :)

**Comment by jmtd** [comment]
initial packag pushed to new; packaging at https://salsa.debian.org/debian/crispy-doom

**Comment by fabiangreffrath** [comment]
Very cool, thanks! Though, I guess the information in `debian/copyright` is now obsolete (i.e. the BSP code is now back to MBF's GPL'd version) and the `+dfsg` suffix is not required anymore.

**Comment by jmtd** [comment]
> Very cool, thanks! Though, I guess the information in debian/copyright is now obsolete (i.e. the BSP code is now back to MBF's GPL'd version) and the +dfsg suffix is not required anymore.

oh, hah, I hadn't realised that. I've gone through the trouble of reverting the doombsp commit uselessly. I piggy-backed another change into the +dfsg1 tarball (remove the "noncommercial" part of the license in the metadata for the readme HTML - this is bug in chocolate-doom.org which is now fixed).

Glad to hear it, the next orig update will be much nicer :)

**Comment by jmtd** [comment]
I asked ftpmasters to REJECT my first upload so we can avoid the +dfsg1 repack.

**Comment by fabiangreffrath** [comment]
:+1:

**Comment by jmtd** [comment]
https://tracker.debian.org/pkg/crispy-doom

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.
