### ISSUE TITLE
builds/installs two setup manpages (and related issues)

### ISSUE THREAD

**Issue by jmtd** [fabiangreffrath/crispy-doom#235]
```
0:tharsis$ make install DESTDIR=$(pwd)/tmp
…
0:tharsis$ find tmp -name \*.6 -o -name \*.5
tmp/usr/local/share/man/man5/crispy-doom.cfg.5
tmp/usr/local/share/man/man5/default.cfg.5
tmp/usr/local/share/man/man6/chocolate-server.6
tmp/usr/local/share/man/man6/chocolate-setup.6
tmp/usr/local/share/man/man6/crispy-doom-setup.6
tmp/usr/local/share/man/man6/crispy-doom.6
```

Problems IMHO:

 * `chocolate-setup.6` shouldn't be installed (it's identical to `crispy-doom-setup.6`)
 * `chocolate-server.6` should be renamed (the corresponding binary is `crispy-server`)

**Comment by fabiangreffrath** [comment]
IMHO this is rather an upstream issue, because the filenames are hard-coded there to `chocolate-server.6` and `chocolate-setup.6`, respectively. We should rename them to e.g. `server.6` and `setup.6` and then copy them over to `@PROGRAM_PREFIX@-server.6` and `@PROGRAM_PREFIX@-setup.6` in the build process.

`chocolate-setup` and `chocolate-doom-setup` may be the same program, but its calling semantics are different, i.e. the latter recognizes that it's supposed to set up Doom and thus doesn't ask for the game to configure at startup.

The Chocolate->Crispy conversion in the static manpages could be achieved by a mere `sed` call, I don't care and am too lazy to change them manually. ;)

**Comment by jmtd** [comment]
In case you are curious, the debian package work-in-progress I've pushed to ssh://git.debian.org/git/collab-maint/crispy-doom.git, but I'm focussing on improving the manpages in upstream before uploading (https://github.com/chocolate-doom/chocolate-doom/issues/959)

**Comment by fabiangreffrath** [comment]
Thanks for doing that! I wonder why you pushed the repo to collab-maint if you are going to have it maintained by the pkg-games team, though? Also, I don't think we need the `Recommends: zenity` and the `Breaks:` relations anymore (Crispy won't crash with any of the Freed[oo]m IWADs, they just may not work as intended). Also, I think we don't need most of the documentation that is shipped in `debian/rules`, Crispy's own canonical documenation is pretty much in `README.Crispy.html`.

**Comment by jmtd** [comment]
Thanks for the feedback. I couldn't be bothered to rejoin the games team and I figured Collab-Maint  is effectively a superset of it anyway.

Your points all look good

I've tagged you to request a review of the upstream docs work, I was wondering if you could consider it also from a crispy POV

Thanks!

**Comment by fabiangreffrath** [comment]
> I've tagged you to request a review of the upstream docs work, I was wondering if you could consider it also from a crispy POV

I have already replied on that.

**Comment by jmtd** [comment]
> I have already replied on that.

If you mean your sed suggestion, that's fine for the Debian package (although I'm preferring to commit some sed and manual changes to a patch in `debian/patches`), but the stuff to change upstream in Chocolate is a bit more substantial, and so is the PR.

**Comment by fabiangreffrath** [comment]
No, I meant the few nitpicks I added to
https://github.com/chocolate-doom/chocolate-doom/pull/962

**Comment by jmtd** [comment]
Oh, I completely missed any nits/comments. I'll take a closer look tomorrow (maybe web interface is also hiding them). Thanks!

**Comment by fabiangreffrath** [comment]
@jmtd Do you think the upstream fix is appropriate so that we can close this?

**Comment by jmtd** [comment]
Yes. There are some other bugs to fix upstream but they will be fixed... upstream :) Thanks
