### ISSUE TITLE
Add brief descriptions to Crispness menu

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#236]
The Idea - is to add brief descriptions for some of Crispy's features right in Crispness menu.

Probably not all features require description, just some of them.

### Mockup

Literally it's a prototype, since I was made some changes in the code to get a real, not a drawn picture:

![](http://screenshot.ru/upload/images/2017/11/27/mockupd8eac.png)

And couple of necessary explanations:

- I'm using `cr_tan` color translation. In my opinion, tan color is the only acceptable here: description is not a selectable menu item, no need to make it too notable. But text shadows also making a huge sense here by preventing text to be "mixed" with tan background. Also, Doom's [PLAYPAL](https://doomwiki.org/w/images/8/8b/Doompal.png) have a very rich tan colors. Probably tan color translation could be brighter, not sure... But gladly will hear any recommendations.
- We need two lines for description, since it seems to be impossible to describe all the features with one line of text.
- Text alignment is centered. Again, because of impossibility to make a super short descriptions.
- Vertical coords for both lines should always be same and constant in all pages, for preventing "jumping". In terms of UX design, this description is "logical block", no need to move it up/down in different pages.

### Features that require a brief description

Let it be step №2, at first we need to understand - do we really need this feature at all? Despite of I know what all the features are doing (and more of that, I mostly know how they are done technically!), I still can take a common player's POV to make some recommendations. Hopefully. :)

### Technical stuff

Sorry, I can't provide a proper solution for this, because my current implementation is nothing more than a quick hack just for show. However, here's some code that will be useful:

**1.** `CR_TAN` HSV translation:
```
    if (cr == CR_TAN)
    {
        hsv.x = 40./360.;  // Hue
        hsv.y = 0.40;      // Saturtion
        hsv.z *= 0.55;     // Value
    }
```

**2.** Vertical coord for the first text line:

`M_WriteText(ORIGWIDTH/2 - M_StringWidth(item) / 2, 169, crispy_menu_text);`

and for the second:

`M_WriteText(ORIGWIDTH/2 - M_StringWidth(item) / 2, 178, crispy_menu_text);`

**3.** In case you are worried about color quality of `CR_TAN` translation, here's the whole alphabet and symbols:

![](http://screenshot.ru/upload/images/2017/11/27/mockup21eebc.png)
___

So... Is this idea is interesting and acceptable? I'm open to hear any corrections and recommendations.

_Suggestion №79_

**Comment by JNechaevsky** [comment]
Another idea is to put descriptions between these logical lines:
![](http://screenshot.ru/upload/images/2017/11/27/centeredee603.png)

This will probably will look more better and logical in terms of UX design, but from another side, this also gives much less space for the description itself.

**Comment by fabiangreffrath** [comment]
I like this idea pretty much, actually, but I see one inevitable issue: There are some menu items that are so obvious that it is sufficient to describe them in half a line, i.e. about as much space as the item itself takes. But there are others which require about a whole manual page to properly describe them. What should I do with these?

So, to summarize: If it is not possible to properly describe a menu item on its own single line, how could I properly explain it on two lines. And, on the other hand, if it is already possible to describe an item on one line, what should I write on the bottom two lines without sounding redundant?

**Comment by JNechaevsky** [comment]
Aha. For these cases I can offer following:

- Obvious features: simply left description blank.
- Not obvious features: this will require linguistic brainstorming. Maybe some very brief and simple description, that gives some basic understanding. At least we can try to compose such a descriptions, but this is my weak point, you know how "perfect" my Russian English.

**Comment by JNechaevsky** [comment]
Since menu items grow higher in amount, now there is simply no place for any short and proper descriptions. Using a non-scaled, i.e. `hires` independent text will be both not looking good and dangeours for non-`hires` (here, I'm using [V_DrawPatchUnscaled](https://github.com/JNechaevsky/russian-doom/blob/master/src/v_video.c#L828) strictly for unscaled crosshair).

Maybe we should consider making a separate page in Chocolate Wiki with descriptions and some screenshots? For example, you know what all the features are doing, @Zodomaniac and I also know, but some players probably don't.

Next, somewhere in first lines of Crispy description text like this can be placed: "All Crispy features are described in Wiki page".

**Comment by fabiangreffrath** [comment]
Very good idea, but we shouldn't probably occupy too much space on the Choco Wiki. One page with brief descriptions of all the features in the Crispness menu should be enough.

**Comment by JNechaevsky** [comment]
Agreed. The only thing - I'd better offer my services in graphical/video aspects there, because frankly, my English level is definitely something like "we bar**r**ely can speak Americano".

**Comment by JNechaevsky** [comment]
Looks likes now there is simply no place for any, even brief texts in Crispness menu, especially for using standard STCFN text. Another possible idea - add a sting like "h - brief description for selected feature", but no, this will be a cascade of windows, a "staircase" like: go here, select this, then press `h`, then close it and so on.

**Comment by fabiangreffrath** [comment]
Now that we even maintain a Wiki on the Github project page, maybe this would be the best place to add one-sentence descriptions to each feature switch in the Crispness menu. What do you think?

**Comment by JNechaevsky** [comment]
I'm all at your services as always, but I definitely will need a proof-reader, my English does not seems to be good and clear enough sometimes.

What can suggest ATM: create a new page "Crispness" (beneath "Home"), with template like this:

--------------

Crispy Doom offers various optional enhancements, ...

### Rendering

Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.

**High resolution rendering**
  * Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor

**Uncapped framerate**
  * ON: many-many fps.
  * OFF: lock to original 35 fps.
  * VSync This is how Crispy should be played.

### VIsual

Nullam dictum felis eu pede mollis pretium. Integer tincidunt.

**Brightmaps**
  * Off: for purists
  * Items: for first half of Crispy auditory
  * Walls: for second half of Crispy auditory
  * Both:  for everyone!

**Comment by JNechaevsky** [comment]
Oh, by the way, before we move on, I need some priorities from you. What is more important, working on Wiki page (faster, needs proof-reading), or working on collection of testing cases (much slower, needs just some extra ideas)?

**Comment by fabiangreffrath** [comment]
I can do the Wiki pages, no problem. I have some ideas already, and I guess I am pretty good at explaining what the features are. However, I suck at level making on an incredible level, so please you take over this. :grin:

**Comment by fabiangreffrath** [comment]
Closing, as the documentation of the Crispness menu in the Wiki is considered complete now:
https://github.com/fabiangreffrath/crispy-doom/wiki/Crispness
