### ISSUE TITLE
Resolution & lack of integer scaling

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#237]
I noticed in 5.0 that you can no longer choose a fullscreen resolution.  When I launch the game, it is scaled vertically 100% as opposed to being integer scaled like it used to be in previous versions.

**Comment by fabiangreffrath** [comment]
Well, back in the SDL1.2 times, seamless scaling up to the max vertical resolution was the most requested feature. Now, we deliver right that and people start requesting the opposite. ;)

I consider this a non-bug, but we have indeed introduced a "secret" option in the config file for people like you who prefer the previous behaviour:

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/i_video.c#L1524
