### ISSUE TITLE
Command-line parameter ideas: music playback and sound recording

### ISSUE THREAD

**Issue by krozett** [fabiangreffrath/crispy-doom#238]
This began as a feature request for Chocolate Doom (https://github.com/chocolate-doom/chocolate-doom/issues/951) but I've fleshed the idea out a bit more.

What I envision is a `-playmusic` parameter similar to `-playdemo`, except it plays a music lump without any video output. Just a command-line music player, using whatever driver and IWADs Crispy is set up to use (there are some minor playback differences depending on the engine version, for example).

I've already got code that works for the OPL driver, though much of it is hard-coded.

A separate but related feature I'd also like to see is something like `-recordsound` that logs all of Crispy's sound output to a WAV file. It could possibly have use on its own, or to be used with `-playmusic` to essentially be a MUS-to-WAV converter.

Before I do any more work and make a PR, I'd like to ask if there is any interest in either of these features. I think they're reasonable to add, but could be feature creep. I'm also considering the idea that a standalone player reusing Chocolate's code would be better.

What do you all think?

**Comment by fabiangreffrath** [comment]
I am generally not opposed to such a feature, but the impact on the rest of the code should be minimal. Thus, I'd appreciate if you could open a pull request with the code you currently have, even if it is not yet polished.

What I mean by this is that I could agree on a command line option that dumps a single track of background music to disk, without starting the game itself (similar to how the `-mergedump` feature currently works). I do not agree, though, that it should be possible to turn Crispy Doom into a mere Doom music player (the other option would already serve that purpose if the dumped music file is fed into a real player). And I don't see any real use in recording all the played SFX into a file, though.

**Comment by krozett** [comment]
I see what you mean about impacting the rest of the code. I may as well just write a separate routine that only calls the bare minimum needed to play the music, rather than trying to work around things in the main loop.

Actually that's what I started doing, but too much of the code depends on seemingly-unrelated stuff. For example, the timer (which I assume the music code needs so the tempo is right) depends on the network initialization stuff. I could probably figure it out, this was just the shortcut to get what I wanted.

**Comment by fabiangreffrath** [comment]
I would accept a command line option that "records" a Doom music track to disk using the internal OPL emulator, but I don't see this is going to lead anywhere soon.
