### ISSUE TITLE
Crispy Heretic development plan

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#240]
### Engine strengthening

| Feature | Commits to apply | Pull request | Done? |
| ------- | -----------------| ------------ | ----- |
| Upgrade renderer to use 32-bit integer math | https://github.com/fabiangreffrath/crispy-doom/commit/31f33df5a59641bfa359cf26b034a7a462b269d5 | https://github.com/fabiangreffrath/crispy-doom/pull/242 | :heavy_check_mark: |
| Remove slime trails            | https://github.com/fabiangreffrath/crispy-doom/commit/4618754ab2a30f5e9a19e30ab8e872f64f9ad04d, https://github.com/fabiangreffrath/crispy-doom/commit/98a1cb352dd85ef27d5f9533543328f157d9d8a1 | https://github.com/fabiangreffrath/crispy-doom/pull/242 | :heavy_check_mark: |
| Fix wobbling long walls        | https://github.com/fabiangreffrath/crispy-doom/commit/2cd6aeb12d6881c838d03f06ec95132f498d7c2d, https://github.com/fabiangreffrath/crispy-doom/commit/95b1e1a71e098a8cd533aef7bfd66b3dc9908198, https://github.com/fabiangreffrath/crispy-doom/commit/11c7be0211e2de89e00fdcee6c7bacc52944edbf, https://github.com/fabiangreffrath/crispy-doom/commit/2a54d71b41c10375ad91c9689155e5f8b67699c5, https://github.com/fabiangreffrath/crispy-doom/commit/6414c85d640e60eb9ef4f1db998901221aa05251, https://github.com/fabiangreffrath/crispy-doom/commit/ddba6706c564257dbbbfd5c728cdf305e9e2a391  | | |
| Fix wall wiggle                | https://github.com/fabiangreffrath/crispy-doom/commit/ab0bc9aa5139269095fdde7fee440b183233ec6e | | |
| Fix Tutti Frutti effect        | https://github.com/fabiangreffrath/crispy-doom/commit/eaf48d3e656197084a476295f56f3530f9775626 | https://github.com/fabiangreffrath/crispy-doom/pull/277 | :heavy_check_mark: |
| Fix Medusa effect              | https://github.com/fabiangreffrath/crispy-doom/commit/6e475fd8e4fa652c5ef1c862afdb41ee11d42a3b | | |
| Fix flat distortion            | https://github.com/fabiangreffrath/crispy-doom/commit/5f9745adf50f89304f3ec4d38242b8bf8f0dd928 | | |
| BLOCKMAP re-creation           | https://github.com/fabiangreffrath/crispy-doom/commit/b5dd11fc8b2fb105e0e62d6f551d2a11b3a0ec6e | | |
| Support huge levels in Automap | https://github.com/fabiangreffrath/crispy-doom/commit/290767164f9545ac54e1429605b4804f8a856834 _is it?_ | | |
| Draw hitscan puffs in outdoor areas | https://github.com/fabiangreffrath/crispy-doom/commit/441e19c937e02a18a524d425477a0c2ec31201e0, https://github.com/fabiangreffrath/crispy-doom/commit/cb3c0a1241b3914a70244af51b3b5ee8899fb96f | | |
| Missiles aren't absorbed by outdoor walls | https://github.com/fabiangreffrath/crispy-doom/commit/160d289e3bd29f6995d3e37773df5d381a334401 | | |

### Limit removing

| Feature | Commits to apply | Pull request | Done? |
| ------- | -----------------| ------------ | ----- |
| Support for extended nodes | https://github.com/fabiangreffrath/crispy-doom/commit/d3b76990baecb0cd7390d21ba30bf1243c442521 | | |
| Remove BLOCKMAP limit      | https://github.com/fabiangreffrath/crispy-doom/commit/423debf9c9ef18dfc794317a6104120adea39ee8 | | |
| Remove MAXVISSPRITE limit  | https://github.com/fabiangreffrath/crispy-doom/commit/cf5ba4f541d38a44af59706ef3e8d82ddd2661c8, https://github.com/fabiangreffrath/crispy-doom/commit/bf22739abeab14c78f221dca167464470978e544 | | https://github.com/fabiangreffrath/crispy-doom/commit/9f4295e58d171abcbd3db81d572af8f3324c1fe3 |
| Remove MAXVISPLANES limit  | https://github.com/fabiangreffrath/crispy-doom/commit/f15b987638d5a669e19f1411d73ad4a087d317dc | | https://github.com/fabiangreffrath/crispy-doom/commit/9f4295e58d171abcbd3db81d572af8f3324c1fe3  |
| Remove MAXDRAWSEGS limit   | https://github.com/fabiangreffrath/crispy-doom/commit/11bf8a64666614cbad65e9a7e7df33d17760aed4 | | https://github.com/fabiangreffrath/crispy-doom/commit/9f4295e58d171abcbd3db81d572af8f3324c1fe3 |
| Remove INTERCEPTS limit    | https://github.com/fabiangreffrath/crispy-doom/commit/8ed01f3bf7c2417698a08fa4bcf0cab6a91ce23d | | |
| Remove MUS size limit      | https://github.com/fabiangreffrath/crispy-doom/commit/e85d6c21d2f59aad1eed11cdefff24c60a87e0ea | _not needed_ | :heavy_check_mark: |
| Disable PWAD lump number limit | https://github.com/fabiangreffrath/crispy-doom/commit/2777de87368d53a646aa46760ba06abd4539de05 | | |

### De-fatals

| Feature | Commits to apply | Pull request | Done? |
| ------- | -----------------| ------------ | ----- |
| Missing textures/patches | https://github.com/fabiangreffrath/crispy-doom/commit/092f14359b28e91d4efcaf32e052a2ba16ce8529 | | |
| Missing flats            | https://github.com/fabiangreffrath/crispy-doom/commit/5c9386303cd63a4ffa8f436f1908972196763c7c, https://github.com/fabiangreffrath/crispy-doom/commit/cd610df01cb6aff4791a703636da64fa5c597be3 | | |
| Unknown map things       | https://github.com/JNechaevsky/russian-doom/commit/82b1f3e6816b4bcbc9acc6f2b754bb904b3e059d | | |
| Unknown sector types     | _where is it?_ | | |
| Door with wrong INDEX    | https://github.com/fabiangreffrath/crispy-doom/commit/e1f22dbbe7daead169013e2f985b43aa6a35ba56 | | |

### Crispy iconic

| Feature | Commits to apply | Pull request | Done? |
| ------- | -----------------| ------------ | ----- |
| Crispness menu       | _where is it?_    | | |
| Crispy HUD           | _where is it?_    | | |
| Crosshair            | _decision needed_ | | |
| Colorized status bar | _where is it?_    | | |
| Jumping              | _where is it?_    | | |
| Cheat codes          | _where is it?_    | | |
| Mouse look           | _where is it?_    | | |

### Various (low priority)

| Feature | Code example | Pull request | Done? |
| ------- | -----------------| ------------ | ----- |
| Add toggleable "always run"                     | https://github.com/fabiangreffrath/crispy-doom/commit/50058916de465a22c3c0691527252df8268ea435 | | |
| Never show the yellow palette for a dead player | https://github.com/fabiangreffrath/crispy-doom/commit/697581ff710358b5e004d5d0632db949f7c105e5 | | |
| Sound effect for manually closed DR             | https://github.com/fabiangreffrath/crispy-doom/commit/549916542dfa2ef70b7c9550c6eef770264a1ae7 | | |
| Add VERSION cheat code                          | https://github.com/fabiangreffrath/crispy-doom/commit/1e4df6e461dd093c3ebd42d94fee6bc95d7cb854 | | |

### Crispy Heretic icon

Should be a stylized green 'H' (just as the current logo for Doom is a stylized 'D' that is "somehow similar" but not too close to the original) on the "crisps" background that could also get used by Choco for the left part of their icon.

### Stress-testing map

Revision 0 (dd.mm.yyyy)

- _to be created..._

**Comment by JNechaevsky** [comment]
@fabiangreffrath, awaiting your inspection and approval.

**Comment by fabiangreffrath** [comment]
First, thank you very much for doing this! I think this is a great starting point.

Two remarks:

- I am missing some features that are somehow iconic to Crispy Doom, e.g. the Crispness menu, the Crispy HUD, a crosshair (do we need a projected crosshair at all? are there any hitscanner weapons the player could use in Heretic?), colorized status bar elements, jumping, the cheat codes, mouse look, etc.

- Although this may sound against the spirit of GIT, but I'd rather not focus on the initial commits which introduced a specific feature, but rather how this feature looks today. There are often many code changes being applied to a feature even after its initial commit that we would miss otherwise. As an example, the introduction of the `I_Realloc()` function upstream at Choco's required changes to aall limit-removing code. Another more current example: https://github.com/fabiangreffrath/crispy-doom/commit/3ff49758f7dc6618d25030cb3377ad21a02c117b and then https://github.com/fabiangreffrath/crispy-doom/commit/83d611cfe171fb450758e7af0ec00ce37172eafa .

**Comment by JNechaevsky** [comment]
> I am missing some features that are somehow iconic to Crispy Doom

Yep. They should be here, and I'll add them, but I'm afraid I can't handle them all by myself. To be more clear:
- Crispness menu. At the moment, it is too hard for me to understand how it's implemented. I will need some directions or even better your implementation with some dummies/placeholders, which will give me a starting point.
- Crispy HUD. I have not tried to implement it yet (not sure it will look as good as in Doom), but I've created my own implementation, see: https://github.com/JNechaevsky/russian-doom/issues/23. It's cool, but the price of it - some notable changes in the original code and I'm not sure I can suggest it for Crispy.
- Crosshair. Well, there are two hitscan types of attack - Elven Wand and Dragon claw. If we are not going to implement disabling of vertical autoaiming, I think crosshair itself is not very needed.
- Colorized status bar. Require a color translation code that I never handled in previous. Need a starting point.
- Jumping. Seems to be not hard to implement, need to try.
- Cheat codes. Seems to be not hard to implement, need to try. There are already `MASSACRE` cheat that acts as `TNTEM`, though.
- Mouse look. Totally needed! But probably, I will need a starting point.

> I'd rather not focus on the initial commits which introduced a specific feature, but rather how this feature looks today

This is getting things much harder, but this is a right thing to to. :| I think a proper way for me here will be taking a look at initial commit and verifying it with current code.

Following this scheme, I will try to commit "Upgrade renderer to use 32-bit integer math" very soon.

**Comment by fabiangreffrath** [comment]
Sound good, thanks. It's good coincidence that you are collecting similar experience with your own Russian Heretic project currently. Take your time, we are not in a hurry. ;)

**Comment by JNechaevsky** [comment]
Done a stylized icon by your directions. Is it looks okay? Any suggestions?

![](http://screenshot.ru/upload/images/2017/12/02/CrispyHereticIcon-128bb1d1.png)

**Comment by fabiangreffrath** [comment]
This icon is absolutely wonderful! This is *exactly* what I had in my mind and you somehow made it into pixels. Please, do me a favor and file a request on the Choco tracker to add the green-H part of this icon as the right half of the Chocolate Heretic icon. Currently, all four games use the same icon and we need to develop some infrastructure first to provide each game its individual icon.

.oO(If you now could draw some stylized red X for Hexen and some... something for Strife)

**Comment by JNechaevsky** [comment]
Thank you for positive feedback, I'm really glad that you like it! Here, all the sizes, necessary and unnecessary, including gorgeous 512x512, as well as Windows .ico file:

- http://jnechaevsky.users.sourceforge.net/files/crispy-heretic-icon.zip

I believe that additional sizes are now as necessary as never before, since Jon is preparing Debian package and Linux may use kinda different icon sizes.

In my project I'm just replacing icon files (as well as some strings in config files) before release compilation, that's why I have different icons in Windows binaries. But needles to say that this trick is working only for Windows.

Ticket for custom Heretic icon in Chocolate tracker: https://github.com/chocolate-doom/chocolate-doom/issues/965

And of course, no problem, I'll handle Hexen and Strife icons, it will just require some time. I'm definitely better with moving pixels, rather than in operating with code. :)

**Comment by Danfun64** [comment]
Actually, because of [this](https://www.doomworld.com/vb/source-ports/85064-mouselook-freelook-for-vanilla-heretic-hexen-and-strife/) , I've been trying to get mouselook into _Chocolate_ Heretic, as displayed by my bringing up the following issue there: chocolate-doom#876

**Comment by fabiangreffrath** [comment]
Sure, mouselook in Heretic (either Crispy or Choco) would be cool!

> On a related note, I know you marked #64 as wontfix, however note that Heretic lacks an equivalent of PrBoom-Plus, and Crispy Heretic might become the closest thing...

What does one have to do with the other?

**Comment by fabiangreffrath** [comment]
Hey @JNechaevsky if you feel really bored, do you think you could tackle the Tutti-Frutti fix for Heretic? :smiley:

**Comment by JNechaevsky** [comment]
Sure I can, and I've got it fixed in my fork, But the problem is - how many lines of code got changed since your initial fix (which I have applied and tested)? As we have seen, I got problems with updating initial code to Crispy's actual code.

**Comment by fabiangreffrath** [comment]
Maybe the following tactics work:
1) Identify the relevant commits which introduce the changes we want to port over
2) Identify the lines of code that were changed by these commits
3) Inspect the current code, identify the code lines from (2) and apply the changes from (1) as if they were commited today

**Comment by JNechaevsky** [comment]
I'm afraid you are still thinking too high about my coding skills. :/ I can accurately copy-paste such a hard technical code, but not actually understand it. Yeah, there are just a few lines, but for me it's a still "few lines of black magic". Even my logical understanding of some code is not good enough in some places. 

We need something another, like... 

1. I can commit initial code after verifying that it actually working.
2. You are inspecting commit, making your comments on formatting and etc.
3. If something still not actual enough, you are changing commit to actual code.

It's kinda ugly scheme, and literally meaning double work, but it's have a "proper seed" because you know (and understand!) your code much better and can figure out what should be changed. For me such a moments can be something like a dead-end.

**Comment by fabiangreffrath** [comment]
Well then, let's try it like this (but we are not in a rush, please take your time!).

**Comment by JNechaevsky** [comment]
Uh-oh. What should I uncomment in makefiles to make a Heretic executable being build under MSYS?

**Comment by fabiangreffrath** [comment]
Just try running `make crispy-heretic.exe` in the src/ directory.

**Comment by fabiangreffrath** [comment]
I have updated the code in your branch a bit, could you please check if it works for you?

**Comment by JNechaevsky** [comment]
Sorry for my long reply. Nope, it does not seems to working with testing wad.

![](http://priscree.ru/img/943c8f2c53a2bb.png)

**Comment by fabiangreffrath** [comment]
Grmpf, I must have introduced a typo somewhere. Would you mind sharing the test map?

**Comment by JNechaevsky** [comment]
Sure, it was shared right in initial TF-fix commit (https://github.com/fabiangreffrath/crispy-doom/pull/277), here it is: 
http://jnechaevsky.users.sourceforge.net/files/tutti-heretic.wad

**Comment by fabiangreffrath** [comment]
@Jnechaevsky Thanks, now it should be tutti bene.

**Comment by JNechaevsky** [comment]
Bellissimo! Please wait until evening, I will check it. We have to be sure that "pixel disco" is also fixed.

**Comment by JNechaevsky** [comment]
Perfecto! 👌 I can confirm that both Tutti and Disco has been fixed now. What's our _(well, mostly your)_ next move?

**Comment by fabiangreffrath** [comment]
Thanks for the confirmation! I currently don't have any further plans for Heretic, just read somewhere in the forums that it works okay except for Tutti Frutti...

**Comment by JNechaevsky** [comment]
There is a request from SiFi270 in [Doom World](https://www.doomworld.com/forum/topic/67168-crispy-doom-51-update-jan-13-2018/?do=findComment&comment=1875612) forum about map stats for Heretic.

It's rather than simple to implement a traditional BOOM-style stats, here's my example: https://github.com/JNechaevsky/russian-doom/commit/db0dc9576979113859e1cebb18786e282845b01c. But it will require a variable, and thus, Crispness menu. :persevere:

**Comment by fabiangreffrath** [comment]
I have seen it, and this is exactly what keeps me from adding more features to Heretic (apart from the fact that I don't like the game myself): I just don't want to duplicate the work and implement a second Crispness menu for this game.

**Comment by kaphula** [comment]
Sorry for off topic, but I am confused does Crispy Doom support casual Heretic playing for the time being? I'd like to play the original vanilla Heretic with uncapped framerate. Is there a way to build the Crispy Heretic from the source of this repo that works?

**Comment by fabiangreffrath** [comment]
Your question is not off-topic at all. It is as easy to build Crispy Heretic from sources as running `make -C heretic ; make crispy-heretic.exe` in the `src` directory. However, you won't get uncapped framerate or any other fancy feature then. Crispy Heretic is years behind (literally!) in terms of development, that's why I don't include it in official releases (resp. hide it in the unsup directory).

**Comment by jgreen14** [comment]
I'm interested in getting Crispy Heretic up to to par with Crispy Doom. I put in a pull request for porting the doom blockmap removal code into heretic (I just picked it as relatively straightforward item to try implementing). Looking at the rest of the things in the "Engine strengthening" and "Limit removing" sections most of them wouldn't be too much more work to implement, so seem sensible to start with. Getting the Crispness menu and all the features into Heretic is obviously a much bigger job, but it seems like a fun project (and I would love to have a fully Crispy version of Heretic to play). The one thing I would like is links or pointers to some maps that would be good for testing.

**Comment by fabiangreffrath** [comment]
> I'm interested in getting Crispy Heretic up to to par with Crispy Doom. 

That's a very noble goal, thanks for your effort!

> The one thing I would like is links or pointers to some maps that would be good for testing.

Honestly, that's the one thing I was about to ask: Where is the one Heretic map that demands all these limit removing features? Does it even exist -- or are we doing all this just for academic interest?

**Comment by jgreen14** [comment]
> Honestly, that's the one thing I was about to ask: Where is the one Heretic map that demands all these limit removing features? Does it even exist -- or are we doing all this just for academic interest?

I've done a little research myself and found a number of Heretic wads that say they require limit removing ports ([Hymn](https://www.doomworld.com/idgames/levels/heretic/Ports/hymn) & [Curse of D'sparil](https://www.doomworld.com/idgames/levels/heretic/Ports/curse) are a couple of examples). There is also an old hacked version of the DOS heretic.exe called [Heretic+](https://sourceforge.net/projects/prboom-plus/files/heretic-plus/) (similar to Doom+), so limit removing in Heretic has existed for a while. I think that's enough evidence to consider the limit removing changes more than just an academic exercise.

**Comment by fabiangreffrath** [comment]
I think Crispy Heretic had its classic limits removed for quite some time. :wink:

**Comment by JNechaevsky** [comment]
Made some progress ([screenshot](https://user-images.githubusercontent.com/21193394/73204640-5a83d600-4150-11ea-86de-55aa830a8695.png)). There are couple of things left to understand:

1. For some reason, `dp_translation` is not working, matters no what kind of translation I'm using, it's always black: [screenshot](https://user-images.githubusercontent.com/21193394/73204473-11cc1d00-4150-11ea-8863-6094410866aa.png).
2. Pixel smoothing seems to be only one feature that working without any extra job in the code.
3. Horizontal alignment is not perfected (yet!).
4. BackSpace is not working on Crispness menu.
5. Having a "Crispness..." along with "More..." is not looking good, but recreating whole Options menu is a question of another day.

**Comment by fabiangreffrath** [comment]
Looks good, even alongside the "more..." menu. Let's stay as close to the original as possible. 

There is also the map statistics and level time feature available, but this requires a 0-1-2 switch.

**Comment by JNechaevsky** [comment]
No problem, this is working:
```
static boolean CrispyAutomapStats(int option)
{
    crispy->automapstats++;

    if (crispy->automapstats > WIDGETS_ALWAYS)
    crispy->automapstats = WIDGETS_OFF;

    return true;
}
```

I will add them, and also `crispy->playercoords`.

**Comment by fabiangreffrath** [comment]
Okay, but why don't you just use the code that's already in crispy doom? m_crispy.c?

**Comment by JNechaevsky** [comment]
Because I'm always too lazy to press `Ctrl+F`... :/ Thanks, it's working fine, I'm keep going.

**Comment by JNechaevsky** [comment]
> Pixel smoothing seems to be only one feature that working without any extra job in the code.

Nope, it is not preserved in config file, and thus, it's always `ON` on starting a new game. Must be declared as: `M_BindIntVariable("crispy_smoothscaling",   &crispy->smoothscaling);` in `d_main.c`. Not in this PR, please!

> Horizontal alignment is not perfected (yet!).

Fixed.

> BackSpace is not working on Crispness menu.

Fixed.

So far, we have this with as small code modification as I can do.
![image](https://user-images.githubusercontent.com/21193394/73210524-88224c80-415b-11ea-98c7-b2dcd34e80be.png)

Ready to make a PR.

**Comment by fabiangreffrath** [comment]
@JNechaevsky Does uncapped framerate with interpolation work well in RD? If yes, what speaks against applying the necessary changes here?

**Comment by fabiangreffrath** [comment]
With "RD" I mean Russian Heretic obviously. 😉

**Comment by jgreen14** [comment]
I spent a few hours today adding uncapped framerate with interpolation to Crispy Heretic and it works great! I didn't check if Russian Heretic had an uncapped framerate until after doing a fair number of changes, and I feel like if @JNechaevsky wants to pass the necessary changes back up to Crispy Heretic that would have the benefit of keeping a closer link between the ports. It would also save me having to clean up a couple little details I skipped over before making a PR 😉. On the other hand if that's not something @JNechaevsky is interested in or it might take a while to happen,  I would be happy to finish the changes and make a PR.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, yep, uncapped framerate in RH working fine and feeling great. There is nothing special and no underwater mines (unlike Hexen's polyobjects), so if @jgreen14 want to make a PR - sure, let's go ahead.

The only thing I was not able to implement is an interpolation of floors/ceilings texture scrolling.

Also, couple of month later, we have discovered a small visual bug with incorrect moving sector height while level loading from command line, and AFAIR it was fixed this way: https://github.com/JNechaevsky/russian-doom/blob/6454800f6d0041d4a70f7e88a52ed9ce3cf86f32/src/doom/p_setup.c#L536

**Comment by fabiangreffrath** [comment]
Cool. Is it already possible to toggle uncapped framerate in-game, i.e. in the Crispness menu? And how about Vsync?

**Comment by JNechaevsky** [comment]
I haven't checked it in Crispy yet. But since there is already such switch for Doom and code to make it VSync friendly, I think everything should be fine.

**Comment by fabiangreffrath** [comment]
I meant, it is currently possible to switch these features in-game in Russian Heretic?

**Comment by JNechaevsky** [comment]
Sure thing! Vsync and uncapped mode are working fine with all possible combinations.

**Comment by fabiangreffrath** [comment]
Is anyone still working on implementing uncapped frame rate and frame interpolation? Because, I'd like to release 5.7.3 anytime soon after Easter and I play the though to release Crispy Heretic alongside for the first time in years. Of course it would be cool to have a major new feature to present.

**Comment by jgreen14** [comment]
I have lots of free time this weekend so I can fix up the couple issues a make a PR by Sunday. I haven't done anything with Vsync so there might not be an option for that yet.

**Comment by fabiangreffrath** [comment]
Perfect 😉

**Comment by JNechaevsky** [comment]
Gentelemen, one small suggestion before release! Few years ago I have discovered small bug in vanilla Heretic: https://github.com/chocolate-doom/chocolate-doom/issues/781 (yay, my first issue on GitHub!).

I have fixed it by turning `ultimatemsg` to `false`, here: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/heretic/p_inter.c#L136, but this way `ultimatemsg` will no longer be unreplaceble by other messages.

Now I figured out a proper approach, all you need is to add:
```
    p->mo = mobj;
    p->playerstate = PST_LIVE;
    p->refire = 0;
    p->message = NULL;
+++ ultimatemsg = false;
    p->damagecount = 0;
    p->bonuscount = 0;
    p->chickenTics = 0;
```
in `P_SpawnPlayer` func https://github.com/fabiangreffrath/crispy-doom/blob/master/src/heretic/p_mobj.c#L994

**Comment by fabiangreffrath** [comment]
Though recognized as strictly Vanilla conforming, I agree that this is something that should be fixed. Also, your approach appears correct to me, i.e. any other field of the player_t struct is cleared, but this one.

Please file a PR with a short comment on the added line - or apply directly to the master branch, thanks!

**Comment by fabiangreffrath** [comment]
Oh wait, I can just cherry-pick that!

**Comment by JNechaevsky** [comment]
Awesome, thanks for accepting and confirming!

**Comment by fabiangreffrath** [comment]
I guess Crispy Heretic is in a pretty good shape right now. Any further improvements can be tracked in separate issues. Thanks @JNechaevsky for your work on this!
