### ISSUE TITLE
Please don't enable April 1st jokes by default

### ISSUE THREAD

**Issue by zenvoid** [fabiangreffrath/crispy-doom#244]
I would want to make a friendly request of not enabling the April first jokes (fliplevels) by default, or at least provide a build option to easily disable the "feature" without having to manually find and comment the code. On some parts of the world outside the United States, April 1st is not a day to play jokes. The equivalent here is on December 28th, but is not exactly the same, and due to cultural differences, it is not expected that computer programs behave different even in that day; it won't be seen as a joke but unexpected behaviour or bug.

**Comment by fabiangreffrath** [comment]
> here is on December 28th

Just out of interest, where is "here"?

**Comment by Zodomaniac** [comment]
Reasonable request, I think there should be a flag setting in Crispness-Visual for 'April 1 jokes: On/Off'.

**Comment by fabiangreffrath** [comment]
No, there has always ever been only one joke, and... you alread know that I hate to add options to the menu! :angry: :smiling_imp:

**Comment by zenvoid** [comment]
> Just out of interest, where is "here"?

Thank you for adding the build option. Here is Spain, I found this article that provides more details in case you are interested: https://www.thoughtco.com/spains-equivalent-of-april-fools-day-3971893
