### ISSUE TITLE
Add an option to choose between original and new map colors

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [fabiangreffrath/crispy-doom#248]
Like it was already mentioned on the DoomWorld forum, there should be an option to disable new map colors. Not only it's a significant visual change, but it also affects gameplay to some extent by making the navigation easier with those colored key doors and teleporters.

**Comment by fabiangreffrath** [comment]
Thanks, but this has already been reported in https://github.com/fabiangreffrath/crispy-doom/issues/245
