### ISSUE TITLE
Suggestion about mouse look direction

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#251]
Have a small suggestion about mouse looking direction. Here's an example case:

- Start the game normally and run any level.
- Enable mouse look, look up or down, and save the game.
- Now, disable mouse look in game menu and load the game.
- Looking direction will be "freezed" and will not be able to change until you enable mouse look again.

I.e., in this case player is forced to go to the menu and enable mouse look. Maybe it's worth to make a very simple check of enabled mouse look, and in case it's disabled, reset looking direction to `0`?

Please take a look at my solution for reference:
https://github.com/JNechaevsky/russian-doom/commit/bd4aa7641c4418c67f424bb18396eafc258d0239

_Suggestion №80!_

**Comment by fabiangreffrath** [comment]
Absolutely! Interesting that this hasn't been reported before. ;)

Please note that technically you could also have keyboard-look enabled to reset looking direction back to horizontal, so I have to take this into accont as well.

**Comment by JNechaevsky** [comment]
Thanks for acception! I have found this necessity while numerous startings/closings of E1M1 while testing clipping problem in another issue.

In Doom I don't have a keyboard vertical looking, so it's seems to be safe. As about Heretic and Hexen, well, these games are designed to have mouse look, so probably it will be better to leave direction as is. Thanks for advice any way!
