### ISSUE TITLE
Add brightmaps for HACX

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#252]
### Map for testing (MAP01)

All the textures, flats and sprites are here.
- [bmaps-hacx.wad](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/bmaps-hacx.wad)

#### TEXTURE1 bank (one and only)

|  №  | Texture | Name     | Brightmap | Comment
| --- | ------- | -------- | --------- | -------
| 1-4 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/BFALL3.png)    | BFALL1-4 | redonly        | Red eyes are prerry dimmed, not sure that redonly will work. Also please try redandgreen.
|   5 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/BRNSMALR.png)  | BRNSMALR | greenonly1     |
|   6 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/DOORRED.png)   | DOORRED  | greenonly1     | Or maybe redandgreen?
|   7 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SLADWALL.png)  | SLADWALL | redonly        | Or notgrayorbrown? Hm.
|   8 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SW1BRCOM.png)  | SW1BRCOM | redonly?       | Probably not safe for handset. See below for SW2BRCOM.
|   9 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SW1BRN1.png)   | SW1BRN1  | redandgreen    |
|  10 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SW1BRN2.png)   | SW1BRN2  | notgrayorbrown |
|  11 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SW1BRNGN.png)  | SW1BRNGN | notgrayorbrown |
|  12 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SW1BROWN.png)  | SW1BROWN | notgrayorbrown |
|  13 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SW2BRCOM.png)  | SW2BRCOM | greenonly      |
|  14 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SW2BRN1.png)   | SW2BRN1  | redandgreen    |
|  15 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SW2BRN2.png)   | SW2BRN2  | notgrayorbrown |
|  16 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SW2BROWN.png)  | SW2BROWN | notgrayorbrown |
|  17 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/COMPSPAN.png)  | COMPSPAN | greenonly      |
|  18 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/COMPSTA1.png)  | COMPSTA1 | notgrayorbrown |
|  19 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/COMPSTA2.png)  | COMPSTA2 | notgrayorbrown |
|  20 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/HD5.png)       | HD5      | redandgreen    | Or maybe just a redonly, there is one green pixel in small right monitor.
|  21 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/HD8.png)       | HD8      | redandgreen    | Probably not safe for the top part
|  22 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/HD9.png)       | HD9      | redandgreen    | Probably not safe for the top part
|  23 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/BLAKWAL2.png)  | BLAKWAL2 | redandgreen    | Probably not safe at all!
|  24 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/CEMENT7.png)   | CEMENT7  | greenonly1     |
|  25 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/ROCK4.png)     | ROCK4    | redonly        | Probably not needed for this one. Only one pixel in a small button is colored red.
|  26 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SLOPPY1.png)   | SLOPPY1  | notgrayorbrown |
|  27 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SPCDOOR4.png)  | SPCDOOR4 | notgrayorbrown | Probably not needed at all!
|  28 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/ZZZFACE1.png)  | ZZZFACE1 | greenonly1     |
|  29 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/ZZZFACE2.png)  | ZZZFACE2 | redandgreen    | Probably not safe for wires
|  30 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/HW166.png)     | HW166    | redandgreen    | Probably not safe for wires
|  31 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/HW510.png)     | HW510    | notgrayorbrown |
|  32 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/HW511.png)     | HW511    | notgrayorbrown |
|  33 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/HW512.png)     | HW512    | notgrayorbrown |

### Floors and Ceilings

|  №  | Flat    | Name     | Brightmap | Comment
| --- | ------- | -------- | --------- | -------
|   1 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/FLOOR1_1.png)    | FLOOR1_1  | notgrayorbrown | 
|   2 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/FLOOR1_7.png)    | FLOOR1_7  | notgrayorbrown | 
|   3 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/FLOOR3_3.png)    | FLOOR3_3  | notgrayorbrown | 
| 4-6 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/NUKAGE1.png)     | NUKAGE1-3 | notgrayorbrown | Animation sequence: NUKAGE1, NUKAGE2, NUKAGE3
| 7-9 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/BLOOD1.png)      | BLOOD1-3  | greenonly1     | Animation sequence: BLOOD1, BLOOD2, BLOOD3
|  10 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SLIME13.png)     | SLIME13   | notgrayorbrown |
|  11 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SLIME14.png)     | SLIME14   | notgrayorbrown |
|  12 | ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SLIME15.png)     | SLIME15   | notgrayorbrown |

### World sprites

| Sprite | Thing name     | Brightmap |
| ------ | -------------- | --------  |
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/CSAWA0.png) | MT_MISC26 (Chainsaw)         | redonly
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/LAUNA0.png) | MT_MISC27 (Rocket launcher)  | redandgreen
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/PLASA0.png) | MT_MISC28 (Plasmagun)        | redonly
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/BON1A0.png) | MT_MISC2 (Health Bonus)      | notgrayorbrown (or redandgreen) 
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/STIMA0.png) | MT_MISC10 (Stimpack)         | notgrayorbrown (or redandgreen)
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/CELLA0.png) | MT_MISC20 (Cell Charge)      | redonly
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/CELPA0.png) | MT_MISC21 (Cell Charge Pack) | redonly

### HUD sprites

Needed your implementation of support for brightmaps in HUD.

**Comment by fabiangreffrath** [comment]
As always, thank you very much!

> Needed your implementation of support for brightmaps in HUD.

This can be done quickly. What would you highlight?

**Comment by JNechaevsky** [comment]
It's my pleasure. :)

> This can be done quickly. What would you highlight?

Here we go. I may be a little wrong with states, they are slightly different from Doom, but I have verified with `info.c` and hope that everything will be okay. I haven't touched `fullbright` states, so there are no any necessary fallbacks.

### HUD sprites

| Weapon | Sprite           | State | Brightmap |
| ------ | ---------------- | ----- | --------  |
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SAWGA0.png) | SAWGA0 | S_SAW2    | lightning
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SAWGB0.png) | SAWGB0 | S_SAW3    | lightning
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SAWGC0.png) | SAWGC0 | S_SAW     | redonly
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/SAWGD0.png) | SAWGD0 | S_SAWB    | redonly
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/MISGA0.png) | MISGA0 | S_MISSILE | redandgreen (or redonly)
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/PLSGA0.png) | PLSGA0 | S_PLASMA  | redonly
| ![](http://jnechaevsky.users.sourceforge.net/files/brightmaps/hacx/PLSGB0.png) | PLSGB0 | S_PLASMA2 | redonly




Brightmap `lightning`:

```
static byte hacxlightning[256] =
{
	0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};
```

In case you are wondering, here's how I'm calculating colors: [screenshot](http://screenshot.ru/upload/images/2018/01/09/howdba10.png). Colors that selected as squares are represented in the table above. Absolutely designer's solution!
