### ISSUE TITLE
Window goes out of vertical bounds in non FullHD mode at startup

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#254]
On first launch, until `crispy-doom.cfg` have not been created. Steps to reproduce:

1. Delete `crispy-doom.cfg` file.
2. Reduce screen resolution to something like 1360x768 or lower.
3. Start Crispy normally and switch to the windowed mode.
4. Game window will be slightly out of vertical screen bounds, until you will not change it's size.

**Video demonstration:** 
- https://youtu.be/9VNJu73OHEg

**Solution:**

It can be easily fixed by removing `* 2` multipliers from here (that's how I've solved it for myself):
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/i_video.c#L113

**Comment by fabiangreffrath** [comment]
> It can be easily fixed by removing * 2 multipliers from here (that's how I've solved it for myself):

Indeed, that's a (dangerous) remnant from the Choco code base, where the initial window resolution is doubled from the antive resolution, which in turn is not desirable for Crispy. Thanks for noticing!
