### ISSUE TITLE
Issue with FLAC

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#255]
When using the FLAC digital music pack under the v5.1 Windows version, there is an obvious hiccup at the beginning.  The first half-second or so of a song is repeated.  This also happens every time a song loops.

This issue does not occur with OGG.

This issue is not present in Chocolate Doom v3.0.0.

**Comment by buvk** [comment]
Chocolate 3.0.0 has the same issue if I use the libraries shipped with Crispy.  Using Chocolate's libraries with Crispy resolves the issue.

**Comment by fabiangreffrath** [comment]
That's good to know, thanks for checking!

**Comment by Zodomaniac** [comment]
Maybe it would even make sense to do a hotfix release of 5.2 when this is fixed?

**Comment by fabiangreffrath** [comment]
What am I supposed to fix here? @buvk has confimed this is an issue with the latest SDL2 and SDL2_mixer libraries.

**Comment by Zodomaniac** [comment]
@fabiangreffrath Push an update to Crispy to use the libraries Choco 3.0.0 uses.

**Comment by fabiangreffrath** [comment]
No, sorry, but I don't think that reverting back two SDL releases may be considered a "fix" in any way. This is clearly an SDL upstream issue, so it has to get located, reported and fixed there.

Else, hypothetically, what if SDL 2.0.8 gets released soon without this fix - and then 2.1.0 some months later or whatever. Should I still stay with 2.0.5 because there was this issue with FLAC playback on Windows back then?

**Comment by Zodomaniac** [comment]
@buvk  Which version of Windows do you have? I cannot reproduce this with Windows 7.

**Comment by buvk** [comment]
I am using Windows 10.

**Comment by buvk** [comment]
Tested again using crispy-doom-20180324-win32; I no longer experience this issue.

**Comment by fabiangreffrath** [comment]
Probably related to @fragglet's fixing of the loop metadata code in https://github.com/chocolate-doom/chocolate-doom/commit/ded7e89d0f5ee328b88c90000dcf3e3e2cba7b88

**Comment by buvk** [comment]
@fabiangreffrath this issue has returned again in the latest autobuilds (tested with crispy-doom-20190607-win32).  It was not present in Crispy Doom 5.5.2.

**Comment by buvk** [comment]
Reported on chocolate tracker.

https://github.com/chocolate-doom/chocolate-doom/issues/1178

**Comment by Noxian16** [comment]
Issue is present in crispy-doom-5.11.1-win32
