### ISSUE TITLE
Dead player beneath the door is able to see level's "out of bounds"

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#257]
It's a vanilla behavior (flaw*), and here's how it looks in DOS version: [screenshot](http://screenshot.ru/upload/images/2018/01/19/vanilla06050.png). Dead player is lying right beneath closed door. Opening and closing automap bringing some shimmering effect. In Crispy it is looking pretty same, except that "out of bounds" colored black for preventing shimmering.

### Technical

My theory: this is happening because of engine does not have additional checking for preventing player's view go beneath the floor. There is no vertical space between ceiling and floor in the sector of closed door, and thus, ceiling "pushes" player slightly beneath floor.

### Possible solution

There are probably two steps to fix this issue.

**1)** We need to add a condition that will prevent prevent player's view go "out of bounds" in the sectors with zero height. I belive this should be done in `p_user.c` @ `P_CalcHeight`, right in the end of whole function (see my [commit](https://github.com/JNechaevsky/russian-doom/commit/247f774a829ab08a341900bc37617dd29dc5ff15) for reference):

```
    if (player->playerstate == PST_DEAD && player->viewz < player->mo->floorz)
    player->viewz = player->mo->floorz;
```

PST_DEAD is a fail-safe condition, i.e. no need to perform this action for live or reborn player.

It will mostly fix this issue, but there will remain one small problem: it is still possible to see one pixel line of door track texture.

Screenshots of [before](http://screenshot.ru/upload/images/2018/01/19/beforef8cd9.png) this step and [after](http://screenshot.ru/upload/images/2018/01/19/afterc0219.png).

**2)** We need to take care about that one pixel line. There are two possible ways: 

- Decrease wall brightness to `0` in the sectors with zero height (I'm currently using it in R_StoreWallRange, but it's deffinitly not smart approach).

- Decrease sector brightness to `0` in the sectors with zero height. This seems to be logical, even in the meaning of the laws of physics, and should be done in `r_bsp.c`, but the problem is - I'm not lucky in implementation of "remembering" initial sector brightness. Without this remembering, if player will open, close, and again open the door, door's sector brightness will be always `0`.

_Suggestion №82_

**Comment by fabiangreffrath** [comment]
Hm, I am not sure I understand this issue entirely. In the code you quoted, `player->viewz` is calculated like this:
```
    player->viewz = player->mo->z + player->viewheight + bob;
```

`player->mo->z` should be the floor level of the sector the player is currently in, `player->viewheight` should have been set to `6*FRACUNIT` in `P_DeathThink()` already and `bob` depends on `player->bob` which in turn depends on the player's momentum in x- und y-direction, whoch should both be zero.

So, `player->viewz` should already by a reasonable value, and this is what we already experience if the dead player does *not* lie beneath a closed door.

Also, I don't think that the player is pushed by the door "through the floor". There is no such code in `PIT_ChangeSector()` and `P_ThingHeightClip()` just doesn't do that.

So, what I believe what actually happens is that the player "gets his head inside the door panel" and sees its inner side rendered. Therefore, I believe moving the `viewz` variable on the *edge* of the floor is the wrong approach, the darkening of the door sector makes much more sense to me. But, is it also dark if rendered from the inside?

**Comment by JNechaevsky** [comment]
Uh, this all seems to be much more harder for me than excepted, no idea what I can suggest next.

Please clarify, you meaning "inside" door panel, right?

**Comment by fabiangreffrath** [comment]
Hm, it seems you are right and I was wrong and what we see is actually the door sector's ceiling flat *from below*. o_O

**Comment by JNechaevsky** [comment]
Yeah. :) I think it can be explained only this way: if player way lying on the floor (i.e. not beneath the floor), he was able to see floor texture, but instead of this texture we can see "out of bounds".

The only question is - why even after my correction it is still possible to see 1px line of door track? There must not be any vertical space between floor and closed door. Maybe it's because of something in the engine not precise enough in the engine, not sure how to explain this more properly.

**Comment by fabiangreffrath** [comment]
I think it doesn't have  to do with the player being "dead". If you type IDCLIP and strafe through the closed door, you will also see that the viewz changes by drastic amounts. It becomes more apparent with the NOMOMENTUM cheat. For more fun, try jumping when beneath the closed door.

> why even after my correction it is still possible to see 1px line of door track

I guess this is because you set viewz exactly on floorheight, so what you are seing is the projection of the "edge" of the flat.

**Comment by JNechaevsky** [comment]
A fun indeed! Just tried your recommendations, yeah, it's something. But at least, jumping beneath closed door making some sense - player goes even lower, which is, probably, meaning that initially he is right beneath the ceiling and not "inside the ceiling" _(I wonder what a person who is not familiar with programming might think while reading this!)_.

> I guess this is because you set viewz exactly on floorheight, so what you are seing is the projection of the "edge" of the flat.

Not sure, that line looks exactly like `DOORTRAK` texture. But we can easily check it be replacing `DOORTRACK` to something different and more notable, like `FIREBLU` ([screenshot](http://screenshot.ru/upload/images/2018/01/23/fireblu4e317.png)). And, after checking with my correction from above, I've got this red-blue line ([screenshot](http://screenshot.ru/upload/images/2018/01/23/fire2e1f47.png)). It's quite wider because of I killed a player with activated noclip cheat, so rocket explosion is unable to throw me back.

Interesting, the height of that line is not 1px of map unit or texture pixel, it's something different.

**Comment by fabiangreffrath** [comment]
So, we are actually seeing a stretched *texture*, not a flat? What happens if you only change one of the DOORTRAK textures to FIREBLU, is the stretched image from the texture in front of you or from the one behind your back?

**Comment by JNechaevsky** [comment]
> So, we are actually seeing a stretched texture, not a flat?

Yes! And the most fun thing with this - both ceiling and floor textrures are seems to be not rendered, that's why everything is black there.

> What happens if you only change one of the DOORTRAK textures to FIREBLU, is the stretched image from the texture in front of you or from the one behind your back?

It is in front of course. Here, I've made a little record to show this visually:

- https://youtu.be/HpAPybzKE4o

What is happening:

1. Player is looking to the `FIREBLUE` texture and this texture is remain on screen after closing door.
2. Second attemp is failed, but according to the "squish" sound, player is still crushed by the door, but since he's not inside the sector with the door, `viewheight` is not changed.
3. Same as №1, but since player is looking to the `DOORTRAK`, this texture is appearing on the screen.

One pixel line may be barely notable, so I'm recommending to watch in full screen. These all was done with my patch from the first post (i.e. only `player->viewz = player->mo->floorz;` stuff).

**Comment by fabiangreffrath** [comment]
> why even after my correction it is still possible to see 1px line of door track

Maybe it's due to the WiggleFix?

https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/r_segs.c#L180

**Comment by JNechaevsky** [comment]
Surprisingly - nope. I have tried to set this condition to:
```
    if (height < 1)
    height = 0;
```
but nothing changes, 1px line is still there. Even increasing result value to `128` does not changing anything. Hovewer, after setting result to `height = -1;` game locks-up if player is dying beneath the door.

**Comment by JNechaevsky** [comment]
:bulb: I'll check Chocolate Doom with my correction, let's see what will happen there. There is no `R_FixWiggle`, maybe it will make some sense.

**Comment by JNechaevsky** [comment]
Done. It seems to be not related to `R_FixWiggle`:

1. Without my correction, after opening/closing automap: [screenshot](http://screenshot.ru/upload/images/2018/01/23/1271c0.png)
2. With my correction, after opening/closing automap. One pixel line is there: [screenshot](http://screenshot.ru/upload/images/2018/01/23/2f449a.png)

**Comment by JNechaevsky** [comment]
Got a plan B _(which is probably stands for bad)_: single-sided linedefs should not be rendered in sectors with zero height. In terms of logic it seems to be okay, but in terms of game engine... Hmm. In code representation it should be something like this:
```
        if (frontsector->floorheight == frontsector->ceilingheight)
        rw_midtexturemid = NULL;
```
But `NULL` is probably not correct approach, need to verify and experiment. Another possible approach was decreasting `walllights` value to zero (in same condition), but I've rejected this idea - it's too silly.

**Comment by JNechaevsky** [comment]
Worked for me: r_segs.c @ `R_StoreWallRange`, in `if (!backsector)` condition:

```
        ds_p->silhouette = SIL_BOTH;
        ds_p->sprtopclip = screenheightarray;
        ds_p->sprbottomclip = negonearray;
        ds_p->bsilheight = INT_MAX;
        ds_p->tsilheight = INT_MIN;

+       // [JN] Don't render midtextures in sectors with zero height
+       if (frontsector->floorheight == frontsector->ceilingheight)
+       midtexture = 0;
    }
    else
    {
        // two sided line
        ds_p->sprtopclip = ds_p->sprbottomclip = NULL;
        ds_p->silhouette = 0;
```

Could you please inspect and make your adjudication?

**Comment by JNechaevsky** [comment]
Going farther. We **must** also take care about two-sided walls, and here's why. Here's a test map where is the door is lowering slightly beneath common floor:

![](http://screenshot.ru/upload/images/2018/01/23/hmmd89b4.png)

And here's what is happening if player will die beneath this door, if we are `NULL`ifiying only single-sided wall: [screenshot](http://screenshot.ru/upload/images/2018/01/23/wrong7b4cf.png). See? Two-sided wall is fully rendered, while single-sided is not rendered at all.

To fix this, we must move the code beneath both if `(!backsector)` and `else` conditions.

r_segs.c @ R_StoreWallRange:

```
        // allocate space for masked texture tables
        if (sidedef->midtexture)
        {
            // masked midtexture
            maskedtexture = true;
            ds_p->maskedtexturecol = maskedtexturecol = lastopening - rw_x;
            lastopening += rw_stopx - rw_x;
        }
    }

+   // [JN] Don't render midtextures in sectors with zero height
+   if (frontsector->floorheight == frontsector->ceilingheight)
+   midtexture = toptexture = bottomtexture = maskedtexture = 0;

    // calculate rw_offset (only needed for textured lines)
    segtextured = midtexture | toptexture | bottomtexture | maskedtexture;
```

...and ta-da, everything is working properly: https://youtu.be/QOlrVedC6-s

I believe it is proper to set this condition right before `segtextured` boolean, i.e. right before any other farther rendering procedures. But your inspection is still needed.

The only place that comes to mind with such an odd doors in a TNT's Mill level (MAP18): [screenshot](http://screenshot.ru/upload/images/2018/01/23/map181252d.png).

Testing map is right here: [odddoor.wad](http://jnechaevsky.users.sourceforge.net/files/odddoor.wad)

**Comment by JNechaevsky** [comment]
And finally, tested this case by two players POV, to make sure that textures are back to normal after raising the door. Everything seems to be fine: https://youtu.be/9x8YHcwxj7A

**Comment by fabiangreffrath** [comment]
This approach looks pretty good to me already!

However, I have two more questions. Sorry, if these sound stupid and obvious, but I currently have no chance to test these ideas myself (playing Doom in office may be considered discouraged).

(1) The four texture variables are already initialized to 0 early in `R_StoreWallRange()`, so it is really necessary to bother with them at all, or could we just jump out of the function if we see the sector is closed?

```
--- a/src/doom/r_segs.c
+++ b/src/doom/r_segs.c
@@ -628,6 +628,11 @@ R_StoreWallRange

     midtexture = toptexture = bottomtexture = maskedtexture = 0;
     ds_p->maskedtexturecol = NULL;
+
+    if (frontsector->floorheight == frontsector->ceilingheight)
+    {
+       return;
+    }

     if (!backsector)
     {

```

(2) I would rather not even consider rendering one-sided lines in closed sectors at all. The earliest chance to omit rendering them would be in `R_AddLine()`. Does this chance make sense?

```
--- a/src/doom/r_bsp.c
+++ b/src/doom/r_bsp.c
@@ -346,7 +346,12 @@ void R_AddLine (seg_t*     line)

     // Single sided line?
     if (!backsector)
+    {
+      if (frontsector->floorheight == frontsector->ceilingheight)
+       return;
+      else
        goto clipsolid;
+    }

     // [AM] Interpolate sector movement before
     //      running clipping tests.  Frontsector
```

**Comment by JNechaevsky** [comment]
Hey, both questions are not stupid! Let's see:

**1.** Your approach is much smarter, since it does not make any additional redefinitions to `0`. I honestly haven't think about using a `return;` because wasn't sure how to properly apply it. The thing I was thinking about is using `goto`, but in this case it is rather funny than usable.

In short words: I can confirm that your approach is working perfect, so let's just use it in `r_segs.c`.

**2.** This idea is possibly more good for performance, but leads to another problem: non-existing line makes a leak to level's "out of bounds", and thus, engine starts to render things (lines, sectors and things) that's are placed behind this missing line. Probably because of they are placed in `backsector`.

Video demonstration: https://youtu.be/VZKIWhEMZu8

So I belive we still need a line itself for proper clipping purposes. Even without a texture, since instead of HOM effect we have a black color which is achieved by V_DrawFilledBox ([here](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_main.c#L1005)).

**Comment by fabiangreffrath** [comment]
> In short words: I can confirm that your approach is working perfect, so let's just use it in r_segs.c.

Cool, thanks! I was afraid of it not getting the clipping right if we omit the rest of the function, but maybe that's nothing to care about in a closed frontsector anyway. Whereas, what happens if you add another inert item into the closing sector?

**Comment by fabiangreffrath** [comment]
> what happens if you add another inert item into the closing sector?

^ In and around the closing sector.

**Comment by JNechaevsky** [comment]
> In and around the closing sector.

Doh, I haven't checked it earlier, so now it's a perfect time. To do this, I will slightly extend our testing map with few additional higher and lower sectors with candles, in and outside closing sector:

![](http://screenshot.ru/upload/images/2018/01/24/dead_pool38272.png)

...and after testing with your addition from `r_segs.c` and my from `p_user.c`, I've got this:

- https://youtu.be/Mk9kWtc1YCE

So, everything that is outside closing sector isn't rendered. Inside, though, only one sector is rendered after closing: the one which is slightly lower. I think we also need to take care about `backsector` stuff. 

First quick suggestion not working, game simply crashes with this:
```
if (frontsector->floorheight == frontsector->ceilingheight
|| backsector->floorheight == backsector->ceilingheight)
```

**Comment by fabiangreffrath** [comment]
So, preventing that the closed sector has not textures messes up segs clipping. *sigh*

Maybe its's not a bad idea to leave this code untouched and actually reduce sector lighting to 0, as you suggested earlierß

**Comment by JNechaevsky** [comment]
Seems to be so. But I was not lucky with remembering initial sector brightness, and as a result sector brightness was remaining 0 after opening - closing - and opening door again.

Maybe we really should go back that way, but before this, I've got another idea.
_Sorry, still haven't tried `diff` utility on Windows!_

We may have a boolean just like `automapactive`, which is [right here](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_segs.c#L566), that will act with following logic:

**r.segs.c**
```
+ boolean beneath_door // [JN] should be global

...

@@ R_StoreWallRange

    // [crispy] (flags & ML_MAPPED) is all we need to know for automap
    if (automapactive && !crispy->automapoverlay)
        return;

+   // [JN] player beneath closed door?
+   if (frontsector->floorheight == frontsector->ceilingheight)
+   beneath_door = true;
+   else
+   beneath_door = false;
```
**r_main.c**
```
@@ R_RenderPlayerView

    extern void V_DrawFilledBox (int x, int y, int w, int h, int c);
    extern boolean automapactive;
+   extern boolean beneath_door;

...

    // Clear buffers.
    R_ClearClipSegs ();
    R_ClearDrawSegs ();
    if (automapactive)
    {
        R_RenderBSPNode (numnodes-1);
        return;
    }
    
+   if (beneath_door == true)
+   {
+       // [JN] fill whole screen with black color and don't go any farther
+       V_DrawFilledBox(viewwindowx, viewwindowy, scaledviewwidth, scaledviewheight, 0);
+       return;
+   }
```

But there are two problems:

1. Despite of solving any possible clipping issues, I'm afraid this approach is too rough.
2. It's not working proper with this draft: after dying beneath closed door and restarting level, whole screen remains black. Screen also becomes black after noclip walking beneath closed door.

**Comment by JNechaevsky** [comment]
Okay, got it working with only **p_user.c** (i.e. without any changes in **r_segs.c**) as: 

```
boolean beneath_door = false; // [JN] initially false

@@ P_CalcHeight
...

    if (player->viewz > player->mo->ceilingz-4*FRACUNIT)
	player->viewz = player->mo->ceilingz-4*FRACUNIT;

+   if (player->playerstate == PST_DEAD && player->viewz < player->mo->floorz)
+   {
+       player->viewz = player->mo->floorz;
+       beneath_door = true;
+   }
+   else
+   {
+       beneath_door = false;
+   }
```

Changes in **r_main.c** same as in my post above.

```
@@ R_RenderPlayerView

    extern void V_DrawFilledBox (int x, int y, int w, int h, int c);
    extern boolean automapactive;
+   extern boolean beneath_door;

...

    // Clear buffers.
    R_ClearClipSegs ();
    R_ClearDrawSegs ();
    if (automapactive)
    {
        R_RenderBSPNode (numnodes-1);
        return;
    }
    
+   if (beneath_door == true)
+   {
+       // [JN] fill whole screen with black color and don't go any farther
+       V_DrawFilledBox(viewwindowx, viewwindowy, scaledviewwidth, scaledviewheight, 0);
+       return;
+   }
```

- Good thing - it is working fine. I can change screen size, open/close help screen and so on, and there will no be any shimmering and etc. Check it out: https://youtu.be/dM8-FWI88WE
- Bad thing - it is not working at all in network game: https://youtu.be/LDzb9kY20Rc. Why the hell...? :grimacing:

Note that removing `player->playerstate == PST_DEAD` does not changing anything in netgame. This definition is still necessary, because if alive player will walk beneath closed door, his gun will not be rendered which is not nice.

**Comment by JNechaevsky** [comment]
> Bad thing - it is not working at all in network game: https://youtu.be/LDzb9kY20Rc. Why the hell...?

Now it's obivious why. Both, i.e. **all** players must be crushed beneath the door to make this condition being executed. Same logics for all players, checkmate. In `-solo-net` it is working fine. Not sure that it is possible to assign this condition to `[consoleplayer]` somehow.

For single player this approach seems to be good, and maybe I'll stick with it, but let's get back to decreasing sector's light approach.

There are a couple of possible places to make a check of zero height. It is possible to do even in **r_bsp.c** @ R_Subsector (see `lightlevel`), with same conditions as above. But there is a one and huge problem: we need to remember initial value of sector brightness. Sadly, I have no idea how to do this, so can't offer anything proper.

If we don't remember initial value, here's what may happen: https://youtu.be/10BnmreCYRU

Another thing that we need to think about - how it should be done safely for performance. 

My theory: we don't need to check all the sectors for brightness value and remember all their brightness values. We need only non-static sectors, that may change it's height. But since engine doesn't have any definition of "this sector is a door", we can lookup only for **tagged** sectors.

Next question is where is checking for changing sector's height should be placed.
I think **r_bsp.c** is not acceptable, since we need a dynamic checking. Probably it's again should be **r_segs.c** with implementation that you have suggested above?

Finally, Killough's implemetation of gradual lighting effects may be handy:
https://github.com/fabiangreffrath/WinMBF/blob/master/Source/p_doors.c#L119

**Comment by fabiangreffrath** [comment]
Welcome to the joys of global variables. ;)

I must admit this issue is slowly getting on my nerves. I have tried to achieve something using `fixedcolormap` yesterday, but the results were not what I expected. There is so little gain for such a high chance of breaking something else, and segs rendernig is not *the* least important part of the Doom engine.

Anyway, thanks for pointing me to MBF's gradual lighting implementation. I had something similar in mind already, but you need to save the original `sector->lightlevel` somewhere - and with that I mean also across savegames. MBF takes the darkest and lightest surrounding sectors of the one tagged with "lighttag" as boundaries for the lightlevels, but that's not something that will be possible to apply to our use case. :/

**Comment by JNechaevsky** [comment]
> but you need to save the original sector->lightlevel somewhere

Yeah, this is exactly I was talking about, and that's a problem №1. If we don't want to put any additional values to savegames, looks likes we have to use approach of dynamic calculation. But again, the more operations we are performing in one tic (especially in renderer), the more CPU usage it will consume, and this is definitely not good. I believe both factors are critical: speed and abusing CPU as less as possible.

As a pre-final idea I'm thinking about messing around with `zlight` which is [right here](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_plane.c#L578), with same conditions as `(floorheight == ceilingheight)`.

**Comment by fabiangreffrath** [comment]
> we don't want to put any additional values to savegames

No, wait, it's *not* necessary to save this. Before a savegame is restored, the entire level is set up from WAD data. That is, we always have a chance to save the original lightlevel value, even if it is later overridden by the savegame data.

**Comment by JNechaevsky** [comment]
Ah, sure, thanks for explanation. There is nothing more I can suggest for today, implementation of local time widget overdriven me.

**Comment by fabiangreffrath** [comment]
Okay, so even forcefully setting the sector's `lightlevel` to `0` doesn't work to remove this artifact, because the player may be so close to the rendered segment, that his "headlight" is sufficient to still have it noticeable. Any further idea?

**Comment by JNechaevsky** [comment]
As a last idea, I can only suggest "turn off the lights" approach, by disabling screen renderer and filling it with black color. I've got it working, but again, it's kinda rough approach and working fine only in single player.

But wait, you are meaning what will happen if player is crushed by the door, but his center (`FRACUNT`?) is placed outside the sector with the door? In this case player is still crushed, but not pushed down below floor. Here's an example [screenshot](http://i6.pixs.ru/storage/3/4/7/crushpng_5460219_29170347.png) (squished face is a good indicator).

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.
