### ISSUE TITLE
Deathmatch: spawn respawn fog in any spawnspot direction

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#258]
There is a bug in vanilla Doom that is emulating in Choco:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/g_game.c#L1340

Because of this bug/emulation, green respawn fog is never spawning in deathmatch spots that's are looking "left" (or using angle 180 in game meanings). These spots are marked red on this [screenshot](http://screenshot.ru/upload/images/2018/01/19/red1bc58.png).

#### Solution

This can be easily fixed by commenting out emation's code. Please use my commit for reference:
https://github.com/JNechaevsky/russian-doom/commit/75f5a6050818797f999a95714a40a88078bbfcfe

You can test it on this map: [dm-test.zip](https://github.com/fabiangreffrath/crispy-doom/files/1646340/dm-test.zip)
Simply run the game as: `./crispy-doom -file dm-test.wad -solo-net -deathmatch -warp 01`

#### Technical

I think it is safe to fix this case. Fog is not solid object that does not affect anything except `INTERCEPTS`. Sadly, I was not able to find any suitable deathmatch demos to check this fix 100% properly.

_Suggestion №83_

**Comment by fabiangreffrath** [comment]
Thank you for the suggestion, but we must be absolutely sure that this change would not affect demo and/or multiplayer sync. 

@fragglet Do you know or remember if this change
https://github.com/chocolate-doom/chocolate-doom/blob/master/src/doom/g_game.c#L1153
was merely a cosmetic fix or if it had any implications for network sync?

It shouldn't, though, because `MT_TFOG` carries the `MF_NOBLOCKMAP` flag, but who ever knows? ;)

**Comment by fragglet** [comment]
I believe it's cosmetic, since the teleport fog things don't interact with anything. But probably you want to make sure you don't overflow the trig tables when doing lookups.

**Comment by fabiangreffrath** [comment]
@fragglet Sounds like a good idea, thank you!

**Comment by fabiangreffrath** [comment]
@JNechaevsky As you might know, I am pretty reluctant when it comes to multiplayer related changes. Might this be considered unfair? I mean, one player gets the fog on the "correct" location, probably blocking his/her view, while the other player (running Choco) doesn't...

**Comment by JNechaevsky** [comment]
Sounds absolutely fair. But then, another thing that harassingly comes to mind is mouse look. Despite of it's locked automaim and strict behavior in netgame, it still can give a little advantage. But I'm definitely not suggesting to disable it completely on netgame - it's too conservative way to go.

Let's just leave this fog "as is".

**Comment by Zodomaniac** [comment]
@JNechaevsky I love the typo 'autoMAIM' XD
I also think the fog thing should be left as is, same as the deliberately preserved silent BFG trick.

**Comment by fabiangreffrath** [comment]
Thanks for your input. So, I am tagging this "wontfix" until we get a better idea...

**Comment by fabiangreffrath** [comment]
I am closing some old issues that I consider irrelevant by now. Feel free to reopen with a comment if you disagree.
