### ISSUE TITLE
With real-tone music WADs e.g. IDMUS03 and IDMUS01 after that doesn't restore the MAP01 music

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#262]
Under Windows, if I start new game in Doom 2 with some music WAD e.g. DoomMetalVol4_44100.wad http://www.moddb.com/groups/doomdb/addons/doom-metal-vol4-resampled-to-441-khz, type IDMUS03 and IDMUS01, the Map 01 music won't be played but music from Map 03 will be restarted.
With MIDI music everything works correctly.

**Comment by fabiangreffrath** [comment]
May I guess, this is resolved by renaming `crispy-midiproc.exe` out of the way?

**Comment by Zodomaniac** [comment]
Yes, moving away this toxic exe really works!

**Comment by Zodomaniac** [comment]
This isn't the case anymore either in the 5.1+daily EXEs build I use or in StasBFG's build I sent you via e-mail.
