### ISSUE TITLE
[Chex] Vanilla bug with episode selection

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#263]
Recently I have suffered this bug in Beta emulation, but Chex is also affected, so I think it will be interesting for you. There is a vanilla bug in game menu, and to reproduce it, just follow these steps:

- Start Chex Quest normally.
- Choose "New Game" and press `ENTER`.
- You will be in the "Choose skill" section.
- Press `BACKSPACE` and you will see "Which Episode?" from Doom.

Screenshot: http://screenshot.ru/upload/images/2018/02/06/chexad669.png

### Technical

This is seems to be because of `key_menu_back` actually leads not to real previously visited menu, but to strictly defined in the code. And since Chex is using `registered` game model, episode selection is still exist as defined in the code.

But I'm sure you know this better than me, so barely you need hear this. :)

### Suggested solution

I have it, but probably it will not be correct enough for Crispy. Here's how I've solved this in Beta:
https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/m_menu.c#L1997

It's fixing issue with episode appearance, but it's too strict - now it's not returning to previous menu, but always to the main menu. In 99% cases this is okay, since menu hierarchy is not too deep, but for example, if I'll go the Options, then to the Volume and press `BACKSPACE` there, I will not return to the Options - instead, I will be in Main Menu.

That's why I'm suggesting my approach only as a reference, Crispy's menu hierarchy in much deeper.

**Edit:** ... and by the way, having a sentence "Knee-Deep in the Dead" in the game which is designed for kids seems to be really not good!

_Suggestion №84_

**Comment by JNechaevsky** [comment]
Oh, one more Chex-related suggestion. Maybe it's also worth to replace some agressive words? There are three strings that I have found in the Crispness menu:

- Colored blood and corpses _(change to Colored ooze and flemoids?)_
- Fix Spectre and Lost Sould blood _(change blood to ooze?)_
- Randomly mirrored corpses _(change to Randomly mirrored flemoids?)_

The rest of the other strings seems to be pretty harmless.

**Comment by fabiangreffrath** [comment]
> Press BACKSPACE and you will see "Which Episode?" from Doom

Thanks for the report! Now if we could only get our hands on the original CHEX.EXE and check if the bug is already present there. If yes, this would be an adequate emulation of the original behaviour inehrited from Choco, which I would fix in Crispy nevertheless. If not, then this would have to get fixed in Choco first and then merged.

> strings that I have found in the Crispness menu

These don't even make sense, because (1) monsters in Chex do not bleed, (2) there are neither Spectres nor Lost Souls and (3) monsters don't leave corpses. So, instead of rewording them to Flemoids, I think I'd rather gray them out if `gameversion == exe_chex`.

**Comment by JNechaevsky** [comment]
> Now if we could only get our hands on the original CHEX.EXE and check if the bug is already present there.

Original DOS executable also have this bug, here's a record under the DosBox: 
- https://youtu.be/GLtPaSI35G8

> These don't even make sense

No no no, I was meaning not a functionality, but the words themselves. I.e. no need to mention such a words like "blood" and "corpse" in a game for children.

**Comment by fabiangreffrath** [comment]
> Original DOS executable also have this bug, here's a record under the DosBox:

So, both Choco and Crispy emulate this properly, but I think I will "fix" this in Crispy anyway.

>  I was meaning not a functionality, but the words themselves

I understand, but I don't think it makes sense to "translate" menu options to child-friendly language, if changing them doesn't have any effect anyway. I will just gray them out to show they are unavailable in Chex.

**Comment by JNechaevsky** [comment]
Doh, figured out a correct fix for `key_menu_back` behavior. Please see for reference: 
https://github.com/JNechaevsky/russian-doom/commit/ce168f7b7299c05fe9ca3969c51eeb87d5bad91d

But since Chex is not a `gamemode`, you probably will need to additional condition into this `switch`. Could it be something like...

```
m_menu.c @@ M_Init
        case registered:
+++         if (gamemission == pack_chex)
+++             NewDef.prevMenu = &MainDef;
        break;
```

**Comment by fabiangreffrath** [comment]
You seem to be missing this commit from Choco, which introduces a `if (gameversion == exe_chex)` check in `M_Init()`:

https://github.com/chocolate-doom/chocolate-doom/commit/44fea0d80e7f7be8783e77303253ed40d492ce29

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
>monsters in Chex do not bleed

They do
![doom0000](https://user-images.githubusercontent.com/15119473/35937335-f7769028-0c56-11e8-8783-f57c75816ab1.png)
![doom0005](https://user-images.githubusercontent.com/15119473/35937336-f7990658-0c56-11e8-90a9-93b3a48368b6.png)

**Comment by fabiangreffrath** [comment]
Hm, indeed they do... at least a bit. ;)

Nevertherless, colorizing their blood sprites does not make any sense, so it was the right decision to gray out the menu entries.
