### ISSUE TITLE
Pixel anomaly on traditional HUD

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#264]
I've got an interesting catch. First of all, it comes from vanilla, but also represented in Choco and Crispy. Steps to reproduce:

- Start Crispy normally (you will need traditional HUD enabled).
- Start new game.
- Take a **very** close look to `arms` widget.
- Open automap and note that few pixels will be changed in widget.

Video demonstration of DOS executable, but it also looks exact same way in Crispy:
- https://youtu.be/kHjdnmSDf18

**Suggestion**

This is seems to because of arms widget is not fully redrawn after opening automap. Probably. At the moment I don't have a more proper suggestion, sorry.

And sorry for showing a thing that _"once seen, it can't be unseen"!_ :/

_Suggestion №85_

**Comment by fabiangreffrath** [comment]
o_O WTF is that?!

**Comment by JNechaevsky** [comment]
I have a same question! Tonight I was experimenting with adding `ST_refreshBackground` and `ST_drawWidgets` into `AM_Start` and `AM_Stop`, but it doesn't helped. Looks likes, erm... something _initially_ wrong in arms widget. Maybe by following logic -- we are starting new game and:

1. Status bar is loaded / appeared (`STBAR`).
2. Next, arms widget is loaded (`STARMS` as background, `STGNUM*` and `STYSNUM*` as a digits).
3. Automap is opened. Everything is updated, except ... background of digits? And this background is catched from `STBAR` picture with FRAGS background, not from `STARMS`.

But this leads to another question: why the hell "glitched" background pixels remain after changing screen size / hiding HUD and opening automap again? Is it because of these pixels are correct appearance? I know there is some kind of screen buffering for pixels for preventing constant redrawing, but is it making any sense?

Alright, bunch of question will not make any sense neither, so I think I need to make a few experiments:

1. Try to make an arms widget' background empty.
2. Try to make digits empty.
3. Try to make a full HUD redraw right after player is spawned. (sounds not smart)

... and see what will happen.

**Comment by JNechaevsky** [comment]
Okay, commenting out this line helped: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/st_stuff.c#L1716

Without `armsbg` numbers doesn't have this anomaly, and probably I'm on right track about thinking of incorrect background of digits. But this also does not make a sense - in the code everything logical: initializing/updating `w_armsbg` first, and `w_arms` second. :japanese_goblin:

**Comment by JNechaevsky** [comment]
Yes, I was right - replacing `ST_diffDraw` to `ST_doRefresh` in https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/st_stuff.c#L1773 solves this anomaly. But as we discussed couple of months ago, this is not correct to redraw whole status bar every game tic.

So all I have to figure out next is - `w_armsbg` is also mus be redrawn on calling `ST_diffDraw`, otherwise digits will use backgound from clean HUD (with FRAGS section) which is leading to this anomaly.

**Comment by fabiangreffrath** [comment]
We should probably only backup the status bar background *after* the starms background has been drawn over it.

**Comment by JNechaevsky** [comment]
Seems to be so. At the moment, I've got a working, but still kinda rough solution. It is possible to update only `w_arms`, but this way right after starting game map this anomaly will blink once on HUD.

![](http://i12.pixs.ru/storage/0/6/7/2351533757_5375346_29286067.jpg)

Replace `refresh` to `true` in two instances: [here](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/st_stuff.c#L1716) and [here](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/st_stuff.c#L1720):

```
    if (screenblocks < CRISPY_HUD || (automapactive && !crispy->automapoverlay))
    {
---    STlib_updateBinIcon(&w_armsbg, refresh);
+++    STlib_updateBinIcon(&w_armsbg, true);
    }
```

```
    for (i=0;i<6;i++)
---	STlib_updateMultIcon(&w_arms[i], refresh || screenblocks >= CRISPY_HUD);
+++	STlib_updateMultIcon(&w_arms[i], true || screenblocks >= CRISPY_HUD);
```

**Comment by fabiangreffrath** [comment]
Does this help?
```
--- a/src/doom/st_stuff.c
+++ b/src/doom/st_stuff.c
@@ -463,6 +463,9 @@ void ST_refreshBackground(void)

        V_DrawPatch(ST_X, 0, sbar);

+       if (!deathmatch)
+           V_DrawPatch(ST_ARMSBGX, 0, armsbg);
+
        if (netgame)
            V_DrawPatch(ST_FX, 0, faceback);

```

**Comment by JNechaevsky** [comment]
Yes, it is! In all cases / screen sizes, just see yourself! 
- https://youtu.be/l8m1mflI43w

_Note: there is a sound issue, since I have installed SDL 2.0.6 and commented out `I_Error` call. I don't know how up forcefully update it to 2.0.7 on Debian. :/_

**Comment by fabiangreffrath** [comment]
Ha, cool!

> I don't know how up forcefully update it to 2.0.7 on Debian. :/

You'll have to change your APT configuration to receive packages from the "testing" suite. There will never be an update of the SDL2 libs in Debian stable (your best guess is the backports suite, though).

**Comment by fabiangreffrath** [comment]
Ahem, have you checked if it works as expected in Deathmatch games as well? I didn't... (but it strictly should!)

**Comment by JNechaevsky** [comment]
Nope, I haven't, will do it now.

**Comment by JNechaevsky** [comment]
Everything seems to be fine. Big red digits doesn't have this anomaly, and there is no any appearance of `armsbg` in Deathmatch mode. In Cooperative mode (simple `-solo-net`) everything is fine too.

p.s. thanks for pointing out, I have completely forgot about `etc/apt/sources.list`!
