### ISSUE TITLE
Keep showing the demo progress bar in intermission stats and text screens

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#265]
IMO it makes sense to not lose track of the demo progress bar between the levels when watching demos, why not let it stay visible upon the intermission stats and text screens?

**Comment by fabiangreffrath** [comment]
Absolutely! I think I will have to move the `HU_DemoProgressBar()` call from `HU_Drawer()` to `D_Display()`.

**Comment by Zodomaniac** [comment]
@fabiangreffrath, do you intend to discuss this further that you didn't make a commit but a patch?

**Comment by fabiangreffrath** [comment]
I tend to post patches when I have an idea, but no time or opportunity to actually test the code. I'll investigate this in more detail later...
