### ISSUE TITLE
Crash when trying to load a non-existent savegame from the command line

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#267]
When trying to load a non-existent savegame (empty slot) from the command line, the executable crashes.
E.g. -loadgame (i) when doomsav(i) file doesn't exist.
I think the program should error out by code
`'Savegame %ssav%d does not exist', game_name, i`
where game_name is substituted based on the loaded IWAD: 'doom' for Doom series, 'chex' for Chex/Chex2, 'hacx' for Hacx.

**Comment by fabiangreffrath** [comment]
Good catch, I wasn't even aware of that! However, this isn't something that should get a fix in Crispy alone. I am sure that properly quitting the game with an error message is applicable to Choco as well. Would you mind raising this issue up there as well, please?

**Comment by Zodomaniac** [comment]
Done :)
https://github.com/chocolate-doom/chocolate-doom/issues/990

**Comment by fabiangreffrath** [comment]
Great, thank you!

**Comment by Zodomaniac** [comment]
It has been fixed, time to merge ;)

**Comment by fabiangreffrath** [comment]
Indeed, thanks for taking this upstream!

**Comment by Zodomaniac** [comment]
@chungy has finalized the fix the way we suggested ;)
