### ISSUE TITLE
-solo-net doesn't work

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#268]
Cannot get a -solo-net game to work by
```
@echo off
start crispy-doom -file comp-dm.wad -solo-net -respawn -altdeath
exit
```
The main menu shows up instead.
[comp-dm.zip](https://github.com/fabiangreffrath/crispy-doom/files/1718710/comp-dm.zip)
Same with Choco.

**Comment by Zodomaniac** [comment]
Fixed by re-typing the command line, maybe there was some unprintable symbol in the way when I copied the string from the manual.

**Comment by fabiangreffrath** [comment]
Alright, thanks! Some problems solve themselves. ;)
