### ISSUE TITLE
Tiny suggestion for "Misc. Sound Fixes"

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#271]
Dig out something rare but interesting. Take a look: https://doomwiki.org/wiki/Sound_cutoffs#DSFLAMST
Maybe it will be a good addition for Crispy's "Misc. Sound Fixes" option?

**Technical**

As described in article, game engine skips any function calls in thing's first frame. I have checked, even `I_Error` call are not being executed, so I think there could be a few possible approaches:

~**1.**~ Replace first `A_Fire` with `A_StartFire`. This will work, but obliviously it's totally unsafe for compatibility:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/info.c#L437

~**2.**~ Add new (second) state with `A_StartFire`, with `0` duration. Totally unacceptable, adding new frames in the middle of array simply breaking all the things that goes after added line.

**3.**  Do something in `A_Fire` function. For example, a counter, because we need to play `sfx_flamst` only once, while `A_Fire` is called many times.

P.S. I believe that fixing initial issue with non-working call in first frame may be not safe at all.

_Suggestion №86_

**Comment by fabiangreffrath** [comment]
Couldn't we just call `S_StartSound(actor,sfx_flamst);` in `A_VileTarget()`, i.e. right after the flame ahs been spawned?

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_enemy.c#L1332

**Comment by fabiangreffrath** [comment]
Alternatively, I am sure we could replace the `A_Fire (fog)` call at the very end of `A_VileTarget()` with `A_StartFire (fog)`, because `A_StartFire()` does nothing more than calling `S_StartSound(actor,sfx_flamst)` and then `A_Fire()` anyway.

**Comment by JNechaevsky** [comment]
Cool! I’ll try it in the evening, thatks for pointing out!

Отправлено с моего телефона на Windows 10

От: Fabian Greffrath<mailto:notifications@github.com>
Отправлено: 20 февраля 2018 г. в 11:30
Кому: fabiangreffrath/crispy-doom<mailto:crispy-doom@noreply.github.com>
Копия: Julia Nechaevskaya<mailto:julia.nechaevskaya@live.com>; Author<mailto:author@noreply.github.com>
Тема: Re: [fabiangreffrath/crispy-doom] Tiny suggestion for "Misc. Sound Fixes" (#271)


Alternatively, I am sure we could replace the A_Fire (fog) call at the very end of A_VileTarget() with A_StartFire (fog), because A_StartFire() does nothing more than calling S_StartSound(actor,sfx_flamst) and then A_Fire() anyway.

**Comment by JNechaevsky** [comment]
I can confirm that both approaches are working. Sound `sfx_flamst` is barely hearable, so I have tested with `sfx_sawhit` first.

The only difference is: 1st is not having sound break, 2nd is have.

Probably second is more acceptable, because it was initially seems to be planned to have sound break, and most important - without sound break `flamst` is *too* notable, which is not good. For my personal taste breakable sound sounds more good. Just take a try by yourself, perfectly good map is MAP16 of Hell on Earth (skill 3 is good enough).

So I would like to vote for approach №2. 

Sorry, nothing I have to suggest here additionally, I'm again completely mentally exhausted... But I'm honestly happy that you have find this case interesting. Please, just take a try this by yourself.

**Comment by fabiangreffrath** [comment]
Well, both approaches are supposed to behave exactly the same, but if you add the `S_StartSound(actor,sfx_flamst)` call to `A_VileTarget()`, the `actor` argument has to get replaced with `fog`, or else the sound will be spawned at the Arch Vile's position, not the flame's - which in turn is why the sound isnÄt interrupted by the flame's later sounds. Sorry, my instructions were misleading!

**Comment by Zodomaniac** [comment]
```
if (crispy->soundfix)
	S_StartSound(fog, sfx_flamst);
A_Fire (fog);
```
Isn't the DSFLAMST interrupted immediately by A_Fire here?
The other option of replacing the A_Fire (fog) call at the very end of A_VileTarget() with A_StartFire (fog) looks more convincing to me, as A_StartFire calls A_Fire not immediately but lets the flame start sound.

**Comment by fabiangreffrath** [comment]
> Isn't the DSFLAMST interrupted immediately by A_Fire here?

No, because `A_Fire()` doesn't play a sound by itself.

In fact, both approaches do the same: They start `S_StartSound()` on the `fog` object and then call `A_Fire()` immediately after. It isn't that a sound in the game is interrupted by merely calling another function in the code. 

What I like more about the taken approach is that it's more clear that what we are giong to fix here is a missing soud being played.
