### ISSUE TITLE
Disable Always Run by default

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#272]
A suggestion for convenience. I think always run being on when starting Crispy for the first time is confusing, also it's not the case in Choco. As I read here https://github.com/chocolate-doom/chocolate-doom/issues/386, Always Run is set by assigning `joyb_speed` a value above `20`. The value `29` used in this Food Doom port family is the default for Crispy, as opposed to Choco default being `2`. IMO there's no reason to deviate from Choco here.
![food doom](https://user-images.githubusercontent.com/15119473/36534597-15623d76-17d8-11e8-9d7e-39b1463bb639.png)

**Comment by fabiangreffrath** [comment]
In general, I agree with you! But this has been enabled by default for such a long time now that I am afraid it will be more confusing if I change the default back. :/

**Comment by Zodomaniac** [comment]
I think many users like me copy the config files from version to version, to avoid configuring all the controls again and again, so I don't think you will confuse many players. But forgetting to copy the default.cfg made me discover that.

**Comment by JNechaevsky** [comment]
Wait. Isn't it a regressive way to go? Always run is not a feature, it's a mechanics of the controls.  For example, mid-res is also non-canonical thing, but that bot the reason to turn it off by default

Отправлено с моего телефона на Windows 10

**Comment by fabiangreffrath** [comment]
> Always run is not a feature, it's a mechanics of the controls

Right, it's a personal preference, and I agree we shouldn't impose these on users.

**Comment by JNechaevsky** [comment]
Ah, sure, disabled "always run" is a traditional behavior. I was alarmed because for me it will be a slightly habit-breaking thing, because for testing purposes I'm always using latest dev build without copying config files.

The Department of Analytics withdraws its objections.
