### ISSUE TITLE
Suggestion: New Crispness option for toning down the duration/intensity of palette flashes

### ISSUE THREAD

**Issue by mfrancis95** [fabiangreffrath/crispy-doom#275]
This would be for the yellow flash that occurs when picking up items and the red damage flashes. This could possibly be extended to the palette changes caused by powerups. Let me know what you guys think.

**Comment by fabiangreffrath** [comment]
Why should we add this, what advantage would that bring? 

Also, there are already way too many items in the Cripsness menus and I am very reluctant to add another one for a rather random change.

**Comment by JNechaevsky** [comment]
**Fabian**, I still would like to suggest my idea of fixing missing first pickup palette, because frankly, having initially second pickup palette, especially on huge monitors, feels like "flash-bang" effect _(trust my eyes, they are my primary vital organ in the project!)_. Yeah, it's a vanilla behavior, but... Nowadays hardware is different and it should be accounted. But it's for your discretion only.

**Comment by mfrancis95** [comment]
It's just to help the player see better, especially in intense situations. In my experience, when taking a large amount of damage, having the screen filled with bright red is disorienting. I've lost several times due to not being able to navigate properly when this happens. The same is true for when you pick up a bunch of items and the yellow flash seemingly stacks up for a bit. I agree that this "flash-bang" effect is a nuisance.

**Comment by fabiangreffrath** [comment]
I think it is less a matter of modern hardware than of how the game actually *feels*.

Haven't we been through this discussion in #202 already? I mean, currently, upon item pickup, the games switches to the second yellow palette and then back to normal. This is what Vanilla does.

Switching to the first "missing" yellow palette and back makes the pickup feel much too weak. Switching to the second yellow palette and then to the first one and then back to normal makes the pickup feel much too long. I think we agreed that both changes felt plain wrong?

**Comment by JNechaevsky** [comment]
I somehow forgot about that discussion (it was a 10 moths ago). Later, however, I used this idea for myself and frankly, I’m happy with it - maybe because of I’m using modified PLAYPAL with more succulent colors.

**Comment by fabiangreffrath** [comment]
Ah, I am sure it has to do with using a different palette.

**Comment by fabiangreffrath** [comment]
I don't think I am going to add a menu option for this.
