### ISSUE TITLE
Crash when pressing switch

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#276]
### Background

Version of Crispy Doom: crispy-doom-20180324-win32

Operating System and version: Windows 10 v1709

Game: Doom & Doom 2

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: When pressing a switch, Crispy Doom crashes

Expected behavior: Crispy Doom should not crash

**Comment by fabiangreffrath** [comment]
He?! Can any of you Windows Doomers confirm this?

**Comment by JNechaevsky** [comment]
For me, `crispy-doom-20180324-win32.zip` working fine with switches (lifts, exits, ...), just checked MAP15 on both Windows 7 (x64) and Windows 10 LTSB (1607, x86). I'll check 1709, but maybe @buvk will be so kind to provide us some more additional information of which exactly switch is crashing the game?

**Comment by buvk** [comment]
I think I may have figured out what is causing this.

If you set crispy_soundfix to 0 in crispy-doom.cfg, then launch the game, pressing a switch will crash the game.

![crash](https://user-images.githubusercontent.com/2666951/37866267-b289ac2c-2f45-11e8-99b8-8f50ef1249c4.png)

**Comment by JNechaevsky** [comment]
Thanks! I can confirm, same happening at me with disabled "Misc. sound fixes".
