### ISSUE TITLE
[Request] Original 320x200 internal resolution

### ISSUE THREAD

**Issue by vanfanel** [fabiangreffrath/crispy-doom#279]
Hi there,

Now that CrispyDoom runs on SDL2, there's need for it to support the original 320x200 resolution for platforms like the Raspberry Pi, where CPU is NOT enough to push 640x pixels at 60FPS.
The idea is that the game runs internally at 320x200 and SDL2 scales that to fullscreen physical resolution (theres no "windows", no Xorg server: SDL2 runs fullscreen on the Rasperry), thus freeing the CPU from doing any scaling: SDL2 on the Pi runs on a GLES/GLES2 renderer that scales with no CPU cost (thats how Scummvm or Zdoom work on the Pi, with very reasonable CPU usage).

I know the original Chocolate Doom provides the original 320x200, but it's tied to the old 35 FPS limit that looks terrible on modern ~60Hz displays, while Crispy can do uncapped framerate!

I know 320x200 original mode is available with Graphics Detail : Low, but some internal software scaling is still done, isn't it? 

EDIT: looking at src/i_video.c, it seems so. A direct, original 320x200 8bpp to SDL2 should definitively be possible, thus letting SDL2 do all the scaling in hardware.

**Comment by fabiangreffrath** [comment]
In "low resolution" mode the game scene is rendered in 320x200 resolution, but is scaled up to 640x400 in the drawing functions. What you probably want is a rebuilt binary with `#define hires 0` which should work properly at least in the then "high resolution" mode.

After all, fixing this once and for all would mean to follow the approach outlined in https://github.com/fabiangreffrath/crispy-doom/issues/274#issuecomment-372108179 , but this is far from trivial to implement!

**Comment by vanfanel** [comment]
@fabiangreffrath : Just did a rebuild with #define hires 0, but the game is still taking ALL the CPU for scaling.

**Comment by Zodomaniac** [comment]
@vanfanel I guess Doom on Raspberry Pi looks like this:
![raspberry_doom](https://user-images.githubusercontent.com/15119473/38127791-5c659062-3400-11e8-9ce1-028a86db2870.jpg)

**Comment by vanfanel** [comment]
@Zodomaniac : Other Doom ports like GZDoom and PRBoom run at perfect 60FPS synchronized with vsync. So the Pi is not the problem here ;)

**Comment by fabiangreffrath** [comment]
Crispy should perform at least as well as GZDoom on your hardware. Is it possible you changed something in the video settings? How does Choco perform, could you try copying its config files over to your Crispy installation?

**Comment by vanfanel** [comment]
@fabiangreffrath : Tried Chocolate and it performs much better than Crispy with #define hires 0.
Still, it's taking A LOT of CPU because it's also scaling the original game's 320x200 frame to 640x.
When did all this start to happen?

**Comment by fabiangreffrath** [comment]
In Crispy you can turn off the intermediate up-scaling by disabling the "Smooth Scaling" option in the Crispness menu. But still, all this scaling should be done by your graphics hardware and not stress your CPU.

**Comment by vanfanel** [comment]
@fabiangreffrath : Even disabling "Smooth Scaling" , the game is NOT sending 320x200 frames to SDL2. It's pre-scaling them to a 640x buffer. CPU usage is very high (~80%) on a Raspberry Pi 3, even with no OPL emulation active.
It's a pitty, CrispyDoom would be great to run on this platform but it just crawls because of the intermediate SOFTWARE scaling it does.

**Comment by fabiangreffrath** [comment]
>  It's pre-scaling them to a 640x buffer

You seem to be pretty focused on this. Where do you know that it is passing a pre-scaled 640x buffer to the SDL code? Where in the code do you find that it does some pre-scaling in software?

Everything from the bare framebuffer to the rendered screen should be done by the graphics hardware, so I don't understand at all why it does this in software on your system...

**Comment by fabiangreffrath** [comment]
May I assume that the same findings from this bug apply to this issue here?
https://github.com/chocolate-doom/chocolate-doom/issues/1009#issuecomment-377695511

**Comment by vanfanel** [comment]
@fabiangreffrath : Yes and no. There was some config problem I was having with Crispy. 
But you were right: with my `#define hires 0` build and a fresh ~/.local/share/chocolate-doom, Crispy stopped scaling internally. Good!

**Comment by fabiangreffrath** [comment]
Thanks!

> #define hires 0

I am currently struggling to turn this into a run-time variable.
