### ISSUE TITLE
It's impossible to access E1M10: Sewers with -warp 10 command

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#281]
### Background

Version of Crispy Doom: Git 31.03.2018

Operating System and version: Windows 7

Game: XBox DOOM.WAD

Any loaded WADs and mods (please include full command line): crispy-doom -iwad doom.wad -warp 10

### Bug description

Observed behavior: Game is started in E1M1: Hangar.

Expected behavior: Game should be started in E1M10: Sewers. Surprisingly, IDCLEV10 does take me to Sewers, but -warp 10 in the command line starts the game in E1M1: Hangar.

**Comment by fabiangreffrath** [comment]
`-warp 10` would mean to warp to episode 1 map 0, which is then "rounded up" to map 1. If you want to warp to map 10 directly, try passing a map number that is "higher" than 9, e.g. "`warp 1a`.

**Comment by Zodomaniac** [comment]
Thanks, `warp 1a` works.
