### ISSUE TITLE
When recording a demo in XBox Doom, triggering the exit from E1M1 to E1M10 takes me to E1M9, and completing E1M10 (warped to) when recording a demo causes a crash

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#282]
Background
Version of Crispy Doom: Git 31.03.2018

Operating System and version: Windows 7

Game: XBox Doom

Any loaded WADs and mods (please include full command line):

Bug description
Observed behavior: Triggering the exit from E1M1 to E1M10 takes me to E1M9, and completing E1M10 (warped to) when recording a demo causes a crash.

Expected behavior: I expected to be taken to E1M10 from the secret exit of E1M1, and be taken to E1M2 on completion of E1M10 like without demo recording.

**Comment by Zodomaniac** [comment]
Still no transitions from E1M10 and MAP33 to other maps when recording demos, why?)
The game just exits, and the intermission screen after E1M10 looks like this
![doom0006](https://user-images.githubusercontent.com/15119473/38189532-617e81ce-3669-11e8-9be0-f2c11bb6597a.png)

**Comment by fabiangreffrath** [comment]
Demo recording mode means strictestest Vanilla compatibility and there simply isn't a valid level transmission from one of these maps in Vanilla. Also, the spot on the intermission screen is the one from E2M1 :)
