### ISSUE TITLE
Video refresh hiccups in uncapped and vsync modes

### ISSUE THREAD

**Issue by vanfanel** [fabiangreffrath/crispy-doom#283]
Hi there,

The uncapped framerate option is awesome. In fact, that's the reason I use crispy-doom: no more 35FPS-on-60HZ uglyness, but "as may frames as physical refresh HZ" instead. Great!

However, there's an small but annoying problem left: there's an occasional hiccup on video refresh in "uncapped" and "vsync" rendering framerates.
It's present in X86_64 and Raspberry Pi, with the latest sources built against different versions of SDL2 on GNU/Linux (Ubuntu, Lubuntu, Raspbian), and -nosound makes no difference. CPU usage with internal scaling disabled is very low (~20% on the Pi, ~5% on X86_64). No services using CPU, with and without Xorg server (I run SDL2 games on KMSDRM but I tested on X11 too).
I was careful to test on different systems, as you can see, and my conclusion is that the movement code must have some error, maybe it's still waiting internally on something (should be blocking on VSYNC only: SDL_RenderPresent is synchronous and waits for vsync if the renderer was created with SDL_RENDERER_PRESENTVSYNC). 

It's easy to replicate: just load a level and keep rotating: you'll eventually see a "previous frame" being presented again. It happens periodically, but not with a continuous period. 

My guess on this is a variable wrapping around of something similar, but I don't know the movement/interpolation code internally, so it's only a guess.

**Comment by Zodomaniac** [comment]
@fabiangreffrath, this time must be the lowest common miltiple of tho oscillations' periods, for 1/35 sec and 1/60 sec it is 1/5=0.2 sec (7 frames of 35 Hz and 12 frames of 60 Hz).

**Comment by fabiangreffrath** [comment]
Oh, right, that would be pretty often...

**Comment by vanfanel** [comment]
@fabiangreffrath : I have mentally measured the period and it's ~12 seconds. Pretty much always the same if one pays enough attention (keep eyes open, no blinking, rotating movement on the game).

**Comment by fabiangreffrath** [comment]
Impressive, thanks! Now, what happens each ~450 tics...?

**Comment by vanfanel** [comment]
@fabiangreffrath : Yes, it happens in both uncapped and vsync modes.
Why not simplifly things and make it depend on physical refresh only?

**Comment by fabiangreffrath** [comment]
Uncapped without vsync might be useful as a benchmark I guess.

**Comment by vanfanel** [comment]
@fabiangreffrath : I mean that "uncapped + vsync" should wait for vsync only. In other words, it should let SDL2 wait for vsync, instead of making any internal timming calculations.

**Comment by fabiangreffrath** [comment]
This is how it currently is! "uncapped+vsync" means the refresh is synchronized with the screen without any internal second-guessing.

**Comment by vanfanel** [comment]
@fabiangreffrath : Then something else is causing these hiccups... What could it be? Angle value wrapping around maybe?

**Comment by fabiangreffrath** [comment]
If that'd be an issue we would also see it in 35FPS mode.

**Comment by vanfanel** [comment]
WRT the initial issue: what about a ~30FPS mode, derived from uncapped framerate? Something like: only refresh every 2 vsyncs, whatever the vsync period is-

**Comment by fabiangreffrath** [comment]
No, thanks! Been there, done that: https://github.com/fabiangreffrath/crispy-doom/commit/c55af8b74468d597aef1aa1ca575b4a45280da1e

The game should render when the screen is ready. I see no benefit in artificially decelerating the refresh rate, especially not below the original tic rate, for the sake of a smooth gaming experience.

**Comment by fabiangreffrath** [comment]
Regarding the in-game access to the WAD data, it appears that all flats, textures and sprites are already loaded before the level starts:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_data.c#L1302

Could you probably find out exactly which data is loaded when you experience the rendering hick-ups? I suspect sound data... Do you have sound pitch variation enabled?

**Comment by fabiangreffrath** [comment]
PS: And does it help if you start the game with lots more memory allocated for the zone, e.g. `-mb 512`?

**Comment by vanfanel** [comment]
@fabiangreffrath : No, it does not help at all. I thought I had answered, sorry it took so much!! :/

**Comment by fabiangreffrath** [comment]
Guys, could anyone of you please check if the attached patch fixes this issue? If moves the calculation of `fractionaltic` right after the rendering of the previous frame. 

[crispy-fractionaltic.zip](https://github.com/fabiangreffrath/crispy-doom/files/2238012/crispy-fractionaltic.zip)

**Comment by bradharding** [comment]
@fabiangreffrath, I can't speak for how it affects Crispy, but since DR has the same/similar issue, using this patch does seem to help considerably. Good work! :grin:

**Comment by JNechaevsky** [comment]
Yesterday was a little bit late, so I was very short in my description. Better I explain it more widely. It's a weekend, and it's a traditional tipsy time :)

First of all, I was never having neither hiccups nor a FPS drops in Crispy, Doom Retro or RusDoom. But! While in fully uncapped mode (60+ fps) I was having something like a... Barely notable delay with mouse rotation command + camera rotation. Frankly, I was absolutely sure, that this is how actually vsync working (Fabian remember for sure my missing of knowledge about it), but after applying this patch I have noted that delay is gone. Now, turning controls, as well as probably others actions, are should work **with out** any delay, making game controls ultimately perfect.

That's it. Perfect place to check is right on MAP01 of Hell on Earth - just try to quickly move your mouse between two zombie man guys: left - then right - then left - and so on, with and with out patch. It's very notable in **close** looking into monitor.

Cheers, love :p :cocktail: :cocktail::cocktail:
