### ISSUE TITLE
Visual option for Doomguy's status face expression during invulnerability

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#284]
I thought that some players might like the emotional Doomguy's face despite the eyes going back from yellow glow to normal. Maybe introduce a switch in Visual options named, e.g., Invulnerability facial expression: godlike serenity/human emotions.

**Comment by fabiangreffrath** [comment]
Hm, another menu item for toggling a mini change?

**Comment by fabiangreffrath** [comment]
I don't think I am going to add a menu option for this.
