### ISSUE TITLE
Add semi_integer_scaling variable to enable semi-integer scaling in fullscreen, like for windowed mode

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#285]
For window sizes, the 960x600 and 1600x1000 resolutions (1.5x and 2.5x) are supported in Crispy.
Why not extend this to fullscreen? It will also wipe out Crispy's inferiority against Choco that in integer scaling you can only get e.g. 1280x800 on a 1920x1080 monitor which has a huge letterbox.
So I'd like to suggest a new, separate variable, enabling screen scaling by semi-integer factors.
To prevent a conflict of `integer_scaling` and this var when both of them are `1`, it would be reasonable to scale by the greater factor of these two which still yields game screen size fitting into the full one.
The variable can be placed at the end of `crispy-doom.cfg` among other Crispy-specific vars as `crispy_semi_integer_scaling`.
Introduction of this var would also serve as a temporary solution until Choco team introduces the aspect ratio correction factor.

**Comment by Zodomaniac** [comment]
>What if you explicitly set the `fullscreen_width` and `fullscreen_height` variables in the config file to the intermediate values, enable `fullscreen` and disable `aspect_ratio_correction` and `integer_scaling`?

The `fullscreen_width` and `fullscreen_height` variables are just ignored, and the game is stretched to full screen. I described this here https://github.com/chocolate-doom/chocolate-doom/issues/1010

**Comment by fabiangreffrath** [comment]
This should be fixed on the SDL-side, not by the port's code.

**Comment by Zodomaniac** [comment]
What a surprise! In StasBFG's Crispy build http://doomgod.com/ports/crdoom5.7z, i.e. with SDL_DLLs compiled in Visual Studio the fullscreen_width and fullscreen_height variables work, the screen size is 1728x1080 letterboxed on the sides!

**Comment by fabiangreffrath** [comment]
This is getting more and more mysterious! What versions of SDL is ths guy using?!

**Comment by Zodomaniac** [comment]
VERSION cheat in his build says it's 2.0.5.
I asked him to try the fresh code.

**Comment by Zodomaniac** [comment]
Seems I got it...it just may be Crispy 5.1 release code, because the screen size is 1728x1080 letterboxed even without the variables.
