### ISSUE TITLE
Crispy Heretic icon concept

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#286]
Even though Crispy Heretic is unofficial and has few differences from Chocolate one (the most noticeable ones being Tutti Frutti glitch and slime trails fixes), it upsets me that its icon is from Doom. @JNechaevsky , if you feel inspired, could you make an icon based on one of these concepts? I prefer the first one btw.
![crispy heretic_2_650x650](https://user-images.githubusercontent.com/15119473/38418276-67a81a2c-39a4-11e8-96d7-0bf5a9b96c9f.png)
![crispy heretic_650x650](https://user-images.githubusercontent.com/15119473/38417858-a3252916-39a2-11e8-8239-146be8438c74.png)

**Comment by JNechaevsky** [comment]
Looks likes I've done it already here: https://github.com/fabiangreffrath/crispy-doom/issues/240#issuecomment-348807598

**Comment by Zodomaniac** [comment]
@JNechaevsky , awesome! No, @fabiangreffrath , it's your turn to build Crispy Heretic with it :)

**Comment by Zodomaniac** [comment]
@JNechaevsky , awesome! Now, @fabiangreffrath , it's your turn to build Crispy Heretic with it :)

**Comment by fabiangreffrath** [comment]
> it's your turn to build Crispy Heretic with it

which is *not* trivial, since it requires to introduce per-exe icons, which in turn is a change that I'd rather like to see in upstream first...
