### ISSUE TITLE
(optional) increase number of sound channels?

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#288]
What if it was possible to increase the number of sound channels (currently 8) to either 16 or 32 (but not more)? This affects the number of sounds that can be played simultanously without one new sound cutting off another one.

**Comment by JNechaevsky** [comment]
Was suggested as #35 (check out our tabelle) and marked as "will probably not come" back then.
But I think it's a neat feature, so I'm totally okay with it.
