### ISSUE TITLE
Apply green blood to Mancubus if Strain_Jive.wad is loaded

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#289]
In PWAD STRAIN http://doom.wikia.com/wiki/STRAIN 
[strainfix.zip](https://github.com/fabiangreffrath/crispy-doom/files/1899799/strainfix.zip)
the Mancubus is DeHackEd-modified into a Demon Lord, a white Baron of Hell that fires 5 fireballs at a time in a spread pattern and shows the Hell Nobles' typical green entrails upon death but bleeds red as he is a modded Mancubus:
![doom0020](https://user-images.githubusercontent.com/15119473/38632398-4800c0a0-3dc5-11e8-9c2e-fc8072fb28af.png)
![doom0027](https://user-images.githubusercontent.com/15119473/38657937-8354a534-3e2b-11e8-8155-7da16d2efe5f.png)
That monster modification is contained in Strain_Jive.wad loaded with 
`start crispy-doom -merge strainfix.wad strain_jive.wad `
Please make that Demon Lord bleed green when colored blood is enabled, as colored blood makes sense in STRAIN where Cacodemons and all Hell Nobles are present. I hope it's possible to enforce the condition of the WAD with a certain name having been loaded on the colored blood behavior.

**Comment by fabiangreffrath** [comment]
Consequently, this would mean that I would have to add explicit support all the PWADs that add or replace one or more sprites for which a different blood color appears more suitable. I hope you understand that this is not an approach that I would like to follow. 

There is a distinction between the Doom IWADs and the HACX IWAD in the code determining blood color, but that's really it. If you find that the blood coloring doesn't fit the PWAD you are playing with, there is still the switch to turn it off entirely.

**Comment by Zodomaniac** [comment]
>this would mean that I would have to add explicit support all the PWADs that add or replace one or more sprites for which a different blood color appears more suitable. 

No, you wouldn't have to. STRAIN is the only exception.

**Comment by fabiangreffrath** [comment]
Do you have an idea how many PWADs are out there which modify a monster sprite in one way or another? Why should I make an exception for Strain but not for all the others?

**Comment by Zodomaniac** [comment]
I don't think there are any more PWADs with vanilla Doom monsters modified from vanilla Doom monsters with different blood color.

**Comment by fabiangreffrath** [comment]
These directly come to mind:
https://doomwiki.org/wiki/Deus_Vult_II
http://doom.wikia.com/wiki/Scythe_2

**Comment by fabiangreffrath** [comment]
The problem is that I will have to carry a global variable from the WAD loading to the sprite rendering code to check if the mancubus sprite is loaded from a PWAD called STRAIN.WAD and check this variable each tic for each rendered blood sprite. And once I introduce this exception, I will open the door for adding explicit support for each and every PWAD modification that people can imagine. :/

**Comment by Zodomaniac** [comment]
I also think no one will bother you about coloring blood in any other WADs.

**Comment by fabiangreffrath** [comment]
> Do you mean this will impact performance?

The performace impact will be negligible. It's that fact that this is an ugly hack that needs to get plunged through the wole code base that I don't like. 

If you have a look at the code, you will see that I would have to treat STRAIN just like another gamemission - which it just isn't:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_things.c#L747

> I also think no one will bother you about coloring blood in any other WADs.

That's the very point: I don't want to open the can of worms and add support for specific PWADs. There are billions of them and they all contain more or less random added or modified content.

**Comment by fabiangreffrath** [comment]
I don't think I am going to add specific support for any non-ID PWADs.

**Comment by Zodomaniac** [comment]
I found a guy at DW who fixed the Demon Lord's corpse and uploaded the result
![REDLORD](https://user-images.githubusercontent.com/15119473/55673107-e79d2c00-58ab-11e9-8504-208c507222ba.png)
https://www.moddb.com/mods/strain/addons/demon-lord-with-red-blood-on-the-fallingdead-body
