### ISSUE TITLE
Romero head should not be randomly flipped after death

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#291]
As was discussed. To get rid of `if`/`else if`/`else something` conditions, I think, obivious choise will be using a flags in info.c. Something like `MF_NOFLIP`. I belive it is safe, since we are using `MF_TRANSLUCENT` for transparent objects and this in not breaking anything.

Another possibe approach is using internal flags (just like Keeloigh did for Torque). But at the moment I can't image how it should work, and is it a proper way at all.

_Suggestion №88_

**Comment by fabiangreffrath** [comment]
Strictly speaking I could use two flags, one for "this sprite may be flipped" and one for "this sprite is flipped".

**Comment by fabiangreffrath** [comment]
On the other hand, maybe I can get away with only one flag which means "this sprite may be flipped" before the thing's death and "flip this sprite" after. Upon a thing's death, the flag would be randomly removed or preserved and then checked with MF_CORPSE during rendering.

But what do I do with things are are already spawned "dead", i.e. blood, bullet puffs or corpse decorations?

**Comment by JNechaevsky** [comment]
> But what do I do with things are are already spawned "dead"

I was thinking about it couple of time ago, it's not a simple question. Imagine we have a mod, where some bloody decorations (not monster corpses) are replaced with some decorations that's are not supposed to be flipped. Signs or arrows, for example. And it's not easy to "catch" this replacements by checking for multiple lumps, since new sprites are always _merged_, not simply _loaded_. You are probably saw already how much pain I was having with making animated candles safe for demos and loaded PWADs.

Monster copses, hovewer, seems to be fine, since even a "dead monster" map things are using monster's graphics.

Thus, my recommendation is to go safe way: flip only monster corpses (even those ones that's are initially decorations), but not bloody decorations.
