### ISSUE TITLE
Change pages in Crispness menus with PgUp/Down keys

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#296]
Not critically necessary feature, but have some good logics and may be handy for navigation.
Presumably, real keys `PGUP` and `PGDOWN` should be used, i.e. not internal bindings like `lookup` and `lookdown`.

Also, `HOME` and `END` buttons may move cursor to the top and bottom of the page.

_Suggestion №89_

**Comment by fabiangreffrath** [comment]
This has been asked before on the forums, I think. Shouldn't be too tricky to implement.
