### ISSUE TITLE
Implement additional gamma-correction levels

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#297]
Looks likes we have totally forgot about this idea, and I haven't properly suggested it earlier.

Here's an additional tables that I wrote couple of months ago:
https://github.com/JNechaevsky/russian-doom/blob/master/src/tables.c#L2133

It was rather than simple, imagine that one gamma table is having just four values. For example:

Gamma-correction off:
`{1, 2, 3, 4}`

Gamma-correction level 1:
`{1, 4, 5, 6}`

So, to make an intermediate level 0.5, values will be:
`{1, 3, 4, 5}`

I haven't changed original levels `off`, `1`, `2`, `3` and `4`, only made a new intermediate ones. Making values higher than `4` is totally unsafe, it can break color indexes and as a result - some colors on the whole screen will be wrong.

There are two possible problems though:

1. I have no idea how it will work with true color rendering and/or hardware gamma.
2. It can be unsafe for `DEHACKED` strings. Not sure that there are any mods exist that's replacing gamma-correction messages, but... To don't add any additional strings, you still can use, for example, "Gamma-correction level 1" for levels `1`, `1.25`, `1.50` and `1.75`. But frankly, my recommendation is to make gamma changing messages independent from Dehacked. Or maybe you will have a better idea.

_Suggestion №90_

**Comment by fabiangreffrath** [comment]
Are you suggesting to add 4 intermediate levels per original level, so a total of 17 (?!) gamma levels?

> Here's an additional tables that I wrote couple of months ago:

The additional tables could just as well get calculated at run-time, right?

> I have no idea how it will work with true color rendering and/or hardware gamma.

Gamma correction looks like crap with true-color rendering anyway, but should pose no further problems.

> It can be unsafe for DEHACKED strings

Hm, not sure it's worth the trouble even thinking about it. ;)

**Comment by JNechaevsky** [comment]
> Are you suggesting to add 4 intermediate levels per original level, so a total of 17 (?!) gamma levels?

Yeah, exactly. 17 levels in total ([link](https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/m_menu.c#L106)), or it can be shortened to `1.5`, `2.5` and so on on, if using `1.25`/`1.75` is too much for your taste.

> The additional tables could just as well get calculated at run-time, right?

Well, probably. But what's wrong with using LUT? Real-time calculation can give a little bit more correct results, but the LUT itself is half-o-cent better for performance.

> Gamma correction looks like crap with true-color rendering

That's my favorite part about improving palette. :) Honestly, `PLAYPAL` colors looking awfully bright on modern monitors. I've solved this by making a custom `PLAYPAL`, but for Crispy something else should be done, in the code obviously. But I don't have any ideas what exactly.

**Comment by JNechaevsky** [comment]
I think I've got a very raw idea about technical (i.e. design) `PLAYPAL` improvement... But first I need to understand the very basis: what actually single color in palette is. How it's values are formed and stored. And how they can be manipulated. Probably it will be an interesting topic for discussion, but excuse me, not here and not now - let's don't start off-topic. I will explain my thoughts approximately in the evening.

**Comment by fabiangreffrath** [comment]
> Honestly, PLAYPAL colors looking awfully bright on modern monitors

Yep, that's somehow the point I wanted to make. I never play with any gamma level, because the game is already bright enough, so why would I want to add even more levels? (Sure, that's somehow a trick question, but I know you understand me).

**Comment by JNechaevsky** [comment]
Sure I understand, and that's a totally good question. And since it is a visual-related, I will answer it slightly wider than exceeded, sorry for another philosophical poem.

Initially I was going to suggest it just for some flexibility. For my eyes, gamma-levels with vanilla `PLAYPAL` are looking like:

- OFF: oh, well.
- 1: Oh, no.
- 2: Oh, no!
- 3: Oh, no!!
- 4: OH, NO!!!

And since we have started to talk about palette improvement (please don't forget to read my e-mail), this flexibility will be really necessary. Surely you have seen my improved palette, but there is not everything that simple with it. Yeah, it's looking good, but my window is looking to the east, and when the morning sun is shining to the window, I simply can't see anything with gamma-levels below 3.

In day and evening time everything is okay, but yet still I want to have, or better say - to _give_ some flexibility for everyone. Some people may like one level, some people may like another, it's question of personal taste.

The reason why I'm not implemented `0.10`, `0.20` and so on levels - there will be too much levels, more than _really_ needed, and will make scrolling uncomfortable.

So yeah, speaking about improved palette, this flexibility will be a good, proper thing for everyone who will wish to have _almost_ perfectly brightened pixels.

**Comment by fabiangreffrath** [comment]
This should be it:
```
diff --git a/src/doom/d_englsh.h b/src/doom/d_englsh.h
index 6ec507d1..35534dc3 100644
--- a/src/doom/d_englsh.h
+++ b/src/doom/d_englsh.h
@@ -69,6 +69,11 @@
 #define GAMMALVL2	"Gamma correction level 2"
 #define GAMMALVL3	"Gamma correction level 3"
 #define GAMMALVL4	"Gamma correction level 4"
+// [crispy] intermediate gamma levels
+#define GAMMALVL05	"Gamma correction level 0.5"
+#define GAMMALVL15	"Gamma correction level 1.5"
+#define GAMMALVL25	"Gamma correction level 2.5"
+#define GAMMALVL35	"Gamma correction level 3.5"
 #define EMPTYSTRING	"empty slot"
 
 //
diff --git a/src/doom/m_menu.c b/src/doom/m_menu.c
index 1a2adeb0..85a16264 100644
--- a/src/doom/m_menu.c
+++ b/src/doom/m_menu.c
@@ -104,12 +104,17 @@ boolean			messageNeedsInput;
 
 void    (*messageRoutine)(int response);
 
-char gammamsg[5][26] =
+// [crispy] intermediate gamma levels
+char gammamsg[5+4][26+2] =
 {
     GAMMALVL0,
+    GAMMALVL05,
     GAMMALVL1,
+    GAMMALVL15,
     GAMMALVL2,
+    GAMMALVL25,
     GAMMALVL3,
+    GAMMALVL35,
     GAMMALVL4
 };
 
@@ -2563,7 +2568,7 @@ boolean M_Responder (event_t* ev)
         else if (key == key_menu_gamma)    // gamma toggle
         {
 	    usegamma++;
-	    if (usegamma > 4)
+	    if (usegamma > 4+4) // [crispy] intermediate gamma levels
 		usegamma = 0;
 	    players[consoleplayer].message = DEH_String(gammamsg[usegamma]);
             I_SetPalette (W_CacheLumpName (DEH_String("PLAYPAL"),PU_CACHE));
diff --git a/src/doom/r_data.c b/src/doom/r_data.c
index a2d93b4d..8e76c273 100644
--- a/src/doom/r_data.c
+++ b/src/doom/r_data.c
@@ -1117,6 +1117,33 @@ void R_InitColormaps (void)
     lump = W_GetNumForName(DEH_String("COLORMAP"));
     colormaps = W_CacheLumpNum(lump, PU_STATIC);
 
+    // [crispy] intermediate gamma levels
+    if (!gamma2table)
+    {
+	int i;
+
+	gamma2table = malloc(9 * sizeof(*gamma2table));
+
+	// [crispy] 5 original gamma levels
+	for (i = 0; i < 5; i++)
+	{
+		gamma2table[2*i] = (byte *)gammatable[i];
+	}
+
+	// [crispy] 4 intermediate gamma levels
+	for (i = 0; i < 4; i++)
+	{
+		int j;
+
+		gamma2table[2*i+1] = malloc(256 * sizeof(**gamma2table));
+
+		for (j = 0; j < 256; j++)
+		{
+			gamma2table[2*i+1][j] = (gamma2table[2*i][j] + gamma2table[2*i+2][j]) / 2;
+		}
+	}
+    }
+
     // [crispy] initialize color translation and color strings tables
     {
 	byte *playpal = W_CacheLumpName("PLAYPAL", PU_STATIC);
diff --git a/src/i_video.c b/src/i_video.c
index d82ab5ee..aa10785d 100644
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -853,9 +853,10 @@ void I_SetPalette (byte *doompalette)
         // Zero out the bottom two bits of each channel - the PC VGA
         // controller only supports 6 bits of accuracy.
 
-        palette[i].r = gammatable[usegamma][*doompalette++] & ~3;
-        palette[i].g = gammatable[usegamma][*doompalette++] & ~3;
-        palette[i].b = gammatable[usegamma][*doompalette++] & ~3;
+        // [crispy] intermediate gamma levels
+        palette[i].r = gamma2table[usegamma][*doompalette++] & ~3;
+        palette[i].g = gamma2table[usegamma][*doompalette++] & ~3;
+        palette[i].b = gamma2table[usegamma][*doompalette++] & ~3;
     }
 
     palette_to_set = true;
diff --git a/src/tables.c b/src/tables.c
index 8ef231a7..3232d781 100644
--- a/src/tables.c
+++ b/src/tables.c
@@ -2147,6 +2147,8 @@ const angle_t tantoangle[2049] =
     536870912
 };
 
+// [crispy] intermediate gamma levels
+byte **gamma2table = NULL;
 // Now where did these came from?
 const byte gammatable[5][256] =
 {
diff --git a/src/tables.h b/src/tables.h
index 8523f073..3a1de4b0 100644
--- a/src/tables.h
+++ b/src/tables.h
@@ -57,6 +57,8 @@ extern const fixed_t finetangent[FINEANGLES/2];
 
 // Gamma correction tables.
 extern const byte gammatable[5][256];
+// [crispy] intermediate gamma levels
+extern byte **gamma2table;
 
 // Binary Angle Measument, BAM.
 
```

**Comment by JNechaevsky** [comment]
❗️ @fabiangreffrath, something goes wrong. I was going to try out Crispy with my improved palette, but I've got a crash while loading a PWAD with just one my `PLAYPAL` lump.

In standard MSYS output I have this:
```
$ ./crispy-doom -file palfix.wad
Segmentation fault
```
And this was is working fine with Chocolate Doom. Please check at your side!

- http://jnechaevsky.users.sourceforge.net/files/palfix.wad

**Comment by JNechaevsky** [comment]
Compilation on MSYS x64 working fine, but on Debian I have this error:

```
tables.c:2151:22: error: ‘NULL’ undeclared here (not in a function)
 byte **gamma2table = NULL;
                      ^~~~
```

**Comment by Zodomaniac** [comment]
@JNechaevsky everything fine with the current code?

**Comment by JNechaevsky** [comment]
💕 Everything is working fine.

![](http://priscree.ru/img/c97507435d9fea.png)
