### ISSUE TITLE
make "High Rendering Resolution" hot-swappable

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#299]
The first entry in the "Rendering" section of the Crispness menu, "High Rendering Resolution", is currently the only one that requires a restart of the engine to take effect. I need to find a way to safely re-initialize the low-level renderer and all the upper-level systems that depend on framebuffer resolution - e.g. automap, status bar, bezel, disk usage icon, etc.

**Comment by Zodomaniac** [comment]
I think this one is also on the to-do list for 5.2 :)
