### ISSUE TITLE
Unflip resurrected mirrored sprite after resurrection animation completes

### ISSUE THREAD

**Issue by mfrancis95** [fabiangreffrath/crispy-doom#302]
I made a note about it in #261. The sprite is unflipped too early (before the resurrection animation completes).

**Comment by fabiangreffrath** [comment]
Well, one could argue that the Archvile first flips the corpses to the right side before resurrecting them. ;)

But I agree that this may look confusing. The bad news is that there is no state which indicates that a monster has been resurrected. All resurrection state sequences seem to end in the respective monster's running state which calls `A_Chase()`, so I could add the flipping back there unconditionally.

**Comment by Zodomaniac** [comment]
So has this been fixed? The closing commit note says
>Unfortunately, this means one step back in fixing #302,
because a monster's flags and health are reset as soon as it gets
resurrected.

**Comment by fabiangreffrath** [comment]
> So has this been fixed? The closing commit note says

No, this cannot get properly fixed anymore (at least I have no idea currently), because a monster's health and flags get reset as soon as the Archvile start the resurrection - and both health and flags determine if a sprite gets flipped or not.

**Comment by fabiangreffrath** [comment]
Tagging as "wontfix", although "cantfix" would fit better.

**Comment by mfrancis95** [comment]
To get closer to fixing this, wouldn't the best way to reaching this goal be by not having the flip based on the health?

**Comment by fabiangreffrath** [comment]
But based on what else that's safe across savegames? Health is so invitingly uncritical for an already dead monster. ;)

**Comment by fabiangreffrath** [comment]
Also, the monsters' flags get reset upon resurrection, and objects which have their `MF_SHOOTABLE` flag set never have their sprites flipped...
