### ISSUE TITLE
Combine "colored blood" and "fixed blood" into one menu item

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#304]
I'd like to get rid of another symptom of micro-featuritis and combine the "colored blood and corpses" and "fix spectre and lost soul blood" menu items into a single "monster-specific blood" item. 
Any objections?

**Comment by JNechaevsky** [comment]
Would like to vote for "yes, combine". I think it's a good idea, both these features are the same in their such.

**Comment by fabiangreffrath** [comment]
> "monster-specific blood"

The only thing that doesn't really fit the combined feature description is that marine corpses are colored in their multiplayer colors if "colored blood _and corpses_" is enabled. Any ideas for a better description?

**Comment by JNechaevsky** [comment]
Ah, I was having this description problem long time ago. :) To get cover both "monsters" and "marines", I'm having a one menu item for both blood and corpses, which is calling "Разноцветная кровь и трупы" _("Multicolored blood are corpses")_. 

Maybe it's worth to just consolidate both these features into one "Colored blood and corpses"? I.e., don't change habitual _colored_ to _multicolored_.
