### ISSUE TITLE
Crispness menu wraparounds to first and last pages

### ISSUE THREAD

**Issue by mfrancis95** [fabiangreffrath/crispy-doom#305]
I'm wondering if you'd like the idea of having a "Prev Page" option on the first page that goes to the fourth page, and a "Next Page" option on the fourth page that goes to the first page.

![screenshot from 2018-05-02 19-26-35](https://user-images.githubusercontent.com/4574480/39554084-d89c415a-4e3e-11e8-9511-1fad804d1e7e.png)

**Comment by fabiangreffrath** [comment]
I like the idea, though prefer "first page >" and "< last page", respectively.

**Comment by fabiangreffrath** [comment]
Yes, I've had a good run. ;)

**Comment by Zodomaniac** [comment]
There is still some polish to add here: play shot sounds when switching pages with PgUp/PgDn keys as well as when switching with Enter key on Prev page/Next page/First page/Last page lines, to provide proper response to player's senses in any case.
