### ISSUE TITLE
35fps during demo playback with menu open, regardless of chosen rendering framerate

### ISSUE THREAD

**Issue by mfrancis95** [fabiangreffrath/crispy-doom#307]
Even if you're set to using uncapped or vsync rendering framerates, demos will play at 35fps whenever the menu is shown.

**Comment by fabiangreffrath** [comment]
Indeed, this is because of this condition here:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_main.c#L983

May I should change `!menuactive` to `!(menuactive && !demoplayback)`.

**Comment by mfrancis95** [comment]
In fe4b698, this wasn't fully fixed. When the menu is shown, the player's sprite is seen "lagging" in front of the view.

**Comment by fabiangreffrath** [comment]
Sorry, I don't understand. Could please elaborate a bit?

**Comment by fabiangreffrath** [comment]
Never mind, I think I got it.
