### ISSUE TITLE
When switching Colored Blood in-game, the Lost Soul blood doesn't switch

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#308]
### Background

Version of Crispy Doom: May 4 daily autobuild https://github.com/fabiangreffrath/crispy-doom/commit/b0f2ebb5e46473618b91d89a0442782db2e2dfbd

### Bug description

Observed behavior: When I switch Colored Blood in-game, Hell Nobles change blood color but Lost Souls don't change red blood to bullet puffs and vice versa. Didn't test for Cacodemons and Spectres but probably everything is fine for them, as it's just a colormap change for them.
![doom0057](https://user-images.githubusercontent.com/15119473/39617428-6524e9c0-4f88-11e8-88c9-4829f83a30d5.png)

**Comment by fabiangreffrath** [comment]
Good catch! Indeed, this change only affects newly spawned monsters. I'll see what I can do about that.

**Comment by JNechaevsky** [comment]
Pardon me for a little artistic offtopic: green blood from translation table is looking slightly brighter than it should be, i.e. comparing to the corpses of Knight and Baron. Maybe it's worth to make it darker (I did it), but this way _"hitting feedback"_ will be slightly less notable. 

From another side, we can imagine that blood is clotted on corpses, that's why it's more dark.

**Comment by fabiangreffrath** [comment]
We could play a bit with the `hsv.x`, `hsv.y`, `hsv.z` values for the green translation until it matches better:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/v_trans.c#L284

**Comment by Zodomaniac** [comment]
>Indeed, this change only affects newly spawned monsters. 
I started the game without colored blood
![doom0061](https://user-images.githubusercontent.com/15119473/39619938-344b0dc0-4f92-11e8-89ee-c17f2d3aafdc.png)
and then switched it on, it took immediate effect for hell knights, but not for the lost souls:
![doom0062](https://user-images.githubusercontent.com/15119473/39619990-5217acdc-4f92-11e8-80cb-a8fa7128b435.png)

**Comment by JNechaevsky** [comment]
@fabiangreffrath, whoah, I wasn't know that colored blood is now also using HSV, this will make things _a lot_ easier! Allright, sound like a fair new suggestion, but I need to experement with values and show some results.

**Comment by fabiangreffrath** [comment]
Yep, right!

**Comment by Zodomaniac** [comment]
Sorry for interrupting, gentlemen, your green blood discussion would be much more pleasant to track here :) https://github.com/fabiangreffrath/crispy-doom/issues/309
