### ISSUE TITLE
Crispy crashes when toggling Colored blood and corpses

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#311]
### Background

Version of Crispy Doom: May 5 autobuild https://github.com/fabiangreffrath/crispy-doom/commit/35cd01e04dcc0bcc7b6726dd38dc195fabb621e4

Operating System and version: Win 7

### Bug description

Observed behavior: Crispy crashes when toggling Colored blood and corpses.

P.S. Colored blood and marine corpses cannot be enabled separately, is this intentional? Maybe some player prefers colored blood but no colored marine corpses and vice versa.

**Comment by fabiangreffrath** [comment]
Another good catch! The code is supposed to change the Lost Souls' blood while in a game, but misses to check if there is already a valid thinker chain available.

> Colored blood and marine corpses cannot be enabled separately, is this intentional? Maybe some player prefers colored blood but no colored marine corpses and vice versa.

Yes, I know, and I have decided not to care about such corner cases anymore. Please consider "Colored Blood and Corpses" as a *feature set* that you either like as a whole or not - just like e.g. "Misc. Sound Fixes". As you might have noticed, I always try to keep the number of choices low in the menu. Feature micro-management is utterly frustrating for a developer to maintain and probably confusing for all but the handful of users whole actually care.

Have you ever ordered a Whopper at Burger King? "I'd like a Whopper, please", "As a menu, which fries, which drink, which sauce to the fries, which bun for the burger, with onions, with cucumber, with tomato, with bacon, with cheese, ..."?! I want to avoid this scenario for the port's feature menu. ;)

**Comment by Zodomaniac** [comment]
>Please consider "Colored Blood and Corpses" as a feature set that you either like as a whole or not - just like e.g. "Misc. Sound Fixes". As you might have noticed, I always try to keep the number of choices low in the menu.

In 'Apply brightmaps to:' menu item there are 4 options: None, Walls, Items and Both.
'Colored blood and corpses' reads quite logical to have selections for blood only and corpses only ;)

**Comment by fabiangreffrath** [comment]
Initially the "and corpses" part of the feature meant the crushed corpses of Barons/Hell Knights and Cacos, which were also colored like their respective blood splats. So, separating "blood" and "corpses" here made no sense, it was basically one feature.

Then, later, multiplayer-colored marine corpses were added. Now "and corpses" got its own meaning and I modified to code to handle colored blood and colored corpses - now monster and player corpses were meant - separately. This, however, meant that even crushed monster corpses were not colored anymore - even if you had colored "blood" enabled - if you disabled the "corpses" part of the feature for any reason. This didn't make any sense to me as well and so I decided to combine everything into one feature set "colored blood and corpses".

Heck, I even considered going as far as enabling colored marine corpses unconditionally, but finally decided against it.

**Comment by Zodomaniac** [comment]
OK, I got your point, thanks for the explanation!

**Comment by JNechaevsky** [comment]
My experience: colored marine's corpses is also consolidated into `colored_blood`, i.e. this variable is activating all the things: a) colored and fuzzy blood, b) colored corpses, c) colored marines's corpses. 

AFAIR, I have done it back in the days when you just explained to me what "featurism" actually is. ;)

**Comment by Zodomaniac** [comment]
@JNechaevsky 
> what "featurism" actually is. ;)

'Featuritis', as it's considered a disease like arthritis etc.

**Comment by JNechaevsky** [comment]
Oops, f-e-a-t-u-r-e-i-s-m. Meaning more and more featurues.

**Comment by fabiangreffrath** [comment]
> this variable is activating all the things: a) colored and fuzzy blood, b) colored corpses, c) colored marines's corpses.

Yep, that's how it is supposed to be.

"Featuritis" is "featurism" turned into a desease. ;)

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
is my Wiki description correct?
"Colored Blood and Corpses" and "Fix Spectre and Lost Soul blood" features have been combined into one menu item (colored blood now includes Spectre and Lost Soul blood fixes) and simplified to on/off, as coloring corpses is responsible not only for Marine corpses' multiplayer colors but also for crushed Cacodemon/Baron/Knight corpses matching their blood colors.

**Comment by fabiangreffrath** [comment]
Almost perfect!
