### ISSUE TITLE
Activating the main menu after game launch/in demo loop with any other key than ESC plays no sound

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#313]
After game launch/in demo loop the main menu can be activated by pressing any key, and if you hit a key other than ESC, the menu activates but no sound is played. The same sound should be played as when hitting ESC in this case.

**Comment by fabiangreffrath** [comment]
Indeed, there is no `S_StartSound()` here:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/g_game.c#L915

Time for a "misc sound fix". ;)
