### ISSUE TITLE
Extended Savegames feature setting is missing and there's no dialog with the required WAD name when v1.666 IWAD is involved

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#314]
### Background

Version of Crispy Doom: Daily autobuild May 10 https://github.com/fabiangreffrath/crispy-doom/commit/843e1beb33638e7232722c2d34d85f630e13436f

### Bug description

Observed behavior: Extended Savegames feature setting is missing from the Crispness menu, and there's no dialog with the required WAD name when trying to load a savegame from a WAD that's not loaded, Crispy just resumes game in this case.

Expected behavior: The dialog with the required WAD name must appear when trying to load a savegame from a WAD that's not loaded.

**Comment by fabiangreffrath** [comment]
I had to remove the switch from the Crispness menu for the lack of space, but left it enabled by default. You must have disabled it before I removed the switch and then it remained at that. I agree, however, that savegames should be scanned for the extended information upon loading even if the feature is disabled.

**Comment by Zodomaniac** [comment]
I have `crispy_extsaveg 1` in `crispy-doom.cfg`, I never disable it

**Comment by fabiangreffrath** [comment]
That's really weird. Would you mind sharing that savegame file?

**Comment by Zodomaniac** [comment]
Aha, I got the issue! I get that 'return to game on load attempt' when I try to load a game which has been saved with a different IWAD!

**Comment by fabiangreffrath** [comment]
So, this means you saved the game with one version of the IWAD loaded and then tried to restore it with another version of the IWAD loaded, but both IWADs are called DOOM2.WAD?

Well, then this flew under the radar, as the savegame loading code only compares the filenames of the WAD files that contain the map to be restored. I would have to extend this method to something much more involved like comparing WAD checksums. However, I consider the current approach safe for all but the most obscure cases, and I consider the issue at hand a very obscure case indeed. ;)

**Comment by Zodomaniac** [comment]
>but both IWADs are called DOOM2.WAD

No, I have IWADs with different names in the same directory. If I load the v1.666 IWAD that I named `doom2v16.wad`, the attempt to load game saved with some other IWAD results in resuming game, not in popping up the dialog.

**Comment by fabiangreffrath** [comment]
Please upload that savegame. :confused:

**Comment by Zodomaniac** [comment]
Here you are
[doomsav6.zip](https://github.com/fabiangreffrath/crispy-doom/files/1994563/doomsav6.zip)

**Comment by fabiangreffrath** [comment]
Hm, the `wadfilename` key is correctly set to `doom2v16.wad`.

![image](https://user-images.githubusercontent.com/6449237/39915917-7aba5686-5509-11e8-94df-8dde32250451.png)

**Comment by Zodomaniac** [comment]
Do you have savegames from other IWADs? Launch the game with `-iwad doom2v16.wad` and try to load a savegame saved with some other IWAD.

**Comment by fabiangreffrath** [comment]
I guess it is failing this check then:
https://github.com/chocolate-doom/chocolate-doom/blob/master/src/doom/p_saveg.c#L1393

Please try to explicitly set `-gameversion 1.666` on the command line when trying to restore the 1.666 savegames with the 1.9 IWAD.

**Comment by Zodomaniac** [comment]
Is this Choco check executed before the extended savegame filename check?

**Comment by Zodomaniac** [comment]
>I had to remove the switch from the Crispness menu for the lack of space, but left it enabled by default.

Is this change final?

**Comment by fabiangreffrath** [comment]
> Is this change final?

Not necessarily. Are there any reasons to ever disable it? I think the extended format doesn't have any disadvantages for the users...

> Yes, please make scanning saves for extended info unconditional :)

Which gives even more weight to my question above...

**Comment by Zodomaniac** [comment]
>Are there any reasons to ever disable it? I think the extended format doesn't have any disadvantages for the users...

IMO you're right :)

**Comment by fabiangreffrath** [comment]
Please report back if the `-gameversion 1.666` quirk works, so we can close this issue. Restoring savegames across different gameversions is apparently unsupported.

**Comment by fabiangreffrath** [comment]
No, we do not even attempt to create back- and forth-compatibility for savegames across different IWAD versions. So, I see the engine works as expected, thanks!

**Comment by fabiangreffrath** [comment]
Maybe it is a good idea to file a request at the Choco tracker to make it somehow more explicit that a savegame refuses to load because of a gameversion mismatch.
