### ISSUE TITLE
Segfault when loading a map with no nodes and one subsector

### ISSUE THREAD

**Issue by mfrancis95** [fabiangreffrath/crispy-doom#315]
```
P_LoadNodes: No nodes in map, but only one subsector.
Segmentation fault (core dumped)
```
The segfault occurs in Chocolate Doom too, but I'm wondering if it's something that should be fixed in Crispy.

**Comment by fabiangreffrath** [comment]
Well, basically it tells you that the nodes haven't been built for this map, but that it should okay since the entire map consists of only one subsector anyway. Thus, it shouldn't crash afterwards!

Would you mind sharing this map here?

Does PrBoom+ crash when attempting to load this map?

**Comment by mfrancis95** [comment]
PrBoom+ output:
```
P_LoadNodes: trivial map (no nodes, one subsector)
P_LoadThings: no things in level
I_ShutdownSound: 
```
[segfault.zip](https://github.com/fabiangreffrath/crispy-doom/files/1996258/segfault.zip)

**Comment by mfrancis95** [comment]
So it might have to do with the lack of things on the map.

**Comment by fabiangreffrath** [comment]
Yes, definitely. If there are no things on the map, there is no Player 1 start.

**Comment by mfrancis95** [comment]
Should this change also be brought into Chocolate?

**Comment by fabiangreffrath** [comment]
Yes, might be a good idea.

**Comment by fabiangreffrath** [comment]
We should probably also add a check to `P_SpawnPlayer()` to check if `mthing == NULL` and error out if this happens.
