### ISSUE TITLE
Smooth texture scrolling

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#317]
It's an interesting topic for discussion rather than suggestion at the moment. As you know, linedef effect 48 is a scrolling texture:

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_spec.c#L1230
```
        case 48:
        // EFFECT FIRSTCOL SCROLL +
        sides[line->sidenum[0]].textureoffset += FRACUNIT;
        break;
```
`FRACUNIT` is acting as one texture pixel here. I'm not familiar with bit-shifting, but real value is looking like this: `1<<16` (is it `65536`?). So, to move texture not by one pixel but softly, we may replace `FRACUNIT` with something like `1024` and immediately another problem comes: scrolling speed will be greatly reduced.

This is seems to be because of `P_UpdateSpecials` is called in `P_Ticker`, which is called in `G_Ticker`, which isn't called ... every game tic? For example, calling `P_UpdateSpecials` from `D_Display` _(it will also affect switches, just for test only!!!)_ is making animation slightly faster.

So how do you think, is there a way to preserve original scrolling speed and make scrolling smoother? 

**Edit:** looks likes smoothing will work only for >35 FPS.

_Suggestion №93_

**Comment by fabiangreffrath** [comment]
The idea is very well possible inanalogy to mobj positions, which we interpolate in each rendering frame but only actually update each gametic.

We would need a function like `P_UpdateSpecials()` that gets called from `D_Display()` (or rather one of the function it calls) and updates the `spriteoffset` field of the animated sides with `fractionaltic`, c.f. `R_ProjectSprite()`. The `sides_t` struct would need to get an `oldoffset` field for that which would get increased in `P_UpdateSpecials()` instead of the actual `spriteoffset` field.

I know this reads like some confusing blubber, but indeed I have an idea behind that. ;)

**Comment by JNechaevsky** [comment]
Duh... I can't check at the moment, I'm at work. What a temptation to leave and check! :disappointed:

**Comment by JNechaevsky** [comment]
I'm extremely short in time, but got it checked. Sadly, no, it's not working properly. Texture is just shaking left-right (was checked in uncapped, but video record is 30 fps):

- https://youtu.be/cb_sBL_DB_E

Also, don't forget to add `void R_InterpolateTextureOffsets();` in r_local.h.

**Comment by fabiangreffrath** [comment]
Sorry, there was a `lines` --> `line` typo in that patch. This one should work, even when paused:
[crispy-smooth-texture-scroll2.txt](https://github.com/fabiangreffrath/crispy-doom/files/2001558/crispy-smooth-texture-scroll2.txt)

**Comment by JNechaevsky** [comment]
Argh, I'm still at work and will get linger today. Probably will be able to check it only in 1.5-2 hours. Sorry for such Impatience, but I have found this idea absolutely lovely, and thus, can't to see it working. 

Self-note: do not forget to check Plutonia's map "Chost Town", where some super-speed scrollers are present (and investigate how this vanilla trick is working).

**Comment by JNechaevsky** [comment]
Testing has been finished and I'm happy to say - it's working! :sparkles:
In both instances: as a standard scroller on HoE MAP30, and as super-fast on Plutonia MAP05.

Super-fast scroller is a mapping trick, as described by Memfis on [DoomWorld](https://www.doomworld.com/forum/topic/95518-fast-texture-scrolling-in-plutonia-map05/?do=findComment&comment=1783641).

However, I have noticed one small moment: when you set game on pause, texture shifts right to one map pixel. To be more clear:

- Unpaused state: http://priscree.ru/img/886adcb2ef282b.png
- Paused state: http://priscree.ru/img/1a09a28f252232.png

It's really not critical, but maybe it also can be fixed somehow?

**Comment by JNechaevsky** [comment]
Hmmm. To prevent texture shifting/shaking, you can replace `0` with `FRACUNIT` in `R_InterpolateTextureOffsets`:

```
	if (crispy->uncapped &&
	    !paused && (!menuactive || demoplayback || netgame))
	{
		frac = fractionaltic;
	}
	else
	{
->		frac = FRACUNIT;
	}
```

This way, while paused state whole texture pixel will still appear, but shifting right will gone. Probably it's a good solution?

Ah yes, you can check shaking by standing very close to the scrolling texture and by holding `PAUSE` button.

**Comment by fabiangreffrath** [comment]
I think I'll stick to this version which should fix the issues you mentioned.

[crispy-smooth-texture-scroll3.txt](https://github.com/fabiangreffrath/crispy-doom/files/2003472/crispy-smooth-texture-scroll3.txt)

**Comment by JNechaevsky** [comment]
Just checked. Now it's always showing half of texture pixel in the corner that is shown on screenshot, whe the game is paused. If my eyes are not tricking me, very small shaking is still notable, but only while _very_ close looking, and holding `PAUSE` button (i.e. extremely fast pausing and unpausing the game). Verified it with with second approach + `FRACUNIT`, nope, it's not an optical illusion.

**Comment by JNechaevsky** [comment]
Wait, shaking and half-o-pixel while pause can be fixed by combining second + third approach, i.e.:

**P_UpdateSpecials**
```
        // EFFECT FIRSTCOL SCROLL +
        // [crispy] smooth texture scrolling
	    sides[line->sidenum[0]].oldtextureoffset =
	    sides[line->sidenum[0]].textureoffset;
 	    sides[line->sidenum[0]].textureoffset += FRACUNIT;
        break;
```
**R_InterpolateTextureOffsets**
```
	else
	{
		frac = FRACUNIT;
	}
```

This way I don't see any shaking and can have any pixel size in paused state: http://priscree.ru/img/6b80216f7703ea.png

Could you please check it on your side?

**Comment by fabiangreffrath** [comment]
Next iteration, I am pretty confident that this is it (though I have been before):
[crispy-smooth-texture-scroll4.txt](https://github.com/fabiangreffrath/crispy-doom/files/2004142/crispy-smooth-texture-scroll4.txt)

**Comment by JNechaevsky** [comment]
No shaking now, but in paused state whole texture pixel is always appearing. Hm. Could be because of how pausing actually works? I.e. it's pausing non-interpolated tic.

Please, take a try my [commit](https://github.com/JNechaevsky/russian-doom/commit/e180e3cfd9eca1a06a81abcdfee5fbc59c45124e), when you'll have time. It's a combination of 2nd and 3rd approach. There will be no shaking, and texture offset will correctly set in paused state, so you can have any size of texture pixel ([screenshot](http://priscree.ru/img/0b32fefa9a687d.png)).

**Comment by fabiangreffrath** [comment]
Yep, pause is only recognized from the next full tic on and keeps the offsets from interpolating from then on. So, it is correct behaviour to only show full pixels on the texture.

Thanks, even though your approach looks nice too, I think I'll stick to mine. ;)

**Comment by JNechaevsky** [comment]
Thanks! I wonder, is now really all the things related to interpolation are done? Probably so. :)

Just a one small addition that comes in mind from nova.wad: in one of levels (was it 17 or 19? Can't say for sure now, neither can't check - I'm back at work), there were a linedefs scrolling right. It's a Boom-specific and obviously not working in Crispy, but the implementation itself is rather than simple, just take a look [here](https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/p_spec.c#L1196) (uh-oh, I forgot to interpolate them!). 

How do you think, is it worth to implement this extremely small addition into Crispy? Or better leave it "as is", since Crispy is not Boom-compatible?

**Comment by fabiangreffrath** [comment]
Let's put it in then!

**Comment by JNechaevsky** [comment]
Hooray! :star2:

Last thing (no, honestly) that coming to mind - swirling liquids. But they seems to be complicated by two reasons:
1. Animation moving their pixels always as whole pixels. Probably, it's still possible to interpolate, since one texture pixel is not a a simple digit `1`, but a `65536` molecules inside mysterious `FRACUNIT`.
2. Their animation is using own `swirltic`.

P.S. I would like to recommend don't describe textures scrolling right as Boom-specific in changelog. Let it be just something like "Linedef specific 85 (Scroll texture right) is now supported". The reason why I'm not recommending to mention Boom - it's a pretty big complex of specifics and other stuff. Some of them are simple to copy/implement, many are differently not. No need to let people think that "can of worms" now opened, and the rest of Boom-specifics are planned. :)

**Comment by fabiangreffrath** [comment]
Although I like the idea in general - and I am sure that the effect looks even much more beatiful when interpolated - flat swirling is such an obscure feature and I have never seen it in any WAD that I currently have no motivation to add this myself. But PR are always welcome. ;)

Weapon bobbing is another thing that comes to mind that is still not interpolated. But since this is very sensitive code, I probably don't care either. 

Regarding the changelog, very good point! @Zodomaniac we should not advertise right scrolling textures as a Boom-specific feature in the release notes!

**Comment by JNechaevsky** [comment]
> I currently have no motivation

That's because you should make this feature as optional, not as just specific-supported, it's awesome! But it also dangerous, since flats are always merged and we probably will not be able to catch a modified flats. Plus, some mods may use liquid flood as a non-liquid animated textures.

Okay, that's fair, I'll see what I can I do, but let me please break my head on Heretic's floor scrolling interpolation first. Scrolling code itself is deadly simple, which is making me totally confused, but that's another story. Plus, I will need to learn how to apply warping in `ANIMDEFS`.

Weapon bobbing is looking pretty well neat in uncapped, so if it's dangerous, better leave it as is. THe only thing I wonder - can it be tablified, as was suggested by id's comment?

**Comment by Zodomaniac** [comment]
> @Zodomaniac we should not advertise right scrolling textures as a Boom-specific feature in the release notes!

I didn't mention Boom, just wrote "linedef specific 85 (Scroll texture right) is now supported".

**Comment by fabiangreffrath** [comment]
Perfect, thanks!

**Comment by JNechaevsky** [comment]
Heretic floor scrolling code is too damn simple to operate with. Swirling, in return, is too hard with few formulas I can't understand. However, with some luck and patience it is possible to achieve some really nice wave effects, even much nicer than simple shaders, but -- it will be interesting only in terms of modding, not in terms of 100% friendly and compatible with vanilla liquids. So let's just leave it "as is". :)

Bobbing is more interesting. Movement itself seems to be interpolated, while pixel redrawing is not. I mean, pixel may move not by weapon pixels themselves, but by "screen pixels", and this, apparently, will bring some more smoothness. But since you declare this as unsafe (because of `FixedMul` + binding to player's coords?), let's also leave it.

I think I have an raw idea for bobbing, but need to think more first...

**Comment by JNechaevsky** [comment]
@fabiangreffrath,

> Weapon bobbing is another thing that comes to mind that is still not interpolated. But since this is very sensitive code, I probably don't care either.

This must be a solution:

1) https://github.com/JNechaevsky/russian-doom/commit/0aa9486112913aa45330c6af77ccdb8c366e88ee
2) https://github.com/JNechaevsky/russian-doom/commit/02b643d24fe47751cbc93995701359dba6be51a3

Second commit is absolutely necessary, because of bug in PrBoom+ code - try to increase/decrease screen size there, you will see a weapon "shaking".

**Comment by fabiangreffrath** [comment]
Nowadays, I calculate weapon bobbing coordinates independent from actual critical `player->bob` value anyway in `P_MovePsprites()`. So it should be safe to add some interpolation here, but I haven't cared so much yet.

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_pspr.c#L1007

**Comment by JNechaevsky** [comment]
Got it, thanks. I'll try when I'll have some time, still in "untra-nightmare" working mode.

_P.S. I have purchased a new monster PC (core i7 9700f, nvidia rtx 2060, 16 gb ram). Do we have any possible cases for benchmarking?_
