### ISSUE TITLE
Fix "Arch-Vile fire spawned at the wrong location"

### ISSUE THREAD

**Issue by mfrancis95** [fabiangreffrath/crispy-doom#318]
```diff
diff --git a/src/doom/p_enemy.c b/src/doom/p_enemy.c
index d66bab49f..0bd0fb12b 100644
--- a/src/doom/p_enemy.c
+++ b/src/doom/p_enemy.c
@@ -1324,7 +1324,7 @@ void A_VileTarget (mobj_t*	actor)
     A_FaceTarget (actor);
 
     fog = P_SpawnMobj (actor->target->x,
-		       actor->target->x,
+		       actor->target->y,
 		       actor->target->z, MT_FIRE);
     
     actor->tracer = fog;
```

I posted this as an issue instead of a PR because I'm not sure if this is something that can cause desyncs.

[Source](https://doomwiki.org/wiki/Arch-Vile_fire_spawned_at_the_wrong_location)

**Comment by mfrancis95** [comment]
This fixes a different bug with the fire.

I confirmed in game that the x-y displacement bug still exists. Are you saying this bug can't be fixed in a demo-compatible matter?

**Comment by fabiangreffrath** [comment]
One bug causes the other: The fire is initially spawned in the wrong sector - granted, that's the one bug. However, its position is then modified during each (second?) tic to follow the targeted player step-by-step. This means, it is just a matter of a few tics until the fire is close to the player. Then, the second bug is that the fire's vertical position is aligned between floor and ceiling of its - mistakenly chosen - spawn sector. That's the bug that has already bee fixed.

The first bug is only visible during the first few tics after the fire is spawned, the second one is much more annoying. Thus, I didn't even bother to fix the first one. I am not sure if fixing it affects demo sync, spawning map things in different sectors might pretty well do so...

**Comment by fabiangreffrath** [comment]
> I see, so it's just something not worth going through the trouble of trying to fix, like the "baron attacking behind his back" quirk. Thanks for the clarification.

Yes, it's probably the same kind of bug.

Though, if you could show me and proof that changing the y-coordinate for the flame's spawning point does not affect demo compatibility, I would probably change my mind. A Plutonia UVMAX32 run would probably qualify. ;)

**Comment by JNechaevsky** [comment]
Guess, this page is all we need for testing Plutonia MAP32?
http://doomedsda.us/wad946m232.html

**Comment by fabiangreffrath** [comment]
Not only map32, it will need a full 32 maps run. ;)

**Comment by JNechaevsky** [comment]
I can make few `-timedemo` runs of different full 32 map demos and a make a video records. Hope it will finally make some clearness in second `target->x`.

**Comment by JNechaevsky** [comment]
But meanwhile, can you please confirm that these two bugs are --

1. Fire spawns in wrong vertical location. Extremely notable on MAP16.
2. Fire jumping from ceiling to floor while cycling through frames (fixed in Crispy).

**Comment by JNechaevsky** [comment]
>If by "vertical location" you mean y-coordinate, then yes, that's the bug in question here!

Yeah-yeah, this exactly was meant, and this first bug is described on [DoomWiki](https://doomwiki.org/wiki/Arch-Vile_fire_spawned_at_the_wrong_location). Second one isn't described on DoomWiki, though, but described pretty clear on [DoomWorld](https://www.doomworld.com/forum/topic/68383-what-is-the-archvile-flame-supposed-to-look-like/?do=findComment&comment=1297985).

Allright then, I'm free to go, and will post my testing videos shortly.

**Comment by JNechaevsky** [comment]
### Plutonia

UVMax32 - PRBoom v2.5.1.3cl4 - 57:27 TAS ([link](http://doomedsda.us/lmps/946/1/plallx5727.zip))
►

UVMax32 - PRBoom v2.5.1.4cl4 - 2:37:18 ([link](http://doomedsda.us/lmps/946/1/plall-23718.zip))
►

UVMax32 - DooM2 v1.9 - 2:54:33 CN ([link](http://doomedsda.us/lmps/946/1/30plmax.zip))
Desync on MAP02! With and without `target->x` correction.
►

### TNT

UVMax32 - PRBoom v2.5.1.3cl4 - 1:46:42 TAS ([link](http://doomedsda.us/lmps/944/1/evallx14642.zip))

**Comment by JNechaevsky** [comment]
Phew, it takes much longer than expected. According to my tests, this correction is safe for demos. 

### Plutonia

UVMax32 - PRBoom v2.5.1.3cl4 - 57:27 TAS ([link](http://doomedsda.us/lmps/946/1/plallx5727.zip))
► https://youtu.be/JY8IUX93m74

UVMax32 - PRBoom v2.5.1.4cl4 - 2:37:18 ([link](http://doomedsda.us/lmps/946/1/plall-23718.zip))
► https://youtu.be/by3yFkHtgi8

UVMax32 - DooM2 v1.9 - 2:54:33 CN ([link](http://doomedsda.us/lmps/946/1/30plmax.zip))
Got no desync as `-timedemo 30plmax.lmp -file plutonia.wad -iwad doom2.wad`. Runner should be slapped to the hands for using IWAD as PWAD!
► _reuploading, working fine_

**Comment by fabiangreffrath** [comment]
Sorry for another wish, but could you probably also check `30plmax`?

**Comment by JNechaevsky** [comment]
NM Speed 32 - CNDoom v2.0.2.1 - 43:57 ([http://doomedsda.us/lmps/946/3/plalln4357.zip](link))
`crispy-doom.exe -timedemo 30pn4357.lmp -iwad plutonia.wad`

Working fine from A to Z, no desyncs (with `target->y` of course).

**Comment by fabiangreffrath** [comment]
Thank you very much for the tests!

Hm, now it begins to make sense. We already spawn "harmless" bullet puffs in outside areas and their respective mapthings `MT_PUFF` have the `MF_NOBLOCKMAP|MF_NOGRAVITY|MF_FLIPPABLE|MF_TRANSLUCENT` flags set. 

The Arch-Vile's fire has mapthing `MT_FIRE` and this has about the `MF_NOBLOCKMAP|MF_NOGRAVITY|MF_TRANSLUCENT` flags set.

While `MF_FLIPPABLE` and `MF_TRANSLUCENT` have been added by myself and are absolutely harmless, both mapthings carry the `MF_NOBLOCKMAP` flag, which should make them safe per se. So, yes, probably it makes sense to fix this issue in the code, but why didn't other source ports bother to do the same before?

**Comment by mfrancis95** [comment]
Just keep in mind that comment in the Doomworld thread about how Dehacked modifications to the fire could potentially cause desyncs.

**Comment by fabiangreffrath** [comment]
Yes, we'd be pretty much borked if the `MF_NOBLOCKMAP` flag was dehacked away from `MT_PUFF` or `MT_FIRE` mapthings. The question is if we want to support that and if this eventuality should keep us from implementing the fix?

**Comment by fabiangreffrath** [comment]
I still feel like a coward today, but will probably add the fix later after I have sympathized with it.

**Comment by JNechaevsky** [comment]
Wait a minute, I have a plan. Let's imagine that we're was _very_ lucky to have no desyncs in Plutonia demos. How else it can be tested then? We need a testing map with:

- Simple maze-like map with rooms, combined with pits and portal, that's can be only crossed by "jumping", invoked by Archvile's attack. Ten rooms with pits and ten with portal could be enough? 
- Custom `COLORMAP` with no inverted palette. I can easily make it, days of making brightmaps based on colormaps was a good experience.
- Couple of invulnerability spheres, placed on this map. Cheating is not working while demo recoring.
- A demo record, made with this map.
- Probably, another demo, recorded as `-solonet` so we can check synchronization after resurrection.
- Not sure how to test other monsters behavior in this map, though.
- Something else?

Finally, if on demo record player will be able to complete the level from starting point to exit, this will be a good sign. So howdy you think, is it a good plan and should I try to do this?

**Comment by JNechaevsky** [comment]
We are fine with this demo (both `-playdemo` and `-timedemo`). But something goes wrong with PAR time, just take a look at the end of the video. Recorded with `target->y` correction:

- https://youtu.be/Bj-KRq5liSg

**Comment by Zodomaniac** [comment]
@JNechaevsky Par time `SUCKS` at MAP33 because of a map bug, I got the same when recording and playing back the demo without the correction.

**Comment by fabiangreffrath** [comment]
It's not a "map bug", it has been implemented like this:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/g_game.c#L1720

**Comment by Zodomaniac** [comment]
@fabiangreffrath The absence of par time in the map is a map bug, the other thing is that you implemented an in-engine fix.

**Comment by fabiangreffrath** [comment]
@Zodomaniac You are right, but I still wouldn't call it a "map bug". Let me try to explain: In DOOM.EXE the par times for the Doom 2 maps are stored in an array of `int`s which has 32 elements.

**Comment by fabiangreffrath** [comment]
Now, if you finished Map33, the engine will look for the par times right after this array, where other data comes. These data is then interpreted as an `int` and shown as the par time for Map33. This, however, results in a very large number (I don't know which one exactly) which in turn results in the "sucks!" graphics to be displayed. I merely emulated this large number by setting the par time for Map33 to `INT_MAX` to achieve the same result.

PS: Sorry for closing and re-opening with the unfinished explanation. It is still early in the mornning...

**Comment by fabiangreffrath** [comment]
The reason why I wouldn't call it a "map bug" is that it isn't the map's fault that there are no par times for it. Par times are hard-coded into the engine, i.e. they are not part of the map's lumps, and there simply has never been a value for Map33.

**Comment by fabiangreffrath** [comment]
Regarding the actual bug discussed here:

My idea is to add debug messages to `A_VileAttack()` (and maybe some of the surrounding `A_Fire*()` functions) and display the actor's and the fire's coordinates during each call. If I am not mistaken, the fire's initial position is irrelevant at the time it does its actual damage to the player. This would become apparent when playing back a demo involving an Arch Vile fight once with and once without the coordinate fix applied.

**Comment by Zodomaniac** [comment]
@fabiangreffrath 

Doom Wiki mentions absence of par time among bugs:
>Bugs
On the intermission screen, the par time for this level is initially displayed as :00, but quickly switches to SUCKS. This normally only appears with the Time readout when the time taken to finish a level exceeds one hour.
In the Xbox version of the level, the teleporter in front of the yellow keycard door does not work...

that's why I called it a map bug, I had been mislead.

**Comment by fabiangreffrath** [comment]
> that's why I called it a map bug, I had been mislead.

I see. ;)

> Does the fire do damage to the player? 

Not during burning, but during the explosion.

It is really that mean! First the Ass Vile launches a barrell explosion against the player and then a `P_RadiusAttack()` fom the fire's position:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_enemy.c#L1345

**Comment by fabiangreffrath** [comment]
I have just seen another thing: What is the last function that is called from `A_VileTarget()` after the fire has been spawned at the wrong coordinate? That's `A_Fire()` in which the fire's coordinate is set again, this time relative to the player's own. So, how is this bug even visible in the first place?

**Comment by JNechaevsky** [comment]
It's getting interesting, so please don't let this investigation down. Actor states at [info.c](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/info.c#L412) are also dropping some fuel to the fire: we have a bunch of `A_FaceTarget` calls and only one `A_VileTarget` call. Need to dig in for few hours, but it's late evening already. ><

As a "plan B" I can suggest this:

```
    fog = P_SpawnMobj (actor->target->x,
		       crispy->singleplayer ? actor->target->y : actor->target->x,
		       actor->target->z, MT_FIRE);
```
But something tells me that by offering this plan I should also have a retreat plan, until someone got me slapped to the hands! :hushed:

**Comment by fabiangreffrath** [comment]
Sorry, but Plan B is out of the question. Either there is a reasonable demo-safe solution, or there isn't. :stuck_out_tongue:

**Comment by JNechaevsky** [comment]
I know, I know! :anguished: Just want everyone to know that suggesting unsafe things like this may have a consequences like this:

![](https://upload.wikimedia.org/wikipedia/commons/1/11/Koerperstrafe-_MA_Birkenrute.png?uselang=ru)

**Comment by JNechaevsky** [comment]
Save file for testing: [doomsav0.zip](https://github.com/fabiangreffrath/crispy-doom/files/2036554/doomsav0.zip). After loading, wait for ~half-o-second and press `back` + `strafe right`. A bit hard to catch a right moment, but with some luck you will be able to see this:

![default](https://user-images.githubusercontent.com/21193394/40503279-450edc4a-5f96-11e8-9868-1ea93d36c0b0.png)

**Comment by JNechaevsky** [comment]
But it still wrong, though. With correct `y` coord, it looks like flame is spawned not in front of player's eyes, but "inside" him. This is happening only when conditions of wrong spawning was repeated. Not sure, is it my imagination or not, but most probably it's not...

**Comment by mfrancis95** [comment]
What's the status on this fix? Since the intercepts limit was removed, will this be able to be added without causing problems?

**Comment by fabiangreffrath** [comment]
I am still afraid this is one of the detail fixes that will sooner or later fall back on my feet. On the other hand, the Vile's fire has the `MF_NOBLOCKMAP` flag, so it should be safe, right? And @JNechaevsky has successfully performed demo tests with this fix, right?

**Comment by JNechaevsky** [comment]
Yeah, I also can make a save game file if necessary. But the problem is - I'm not very happy about the result. This way (i.e. in this case) flame in spawned "inside" the player, in his X and Y coords, not in front of the face, which feels odd. That's why I've decided to don't apply this fix in RD.

**Comment by fabiangreffrath** [comment]
I guess in the current light of #484 (i.e. merely adjusting the fire mobj's `floorz` and `ceilingz` values to prevent it from jumping up and down causes demo desync) it is clear that changing the fire's spawn coordinate is an absolute no-go!
