### ISSUE TITLE
Add an environment variable to specify a path to the IWAD directory

### ISSUE THREAD

**Issue by Calinou** [fabiangreffrath/crispy-doom#320]
I'd like to add Crispy Doom to my [scoop-games](https://github.com/Calinou/scoop-games) Scoop bucket (it's a package manager of sorts for Windows).

However, I need to be able to specify an absolute path to an IWAD directory so that I can make that directory persistent (otherwise, user-supplied IWADs would be removed on every update; you can read about how Scoop handles persistent data [here](https://github.com/lukesampson/scoop/wiki/Persistent-data)).

GZDoom already supports the `DOOMWADDIR` environment variable to achieve this; see an example usage [here](https://github.com/Calinou/scoop-games/blob/master/gzdoom.json#L29). Should we use the same name (to reuse it if it's already there) or a different name (to avoid conflicts in case this is undesired)?

**Comment by fabiangreffrath** [comment]
Choco and Crispy do already support `DOOMWADDIR`, so what is missing?
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/d_iwad.c#L686

**Comment by Calinou** [comment]
I overlooked that – I should have done a code search, sorry. Thanks for mentioning it; I just committed [Crispy Doom in scoop-games](https://github.com/Calinou/scoop-games/blob/master/crispy-doom.json) :smiley:

**Comment by fabiangreffrath** [comment]
Thanks for adding Crispy Doom!

Regarding your nitpick: We have `-config` and `-extraconfig` variables that might be exactly what you are looking for.
