### ISSUE TITLE
Fuzz effect goes out of bounds

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#321]
Apparently, it's brought by cleaning up `hires` code. It is happening in all four display modes:

- hires / high detail
- hires / low detail
- lowres / high detail
- lowres / low detail

Screenshots of [hires](http://priscree.ru/img/e05c7ed1182131.png) and [lowres](http://priscree.ru/img/6c23c45bce0ae8.png).

**Comment by Zodomaniac** [comment]
I cannot see anything going out of bounds
![doom0077](https://user-images.githubusercontent.com/15119473/40276261-fcafae9c-5c0d-11e8-97fb-b06e5fcb6bf4.png)
![doom0076](https://user-images.githubusercontent.com/15119473/40276262-fccbd626-5c0d-11e8-8a3c-6db6d392415e.png)

**Comment by JNechaevsky** [comment]
Here: http://priscree.ru/img/c86614552e25a0.png

Those pixels are filled with random data of colors. If you enable traditional HUD / bezel, you will notice that similar fuzzy pixels will be placed right in HUD / bezel.

**Comment by Zodomaniac** [comment]
BTW, @fabiangreffrath, what's the difference between lowres and low detail? Wiki says:
>Enhanced 640x400 display resolution, with the original 320x200 resolution still available in the "Graphics Detail: Low" mode.

So they were kinda connected before, and now they are not?

**Comment by fabiangreffrath** [comment]
Yep, that sentence isn't right anymore! In Vanilla the "Graphics Detail: Low" means that *horizontal* resolution is halved and thus pixels need to get doubled on the horizontal axis. Originally, I changed this to have both vertical and horizontal resolution hlved, so pixels needed to get doubled on both axes. However, this was only done so if Crispy was compiled with the `hires` macro set to 1 (which is the default), preserving the original behaviour if compiled with `hires 0`. This lead to a lot of `if ... then .. else` chaos involving both the `hires`macro and the `detailshift` variable.

With the recent code clean-up, these two are now uncoupled. If you select the "Graphics Detail: Low" mode, only horizontal resolution will get halved (just like in Vanilla), so you end up with 320x400. In turn, if you choose "High Resolution Rendering: Off" in the Crispness menu, the low-level framebuffer resolution will be changed to 320x200, i.e. the original Vanilla resolution without any pixel doubling. "Graphics Detail: Low" mode will, of course, also work just like in Vanilla.

The only drawback that makes this a bit clumsy at the moment is that changing this setting requires a restart and is currently not applied on-the-fly.

**Comment by fabiangreffrath** [comment]
Does this help`
```
--- a/src/doom/r_draw.c
+++ b/src/doom/r_draw.c
@@ -410,7 +410,7 @@ void R_DrawFuzzColumn (void)
     // draw one extra line using only pixels of that line and the one above
     if (cutoff)
     {
-       *dest = colormaps[6*256+dest[(SCREENWIDTH*fuzzoffset[fuzzpos]-FUZZOFF)/2]];
+       *dest = colormaps[6*256+dest[SCREENWIDTH*(fuzzoffset[fuzzpos]-FUZZOFF)/2]];
     }
 }

@@ -489,8 +489,8 @@ void R_DrawFuzzColumnLow (void)
     // draw one extra line using only pixels of that line and the one above
     if (cutoff)
     {
-       *dest = colormaps[6*256+dest[(SCREENWIDTH*fuzzoffset[fuzzpos]-FUZZOFF)/2]];
-       *dest2 = colormaps[6*256+dest2[(SCREENWIDTH*fuzzoffset[fuzzpos]-FUZZOFF)/2]];
+       *dest = colormaps[6*256+dest[SCREENWIDTH*(fuzzoffset[fuzzpos]-FUZZOFF)/2]];
+       *dest2 = colormaps[6*256+dest2[SCREENWIDTH*(fuzzoffset[fuzzpos]-FUZZOFF)/2]];
     }
 }

```

**Comment by JNechaevsky** [comment]
Yes, this way it's working fine in all four screen modes.
