### ISSUE TITLE
P_LoadLineDefs warning with linedefs 271 and 272

### ISSUE THREAD

**Issue by mfrancis95** [fabiangreffrath/crispy-doom#322]
MBF sky transfer linedefs are supported, yet are warned about as if they're unknown linedef types. Something like this will remove the warning:

```diff
diff --git a/src/doom/p_setup.c b/src/doom/p_setup.c
index cfc321214..8aeef9563 100644
--- a/src/doom/p_setup.c
+++ b/src/doom/p_setup.c
@@ -581,7 +581,7 @@ void P_LoadLineDefs (int lump)
        ld->flags = (unsigned short)SHORT(mld->flags); // [crispy] extended nodes
        ld->special = SHORT(mld->special);
        // [crispy] warn about unknown linedef types
-       if ((unsigned short) ld->special > 141)
+       if ((unsigned short) ld->special > 141 && ld->special != 271 && ld->special != 272)
        {
            fprintf(stderr, "P_LoadLineDefs: Unknown special %d at line %d.\n", ld->special, i);
            warn++;
```

I'm not sure what the significance of the casting is here. I guess you could cast the other occurrences of `ld->special` to `unsigned short` to be safe.

**Comment by fabiangreffrath** [comment]
The cast is there, because I am lazy and only check aganist 141 as an upper bound. However, `-1` is also an unsupported linedef type and by casting it to `unsigned short` it will be `> 141`.

The most proper fix to fix would be to finally implelent the other missing extended linedef types (not talking about generalized linedef types yet).

**Comment by fabiangreffrath** [comment]
@mfrancis95 I have seen that you have been working on implementing some extended Linedef (or was it sector) types in your Crispy fork. How far have you come with that? Is it in a state that could get merged?
