### ISSUE TITLE
(Boom) Scroll Texture Right not working?

### ISSUE THREAD

**Issue by mfrancis95** [fabiangreffrath/crispy-doom#323]
In the most recent commit (890299a), linedef 85 is apparently not working. It just displays without the scroll right effect. It's not working even in 977df2d.

[BOOMEDIT.WAD](https://www.doomworld.com/idgames/themes/TeamTNT/boom/boomedit) is a good wad for testing out Boom features.

**Comment by Zodomaniac** [comment]
I see scrolling left also works, should I mention it in the changelog?
![doom0054](https://user-images.githubusercontent.com/15119473/40470895-8ebb1290-5f3d-11e8-93f7-fb57a4a133fa.png)
![doom0075](https://user-images.githubusercontent.com/15119473/40470894-8e995ccc-5f3d-11e8-955d-1b434ba6d66a.png)

**Comment by JNechaevsky** [comment]
No-o, linedef specific `48` is a standard Doom specific which is working "from the box" in any source port. As an example, simply try to open up HoE's MAP30 in Doom Builder - scrolling faces texture in the sector with teleport is spec. `48`.
