### ISSUE TITLE
Suggestion: New Crispness option for disabling view bobbing

### ISSUE THREAD

**Issue by mfrancis95** [fabiangreffrath/crispy-doom#325]
Not to be confused with weapon bobbing.

**Comment by fabiangreffrath** [comment]
What exactly is this supposed to achieve?

As a rule of thumb, a request has very low chances of acceptance from my side if (a) it requires another switch in the Crispness menu and (b) does not mean much more than removing a feature or changing a characteristic of the original engine. :wink:

**Comment by mfrancis95** [comment]
I guess it's not supposed to achieve much. I look at it as a modification akin to weapon squatting and attack alignment.

**Comment by fabiangreffrath** [comment]
Weapon squatting adds a bit to the engine's feel of realism (and was a bit of a technical challenge, sometimes this is an important aspect for the implementation of a feature as well :grin:) and attack alignment helps a lot with aiming while you move even when not using a crosshair. The change discussed here, though, feels more like another change for the sake of a change (like "hey, we have the code, so we *could* make it"), and I am generally opopsed to that.

**Comment by fabiangreffrath** [comment]
I think it's clear that this has no space in Crispy.
