### ISSUE TITLE
Release Crispy Doom 5.2

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#326]
I think it makes sense to gather some ideas here and close the issue when the release has been done.

I think the most important features in this cycle have been implemented and "aged well". All other features/requests are either low priority, "nice to have" or "possibly critical" and need some closer inspection.

Any objections?

**Comment by Zodomaniac** [comment]
I have created a Crispy Doom 5.2 milestone and attached some issues to it:
https://github.com/fabiangreffrath/crispy-doom/issues/266
and possibly https://github.com/fabiangreffrath/crispy-doom/issues/316 if it's easy to implement.

BTW, could you try building the release SDL DLLs with Visual Studio and EXEs in MinGW with static libgcc as StasBFG did, eliminating the bugs revealed by the presence of midiproc?

**Comment by fabiangreffrath** [comment]
> I have created a Crispy Doom 5.2 milestone and attached some issues to it:

Yes, thanks, I have seen that. However, the tagged issues clearly fall into the low/no priority category for me. Please see my comment to #316 and take it with a grain of salt. ;)

> BTW, could you try building the release SDL DLLs with Visual Studio and EXEs in MinGW with static libgcc as StasBFG did, eliminating the bugs revealed by the presence of midiproc?

No, sorry. I don't even have access to a MSCV compiler and I am not going to install one to build one half of the release with this toolchain and the other one with that. It is already a huge burden for me to create windows binaries at all (if it was just me, a "release" would be a tag in the GIT repo) and I think that issues like the midiproc stuff should be fixed in the code, not by some compiler magic that nobody is able to understand or even reproduce.

**Comment by JNechaevsky** [comment]
No blockers from my side. Just to ask you for some clarifications, please:

- You are not considering to implement #324 because of too big change of Chocolate <-> Crispy code? If so, it's quite clear and understanble. If not, what's wrong then?
- You have mentioned, that interpolating weapon bobbing is dangerous. After taking a brief look, I think it's not only dangerous, but will require an another `V_DrawPatch`-like function that will move pixels not by "half-of-sprite", but by "screen pixel"? Another notable thing is bobbing itself is hardly binded to player's movement. Moving trajectory itself seems to interpolated. Am I right? Could you please shed some light on this?

**Comment by fabiangreffrath** [comment]
> You are not considering to implement #324 because of too big change of Chocolate <-> Crispy code? 

Yes, I am not going to move that `enum` around.

> interpolating weapon bobbing is dangerous

In fact, it is not more dangerous than what we already do with the weapon sprite, e.g. centering during firing or squatting when landing after falling. But, because all this is already done in a very convulte dway to achieve demo sync, we would have to fiddle the bobbing interpolation into all of this code - and I simply have no intention to do so, at least not now...

**Comment by JNechaevsky** [comment]
Aha. Thanks! That's all I can say for now, because at the moment I'm out of ideas/suggestions completely, and just as usual, need some time for "refreshing". I hope 5.2 will be a Bomb, just take a look at the amount of things that's has been done!

**Comment by fabiangreffrath** [comment]
done

**Comment by JNechaevsky** [comment]
It's a greatest triumph, I have to say. Just take a look at the changelog, to the whole amount of efforts!

**Congratulations! And let's keep things rockin'!** :godmode:

_Ah yes, I have just a few suggestions already, inspired from Atari Jaguar. But not sure they are significant or useful enough for traditional Doom, or maybe I'm simply can't find suitable words to describe them properly. Anyways, not now. Later. :)_

**Comment by fabiangreffrath** [comment]
Thanks! :smile:
