### ISSUE TITLE
clipping glitch

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#327]
https://github.com/fabiangreffrath/crispy-doom/issues/324#issuecomment-408206789

Hovewer, while testing, I have noticed one odd bug. Please try to do following:

Start HoE and warp to MAP30.
Activate no clipping mode and go to the room with Icon of Sin.
Try to shoot it with with any weapon, except Rocket Launcher.

exclamation Both projectiles and missiles are seems to be flying through the head, and needles to say it's a not a vanilla behavior. Reverting oldleveltime changed does not fix this case, and I'm not sure why this is happening.

**Comment by JNechaevsky** [comment]
Bad news, Icon is non-solid for shooting even when level is started normally, i.e. without noclipping and normal walking. Testing map is attached (MAP01, two Icons): [sin.zip](https://github.com/fabiangreffrath/crispy-doom/files/2235352/sin.zip)

**Comment by fabiangreffrath** [comment]
Hm, I am not sure what you mean. In your WAD on MAP01 I see Romero's head on a stick which I can kill with the pistol. What's wrong with that?

**Comment by fabiangreffrath** [comment]
Are you sure you are working with a clean code copy? Does "git diff" show any changes?

**Comment by JNechaevsky** [comment]
Here we go. Setting "Vertical aiming" to "Direct" is causing a bug:

![](http://priscree.ru/img/710aa63f3b9edf.png)

**Comment by JNechaevsky** [comment]
...and it's seems to be because of `MT_BOSSBRAIN` height is 16 map units (`16*FRACUNIT`), while projectiles and missilies attack height is about +-40. This making a sense by the fact, it's not exactly a bug, because direct aiming is supposed to work this way, right? But it also requires a free look, which is disabled in my case.

Not sure what to suggest, but something, probably, should be done - it may be not obvious for someone. :\

As always, at your discretion.

**Comment by fabiangreffrath** [comment]
So, this is not the engine-breaking bug that it appeared to be.

Sure, I could add something like this to fix this
```
--- a/src/doom/p_map.c
+++ b/src/doom/p_map.c
@@ -1144,7 +1144,14 @@ boolean PTR_ShootTraverse (intercept_t* in)
                
     // check angles to see if the thing can be aimed at
     dist = FixedMul (attackrange, in->frac);
-    thingtopslope = FixedDiv (th->z+th->height - shootz , dist);
+    {
+    fixed_t height;
+    if (critical->freeaim == FREEAIM_DIRECT && th->height < 56*FRACUNIT)
+       height = 56*FRACUNIT;
+    else
+       height = th->height;
+    thingtopslope = FixedDiv (th->z+height - shootz , dist);
+    }
 
     if (thingtopslope < aimslope)
        return true;            // shot over the thing
```
but I am somehow reluctant to hard-code this, as nobody knows yet what further breakage this may cause and the same effect could be achieved by a simple DEH file.

Furthermore, it shows that some feature combinations simply don't make sense, like e.g. enabling direct aiming without the possibility to choose the vertical aiming direction. ;)

**Comment by fabiangreffrath** [comment]
And, you have revealed one important secret about Romero's head: Only the stick is vulnerable, the head itself is not! :wink:

**Comment by fabiangreffrath** [comment]
This should be fixed by https://github.com/fabiangreffrath/crispy-doom/commit/6cfe557765cf1e7afdd02e6fa8f937ed6d1acf9a

@JNechaevsky Could you please confirm that this is not an issue anymore and sorry to both of you and @Zodomaniac for mixing you up in the commit message. :grin:

**Comment by JNechaevsky** [comment]
@fabiangreffrath sure thing, this will be my plan for the evening. I just need remember what actually was happened here, can't remember what I did last summer. :frowning:

**Comment by fabiangreffrath** [comment]
It's all in the bug report. :wink:

**Comment by JNechaevsky** [comment]
I literally can't remember anything about this half of year ago issue, and it's same about https://github.com/fabiangreffrath/crispy-doom/issues/324 (although I remember that's initial suggestion, but not farther discussion). Hope it's not a progressive sclerosis. Creepy. :/

I'm a bit confused about direct aiming - now bullets are hitting whole height of Icon, while projectiles are not. Is it supposed to work this way?

- https://youtu.be/_nWCNNqchDE

_(need to tweak my screen recorder, there is an awful screen tearing for some unknown reason)_

**Comment by fabiangreffrath** [comment]
> I'm a bit confused about direct aiming - now bullets are hitting whole height of Icon, while projectiles are not. Is it supposed to work this way?

Ah, projectiles! I simply forgot the are affected as well. :man_facepalming:
