### ISSUE TITLE
Fix "Key pickup resets palette"

### ISSUE THREAD

**Issue by mfrancis95** [fabiangreffrath/crispy-doom#328]
[https://doomwiki.org/wiki/Key_pickup_resets_palette](https://doomwiki.org/wiki/Key_pickup_resets_palette)

Simply removing or commenting out [this line](https://github.com/fabiangreffrath/crispy-doom/blob/63a0cfd1f084f174b0c07cf7c37b97e57f7fbefb/src/doom/p_inter.c#L273) will fix it, for singleplayer at least.

**Comment by bradharding** [comment]
> Simply removing or commenting out this line will fix it.

Changing the `=` to `+=` would be better, otherwise the screen won't flash at all.

**Comment by fabiangreffrath** [comment]
This is really confusing. I also have no idea what the `netgame` check is for, but I am more with @bradharding about changing the `=` to `+=`.

**Comment by fabiangreffrath** [comment]
> I'm not sure what the significance of the netgame check is.

Ah, I think this is to prevent the key item from getting removed off the map in multiplayer games.
