### ISSUE TITLE
DEHACKED problem

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#330]
In the previous topic I was talking about a Dehacked patch fixing the chaingunner firing sound. I found it was compatible with Strain, and decided to make my own patch for Strain based on this. I quite like the gameplay modifications of Strain but hate the fact that its pistol start is in fact a fist start: initial supply of bullets is zero. I incorporated all the fixes in the following DEH patch:

```
Patch File for DeHackEd v3.0

Doom version = 19
Patch format = 6

Frame 418
Duration = 3

Pointer 234 (Frame 417)
Codep Frame = 185

Pointer 235 (Frame 418)
Codep Frame = 185

Misc 0
Initial Bullets = 10
Blue Armor Class = 3
BFG Cells/Shot = 3
```

I load the patch after Strain with a command line `start crispy-doom -merge strainfix.wad strain_jive.wad -deh zweapfix.deh -fast` (strainfix.wad is a wad with maps fixed for sourceports). The initial bullets number is still zero, why?

**Comment by fabiangreffrath** [comment]
This is because of the order in which DEHACKED patches are parsed:
https://github.com/chocolate-doom/chocolate-doom/blob/28e726147ae63442a5aeb99724b41d4ba7f0df3e/src/doom/d_main.c#L1513

That is. command line patches are loaded before PWAD patches, so the latter override the former.

**Comment by Zodomaniac** [comment]
Thank you) I will then make a WAD incorporating this deh patch, as I'm going to fix up some pistol and fists'prites for Strain
