### ISSUE TITLE
Allow Colored Blood without Colored Corpses

### ISSUE THREAD

**Issue by ice44** [fabiangreffrath/crispy-doom#331]
Would you mind adding back in the option to select Colored Blood without Colored Corpses in the settings? I had been using this setting and was surprised to see it completely removed.

**Comment by fabiangreffrath** [comment]
I provided some rationale here:
https://github.com/fabiangreffrath/crispy-doom/issues/311#issuecomment-386986441

**Comment by ice44** [comment]
Ok, thanks for the reply. Completely understand!
