### ISSUE TITLE
The slot of the first quick save/load of the game stays permanently until the game is shut down

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#332]
### Background

Version of Crispy Doom: Git daily build Sep 06, 2018

Operating System and version: Win 7

Game: Any

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: When I
1) launch game and first press F6/F9 to quick save/load the game and choose the slot X,
2) play for some time, then save/load a game to/from slot Y in a regular fashion, and
3) attempt a quick save/load, it will still ask me about quick saving/loading slot X though the last saved/loaded slot was Y.

Expected behavior: The quick save/load slot should change on every saving/loading game to the slot where the game was saved/loaded.

**Comment by fabiangreffrath** [comment]
You can reset the quicksave slot by doing "End Game" in the menu.

Nevertheless, I am not sure if quicksave should switch to the latest slot used for regular saving. I am sure there are users who use one dedicated slot for quicksaves (e.g. during intense phases) and another one for regular saves (e.g. at level starts).

**Comment by Zodomaniac** [comment]
OK, I think End Game resetting the quick save/load slot is enough. I agree with your rationale, let it stay as is.
