### ISSUE TITLE
Apply blue digits to megaarmor/health color if it goes beyond 200

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#333]
For example, in STRAIN the megaarmor gives 300 points, and not sure why exactly (dehacked or just no condition in the code for numbers >200), but the number is green.
![doom0007](https://user-images.githubusercontent.com/15119473/45158028-71d4c300-b1eb-11e8-811e-82c394f2e291.png)

**Comment by fabiangreffrath** [comment]
The armor widget is different in that it changes its color based on armor **type** (i.e. green or blue) instead of armor **amount**.

**Comment by Zodomaniac** [comment]
I know, but in STRAIN it's the megaarmor, just with modified amount, so shouldn't the digits be blue?
DeHackEd says 'Armor class = 3' IIRC.

**Comment by fabiangreffrath** [comment]
So, I need to check if `armortype >=2` instead of `armortype == 2` for the blue color. 

Please note that in your screenshot the armor widget isn't translated to green but instead left untouched. There are subtle differences in the green shades of digit '3' in the ammo widget and the armor one.

**Comment by Zodomaniac** [comment]
>Please note that in your screenshot the armor widget isn't translated to green but instead left untouched. There are subtle differences in the green shades of digit '3' in the ammo widget and the armor one.

Yes, the Crispified ammo widget is a bit darker. Here is the screenshot of the same gameplay situation from Chocolate Doom:
![doom03](https://user-images.githubusercontent.com/15119473/45220552-2851aa00-b2b7-11e8-8668-9e60884e28e4.png)
BTW, for some reason Chocolate Doom appears to be unable to load sprites from PWADs and the Dehacked when launched with `-merge`: `start chocolate-doom -merge strainfix.wad strain_jive.wad zostrafix.wad -deh cpos-bul.deh`
![doom05](https://user-images.githubusercontent.com/15119473/45220777-0573c580-b2b8-11e8-8543-4cb96b1a1be7.png)
