### ISSUE TITLE
Implement brightmaps for SW2SATYR, SW2LION and SW2GARG

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#334]
Implement brightmaps for textures: `SW2SATYR`, `SW2LION` and `SW2GARG`. In fact, it's one brightmap for all three textures:

```
static byte brighttan[256] =
{
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
	1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
	0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};
```

Note: all three textures are existing in all the games: D1, D2, Plutonia and TNT, but not in shareware.
Initial discussion and screen shot examples: https://github.com/JNechaevsky/russian-doom/issues/79
Testing map (MAP01): [brighttan.zip](https://github.com/fabiangreffrath/crispy-doom/files/2412716/brighttan.zip)

Not sure about the "tan", so please feel free to name it as you wish.

_Good thing I'm still kicking, let it be suggestion №95 please._

**Comment by Zodomaniac** [comment]
@JNechaevsky Are the switches on the test map permanently 'on'? I cannot use them.

**Comment by JNechaevsky** [comment]
Nothing to lit up on such switches (SW1's):

![sw1](https://user-images.githubusercontent.com/21193394/46026972-4dd31600-c0f5-11e8-8c55-c8a0a365f559.png)
