### ISSUE TITLE
Proportional video scaling (16x10) found in Doom Retro, looking forward to in Crispy

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#335]
I'm bringing this back because Doom Retro has the `vid_widescreen` console variable to choose between either 4:3 or 16:10 (which is proportional to internal 320x200, 640x400) aspect ratio.
For instance, powerup spheres, imp/cacodemon fireballs, cacodemons and pain elementals actually look spherical in 16:10 aspect ratio.

I'd suggest to achieve this by replacing 'Force correct aspect ratio' in Setup->Configure Display->Advanced  with three sub-items of which only can be enabled:
1) 'Aspect ratio not enforced' (stretching to full screen if the latter is enabled, and suggesting 16x10 aspect ratios of windows if Full Screen is off)
2) 'Proportional scaling (16:10)'
3) 'CRT aspect ratio (4:3)' as it was enforced on old CRT monitors, the default value.

**Comment by fabiangreffrath** [comment]
So, what you want to achieve is not only 320x240 ratio or any other ratio else (as it is now with Aspect Ratio Correction), but either 320x240 ratio or 320x200 ratio or any other ratio else. Right?

**Comment by Zodomaniac** [comment]
Yes, you got me right)

**Comment by fabiangreffrath** [comment]
The code change is trivial, but I am afraid this will be another "secret" config option, i.e. there won't be a menu item for this (not even in the setup tool).

**Comment by Zodomaniac** [comment]
May I suggest to also add the 3:2 aspect ratio? Kinda average between 4:3 and 16:10.

**Comment by fabiangreffrath** [comment]
But that's neither the original square nor the original VGA aspect ratio, so it is not right in any regard!

**Comment by fabiangreffrath** [comment]
Also, you could turn the correction "off" and scale your game window to whatever aspect ratio you like.
