### ISSUE TITLE
Option for extending autoaim pitch limit to -90...+90 degrees?

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#336]
I have run into a situation that clearly shows that autoaim pitch angle is limited.
By the projected crosshair position and highlight you can see target is acquired here
![doom0017](https://user-images.githubusercontent.com/15119473/46082376-a06d0a80-c1a7-11e8-9b3f-0a93a6152fc4.png)
but not here
![doom0023](https://user-images.githubusercontent.com/15119473/46082405-b37fda80-c1a7-11e8-9660-d410ec000baa.png)
though the absolute value of the FOV center pitch is less than 90 degrees, limited in Crispy for some reason (I'm curious why exactly?)
P.S. Of course, if it's implemented, it should be an item in the Physical sub-menu as it would be a non-Vanilla aiming mechanic, shadowed if aiming is set to Direct (i.e. autoaim is disabled).

**Comment by fabiangreffrath** [comment]
The maximum view angles are taken unmodified from Heretic, where indeed the entire vertical view implementation has been taken from. Some experimenting has shown that at higher angles, textures and sprites get distorted in absurd ways. I think @JNechaevsky has once recorded a video that shows what happens if you extend the viewing angles more and more.

**Comment by Zodomaniac** [comment]
OK, I got your point on view angles, but what about the autoaim angles? I expected to hit that imp in the second screenshot but the autoaim didn't lock on it. So why not introduce 'Unlimited autoaim angles' (i.e. rom -90 to +90 degrees) in Physical sub-menu?

**Comment by fabiangreffrath** [comment]
Autoaim is already independent of any vertical angle, but please note that projectiles are not emitted from your viewheight, but a bit below:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_map.c#L1210

So, the sheer fact that you can see the enemy does not mean that you can reach it with a weapon from the very same position.

**Comment by Zodomaniac** [comment]
Thank you for the explanation)
