### ISSUE TITLE
Highlight revealed secrets with purple on the automap

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#338]
The excellent Crispy extended automap colorization scheme lacks just one small feature: colorizing revealed secret sectors with e.g. purple/magenta like in GZDoom.
![screenshot_doom_20181009_140402](https://user-images.githubusercontent.com/15119473/46675399-f51c7680-cbe6-11e8-838c-7697892d5703.png)
I think it would be logical enough to highlight the the revealed secrets in automap when two conditions are met:
1) the player enables Extended Automap Colors to know about the linedef types seen on the map and
2) wants to get notified about the revealed secrets, enabling Show Revealed Secrets.

In case Show Revealed Secrets is off, treat the outlines of revealed secret sectors just like any other linedefs in either extended or traditional coloring, depending on which one is chosen. 

Another option is a separate, additional 'Map revealed secrets' (where map is a verb) Navigational option, independent of map colorization and sound/text secret reveal notifier.

**Comment by fabiangreffrath** [comment]
I don't see any sense in highlighting already revealed secrets. First, once they are revealed, they aren't actually secret anymore. Second, assume you have a map with 10 secrets, but you have only found 9 so far. Now you open the Automap to find the one you are missing, but it actually shows 10 - so which is the one you are missing?

**Comment by Zodomaniac** [comment]
Let me give you example. The sector to the left of the player can be seen but not triggered from the current position (it's a wall, you have to teleport on top of it). I think there should be some difference in displaying this sector before and after triggering it as a secret.
![doom0009](https://user-images.githubusercontent.com/15119473/46721946-03b56d00-cc7d-11e8-8a90-13d1fc2a9931.png)

**Comment by fabiangreffrath** [comment]
Hm, why isn't the sector colored in purple in your screenshot if you haven't revealed this secret yet?

**Comment by Zodomaniac** [comment]
The previous screenshot was from GZDoom, and the last one is from Crispy. I mean that there should be an option for secret sectors to be outlined in purple when revealed.

**Comment by Zodomaniac** [comment]
I suggest purple for revealed secret sectors. In Crispy it's not implemented yet, that's why currently the sector won't be purple even if triggered.

**Comment by fabiangreffrath** [comment]
Sorry, I was a bit confused. Secret sectors are only colored purple if you use the IDDT cheat. So, you suggest to use the purple color for revealed secret sectors without the IDDT cheat?

**Comment by Zodomaniac** [comment]
Yeah, right.

**Comment by fabiangreffrath** [comment]
The problem is that a secret sector - once revealed - does literally lose its special status, so I would have to keep track of "was once special". :_/

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_spec.c#L1147

**Comment by Zodomaniac** [comment]
Any chance of implementing this in 5.5?

**Comment by fabiangreffrath** [comment]
I don't even like the idea of the purple color switching meanings (revealed secret vs. unrevealed secret) whether IDDT is active or not...

**Comment by Zodomaniac** [comment]
Maybe then show revealed secrets as some sort of bright orange?

**Comment by fabiangreffrath** [comment]
Doom palette colors only, please!

I am currently using 252 for secret sectors. I could use a darker one like 254 for unrevealed secrets and a brighter one like 251 for revealed ones -- or vice versa. This is confusing even now!

**Comment by fabiangreffrath** [comment]
So, here is an approach that draws lines surrounding a revealed secret in a darker purple. It is not yet safe across savegames, this would need some code in `doom/p_extsaveg.c`.

```
diff --git a/src/doom/am_map.c b/src/doom/am_map.c
index 4454a913..b5648186 100644
--- a/src/doom/am_map.c
+++ b/src/doom/am_map.c
@@ -79,6 +79,7 @@
 #define THINGCOLORS	GREENS
 #define THINGRANGE	GREENRANGE
 #define SECRETWALLCOLORS (crispy->extautomap ? 252 : WALLCOLORS) // [crispy] purple
+#define SECRETWALLCOLORS2 (crispy->extautomap ? 254 : WALLCOLORS) // [crispy] darker purple
 #define SECRETWALLRANGE WALLRANGE
 #define GRIDCOLORS	(GRAYS + GRAYSRANGE/2)
 #define GRIDRANGE	0
@@ -1352,8 +1353,8 @@ void AM_drawWalls(void)
 	    {
 		// [crispy] draw 1S secret sector boundaries in purple
 		if (crispy->extautomap &&
-		    cheating && (lines[i].frontsector->special == 9))
-		    AM_drawMline(&l, SECRETWALLCOLORS);
+		    cheating && (lines[i].frontsector->special == 9 || lines[i].frontsector->oldspecial == 9))
+		    AM_drawMline(&l, (lines[i].frontsector->oldspecial == 9) ? SECRETWALLCOLORS2 : SECRETWALLCOLORS);
 		else
 		AM_drawMline(&l, WALLCOLORS+lightlev);
 	    }
@@ -1375,6 +1376,12 @@ void AM_drawWalls(void)
 		    else AM_drawMline(&l, WALLCOLORS+lightlev);
 		}
 		// [crispy] draw 2S secret sector boundaries in purple
+		else if (crispy->extautomap && cheating &&
+		    (lines[i].backsector->oldspecial == 9 ||
+		    lines[i].frontsector->oldspecial == 9))
+		{
+		    AM_drawMline(&l, SECRETWALLCOLORS2);
+		}
 		else if (crispy->extautomap && cheating &&
 		    (lines[i].backsector->special == 9 ||
 		    lines[i].frontsector->special == 9))
diff --git a/src/doom/p_spec.c b/src/doom/p_spec.c
index 05d4106d..d1f47756 100644
--- a/src/doom/p_spec.c
+++ b/src/doom/p_spec.c
@@ -1144,6 +1144,7 @@ void P_PlayerInSpecialSector (player_t* player)
 	        S_StartSound(NULL, sfx_id);
 	}
 	player->secretcount++;
+	sector->oldspecial = sector->special;
 	sector->special = 0;
 	break;
 			
diff --git a/src/doom/r_defs.h b/src/doom/r_defs.h
index 2527f10d..7f01aa06 100644
--- a/src/doom/r_defs.h
+++ b/src/doom/r_defs.h
@@ -108,6 +108,7 @@ typedef	struct
     short	floorpic;
     short	ceilingpic;
     short	lightlevel;
+    short	oldspecial;
     short	special;
     short	tag;

```

And this is how it looks:

![doom0000](https://user-images.githubusercontent.com/6449237/52520078-473cd980-2c65-11e9-89fb-f971b1c0b3a9.png)

**Comment by Zodomaniac** [comment]
@fabiangreffrath  If 'Doom palette colors only', I think revealed secrets should be colored with the same white as the exit line, one won't mix those up because secrets are sectors and the exit trigger is a line.

**Comment by fabiangreffrath** [comment]
Of course white would be ambigious. The human brain reads the map by colors and not by context. Also, it is much too striking for a sector that isn't any special anymore, apart from the fact that it was once secret before it was discovered. And light-blue just feels odd.

Should I ever apply this. the not-so-secret-anymore sectors need to be unobtrusive and harmonically align with the other non-secret sectors.

**Comment by Zodomaniac** [comment]
>Should I ever apply this. the not-so-secret-anymore sectors need to be unobtrusive and harmonically align with the other non-secret sectors.

What about bright green, 114? It's different enough from darker green used for teleporter lines and all the regular line colors (see screenshot).
![doom0001](https://user-images.githubusercontent.com/15119473/52555320-6ae55880-2dfa-11e9-8f01-75cf47a63eb8.png)

**Comment by fabiangreffrath** [comment]
That would still be a signal color for a sector that isn't special anymore.

**Comment by Zodomaniac** [comment]
Yes, but why not store the visited secret like GZDoom does? The revealed secrets could also be stored in extended savegame format.

**Comment by fabiangreffrath** [comment]
Sure, that's the plan. My problem is the way we present discovered secrets in the map. I don't want to grant them any attention at all.

**Comment by fabiangreffrath** [comment]
Now we need a Changelog for 5.5!

**Comment by fabiangreffrath** [comment]
Hm, this should probably only be green if "show revealed secrets" is enabled?

**Comment by Zodomaniac** [comment]
> Hm, this should probably only be green if "show revealed secrets" is enabled?

Maybe. But then it should be toggled on and off correctly for revealed secrets while toggling the variable "show revealed secrets".

**Comment by fabiangreffrath** [comment]
> Maybe. But then it should be toggled on and off correctly for revealed secrets while toggling the variable "show revealed secrets".

Yes, this is exactly what I mean!

Another thought: The "A Secret Is Revealed" message is printed in yellow/golden letters, but the revealed secret sectors are rendered in green on the map. Have you considered (or tried out) how the sectors would look if rendered in some kind of yellow/golden tone? Like Doom palette's 160 or 231 or 249?

> The upcoming week I'll do that, I guess)

Cool, looking forward to getting this release done.

**Comment by Zodomaniac** [comment]
>Another thought: The "A Secret Is Revealed" message is printed in yellow/golden letters, but the revealed secret sectors are rendered in green on the map. Have you considered (or tried out) how the sectors would look if rendered in some kind of yellow/golden tone? Like Doom palette's 160 or 231 or 249?

I've examined the golden colors. They have to be not too similar to the yellow key door, so I suggest 162.
![doom0000](https://user-images.githubusercontent.com/15119473/53321892-ccbdbc00-38ea-11e9-9210-d06a234b4994.png)

**Comment by fabiangreffrath** [comment]
Yellow keyed doors are drawn with color 231, actually. When you say you suggest color 162, do you mean you suggest it over 112, or is bright green still your preferred choise?

**Comment by Zodomaniac** [comment]
Yes, I think it should be changed to 162 from 112 to be consistent with the secret reveal message.

**Comment by fabiangreffrath** [comment]
If you apply the "gold" color translation table used to colorize the "secret revealed" message to the wall colors currently used in the Automap, the following happens:
```
wall 23 163
fdwall 55 231
cdwall 215 231
secret 252 163
revealed 112 231
```

So, they are either translated to 163 (regular walls and purple secret walls) or 231 (orange and beige walls and current bright green revealed secret walls), but never to 162. Since 231 is already reserved for yellow-keyed doors, I suggest to use 163 instead to keep a harmonic color composition.

**Comment by Zodomaniac** [comment]
OK, let it be 163.

**Comment by fabiangreffrath** [comment]
On the other hand, 163 is a bit too shy...

**Comment by fabiangreffrath** [comment]
This appears to be the most complicated design decision I ever had to take for this port. :dizzy_face:

**Comment by Zodomaniac** [comment]
Well, we have seen what bright green looks like, so maybe let's try 163 and revert it if it's too dark, but...
Why cannot we just replace 112 with 162?

**Comment by Zodomaniac** [comment]
Like
`wall 23 163
fdwall 55 231
cdwall 215 231
secret 252 163
revealed 162 231`

**Comment by fabiangreffrath** [comment]
> I still don't get why cannot we just use 162 anstead of 112?

Sure we can, sorry. I seem to have some kind of symmetry OCD, especially when numbers are concerned...
