### ISSUE TITLE
[Suggestion] SSG (only) in not indicated on arms widget

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#343]
This is an interesting case. Please try to do this:

- Start Crispy normally and warp to `MAP18` (or any map with SSG)
- Do not pickup standard shotgun
- Pickup SSG and note that it isn't indicated on HUD's arms widget.

How it actually looking:

![no_3](https://user-images.githubusercontent.com/21193394/47618400-c1e14f00-dae3-11e8-8571-67956d1722ef.png)

I have only SSG (i.e. no standard shotgun), and number `3` is not yellow. Gosh, so many thing comes from MAP18!

_Suggestion №96, please!_

**Comment by fabiangreffrath** [comment]
Also, the widgets only draw anything if the value they represent has been changed since the last call.

**Comment by JNechaevsky** [comment]
:frowning: I see... Another problem - internal SSG number is `9`.
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/doomdef.h#L108

**Comment by bradharding** [comment]
Hey guys. Check out the `shotguns` bool on lines 1309 and 1528 in https://github.com/bradharding/doomretro/blob/master/src/st_stuff.c.

**Comment by fabiangreffrath** [comment]
@JNechaevsky That's the smallest problem. :wink: 
@bradharding Combining both `plyr->weaponowned[]` values into one variable looks like a good idea, maybe I'll do it that way.

**Comment by JNechaevsky** [comment]
Awesome! Thank you very much, colleagues!

**Comment by Zodomaniac** [comment]
P.S. It was easier to get the SSG without the regular shotgun by warping to MAP07-Dead Simple)
