### ISSUE TITLE
Give weapons properly by using IDKFA and IDFA

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#344]
The idea is to give weapons properly:

1. Don't give SSG, Plasmagun and BFG in `shareware`.
2. Give SSG only in `commercial`.

This should not break any compatibility, since non-shareware weapons are not available to choose by using controls, but in fact, according to the HUD's arms widget, they are still available.

Working approach: a bit too strict and huge, but working fine: https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/st_stuff.c#L606. Not sure about _real_ necessity of giving fist and pistol, but just for sure...

- [Screenshot ](https://user-images.githubusercontent.com/21193394/47991464-41ca7300-e0fb-11e8-90e1-b06336bd849a.png)

Another possible additional approach is to play around with `&w_arms` widget by reducing `i<6` to `i<4` (in short words), to disable indication of Plasmagun and BFG completely in Shareware:

- [Screenshot](https://user-images.githubusercontent.com/21193394/47991613-bac9ca80-e0fb-11e8-985c-44db8d0c67f9.png)

I haven't done this, because I prefer to don't have an empty cells, and leave 6 and 7 number just colored gray. For Crispy you should decide by yourself of course.

_Suggestion №97!_

**Comment by Zodomaniac** [comment]
I don't get it why give SSG only in commercial version and not give pump sg.
