### ISSUE TITLE
Timidity music volume is too high

### ISSUE THREAD

**Issue by FistsAkimbo** [fabiangreffrath/crispy-doom#345]
Timidity plays fine with crispy doom, but the volume is too high even on setting 1, easily overpowering the game SFX volume.

I'm not entirely sure if there even is any means to further tweak the timidity volume, to be clear. I tried to raise the game SFX beyond 15, but crispy prints a windowed message saying more or less "no." So I'm at a loss as to how to balance these two volumes more tastefully. I really prefer timidity over OPL2/3. I also tried to change the music volume value (which does work, to clarify, just too loud) a decimal, thinking it would use the specified value in a fashion similar to (G)ZDoom, but it lopped off the decimal making it a clean 0. Any help on this would be greatly appreciated, thank you

**Comment by fabiangreffrath** [comment]
Please try moving `crispy-midiproc.exe` from the `unsup` directory next to `crispy-doom.exe`.

**Comment by Zodomaniac** [comment]
@FistsAkimbo or use the Music Pack http://www.greffrath.com/~fabian/crispy-doom-music-pack_5.1.zip either specifying the soundfont with the following command in your launching BAT file:
`set SDL_SOUNDFONTS=TimGM6mb.sf2`
or even downloading the real-tone WAD with music played with real instruments:
https://www.moddb.com/groups/doomdb/addons/doom-metal-vol4-resampled-to-441-khz

**Comment by fabiangreffrath** [comment]
So, did it help to have `crispy-midiproc.exe` in the same directory as `crispy-doom.exe`?

**Comment by Zodomaniac** [comment]
@FistsAkimbo I use BAT files to launch Crispy with every specific set of WADs and include this command, I don't know how to make it work otherwise.
