### ISSUE TITLE
[Idea] Implement single color visplane rendering

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#346]
Initially, the Idea comes from Doom Alpha builds, where it was possible to choose rendering visplanes as single color in real time. Back in 1993 it was good for rendering performance and [SNES](https://www.youtube.com/watch?v=zGIye6Bkxvw) console port is using this idea (but it's a different engine, though). Just try to run Alpha [0.3](https://doomwiki.org/wiki/Doom_v0.3) or [0.4](https://doomwiki.org/wiki/Doom_v0.4) and press `C` in the level to disable visplane textures, and press `Z` to show them back.

Nowadays, it's really not necessary to do this on modern CPUs, especially in capped 60/70 fps, but after some `-timedemo` benchmarks on RD version for DOS, I was pleasantly surprised by the fact in increasing average fps. It's higher, meaning that this approach is actually works.

Okay, now about the code. I'm pretty sure that my approach is totally different from original id's, but it's looking same in the game. Here's an example, please feel free to improve it.

- https://gist.github.com/JNechaevsky/08b67569cdd7d49ef4dfd2bb2624ee1b
_note: GCC will print a warning in case of using a `NULL` instead of `0`_

The result as follows: [screenshot](https://user-images.githubusercontent.com/21193394/48078634-e67faa00-e1fa-11e8-85b1-9223e8732d11.png). Diminished lighting is working, but it's barely notable on standard palette. Disabled diminished lighting for visplanes makes overall picture looking bad.

Have to agree, it can be implemented as a cheat code along with `GOOBERS`, and named like... `IDNOFLATS`? No idea for the moment.

_Please consider this as a suggestion №98._
_Initial issue: https://github.com/JNechaevsky/russian-doom/issues/92_
___________

But! Before move on, I would like to offer a little discussion about what else we can do in this aspects. Couple of ideas comes today, we can do something similar:

- Optionally remove calculation of diminished lighting by leaving only sector's itself brightness. Probably will also save few bits of performance, but it have to be done for both visplanes and walls/segments.
- **Don't** do same for walls. I.e. for common walls it could be okay, but there two types of walls which must not be touched: switches and masked textures (but mask itself is calculated separately by Killough tutti-frutti fix?).
- **Don't** do same for sprites. The shape of the sprite is calculated separately, but drawing sprite with single color will make it looking like paper cutted doll.
- Maybe other ideas?

**Comment by fabiangreffrath** [comment]
So, now that we have working code ready, the main question remains: What could we do with it? :grin:

**Comment by JNechaevsky** [comment]
Hm. In DOS version this is not a question at all, it's a cmd line parameter `-noflats`, just like others: `-nosfx`, `-nomonsters`, `-nomus`... But in DOS version it's a colossal optimization, not just a toy to play around.

Until there are no others optimizations, I think this can be a cheat code or hidden variable in config file. In case of having other things like disabling of diminished lighting, maybe it is wort to add whole new section in Crispness menu like... "Rendering optimization" or "Rendering (experimental)"? Then again, maybe not.

**Comment by fabiangreffrath** [comment]
No, I am sure this won't get into the menu. This will either be a command line parameter or part of a cheat/easter egg.

**Comment by JNechaevsky** [comment]
Allright, I'll suggest following path then:

- I will try to implement `-nolights` variable for disabling diminished lights calculation. It does not seems to very easy, so it probably will take a few evenings.
  - If I will not succeed, it's still a question: leave `noflats` as a cheat code and/or command line parameter. Sorry, really no idea what to suggest for you.
  - If I will succeed and you'll like the idea && approach, you can do same in Crispy, and obviously both features should a command line parameters. 

Bah, but again, maybe not! DOS is damn good, but no one will bring us back into 1993, where such features were critically necessary. I still perfectly remember how the game was running in i386 with 20 MB hard drive and 16 MB RAM, and especially in coop mode, while I was playing with my father by null-modem cable, which he made by himself.

Maybe it will be even better to calm down a bit and pause this issue for short time, until we will not have ultimately one idea of how to use it. At least, we have the code, and it's working perfectly fine.

**Comment by JNechaevsky** [comment]
Finally I'm ready to provide a clear decision. If we a speaking about optimization, it should be a cmd line parameter or config variable. If we a speaking about this tick just as a fun thing like `GOOBERS`, then yes, it should be a cheat code.

The point of no return: it is pretty clear, that on modern CPUs it's a questionable optimization, especially on Windows/Linux binary. And since Crispy is a Windows/Linux port, this trick is not optimization at all. To get a <60 fps, it is necessary to have huge and wide open space, just like on Nova MAP31. Yep, on my Intel Core i3-4160 @ 3.60 GHz I have about 36-42 fps there. But normally, game is running fine even on potato like Intel Atom of some kind @ 1.5 GHz (can't remember exactly, but still have it - it's a... oh god, fourth notebook I've totally forgot about!).

In case one day you will decide to make some options like returning some pure vanilla aspects like flat distortion and non-matching visplanes on different light levels, then yes, this feature deserves and separate option just like others. But until then, let it be a cheat code like `IDNOFLATS` or something like this.

As about turning `RANGECHECK` into a variable - I think it should be a separate suggestion, I'm already gone too far from initial idea in this issue. But before, I need to make some proper and longer tests of timedemo and simple fps checking. If there will no be any real benefit, better keep it to have a proper error messages instead of "segmentation fault".

**Comment by JNechaevsky** [comment]
How about this: type `goobers` once to activate Wolf3D mode, type `goobers` again to disable visplane textures.

About `RANGECHECK`. I've finally made some runs on Ultimate Doom, looks likes disabling it does not gives _any_ benefits. Average fps results are mostly same in all four demos. Let's aband the idea of turning `RANGECHECK` into a variable.

**Comment by fabiangreffrath** [comment]
I still like the idea of this becoming part of the GOOBERS cheat and getting reset when loading a new map.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/5001ac6333d581141e10c426395226c9fc8595ac
