### ISSUE TITLE
[Idea] I_Error messages for errors can be more informative

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#349]
The idea is to review and make `I_Error` messages for errors more informative. For example, if we have a `Bad V_DrawPatch`, we can indicate which exactly patch is making a problem. In `R_MapPlane` we can "slightly deobfuscate" message: `"R_MapPlane: 1, 2 at 3"`, to `"R_MapPlane: x1: 1, x2: 2 at y: 3"`, an so on.

There are couple of other examples, but before reviewing and making a list, I propose to determine - is it interesting at all?

_Suggestion №99_

**Comment by fabiangreffrath** [comment]
So, now that you've got @fragglet's approval in https://github.com/chocolate-doom/chocolate-doom/issues/1102, I guess this has turned into a cal for a pull request there. ;)

**Comment by JNechaevsky** [comment]
Excellent! By running a little bit forward, I'll probably will need some help, mostly with `%i` variables in the messages. I think it's worth to discuss some things before making any PR, and making a full list will take some time, but better to start from Doom, rather than doing this for all four games. 

Will provide the list with suggested changes in the Saturday. Hopefully. For God's sake, making thingы like this on Friday's evening is certainly bad idea!

**Comment by fabiangreffrath** [comment]
Thanks for wrapping up your sleeves! Take your time, there is certainly no pressure behind this. :wink:
