### ISSUE TITLE
Fix/Toggle for Mancubus fireball clipping?

### ISSUE THREAD

**Issue by FistsAkimbo** [fabiangreffrath/crispy-doom#350]
I know chocolate doom's focus was for keeping a lot of vanilla's gameplay bugs intact, but this one is genuinely annoying. Would there be any chance of Crispy adding some means of avoiding this bug?

**Comment by mfrancis95** [comment]
This would break demos that feature the fireball clipping.

**Comment by fabiangreffrath** [comment]
Indeed, this is impossible to fix without breaking demo compatibility, sorry.
