### ISSUE TITLE
Using PLAYPAL and COLORMAP lump in high color mode

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#351]
As an anniversary suggestion, I would like to suggest something crazy. Couple of months ago we was having a short discussion about PLAYPAL and other stuff in high color rendering, and I think I have something to say, maybe as raw idea but... Better to say it, instead of holding it into the coffin. Maybe it will be helpful a bit, maybe totally useless, I really don't know.

I suppose that both PLAYPAL and COLORMAP is still can be used normally in high color rendering. I'll try to be consistent.

### PLAYPAL is still needed

Yes, `PLAYPAL` is still absolutely necessary, but in exactly two instances:

1. One for game world rendering (highlighted green).
2. One for the rest of everything: menus, status bar, HUD, fonts and etc (highlighted red).

We need to know the colors to operate with.

Visually:
![colordef](https://user-images.githubusercontent.com/21193394/48220661-f89b4d00-e3a0-11e8-8563-56c538a8237f.png)

Instance №2 never changes it's brightness, so using a static 256 colors will be enough.
Instance №1, though, should use more-than high color mode of 917504 colors. Why not 65536 colors? It's simple: 256 colors * 256 brightness tables * 14 palettes inside PLAYPAL. Usage can be implemented by this scheme:

* Table №1: standard colors, standard brightness of each color
* Table №2: standard colors, brightness -1 of each color
* ...Table №256: standard colors, brightness -256 of each color

The code from Hexen's fading in/out may become handy for decreasing brightness:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/hexen/f_finale.c#L243

### Diminished lighting

Probably will not require _much_ additional work for smoothed mode, since there are already 1024 possible levels instead of standard 16.

### Determining sector brightness

Probably can be done this way:

* Sector brightness 192: ok, use table №192
* Sector brightness 32: ok, use table №32

### Accounting different palettes in PLAYPAL

Must be done for keeping compatibility, but brightness calculation should be same for all of them. For example, we still can have a radiation palette but with 65536 colors: 1 rad pal * 256 colors * 256 brightness tables.

### Ah yes, brightness tables

Using a prebuilt LUT for brightness instead of calculation every tic might be a good idea, but from another side, instead of writing huge table it can be generated while startup and kept in RAM.

Approximate size is: 768 bytes of one pal * 14 pals total * 256 tables = 2752512 bytes = 2.625 megabyes

### COLORMAP is still needed

Mostly for two things:

1. To align initial PLAYPAL colors (but not light levels). We only need first level.
2. To keep possibly custom INVUL effect.

### Brightmaps

Should work fine since we are still using PLAYPAL colors.

### Optionality

Better don't ask me. Good thing that there are four functions for determining diminished lighting:

1. For walls (`R_StoreWallRange`)
2. For masked textures (`R_RenderMaskedSegRange`)
3. For floors (`R_DrawSpan`)
4. For sprites (`R_ProjectSprite`)

### Reefs

Can't imagine at the moment. But the first real reef is amount of work of implementation.

_Suggestion №:100:_

**Comment by fabiangreffrath** [comment]
Well, first, congratulations for the 100th suggestion you sent to me within the previous years! That's really a respectable contribution, even if not all of them could get implemented in the end. ;)

Regarding this request, sorry, but I am not sure I fully understand it.

What you suggest here actually sounds more or less like the true-color rendering implementation that I have ready literally for years in a separate branch. In this approach the COLORMAP lump changes roles: From a list of indices into the PLAYPAL lump to a list of actual RGB values.

Is this what you mean?

**Comment by JNechaevsky** [comment]
Exactly this. :open_mouth: 

For some reason I was sure that something is not working properly. Oh well, it's sad to know that nothing useful I can suggest here, but I'm really happy to know that I have build your true color approach (well, roughly speaking, of course) inside my head without looking into your code!

Anyways, what is situation with `hicol` branch? Is it working? What's the plans?

_P.S. And thank you for kind words! It's still a mystery how ideas sometimes coming from nowhere, or by simple walking by circles on MAP18 . On some days it is simply impossible to come up with anything, and frankly speaking it feels awful and painful, something like... "creative impotence" (excuse for such a word). But hey, I'm speaking not about sadness! Next aim: another 100 suggestions!_

**Comment by fabiangreffrath** [comment]
> Anyways, what is situation with hicol branch? Is it working? What's the plans?

My objections expressed here still apply: https://github.com/fabiangreffrath/crispy-doom/issues/57#issuecomment-405182541

**Comment by JNechaevsky** [comment]
That's it! Broken non-Doom games is out of question, but please, explain a little bit wider, why non-standard palettes will be broken? Because only first one PLAYPAL lump is operational/accounted, right?

**Comment by JNechaevsky** [comment]
Got it. So the main problem is _reproducing_ tinting effects, instead of taking non-first palette as a basic palette for post-processing? Hard to explain with bare words, but i'll try.

I specifically was talking about decreasing brightness value. Try to imagine: the first of 14 available PLAYPAL palettes is a basis. These colors are in maximum needed brightness, which can be decreased by the code (see Hexen's fading). But, when palette changes for any kind of effect, let be other PLAYPAL palette be a basis, and that is all what is necessary for game world rendering.

However, I seems to miscount overall amount of colors per one palette:
* 256 colors * 256 possible brightness level * 256 combinations for each pixel = 16,777,216 possible colors per one palette in PLAYPAOL. Looks likes it's a high, not a true color then.

Pfff, I'm afraid I'm going to astral again. Maybe I should record you a video with visual explanation of what the heck I have in my mind. =\

**Comment by fabiangreffrath** [comment]
Sure, I could repeat the procedure for all 14 palettes and switch to an effect palette on-the-fly - but this would only apply to graphics which are rendered during the next frame, i.e. only the game scene. All the static graphics like the status bar, bezel and menu would remain unchanged. 

I would have to force-redraw them during each palette change - and that's quite alot if you go through a massive item pick-up or pain sequence.

**Comment by JNechaevsky** [comment]
Phew, glad you understand me, thanks! Maybe it's not very massive at all, HUD elements as well as other non-game scene elements don't have a necessity for changing brightness or have a post-rendering. They can be always in full (or same) brightness, using only values/colors from appropriate palette number. Or I'm wrong here?

**Comment by fabiangreffrath** [comment]
Most of this is already implemented in the "--enable-truecolor" code path. The details could be ironed out if we ever decide to make this the default - which is unlikely currently.
