### ISSUE TITLE
Fix Doomguy in casting sequence

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#352]
The problem is: Doomguy ("Our Hero") have missing frames in casting sequence and thus, there is not SSG firing sound. Take a look in the code, it should be played: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/f_finale.c#L476

Replacing `case S_PLAY_ATK1` to `case S_PLAY_ATK2` seems to solve only half of problem, another problem is - `S_PLAY_ATK2` is not appearing at all. Something have to be done here: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/f_finale.c#L459

_Suggestion №101_
_Initial discussion: https://github.com/JNechaevsky/yaguar-doom/commit/91bbf35f8215c71bf0e9137a0270775663978268#r31342103_

**Comment by fabiangreffrath** [comment]
```
	if (!castdeath && caststate == &states[S_PLAY_ATK1])
	    goto stopattack;	// Oh, gross hack!
```

Hm, this tells us that if the current state is `S_PLAY_ATK1`, it stops proceeding to `->nextstate` (which would be `S_PLAY`) and falls back to `->seestate` instead (which is `S_PLAY_RUN1`). So, it doesn't even have a chance to change into `S_PLAY_ATK2` state, because this isn't `->missilestate` nor `->nextstate` for any other state.

**Comment by fabiangreffrath** [comment]
Hm, it seems that Doomguy is merely aiming, but not actually shooting, in the cast sequence.

So, either we declare this a non-bug, because when he isn't shooting, there shouldn't be any sound either - or we fix the shooting sequence as well.

**Comment by fabiangreffrath** [comment]
I guess, this its it...
```
--- a/src/doom/f_finale.c
+++ b/src/doom/f_finale.c
@@ -456,8 +456,11 @@ void F_CastTicker (void)
     else
     {
        // just advance to next state in animation
+       // [crispy] fix Doomguy in casting sequence
+       /*
        if (!castdeath && caststate == &states[S_PLAY_ATK1])
            goto stopattack;    // Oh, gross hack!
+       */
        // [crispy] Allow A_RandomJump() in deaths in cast sequence
        if (caststate->action.acp1 == A_RandomJump && Crispy_Random() < caststate->misc2)
        {
@@ -465,6 +468,13 @@ void F_CastTicker (void)
        }
        else
        {
+       // [crispy] fix Doomguy in casting sequence
+       if (!castdeath && caststate == &states[S_PLAY_ATK1])
+           st = S_PLAY_ATK2;
+       else
+       if (!castdeath && caststate == &states[S_PLAY_ATK2])
+           goto stopattack;    // Oh, gross hack!
+       else
        st = caststate->nextstate;
        }
        caststate = &states[st];
@@ -473,7 +483,7 @@ void F_CastTicker (void)
        // sound hacks....
        switch (st)
        {
-         case S_PLAY_ATK1:     sfx = sfx_dshtgn; break;
+         case S_PLAY_ATK2:     sfx = sfx_dshtgn; break; // [crispy] fix Doomguy in casting sequence
          case S_POSS_ATK2:     sfx = sfx_pistol; break;
          case S_SPOS_ATK2:     sfx = sfx_shotgn; break;
          case S_VILE_ATK2:     sfx = sfx_vilatk; break;

```

**Comment by fabiangreffrath** [comment]
Hey, congratulations to your job qualification!

> But it will be nice, if after ATK2 frame, player will get back to ATK1 for few tics

But then I cannot know if we are in `ATK1` state before or after `ATK2` state and we don't have any more `ATK` states left to keep track of this. I would have to implement this by introducing another variable just for this corner case, but I guess I am fine enough with the current approach.

**Comment by fabiangreffrath** [comment]
Well, in-game the three death sounds are played randomly for all three types of possessed humans:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_enemy.c#L1595

Code-wise this means "if the monster's registered death sound is one of these three, play one random of these three".

In the cast, though, only the monster's registered sound will be played, without any randomization:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/f_finale.c#L647

I could, of course, add the same randomization there, or leave the sounds constant and change the Chaingun Dude's registered death sound to `podth3`. This will trigger the same randomization in-game, so the change won't be noticable at all.

**Comment by JNechaevsky** [comment]
Actually, randomization sounds interesting, because Imp have two death sounds instead of one. Maybe it's worth to try? Excuse, not sure I got correctly your last words about in-game randomization - this means that it does not affect gameplay behavior?

**Comment by fabiangreffrath** [comment]
Yes, indeed. This block basically means "it doesn't matter if your death sound is `podth1` or `podth2` or `podth3` - if you die I will randomly play one of them":

```
    switch (actor->info->deathsound)
    {
      [...]
      case sfx_podth1:
      case sfx_podth2:
      case sfx_podth3:
	sound = sfx_podth1 + P_Random ()%3;
	break;
```

So, if I change the death sound for the Chaingun Dude from `podth2` to `podth3` this won't make a difference when playing the game, but it will play `podth3` in the cast.

**Comment by JNechaevsky** [comment]
Oooh, got it now, thanks! Even better, less work to do, all that is necessary is to set `P_Random` func just like in p_enemy. :) Please also don't forget to try to make a random sound for Imp, the code is right below: 

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_enemy.c#L1601

**Comment by fabiangreffrath** [comment]
Same applies to `seesound`...
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_enemy.c#L642
