### ISSUE TITLE
default wad path?

### ISSUE THREAD

**Issue by inukaze** [fabiangreffrath/crispy-doom#355]
Hi there i just want to know where is the default path the binary executable under gnu/linux search first files like doom.wad ?

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/d_iwad.c#L592

So, your best guesses are
`~/.local/share/games/doom`
for per-user files and
`/usr/local/share/games/doom`
or
`/usr/share/games/doom`
for system wide installation.

**Comment by inukaze** [comment]
Ok if i want the crispy doom, search in a sub-folder called "wad" or "wards" where i compile the binary executable ?

**Comment by fabiangreffrath** [comment]
Erm, well it doesn't matter *where* you compile the binary. I am not sure I understand what you are even asking, but I have already pointed you to the relevant places in the code that you would have to modify if you wanted to re-compile with different search locations.

What you can do is point the engine to a specifc IWAD file by passing it on the command line, e.g. `crispy-doom -iwad /path/to/iwad.wad`, or add the path containing the IWAD file to the `DOOMWADDIR` environment variable.
