### ISSUE TITLE
Making SCREENWIDTH non-const introduces Variable Length Arrays

### ISSUE THREAD

**Issue by zx64** [fabiangreffrath/crispy-doom#356]
While testing building chocolate and crispy-doom with MSVC, I ran into an issue specific to a change in Crispy:
The change in `src\i_video.h` from `#define SCREENWIDTH  320` to `extern int SCREENWIDTH` (etc.) impacts the function `R_DrawSprite`.
This function has two arrays `cliptop` and `clipbot` that use the value of `SCREENWIDTH` for their size. Since it's no longer a compile time constant, those arrays become variable length.

Technically this is MSVC's fault for not supporting this C99 feature (but C11 also made VLAs an optional feature), but either way, a simple fix is to make it explicit with `alloca`:
```
 #include <stdlib.h>
+#include <malloc.h>

...

void R_DrawSprite (vissprite_t* spr)
{
     drawseg_t*         ds;
-    int                clipbot[SCREENWIDTH]; // [crispy] 32-bit integer math
-    int                cliptop[SCREENWIDTH]; // [crispy] 32-bit integer math
+    int*               clipbot = alloca(sizeof(int) * SCREENWIDTH); // [crispy] 32-bit integer math
+    int*               cliptop = alloca(sizeof(int) * SCREENWIDTH); // [crispy] 32-bit integer math
```

SDL does have `SDL_stack_alloc` but that just forwards to `alloca` on platforms that have it and `malloc`(!) on those that don't (requiring you to also use `SDL_stack_free` to avoid possible memory leaks).

**Comment by fabiangreffrath** [comment]
I was sure I have fixed all array sizes in the course of the change to run-time variable screen resolution. Thanks for spotting this, I'll fix it with a more trivial approach.

**Comment by zx64** [comment]
Cool. :-) As a further note, you can ask GCC to warn about any it finds with `-Wvla`.

**Comment by fabiangreffrath** [comment]
You never stop learning, thanks!
