### ISSUE TITLE
PK3/Merged IWADs Support

### ISSUE THREAD

**Issue by ssjkakaroto** [fabiangreffrath/crispy-doom#358]
Hello, is there any chance to support the IWAD file created by [Wadsmoosh](https://bitbucket.org/JPLeBreton/wadsmoosh)?
It's much more convenient to have all Doom games and extra official levels in a single file.

**Comment by fabiangreffrath** [comment]
Sorry, no chance!

The game mode is determined pretty early during the engine start-up and it is currently impossible to change it at run-time at any later point. Please note, though, that it is already possible in Crispy to conveniently merge an IWAD with some PWADs using the `-mergedump` parameter. Maybe this helps a bit.
