### ISSUE TITLE
MSVC/x64 needs malloc.h included in r_data.c

### ISSUE THREAD

**Issue by zx64** [fabiangreffrath/crispy-doom#361]
I think the cause of this is that because the function prototype is missing without the header, the compiler assumes the return value of `malloc` is `int`, which in practice results in a crash while populating the `crstr` array inside `R_InitColormaps` as that pointer has been truncated.
Certainly would explain why in the debugger the return value of `malloc` looked fine, but inspecting `crstr` at the point of the crash showed a value with leading `0xffff...`

**Comment by fabiangreffrath** [comment]
I could just as well use `I_Realloc()` here and should probably get rid of stdlib functions in this high-level code altogether...
