### ISSUE TITLE
Fixing "Lopsided final boss explosions" possible?

### ISSUE THREAD

**Issue by mfrancis95** [fabiangreffrath/crispy-doom#362]
[https://doomwiki.org/wiki/Lopsided_final_boss_explosions](https://doomwiki.org/wiki/Lopsided_final_boss_explosions)

I'm wondering if this is something that can be fixed without breaking demos or dehacked.

**Comment by fabiangreffrath** [comment]
Well, in general I am sure we all know what negative effects moving things around on the map has on demo and network compatibility, especially *exploding* things. 

On the other hand, the death of the IOS always marks the beginning of the end of a map, so who cares what happens during the end sequence? A monster standing near the explosions could get killed, messung up the "Kills" count at the end of the map. On the other hand, the spawned rockets are set to `S_BRAINEXPLODE1` state immediately, does this even result in calling `P_RadiusAttack()`?

There are a lot of `P_Random()` calls involved which need to be taken care of for IOS which are used in PWADs on intermediate maps (i.e. not MAP30).

And finally, we need to ask ourselves if this is actually worth all the worry and who really gives a damn. :grin:

**Comment by JNechaevsky** [comment]
Colleagues, wait a sec, fixing explosions does not seems to be safe. Map16 of Freedoom2 comes to mind, where explosions are used as an animation in skyline buildings destroying before level ending. Thus, it can be dangerous for demos. I think, the chance of desync is really small, but it is still possible to something will go wrong because of that. Be careful.

![map16](https://user-images.githubusercontent.com/21193394/49384736-b5789380-f72c-11e8-96d3-79bd275e67d2.png)

**Comment by JNechaevsky** [comment]
Possible case of not desyncing, but wrong counting on intermission stats: explosions may kill monsters, and as a result, if they are displaced, some monsters can stay alive on the level. Reverse logic can also be applied: monsters which were not killed before by explosions, can be killed after explosions displacement.

Probably better to leave them "as is".

**Comment by mfrancis95** [comment]
Then I would say the only other approach would be to visually correct the positions of the explosions but internally still use the original lopsided positions so that desyncs don't occur.

But it goes back to what @fabiangreffrath said. Is it really worth it at this point?

**Comment by fabiangreffrath** [comment]
I am closing some old issues that I consider irrelevant by now. Feel free to reopen with a comment if you disagree.
