### ISSUE TITLE
In-game sound pitch is too high and can't be changed in the setup/options menu

### ISSUE THREAD

**Issue by DeadSirius** [fabiangreffrath/crispy-doom#367]
Crispy Doom v5.3
Windows 10

The same is true for earlier versions of Crispy Doom: the music is fine, but the sound effects sound cartoonish, as though they're sped up. I've ascertained it has nothing to do with the 'Pitch-Shifted Sound' option in the setup folder nor the audio settings on my PC. One person said that for him it had something to do with a faulty .DLL file in his game folder but he never specified which one.

Here's a video of the exact problem I'm experiencing:

https://www.youtube.com/watch?time_continue=16&v=8LOdXSDek-o

What else can be done to fix this?

**Comment by fabiangreffrath** [comment]
The default SDL audio backend on Windows has been changed for the new release, so most probably simply updating the engine will fix this issue.
