### ISSUE TITLE
Support for Hexen-style MAPINFO lumps with ZDoom extensions

### ISSUE THREAD

**Issue by BCG2000** [fabiangreffrath/crispy-doom#372]
This suggestion is most likely out of scope for this source port, but I thought I would take a shot at it anyways since nobody tried it before. If it's rejected, no problem.

The point is that supporting this MAPINFO lump format would enable for a lot more WADs to be natively played in Crispy Doom, supporting the basic features necessary for custom map flow and intermissions.

Why this specific format? Because it's based on Hexen, just with some extensions making it more versatile and I believe is simpler to implement too. I think the only obstacle is the "lookup" keyword which would require parsing LANGUAGE lumps as well.

Here you can see the documentation and examples (bottom of the page): https://zdoom.org/wiki/MAPINFO_(old_format)

**Comment by fabiangreffrath** [comment]
Just as support for generalized linedef and sector types, this isn't completely out of scope. I am looking forward to a clean patch, but won't work on it myself in the short term.

**Comment by BCG2000** [comment]
What about being able to define a custom map order and episodes under New Game?

**Comment by fabiangreffrath** [comment]
Sure, that'd be nice.

**Comment by fabiangreffrath** [comment]
I am closing some old issues that I consider irrelevant by now. Feel free to reopen with a comment if you disagree.
