### ISSUE TITLE
-loadgame flag causes crashing on valid save files made from Crispy Doom itself

### ISSUE THREAD

**Issue by ultimaplayer12** [fabiangreffrath/crispy-doom#373]
### Background

Version of Chocolate Doom: 5.4

Operating System and version: Windows 10 (latest build)

Game: Doom

Any loaded WADs and mods (please include full command line): None, only using -loadgame flag.

### Bug description

Observed behavior: The game should launch the save file specified. It makes an attempt to, and then crashes out. This is repeatable every time, and specifying an invalid save causes a report that the save could not be loaded. This happens on saves made directly from Crispy Doom itself, and seemingly from Chocolate Doom as well.

Expected behavior: The save file should just load.

**Comment by ultimaplayer12** [comment]
Sorry for not including these details previously. This has only been tested with my Ultimate Doom and Doom II iWADs, I have not attempted loading PWAD saves without said PWAD present. In order to verify this wasnt the issue, I had set up a new instance of Crispy Doom and fed it a separate copy of each WAD and tried using the loadgame flag. The saves work fine on Chocolate Doom, even if made in Crispy, but Crispy refuses to load them through the flag. Through the menu, however, the game loads the save just fine.

**Comment by fabiangreffrath** [comment]
And you are never asked if you *really* want to continue loading the game in Crispy?

Does it help if you set `crispy_extsaveg` to `0` in `crispy-doom.cfg`?

**Comment by ultimaplayer12** [comment]
The only thing that happens is it blacks the screen out, as if it attempts to load the level, then the executable crashes with "Could not load savegame doomsav0.dsg" and this applies to any save slot I select.

I just tested with crispy_extsaveg to 0 in the cfg and it does not seem to resolve the issue.

**Comment by fabiangreffrath** [comment]
Could you please share the savegame file (zipped) here?

**Comment by ultimaplayer12** [comment]
Sure thing. I'm going to start feeling like a mad man if it loads correctly for you in Crispy, but here it is for your testing!
[doomsav7.zip](https://github.com/fabiangreffrath/crispy-doom/files/2747053/doomsav7.zip)

**Comment by fabiangreffrath** [comment]
Does it work if you explicitly specify the entire IWDA path, i.e. `crispy-doom -iwad "E:/Doom Classic Stuff/WADs/Official/iWADs/doomu.wad" -loadgame 7`?

**Comment by ultimaplayer12** [comment]
That is the identical command I've been using to try and load, and the same command works fine with normal Chocolate Doom with a copy of that save so it doesn't seem to be a save file issue itself

**Comment by fabiangreffrath** [comment]
Could you probably run it with GDB and provide a backtrace, so I can see which function actually crashes?

Could you please try a daily snapshot and see if this behaves differently?
http://latest.chocolate-doom.org/

**Comment by fabiangreffrath** [comment]
Does this savegame file work?
[doomsav7.zip](https://github.com/fabiangreffrath/crispy-doom/files/2747106/doomsav7.zip)

**Comment by ultimaplayer12** [comment]
I just tested the doomsav7 you uploaded, and it loads just fine with the flag. The strange thing is that now, after having put that dsg file in the directory then manually removing it, I can save to that slot and load from it fine. Doom 2 is also saving and loading fine. But new saves made even in a separate instance of Crispy Doom are exhibiting the same problem. I'm starting to wonder if my Doom WAD is seeing corruption, I may need to replace it and see if that fixes anything.

Also, what tool are you referring to with GDB? I would like to figure out what is going on with the save I shared with you so I know how to prevent it in the future. It's not the only save I've had this happen with but the issue is also not repeating itself like it was just a couple of hours ago.

**Comment by BCG2000** [comment]
I decided to test this using The Ultimate DOOM (DOOM.WAD), the original unmodified WAD.

Weirdly enough, both of your savegames crash my game when loaded from the command line (cmd.exe > "crispy-doom -iwad DOOM.WAD -loadgame 7"), but not from the main menu.
The savegame from @ultimaplayer12 asks me for confirmation, mentioning DOOM.WAD (I assume this confirms a difference in our WADs?).
Whereas the savegame from @fabiangreffrath doesn't ask for confirmation.

**Comment by ultimaplayer12** [comment]
@BCG2000 just confirming that I do indeed have the Ultimate Doom WAD. I personally renamed it doomu.wad specifically because I collect various versions of Doom and like a way to differentiate them all.

**Comment by BCG2000** [comment]
Okay, now @fabiangreffrath's savegame didn't crash. Here is the GDB output and backtrace resulting from @ultimaplayer12's crashing savegame: https://pastebin.com/8gj5TuwM

**Comment by BCG2000** [comment]
@ultimaplayer12, can you check if your DOOMU.WAD is really the original one (verify the hash)? From the Doom Wiki:

Version 1.9ud of the Ultimate Doom WAD is 12,408,292 bytes in size, is dated 1995-05-25, and contains 2,306 entries. It has the following hashes:

MD5: c4fe9fd920207691a9f493668e0a2083
SHA-1: 9b07b02ab3c275a6a7570c3f73cc20d63a0e3833
CRC-32: bf0eaac0

You can just RAR/7z it up in WinRAR or 7-Zip and check if CRC field matches the CRC32 above when you open the compressed file.

**Comment by ultimaplayer12** [comment]
Name: doomu.wad
Size: 12408292 bytes (11 MiB)
SHA1: 9B07B02AB3C275A6A7570C3F73CC20D63A0E3833

This is the exact copy-pasta from my 7-zip output.

**Comment by BCG2000** [comment]
So your WAD is also original and unmodified, strange...

**Comment by fabiangreffrath** [comment]
> Here is the GDB output and backtrace resulting from @ultimaplayer12's crashing savegame (no function names unfortunately): https://pastebin.com/8gj5TuwM

This is from a stripped binary, so I can only guess what the cause is.

But I think I have just pushed the necessary changes. @ultimaplayer12 please re-enable the `crispy_extsaveg` feature in your config file before testing tomorrow's daily build. :wink:

**Comment by BCG2000** [comment]
I forgot to say that my crispy_extsaveg was always 1.

My game no longer crashes after https://github.com/fabiangreffrath/crispy-doom/commit/98ba9c8d72d5798191ee28359b81d9a6198161b6.

**Comment by ultimaplayer12** [comment]
Made a new instance of the latest crispy doom install, thrilled to say there was absolutely no problems loading the save now! Thank you for the save update push  @fabiangreffrath and thank you for the help as well @BCG2000

**Comment by fabiangreffrath** [comment]
Cool!
