### ISSUE TITLE
Recolor Crispy setup by Crispy colors

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#375]
Using a latest Fragglet's code of textscreen, now it is possible to change setup executable colors more easily. Maybe it is worth to _try_ to change the colors of Crispy setup executable by using Crispy branded colors?

I don't have a harmonious colors at the moment, but here's an example mockup:

![recolor](https://user-images.githubusercontent.com/21193394/51276667-69389880-19e6-11e9-98d2-35e38cfd6a16.png)

Please note: this is just for show. Getting a good colors will require a research, it's not that easy as it may looks. Also, maybe we should create a Crispy brand book?

_Suggestion №102_

**Comment by fabiangreffrath** [comment]
This doesn't even look bad! Though, we shouldn't probably change the color scheme too much. Just replace e.g. the highlighting color with a more Crispy color, so it's possible to distinguish Choco's and Crispy's setup tool at first sight. Something decent...

**Comment by Zodomaniac** [comment]
The blue window header and yellow window don't look good to me.

**Comment by JNechaevsky** [comment]
Window header is an OS / window manager specific, nothing we can do about.
Except, well, as Fabian already mentioned - making whole color gamma more decent.

**Comment by JNechaevsky** [comment]
Fun fact: after making Crispy iconic orange color more decent, it becomes brown, which is more Chocolate iconic. Working on colors will definitely be an interesting challenge.

![color](https://user-images.githubusercontent.com/21193394/51307877-d5041b00-1a51-11e9-9aaf-383c67faf75d.png)

**Comment by fabiangreffrath** [comment]
It's not that I don't like the orange tone from the initial screen shot! It's just that there is a bit *too much* (in terms of screen area) orange on the picture. what if you only change the color that highlights the currently selected line and leave all the other colors unchanged?

**Comment by fabiangreffrath** [comment]
I definitely want to keep "Romero blue" as the main color. :wink:

**Comment by JNechaevsky** [comment]
Whatever you say!,Now we just have to find good highlight color, which must fits in two principles:

1. Must not be very decent dimmed. It's a _highlight_ color, that should attract attention.
2. Must not be very bright, otherwise it will make white texts unreadable.

Thus, an obvious choose is "not awfully bright orange, like a crisp sunset in the end of the summer".

**Comment by fabiangreffrath** [comment]
> "not awfully bright orange, like a crisp sunset in the end of the summer"

:yum:

**Comment by Zodomaniac** [comment]
>Now we just have to find good highlight color

So we're talking about dark orange highlight on Romero blue background with white text?

How about this?
![crd_setup](https://user-images.githubusercontent.com/15119473/51317745-734fab00-1a69-11e9-866f-fac68c81458e.png)

**Comment by fabiangreffrath** [comment]
Wow!

**Comment by Zodomaniac** [comment]
More exact, considered all the cases
![crd_setup2](https://user-images.githubusercontent.com/15119473/51319477-3e922280-1a6e-11e9-9174-eade0ecd9f27.png)

**Comment by fabiangreffrath** [comment]
Really not bad, but a tad to brownish for my taste. If you could shift this a bit more towards the orange/yellowish corner, that would be nice...

**Comment by Zodomaniac** [comment]
I chose brownest color so that both dark-blue and white letters stand out well on it. You may play with those values that are:
selection/header background: 160, 85, 0
sub-header/hotkey: 255, 140, 0
mouse hover background: 160, 144, 0
borderlines, ='s at hotkeys: 255, 255, 0

**Comment by fabiangreffrath** [comment]
Actually, I like option 3 the most.

**Comment by JNechaevsky** [comment]
![images](https://user-images.githubusercontent.com/21193394/51335694-c3dbfe00-1a93-11e9-8a39-39c31f832782.jpg)

**Comment by fabiangreffrath** [comment]
So, how about this?
![bildschirmfoto vom 2019-01-17 21-58-57](https://user-images.githubusercontent.com/6449237/51348484-28528980-1aa3-11e9-8b27-eadf9f41fc7d.png)

**Comment by fabiangreffrath** [comment]
```
--- a/src/setup/mainmenu.c
+++ b/src/setup/mainmenu.c
@@ -316,6 +316,11 @@ static void InitTextscreen(void)
     // <https://doomwiki.org/wiki/Romero_Blue>
     TXT_SetColor(TXT_COLOR_BLUE, 0x04, 0x14, 0x40);
 
+//  TXT_SetColor(TXT_COLOR_GREY, 220, 153, 0);
+    TXT_SetColor(TXT_COLOR_BRIGHT_GREEN, 255, 140, 0);
+    TXT_SetColor(TXT_COLOR_BRIGHT_BLUE, 160, 144, 0);
+    TXT_SetColor(TXT_COLOR_BRIGHT_CYAN, 255, 255, 0);
+
     SetIcon();
     SetWindowTitle();
 }
```

**Comment by fabiangreffrath** [comment]
Hm, apparently I am bad at this. But I have not yet found a way to change gray as the highlighting color for the menu entries without changing the entire menu background as well. Any ideas?

**Comment by JNechaevsky** [comment]
I like the way how it looks, so don't have anything to add. :+1:

Except.. Well. For my eyes this scheme looking a little bit "conservative", there is too high contrast between bright elements (texts and markers) and dark elements (primary dark blue background). It feels like there still strict EGA colors are used, so I would like to change background a bit.

Again, this is not meaning that this scheme is bad. But would you mind to take a try to make background very slightly brighten, and shift it from blue to a little bit cyanic? To make it like a mix between "old and new": 

![untitled-1](https://user-images.githubusercontent.com/21193394/51372361-1528d380-1b0e-11e9-83fc-e00b2835057a.png)

The color is: #15284d

> Hm, apparently I am bad at this.

Please clarify, you meaning technical or visual approach? I.e. is it code or coloring problem?

**Comment by fabiangreffrath** [comment]
> The color is: #15284d

Oh, yes, this is really looking better, "fresher".

> Please clarify, you meaning technical or visual approach? I.e. is it code or coloring problem?

Visual. I am absolutely no design person.

**Comment by JNechaevsky** [comment]
Excellent! But please wait until evening, I'm using a bit different gamma on my monitor at work, so it's just a quick suggestion - the real value may be a little bit different.

Hmm. If now we have a bright yellow, dark orange, dark blue - maybe we should have a bright blue? Something like this

![color](https://user-images.githubusercontent.com/21193394/51373760-fb898b00-1b11-11e9-947e-66abc4f34185.png)


(#6781ad)

But this will absolutely require changing color of window title.

**Comment by Zodomaniac** [comment]
The bright blue does not associate with crisps ;)

**Comment by JNechaevsky** [comment]
> The bright blue does not associate with crisps ;)

Actually, agreed. So it may be something "between yellow and orange"?

![color](https://user-images.githubusercontent.com/21193394/51377020-d4838700-1b1a-11e9-8d2e-44b320e9713a.png)
(#cc904a)

**Comment by Zodomaniac** [comment]
>So it may be something "between yellow and orange"?

Yes, that's what I initially proposed, bu with color (220, 153, 0) which looks similar (my option 3).
But @fabiangreffrath says:
>But I have not yet found a way to change gray as the highlighting color for the menu entries without changing the entire menu background as well

which I asked to clarify.

**Comment by JNechaevsky** [comment]
Probably shortest way will to change window title's text color, which is now using background color.

**Comment by Zodomaniac** [comment]
>Probably shortest way will to change window title's text color, which is now using background color.

@JNechaevsky Please reply me in Telegram, I didn't quite understand your point.

**Comment by fabiangreffrath** [comment]
The marked regions are all the same color (i.e. "gray") and even the dotted background uses this color. You have to change the colors *in the palette* which means that if you change it for one regions, it affects all the others as well. 

I am not sure if there is a way around this, but I have to admit I haven't really researched either.

![gray](https://user-images.githubusercontent.com/6449237/51378257-28876f00-1b0d-11e9-9024-0413a724c473.PNG)

**Comment by Zodomaniac** [comment]
@fabiangreffrath Could you pls give a screenshot of what happens if you set gray to #cc904a?

**Comment by fabiangreffrath** [comment]
Here it is:

![orange](https://user-images.githubusercontent.com/6449237/51379209-32aa6d00-1b0f-11e9-8624-69b3707a2e30.PNG)

```
--- a/src/setup/mainmenu.c
+++ b/src/setup/mainmenu.c
@@ -316,6 +316,11 @@ static void InitTextscreen(void)
     // <https://doomwiki.org/wiki/Romero_Blue>
     TXT_SetColor(TXT_COLOR_BLUE, 0x04, 0x14, 0x40);

+    TXT_SetColor(TXT_COLOR_GREY, 204, 144, 74);
+    TXT_SetColor(TXT_COLOR_BRIGHT_GREEN, 255, 140, 0);
+    TXT_SetColor(TXT_COLOR_BRIGHT_BLUE, 160, 144, 0);
+    TXT_SetColor(TXT_COLOR_BRIGHT_CYAN, 255, 255, 0);
+
     SetIcon();
     SetWindowTitle();
 }
```

**Comment by Zodomaniac** [comment]
I totally like it! @JNechaevsky your opinion?

**Comment by fabiangreffrath** [comment]
Choco setup is still the reference! I think this is too offensively orange.

I wanted the changes to be subtle, so that you would realize at second sight that the colors are a bit more "Crispy" themed than in Choco setup.

**Comment by JNechaevsky** [comment]
Tip: instead of using "▒" symbol, you can use " " or "█", depending of what kind of solid color you wish to use for background.

**Comment by fabiangreffrath** [comment]
Sure thing. But I'd like to apply the same mantra here that also applies to the code: Keep as much original code as possible, changes only as few and as least invasive as necessary.

I think with the thre color changes presented above, Crispy setup still looks like choco setup -- which is good -- but with a few subtle changes that make it Crispy. ;)

**Comment by fabiangreffrath** [comment]
I am still unsure about Romero blue. I consider it as an "insider joke" and changing it back to some other random blue feels like "not getting it".
