### ISSUE TITLE
Player coordinates displayed with IDMYPOS cheat don't update the last 3 seconds they're shown

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#377]
If you enter the IDMYPOS cheat, you'll see the coordinates for some time, but they stop updating about 3 seconds earlier than they stop displaying.

**Comment by fabiangreffrath** [comment]
Yes, that's because then they turn into a regular player message.

**Comment by Zodomaniac** [comment]
Is there a way just to discard that message and not display it further?
