### ISSUE TITLE
In Strain weapon pickup messages are not shown

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#378]
### Background

Version of Crispy Doom: 5.4 and further (no such issue in Chocolate)

Operating System and version: Win 7

Game: (Doom/Heretic/Hexen/Strife/other) Doom 2

Any loaded WADs and mods (please include full command line): `start crispy-doom -merge strain.wad -deh strain.deh`

### Bug description

Observed behavior: No message on picking up weapons, items and ammo do have pickup messages though (there is no such problem in daily Chocolate build with any kind of pickupables).

Launch strain.bat with Choco and strain_crispy.bat with Crispy, and load the savegame attached (ignore the warning for WAD file name).
[strain_test.zip](https://github.com/fabiangreffrath/crispy-doom/files/2791916/strain_test.zip)

**Comment by fabiangreffrath** [comment]
Probably connected to this?
https://github.com/fabiangreffrath/crispy-doom/commit/a8da692786bf0e894e82fdd8a4d7892a3b0119a7

**Comment by fabiangreffrath** [comment]
@Zodomaniac This shouldn't be limited to Strain. If you pick up a weapon that you already owned before, so you just gets its ammo, does it print the message in regular Doom?

**Comment by Zodomaniac** [comment]
Aha, I see. The message on picking up a weapon that I already own is printed in Choco, but isn't in Crispy.
