### ISSUE TITLE
Crispy-midiproc.exe doesn't do its job in Crispy 5.4

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#379]
### Background

Version of Crispy Doom: 5.4

Operating System and version: Win 7

Game: (Doom/Heretic/Hexen/Strife/other) Doom 2

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: The SFX volume depends on the music volume and is in fact the music volume multiplied by (SFX volume/15).

Expected behavior: SFX volume should be independent of music volume. Both daily builds of Crispy and Chocolate 3.0.0 don't suffer from this. Maybe because they're based on SDL2 2.0.5 and SDL2_mixer 2.0.1, while Crispy 5.4 is based on SDL2 2.0.9 and SDL2_mixer 2.0.4?

**Comment by fabiangreffrath** [comment]
> Maybe because they're based on SDL2 2.0.5 and SDL2_mixer 2.0.1, while Crispy 5.4 is based on SDL2 2.0.9 and SDL2_mixer 2.0.4?

Yes, probably. Now that the daily builds support MP3 playback through a statically linked libmad, I will not do my own Windows releases anymore. The "release" will be the daily build from the day I pushed the GIT tag. I am really too fed up with running behind sound issues on an OS that I refuse to use myself.

**Comment by Zodomaniac** [comment]
>Now that the daily builds support MP3 playback through a statically linked libmad

But there is no libmad in the daily build.

**Comment by fabiangreffrath** [comment]
statically linked
^^^^^^^^^^
means it it built in into SDL2_Mixer.dlll
