### ISSUE TITLE
Adapt the issue submission template to Crispy

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#380]
Thank you for reporting a bug in Crispy Doom. Please complete
  the following template so that we can better diagnose the source
  of your problem.

### Background

Version of Crispy Doom:

Operating System and version:

Game: (Doom/Heretic/Hexen/Strife/other)

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior:

Expected behavior:

**Comment by Zodomaniac** [comment]
The `Thank you...` paragraph should be styled the same way as in Choco, enclosed in `<!--` and `-->`

**Comment by fabiangreffrath** [comment]
> I'll do it myself from home.

Ok, thanks!
