### ISSUE TITLE
Suggestion: Option for fixed hitscan traces

### ISSUE THREAD

**Issue by NeuralStunner** [fabiangreffrath/crispy-doom#384]
As described [here](https://doomwiki.org/wiki/Flawed_collision_detection).

I've only occasionally encountered the first issue, but the second comes up often, in effect making the chainsaw or fist a useless fallback when dealing with the larger monsters. (In particular, MAP12 has _3_ berserk packs, and numerous arachnotrons/mancubi.)

I considered this as an option (rather than direct change) for possible demo compatibility reasons.

**Comment by fabiangreffrath** [comment]
Sorry, but this is exactly the kind of subtly game logic changing intervention that I'd like to keep of out Crispy. There are dozens of little bugs like this in Vanilla, but fixing them would either instantly destroy demo and multiplayer compatibility or require a switch that I would have to manitain forever, but don't want to introduce in the first place. 
It's imperfections like this that make Vanilla Doom as charming as it is. :wink:
