### ISSUE TITLE
No weapon in clean screenshot with alternative status bars

### ISSUE THREAD

**Issue by danpla** [fabiangreffrath/crispy-doom#386]
### Background

Version of Crispy Doom: 5.4

Operating System and version: Xubuntu 14.04

Game: Doom

### Bug description

The README says that clean screenshots are taken:

>  without burning the status bar and HUD messages into them.

HUD messages are OK, they are never included. However, depending on the status bar mode there are two issues:

* In the normal status bar mode, it's actually included in the screenshot, which doesn't match README.
* In three extra modes (hidden, no background, no background + alpha), status bar is not included, but weapons are not included as well.

**Comment by fabiangreffrath** [comment]
Indeed, that's inconsistent. I'll adjust the wording a bit.
