### ISSUE TITLE
IDBEHOLDA doesn't toggle the full automap 'off'

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#387]
### Background

Version of Crispy Doom: Latest git

Operating System and version: Win7

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: When typing IDBEHOLDA for the second time, the full automap shown when the cheat is typed in for the first time doesn't go away when 'toggled off', unlike e,g, Berserk IDBEHOLDS
or Invisibility IDBEHOLDI.

Expected behavior: When typing IDBEHOLDA for the second time the full automap should be replaced by the map part actually discovered by the player.

**Comment by fabiangreffrath** [comment]
Indeed, why didn't nobody ever notice this before?!
