### ISSUE TITLE
Two-sided borders of revealed secret sectors are colorized in gold regardless of "Show Revealed Secrets" setting

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#389]
### Background

Version of Crispy Doom: 5.5

Operating System and version: Win 7

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: Two-sided borders of revealed secret sectors are colorized in gold regardless of "Show Revealed Secrets" setting. The setting thus applies to single-sided lines only. Here showing revealed secrets is off, and the top line is not colorized, but te left and right sides of the sector still are.

![doom0002](https://user-images.githubusercontent.com/15119473/53555627-5c65a380-3b53-11e9-91be-170c082f58f5.png)

and with IDDT that makes one more 2-sided line that isn't automapped (the bottom line) visible:

![doom0003](https://user-images.githubusercontent.com/15119473/53555796-b2d2e200-3b53-11e9-9c4f-78fc84a6a399.png)

Expected behavior: All the lines enclosing the revealed secret sector should not be colorized in "Show Revealed Secrets" is off.

**Comment by fabiangreffrath** [comment]
Ah, the first post-release bug report, no less than two hours after the release. :grin:

Indeed, this is an oversight, thanks!

**Comment by Zodomaniac** [comment]
So maybe tag it as a hotfixed Crispy 5.6?)

**Comment by fabiangreffrath** [comment]
> So maybe tag it as a hotfixed Crispy 5.6?)

Na, not yet. I expect more of this to come. :wink: 

Also, I have decided to introduce a micro version number for hotfixes, i.e. this would be 5.5.1.

**Comment by Zodomaniac** [comment]
>Also, I have decided to introduce a micro version number for hotfixes, i.e. this would be 5.5.1.

Yup, I see the current release is 5.5.0.

**Comment by Zodomaniac** [comment]
I think there should be a hotfix after gathering some feedback from Doomworld forums, right? In about a week.

**Comment by fabiangreffrath** [comment]
Yes, maybe a week. We are currently figuring out why MP3 playback is broken in the daily builds, but most probably after that...

**Comment by Zodomaniac** [comment]
>We are currently figuring out why MP3 playback is broken in the daily builds, but most probably after that...

For me MP3 inside WADs is played. Could you share your test case?

**Comment by fabiangreffrath** [comment]
It's DoomMetalVol4.wad, it sounds terrible!

**Comment by Zodomaniac** [comment]
It's OGG not MP3, and in it some files are in 32 kHz sample rate which makes them play wrong. I made a WAD of resamples to 44.1 kHz to play with Crispy https://www.moddb.com/groups/doomdb/addons/doom-metal-vol4-resampled-to-441-khz

**Comment by Zodomaniac** [comment]
I have another idea: to let the player choose the color for the secret revealing message and sectors on the map: Off, Gold (162), Green (112) or Light-Blue (194).

**Comment by fabiangreffrath** [comment]
This will open a can of worms and people will want to choose the colors for everything else.

**Comment by Zodomaniac** [comment]
OK, let the sectors be green then. IMO the screenshot shows gold is not very good.
(Posting it here once again for everyone to see)
![doom0012](https://user-images.githubusercontent.com/15119473/53877901-730c6e80-401b-11e9-8e2b-61a39b0ebb6d.png)
