### ISSUE TITLE
Implement IDCLEV1A cheat to access E1M10: Sewers to unify with -warp 1a and not coincide with E1M0 of NEIS.wad

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#391]
### Background

Version of Crispy Doom: 5.5.1

Operating System and version: Win 7

Game: (Doom/Heretic/Hexen/Strife/other) XBox Doom

Any loaded WADs and mods (please include full command line): start crispy-doom -iwad doom(3).wad -merge neis.wad

### Bug description

Observed behavior: `IDCLEV1A` doesn't work, though one can expect this as `-warp 1a` works and `IDCLEV10` that normally warps to Sewers takes you to E1M0 of NEIS.wad when the latter is loaded.

Expected behavior: I expect `IDCLEV1A` to warp to E1M10: Sewers like `-warp 1a`.

**Comment by fabiangreffrath** [comment]
Does `IDCLEV10` bring you to E1M10? Are you playing NEIS.wad with the XBOX DOOM.WAD?

**Comment by Zodomaniac** [comment]
>Does IDCLEV10 bring you to E1M10?

If I'm playing pure XBOX Doom IWAD alone, it does. If I'm playing NEIS.wad with the XBOX DOOM.WAD, it brings me to E1M0. That's why I'm suggesting to introduce a separate cheat `IDCLEV1A` for E1M10: Sewers.

**Comment by Zodomaniac** [comment]
Sorry for not reminding of it before 5.5.1, I remembered 'all the shit you've gone through (like through actual sewers) to properly support E1M10' and decided not to hinder the 5.5.1 release, and now I deemed it can be given a thought to be part of the release that will handle MIDI sound issue https://github.com/chocolate-doom/chocolate-doom/issues/1147

**Comment by fabiangreffrath** [comment]
Never mind, we are not in a hurry and this is no life-critical software. The E1M10 use case is already pretty exotic and even more so in combination with NEIS.wad - or any other wad providing E1M0.
