### ISSUE TITLE
More command line aliases and new cheat code SKILL to display current skill level

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#392]
In [Marshmallow Doom](https://doomwiki.org/wiki/Marshmallow_Doom) there are some aliases for command line arguments that seem useful to me:

`-itytd` enables "baby mode" skill level
`-hntr` enables easy skill level
`-hmp` enables normal skill level
`-uv` enables hard skill level
`-nm` enables Nightmare skill level

Also, if there is a VERSION cheat, why not have a SKILL cheat to display `Skill: *current skill level*`, where 
`*current skill level*`can be `baby mode`, `easy`, `normal`, `hard` and `Nightmare` (they can have different names in specific WADs, as lumps with skill level names are actually sprites AFAIK)

**Comment by fabiangreffrath** [comment]
> `-itytd` enables "baby mode" skill level
> `-hntr` enables easy skill level
> `-hmp` enables normal skill level
> `-uv` enables hard skill level
> `-nm` enables Nightmare skill level

This doesn't appear easier to remember than `-skill N`.

> Also, if there is a VERSION cheat, why not have a SKILL cheat to display `Skill: *current skill level*`, 

Hm, it's already logged to STDOUT whenever you enter a level.

> `*current skill level*`can be `baby mode`, `easy`, `normal`, `hard` and `Nightmare` (they can have different names in specific WADs, as lumps with skill level names are actually sprites AFAIK)

and thus there is already a skill -> text mapping available here:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_setup.c#L1091

but I agree being more neutral with the wording might help.

**Comment by Zodomaniac** [comment]
>Hm, it's already logged to STDOUT whenever you enter a level

I thought it was a bit inconvenient to checck STDOUT for that while in-game. BTW, after transition to SDL2 Choco doesn't write `stdout.txt` and `stderr.txt` files anymore.

**Comment by fabiangreffrath** [comment]
I see. Is the SKILL cheat idea also taken from Marshmallow Doom?

**Comment by Zodomaniac** [comment]
No, SKILL cheat is my own idea :)
