### ISSUE TITLE
add ability to take over demo 

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#394]
It should be possible to take over a demo by pressing "q" during playback.

Bonus points: continue recording under a different name.

**Comment by Zodomaniac** [comment]
What does it mean to take over a demo? Switch to recording during playback?
And why Q? Do you mean generally the key that finishes recording demo?

**Comment by fabiangreffrath** [comment]
"Taking over" means that the demo stops playing back and you are left in the scene and get the control over the player. The "q" key is supposed to stop recording a demo, so it's unambigious to use it to stop playing back a demo as well.

Immediately switching over to record a new demo that consists of the original demo up to the point when you took over and then continues with your controls will be tricky - but desirable.

**Comment by fabiangreffrath** [comment]
This seems to do the trick:
```
diff --git a/src/doom/g_game.c b/src/doom/g_game.c
index 32af667d..a52363e3 100644
--- a/src/doom/g_game.c
+++ b/src/doom/g_game.c
@@ -2389,6 +2389,8 @@ G_InitNew
 
 // [crispy] demo progress bar and timer widget
 int defdemotics = 0, deftotaldemotics;
+// [crispy] moved here
+static const char *defdemoname;
 
 void G_ReadDemoTiccmd (ticcmd_t* cmd) 
 { 
@@ -2398,6 +2400,27 @@ void G_ReadDemoTiccmd (ticcmd_t* cmd)
 	G_CheckDemoStatus (); 
 	return; 
     } 
+
+    if (gamekeydown[key_demo_quit] && singledemo)
+    {
+	byte *actualbuffer = demobuffer;
+	char *actualname = M_StringDuplicate(defdemoname);
+
+	gamekeydown[key_demo_quit] = false;
+
+	// [crispy] find a new name for the continued demo
+	G_RecordDemo(actualname);
+	free(actualname);
+
+	// [crispy] discard the newly allocated demo buffer
+	Z_Free(demobuffer);
+	demobuffer = actualbuffer;
+
+	// [crispy] continue recording
+	G_CheckDemoStatus();
+	return;
+    }
+
     cmd->forwardmove = ((signed char)*demo_p++); 
     cmd->sidemove = ((signed char)*demo_p++); 
 
@@ -2624,7 +2647,6 @@ void G_BeginRecording (void)
 // G_PlayDemo 
 //
 
-static const char *defdemoname;
  
 void G_DeferedPlayDemo(const char *name)
 { 
```

**Comment by Zodomaniac** [comment]
>void G_DeferedPlayDemo(const char *name)

Deferred is spelt with double R, but you can leave it as is if it needs replacement in multiple files.

**Comment by fabiangreffrath** [comment]
I am not going to fix typos in ID's function names. :wink: There are some others, e.g. `P_AproxDistance()` with a single 'p'.

**Comment by Zodomaniac** [comment]
Didn't know those were ID's typos, funny)
