### ISSUE TITLE
Corpses/death animations of Dehacked-modified monsters are not mirrored

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#395]
Looks like corpses/death animations of Dehacked-modified monsters are not mirrored, for instance, in Batman Doom
![DOOM0004](https://user-images.githubusercontent.com/15119473/54596493-d21fa980-4a45-11e9-8c03-2be92ef74bf9.png)

**Comment by fabiangreffrath** [comment]
I guess the DEHACKED patch sets new flags for map things and these, of course, don't contain the MF_FLIPPABLE bit. Not much I can do about this for mods that decide to turn the state table upside down or mess around with thing flags. :frowning_face:
