### ISSUE TITLE
The 'Continue loading from another WAD file' dialog desyncs the demo

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#396]
If I'm recording the demo, go to Load game menu, then try to load a savegame from another WAD, decline in the dialog that appears and return to game, the resulting demo desyncs. This is probably related to https://github.com/fabiangreffrath/crispy-doom/issues/393.
According to my observation, in demo playing the demo is unpaused for the time spent in the load confirmation dialog.

**Comment by fabiangreffrath** [comment]
Yes, it's most probably related. It's not *that* bad, though, because if you are honestly trying to load a game during demo recording, you aren't expecting a syncing demo anyway, but - nevertheless - it shouldn't happen.
