### ISSUE TITLE
Demo files recorded with taking over are desynced and named with all the upper case letters

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#397]
### Background

Version of Crispy Doom: Daily 23.03.2019

Operating System and version: Win 7

Game: Doom 2

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: The taken-over demo file is named wth all the upper case letter (SYNCTEST-00000.lmp) and is desynced.

Expected behavior: the letter case in the filename should be preserved like for usual multi-attempt demo and have no desync.

[synctest.zip](https://github.com/fabiangreffrath/crispy-doom/files/2999199/synctest.zip)

**Comment by fabiangreffrath** [comment]
> The taken-over demo file is named wth all the upper case letter (SYNCTEST-00000.lmp)

I don't care too much about this one. Once a demo lump has been loaded on the command line it gets integrated into the engine's run-time lump name space, i.e. reduced to eight upper-case letters. There isn't much I can do about this.

> and is desynced

This is annoying. It didn't happen with `-playdemo demo3` from Doom2.wad when I tested this. Which setup did you use to find it desyncs?

I will probably have to move the added code to the bottom of `G_BuildTiccmd()`...?

**Comment by Zodomaniac** [comment]
I just recorded a demo from start of MAP01 and took it over. and attached the result

**Comment by fabiangreffrath** [comment]
Ouch, didn't see the attachment!

**Comment by fabiangreffrath** [comment]
Something is wrong with my method! Upon more thorough investigation, it seems that even continued `-playdemo X -record Y` demos desync. :frowning_face:

**Comment by fabiangreffrath** [comment]
It seems like I am losing a tic somewhere...

**Comment by Zodomaniac** [comment]
When you fix that, I think it's worth a release.

**Comment by fabiangreffrath** [comment]
Yes, if it's fixable that is!
