### ISSUE TITLE
When continuing to record the demo with -playdemo -record, there is no music

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#398]
### Background

Version of Crispy Doom: Git March 29, 2019

Observed behavior: The music doesn't play when continuing a demo with `-playdemo demoname1 -record demoname2`

Expected behavior: The music should play.

Hopefully the last issue preventing the hotfix 5.5.2 from release.
BTW, should 5.5.2 use the old SDL DLLs, same as 5.5.1? Some users are experiencing issues with new ones https://github.com/chocolate-doom/chocolate-doom/issues/1149

**Comment by fabiangreffrath** [comment]
Good catch. However, it will be impossible to start the correct music if the demo is continued during an intermission screen - is this even possible at all?
