### ISSUE TITLE
Crispy-midiproc.exe crashes when exiting the game

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#399]
### Background

Version of Crispy Doom: Daily Git 30.03.19

Operating System and version: Win 7

Observed behavior: Upon exiting the game a crash window shows up informing of midiproc crash after yesterday's commit

**Comment by fabiangreffrath** [comment]
I don't think this has to do with yesterday's commit. Did you have any pwads loaded? Did the same ever happen with Choco, too?

**Comment by Zodomaniac** [comment]
No, there were no PWADs loaded neither does this happen with Choco. Today's daily Choco doesn't have this midiproc crash.

**Comment by fabiangreffrath** [comment]
So, the current state is ready for 5.5.2 you say?
