### ISSUE TITLE
No flesh beating sound when fist hits the enemy

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#401]
### Background

Version of Crispy Doom: Git April 3, 2019

Operating System and version: Win 7

### Bug description

Observed behavior: When fist hits the enemy, there is no beating sound

**Comment by fabiangreffrath** [comment]
Do you have "play sounds in full length" enabled?

**Comment by Zodomaniac** [comment]
Yes, I do have it enabled, but in 5.5.2 release I don't have the bug, I can hear beating sounds. Since the today's daily build it's gone.

**Comment by fabiangreffrath** [comment]
Doesn't seem to make any sense. None of the changes since Monday touched the relevant code even remotely.

**Comment by Zodomaniac** [comment]
When I replace the 5.5.2 exe with the daily one, the fist beating sound vanishes.
