### ISSUE TITLE
Crash in Struggle (STRG.WAD) with the invisible cacodemon

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#403]
### Background

Version of Crispy Doom: Git April 3, 2019

Operating System and version: Win 7

Game: Doom 2

Any loaded WADs and mods: Struggle `start crispy-doom -merge strg.wad`
You can download the WAD here https://www.doomworld.com/files/file/19194-struggle-antaresian-legacy/

### Bug description

Observed behavior: I get a crash when fighting the invisible cacodemon.
![DOOM0002](https://user-images.githubusercontent.com/15119473/55506931-46ba3100-565f-11e9-8687-39f62aa8d85f.png)

Here's the savegame: 
[doomsav0.zip](https://github.com/fabiangreffrath/crispy-doom/files/3040400/doomsav0.zip)

What's interesting, the 5.5.2 release handles this without a crash, so you released it about time! :)

**Comment by fabiangreffrath** [comment]
Does it help if you disable colored blood?

**Comment by Zodomaniac** [comment]
No, it doesn't. More than that, the in-built demos of the WADs (even DOOM2.WAD) now desync!

**Comment by fabiangreffrath** [comment]
Oh, I guess this is because I turned `SCREENHEIGHT` and `SCREENWIDTH` into `unsigned int`s. Seems like the code depends on them being signed in some calculations, e.g. for rendering of "invisibl' sprites.

**Comment by JNechaevsky** [comment]
@fabiangreffrath it's not only! While I was working in widescreen stuff, I have found a place, where `SCREENWIDTH` must remain same, i.e. `320`, otherwise demos will desync. Here it is:

https://github.com/JNechaevsky/russian-doom/blob/master/src_wide/doom/p_map.c#L1418

- `SCREENWIDTH_OLD` is `320`
- `SCREENWIDTH` is `426`
