### ISSUE TITLE
show tally screen after ExM8

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#404]
This came up in the Doomworld forums. Why don't we show a tally screen after ExM8 while other source ports do so? Honestly, I don't know. Vanilla doesn't either and nobody has asked this question, yet, it seems.

Implementation is quite straightforward. Does this have any impact on demos? I mean, how is the demo time for finishing a ExM8 level determined if there is no tally screen. And does it matter that a tally scren requires additional key presses?

**Comment by fabiangreffrath** [comment]
```
diff --git a/src/doom/g_game.c b/src/doom/g_game.c
index c58316a5..51bf0d81 100644
--- a/src/doom/g_game.c
+++ b/src/doom/g_game.c
@@ -1656,9 +1656,12 @@ void G_DoCompleted (void)
         {
             switch(gamemap)
             {
+            // [crispy] display tally screen after ExM8
+            /*
               case 8:
                 gameaction = ga_victory;
                 return;
+            */
               case 9:
                 for (i=0 ; i<MAXPLAYERS ; i++)
                     players[i].didsecret = true;
@@ -1667,6 +1670,8 @@ void G_DoCompleted (void)
         }
     }

+// [crispy] disable redundant code
+/*
 //#if 0  Hmmm - why?
     if ( (gamemap == 8)
         && (gamemode != commercial) )
@@ -1684,6 +1689,7 @@ void G_DoCompleted (void)
            players[i].didsecret = true;
     }
 //#endif
+*/


     wminfo.didsecret = players[consoleplayer].didsecret;
@@ -1907,6 +1913,12 @@ void G_WorldDone (void)
            break;
        }
     }
+    // [crispy] display tally screen after ExM8
+    else
+    if ( gamemap == 8 )
+    {
+       gameaction = ga_victory;
+    }
 }

 void G_DoWorldDone (void)
diff --git a/src/doom/wi_stuff.c b/src/doom/wi_stuff.c
index c8238f91..65844f3d 100644
--- a/src/doom/wi_stuff.c
+++ b/src/doom/wi_stuff.c
@@ -802,6 +802,13 @@ static boolean             snl_pointeron = false;

 void WI_initShowNextLoc(void)
 {
+    // [crispy] display tally screen after ExM8
+    if ((gamemode != commercial) && (gamemap == 8))
+    {
+       G_WorldDone();
+       return;
+    }
+
     state = ShowNextLoc;
     acceleratestage = 0;
     cnt = SHOWNEXTLOCDELAY * TICRATE;

```

**Comment by JNechaevsky** [comment]
I think the best way to check, is to record demo with tally screen, try to play it in vanilla executable and see what will happen. With few cases, like pressing and not pressing `USE`. Should I try this?

Obviously, changing `gameaction` is a destructive thing, but - every ExM8 map is the last map, there is no way to continue playing after that. At least, I hope so!

**Comment by fabiangreffrath** [comment]
Exactly what I was thinking. If `gamemode != commercial` then the end of map 8 is the end of the game, that's hard-coded into the engine. So, if you finish that map, in fact you finished your demo. It doesn't matter if you press `USE` another time to put away the tally screen. Yout time for finishing the game is determined before.

**Comment by JNechaevsky** [comment]
Well, let's find it out how it will work then. I'll try to investigate it in the evening, and if I don't - please notify me somehow, I have a lots of things to deal / take care about now, so can simply forgot about testing. =/

**Comment by JNechaevsky** [comment]
Jeez, I've finished my day job only now. :scream:

Good news, though! There is no tally screen in vanilla executable in recorded demo, so it seems to be safe. Well, hopefully, my head is not fresh enough to analyze everything. To summarize:

* In Crispy, full time and actions of E3M8 intermission is recorded.
* In Vanilla, beating E3M8 leading to final text with preserved time spend there.

Here's the demo, compatible with Ultimate Doom: [demdem.zip](https://github.com/fabiangreffrath/crispy-doom/files/3060747/demdem.zip)
 
Ah yes, a small extra suggestion: there is blood splat on ExM8 in intermission screen. Maybe we should add it?

**Comment by JNechaevsky** [comment]
Awoke with a thought that I haven't checked vice versa way - what will happen in Crispy while playing demo from vanilla executable, i.e. what will happen in intermission screen after beating ExM8 map? Will be there very soft lock-up, which will await user's key press or not.

I'm very short in time in the morning, so can check it only in the deep evening.

**Comment by fabiangreffrath** [comment]
> there is blood splat on ExM8 in intermission screen

Did you mean there is *no* blood splat for ExM8?

**Comment by JNechaevsky** [comment]
> Did you mean there is no blood splat for ExM8?

Oh yes, there is _no_ blood splat, sorry for typo.

**Comment by fabiangreffrath** [comment]
Hm, correct me if I'm wrong, but blood splats are never shown on the "Finished <current level>" screen where the stats are calculated. They are only shown on the "Entering <next level>" screen which we skip on purpose -- because there is no next level after ExM8, right?

**Comment by JNechaevsky** [comment]
You've right, there is no splats until "Entering" is appeared:
![1](https://user-images.githubusercontent.com/21193394/55872130-e5c9b600-5b94-11e9-93bc-d6134cf67113.png)

![2](https://user-images.githubusercontent.com/21193394/55872156-f548ff00-5b94-11e9-926b-abbedb5f8cff.png)

Looks likes my memory tricked me, or I have seen it in another source port. Oh well, matters no, let's leave it as is to represent vanilla appearance.

**Comment by JNechaevsky** [comment]
Phew, now I really understand the proverb "Business before pleasure" or "Erst die Arbeit, dann das Vergnügen", or "Delu vremya, potehe chas". It's pretty much a predecessor of "No rest for the living".
Moving on!

It seems to be okay. Intermission screen of E3M8 will does not have soft-lock, it will pass in ~10 seconds, and proper text, and then bunny screen will start. Although, timings of bunny screen is a bit different in vanilla and Crispy, take a try both engines and you will see.

So... This is not good for `100%` ideal compatibility, but it seems to be fine. I really have no idea, is it worth to keep timings of final (after-intermission) screens. Knowing Crispy philosophy - probably it is worth. But the feature itself is very useful, I suppose not only for speed runners, but also for common players. 

The demo, recorded in Ultimate Doom for DOS: [vanvan.zip](https://github.com/fabiangreffrath/crispy-doom/files/3065329/vanvan.zip)

**Comment by fabiangreffrath** [comment]
@JNechaevsky Thanks for the checks. I am glad you are back!

The outcome is pretty much expected. However, it doesn't matter exactly when the bunny screen starts. At this point the game is already over and the results that count are recorded. Regarding the project philosophy, the aim is to make the game as convenient as possible while preserving demo *compatibility*. I don't see this threatened by a change that only affects what happens after the actual recording has finished. Also, the demo reference port PrBoom+ already has this by default and apparently people are expecting and requesting this feature.

**Comment by JNechaevsky** [comment]
Thank you, awesome feature and job!

I was having a small additional thought - move some "You are here" patches around, so they will not be overlayed by level name (probably only Dis is affected), but nope, it will harm some gfx placements in some kind of total conversions. In other words, it's not safe for visual compatibility.

**Comment by fabiangreffrath** [comment]
Nope, I am not comfortable with moving around these patches, either.

What could help, though, is a better position for the E1M10 blood splat. It is currently taken from the E2M1 position, but maybe there are other positions on the map that fit better? I don't know...

**Comment by JNechaevsky** [comment]
Is it "Sewers" map? No problem, I'll try to find a suitable place, got some thoughts already.

**Comment by fabiangreffrath** [comment]
The point is, I'd rather not add a new X/Y cordinate pair, but take one of the existing ones for E2 and E3. It doesn't necessarily have to be the one from E2M1, though, that's more or less by accident.

**Comment by JNechaevsky** [comment]
Ouch. Okay, will do as you say.

**Comment by JNechaevsky** [comment]
Uh.. How can access E1M10? And must it be in a IWAD?

**Comment by fabiangreffrath** [comment]
For the record: It is sufficient if you have a map lump called `E1M10` and a graphics lump called `sewers` with the map name for the intermission screen. If you like you could just create copies of e.g. `E1M1` and `WILV00` with SLADE and rename them.

**Comment by fabiangreffrath** [comment]
Alternatively, there are binary patches available to convert one version of an IWAD into any other:

https://github.com/Doom-Utils/iwad-patches

**Comment by JNechaevsky** [comment]
Oh yes, that helps, thanks.

Interesting, according to the video recorded from console version, E2M1's patch placement seems to be "official":

- https://youtu.be/t0XwIuMJYMU?t=63 (from 1:03)
- [Screenshot](https://user-images.githubusercontent.com/21193394/56013498-a1a3f600-5cf9-11e9-8bbb-b8697cbb5a34.png) from video

Kinda odd, but maybe we should leave it as is because of this "official placement"? I was thinking about placing arrow somewhere to bottom-right corner, just like with Warrens map, because it will not be far from Hangar. 

Anyways, what the plan? We leave it as is, or should I try E3M9 placement? I'm recommending "as is" approach, but if you insist on trying something else, sure, let's try then.

**Comment by fabiangreffrath** [comment]
Where else would you have put the blood splat? I think it should be either close to e1m1 and e1m2 -- or completely far off as it is now. There are exactly 9 buildings visible on the map already, one for each regular mso, so where is the best place to add sewers?

**Comment by fabiangreffrath** [comment]
Saw your reply just too late! I agree, let's leave it as it is.
