### ISSUE TITLE
Zoom automap by mouse wheel

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#405]
PrBoom+ offering an useful thing - automap zooming by mouse wheel. How do you think, maybe it is worth to implement it also in Crispy? For now, mouse wheel is cycling weapons and moving cursor in game menus. 

I haven't tried yet, but probably `automapactive` condition could do this trick.

Also, maybe it is worth to make automap scrollable by moving mouse if `F` mode, but: 

1. Not sure it's a good idea
2. Not sure it is safe for demos

_Suggestion №103_

**Comment by fabiangreffrath** [comment]
I agree that it makes sense not to change the weapon (but zoom in/out instead) if you cannot see its sprite while the Automap is enabled. What should we do, though, when the overlay mode is active?

**Comment by JNechaevsky** [comment]
I suppose, if automap is active, it should have a higher priority, and in fact, zoom should happen.

But (1) - overlayed automap is mostly used as a "background", so it probably should not have a priority, and wheel must act as a weapon cycling.
But (2) - cycling weapons, especially when you need to do it quickly, though the wheel is certainly not good idea, and probably no one will do it. I'm meaning situations when player should quickly change his his weapon, not a common situations. For example, I'm using wheel sometimes while playing, but never while fighting.

So I think it will be okay to make a zoom even if overlay mode is active.

**Comment by fabiangreffrath** [comment]
```
diff --git a/src/doom/am_map.c b/src/doom/am_map.c
index d6bf46e6..9ac177b2 100644
--- a/src/doom/am_map.c
+++ b/src/doom/am_map.c
@@ -102,6 +102,10 @@
 // pulls out to 0.5x in 1 second
 #define M_ZOOMOUT       ((int) (FRACUNIT/1.02))
 
+// [crispy] zoom twice as fast with the mouse wheel
+#define M2_ZOOMIN       ((int) (1.02*1.02*FRACUNIT))
+#define M2_ZOOMOUT      ((int) (FRACUNIT/1.02/1.02))
+
 // translates between frame-buffer and map distances
 // [crispy] fix int overflow that causes map and grid lines to disappear
 #define FTOM(x) (((int64_t)((x)<<FRACBITS) * scale_ftom) >> FRACBITS)
@@ -694,6 +698,24 @@ AM_Responder
 	    rc = true;
 	}
     }
+    // [crispy] zoom Automap with the mouse wheel
+    else
+    if (ev->type == ev_mouse && !crispy->automapoverlay)
+    {
+	if (mousebprevweapon >= 0 && ev->data1 & (1 << mousebprevweapon))
+	{
+		mtof_zoommul = M2_ZOOMOUT;
+		ftom_zoommul = M2_ZOOMIN;
+		rc = true;
+	}
+	else
+	if (mousebnextweapon >= 0 && ev->data1 & (1 << mousebnextweapon))
+	{
+		mtof_zoommul = M2_ZOOMIN;
+		ftom_zoommul = M2_ZOOMOUT;
+		rc = true;
+	}
+    }
     else if (ev->type == ev_keydown)
     {
 	rc = true;
@@ -851,6 +873,12 @@ void AM_changeWindowScale(void)
     scale_mtof = FixedMul(scale_mtof, mtof_zoommul);
     scale_ftom = FixedDiv(FRACUNIT, scale_mtof);
 
+    // [crispy] reset after zooming with the mouse wheel
+    if (ftom_zoommul == M2_ZOOMIN || ftom_zoommul == M2_ZOOMOUT)
+    {
+	ftom_zoommul = FRACUNIT;
+    }
+
     if (scale_mtof < min_scale_mtof)
 	AM_minOutWindowScale();
     else if (scale_mtof > max_scale_mtof
```

**Comment by fabiangreffrath** [comment]
> But (1) - overlayed automap is mostly used as a "background", so it probably should not have a priority, and wheel must act as a weapon cycling.

I agree with this!

**Comment by JNechaevsky** [comment]
Awesome! Please wait until evening, I'll check with small/huge maps and other possible cases, just to make sure that things are fine as always.

**Comment by fabiangreffrath** [comment]
Cool, thanks!

**Comment by JNechaevsky** [comment]
Done some tests. Technically, it's working just fine, and here's my recommendations:

- Increase zooming speed to `3x`, because `2x` is a bit slow, and player will have to spin mouse wheel a lot. AFAIK, there is no meaning of "mouse wheel speed" on any OS, it is possible to just tweak amount of scrolled lines, at least on Windows. Also, `3x` is pretty similar to PrBoom, and I think other players will be happy to have a similar behavior between ports. As about map sizes, this speed is adequate for huge maps like sunder.wad MAP08, and Doom II Entryway.
- Disable zooming while game menu is active. If I have an opened menu and scrolling it by mouse wheel, automap is also zooming.
- Same while `inhelpscreens`.
- ... for "Paused" and dead states it is totally proper to allow to zoom, this is okay.

A small extra thoughts, which I can't suggest. Just for the record:

- If "show player coords" is enabled, it will be cool to have an extra item: "Zoom level". But no. First of all, unlike map editor, there is no static "zoom level" meaning, automap size and it's max/mix zoom factors are calculated via map size itself. And by the way, placing yet another widget, even while `automapactive` is another possible headache.
- Heretic offers an cool feature with line antialiasing in automap. It's looking cool, but "smooth" values (`PLAYPAL` color numbers in fact) are hardcoded, and in case of using a very custom `PLAYPAL` in some kind of TC, something definitely not good may happen with antialiasing colors. Another problem, automap code in Heretic is even more complicated.

**Comment by fabiangreffrath** [comment]
> * Increase zooming speed to `3x`, because `2x` is a bit slow, 

This would have to be `4x`, because `1.02 x 1.02 = 1.04`. :grin:

> * Disable zooming while game menu is active. If I have an opened menu and scrolling it by mouse wheel, automap is also zooming.

Interesting, `M_Responder()` should have eaten this event.

> * If "show player coords" is enabled, it will be cool to have an extra item: "Zoom level". But no. First of all, unlike map editor, there is no static "zoom level" meaning, automap size and it's max/mix zoom factors are calculated via map size itself. And by the way, placing yet another widget, even while `automapactive` is another possible headache.

Indeed, I assume this would only be of little help.

> * Heretic offers an cool feature with line antialiasing in automap. 

Maybe later...

**Comment by JNechaevsky** [comment]
> This would have to be 4x, because 1.02 x 1.02 = 1.04. grin

Christ! Good thing you never asked me about my grades in mathematics... Erm, I mean, hey, I'm an artist, that's my vision! Yeah, that's it. :neckbeard:

> Indeed, I assume this would only be of little help.

Oh, I've actually forgot about "full zoom" by pressing `0`. This could be a `1.0` zoom level, probably.

> Maybe later...

I'm asking to be careful there, because for me, reading such a deadly simple formulas / code is like reading runes of Black Magic. I barely can understand just a few functions there.

**Comment by fabiangreffrath** [comment]
```
diff --git a/src/doom/am_map.c b/src/doom/am_map.c
index d6bf46e6..8dc56c83 100644
--- a/src/doom/am_map.c
+++ b/src/doom/am_map.c
@@ -46,6 +46,7 @@
 #include "dstrings.h"
 
 #include "am_map.h"
+extern boolean inhelpscreens; // [crispy]
 
 
 // For use if I do walls with outsides/insides
@@ -102,6 +103,10 @@
 // pulls out to 0.5x in 1 second
 #define M_ZOOMOUT       ((int) (FRACUNIT/1.02))
 
+// [crispy] zoom faster with the mouse wheel
+#define M2_ZOOMIN       ((int) (1.08*FRACUNIT))
+#define M2_ZOOMOUT      ((int) (FRACUNIT/1.08))
+
 // translates between frame-buffer and map distances
 // [crispy] fix int overflow that causes map and grid lines to disappear
 #define FTOM(x) (((int64_t)((x)<<FRACBITS) * scale_ftom) >> FRACBITS)
@@ -694,6 +699,24 @@ AM_Responder
 	    rc = true;
 	}
     }
+    // [crispy] zoom Automap with the mouse wheel
+    else
+    if (ev->type == ev_mouse && !crispy->automapoverlay && !menuactive && !inhelpscreens)
+    {
+	if (mousebprevweapon >= 0 && ev->data1 & (1 << mousebprevweapon))
+	{
+		mtof_zoommul = M2_ZOOMOUT;
+		ftom_zoommul = M2_ZOOMIN;
+		rc = true;
+	}
+	else
+	if (mousebnextweapon >= 0 && ev->data1 & (1 << mousebnextweapon))
+	{
+		mtof_zoommul = M2_ZOOMIN;
+		ftom_zoommul = M2_ZOOMOUT;
+		rc = true;
+	}
+    }
     else if (ev->type == ev_keydown)
     {
 	rc = true;
@@ -779,7 +802,6 @@ AM_Responder
         else if (key == key_map_overlay)
         {
             // [crispy] force redraw status bar
-            extern boolean inhelpscreens;
             inhelpscreens = true;
 
             crispy->automapoverlay = !crispy->automapoverlay;
@@ -851,6 +873,13 @@ void AM_changeWindowScale(void)
     scale_mtof = FixedMul(scale_mtof, mtof_zoommul);
     scale_ftom = FixedDiv(FRACUNIT, scale_mtof);
 
+    // [crispy] reset after zooming with the mouse wheel
+    if (ftom_zoommul == M2_ZOOMIN || ftom_zoommul == M2_ZOOMOUT)
+    {
+	mtof_zoommul = FRACUNIT;
+	ftom_zoommul = FRACUNIT;
+    }
+
     if (scale_mtof < min_scale_mtof)
 	AM_minOutWindowScale();
     else if (scale_mtof > max_scale_mtof)
```

I still like the idea of moving the map with the mouse if `followplayer` is off...

**Comment by JNechaevsky** [comment]
> I still like the idea of moving the map with the mouse if followplayer is off...

Actually, yes! I was thinking about it, but was afraid to suggest by very simple reason - despite of it's awesome usability, will it be safe for demos?

**Comment by fabiangreffrath** [comment]
> Actually, yes! I was thinking about it, but was afraid to suggest by very simple reason - despite of it's awesome usability, will it be safe for demos?

Yes, if `AM_Responder()` is told to eat the mouse event, so it is never passed through to the actual game.

**Comment by fabiangreffrath** [comment]
I have updated the patch, could you please give it another try (especially regarding demo recording/playback with mouse movement in Automap) before I commit it?

**Comment by JNechaevsky** [comment]
Sure, with great pleasure, but traditionally - only in the evening. I think making a demo with walking on / by zigzag / through Entryway will be enough for testing.

**Comment by fabiangreffrath** [comment]
Sure, thanks!

**Comment by JNechaevsky** [comment]
Looks likes everything is fine! Here, my goal to was reach the exit while walking with opened automap in `F` mode:

- Demo itself [mouse.zip](https://github.com/fabiangreffrath/crispy-doom/files/3121988/mouse.zip) (fine to play with `-timedemo`)
- And screen record: https://youtu.be/45u9cVs0icg (to see what's really was happened and why I was moving so odd)

Just one small extra thought: zooming speed is absolutely good, but scrolling speed is too fast, it feels much different from zooming. Is it possible to make it slower?
