### ISSUE TITLE
Possible small optimization in HUD (traditional only)

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#407]
There is very interesting optimization in Heretic's status bar code, have a look:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/heretic/sb_bar.c#L832

What it does in short words: while status bar updating loop, this condition is preventing to invoke some numbers update routine (patch redrawing and recalculating digits value). Just like with gray status bar background, which is not updating every tic, but only when necessary.

AFAIR, in Doom status bar digits are redrawing every tic. Maybe it's worth to apply this small optimization to don't invoke digits widget updating if no changes were made in the health, armor, ammo and other values?

Have to be careful, though - updating of widget color is still needed for proper color update in colored HUD.

_Suggestion №105_

**Comment by mfrancis95** [comment]
If this is just an optimisation and doesn't affect anything visually, would it be better brought to Chocolate?

**Comment by JNechaevsky** [comment]
It may be considered as a non-canonical code changing. Better do not touch Chocolate code with things like this.

**Comment by mfrancis95** [comment]
We've done optimisations in Chocolate before. https://github.com/chocolate-doom/chocolate-doom/issues/976

**Comment by fabiangreffrath** [comment]
@mfrancis95 I see it a bit different. The commit you are referring to is merely enabling an optimization that has been introduced at a lower level. It does not mean fiddling around in the code in a non-canonical way in order to gain some micro-FPS.

**Comment by fabiangreffrath** [comment]
There is already some similar code in `st_lib.c`:
https://github.com/fabiangreffrath/crispy-doom/blob/346ad0295645b6e4b877dd6025b80c18b853b822/src/doom/st_lib.c#L86

Note that there is a `refresh` parameter to `STlib_drawNum()` that is passed all the way through `STlib_updatePercent()` and `STlib_updateNum()` - but is never actually checked in `STlib_drawNum()`.  I guess if we could add a check here, this would get very close to the code from Heretic that you pointed to.

**Comment by fabiangreffrath** [comment]
```
--- a/src/doom/st_lib.c
+++ b/src/doom/st_lib.c
@@ -97,6 +97,12 @@ STlib_drawNum

     int                neg;

+    // [crispy] redraw only if necessary
+    if (n->oldnum == num && !refresh)
+    {
+       return;
+    }
+
     n->oldnum = *n->num;

     neg = num < 0;

```
