### ISSUE TITLE
Improve colors for HUD digits

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#409]
There is a huge visual difference between tablified (old) and HSV (new) colorization in HUD digits. Old approach giving much more proper and juicy colors, take a look:

![hud-colors](https://user-images.githubusercontent.com/21193394/56714572-e25e2f00-673d-11e9-981d-9b18092029b3.png)

I have tried to play around with HSV colorization in HUD, but no luck, especially with gold color... How do you think, maybe it is worth to apply old `red-to-something` for standard unmodified Doom digits?

If I remember correctly, improving was planned for true color rendering, but true color rendering have few serious blockers, and probably will not come at all.

_Suggestion №106_

**Comment by fabiangreffrath** [comment]
The point is that in the HSV color conversion, each source color is converted to the same destination color but with varying intensity based on the source color's intensity. In the static conversion tables, though, different shades of red in the source colors are converted to different shades of yellow/gold in the destination colors. I once tried to emulate this in the HSV conversion code by means of a linear interpolation, but apparently wasn't satisfied enough with the results. The code is still there if you would like to play with it:

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/v_trans.c#L292

**Comment by JNechaevsky** [comment]
Thanks for explanation! I know this difference already, and was having some experience with current HSV approach.

> The code is still there if you would like to play with it:
> https://github.com/fabiangreffrath/crispy-doom/blob/master/src/v_trans.c#L292

That's what I was trying yesterday, and was not lucky with satisfying results. I need to try harder, i.e. **much** harder then. It is not an operating with graphical pixels, so I do not want to give an empty promises about the results, but I'll try do my best. Please don't close this issue until I'll will be able to show some results or, well, until I give up.

**Comment by fabiangreffrath** [comment]
So, how about this?
```
	if (cr == CR_GOLD)
	{
//	    hsv.x = 45./360.;
	    hsv.x = (60. * hsv.z + 45. * (1. - hsv.z))/360.;
	}
```

**Comment by fabiangreffrath** [comment]
And how about this for green?
```
	if (cr == CR_GREEN)
	{
//	    hsv.x = 135./360.;
	    hsv.x = (150. * hsv.z + 120. * (1. - hsv.z))/360.;
	}
```

**Comment by fabiangreffrath** [comment]
Red and blue should be no problem, since all relevant palette colors already have the same HSV color index.

**Comment by JNechaevsky** [comment]
>So, how about this?

Ouch. This looking better is some parts, but now yellow chars have even more notable bright-yellow color :(

![gold_old_new](https://user-images.githubusercontent.com/21193394/56758210-c2128c80-679e-11e9-8548-180b4d365ee1.png)

Have to seek other approach, but having just a little amount of yellow color ties hands badly.

---------

> And how about this for green?

That's really good! HUD digits will now have just a little bit more colors and have a better lighting, but take a look at Crispness menu, now new green chars are looking much more fresh!

![green_old_new](https://user-images.githubusercontent.com/21193394/56757620-5845b300-679d-11e9-99ed-6f349e5d1787.png)

Absolutely lovely! :green_heart:

I was going to start from `hsv.x = 117./360.`, because "most" green in Doom is not a `r:0 g:255 b:0`, it's a `r:119 g:255 b:111` (in HSV it's a `h:117 s:56 v:100`), but your approach if far better already.

What stand behind your formula? What's the secret?

---------

> Red and blue should be no problem

Agreed completely, blue is totally okay.

**Comment by fabiangreffrath** [comment]
> What stand behind your formula? What's the secret?

There is no secret behind it. :wink: 

The formula means that lighter source colors (i.e. the ones for which `hsv.z` -- the V in HSV -- is close to `1.0`) will get mapped to a different destination color than darker source colors for which `(1. - hsv.z)` is closer to `1.0`. This and a picture of the Doom palette and the Gimp's color picker. :grin: 

How would you like if we extend the golden range a bit further into the orange?
```
hsv.x = (60. * hsv.z + 30. * (1. - hsv.z))/360.;
```

**Comment by JNechaevsky** [comment]
> How would you like if we extend the golden range a bit further into the orange?

Ehh. Colors becomes a little bit more contrast, but in general all the same. If only we can get rid of that shining-bright yellow somehow, that's will change everything. I'm a bit tired for today to properly reproduce your approach (thanks for explanation!), so just an idea for now...

![gold_old_new](https://user-images.githubusercontent.com/21193394/56767855-76b7a880-67b5-11e9-85ab-356eb5da272d.png)

This bright yellow color is `r:255 g:255 b:115` / `h:60 s:55 v:100` (№160 in [PLAYPAL](https://i2.wp.com/www.jeffreythompson.org/blog/wp-content/uploads/2013/03/DoomColorPalette.gif?zoom=1.25&resize=522%2C522)). What if we reduce maximum brightness (`z`?) to 92-91, just like with next yellow color №161?

**Comment by fabiangreffrath** [comment]
Sorry, I don't have a vision for this. For me this is "oh, orange with some yellow, cool!" :grin: 

Sure, we could either reduce source color brightness, or we could move the yellow end of the color range more towards the orange, e.g. 
```
hsv.x = (50. * hsv.z + 30. * (1. - hsv.z))/360.;
```

**Comment by JNechaevsky** [comment]
> hsv.x = (50. * hsv.z + 30. * (1. - hsv.z))/360.;

Oh yes, I see the difference, now colors becomes "a little bit orange", and this is definitely better! Another important thing - it's not too notable, so no one will get confused about the change. 

Take a look at `0` in old value, at the left side of the digit. There are few pixels which are colored brown (by mixing with yellow they looks like green), and in new approach they are fine! There is also more available colors in "new".

![gold_old_new](https://user-images.githubusercontent.com/21193394/56822298-4fb2b280-6859-11e9-8084-8058cb6f1d34.png)

I can't suggest anything better, because writing down formula by such magical values is still a bit confusing for me. For all my life I was choosing colors in this window ([screenshot](https://user-images.githubusercontent.com/21193394/56822405-9e604c80-6859-11e9-9852-bb24376a4a92.png)) and you did everything far better. 

Guess, everything is done here. :relieved:

**Comment by JNechaevsky** [comment]
Small afterword. Do you want to see some magic? Take a look, at the right variant, especially at "X" char, there are more colors and brightness of yellow color seems to be normalized.

![MAGIC](https://user-images.githubusercontent.com/21193394/56843691-9d0c3f80-68ac-11e9-87b3-a66f4c2c47d0.png)

I haven't touched v_trans.c. So what is the secret? I've just tried to run Crispy with my improved palette and nothing more.

Really no idea why how this improvement may happen, I'm using absolutely same colors as in original PLAYPAL, just with heavily tweaked brightness/contrast/gamma. But what really important here - your formulas are perfectly fine, the _real_ problem is a standard PLAYPAL.

**Comment by fabiangreffrath** [comment]
Still no magic. :wink: The difference is that now, instead of mapping colors to a single destination color hue, I am mapping them to a range of hues: Lighter colors get mapped more towards the yellow, darker colors more towards the orange. This results in a wider range of destination colors.

Of course, this scales with how balanced the underlying palette already is. If there are more color indices available in the destination range, it will be easier for the algorithm to find a fitting one for each source color.

**Comment by JNechaevsky** [comment]
This explains much! I was absolutely sure that `hsv.x`, even after making formulas, in the end just a single integer value. Needles to say that I'm happy to know I was wrong.

P.S. Just got an very odd flashing thought: if original palette is always 256 colors and 768 bytes, what the rest of other colors will be hardcoded into executable by this formula: `(256 * 256 * 256) - 256`? I.e. "high color" values - 256 original colors. Ah, nevermind, AFAIK, SDL itself in the engine is placing all colors via PLAYPAL values, so the rest of other colors will be ignored. Probably. Oh, nevermind, guess I was drawing too much today, from 3:30 till now (21:30).

**Comment by fabiangreffrath** [comment]
> I was absolutely sure that `hsv.x`, even after making formulas, in the end just a single integer value.

It is a single integer value, but a different one depending on the source color's `hsv.z` value -- but I guess this is what you meant.

However, your "afterword" shows that we are still not there yet for the golden color range. I don't like, for example, that the X glyph is all a single color. I have played a bit with more radical values for the borders of the color range, e.g. `hsv.x = (60. * hsv.z + 0. * (1. - hsv.z))/360.;` and this vastly increases the number of colors used in each glyph, but has some other drawbacks, like a dark border around the status bar numbers. Oh my...

**Comment by JNechaevsky** [comment]
> It is a single integer value, but a different one depending on the source color's hsv.z value -- but I guess this is what you meant.

Yep, I was meaning dependence from `z`, not just a bare `x`, which I was using.

> hsv.x = (60. * hsv.z + 0. * (1. - hsv.z))/360.;

Despite of good visual amount of colors, it feels even more "juicy", a bit too aggressive, comparing with other colored chars. I would like to don't recommend to use it.

_______

A couple of extra thoughts:

**1.** We may check for unmodified original HUD digits (@bradharding created one [here](https://github.com/bradharding/doomretro/blob/master/src/w_wad.c#L398), which I'm happily using for catching modified resources in PWADs). Next logic is blazing simple:
* If digits are unmodified, use old tablified approach.
* If digits are modified, use new HSV approach.

But there will be two notable problems:

* It's not a "one logic" approach, which AFAIK, you are always prefer to use.
* It is okay for catching HUD digits, but what to do with STCFN* fonts? Catch all the characters? Or only first one? And what if there first one will be same, but only some of characters will be changed? 

If there wasn't any mods for Doom, life can be much easier and things can be better, to be honest...

**2.** (Just for the record) I don't know if there is any any existing LUT for "high color" values, neither I don't see any way to automate it's creation - Pohotoshop is allowing to save only 256 colors per indexed palette, other graphical editors probably too (because it's a golden standard).

So, for example, to have a simple LUT of `TRANMAP`, I'll have to literally cut 65536 colors to separate files with 256 colors (256 files total), save each of them and join all 256 into one. Good thing there is no three bytes header, and color values are placed "from left to right" in both graphical editor and exported file.

Okay, doing in 256 times is not an horrible amount of work to have a nice LUT like this:

![COLORMAP](https://user-images.githubusercontent.com/21193394/56859834-fb165100-6998-11e9-83ff-4e53b343a827.png)

But in case of creating LUT for high color mode... This operation must be done 65536 times. And trying to imagine amount of work for the engine to making a lookup every tic 50 MB LUT file (65536 * 3) is... Oh oh well.  At least it's clear enough that this is not a way to go.

**Comment by fabiangreffrath** [comment]
> Despite of good visual amount of colors, it feels even more "juicy", a bit too aggressive, comparing with other colored chars. I would like to don't recommend to use it.

Alright, last try, how about
```
hsv.x = (60. * hsv.z + 20. * (1. - hsv.z))/360.;
```

>     * It's not a "one logic" approach, which AFAIK, you are always prefer to use.

Indeed, that's not very Crispy.

I prefer a good color translation logic that applies well enough to all use cases over a solution that's perfect for the simple case but fails for all others.

**Comment by JNechaevsky** [comment]
> hsv.x = (60. * hsv.z + 20. * (1. - hsv.z))/360.;

![Untitled-1](https://user-images.githubusercontent.com/21193394/56860620-4af91600-69a1-11e9-982f-5d2cc0cb4b4d.png)

Some orange colors become more "notably agressive", and now there is more "stinky notable" yellow. :/

**Comment by fabiangreffrath** [comment]
Okay, middle ground:
```
hsv.x = (55. * hsv.z + 25. * (1. - hsv.z))/360.;
```

**Comment by JNechaevsky** [comment]
![Untitled-1](https://user-images.githubusercontent.com/21193394/56861550-7b917d80-69aa-11e9-8da1-05b8de032728.png)

By making an very close look, I don't see _any_ difference in the colors, except there is now a little bit more "awfully bright yellow". :confused:

**Comment by fabiangreffrath** [comment]
:weary: Do you have any other suggestion?

**Comment by fabiangreffrath** [comment]
Maybe
```
hsv.x = (50. * hsv.z + 20. * (1. - hsv.z))/360.;
```

**Comment by JNechaevsky** [comment]
I still can't suggest anything better, sadly. This way yellow becomes a bit more orange, and some characters like `A` have a slightly more colors. Hm... For some reason, this way "notable yellow" is feeling less notable, probably because of rest of colors become more contrast (it's an inner visual feeling, hard to explain).

![Untitled-1](https://user-images.githubusercontent.com/21193394/56862475-0b87f500-69b4-11e9-83b8-6e209199fece.png)

Have a look at `A`, there is more color info now:

![Untitled-1](https://user-images.githubusercontent.com/21193394/56862511-7a654e00-69b4-11e9-8062-9885b9fabae6.png)

Looks likes, it good to use this formula.

**Comment by fabiangreffrath** [comment]
Okay, I have to come up with another formula:
```
	    hsv.x = (7.0 + 53. * hsv.z)/360.;
	    hsv.y = 1.0 - 0.4 * hsv.z;
	    hsv.z = 0.2 + 0.8 * hsv.z;
```

This should resemble the original gold color translation table from Boom pretty closely. What's interesting is if you comment out the `hsv.y` line or the `hsv.z` line or even both. Would you mind telling me what you think about this variant?

**Comment by JNechaevsky** [comment]
Commenting out `both`: **too** agressive!
Commenting out `hsv.z`: interesting color, but it's no longer yellow/gold, it's a... Wet yellow? Anyways, color's saturation is low.
Commenting out `hsv.y`: too err... too notable. Not sure how to explain. Not too bright, not too contrast. But feels wrong.

Not commenting anything: Pure and True gold we was seeking for! Absolutely must be used!

**Comment by fabiangreffrath** [comment]
> Not commenting anything: Pure and True gold we was seeking for! Absolutely must be used!

That's what I wanted to read, thanks!

**Comment by JNechaevsky** [comment]
I know already that you know Black Magic, and now I know that you know Alchemy!
If Crispy could have a version code names, upcoming version could be an "alchemist stone" or "seekers of True Gold". :)

**Comment by fabiangreffrath** [comment]
Why not, 1.5 and 2.0 did already have release names, but I somehow lost interest in this. However, when it fits to a release I am all for it.

So, do you think that we now have satifactory color translation tables or is there anything left that we need to adjust?

**Comment by JNechaevsky** [comment]
> However, when it fits to a release I am all for it.

No-no, I'm not suggesting any name. I'm not a big fun of such approach - for my personal taste there must be exactly one baptised name for the project and version number.

> So, do you think that we now have satifactory color translation tables or is there anything left that we need to adjust?

Speaking for myself - absolutely. It's grows much higher than I was suggesting / excepting. Also, there no more `CR_*` palettes to care about, so I think everything is done.

**Comment by fabiangreffrath** [comment]
> everything is done

:muscle:

**Comment by JNechaevsky** [comment]
@fabiangreffrath, awful offtopic, but... Can I disable `docgen` in MSYS compilation somehow? I don't need Linux-style docs on Windows, and they are re-creating every build, which takes more time than composing an executable file.

Alternatively, is it worth to do it in Choco? Perhaps, some kind of macro like... Hm. Looks line I don't know how make an exclusive macro. Could it be a:
```
#ifdef !WIN32 (or #ifndef?)
    docgen ...
#endif
```

**Comment by fabiangreffrath** [comment]
Try *not* to have python installed, does this fo the trick?

**Comment by JNechaevsky** [comment]
Un-uh. After removing python-3.7.3-1 by:
```
# pacman -R python
```

I've got this:
```
make[3]: entering «/home/Julian/crispy-doom/textscreen/fonts»
./convert-font large large.png large.h
/usr/bin/env: «python»: No such file or directory
make[3]: *** [Makefile:450: large.h] Ошибка 127
make[3]: leaving «/home/Julian/crispy-doom/textscreen/fonts»
make[2]: *** [Makefile:487: all-recursive] Error 1
make[2]: leaving «/home/Julian/crispy-doom/textscreen»
make[1]: *** [Makefile:502: all-recursive] Error 1
make[1]: leaving «/home/Julian/crispy-doom»
make: *** [Makefile:418: all] Error 2
```

**Comment by fabiangreffrath** [comment]
You'll have to re-run ./configure

**Comment by JNechaevsky** [comment]
Oh yes, that's worked. Thanks! It will save a lot of time!
