### ISSUE TITLE
Chex: own automap colors

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#412]
A small suggestion for Chex. What if it can have a custom, own automap colors?

For extended scheme:
![chex_extended](https://user-images.githubusercontent.com/21193394/56844005-e90db300-68b1-11e9-979a-a467a30d123e.png)

For traditional scheme:
![chex_traditional](https://user-images.githubusercontent.com/21193394/56844026-81a43300-68b2-11e9-8ee7-e4e5aa709178.png)

_Suggestion №107_

**Comment by fabiangreffrath** [comment]
I considered this myself before. But I was afraid that with such a change, Chex will become "too green" overall. Do you know what I mean?

**Comment by JNechaevsky** [comment]
I think yes. Well, you're right. In Doom we have a mostly red automap, red font and menus, but much other than red colored enemies. Alternatively, not-only-green color may be used, maybe with a little mix with yellow. Should I try it?

**Comment by fabiangreffrath** [comment]
Hm, this would clutter Automap code even more -- but if you have an idea, why not try it?

**Comment by fabiangreffrath** [comment]
After one year of inactivity, I guess this really isn't that important.
