### ISSUE TITLE
add widescreen rendering

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#413]
The idea is to probe the screen's dimensions (e.g. 1280x768), scale them down to WIDTHx200 and adjust field-of-view and centered patch drawing to the difference between WIDTH and 320.

**Comment by Zodomaniac** [comment]
Will this result in preserving the pixel aspect ratio but using the full monitor field of view?

**Comment by fabiangreffrath** [comment]
Yep, that's the plan.

**Comment by Zodomaniac** [comment]
I'd like to keep the option to adjust the pixel aspect ratio still.

**Comment by fabiangreffrath** [comment]
Yes, aspect ratio correction will still be there. 
I'd like to call it "widescreen rendering", btw, because this is what it actually is about.

**Comment by Zodomaniac** [comment]
How will the title screens and menu be rendered? Will they be stretched the same way as for unconstrained aspect ratio now?
Will the renderer be still 16:10 (640x400, 320x200)?

**Comment by fabiangreffrath** [comment]
> How will the title screens and menu be rendered? Will they be stretched the same way as for unconstrained aspect ratio now?

I think they will be rendered with the correct aspect ratio and with black vertical bars left and right.

> Will the renderer be still 16:10 (640x400, 320x200)?

No, the horizontal resolution (and thus field-of-view) will have to get increased.

**Comment by Zodomaniac** [comment]
Yes, I like it this way :)

**Comment by Zodomaniac** [comment]
Actually the 16:10 widescreen option in Doom Retro was done this way, changing the FOV and not the pixel aspect ratio. But on 16:9 monitors it's still letterboxed.

**Comment by fabiangreffrath** [comment]
> Actually the 16:10 widescreen option in Doom Retro was done this way, changing the FOV and not the pixel aspect ratio. But on 16:9 monitors it's still letterboxed.

Erm... last time I checked this was merely the view with the status bar, but with the status bar cut off.

**Comment by Zodomaniac** [comment]
Here's what the widescreen in Doom Retro looks like: 1728x1080 (16:10) preserving the 1.2 pixel aspect ratio and letterboxed on 1920x1080 (16:9) monitor.
![Entryway](https://user-images.githubusercontent.com/15119473/59667742-e055a100-91bf-11e9-8b7e-8a2cf4afaa85.png)
