### ISSUE TITLE
SSG reloading sounds still can be breaked by 'oof'

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#416]
When "full sounds" are on. Can be fixed easily:

**A_OpenShotgun2**
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_enemy.c#L1844
```
---    S_StartSound (player->mo, sfx_dbopn);
+++    S_StartSound (player->so, sfx_dbopn); // [crispy] weapon sound source
```
**A_LoadShotgun2**
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_enemy.c#L1854
```
---    S_StartSound (player->mo, sfx_dbload);
+++    S_StartSound (player->so, sfx_dbload); // [crispy] weapon sound source
```

**A_CloseShotgun2**
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_enemy.c#L1870
```
---    S_StartSound (player->mo, sfx_dbcls);
+++    S_StartSound (player->so, sfx_dbcls); // [crispy] weapon sound source
```

I wonder why id decided to place this SSG code to p_enemy.c...

**Comment by fabiangreffrath** [comment]
Indeed, that's a strange location, thanks for finding it!
