### ISSUE TITLE
Setup does not detect x360 controller

### ISSUE THREAD

**Issue by Kizoky** [fabiangreffrath/crispy-doom#417]
### Background

Version of Crispy Doom: crispy-doom-20190524-win32

Operating System and version: Windows 10 Home (1809)

Game: All

Any loaded WADs and mods (please include full command line):
none

### Bug description

Observed behavior:
Setup says no gamepads or joysticks are found

Expected behavior:
It should be able to detect the x360 gamepad
(Chocolate Doom can detect it, 3.0.0)

**Comment by fabiangreffrath** [comment]
Does a chocolate doom daily build detect the controller? Does it help if you copy the sdl*.dll files over from the chocolate doom 3.0.0 release?

**Comment by Kizoky** [comment]
Just checked, even the daily build of Chocolate Doom can't detect it either, however the 3.0.0 can detect it just fine

And yes, it does help, copying all the SDL* files from the 3.0.0 release to Crispy Doom's folder now detects my controller

**Comment by fabiangreffrath** [comment]
> Just checked, even the daily build of Chocolate Doom can't detect it either, however the 3.0.0 can detect it just fine

Please do me a favour and report this over at the Chocolate Doom bug tracker, thanks!
