### ISSUE TITLE
Were there any changes to translucency? Some items don't look very good

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#420]
Blinking moment with transparency
![DOOM0003](https://user-images.githubusercontent.com/15119473/59083223-33497180-88ff-11e9-8afb-74e46dcd67f0.png)
Without it, for comparison
![DOOM0004](https://user-images.githubusercontent.com/15119473/59083244-48260500-88ff-11e9-982f-d5894f230cfd.png)

**Comment by fabiangreffrath** [comment]
No changes recently if you are using the palette renderer, which you seem to. Blue has always been a problem with translucency, especially with dark backgrounds. What we see here is nothing new, just the best we can get with palette colors.
