### ISSUE TITLE
Support Music Packs in WAD

### ISSUE THREAD

**Issue by pmjdebruijn** [fabiangreffrath/crispy-doom#424]
Crispy currently doesn't seem to support the SIGIL_SHREDS.WAD replacement music, and it would be rather nice if it would in the future.

I made a script that converts the SC55 FLACs to a WAD that should be nearly technically identical:

[musicwadenc.sh.txt](https://github.com/fabiangreffrath/crispy-doom/files/3287419/musicwadenc.sh.txt)

**Comment by Zodomaniac** [comment]
>Crispy currently doesn't seem to support the SIGIL_SHREDS.WAD

The daily build already does :) it's available at latest.chocolate-doom.org.
Crispy plays FLAC, OGG and MP3 music from WADs.

**Comment by fabiangreffrath** [comment]
If the music backend is set to "native midi", that is. Anyway, nothing left to do here.

**Comment by pmjdebruijn** [comment]
Now you mention it I do recall reading about that some time ago. But apparently I forgot again.

One could argue (from a usability perspective) that if replacement audio is being provided, any settings with regard to midi rendering should ideally be ignored/overridden?

**Comment by Zodomaniac** [comment]
>if replacement audio is being provided, any settings with regard to midi rendering should ideally be ignored/overridden?

Aren't they already ignored? I have Native MIDI set and all kinds of MP3/OGG/FLAC in WADs play for me.

**Comment by pmjdebruijn** [comment]
What I mean is, when replacement audio is being explicitly provided should that option matter at all?

**Comment by Zodomaniac** [comment]
That option doesn't matter, or does it in your case?

**Comment by pmjdebruijn** [comment]
It very much does. However for clarity's sake, I'm still on 5.5.2...

**Comment by Zodomaniac** [comment]
For me it never mattered, that's why I'm asking. How do you provide the replacement audio?

**Comment by pmjdebruijn** [comment]
I downloaded the DOOM SC55 FLAC pack, then ran my script on it, to create a SIGIL_SHREDS like WAD.

Then I'm starting crispy like so:
crispy-doom -iwad doom.wad -file doom_sc55.wad 
(which works with Native MIDI set, but doesn't with another option set)

Behaviorally it shouldn't matter though were the replacement sound comes from, should it?

**Comment by Zodomaniac** [comment]
>(which works with Native MIDI set, but doesn't with another option set)

Now I get your point.

**Comment by fabiangreffrath** [comment]
It is possible to play music in MP3/OGG/FLAC format since about Crispy Doom 2.3, but you will have to set your music backend to "Native MIDI". I admit this is a very ambigious name for that setting.

I think I will change it to read "MIDI/MP3/OGG/FLAC" instead of "Native MIDI".

**Comment by JNechaevsky** [comment]
@fabiangreffrath how do you think, is it possible to make .mp3-and-stuff compatible with OPL backend? Have some raw thoughts about it, it's a hot-swapping again. Logics may be pretty simple.

* We have an OPL music backend enables
* IF music lump is a mus/midi, it's played via OPL
* ELSE music is mp3-and-stuff, it's played via midi-proc piping.

I'm sure music types can be defined via first three bytes of music lump, so we have to read lump header first... Something like that.

**Comment by fabiangreffrath** [comment]
Yes, something like this should be possible, but is probably very complex (music backends want to be initialized, probably need Timidity cfg paths, think of midiproc, etc.). 

Anyway, this discussion is better moved to the Choco bug tracker. The underlying problems are the same there. Although you cannot play music lumps in any compressed format in Choco, you may add music replacements and these won't work if you have set the music backend to one of the emulation modes.

**Comment by JNechaevsky** [comment]
Music replacement via separate folders is something I'm try to avoid as a plague. =/

Anyways, thanks for renaming "Native MIDI" idea, this seems to be a blazingly fast and painless way.

**Comment by fabiangreffrath** [comment]
It's not a proper solution, but at least it makes things more obvious. :wink:

**Comment by JNechaevsky** [comment]
Definitely! For me it was a huge surprise to know how actually mp3 lumps can be played, since I'm always using orthodoxal OPL. 

_I've even got it working in RD, althrough with bunch of libs from MSYS, but excuse me, it's both offtopic and WIndows-related, so I'm just :zipper_mouth_face: now!_

**Comment by dblblaster** [comment]
@fabiangreffrath sry for the bump, not sure whether to open a new issue, I think better to expand here.

I'm trying to play on Linux, with `-file wads/SIGIL_v1_21.wad wads/SIGIL_SHREDS.wad` and have no music.

If I use `OPL_DRIVER=SDL` then I have sound but no music. If I use `OPL_DRIVER=Linux` I must also run it with `sudo` to avoid the `Failed to get I/O port permissions for 0x388: Operation not permitted`, and then I get:

```
I_Init: Setting up machine state.
OPL_Init: No OPL detected using 'Linux' driver.
OPL_Init: Failed to initialize driver: 'Linux'.
Dude.  The Adlib isn't responding.
```

Question, why can't the recorded (SIGIL_SHREDS.wad) music be played back through SDL2? I would prefer not having to hack my entire system just to make 1 application work.

**Comment by fabiangreffrath** [comment]
Becaue you are not using SDL, but the OPL emulator and you cannot play back MP3 music through that.

**Comment by dblblaster** [comment]
> Becaue you are not using SDL, but the OPL emulator and you cannot play back MP3 music through that.

In the thread above you say:

>If the music backend is set to "native midi", that is. Anyway, nothing left to do here.

But what does it mean "native midi" in Linux context? I read the manpage for crispy-doom and all I could find was the `OPL_DRIVER` variable so I tried experimenting with that and it didn't work with neither SDL nor Linux setting.

Is it possible at all to get it to play the wad music under Linux? I did some experimenting and digging and hit a wall. If I'm reading [this](https://www.kernel.org/doc/html/v4.10/sound/alsa-configuration.html#module-snd-adlib) right then PCM playback is not supported:

>This module supports multiple cards. It does not support autoprobe, so the port must be specified. For actual AdLib FM cards it will be 0x388. Note that this card does not have PCM support and no mixer; only FM synthesis.

**Comment by fabiangreffrath** [comment]
You will have to select the "MIDI/MP3/OGG/FLAC" music device in the setup tool.

**Comment by fabiangreffrath** [comment]
Because later I said "I think I will change it to read "MIDI/MP3/OGG/FLAC" instead of "Native MIDI"." 😉

**Comment by dblblaster** [comment]
Works now, thanks!

My bad... I never actually ran `crispy-doom-setup` and just rolled with default config, which didn't reveal the `snd_musicdevice` config file entry that the setup tool writes so of course I couldn't find the setting!

Some background: I'm writing [lutris](https://lutris.net/) installers for Linux ([example](https://lutris.net/api/installers/games/the-ultimate-doom/revisions/93161)), and idea is to package the games into their own folders with config and savegames stored locally. So I made it to run the game using launcher script, like:

`./doom.sh -iwad wads/DOOM.WAD -file wads/SIGIL_v1_21.wad wads/SIGIL_SHREDS.wad`

which is simply a wrapper around the binary to enforce use of local files, and then pass on any additional args given to the script to crispy-doom (`$@` at the end):

```
#!/bin/bash
crispy-doom -config default.cfg -extraconfig crispy-doom.cfg -iwad wads/DOOM.WAD -savedir savegames/doom.wad $@
```

Thanks again, now it's up to me to figure out how to implement this new knowledge into my installer/launcher.
