### ISSUE TITLE
Problem when compiling sources myself (MSYS2, Windows 10 1903)

### ISSUE THREAD

**Issue by WSSDude** [fabiangreffrath/crispy-doom#425]
I have weird issues when I try to compile Crispy Doom from sources. This affects at least the last official release source (5.5.2) and latest source code inside master branch as those one I tried.

[![https://www.youtube.com/watch?v=3Ys_7xmFsxc](https://img.youtube.com/vi/3Ys_7xmFsxc/0.jpg)](https://www.youtube.com/watch?v=3Ys_7xmFsxc)

When I build the source, resulting executable is skipping frames for some reason. It happens periodically, as can be seen in the video. It doesn't matter if you are in menu or inside game or demo, it always chops like this. I even tried to flip settings around, didn't help.

Prebuilt binaries work fine, but I wanted to play around with source and I can't because of this issue. It is really annoying and I don't know the exact cause.

I'm using MSYS2, GCC 9.1.0, all required libs installed and all are are up-to-date (pacman -Syu).
I compiled it performing these commands from MINGW64 shell inside folder:
```
autoreconf -fi
./configure
make
cd pkg/win32
make
```

### Background

Version of Crispy Doom: 5.5.2 and master

Operating System and version: WIndows 10 1903 64-bit

Game: Doom

Any loaded WADs and mods (please include full command line): DOOM2.WAD

### Bug description

Observed behavior: Skipped frame/frames periodically

Expected behavior: Not skipping frames

**Comment by WSSDude** [comment]
I think it may be some issue with versions of my libs or compiler or something... 

Could someone who can compile on Windows without issues post here version of compiler and libs please?

**Comment by WSSDude** [comment]
Some of my package versions (don't know if there is any other that could break it this way):

Package | Version
------------ | -------------
mingw-w64-x86_64-SDL2 | 2.0.9-1
mingw-w64-x86_64-SDL2_mixer | 2.0.4-1
mingw-w64-x86_64-SDL2_net | 2.0.1-1
mingw-w64-x86_64-libsamplerate | 0.1.9-1
mingw-w64-x86_64-libpng | 1.6.37-3
mingw-w64-x86_64-gcc | 9.1.0-3 
mingw-w64-x86_64-gcc-libs | 9.1.0-3

**Comment by fabiangreffrath** [comment]
What you report here is a known issue with SDL 2.0.9 - which is the version currently used in both MSYS2 and the Choco auto-builder. You may try to either upgrade to the SDL 2.0.10 pre-release or downgrade to any other version. It should be sufficient to exchange the runtime libraries, they should be ABI compatible.

**Comment by fabiangreffrath** [comment]
Context:
https://github.com/chocolate-doom/chocolate-doom/issues/1171

**Comment by WSSDude** [comment]
Thanks, that solved the issue.

I downgraded to 2.0.8-2 package I had in cache, as I seem to not be able to upgrade to that prerelease package and no more chopping now. Just some good old demon slaying 😎

**Comment by fabiangreffrath** [comment]
Cool, thanks for reporting back.
