### ISSUE TITLE
Remember item position in Crispness menu

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#428]
While scrolling Crispness menu by `PGUP`/`PGDN` keys, cursor placement is always reset to the first line. I guess this is not very traditional Doom menu behavior, because game is always remember which line was selected in previous menu. 

For example, select "New Game", move cursor to "Nightmare!", then press `Backspace`, then go to "New Game" again - cursor will be placed on "Nightmare!", not on "Hurt me plenty".

To fix it, simply add following lines in `m_menu.c`:
```
    // [crispy] next/prev Crispness menu
    else if (key == KEY_PGUP)
    {
+++ currentMenu->lastOn = itemOn;
	if (currentMenu == CrispnessMenus[crispness_cur])
	{
	    M_CrispnessPrev(0);
	    S_StartSound(NULL,sfx_swtchn);
	    return true;
	}
    }
    else if (key == KEY_PGDN)
    {
+++ currentMenu->lastOn = itemOn;
	if (currentMenu == CrispnessMenus[crispness_cur])
	{
	    M_CrispnessNext(0);
	    S_StartSound(NULL,sfx_swtchn);
	    return true;
	}
    }
```

_Suggestion №109_

**Comment by fabiangreffrath** [comment]
Thanks for the suggestion, @JNechaevsky. However, you have commit rights to the repo, and obvious cases like this I ask you to make use of it and just "make facts". :wink:

**Comment by JNechaevsky** [comment]
Dear Fabian, I deeply appreciate your trust and it's not just a word for me. But I can't let myself to just change Crispy code even in such small things without discussion and/or approval. This is not a RD where I can do everything I want and the way I want, this is your project and your code, so all final decisions must be on your side. Even after two-and-half years of our collaboration, subordination is a first thing for me. 

But don't get me wrong here, now I know how to make a PRs using GitHub Desktop app, which much faster and simpler for me, than using console approach. :)

**Comment by fabiangreffrath** [comment]
It's understood, thank you!
