### ISSUE TITLE
Support for extended nodes

### ISSUE THREAD

**Issue by plumsinus** [fabiangreffrath/crispy-doom#43]
A "risky" request as you might say: support ZDBSP (and maybe DeePSea) extended nodes, to allow gigantic maps like in http://www.doomworld.com/vb/post/1301335 to be played. (ignore that that wad has other problems...)

Info about ZDoom's nodes are at http://zdoom.org/wiki/Node#ZDoom_extended_nodes. Don't know about DeepSea but I'm sure there are details somewhere. I know PrBoom+ supports both kinds of extended nodes as long as they're uncompressed.

**Comment by fabiangreffrath** [comment]
Actually, it seems that adding support for DeepBSP nodes is nearly trivial. It only required to exchange some variable types in the existing functions. ZDBSP nodes, however, are a different story. they are stored in an entirely different format. But, in the end, the code is all there and I could simply copy&paste it from e.g. PrBoom+.
