### ISSUE TITLE
Allow gamma-correction to be changed while in active menu

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#431]
`F` keys are restricted to use while any on-screen menu is active:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/m_menu.c
```
    // F-Keys
    if (!menuactive)
```

Obviously, this is by design, and it feels right: from one side, it give some strictness, player can't accidentally switch one menu to another (like save to load), but this is also making impossible to change gamma-correction in any active menu, even in main.

Maybe it is worth to make a small exception? Quite simple:
```
    // F-Keys
    // Allow gamma to be changed in any menu
    if (!menuactive || key == key_menu_gamma)
```

_Suggestion №110_

**Comment by fabiangreffrath** [comment]
I understand the issue and like the idea - but I don't like the implementation. `menuactive` is a global variable and describes a very general state, whereas `key == key_menu_gamma` is a very specific exception. Hm...

**Comment by JNechaevsky** [comment]
You've right! Actually, we may simply move out `F11` stuff from `M_Responder` to ... err ... Was it a `HU_Responder`? I can't remember for now, but there is a place - in RD I've made crosshair toggling available in any moment. Please wait until evening, I need to dig my code.

**Comment by JNechaevsky** [comment]
Oops, no, not a `HU_Responder`, it's `G_BuildTiccmd`. The code for gamma changing is quite same, as example:
```
    memset(cmd, 0, sizeof(ticcmd_t));

    cmd->consistancy = 
	consistancy[consoleplayer][maketic%BACKUPTICS]; 

+++ if (gamekeydown[key_menu_gamma])    // gamma toggle
+++ {
+++     usegamma++;
+++     if (usegamma > 4)
+++     usegamma = 0;
+++     players[consoleplayer].message = DEH_String(gammamsg[usegamma]);
+++     I_SetPalette (W_CacheLumpName (DEH_String("PLAYPAL"),PU_CACHE));
+++
+++     gamekeydown[key_menu_gamma] = false;    // [JN] release button
+++ }
```

Do not forget to remove `else if (key == key_menu_gamma)` section from `M_Responder`.

There is only one thing I can't handle - I don't know how to externalize `char gammamsg[5+4][26+2]`.
Or can it simply be moved to d_main.c as well?

**Comment by JNechaevsky** [comment]
Deleted my bullshit above. Here's how it should be done, blazingly simple, just move `F11` key handling few lines below, outside of `if (!menuactive)` condition: https://github.com/JNechaevsky/russian-doom/commit/44a7957c5e805eb33145ce657b92320d827ccaeb

**Comment by fabiangreffrath** [comment]
Thank you for the code! However, this is still on the lower end of my priority scale -- means, I am not sure if so much code change is justified for such a corner case.

**Comment by JNechaevsky** [comment]
My pleasure! Perhaps, we need something "bigger and better" then. Not sure what exactly, though. Quick idea - ability to print messages even if player not in game, same to Heretic manner. Technically it's not very hard (see https://github.com/fabiangreffrath/crispy-doom/blob/master/src/heretic/d_main.c#L248), but the necessity is questionable, especially because we'll have to restore background beneath printed message.

Or maybe even better to leave everything "as is".

**Comment by fabiangreffrath** [comment]
I add the "wontfix" label for the time being.

**Comment by fabiangreffrath** [comment]
Closing this now, I am not going to move code around like that.
