### ISSUE TITLE
Remove remains of Hexen, Heretic,...

### ISSUE THREAD

**Issue by WSSDude** [fabiangreffrath/crispy-doom#433]
Do sources for Heretic, Hexen,... have any meaning being in the repo, if they are not compiled and are not maintained? I at least assume this, as they seem to not compile with doom source in any way. 

Because if this is true, they are just clutter in the repo if they have no meaning at all.

**Comment by Zodomaniac** [comment]
Crispy Heretic fixes tutti-frutti effect, has Crispy's intermediate gamma correction levels and some more fixes. It's not maintained but can be downloaded: https://www.doomworld.com/applications/core/interface/file/attachment.php?id=51061

**Comment by fabiangreffrath** [comment]
Nope, the non-Doom ports are going to stay. You are right that they are not built by default and are not part of a regular release anymore. However, it is trivial to build them (e.g. `cd src && make heretic && make crispy-heretic.exe`) and if I feel like it, the source is still there. Also, as @Zodomaniac pointed out, some effort has already gone into these games, i.e. they have high-resolution rendering, have their limits removed (in parts), etc. It would be a waste to remove them from the sources as as they are now, they "don't eat bread" (i.e. they don't waste resources) as we say in Germany. Last but not least, I maintain this repository to stay as close as possible to the original Chocolate sources and having removed 3/4 of them is quite some deviation.

**Comment by WSSDude** [comment]
Cool, I thought it was just kinda there. It is true I didn't study makefiles themselves much. I must have missed that option. Good to know though that Heretic etc. have few enhancements here as well. I must compile them and try them out now lol :D
