### ISSUE TITLE
Allow disabling colored marine corpses

### ISSUE THREAD

**Issue by GabrielCARangel** [fabiangreffrath/crispy-doom#434]
I searched through the cfg and in the Crispness menu and couldn't find this option.
A minor thing really, but would be nice to be an option.

**Comment by fabiangreffrath** [comment]
This is connected to the "Colored Blood and Corpses" switch. You'll have to reload the map for this change to become effective on marine corpses, though.

There won't be a separate switch for this minor change, though.

**Comment by Zodomaniac** [comment]
@GabrielCARangel The colored corpses include not only marine corpses but crushed Hell Nobles|Cacodemons corpses that include green/blue blood. That's why the colored corpses and colored blood must be switched together.

**Comment by fabiangreffrath** [comment]
Yes, right.

**Comment by GabrielCARangel** [comment]
I tried switching "Colored Blood and Corpses" but didn't know I had to restart the map to the effect to work.
That's just what I was looking for. Thanks guys.
