### ISSUE TITLE
Also auto-load .deh, .bex and other files in the "doom-all" subdirectory of the config directory

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#436]
IMHO that would be a nice Crispy completion of the Choco feature.

**Comment by Zodomaniac** [comment]
UPD: even patch WADs don't autoload.

**Comment by fabiangreffrath** [comment]
How do you know? At the time of writing the merged code didn't even make it to the auto-builder.

**Comment by Zodomaniac** [comment]
The daily build has just been updated, and there's no auto-load neither for PWADs nor for other patches.

**Comment by fabiangreffrath** [comment]
Could you check the "autoload_path" in your config?

**Comment by Zodomaniac** [comment]
Aha! I thought 'config directory' was the directory containing the crispy-doom.cfg.
I set it to my crispy/autoload directory and everything works.

**Comment by fabiangreffrath** [comment]
Cool, thanks!
