### ISSUE TITLE
Hardcode some swirling flats

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#437]
@fabiangreffrath , you said here https://github.com/fabiangreffrath/crispy-doom/commit/3e3e77ebb5b89262778cd2b09f69986d9e511972#commitcomment-34104188 :
>Okay, guys. This code turns the FWATER1-4 flat animation into a swirling flat, if and only if the animation definition is not from an ANIMATED lump, if the FWATER1 lump is from the IWAD and if its lump name has not been dehacked. This is the most Vanilla state possible and only then this code would enforce the FWATER1-4 animation sequence to become a swirling FWATER1 flat.

Could you implement that for:
FWATER1
SWATER1
NUKAGE1
LAVA1
BLOOD1
SLIME01
SLIME05
?

**Comment by fabiangreffrath** [comment]
I once considered that, but it is completely out of question now. I won't replace animated flats by swirling pendants by default, this is just too non-Vanilla. However, the desired effect can be easily achieved by auto-loading a PWAD that contains a properly prepared ANIMATED lump.
