### ISSUE TITLE
macOS Releases?

### ISSUE THREAD

**Issue by a-hurst** [fabiangreffrath/crispy-doom#440]
Unlike Chocolate Doom, which currently offers pre-compiled and nicely packaged macOS versions on its Github releases page, Crispy Doom currently only offers Windows binaries and can't easily build a .app version. After some messing around with chocpkg and the Crispy Doom source, I've made the fixes necessary for the Mac .app of Crispy Doom to build.

Basically, to build the Crispy Doom .dmg for Mac, you need to:

1. build Crispy Doom using chocpkg via `./chocpkg build crispy-doom/latest`
2. cd to the ./pkg/osx/ directory in the crispy doom source, and
3. run `make -f GNUmakefile'

Currently this doesn't work, because the Chocolate Doom.app build script tries to copy the Chocolate Heretic/Hexen/Strife/Etc binaries inside it and errors out because Crispy Doom doesn't build these by default. To get it building properly, I had to comment out the lines that do this in GNUmakefile:

```bash
	./cp-with-libs $(TOPLEVEL)/src/$(PROGRAM_PREFIX)doom "$(APP_BIN_DIR)"
	$(STRIP) "$(APP_BIN_DIR)/$(PROGRAM_PREFIX)doom"
#	./cp-with-libs $(TOPLEVEL)/src/$(PROGRAM_PREFIX)heretic "$(APP_BIN_DIR)"
#	$(STRIP) "$(APP_BIN_DIR)/$(PROGRAM_PREFIX)heretic"
#	./cp-with-libs $(TOPLEVEL)/src/$(PROGRAM_PREFIX)hexen "$(APP_BIN_DIR)"
#	$(STRIP) "$(APP_BIN_DIR)/$(PROGRAM_PREFIX)hexen"
#	./cp-with-libs $(TOPLEVEL)/src/$(PROGRAM_PREFIX)strife "$(APP_BIN_DIR)"
#	$(STRIP) "$(APP_BIN_DIR)/$(PROGRAM_PREFIX)strife"
	./cp-with-libs $(TOPLEVEL)/src/$(PROGRAM_PREFIX)setup "$(APP_BIN_DIR)"
	$(STRIP) "$(APP_BIN_DIR)/$(PROGRAM_PREFIX)setup"
```

and remove the ' heretic hexen strife' from this loop.

```bash
	for game in doom heretic hexen strife; do       \
		cp $(TOPLEVEL)/man/CMDLINE.$$game       \
		   "$(APP_DOC_DIR)/CMDLINE-$$game";     \
	done
```

Also, on my Mac the script that puts together the pretty .dmg doesn't wait long enough for it to mount before trying to arrange the icons nicely and throws an error, so in the `dmgfix` script I changed the delay in this part to 2 instead of 1:

```applescript
--activate
        open dmgFile
        delay 2
        set theDisk to disk diskName
        open POSIX file "/"
```

After that, everything builds!

![Screen Shot 2019-07-26 at 9 29 07 PM](https://user-images.githubusercontent.com/18648066/61988236-6ef1e500-afec-11e9-9408-2eb2dac25769.png)

The only remaining issue at this point is that the Chocolate Doom launcher .app for Mac lets you specify the WAD paths for all available games, including Hexen, Heretic, etc., so until those start getting supported again in Crispy Doom those menu options should probably be commented out too.

If you're interested in doing Mac releases alongside the Windows ones, I'd be happy to make a pull request with the necessary fixes! If not, hopefully this helps someone else down the line.

**Comment by fabiangreffrath** [comment]
> After some messing around with chocpkg and the Crispy Doom source, I've made the fixes necessary for the Mac .app of Crispy Doom to build.

Cool, thanks for that!

> Also, on my Mac the script that puts together the pretty .dmg doesn't wait long enough for it to mount before trying to arrange the icons nicely and throws an error, so in the `dmgfix` script I changed the delay in this part to 2 instead of 1:

This isn't Crispy specific. Could you please suggest this change as a PR upstream at the Choco tracker?

> After that, everything builds!

:sunglasses: 

> If you're interested in doing Mac releases alongside the Windows ones, I'd be happy to make a pull request with the necessary fixes! If not, hopefully this helps someone else down the line.

No, there won't be official Mac releases. But if you can suggest a few non-intrusive changes to the code that make it easier to build Mac binaries, then I am all for it! Waiting for your PR. :wink:

**Comment by PeterPerhac** [comment]
LOVELY! Thanks for the instructions. I was able to build my own crispy-doom on macOS Catalina 10.15.1 🎉 👍 💯 🥇

**Comment by foxxgaming** [comment]
Crispy Doom Pre-Built (in .app form) for MacOS Catalina
https://github.com/foxxgaming/CrispyDoomMac
