### ISSUE TITLE
Make 'Double click acts as Use' mouse option false by default

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#441]
When this option is true (as it is by default currently), double-clicking middle or right mouse button acts as Use. But in Crispy these mouse buttons can be bound to other actions (e.g. Quick Reverse), so IMO it makes sense to make this option false by default.

**Comment by fabiangreffrath** [comment]
True on the one hand. On the other hand, this is another deviation from Choco's default settings and if you decide to bind your mouse buttons to something exotic, you may also be expected to take care of this yourself.

**Comment by Zodomaniac** [comment]
We already deviate from Choco's default settings with disabling vertical mouse movement, saving screenshots in PNG format etc.

**Comment by fabiangreffrath** [comment]
Sorry, but I have decided not to change this. I am not going to hard-code everyone's favorite configuration.

I feel that I have probably already changed too much, and I have even reverted some specific configurations back to Choco's defaults in the past (remember Vanilla keyboard mapping?).

Regarding the novert setting, I some how take it as "community consensus" that this needs to be enabled. Regarding the setting discussed here, I think users can be expected - if they bind their mouse keys in some specific way - to make sure that this doesn't collide with any other mouse configuration.
