### ISSUE TITLE
Crispy Doom is great... can't see my joystick

### ISSUE THREAD

**Issue by bumbershoots** [fabiangreffrath/crispy-doom#442]
### Background   Not an idiot.

Version of Crispy Doom:  crispy-doom-20190803-win32

Operating System and version:  Win 7 Home Premium x64

Game: (Doom/Heretic/Hexen/Strife/other) Doom II

Any loaded WADs and mods (please include full command line):  Didn't get that far.

### Bug description  Crispy can't see my MS Precision 2 joystick.  Windows and Chocolate Doom can.  Ran the setup, just like I did in Chocolate Doom, but Crispy couldn't find the joystick.  Same setup, practically.

Observed behavior: See above

Expected behavior:  I expected it to see my joystick.

**Comment by Zodomaniac** [comment]
Do Crispy 5.6 and 5.5.2 see your joystick?

**Comment by bumbershoots** [comment]
None of them do.  I even edited the cfg file to use joystick = 1  or w/e.  No luck.The MS Precision 2 joystick has no software.  MS refuses to write a 64 bit version.  However, I can calibrate and test it in Windows.Currently I'm using Zdoom 2.8.1.0 I believe.  That works fine.The GOG versions of Doom and Doom II also have no issues.
I really wanted to use Crispy, because whoever coded it, didn't go nuts.  Zdoom for example took me 30 mins easy just to set up the options, and the whole time the options were overlayed on other images...  making it very hard to read.
On a side note...  I tried my best to get Crispy to work.
What I personally want in a source port...
Great graphics, working joystick support, and that's pretty much it.  I'm 62 years old...  I grew up with Doom and Doom IIOh one other thing that would be fantastic.  I have a CD with 1600 wads.  The official Doom Master levels.  There needs to be a very simple launcher way (?) to select among all those wads.
 
 
 
-----Original Message-----

**Comment by Zodomaniac** [comment]
Which version of Chocolate Doom does see your joystick?

**Comment by fabiangreffrath** [comment]
Most probably an SDL issue. Choco and Crispy Daily builds as well as Crispy 5.6 use the same SDL library versions, so the issue should be the same with all of them. The Choco 3.0 release uses an older set of libraries, so if this works for you, you could try to replace *.DLL in Crispy 5.6 with the ones from Choco 3.0.

**Comment by bumbershoots** [comment]
Which .dll should I replace?
 
 
 
-----Original Message-----

**Comment by bumbershoots** [comment]
Version 3.0.7 ??
 
 
 
-----Original Message-----

**Comment by fabiangreffrath** [comment]
SDL*.dll

**Comment by bumbershoots** [comment]
Yep, moving the three SDL files worked.  I'm gonna play with both Crispy and ZDoom and see which I like better...  they are almost identical...   "crispness".
Thx for the fast response.  That was nice.
 
 
 
-----Original Message-----

**Comment by fabiangreffrath** [comment]
Closing.

> I'm gonna play with both Crispy and ZDoom and see which I like better...  they are almost identical... 

That one was good. :grin:

**Comment by bumbershoots** [comment]
My full report on the comparison...
Crispy has same graphics as ZDoom except...   Crispy has better skies.Both now, support my joystick.  ZDoom has sensitivity adjustments for the joystick axis'.  Crispy needs this.  On Crispy, the joystick has far too much travel.  In ZDoom I can up the sensitivity to compensate...  can't do that in Crispy.  <---  As far as I know.
 
 
 
-----Original Message-----

**Comment by fabiangreffrath** [comment]
The graphics appear similar because both ports use a software renderer. But under the hood, the ports are as different as you can get in the Doom source port universe. Crispy is a *very* conservative port based on Chocolate Doom, which in turn aims to be as close to the original DOOM.EXE as possible. ZDoom, on the other hand, is (one of) the most advanced source ports out there with tons of extensions available and all the bells and whistles.

**Comment by bumbershoots** [comment]
Yeah.  The skies in ZDoom are horrible.  I like Crispy better except for not having joystick sensitivity settings.Thx for all the help.  I appreciate it.
 
 
 
-----Original Message-----
