### ISSUE TITLE
Differentiate NUM keys from arrow keys

### ISSUE THREAD

**Issue by vittau** [fabiangreffrath/crispy-doom#444]
### Background

Version of Crispy Doom: 5.6

Operating System and version: Windows 10 Pro

Game: Doom

Any loaded WADs and mods (please include full command line): doomu.wad

### Bug description

Observed behavior: Setup tool maps NUM_2, NUM_4, NUM_6 and NUM_8 to equivalent arrow keys, even with NUMLOCK enabled.

Expected behavior: Consider these keys independently.

**Comment by vittau** [comment]
Hi,

The reason I ask for this is because I'm left-handed, and so I use the NUM keys to move around, and use arrow keys for other actions (i.e. running), with my thumb.

**Comment by fabiangreffrath** [comment]
Perfectly valid request. However, it has already been reported upstream at the Choco issue tracker. So, I'll close this bug here and reference you there instead. 

https://github.com/chocolate-doom/chocolate-doom/issues/1101
