### ISSUE TITLE
[Graphic Bug]The buttons in REKKR 1.16 are rendered incorrectly

### ISSUE THREAD

**Issue by IsBebs** [fabiangreffrath/crispy-doom#445]
### Background

Version of Crispy Doom:2019-0817

Operating System and version:Windows 10 Home 10.0.18362

Game: (Doom)

Any loaded WADs and mods (please include full command line):
 crispy-doom.exe -iwad DOOM.WAD  -merge REKKR.wad

### Bug description
The buttons in REKKR 1.16 are rendered incorrectly
Observed behavior:
![DOOM0000](https://user-images.githubusercontent.com/33869439/63210418-44c4ac00-c0ee-11e9-8796-08c122453e8e.png)
![DOOM0001](https://user-images.githubusercontent.com/33869439/63210430-62921100-c0ee-11e9-81c1-0c038b374ebd.png)
![DOOM0003](https://user-images.githubusercontent.com/33869439/63210433-658d0180-c0ee-11e9-9b9d-8c58d2ee0785.png)

Expected behavior:
![DOOM00](https://user-images.githubusercontent.com/33869439/63210421-4a21f680-c0ee-11e9-87e2-978f8bf694a4.png)
![DOOM01](https://user-images.githubusercontent.com/33869439/63210423-51490480-c0ee-11e9-83d2-8f18167bcc27.png)
![DOOM02](https://user-images.githubusercontent.com/33869439/63210427-55752200-c0ee-11e9-9a18-2b5718e77415.png)

**Comment by Zodomaniac** [comment]
Haven't you forgot `-deh rekkr.deh`?
Are all these buttons in episode 1 level 1?

**Comment by IsBebs** [comment]
I added -deh rekkr.deh but it gives the same result. Yes they are all from episode 1 level 1

**Comment by fabiangreffrath** [comment]
I can confirm the issue, but cannot tell why it happens. :frowning:

**Comment by IsBebs** [comment]
it works on the 5.6 release

**Comment by fabiangreffrath** [comment]
Could you try to remove SIGIL.WAD out of the way?

**Comment by IsBebs** [comment]
It works now

**Comment by fabiangreffrath** [comment]
Thanks! That's SIGIL's PNAMES/TEXTURE1/TEXTURE2 lumps colliding with REKKR's own.
