### ISSUE TITLE
Wrong music track played in IWAD intrinsic demos when played with music PWADs

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#446]
### Background

Version of Crispy Doom: 5.6.1

Operating System and version: Windows 7 Professional SP1

Game: Doom, Doom 2

Any loaded WADs and mods (please include full command line): crispy-doom.exe (-iwad doom.wad) -merge DoomMetalVol5(or 4)_44100.wad

### Bug description

Observed behavior: In IWAD intrinsic demos the title track is played, not the level soundtrack. This occurs with music PWADs only, and SIGIL.WAD has nothing to do with it, I remove it and nothing changes.

Expected behavior: In demos, the level soundtracks should be played.

**Comment by fabiangreffrath** [comment]
Hm, can't seem to reproduce here.

**Comment by Zodomaniac** [comment]
Here you are. Version 5.6 doesn't have this glitch.
https://youtu.be/xOf9pOpuiqQ

**Comment by fabiangreffrath** [comment]
Does it work if you remove midiproc.exe?

**Comment by Zodomaniac** [comment]
Yes, removing midiproc fixes the issue. I remember there were some changes to midiproc in Choco repository right after the 5.6 release, and they seem to have affected the music playback.

**Comment by fabiangreffrath** [comment]
Well, tada!

**Comment by Zodomaniac** [comment]
Even further: if I start new game from the menu, the title track restarts and plays instead of the level soundtrack as well.

**Comment by fabiangreffrath** [comment]
Time to fix this once and for all.

**Comment by vittau** [comment]
Hello everyone,
When I pass a level in Sigil with SHREDS the music simply replays, instead of changing to the next level music. Is it related to this bug? Is it upstream?

**Comment by Zodomaniac** [comment]
@vittau Yes, it's related to this bug which was introduced upstream.

**Comment by Zodomaniac** [comment]
@fabiangreffrath Should I open this issue in Chocolate Doom as it's upstream?
I haven't tried to reproduce it for Choco though, as it would require Music Pack configuration, Choco doesn't support real-tone music WADs AFAIK.

**Comment by Zodomaniac** [comment]
Hooray, this has been fixed in https://github.com/fabiangreffrath/crispy-doom/commit/6a6b7fc6860bd66406f718aeb09fde8dd6da71e2 !

**Comment by fabiangreffrath** [comment]
Halle-fucking-lujah! That was high time.
