### ISSUE TITLE
PNG screenshots have alpha channel only containing zero

### ISSUE THREAD

**Issue by JamesDunne** [fabiangreffrath/crispy-doom#447]
### Background

Version of Crispy Doom: 5.6

Operating System and version: MacOS Sierra 10.12.6

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line): N/A

### Bug description

Observed behavior: Taking screenshots using "Clean Screenshot" key and LIBPNG available results in PNG files with an alpha channel that consists of all zeroes, making the screenshot entirely transparent. The RGB color data is preserved but all applications that preview the PNG including Finder and Preview.app render a blank rectangle. The original screenshot is salvageable by opening it in an image-editing program such as GIMP and raising all alpha channel values from 0 up to 255 as they should default to (or remove the alpha channel entirely, implying the same effect but using less storage).

Expected behavior: PNGs for screenshots should not contain alpha channels because screenshots are captured from the screen, and only the final RGB colors of the pixels should be relevant.

**Comment by fabiangreffrath** [comment]
So this is on mac os?

**Comment by JamesDunne** [comment]
Correct. I'm building from source too, using Homebrew to fetch library dependencies.

`libpng` is `1.6.37`
`SDL2` is `2.0.9_1`

**Comment by fabiangreffrath** [comment]
Does this also happen with daily builds of chocolate doom? Our screenshot code paths are slightly different.

**Comment by JamesDunne** [comment]
Let me check!

**Comment by JamesDunne** [comment]
Confirmed that `chocolate-doom` current `master` (built from source) creates valid PNG screenshots without alpha channels when enabling `png_screenshots` config to `1`.

**Comment by JamesDunne** [comment]
From crispy-doom:
![DOOM0012](https://user-images.githubusercontent.com/538152/63625066-14847e00-c5c4-11e9-872b-a8930a31cef6.png)

From chocolate-doom:
![DOOM00](https://user-images.githubusercontent.com/538152/63625078-1e0de600-c5c4-11e9-88ac-e66cd1abeb3f.png)

Both screenshots are of DOOM2 MAP01.

**Comment by JamesDunne** [comment]
I can open the crispy-doom image in GIMP and use Colors > Curves to adjust the Alpha curve to a flat 255->255 line instead of 0->255 and the image appears as it should.
![image](https://user-images.githubusercontent.com/538152/63625154-5d3c3700-c5c4-11e9-99d8-a252de28e706.png)

**Comment by Zodomaniac** [comment]
> From crispy-doom:
> ![DOOM0012](https://user-images.githubusercontent.com/538152/63625066-14847e00-c5c4-11e9-872b-a8930a31cef6.png)
> 
> From chocolate-doom:
> ![DOOM00](https://user-images.githubusercontent.com/538152/63625078-1e0de600-c5c4-11e9-88ac-e66cd1abeb3f.png)
> 
> Both screenshots are of DOOM2 MAP01.

@JamesDunne, does this happen with Clean Screenshots of Crispy only or with regular screenshots as well?

**Comment by JamesDunne** [comment]
I think both clean and regular exhibit the same behavior.

**Comment by JamesDunne** [comment]
Confirmed both clean and regular screenshot behave the same.

Regular:
![DOOM0017](https://user-images.githubusercontent.com/538152/63643380-c8edd500-c694-11e9-8082-3635b63bd63a.png)

Clean:
![DOOM0018](https://user-images.githubusercontent.com/538152/63643381-cab79880-c694-11e9-87a3-10cce86d88bd.png)

**Comment by fabiangreffrath** [comment]
> Expected behavior: PNGs for screenshots should not contain alpha channels because screenshots are captured from the screen, and only the final RGB colors of the pixels should be relevant.

The point is, screenshots in Crispy are exactly that. They are a reproduction of the image rendered on screen. Since this image is opaque, the alpha channels are all set to 1 on both Linux and Windows. But Mac OS has to be a very special pony...

However, I agree with you that screenshots do not even need an alpha channel. Could you please check if adding this line does what it promises? It makes no difference on Linux, not sure if this is a good or bad sign.

```
--- a/src/v_video.c
+++ b/src/v_video.c
@@ -1119,6 +1119,8 @@ void WritePNGfile(char *filename, pixel_t *data,
     }
     free(palette);
 
+    png_set_strip_alpha(ppng);
+
     png_write_end(ppng, pinfo);
     png_destroy_write_struct(&ppng, &pinfo);
     fclose(handle);
```

**Comment by fabiangreffrath** [comment]
That was expected. libpng seldomly does what you expect of it. :wink:

Could you please confirm that this does the trick? It works on Linux and if @Zodomaniac or @JNechaevsky could confirm it works on Windows as well, this is the way to go:
```
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -1803,11 +1803,7 @@ void I_RenderReadPixels(byte **data, int *w, int *h, int *p)
        }
 
        // [crispy] native PNG pixel format
-#if SDL_BYTEORDER == SDL_LIL_ENDIAN
-       png_format = SDL_PIXELFORMAT_ABGR8888;
-#else
-       png_format = SDL_PIXELFORMAT_RGBA8888;
-#endif
+       png_format = SDL_PIXELFORMAT_RGB24;
        format = SDL_AllocFormat(png_format);
        temp = rect.w * format->BytesPerPixel; // [crispy] pitch
 
diff --git a/src/v_video.c b/src/v_video.c
index 96020d50..dd5e5f0c 100644
--- a/src/v_video.c
+++ b/src/v_video.c
@@ -1060,7 +1060,7 @@ void WritePNGfile(char *filename, pixel_t *data,
     rowbuf = palette; // [crispy] pointer abuse!
 
     png_set_IHDR(ppng, pinfo, width, height,
-                 8, PNG_COLOR_TYPE_RGB_ALPHA, PNG_INTERLACE_NONE,
+                 8, PNG_COLOR_TYPE_RGB, PNG_INTERLACE_NONE,
                  PNG_COMPRESSION_TYPE_DEFAULT, PNG_FILTER_TYPE_DEFAULT);
 /*
     png_set_IHDR(ppng, pinfo, width, height,
```

**Comment by JNechaevsky** [comment]
Seems to be okay on my side (Windows 10, latest Version 10.0.18362.295), except... Clean screenshot seems to be same to standard. Here's what I've got:

**Standard**
![DOOM0000](https://user-images.githubusercontent.com/21193394/63717796-b79df780-c851-11e9-9bfa-2fdef610df3c.png)

**Clean**
![DOOM0001](https://user-images.githubusercontent.com/21193394/63717807-bcfb4200-c851-11e9-98de-e0b5b5cf7fad.png)


P.S. Also, there is a small warning while compiling midiproc:
```
make[2]: вход в каталог «/home/Julian/crispy-doom/midiproc»
  CC       buffer.o
  CC       main.o
main.c: In function 'RegisterSong':
main.c:124:20: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  124 |     music_filename = filename;
      |                    ^
  CCLD     crispy-midiproc.exe
```

**Comment by fabiangreffrath** [comment]
Hi @JNechaevsky. Thanks for checking! But, what difference do you expect between both screenshots? We decided to keep the weapon sprite if the status is visible for ages.

**Comment by Zodomaniac** [comment]
@JNechaevsky , you should have enabled Crispy HUD to get a truly clean screenshot.
BTW, how do you compile Crispy on Windows? I struggled to CMake the makefiles and then use MinGW, but the compiler errors out on midiproc
![Struggle with compiler](https://user-images.githubusercontent.com/15119473/63726478-0ce40400-c866-11e9-9afb-944ce6077445.png)
.

**Comment by JNechaevsky** [comment]
Hm, well, I was excepted a HUD-less screenshot even with standard HUD. If it only works with Crispy HUD, okay.

@Zodomaniac, try to use [MSYS](https://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Windows) for Windows, it's all-in-one portable environment, while CMake is a nightmare. Not sure about error though, probably compiler handles code differently in MSYS and MinGW.
