### ISSUE TITLE
Changing aspect ratio in windowed mode progressively decreases window size

### ISSUE THREAD

**Issue by JamesDunne** [fabiangreffrath/crispy-doom#448]
### Background

Version of Crispy Doom: 5.6

Operating System and version: MacOS Sierra 10.12.6

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line): N/A

### Bug description

Observed behavior:
Use `crispy-doom-setup` to set resolution to `1280x960`
Start `crispy-doom -window` for windowed mode
Go to options, crispness, rendering, force aspect ratio, and cycle through the options.
Every time 4x3 is selected, the window size drops and gets progressively smaller ultimately reverting to 640x480.

Expected behavior:
The original resolution set in `crispy-doom-setup` (1280x960) should be retained as much as possible while cycling through aspect ratios and the window size should not shrink down to 640x480.

**Comment by fabiangreffrath** [comment]
This is because when you change the aspect ratio, the new windows dimensions are calculated to fit *into* the previous ones. What you have once set in the setup tool doesn't apply anymore.

**Comment by fabiangreffrath** [comment]
The point is that you negate the video settings you have selected in crispy-doom-setup by changing them in-game in crispy-doom. The resolution you chose (1280x960) is only valid if "aspect ratio correction" is enabled - it doesn't make any sense without that. So, if you change the aspect ratio setting in-game, a new resolution has to be found. what you had set in the setup tool before isn't relevant anymore, the boundary conditions have changed.
Now it tries to find the next best resolution that meets the new aspect ratio setting without exceeding the previous window size - else we would grow your window out of your screen.

I hope you agree that this is only a minor issue. You are still free to resize your game window after every change in the Crispness menu by the usual means. I am tempted to close this with the "wontfix" label, unless you beat me to a reasonable fix. :wink:

**Comment by JamesDunne** [comment]
Eh, I'm not gonna fight you on it. :) Feel free to close.

**Comment by fabiangreffrath** [comment]
Thanks!
