### ISSUE TITLE
In i3, game is rendered in a corner instead of the center.

### ISSUE THREAD

**Issue by crocket** [fabiangreffrath/crispy-doom#449]
### Background

Version of Crispy Doom: 5.6

Operating System and version: Gentoo Linux

Game: Any

Any loaded WADs and mods (please include full command line):

* crispy-doom -iwad the-ultimate-doom.wad -window
* crispy-doom -iwad doom2.wad -window

### Bug description

Observed behavior:

Initially, game is rendered at the center of an i3 window.

![2019-08-24_Sat_10:53:40](https://user-images.githubusercontent.com/748856/63636354-2c81fd80-c6a9-11e9-80f2-2d3dba6e49c2.png)
![2019-08-24_Sat_10:53:29](https://user-images.githubusercontent.com/748856/63636353-2c81fd80-c6a9-11e9-9a20-67092dce3356.png)

After changing i3 layout, game is rendered in corners. This looks ugly.

![2019-08-24_Sat_10:53:11](https://user-images.githubusercontent.com/748856/63636360-5affd880-c6a9-11e9-840e-779097e05d50.png)
![2019-08-24_Sat_10:53:17](https://user-images.githubusercontent.com/748856/63636361-5affd880-c6a9-11e9-8349-9f38bb57622a.png)

Expected behavior:

Game should be rendered in the center after changing layout in i3.

**Comment by Zodomaniac** [comment]
Does this happen to Chocolate Doom as well? If yes, then this should be fixed for Choco, as Crispy is its fork.

**Comment by crocket** [comment]
I will test chocolate doom and get back.

**Comment by crocket** [comment]
I can reproduce the issue on chocolate-doom.

**Comment by crocket** [comment]
Putting `export SDL_VIDEO_CENTERED=1` in ~/.profile and logging in again works around the issue.
