### ISSUE TITLE
Extended demos in other Crispy games, and Chocolate compatibility

### ISSUE THREAD

**Issue by plumsinus** [fabiangreffrath/crispy-doom#45]
Now that I am set up to play around with the Crispy/Chocolate source and work with git, one of the first things I'd like to try to do is to add extended demo support to Heretic/Hexen/Strife. Things like unlimited demo length, support for -longtics, multi-level movies, etc. 

I'm going to ask fraggle if he thinks that any of these things belong in Chocolate Doom. I think there is enough precedent for it, but it's up to him. If he doesn't, then I'd like to include them in the Crispy Doom package. But, this will mean that Crispy Heretic/Hexen/Strife could produce demos that the Chocolate games couldn't play, if certain options like -longtics are used. 

Does this go against your goals for Crispy Doom? Of course, Chocolate demos will still play in Crispy, and extended demos from Crispy will also play in other DOS programs (vv Heretic and Hexen-plus).

I'll post a full list of what I'd like to change on the Chocolate Doom tracker, in a bit. I want to play with Strife first since I know nothing about demo recording for it.

**Comment by fabiangreffrath** [comment]
I think this is mostly fixed in Choco now. Could you please try a recent snapshot and report anything that you feel is still missing?

**Comment by fabiangreffrath** [comment]
I consider this fixed upstream in Choco now. Please open another bug there if you feel something is still missing.
