### ISSUE TITLE
Keyboard input is ignored whenever a screen melt occurs on menu screen.

### ISSUE THREAD

**Issue by crocket** [fabiangreffrath/crispy-doom#450]
### Background

Version of Crispy Doom: 5.6

Operating System and version: Gentoo Linux

Game: Doom

Any loaded WADs and mods (please include full command line):

* crispy-doom -iwad the-ultimate-doom.wad --window

### Bug description

Observed behavior:

Keyboard input is ignored while a screen melt occurs on menu screen.

According to https://github.com/chocolate-doom/chocolate-doom/issues/1192
it is vanilla behavior that doesn't need to be fixed.

Expected behavior:

Keyboard input is not ignored when a screen melt occurs on menu screen.

**Comment by fabiangreffrath** [comment]
> According to [chocolate-doom#1192](https://github.com/chocolate-doom/chocolate-doom/issues/1192)
> it is vanilla behavior that doesn't need to be fixed.

Same here!

Also, I am pretty sure demos would desync if we suddenly started to process input during the melting screen.
