### ISSUE TITLE
SKY offset wrong

### ISSUE THREAD

**Issue by P41R47** [fabiangreffrath/crispy-doom#451]
### Background

Version of Crispy Doom: 5.5.2

Operating System and version: win 7 ultimate 32 bits

Game: (Doom/Heretic/Hexen/Strife/other)
Doom 2

Any loaded WADs and mods (please include full command line):
Perdition's Gate: PG-RAW.wad, Back to Saturn X: btsxe1a.wad btsxe1b.wad

### Bug description

Observed behavior:
Crispy doom, for some reason, has a wrong offset, breaking the compatibility with some mods. This not only happened with mods, it also happened with ultimate doom iwad campaing and doom 2 iwad campaing.

Expected behavior:
here some photos from chocolate-doom behavior and crispy-doom behavior:
![Sky offset1](https://user-images.githubusercontent.com/54422591/63644392-b092b000-c6be-11e9-819e-72743b9d2135.png)
![Sky offset2](https://user-images.githubusercontent.com/54422591/63644393-b092b000-c6be-11e9-9c2c-db86688ad4f1.png)
![Sky offset3](https://user-images.githubusercontent.com/54422591/63644394-b092b000-c6be-11e9-8065-5bae51fada80.png)
![Sky offset4](https://user-images.githubusercontent.com/54422591/63644395-b092b000-c6be-11e9-9668-01680b40137b.png)

the 2nd and 3rd photo are from chocolate doom 3.0.0
the 1st and the 4th photo are from crispy doom 5.5.2

**Comment by fabiangreffrath** [comment]
In Crispy the sky is vertically stretched. This is because you have either the free look / mouse look or the weapon recoil features enabled. Without stretching the sky picture, it would tile if you looked up or down. But I assume, this issue shows that this implication needs to be documented in the Wiki.

**Comment by fabiangreffrath** [comment]
This is how looking up in E3M1 would look like if the sky texture wasn't stretched:

![DOOM0000](https://user-images.githubusercontent.com/6449237/63673642-09f4ff00-c7e5-11e9-8031-a80e5368752d.png)

**Comment by fabiangreffrath** [comment]
> But I assume, this issue shows that this implication needs to be documented in the Wiki.

Since I have done that now, I'll close this issue.
