### ISSUE TITLE
SIGIL_SHREDS.wad music problem

### ISSUE THREAD

**Issue by d9d6ka** [fabiangreffrath/crispy-doom#453]
### Background

Version of Crispy Doom: 5.6.1

Operating System and version: Windows 7 Professional

Game: Doom

Any loaded WADs and mods (please include full command line): crispy-doom -file SIGIL.wad SIGIL_SHREDS.wad

### Bug description

Observed behavior: When I start the game via the CMD I hear the SIGIL main menu music in menu, in every level (even in not ones of SIGIL), and in level ending screen. When I start just by doubleclicking the crispy-doom.exe (and when all the SIGIL wads are autoloaded as I understand) the problem is _slightly_ different: if I start any episode but SIGIL I'll hear its normal music. But if I start SIGIL episode then it will be the SIGIL's 1st level music playing everywhere (menu, all levels of all episodes, etc) till I restart crispt-doom.exe.

Expected behavior: playing proper music in proper place. I have to use GZDoom, but I don't like it much as I prefer Chocolate/Crispy Doom.

**Comment by Zodomaniac** [comment]
This should already have been fixed, try the daily build at http://latest.chocolate-doom.org

**Comment by d9d6ka** [comment]
Thanks, sorry! I'd have checked this version...
