### ISSUE TITLE
Lower/upper texture not moving but 'collapsing' when floor/ceiling changes height

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#456]
### Background

Version of Crispy Doom: 5.6.2

Operating System and version: Win 7 Professional x64

Game: Doom 2

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior:

![floormovesbutnotlowertexture](https://user-images.githubusercontent.com/15119473/64912544-9dad5180-d739-11e9-8a59-4db79d40fe58.png)

Expected behavior:

![expected](https://user-images.githubusercontent.com/15119473/64912537-7a82a200-d739-11e9-9f46-05987288fc6a.png)

**Comment by fabiangreffrath** [comment]
It looks strange, but exactly the same happens with PrBoom+.

**Comment by fabiangreffrath** [comment]
Pretty sure a problem with upper/lower unpeg and vertical texture size, but not an engine issue.
