### ISSUE TITLE
Midiproc cannot run with older DLLs (SDL2 2.0.5, mixer 2.0.1) when using fluidsynth 

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#457]
### Background

Version of Crispy Doom: 5.6.2

Operating System and version: Windows 7 Professional x64

Game: Doom

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior:
In case of command line
```
@echo off
set SDL_SOUNDFONTS=TimGM6mb.sf2
start crispy-doom -iwad doom.wad -merge DoomMetalVol5_44100.wad -warp 31
exit
```
the music volume is the same as played in Choco fashion.

For command line
```
@echo off
start crispy-doom -iwad doom.wad -merge DoomMetalVol5_44100.wad -warp 31
exit
```
(not setting the soundfont)
the music is much quieter than when SDL_SOUNDFONTS variable is set or when music is played in Choco fashion.

When playing music in Choco music pack fashion, setting SDL_SOUNDFONTS or not doesn't make a difference.

Expected behavior:
There should not be any difference in volume when playing music from WADs regardless of setting the soundfont or not.

**Comment by fabiangreffrath** [comment]
This doesn't seem to make any sense. The `SDL_SOUNDFONT` variable is really only relevant for the fluidsynth backend, and if you play OGG/MP3 music an entirely different backend is used which does not even check for this variable.

**Comment by Zodomaniac** [comment]
Nevertheless, #ithappens xD

**Comment by fabiangreffrath** [comment]
Is midiproc running in both cases? 
What if you unset the environment variable again and start anew?

**Comment by Zodomaniac** [comment]
I discovered it's a bug in SDL2 2.0.5/SDL2_mixer 2.0.1 that I'm using. In SDL2 2.0.10/SDL2_mixer 2.0.4 it's not the case.

**Comment by fabiangreffrath** [comment]
:facepalm:

**Comment by fabiangreffrath** [comment]
Where will this lead us,  SDL?!

**Comment by Zodomaniac** [comment]
Here's what I discovered: under SDL2 2.0.5/mixer 2.0.1 in case of using fluidsynth midiproc doesn't start, that's why the volume of OGG/MP3 soundtrack is loud!
In SDL 2.0.10 midiproc starts both in cases of using or not using fluidsynth.

**Comment by Zodomaniac** [comment]
Also, fluidsynth volume is considerably lower than in Chocolate with fluidsynth, both with SDL2 2.0.10!

**Comment by Zodomaniac** [comment]
In fact this is a Choco issue.
