### ISSUE TITLE
Sounds pitched up and no music playing since 5.6

### ISSUE THREAD

**Issue by CliffyPrime** [fabiangreffrath/crispy-doom#458]
### Background

Version of Crispy Doom: 5.6 onward (including the latest 5.6.2)

Operating System and version: Windows 10 x64 Professional, Build 18362.356

Game: Doom, Doom II (no other games tried)

Any loaded WADs and mods (please include full command line): only the original DOOM and DOOM2 WAD

### Bug description

Observed behavior: No matter which settings are chosen, no background music is playing and the sound effects (guns, voices / monster sounds etc) are pitched up in tone but not shortened in length as it seems. Everything just sounds like Mikey Mouse ;)

Expected behavior: Sounds playing normally.

Additional info: when i manually copy the "old" SDL2.dll, SDL2_mixer.dll and SDL2_net.dll (didn't try one at a time) from version 5.5.2 into the newer versions folder and overwrite the newer files with those older versions, the sounds are OK in the newer versions, so this would be the area someone should maybe look into and what changes between 5.5.2 and 5.6 were made...

(Sound)Hardware: Soundblaster Z

**Comment by Zodomaniac** [comment]
This is SDL2 2.0.10 issue: #454 . I guess you use 5.1 audio configuration, judging by the fact you have this kind of problem.
Feel free to mitigate the sound pitching with [this old DLL pack](https://github.com/fabiangreffrath/crispy-doom/files/3616050/crispy-doom-DLL-fix-pack.zip) and take advantage of fluidsynth soundfont support as a bonus.
