### ISSUE TITLE
If changes to game options (sound volume, always run etc.) are made when recording a demo, they are not saved

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#459]
### Background

Version of Crispy Doom: 5.6.2

Operating System and version: Win 7 Professional x64

Game: Doom (2)

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: if changes to game options (sound volume, always run etc.) are made when recording a demo, they are not saved, config files are not updated.

Expected behavior: config files should always be updated when quitting game, regardless of demo recording, netgame or whatever.

I'm really not sure if it's a bug in the parent port, Choco, or vanilla behavior it emulates, but in Crispy it should be fixed as counter-intuitive IMO.

**Comment by JNechaevsky** [comment]
Voting yes, actually. :thumbsup: Could be also helpful for long `-timedemo` runs, when you don't need to hear too fast sounds, but to see just a gameplay, i.e. quickly reduce volume to zero, then finish watching, then run it again in case of necessity.

**Comment by fabiangreffrath** [comment]
> I'm really not sure if it's a bug in the parent port, Choco, or vanilla behavior it emulates, but in Crispy it should be fixed as counter-intuitive IMO.

Could you please check with Vanilla (in DOSBOX or whatever) so to I know which port to tackle for that?

**Comment by Zodomaniac** [comment]
I checked, it's Vanilla behavior so it should be fixed in Crispy only.

**Comment by fabiangreffrath** [comment]
Okay, thanks.

**Comment by fabiangreffrath** [comment]
Okay, this is because `-timedemo` and `-record` exit with `I_Error()` whereas `-playdemo` exits with `I_Quit()`. `I_Error()` in turn only calls the `atexit` functions which have `run_on_error` set to `true` which is not the case for `M_SaveDefaults()`.
