### ISSUE TITLE
Rewinding demos fast-forward/backward

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#460]
I have a suggestion that may be useful to look for particular moments in demos.
Maybe make Turn Left key play the demo fast-backward, and Turn Right fast-forward with the speed proportional to the length of the demo (so that the progress bar rewind speed remains constant, e.g. 40 framebuffer pixels per second in high resolution and 20 in low resolution).

**Comment by fabiangreffrath** [comment]
> Maybe make Turn Left key play the demo fast-backward

Great idea! But unfortunately absolutely impossible. There is no way to revert a tic in Doom. What would be needed is a savegame each tic, but I am not even sure if a save and reload cycle within a demo playback would keep sync.

> and Turn Right fast-forward with the speed proportional to the length of the demo 

Hm, I have played the thought of toggling playdemo/timedemo during playback before. but your suggested attempt with playback speed proportional to the demo length sounds a bit too over-engineered to me. 

*From the latest suggestions that I got, I guess we have more or less reached the point of feature saturation by now and are desperately searching for opportunities to "get a bit more cool stuff" out of the engine.* :grin:

**Comment by JNechaevsky** [comment]
> From the latest suggestions that I got, I guess we have more or less reached the point of feature saturation ...

So I will got fired from Crispy project? :scream: 

Well, to be more serious, looks likes it is true. I still have few ideas, which are, let's just say, `singleplayer` only, or at least they can't be easily simply implemented w/o compatibility impact. Another possible way to go - customization, but as Fabian already mentioned, some canonical Doom aspects should not be changed. Third another possible way - making some stuff, which can not be achieved by deh/bex mods, like bringing some randomness to monster's behavior, but despite of possible research/gameplay interest, it's a flagrant violation of game mechanics.

**Comment by Zodomaniac** [comment]
@JNechaevsky For different monster behavior you can try DOOM 4 Vanilla mod that comes bundled with some WADs for Doom 2 https://www.doomworld.com/forum/topic/108725-doom-4-vanilla-v12/

**Comment by JNechaevsky** [comment]
@Zodomaniac no-no, I was meaning a bit different thing. Not just a mod/TC, but something... Still canonical but with different feeling, which may literally break habits, formed for year.

A perfect example is flipped levels. For example, when you are playing through original Doom levels, you don't need to thing where to go - for now, it's a game of instincts and map route is stored somewhere in subconscious. But try to finish flipped Doom II, for first 5-15 minutes you will bump into walls, maybe even fill dizziness (!). Some time later you will be fine, but will be enforced to think - where to go.

Maybe something like this can be done for monsters. Another example: you perfectly know timings of Mancubus attacks, you know when to dodge left, when to dodge right. But what if fireball directions will be random? Quite challenging at least. Or depending of player's distance, fireball attack may have some randomness in accuracy, which will make dodging harder. Or random pain chances for same monsters. Something like this.

**Comment by Zodomaniac** [comment]
@JNechaevsky there's still room for your artistic endeavours: Crispy Heretic/Hexen/Strife icons are still needed, as well as actual chocolate bar for Chocolate engines https://github.com/chocolate-doom/chocolate-doom/issues/1020

**Comment by JNechaevsky** [comment]
I'm lazy.

**Comment by Zodomaniac** [comment]
@JNechaevsky if you are interested in different weapon timings, check out my small gameplay mod https://www.doomworld.com/forum/topic/104839-stroom-a-small-add-on-bringing-the-fury-of-strain-to-classic-doom-arsenal/
I also use the fix for chaingunners to fire with the same rate as the player does and sound correctly.
[CPOS-BUL.zip](https://github.com/fabiangreffrath/crispy-doom/files/3652388/CPOS-BUL.zip)

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.
