### ISSUE TITLE
If any kind of translucency in enabled, the weapon sprite is affected by it

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#461]
### Background

Version of Crispy Doom: 5.6.2

Operating System and version: Win 7

Game: Doom 2, DOOM 4 Vanilla mod https://www.doomworld.com/forum/topic/108725-doom-4-vanilla-v12/ 

Any loaded WADs and mods (please include full command line): `crispy-doom -merge SCYTHE.wad FSCYTHE.wad D4V.wad -nodeh -deh D4V.deh` 

### Bug description

Observed behavior: If any kind of translucency (projectiles, items, or both) is enabled, the rocket launcher reload sprites become translucent despite they neither belong to projectiles nor items.
![DOOM0000](https://user-images.githubusercontent.com/15119473/65495609-b519d680-debf-11e9-861e-842d0d42ca2d.png)

Expected behavior: No translucency of weapon sprites.

**Comment by fabiangreffrath** [comment]
Seems like a lot of dehackery has been applied and the rocket launcher has taken the place of a thing which has the translucent flag applied by default. Also, what is fscythe.wad?

**Comment by fabiangreffrath** [comment]
Ah, wait, this is rendered as the gun flash. Does the gun sprite look translucent in the moment of firing? Is a flash sprite rendered at all?

**Comment by Zodomaniac** [comment]
Fscythe.wad is a fix for playing Scythe MAP07 with D4V.

**Comment by Zodomaniac** [comment]
>Does the gun sprite look translucent in the moment of firing?

Yes, it does.

>Is a flash sprite rendered at all?

Yes, it is. Or is it the rocket sprite? Not sure.

![DOOM0001](https://user-images.githubusercontent.com/15119473/65503297-50657880-decd-11e9-999c-c3b34ffc3350.png)

**Comment by Zodomaniac** [comment]
Here are translucent and non-translucent gun flashes.
![DOOM0006](https://user-images.githubusercontent.com/15119473/65503603-eac5bc00-decd-11e9-922a-54891bb0fa9d.png)
![DOOM0002](https://user-images.githubusercontent.com/15119473/65503602-eac5bc00-decd-11e9-995f-694cbb4cc195.png)

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.
