### ISSUE TITLE
Music slider doesn't work with virtual midi synth

### ISSUE THREAD

**Issue by vocaab** [fabiangreffrath/crispy-doom#462]
Version of Crispy Doom: 5.6.2

Operating System: Windows 10 1903

Game: Doom 1 and Doom 2

I use virtual midi synth for my default midi player. That works correctly. I notice it's loud, but then when I use the music slider, it doesn't even function. I can turn the music down through virtual midi synth/windows sound mixer, but I don't quite understand why the music slider doesn't function. With a music pack, the music slider functions correctly, and when I use MS GS Wavetable Synth, the music slider works. Not the biggest deal, but it's something I observed using a popular midi player.

Thanks.

**Comment by Zodomaniac** [comment]
I'm glad the music pack functions correctly, did you find it at the Doomworld forums?

**Comment by vocaab** [comment]
The music pack I use is from here: http://sc55.duke4.net/ I'm unsure if MusicallyInspired posts at doomworld forums.

I just tried the Chocolate Doom daily build, and the slider doesn't work.

**Comment by Zodomaniac** [comment]
>I just tried the Chocolate Doom daily build, and the slider still doesn't work with virtual midi synth.

Please open this issue for Choco then :)

**Comment by fabiangreffrath** [comment]
Sorry, but this is nothing that can be fixed by the source port.
