### ISSUE TITLE
Enable pausing demo playback with Pause key

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#463]
I've had an idea to enable pausing the demo playback, the same way as recording can be paused with Pause key. P. S. When pausing the game with Pause key, the music is muted but not paused.

**Comment by fabiangreffrath** [comment]
Won't this cause `basetic` and `leveltime` to get out of sync? Won't this affect Revenant homing missiles, etc.?

**Comment by tpoppins** [comment]
Yikes, sorry for the commit spam.
