### ISSUE TITLE
Blinking status bar while changing automap overlay mode

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#464]
This visual bug happens only while low framerate. To reproduce it, please repeat following steps:

* First, run any kind of map with massive scene which drops framerate to about 10-15. Sunder_21813 map15 in some places is good example.
* Increase screen size to Crispy HUD w/o status bar.
* Open automap, enable overlay mode.
* Now simple hold `TAB` button.
* You will notice, that status bar is appearing for some frames.

This is happening because of invoking `ST_refreshBackground`, which does not seems to be needed in this case. 

~Suggested~ Possible solution, applied in RD: https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/st_stuff.c#L494, although I'm not sure it's fits for Crispy - in RD I have a four various status bar drawing functions (doom standard/wide, jaguar standard/wide), so your own inspection is still needed.

**Comment by Zodomaniac** [comment]
@JNechaevsky could you try Struggle MAP28 if this can be reproduced?

**Comment by fabiangreffrath** [comment]
So, this will be the fix?
```
--- a/src/doom/st_stuff.c
+++ b/src/doom/st_stuff.c
@@ -460,7 +460,7 @@ void ST_Stop(void);
 void ST_refreshBackground(void)
 {

-    if (screenblocks >= CRISPY_HUD && !automapactive)
+    if (screenblocks >= CRISPY_HUD && (!automapactive || crispy->automapoverlay))
         return;

     if (st_statusbaron)

```

**Comment by fabiangreffrath** [comment]
Yes?

**Comment by Zodomaniac** [comment]
Gonna check in an hour.

**Comment by Zodomaniac** [comment]
Looks like it has worked ;)

P.S. 
>`if (st_statusbaron)`

Sensation! Leaked code shows future possibility to play as Baron of Hell, like in Brutal Doom! XD
