### ISSUE TITLE
Keep automap settings

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#465]
As was discussed, keeping automap setting will be a good addition. Possible ways of setting keeping 

1. Automap settings should be kept in saved games, then reset after starting a new game.
2. Automap setting should be set once and kept for ever, just like other gameplay features.

I still would like to suggest approach №2 because of simplicity for player - just need choose setting once, same to gameplay features and/or other settings.

List of setting to keep:
* Follow mode
* Overlay mode
* Rotate mode
* Grid

_Suggestion №111, initial discussion: 
https://github.com/JNechaevsky/russian-doom/commit/2b22e9d8b9f5f5110ab8382c19782ac35e272f71_

**Comment by Zodomaniac** [comment]
I vote for #2 approach.

**Comment by fabiangreffrath** [comment]
Hm, I'd argue that settings like Automap overlay are not general gameplay features but rather situation depending. I'd be surprised if I decided to use the overlay on one map and find it still active if I load a different one.

**Comment by JNechaevsky** [comment]
But it is. For example, GZDoom allows to highly customize automap with whole menu section, and settings will stay same until user will change them again. 

Not sure about PrBoom+, can't check it now.

**Comment by Zodomaniac** [comment]
What about Crispy keys for saving and loading combined automap+screen size settings? (e.g. T and B by default)

**Comment by JNechaevsky** [comment]
PrBoom+ (2.5.1.4) is remembering all four modes. Anyways, @fabiangreffrath, final decision must be yours.

**Comment by fabiangreffrath** [comment]
Follow and grid are probably nonsense, but I'll consider turning overlay and rotate into config variables.
