### ISSUE TITLE
Automatically update default savegame names?

### ISSUE THREAD

**Issue by zebzorb** [fabiangreffrath/crispy-doom#467]
When I save a game (in 5.6.3) it automatically fills in the name with the current map and wad -- e.g. it'll put "MAP03 (3HAFINAL)" if I'm on map03 of 3hafinal.wad.

This is really handy! However, if I'm on map05 and I save over the same slot, it keeps the name the same as it was: MAP03.

It'd be great if it could detect that the slot I'm saving over has an automatically generated name and update the map number and wad name. I was thinking custom save names (i.e. names that don't match the pattern) would retain their labels, like the way it is now.

I know I can delete the old save first, but that's an extra key (and you have to be in the save menu, so it doesn't work with quicksaving) and I'm lazy :stuck_out_tongue_closed_eyes:

**Comment by fabiangreffrath** [comment]
Very nice idea, I like it!
