### ISSUE TITLE
Daily auto-builder failure to build Crispy

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#468]
What's the matter with the auto-builder? Crispy Travis build passes but the auto-builder builds Choco only and not Crispy since October 1.

**Comment by fabiangreffrath** [comment]
I noticed. We'll have to ask @fragglet what's the matter.

**Comment by fragglet** [comment]
Fixed.

**Comment by fabiangreffrath** [comment]
@fragglet Great, thanks! Would you mind sharing what was the cause? Anything that I could fix myself in the future?

**Comment by fragglet** [comment]
```
ATTENTION: Crispy Doom autobuild failed:
From https://github.com/fabiangreffrath/crispy-doom
   5c5d69cb..346ad029  master     -> origin/master
fatal: Not possible to fast-forward, aborting.

Failed to cleanly 'git pull' from upstream. You may need to
manually resolve merge conflicts with local changes, eg.
```
Did you do a force push by any chance (`git push -f`)?

**Comment by fabiangreffrath** [comment]
Oh, indeed. But that was a different (WIP) branch.

**Comment by fabiangreffrath** [comment]
@fragglet Erm, I am afraid it happened again today.

**Comment by fabiangreffrath** [comment]
This seemed to be false alarm, sorry. However, there is something psurious in the build logs that I cannot find in Chocolate's:
```
for f in README.md README.Music.md COPYING.md NEWS.md; do                              \
	pandoc  -f gfm -o staging-doom/$(basename $f .md).html  \
		-s ../../$f;                     \
done
pandoc: Unknown reader: gfm
pandoc: Unknown reader: gfm
pandoc: Unknown reader: gfm
pandoc: Unknown reader: gfm
GNUmakefile:39: recipe for target 'staging-doom' failed
```
