### ISSUE TITLE
Static automap grid bug 

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#474]
Oh yes, automap again. :scroll:

There is a vanilla bug in grid mode. Have a look at left side, there is always first vertical line missing ([screenshot](https://user-images.githubusercontent.com/21193394/66413361-e508c400-e9ff-11e9-9302-2bf74d226d9a.png)), but interestingly, this is not happening on huge maps like Sunder MAP15 ([screenshot](https://user-images.githubusercontent.com/21193394/66413437-0f5a8180-ea00-11e9-8ecf-20492f2102db.png)).

This problem seems to be investigated and fixed in PrBoom+: https://github.com/coelckers/prboom-plus/blob/master/prboom2/src/am_map.c#L1221

"Seems to be working" solution is commenting out all `if (crispy->automaprotate)` conditions in `AM_drawGrid`, just like this:
```
    // Figure out start of vertical gridlines
    start = m_x;
--- if (crispy->automaprotate)
    {
	start -= m_h / 2;
    }
```

But I really not sure it's a good way to go, automap system is still something beyond my subconscious.

_Suggestion №113_

**Comment by fabiangreffrath** [comment]
I have extended the limits in the `if (crispy->automaprotate)` case, because if you rotate the map you have to draw much more and longer lines than you would have to with a static map. Adding half the map dimensions to each end was just a quick estimation that proved to work.

There is a much clearner solution to this in PrBoom+'s code.

However, there is also a comment stating:

```
  // Fix vanilla automap grid bug: losing grid lines near the map boundary
  // due to unnecessary addition of MAPBLOCKUNITS to start
  // Proper math is to just subtract the remainder; AM_drawMLine will take care
  // of clipping if an extra line is offscreen.
```

Translated into Vanilla Automap code, this should be the right solution:

```
--- a/src/doom/am_map.c
+++ b/src/doom/am_map.c
@@ -1247,7 +1247,7 @@ void AM_drawGrid(int color)
        start -= m_h / 2;
     }
     if ((start-bmaporgx)%(MAPBLOCKUNITS<<FRACBITS))
-       start += (MAPBLOCKUNITS<<FRACBITS)
+       start += // (MAPBLOCKUNITS<<FRACBITS)
            - ((start-bmaporgx)%(MAPBLOCKUNITS<<FRACBITS));
     end = m_x + m_w;
     if (crispy->automaprotate)
@@ -1280,7 +1280,7 @@ void AM_drawGrid(int color)
        start -= m_w / 2;
     }
     if ((start-bmaporgy)%(MAPBLOCKUNITS<<FRACBITS))
-       start += (MAPBLOCKUNITS<<FRACBITS)
+       start += // (MAPBLOCKUNITS<<FRACBITS)
            - ((start-bmaporgy)%(MAPBLOCKUNITS<<FRACBITS));
     end = m_y + m_h;
     if (crispy->automaprotate)

```

**Comment by JNechaevsky** [comment]
Awesome! Let me please check in the evening. 

This probably will also fix one small problem with minimum zoom level + grid + rotation in huge maps, but that's another day's question - a day, when Crispy will be available in widescreen mode.

**Comment by JNechaevsky** [comment]
Checked. Da, that's working perfectly, in both small and huge maps!

As about grid bug in rotation mode, sorry, false alarm. I was using old code in `AM_rotatePoint`, with `fixed_t tmpx;`, when it should be `int64_t tmpx;`.
