### ISSUE TITLE
Non-MIDI music played from WADs should be played by main exe, not by midiproc

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#475]
### Background

Version of Crispy Doom: 5.6.3

Operating System and version: Win 7 Professional x64

Game: Doom (2)

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: If you
- launch Crispy without command line arguments,
- then set music volume to 1,
- quit and 
- launch with `start crispy-doom -merge  DoomMetalVol5_44100.wad`, the MP3/OGG/FLAC music is almost inaudibly quiet.
What happens in Windows mixer is:
![vicious midiproc](https://user-images.githubusercontent.com/15119473/66555691-c0276480-eb57-11e9-91ea-012aa05411c2.png)

Expected behavior: Midiproc volume not to influence music played by Crispy Doom itself.

This is a Crispy issue as Choco won't play music from WADs at all, and when playing music in Music Pack Choco fashion the midiproc volume doesn't influence MP3/OGG/FLAC music volume.

**Comment by fabiangreffrath** [comment]
> set music volume to 1
[...]
> music is almost inaudibly quiet

Erm, I don't exactly understand the problem here. Do you expect music volume to be stored by file type? Quite apparently, it is midiproc that is playing the MP3/OGG/FLAC music lumps here, so what exactly to you want to be changed?

**Comment by Zodomaniac** [comment]
Try increasing music volume in Doom after taking all these steps, I changed the volume to 15 but midiproc volume is still as if it was on 1!
![vicious midiproc 2](https://user-images.githubusercontent.com/15119473/66561303-e5b96b80-eb61-11e9-9c38-46058fdf214d.png)

**Comment by Zodomaniac** [comment]
Looks like the volume is applied to music from WADs twice: from the main executable and from the midiproc. Is that right?

**Comment by fabiangreffrath** [comment]
> The solution is obvious: if music lump is MP3/OGG/FLAC/whatever but not MUS/MIDI/fluidsynth,
> play it with the main process, not midiproc!

But this doesn't seem to make any sense. It should not matter which process plays the music. The volume is supposed to be in sync between Doom and the midiproc process.

**Comment by fabiangreffrath** [comment]
Does this help?
```
--- a/midiproc/main.c
+++ b/midiproc/main.c
@@ -149,7 +149,7 @@ static void PlaySong(int loops)
     //
     //      To work around this bug, we set the volume to itself after the MIDI
     //      has started playing.
-    Mix_VolumeMusic(Mix_VolumeMusic(-1));
+//  Mix_VolumeMusic(Mix_VolumeMusic(-1));
 }

 static void StopSong()
diff --git a/src/i_sdlmusic.c b/src/i_sdlmusic.c
index f4129f3a..df5cf4ff 100644
--- a/src/i_sdlmusic.c
+++ b/src/i_sdlmusic.c
@@ -285,6 +285,7 @@ static void I_SDL_PlaySong(void *handle, boolean looping)
     if (midi_server_registered)
     {
         I_MidiPipe_PlaySong(loops);
+        UpdateMusicVolume();
     }
     else
 #endif

```

**Comment by Zodomaniac** [comment]
>It should not matter which process plays the music.

IMO the same format lumps should be played by the same process, no matter if they are Music pack files or WAD lumps.

>Does this help?

No, it doesn't. I say that setting the in-WAD music lumps to play with the main process will help.

**Comment by fabiangreffrath** [comment]
There is no compelling *technical* reason for that - apart from the fact that it apparently mitigates the symptoms of the real underlying issue.

**Comment by Zodomaniac** [comment]
But there is the reason of unification, in addition to mitigating the symptoms.

**Comment by Zodomaniac** [comment]
*Up*
I hope my reasoning is enough to move playing non-MIDI away from midiproc :)

**Comment by fabiangreffrath** [comment]
Erm, no! There is no technical reason why midiproc should not work properly with MP3 or OGG music lumps. So, we need to find out the reason why it actually does not work properly. I hate "I don't know why, but it works this way so let's do it this way" kind of solutions. Also, I am not going to add a bunch of code to `i_sdlmusic.c` in order to shutdown or restart midiproc depending on the music type. This should simply be not necessary.

**Comment by Zodomaniac** [comment]
But well...how does Choco play MP3s etc. Music Packs with the main process? Cannot the same code be used for WAD lumps?

**Comment by fabiangreffrath** [comment]
"same code" here means "music from lumps is played by midiproc".

**Comment by Zodomaniac** [comment]
Is there a way to re-use Music Pack playing code for lumps?

**Comment by Zodomaniac** [comment]
Then maybe we could approach this another way round, moving all the music playing to midiproc (including Choco Music packs) and the volume slider in Doom to apply no attenuation inside the main process but always control the midiproc volume in the mixer. regardless of the format played?

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.
