### ISSUE TITLE
Demo playback 

### ISSUE THREAD

**Issue by satori80** [fabiangreffrath/crispy-doom#479]
I've noticed that version 5.6.3 doesn't display end of game sequences in demos (ie. The burning city with impaled bunny heads @ the end of episode 3 in doom) .

Please note that this works properly for normal game play, only -playdemo has this problem.

Also note that chocolate doom 3.0.0 properly preserves the end of game sequences in demo playback.

**Comment by fabiangreffrath** [comment]
Oh, I guess that's because Crispy shows the tally screen after ExM8 and Choco doesn't.

**Comment by satori80** [comment]
I didn't realize crispy did something different there.

I don't suppose there is a way around that....
