### ISSUE TITLE
Setup is white then closes

### ISSUE THREAD

**Issue by nhaselton** [fabiangreffrath/crispy-doom#480]
I can't run the setup, when it do it pops up a white window then closes almost instantly

**Comment by Zodomaniac** [comment]
What's your operation system?

**Comment by fabiangreffrath** [comment]
You need to run the setup from a directory to which you have write access so it can create its configuration files. Try running it e.g. from your Desktop.

**Comment by fabiangreffrath** [comment]
Any antivirus active? Avast probably?

**Comment by fabiangreffrath** [comment]
This won't lead us anywhere...
