### ISSUE TITLE
Crisps background to the main menu - garnish for the demon meat!

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#481]
I've figured out a suggestion to increase the individuality of the port.
What about drawing Crisps as a background for main menu entries, like this?
Switching off when the menu is off, naturally. And maybe optional (Crispness->Main Menu Crisps, for example)
![crisps_in_the_menu](https://user-images.githubusercontent.com/15119473/66732755-ca05dc00-ee65-11e9-91ef-6c6ddca9960a.png)

**Comment by fabiangreffrath** [comment]
Sorry, neat idea, but no chance. I get regular requests to *reduce* the individuality of the port relative to Choco.

**Comment by Zodomaniac** [comment]
I guess it should be added here
```
//
// M_DrawMainMenu
//
void M_DrawMainMenu(void)
{
    V_DrawPatchDirect(94, 2,
                      W_CacheLumpName(DEH_String("M_DOOM"), PU_CACHE));
}
```
and which drawing function can I use if I have the texture stored as an array in m_background.h?

**Comment by fabiangreffrath** [comment]
The background graphics array in `m_background.h` is stored in the much simpler flats format. Turning this into patch format is possible but not trivial: https://doomwiki.org/wiki/Picture_format

**Comment by Zodomaniac** [comment]
Oh, then I suppose using `void V_DrawBlock(int x, int y, int width, int height, pixel_t *src)` is a better idea :)

**Comment by Zodomaniac** [comment]
Here you are :)
![DOOM0008](https://user-images.githubusercontent.com/15119473/66898337-b3948780-f001-11e9-9e61-7932e048eb19.png)
