### ISSUE TITLE
add a TNTWEAP0 cheat

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#482]
I consider adding a TNTWEAP0 cheat which takes away all weapons and ammo except for the pistol and 50 bullets, i.e. pistol start conditions. I am not sure about health and armor, though, what do you think?

**Comment by Zodomaniac** [comment]
I think the pistol start conditions should include health and armor, health should become 100, armor and berserk strength taken away.

**Comment by Zodomaniac** [comment]
Also, I'd love to see the message after TNTWEAP:
`"Take/leave weapon: %s1-9%s", crstr[CR_GOLD], crstr[CR_NONE]`
It would be nice to have such confirmation that a rather long TNTWEAP word has been typed correctly.

**Comment by fabiangreffrath** [comment]
> I think the pistol start conditions should include health and armor, health should become 100, armor and berserk strength should be taken away, as well as the backpack.

But that would overload the "weapon2 metaphor of the TNTWEAP cheat too much.

> It would be nice to have such confirmation that a rather long TNTWEAP word has been typed correctly.

You would have to introduce a parameter-less TNTWEAP cheat for that which does nothing more than print this message, see the IDBEHOLD cheat.

**Comment by Zodomaniac** [comment]
>I think the pistol start conditions should include health and armor, health should become 100, armor and berserk strength should be taken away, as well as the backpack.

I meant this for TNTWEAP0 only. TNTWEAP2 only should remove the pistol.

**Comment by fabiangreffrath** [comment]
Yes, I understood. But I think a cheat called TNTWEAP should only act on weapons and not on health and armor. The "official" way to do a pistol start of a map is IDCLEV00.

**Comment by Zodomaniac** [comment]
OK, let it not affect health and armor. I think berserk power should be taken away by TNTWEAP0 though, as with this power fist becomes a selectable weapon even with the chainsaw equipped.

**Comment by Zodomaniac** [comment]
>You would have to introduce a parameter-less TNTWEAP cheat for that which does nothing more than print this message, see the IDBEHOLD cheat.

I get your point, but before doing that in So Doom I'd like to ask if you're planning it for Crispy. If yes, I'll just wait and merge.

**Comment by fabiangreffrath** [comment]
>  I'd like to ask if you're planning it for Crispy. 

I don't think so.
