### ISSUE TITLE
Regression testing of Crispy Doom

### ISSUE THREAD

**Issue by fragglet** [fabiangreffrath/crispy-doom#484]
As requested, I looked a bit into setting up a weekly regression test of Crispy Doom, like I've set up for Choco.

Here's the initial output from running the HEAD version (a289afc21f5487d39355b) through statcheck:

https://soulsphere.org/random/crispy.log

There are some common patterns here:

* Statistics are dumped for ExM8, whereas vanilla Doom doesn't generate these because the levels end without an intermission screen. So there are a lot of diffs like this:

```
--- output/doom/fast/f1m8-109.zip/f1m8-109.txt	Tue May 14 12:41:46 2019
+++ /tmp/tmpkfIvQy/output-6.txt	Sun Oct 27 03:09:59 2019
@@ -0,0 +1,11 @@
+===========================================
+E1M8
+===========================================
+
+Time: 1:09 (par: 0:30)
+
+Player 1 (Green):
+	Kills: 29 / 41 (70%)
+	Items: 1 / 3 (33%)
+	Secrets: 1 / 1 (100%)
+
doom/fast/f1m8-109.zip                            f1m8-109.lmp   [91mFAIL[0m
```

I understand the desire to get a more complete statdump output  that includes ExM8, but can we at least get an extra command line argument to disable this behavior so it behaves like vanilla statdump?

* Some of the diffs are excessively verbose, because they're comparing DOS and Unix-format text files. See `doom/movie/ep2-3042.zip` for example - it's just the ExM8 bug again, so most of the diff can be ignored.

* There are some genuine desyncs hiding in the output. For example:

```
--- output/tnt/nmare/tn27-511.zip/tn27-511.txt	Tue May 14 13:03:37 2019
+++ /tmp/tmpkfIvQy/output-9202.txt	Sun Oct 27 14:25:18 2019
@@ -1,11 +0,0 @@
-===========================================
-MAP27
-===========================================
-
-Time: 5:11 (par: 5:30)
-
-Player 1 (Green):
-	Kills: 154 / 290 (53%)
-	Items: 12 / 22 (54%)
-	Secrets: 2 / 2 (100%)
-
tnt/nmare/tn27-511.zip                            tn27-511.lmp   [91mFAIL[0m
```

```
--- output/tnt/nm100s/es17-114.zip/es17-114.txt	Tue May 14 13:01:50 2019
+++ /tmp/tmpkfIvQy/output-8863.txt	Sun Oct 27 14:01:00 2019
@@ -1,11 +0,0 @@
-===========================================
-MAP17
-===========================================
-
-Time: 1:14 (par: 7:00)
-
-Player 1 (Green):
-	Kills: 44 / 102 (43%)
-	Items: 15 / 23 (65%)
-	Secrets: 4 / 4 (100%)
-
tnt/nm100s/es17-114.zip                           es17-114.lmp   [91mFAIL[0m
```

```
--- output/tnt/speed/ev28-124.zip/ev28-124.txt	Tue May 14 13:04:37 2019
+++ /tmp/tmpkfIvQy/output-8704.txt	Sun Oct 27 13:55:16 2019
@@ -1,11 +0,0 @@
-===========================================
-MAP28
-===========================================
-
-Time: 1:24 (par: 7:00)
-
-Player 1 (Green):
-	Kills: 25 / 116 (21%)
-	Items: 1 / 2 (50%)
-	Secrets: 0 / 2 (0%)
-
tnt/speed/ev28-124.zip                            ev28-124.lmp   [91mFAIL[0m
```

I haven't dug too deep into the causes of these, but they look like genuine desyncs where the demo isn't completing and should probably be looked into and fixed.

**Comment by fabiangreffrath** [comment]
@fragglet Thank you very much for doing this!

> * Statistics are dumped for ExM8, whereas vanilla Doom doesn't generate these because the levels end without an intermission screen. So there are a lot of diffs like this:

Alright, I will suppress statdump output for ExM8 maps.

> * Some of the diffs are excessively verbose, because they're comparing DOS and Unix-format text files. See `doom/movie/ep2-3042.zip` for example - it's just the ExM8 bug again, so most of the diff can be ignored.

The `diff` command has a variety of command line options to ignore differences in whitespace and also explicitely in line endings. At least GNU diff has `--ignore-all-space` and `--strip-trailing-cr`. And, last but not least, it is still possible to run the command like this: `diff -u <(cat file1 | dos2unix) <(cat file2 | dos2unix)`, at least with the bash shell.

> * There are some genuine desyncs hiding in the output. For example:

Now it gets beefy. Thanks for these, I'll have to investigate them as soon as time allows!

**Comment by fragglet** [comment]
Ran again, PTAL at https://soulsphere.org/random/crispy.log

Most failures have now been eliminated, these are the ones which still remain:

```
doom2/nm100s/ns11-135.zip                         NS11-135.LMP   FAIL
doom2/nm100s/ns11-129.zip                         NS11-129.LMP   FAIL
pwads/hr/fast/hf132611.zip                        hf132611.lmp   FAIL
pwads/hr/coop/hn32c021.zip                        hn32e021.lmp   FAIL
pwads/hr/coop/hn32c021.zip                        hn32t021.lmp   FAIL
tnt/speed/ev28-124.zip                            ev28-124.lmp   FAIL
tnt/nm100s/es17-114.zip                           es17-114.lmp   FAIL
tnt/nmare/tn27-511.zip                            tn27-511.lmp   FAIL
```

All appear to be desyncs where the level doesn't complete as expected.

**Comment by fabiangreffrath** [comment]
Thank you for running this again! So, we are down to 8 desyncs out of ~9500 which isn't *that* bad but still more than I hoped for.

**Comment by fragglet** [comment]
Yes, but bear in mind that there's a good chance all those are caused by one bug and once it's fixed you'll be back to 100% :)

**Comment by fabiangreffrath** [comment]
> doom2/nm100s/ns11-135.zip                         NS11-135.LMP   FAIL

This desync has been introduced somewhere between the 3.3 and 3.4 releases.

**Comment by fabiangreffrath** [comment]
Culprit found! https://github.com/fabiangreffrath/crispy-doom/commit/43bab

**Comment by fragglet** [comment]
Nice job! I'll rerun those tests and assuming they pass, I'll set up the Crispy tests to run every week.

**Comment by fragglet** [comment]
Oh, I guess you haven't committed the fix yet ...

**Comment by fabiangreffrath** [comment]
> Oh, I guess you haven't committed the fix yet ...

Not yet. I was still hoping for an alternative demo-friendly implementation - but failed so far. I guess that an mobj's `floorz` and `ceilingz` values affect moving sectors through `P_ThingHeightClip()` in `PIT_ChangeSector()` but I haven't investigated any farther. It seems a bit illogical, because `MT_FIRE` mobjs are not even registered in the BLOCKMAP, but well, it is clearly the culprit but my analysis so far is just a guess. I'll revert the offending commit in a minute...

**Comment by fabiangreffrath** [comment]
> Nice job! I'll rerun those tests and assuming they pass, I'll set up the Crispy tests to run every week.

This will be great, thank you very much for that! :kissing_heart:

**Comment by fragglet** [comment]
Thanks. The tests all now pass and I've set up the weekly cronjob to run on Tuesdays. Results will appear here:

http://evans.soulsphere.org/autobuild/crispy.txt

**Comment by fabiangreffrath** [comment]
Yeeha, thanks!

**Comment by fabiangreffrath** [comment]
@fragglet Are these regression tests performed on a clean check-out in a clean environment? I am asking, because currently all additional Crispy-specific features are turned off by default, even the non-critical ones. However, I would like to do a regressions test with all of these features turned. For this, I will either have to provide a config file or temporarily set the defaults of all features to "enabled". The latter, however, will only work if the engine is run in a clean environment with no config file available yet.

**Comment by Zodomaniac** [comment]
> http://evans.soulsphere.org/autobuild/crispy.txt

@fragglet , the link doesn't work :(

**Comment by fragglet** [comment]
Thanks for the heads up. Machine seems to have gone down - I hope to have it back up by Friday

**Comment by fragglet** [comment]
A long-overdue update: new hardware I ordered doesn't work in the machine. Will order an alternative and still hope to have it back up at some point during the holiday.
