### ISSUE TITLE
NOMOMENTUM cheat makes the player burrow into stairs

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#488]
When walking around with `NOMOMENTUM`, the player falls down correctly from ledges but burrows into the stairs instead of walking up them. Walking around on MAP02 will reproduce that.

**Comment by Zodomaniac** [comment]
I hope this is not a wontfix...)

**Comment by fabiangreffrath** [comment]
No, but a LOWPRIO 😉
