### ISSUE TITLE
MP3/OGG/FLAC playback from WAD lumps is broken

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#493]
### Background

Version of Crispy Doom: Latest git

Operating System and version: Win 7 Prof x64

Game: Doom (2)

Any loaded WADs and mods (please include full command line): `start crispy-doom -merge DoomMetalVol5_44100.wad`

### Bug description

Observed behavior: The real-tone music from WAD lumps is not played, there is silence instead.

Expected behavior: The music should be played. I'm pretty sure recent four commits broke something as So Doom that is 4 commits behind plays music OK.

Note: the music played as Music Pack (Choco fashion) plays OK.

**Comment by fabiangreffrath** [comment]
None of the most recent commits touched the music system. Did you exchange some DLLs or change the music backend setting?

**Comment by Zodomaniac** [comment]
No, I didn't. I have So Doom and Crispy Doom in the same folder, they even share the default.cfg.

**Comment by Zodomaniac** [comment]
It fixed itself on booting up the PC another time as suddenly as it appeared.
