### ISSUE TITLE
50% weapon bobbing option

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#496]
If we have the difference as subtle as the one between full and 75% bobbing implemented, why not bring half bobbing amplitude?

**Comment by Zodomaniac** [comment]
There was half bobbing amplitude before the rework, in weapon attack alignment options.

**Comment by fabiangreffrath** [comment]
Yep, but then I decided there won't be more than one option for centering and bobbing during attacks anymore now that bobbing can get reduced globally.

**Comment by Zodomaniac** [comment]
OK, +1 setting for So Doom again :)
