### ISSUE TITLE
Issue in Crispy with SIGIL MIDI and VST players.

### ISSUE THREAD

**Issue by putridpete** [fabiangreffrath/crispy-doom#498]
I've been using Falcosoft's MIDI Player to use a Yamaha S-YXG50 VSTi plugin to play MIDIs. I've noticed that in Crispy Doom whenever I play the first level of SIGIL, the MIDI has a part where the volume is really low. You can hear an example in this link: https://streamable.com/vdp9b. The same issue also happens with VSTHost or Savihost. It also happens with any other plugin, such as Sound Canvas VA. The issue is not present in PrBoom+ or GZDoom. Here's how it sounds in PrBoom+: https://streamable.com/07sm9.

This problem seems to happen only in SIGIL, as I've played through all previous four episodes of Doom without any issues. I've yet to play Doom II, however.

I'm using Crispy Doom 5.6.3, Windows 10, and other additional tools that may be related such as OmniMIDI, OmniMapper (also tried CoolSoft's MIDIMapper to no avail) and loopMIDI.

Could the issue be on my end due to a wrong configuration? Regardless, I'd appreciate any help.

**Comment by fabiangreffrath** [comment]
Sorry, but I will _never_ be able to reproduce this.

**Comment by putridpete** [comment]
Oh well, since it only happens with SIGIL, I guess I'll just have to fire up PrBoom+ for that. Crispy Doom's sound out of the box won't work for me without the older DLLs Zodomaniac provided (https://www.doomworld.com/forum/post/2035784), so I'm guessing it's related to that in some form. Thanks anyway.

**Comment by fabiangreffrath** [comment]
Thanks for reporting anyway!

**Comment by Zodomaniac** [comment]
@putridpete, I'm glad that the older DLLs hrlp to mitigate your issue :)
@fabiangreffrath, are you going to report this issue and that SDL 2.0.10 bugged audio with 5.1 sound configuration on Windows in SDL2 issue tracker?

**Comment by fabiangreffrath** [comment]
No, because I couldn't answer any questions. That's why "someone told me that this doesn't work" bug reports are mostly/always useless.

**Comment by Zodomaniac** [comment]
https://www.youtube.com/watch?v=WBWB81EOVQQ This is the demonstration of the sound bug on Windows with speaker configuration 5.1. I thought that your word as that of a developer would have more impact than mine :)

**Comment by fabiangreffrath** [comment]
Nope. They won't care about me developing a Doom source port or not. But they might have questions regarding speaker setup, driver versions etc. that I just won't be able to answer.

**Comment by putridpete** [comment]
Just for posterity, and if anybody who has the same issue finds this, I at least managed Roland's Sound Canvas VA to work with SaviHost. I simply switched to the x64 version and it worked. I was using the x86 because the Yamaha VSTi plugin was x86 only and that's the one I downloaded first. However, VSTHost and Falcosoft's MIDI player still present the same issue even on their x64 varieties. Sadly no luck to get the S-YXG50 VSTi plugin to work properly since it's x86 only, so I can't test it with the x64 working version of SaviHost.

Anyway, here's the bittersweet victory of at least getting SCVA to render that part in Crispy Doom and allowing me to avoid a port switcheroo: https://streamable.com/mf0xm

Hope this information proves useful to anyone.

**Comment by putridpete** [comment]
Sorry to keep posting on this after it's been closed, but I've come up with a new development. I found out that while using the Sound Canvas VA plugin with Falcosoft's MIDI player, if I start Crispy with the SIGIL wad and play the Knee Deep in the Dead episode first, then switch over to the SIGIL episode, any issues with the MIDIs get sorted out. You have to do this every time you start SIGIL, even if you've already beaten the opening level because there are a few other MIDIs that present problems later on, such as the ending theme.

For the S-YXG50 VSTi plugin, I have excellent news as well. I also managed to get it to work. What you need to do is hit the reset button that is present in Falcosoft's MIDI player from either the main menu or another episode, then start the SIGIL episode and all MIDIs play fine. This method DOES NOT WORK with Sound Canvas VA, however.

Why this fixes all issues is beyond me, but hey... it works!
