### ISSUE TITLE
Disable translucency on pwad replacement sprites

### ISSUE THREAD

**Issue by plumsinus** [fabiangreffrath/crispy-doom#50]
Or at least the powerups. I think projectiles are maybe safe to have always translucent?

It might be nice if sprite translucency (and coloured blood) were turned off on a per-sprite basis instead of turning it all of if there is one replacement sprite. A bonus is that this would also let people turn off coloured blood for individual enemies (like the latest post in the DW thread) with a simple hack of including a pwad that had the necessary sprites.

**Comment by fabiangreffrath** [comment]
@plumsinus 
If you ever read this: colored blood, fixed-up blood for the Lost Soul and Spectre as well as translucency can be turned off separately, but this will have global effect. 

Are you fine with closing this bug? I don't think configuration will ever get any more fine-grained than that...

**Comment by fabiangreffrath** [comment]
Hey @plumsinus ,

now that you are back, could you please review this issue and close it if you find appropriate?

 Thanks!

**Comment by plumsinus** [comment]
Hey, just caught this now. I like the current solution. Closing.
