### ISSUE TITLE
v1.2 support incomplete

### ISSUE THREAD

**Issue by tpoppins** [fabiangreffrath/crispy-doom#500]
### Background

Version of Crispy Doom:
2019-11-29 daily build

Operating System and version:
Win 7 x64 Pro SP2

Game: (Doom/Heretic/Hexen/Strife/other)
DOOM

Any loaded WADs and mods (please include full command line):
[1_ON_1.WAD](https://www.doomworld.com/idgames/levels/doom/0-9/1_on_1) with the accompanying v1.2 demo

cmdline:
-iwad doom.wad -file 1_ON_1.WAD -playdemo 1_ON_1 -gameversion 1.2

### Bug description

Observed behavior:
Sectors 305 and 308 -- segments (second from the south) of the walkways over the nukage that lead to the BFG in the south - fail to rise. 

Expected behavior:
Sectors 305 and 308 are supposed to rise to the level of the adjacent walkway segments, the way it works in the v1.2 vanilla. Prb+ doesn't emulate this 100% (they rise slightly higher), yet plays the demo successfully to the end.

This is a situation similar to the exit bridge on [RETURN01](https://www.doomworld.com/idgames/levels/doom/p-r/return01) E1M2. Crispy desyncs on my old [v1.2 max](http://doomedsda.us/col159.html) too. These are the only two v1.2 demos I've encountered out of a couple dozen tested so far that Crispy has trouble with.

**Comment by fabiangreffrath** [comment]
Crispy's support for pre-1.9 versions is inherited from Chocolate Doom. Any incompatibilities should be reported there. And, from what I understand, support for v1.2 and earlier is not complete yet but still work-in-progress.
