### ISSUE TITLE
Make Tutti-frutti fix optional

### ISSUE THREAD

**Issue by tpoppins** [fabiangreffrath/crispy-doom#501]
There are quite a few maps where Tutti-frutti appears to be part of the design. Some examples:

The TEKWAL1 door to the automap secret on the original E2M2 - the green stripe at the top appears to be a hint to the secret's presence.
[ALOHA911.WAD](https://www.doomworld.com/idgames/levels/doom/a-c/aloha911) E1M3 - [screenie](https://postimg.cc/Lh9zNrDG).
[APOCALYP.WAD](https://www.doomworld.com/idgames/levels/doom/a-c/apocalyp) E1M2 - [screenie](https://postimg.cc/nsNPvnq8).
The R.WAD example on the doomwiki's [Tutti-frutti page](https://doomwiki.org/wiki/Tutti-frutti_effect).

This could be optioned via the config file, no need to clutter the menus; the fix could stay on by default.

**Comment by fabiangreffrath** [comment]
I don't think that Tutti-Frutti has been used intentionallyin IWADs, it always looks like crap. Also, that second screenshot (APOCALYP.WAD E1M2) does not show classic Tutti-Frutti, but a texture with transparent areas ("holes") used on a single-sided linedef, which is a different can of worms. I don't think I am going to re-introduce that.

**Comment by fabiangreffrath** [comment]
Sorry, but this won't happen.
