### ISSUE TITLE
"Error creating render for screen window: Couldn't find matching render driver"

### ISSUE THREAD

**Issue by SGacore** [fabiangreffrath/crispy-doom#502]
I admit i am a complete newbie when it comes to sourceported Doom (as the pic shows, i'm using Crispy) and i literally got both the wads and the sourceport today, so i don't know what i should do. I googled this error and i could only find old threads talking about this issue on Chocolate Doom. I have Win7 32-bit with a basic VGA card. I hope it's not a problem on the sourcecode because i don't even know how to open that up (unless it is crispy-doom.cfg or i need to open one of the dll files?).
![cdddd](https://user-images.githubusercontent.com/58445709/69999827-f4a01700-152f-11ea-9dd6-4243ce1ceb44.png)

**Comment by fabiangreffrath** [comment]
Oh, it seems that your graphic card or driver does not support 3D acceleration. Please open the `crispy-doom.cfg` file and change the `force_software_renderer` line to end with `1`.

**Comment by SGacore** [comment]
Ah, it was just that, thank you.

**Comment by fabiangreffrath** [comment]
I am glad that helped you! However, you shouldn't need to find this out yourself - it just shouldn't be necessary. Our video initialization code should be smart enough to detect this case itself and fix it. 

Thus, I have filed the following PR for that:
https://github.com/chocolate-doom/chocolate-doom/pull/1221
