### ISSUE TITLE
Fails to build with CMake

### ISSUE THREAD

**Issue by turol** [fabiangreffrath/crispy-doom#505]
Latest master fails to build on Linux with CMake. Autoconf build works. Error is

```
Building C object src/doom/CMakeFiles/doom.dir/r_swirl.c.o
crispy-doom/src/doom/r_swirl.c:22:10: fatal error: doomstat.h: No such file or directory
   22 | #include <doomstat.h>
      |          ^~~~~~~~~~~~
compilation terminated.

```

As far as I can tell this is the only file which fails, with `-k` it keeps going and builds the other binaries. Incorrect include paths somewhere?

**Comment by fabiangreffrath** [comment]
Known bug, forgotten to push.

Fixed in https://github.com/fabiangreffrath/crispy-doom/commit/74ecad64eca6d2ff531d80761d74382f13aa4cba

Thank you!

**Comment by turol** [comment]
Confirm fixed.
