### ISSUE TITLE
Please support higher resolution.

### ISSUE THREAD

**Issue by skyrain128** [fabiangreffrath/crispy-doom#506]
Please support higher resolution.
640x480 resolution is not enough in 2019.
I need higher resolution like 1920x1080, 2560x1440 and 7680x4320.
Can you make this Doom source port supports higher resoluton??

**Comment by fabiangreffrath** [comment]
> 640x480 resolution is not enough in 2019.

[citation needed]

> I need higher resolution like 1920x1080, 2560x1440 and 7680x4320.
> Can you make this Doom source port supports higher resoluton??

Nope, sorry, Crispy will stay at 640x400.

**Comment by Zodomaniac** [comment]
@skyrain128 With Doom's low-res sprites and textures, framebuffer resolutions higher than 640x400 make no sense.
