### ISSUE TITLE
[Question] Uncapped framerate... not uncapped?

### ISSUE THREAD

**Issue by vanfanel** [fabiangreffrath/crispy-doom#508]
Hi!

Its been a lot of time since I tried building Crispy, and I saw with great pleasure that it has incorporated SDL2 support and some important features like low-res rendering with uncapped framerates and vsync.

However, uncapped framerate in Crispy seems to be NOT uncapped. In DoomRetro, for example, uncapped framerate gives smooth and rock-solid near-60FPS screen refresh (I say near-60FPS because every HDMI video mode has different exact rates in the 60.xxxx range, not exactly 60.000Hz).
However, setting uncapped + vsync in Crispy gives smooth but near-30FPS refresh rate instead (half the monitor screen refresh actually).
I seem to understand Crispy is missing movement interpolation, hence it can not do uncapped 60-ish screen refresh, am I right?

**Comment by fabiangreffrath** [comment]
Erm, no, Crispy does frame interpolation and if you have both uncapped and vsync enabled it should play smoothly with the screen's refresh rate. Please make sure you don't have `force_software_rendering` enabled in the config file.

**Comment by vanfanel** [comment]
I dont have `force_software_rendering` in my CFG, that makes the game run with a VERY low framerate. 
Mu CPU usage is ~13%, so the framerate is not limited by the CPU either. Strange.

**Comment by fabiangreffrath** [comment]
What does the SHOWFPS cheat show if you play with uncapped framerate enabled and vsync disabled?

**Comment by fabiangreffrath** [comment]
Will this lead us anywhere?

**Comment by vanfanel** [comment]
@fabiangreffrath I am VERY sorry to have been so late in answering to this issue thread.
SHOWFPS shows 30, with occasional drops to 27-28.
Thats with uncapped framerate and vsync disabled. Take into accound VSYNC is always enabled in the VC4 MESA driver, on top of which SDL2 runs on the Pi.
CPU usage during Doom2 map1 is around 13-15% as I said.

**Comment by fabiangreffrath** [comment]
Well, if you will not reach more than 30 FPS with uncapped framerate and with vsync disabled, but vsync is forced upon you by your video driver, well what do you expect me to do for you then?

**Comment by vanfanel** [comment]
@fabiangreffrath The problem is not vsync: DoomRetro, for example, runs at rock-solid 60FPS with VSYNC on (its always on with the VC4 driver on Raspberry Pi).
I mean: with a CPU usage of ~15%, there is plenty of room for 60FPS instead of 30.
My guess here is that the two-buffers for scaling that Crispy uses, with the inherent double copy per frame associated to it, is taking too long on the Pi and thus forcing the engine to skip one frame update of each two: game loop + two buffer copies take more than 16ms per frame, so we get locked to 30fps instead of the typical ~60 matching the screen vsync rate.

So, what about an option where only ONE scaling buffer is used? No grainy DOS-like scaling, of course, but it could be paired with `SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "linear")`
and the results would be great! (Well, they ARE great, since I do that with DoomRetro). And having to do only ONE scaling, Crispy would be running at 60FPS on the poor but popular Raspberry Pis.

**Comment by fabiangreffrath** [comment]
Well, that option is already there. If you disable "smooth pixel scaling" in the Crispness menu, the framebuffer is directly loaded into the texture that gets scaled to screen without any intermediate step.

**Comment by vanfanel** [comment]
@fabiangreffrath I disabled "smooth pixel scaling" and now CrispyDoom runs at 60FPS on my Pi, awesome! So I was right: the two-times buffer copy due to the intermediate buffer usage was to blame. And you were right too (of course you were, its your code!) :D

There is however some hiccups during gameplay, lowering framerate to ~55FPS. Those are associated to sound effects play. I have seen the same problem in other sourceports with not threaded audio, like DoomRetro. The problem comes from calling the SDL2 function `SDL_BuildAudioCVT()` every time a sound effect like a monster howling is played: that function is slow and blocking on ARM.
I see you call it here:
https://github.com/fabiangreffrath/crispy-doom/blob/51853181e2efcc13edbcd92de33b680b1c35bc3f/src/i_sdlsound.c#L633

Luckily, there is a generic samplerate conversion code in the same function, starting here:
https://github.com/fabiangreffrath/crispy-doom/blob/51853181e2efcc13edbcd92de33b680b1c35bc3f/src/i_sdlsound.c#L647
SO I went and commented out the SDL converting code, used the generic expansion instead, and I get rock-solid 60FPS always, no more slowdowns on sound effects play.

This raises some questions:

1 - The `SDL_BuildAudioCVT()` can not be moved to the SDL sound init functions instead of being called every time a sound effect is played, right?
I presume it can not be done because of different length for each sample. But maybe I am wrong here.

2- If I am not mistaken, passing -DHAVE_LIBSAMPLERATE should build a version not using SDL2 sound conversion code, but libsamplerate instead, right?

3- Maybe an option could be added to avoid SDL2 rate conversion and use generic expansion on low-end ARM devices altogether?

**Comment by fabiangreffrath** [comment]
I am not sure why sounds aren't pre-cached with the SDL samplerate conversion function if libsamplerate is not available. You'll probably have to suggest this at the Choco bug tracker, because that's where this code originally comes from.

However, if you build with libsamplerate support, all your sounds will get pre-cached using a high quality algorithm. This might take a bit longer at start-up, but the results in-game should be worth it. So, all I can tell you now is to rebuild your code with libsamplerate support and probably file an issue at the Choco tracker requesting sounds to be pre-cached even if libsamplerate is not available. Thanks!

**Comment by vanfanel** [comment]
Well, libsamplerate is an option, so it works well enough. I will suggest pre-caching of the converted on the chocolate doom base repository, however.
Also, the generic expansion code seems a bit faster than libsamplerate... Thats puzzling, but true :D

**Comment by fabiangreffrath** [comment]
So, it seems you found solutions for your reported issues. Can we close this now?

**Comment by vanfanel** [comment]
@fabiangreffrath Yes, we can close it :)
Thanks for your answers and help!
