### ISSUE TITLE
[Question] SDL_Mixer Timidity dependency 

### ISSUE THREAD

**Issue by vanfanel** [fabiangreffrath/crispy-doom#509]
Another question that comes to my head:

How does Crispy play MIDI (GUS, native) and OGG/FLAC/MP3? Does it depend SDL_Mixer being built with Timidity support for MIDI/GUS emulation?

**Comment by fabiangreffrath** [comment]
It dumps the music lump to disk and tells SDL_Mixer to "play this". If the lump is e.g. in MP3 format and SDL_Mixer has been build with MP3 support, then it will be played, else it won't. Same with MIDI, SDL_Mixer will recognize the lump as a MIDI file and play it back with whatever MIDI backend it has been configured.

For GUS emulation, though, I think you need SDL_Mixer's built in Timidity support, but I guess that this gets compiled in anyway. However, I am not an expert in this code path, as I never use it myself.
