### ISSUE TITLE
Disable Monster Interpolation?

### ISSUE THREAD

**Issue by PolarDawn** [fabiangreffrath/crispy-doom#513]
Can we get a setting to disable monster interpolation? I like the benefits of an unlocked framerate, but monster sliding around is unappealing.

**Comment by fabiangreffrath** [comment]
Sorry, but what's the "benefits of an unlocked framerate" if things are still updated at a rate of 35 FPS?

**Comment by Zodomaniac** [comment]
>what's the "benefits of an unlocked framerate" if things are still updated at a rate of 35 FPS?

I guess walls/floors still updating properly while the player moves.

**Comment by turol** [comment]
The player viewpoint (especially if using mouselook) could update at high FPS but monsters would still move at 35.

**Comment by fabiangreffrath** [comment]
Still don't see a compelling reason to implement this, sorry.

**Comment by PolarDawn** [comment]
The benefits to an unlocked frame rate mean smoother gameplay and more responsive inputs. But interpolating the movement of monsters makes them appear to be sliding around. Having the two seperate retains the feeling of classic gameplay, but more correct/accurate enemy animations, assuming the simulation rate of the game remains at 35hz.
It's a feature of other sourceports that I miss.

**Comment by fabiangreffrath** [comment]
I won't add this myself, but if you want to build a variant of your own with mobj interpolation disabled, set this line to `false` inetad of `true`:

https://github.com/fabiangreffrath/crispy-doom/blob/5ddf908faa12255e26546c60c4f4edca48c1ede5/src/doom/p_mobj.c#L548

**Comment by Zodomaniac** [comment]
@PolarDawn I'm going to implement disabling monster interpolation in So Doom, my fork of Crispy Doom github.com/zodomaniac/so-doom
@fabiangreffrath thanks for the hint how to do it!

**Comment by Zodomaniac** [comment]
@PolarDawn and @fabiangreffrath ,could you please build So Doom, turn the Thing Interpolation option on and off and see if it works? I cannot detect any difference even with Uncapped framerate disabled.

**Comment by Zodomaniac** [comment]
https://github.com/Zodomaniac/So-Doom/commit/2ef6c2b7d2bc340afc47c80fb5e3b33d3501f553
Here's the commit implementing this option.
