### ISSUE TITLE
AppImage releases

### ISSUE THREAD

**Issue by chungy** [fabiangreffrath/crispy-doom#515]
[AppImage](https://appimage.org/) is a standard for creating single-file executable Linux applications; they're typically either ISO-9660 or SquashFS images containing all of an application's files and dependent libraries (eg, SDL2 et al). They make it very convenient for just downloading and running an application, especially something like Crispy Doom that isn't widely available in distributions.

The docs are a bit long, but the gist of it isn't too bad to do. I created an AppImage in response to a [Doomworld thread](https://www.doomworld.com/forum/topic/111586-how-to-get-crispy-doom-to-work-on-linux/) about running it. The process was basically:
1. Install Debian 9 (the AppImage people highly recommend a old distro, basically so the binaries you include don't require too new of a kernel/libc). Make sure all the dependencies are on it
2. Download crispy-doom-5.6.4
3. `./configure --prefix=/usr && make && make DESTDIR=$(pwd)/AppDir install`
4. `linuxdeploy --appdir=AppDir --desktop-file=AppDir/usr/share/applications/io.github.fabiangreffrath.Doom.desktop`
5. `appimagetool AppDir Crispy_Doom-5.6.4-x86_64.AppImage`

The last two tools are available themselves as AppImages, the process is fairly straightforward and should be perfectly scriptable. There do exist solutions to automatically build them from Travis and/or [OBS](https://build.opensuse.org/)

**Comment by fabiangreffrath** [comment]
Alright, what's my role in this play?

I am not going to publish Linux AppImage releases myself. I wouldn't even publish Windows binaries if the Choco auto-builder wasn't available to do this "for free". :wink:

**Comment by chungy** [comment]
Feel free to turn down the request :)

I figured it'd be a great service, though i was reminded by that thread that Crispy isn't quite independent of the setup tool like I thought it was (key bindings can't be done in-game, for example).

**Comment by fabiangreffrath** [comment]
Okay, thanks for the suggestion anyway.
