### ISSUE TITLE
Test Crispy with Unity IWADs

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#516]
### Internal demos

Fine in all four Unity IWADs, no desyncs.

|              | Demo1 | Demo2 | Demo3 | Demo4 |
| - |  - | - |  - | - |
| Doom.wad     |  OK   |  OK   |  OK   |  OK   |
| Doom2.wad    |  OK   |  OK   |  OK   |  -    |
| TNT.wad      |  OK   |  OK   |  OK   |  -    |
| Plutonia.wad |  OK   |  OK   |  OK   |  -    |

### External demos

There are desyncs, obiviously because of some changes in levels. Done some test with UvMAX runs from [doomedsda.us](http://doomedsda.us) archive (DooM v1.9 engine).

| IWAD | Demo | Result |
| - | - | - |
| Doom.wad / EP1 | [ep1-1818.zip](http://doomedsda.us/lmps/947/1/ep1-1818.zip) | Desync on E1M4. I see that level architecture and things are absolutely same to original Doom, ex-swastica was not changed, but nodes are recreaded. Why? No idea.
| Doom.wad / EP2 | [ep2-2911.zip](http://doomedsda.us/lmps/947/1/ep2-2911.zip) | OK |
| Doom.wad / EP3 | [ep3-2349.zip](http://doomedsda.us/lmps/947/1/ep3-2349.zip) | OK |
| Doom.wad / EP4 | [ep4-2058.zip](http://doomedsda.us/lmps/947/1/ep4-2058.zip) | Desync on E4M1. Because of removed NIИ logo and thus, recreated nodes. |
| Doom2.wad      | [30uvmax4.zip](http://doomedsda.us/lmps/945/1/30uvmax4.zip) | Desync on Map06 (The Crusher). Because of removed action №117 from linedefs №24 and 25. |
| TNT.wad        | [evall-3701.zip](http://doomedsda.us/lmps/944/2/evall-3701.zip) | OK
| Plutonia.wad   | [plalln4357.zip](http://doomedsda.us/lmps/946/3/plalln4357.zip) | OK

_Note: no desync were catched with original IWADs!_

### No Rest for the Living

Fine as: `crispy-doom.exe -file NERVE.WAD`, wrong titles in episode selection ([screenshot](https://user-images.githubusercontent.com/21193394/73374720-ba52bc00-42cb-11ea-8433-4f7a2ca3c775.png)). Not really wrong, because unlike BFG-Edition, `M_EPI1/2` are using Doom I graphics.

### Wolfenstein levels (Doom II)

Fine, defined as IDKFA/KEEN, sectet exits are working. SS Guards are on place (now have a odd "see sound"), swastika replaced with triangles on wall textures.

### Afterwords

Technically, Unity's Doom2.wad is identified as BFG edition (`DMENUPIC` is present), but in fact it's a modified vanilla Doom2.wad. Fortunaly, these IWADs can't be simply copied from Unity edition, they are packed into some kind of data archives and can be extracted by hex-editor (exception: TNT and Plutonia, which are simply names as extension-less files "1" and "2"). 

IWADs are fine for casual playing, but for demos and network playing everyone should use original ones of course. Good thing, original Doom 1/2 is provided freely after purchasing a Unity edition.

**Comment by fabiangreffrath** [comment]
Nice idea, though I don't expect any serious issues with these IWADs.

**Comment by JNechaevsky** [comment]
Updated first comment with a results.

**Comment by fabiangreffrath** [comment]
Thank you for these extensive tests!

Results don't look that bad, nor not? I mean, we even have similar desyncs when using the BFG Edition IWADs. The desyncs in MAP06 are likely because a "dead" switch has been removed from the map which would cause the (Vanilla) engine to crash if activated. Only question left is why the engine believes that TNT.wad and Plutonia.wad are regular Doom 2 IWADs...

**Comment by JNechaevsky** [comment]
I think for casual playing they are more than good. Again, there is no way to get these IWADs so simple, neither from PC version, nor from Android. 

> likely because a "dead" switch has been removed from the map

Oh yes, a red key door. I'll check in Doom Builder today. So, instead of fixing this issue in the code, they decided to go faster way. Not good, not good.

> believes that TNT.wad and Plutonia.wad are regular Doom 2 IWADs...

All I can say at the moment - Unity IWADs of TNT and Plutonia are smaller (!) in size than original ones. No idea why, I have'n compared them yet. But something seems to be missing, even after using a `-iwad` cmd line parameter. I need also to check file headers, is there `PWAD` or `IWAD`.

**Comment by drfrag666** [comment]
Those are supported in both GZDoom and LZDoom. A guy wrote an extracting tool.
https://forum.zdoom.org/viewtopic.php?f=44&t=66922&sid=3fe972a8c665eeafa622484647491dfe

**Comment by JNechaevsky** [comment]
@fabiangreffrath both TNT and Plutonia have IWAD headers, but do we have an IWAD/PWAD checking and is it really necessary?

![image](https://user-images.githubusercontent.com/21193394/73445479-d27a1800-436b-11ea-9d8a-6366e7319801.png)

I need to dig in deeper to see why it's smaller and why they are identified as HoE.

**Comment by JNechaevsky** [comment]
@drfrag666 thanks! Haven't checked this yet, faster was to extract them by hex-editor. AFAIK, GZDoom also can read these IWADs right from Unity archives, but maybe I'm wrong.

**Comment by fabiangreffrath** [comment]
IIRC, Choco et al. do not check for IWAD content but select gamemission by file name. Could you convert the file names to lower case and try again, please?

**Comment by fabiangreffrath** [comment]
https://github.com/chocolate-doom/chocolate-doom/blob/master/src/d_iwad.c#L538

**Comment by drfrag666** [comment]
No, they must be extracted first.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, dang, my bad. Upper/lower case does not matter, detecting was wrong because of I was using a name `PlutoniaNew.wad`. Better I recheck both Plutonia and TNT now.

**Comment by JNechaevsky** [comment]
Rechecked both IWADs with same demos and correct names: everything is perfect! Also, yeah, they have corrected MAP06 "dead switch" ([screenshot](https://user-images.githubusercontent.com/21193394/73470651-441c8b00-4399-11ea-902a-8dcfe136c8d1.png)). Updated my first post with proper results.

Still wondering about E1M4, have to look closer.

**Comment by JNechaevsky** [comment]
There is NO difference between vanilla and unity E1M4. Amount of vertices, linedefs, sidedefs, sectors and things are same. Even their index numbers are same. Even amount of total warnings are same with all checked cases.

What now? Let's take a look at `VERTEXES` lump of both vanilla and unity E1M4. Here's a starting point, where the difference comes, vertex №673: [screenshot](https://user-images.githubusercontent.com/21193394/73473461-e0e12780-439d-11ea-909c-da8e013dde1a.png). Acording to the info of Doom Builder, there are only 673 Vertices in total, so 672 must be a last one ([screenshot](https://user-images.githubusercontent.com/21193394/73473871-85fc0000-439e-11ea-9ce1-02bec3b19e71.png)), and here it is, on ex-swastika shape ([screenshot](https://user-images.githubusercontent.com/21193394/73474111-f4d95900-439e-11ea-9e55-c65f81128774.png)).

So what's all about unused vertices? I don't know. But in fact, there are different total numbers in `VERTEXES` lumps:

* Vanilla: 779
* Unity: 768

My only theory: this map was resaved with non-vanilla nodebuilder. Probably, by accident - Bethesda was thinking something about ex-swastika shape, but then canceled changes but still, pressed "Save" button. More interesting, all E1M4 lump are same in vanilla and BFG-Edition.

**Comment by fabiangreffrath** [comment]
So, is there anything left to check here?

**Comment by JNechaevsky** [comment]
Ah, sorry, no, we're done here. Speaking without emotions: these IWADs are fine for casual playing, but never should be used for network playing and _any_ kind of speedruns.

Closing for good.
