### ISSUE TITLE
16:9 and 16:10 widescreen rendering options

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#522]
Imagine that some player plays with Widescreen rendering with pixel aspect ratio 1.2 on a 16:10 monitor (e.g. 1680x1050, 1728x1080, 1920x1200). Won't the leftmost and rightmost HUD widgets protrude beyond the screen borders? I thought `crispy_widescreen` could be more than just a flag, as there are at least two common monitor aspect ratios.

**Comment by fabiangreffrath** [comment]
It adjusts itself to the actual screen dimensions and merely falls back to 16:9 if that fails:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/i_video.c#L1541

did I say widescreen would strictly mean 16:9 anywhere? :wink:

**Comment by fabiangreffrath** [comment]
> Did I say anywhere that "widescreen" would strictly mean 16:9?

Indeed I did, in the Wiki. This is now fixed!

**Comment by Zodomaniac** [comment]
OK, the next question is where 'aspect_ratio_correct==2' case is considered in the code, because in `i_video.c` this case is not considered yet it does its impact somewhere, as for 'aspect_ratio_correct==0' we have stretched pixels and for 'aspect_ratio_correct==2' we have square ones and letterboxed screen.

**Comment by fabiangreffrath** [comment]
`aspect_ratio_correct==2` also returns true whenever `if (aspect_ratio_correct)` is checked. The only real difference to the `aspect_ratio_correct==1` case is the value of `actualheight`.

**Comment by fabiangreffrath** [comment]
This is where I sneaked it in: :laughing: 

https://github.com/chocolate-doom/chocolate-doom/commit/3bf06ab27b707bb4e80d865c7b98fbd58b771b35

**Comment by Zodomaniac** [comment]
Question resolved :)
