### ISSUE TITLE
If widescreen is switched on at the very moment disk icon appears, wall textures become all Tutti-Frutti

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#524]
### Background

Version of Crispy Doom: 5.7

Operating System and version: Win 10

Game: Doom 2

Any loaded WADs and mods (please include full command line): Running from a flash drive

### Bug description

Observed behavior:
Have the widescreen turned off. Launch game, go to Crispness menu and at the moment intro music stops playing (and loading the map for the demo begins), turn widescreen rendering on.
![DOOM0002](https://user-images.githubusercontent.com/15119473/75025540-7313b180-54ac-11ea-8775-6eff987eff43.png)

Expected behavior: Switching the widecreen on at the moment it would corrupt memory should be disallowed.

**Comment by fabiangreffrath** [comment]
:astonished: wow, what a mess!

**Comment by fabiangreffrath** [comment]
I guess we will have to reset `recent_bytes_read = 0` in `V_EnableLoadingDisk()`.

**Comment by Zodomaniac** [comment]
So Doom has a similar issue but looks blacker due to the Sodoomy menu background.
That's where I discovered it in the first place, then checked Crispy and was relieved to find that it wasn't me doing anything wrong
![DOOM0000](https://user-images.githubusercontent.com/15119473/75034697-d60e4400-54be-11ea-8c85-a4194602153c.png)

**Comment by fabiangreffrath** [comment]
I find this hard to trigger on my system. Does this fix the issue for you?

```
--- a/src/v_diskicon.c
+++ b/src/v_diskicon.c
@@ -104,6 +104,9 @@ void V_EnableLoadingDisk(const char *lump_name, int xoffs, int yoffs)
     {
         Z_Free(saved_background);
         saved_background = NULL;
+
+        // [crispy] reset bytes counter when re-initializing
+        recent_bytes_read = 0;
     }

     saved_background = Z_Malloc(LOADING_DISK_W * LOADING_DISK_H
```

**Comment by fabiangreffrath** [comment]
I still fail to reproduce this...

**Comment by JNechaevsky** [comment]
Looks likes, memory corruption happens only on Windows. I've made some tests on both Debian and Windows 10. Everything is fine on Linux, on Win10, however, silent crash happens. My steps are:

* `gdb ./crispy-doom`
* `run`
* After game is just started, went to Options > Crispness menu, on hold `Enter` key on "Widescreen rendering" item.
* Game screen will blink like crazy, and after some time (half of minute) crash will happen.

Sadly, my `gdb` output is a bit laggy on Windows, so lines may be screwed up a bit. Anyway:

```
R_Init: Init DOOM refresh daemon - .......................................
P_Init: Init Playloop state.
S_Init: Setting up sound.
I_SDL_PrecacheSounds: Precaching all sound effects......................[New Thread 7384.0x2118]
[New Thread 7384.0x9e8]
[Thread 7384.0x9e8 exited with code 0]
[New Thread 7384.0xec]
[New Thread 7384.0x63c]
[New Thread 7384.0x10c4]
[New Thread 7384.0x59c]
[New Thread 7384.0xd0c]
[New Thread 7384.0x1d70]
IOperm_InstallDriver: Failed to start service (2).
I_InitSound: SDL audio driver is wasapi
S_ChangeMusic: D_DM2TTL (doom2.wad)
S_ChangeMusic: D_STLKS2 (doom2.wad)
P_SetupLevel: MAP11 (doom2.wad) Hard 0:00:00/0:00:00 Doom (BSP)
Z_Free: freed a pointer without ZONEID


[New Thread 7384.0x2160]

[Thread 7384.0xb8c exited with code 0]
warning: avcore\audiocore\client\audioclient\audioclientcore.cpp(1907)\AUDIOSES.DLL!73380245: (caller: 72763E5F) ReturnHr(1) tid(e04) 80070057 ▒▒▒▒▒▒▒▒ ▒▒▒▒▒ ▒▒▒▒▒▒▒.



D_CheckNetGame: Checking network game status.
startskill 2  deathmatch: 0  startmap: 1  startepisode: 1
player 1 of 1 (1 nodes)
Emulating the behavior of the 'Doom 1.9' executable.
HU_Init: Setting up heads up display.
ST_Init: Init status bar.
[Thread 7384.0xd00 exited with code 0]
[Thread 7384.0xb80 exited with code 4294967295]
[Thread 7384.0x63c exited with code 4294967295]
[Thread 7384.0x2160 exited with code 4294967295]
[Thread 7384.0x1d70 exited with code 4294967295]
[Thread 7384.0x10c4 exited with code 4294967295]
[Thread 7384.0xec exited with code 4294967295]
[Thread 7384.0x2118 exited with code 4294967295]
[Thread 7384.0x2260 exited with code 4294967295]
[Thread 7384.0x4bc exited with code 4294967295]
[Thread 7384.0x1758 exited with code 4294967295]
[Thread 7384.0xd0c exited with code 4294967295]
[Thread 7384.0x59c exited with code 4294967295]
[Inferior 1 (process 7384) exited with code 037777777777]
(gdb)
```

Notable problems are:
```
Z_Free: freed a pointer without ZONEID
```
```
warning: avcore\audiocore\client\audioclient\audioclientcore.cpp(1907)\AUDIOSES.DLL!73380245: (caller: 72763E5F) ReturnHr(1) tid(e04) 80070057 ▒▒▒▒▒▒▒▒ ▒▒▒▒▒ ▒▒▒▒▒▒▒.
```
 (wha-?!)

**Comment by Zodomaniac** [comment]
I also encounter silent crashes on my Win7 when de-activating menu with `Esc` after having switched to widescreen at the moment I described.

**Comment by fabiangreffrath** [comment]
That "ZFree" message is an `I_Error()`. This means that Doom recognized that its zone memory is corrupted, but you have no chance to debug it with the OS's own debugging methods, because the Doom process has corrupted its own memory that it allocated for itself. :sob:

**Comment by fabiangreffrath** [comment]
If `recent_bytes_read = 0;` didn't help, maybe does adding `disk_drawn = true;`?

May I assume both of you have uncapped framerate and vsync enabled?

**Comment by fabiangreffrath** [comment]
OMG, it's `disk_drawn = false;`!!!

**Comment by Zodomaniac** [comment]
`disk_drawn = false;` doesn't help either, so I reverted back to the original code.

I think I have some diagnostic info though:
in Win 7 Professional x64 with `aspect_ratio_correct==1` a silent crash happens, while with `aspect_ratio_correct==0 or 2` the bug is screenshootable and looks like Tutti-Frutti:
![DOOM0009](https://user-images.githubusercontent.com/15119473/75271185-d71bda00-580c-11ea-812c-f9877aa8e86d.png)

**Comment by Zodomaniac** [comment]
>May I assume both of you have uncapped framerate and vsync enabled?

I do.

**Comment by JNechaevsky** [comment]
Un-uh, vertical sync is on, but uncapped framerate is off.

**Comment by fabiangreffrath** [comment]
Are we sure that the loading disk icon is the culprit? Do you get similar crashes when rapidly switching "high resolution rendering" on and off? Does disabling the disk icon in the setup tool prevent the crashes?

**Comment by Zodomaniac** [comment]
I don't think disk icon is to blame. I disabled it and still have the memory zone error in case of `aspect_ratio_correct == 1`.
Here I have a 16:10 monitor and for `aspect_ratio_correct == 2` this bug doesn't happen in any form.

**Comment by fabiangreffrath** [comment]
This bug is frustrating! :angry: 

Does it occur when switching *from* widescreen mode or *to* widescreen mode? Does it also happen when toggling high resolution rendering - when widescreen mode is either enabled or disabled? 

Could you probably repeat with the `-mb 1` parameter, so our memory zone is smaller and we increase the risk to write crap into the OS's memory - which would mke it possible to provide a proper backtrace.

**Comment by Zodomaniac** [comment]
>Does it occur when switching from widescreen mode or to widescreen mode?

_To_ widescreen mode.

>Does it also happen when toggling high resolution rendering - when widescreen mode is either enabled or disabled?

Yes, it does, for both aspect ratio correction values and both narrow and wide screen, then switching _to_ high resolution rendering. The bug is silent crash in all cases.

**Comment by fabiangreffrath** [comment]
Very valuable information, thank you!

**Comment by fabiangreffrath** [comment]
Another question: Does it only crash when the game scene is rendered or does it also crash if e.g. the titlepic is shown?

**Comment by Zodomaniac** [comment]
Only when the game scene is rendered, i.e. in Crispness menu where the game view is hidden by the tiled crisps all over the screen, the crash doesn't happen. It happens when I hit `Esc` to see the played demo.

**Comment by fabiangreffrath** [comment]
I still cannot reproduce this, even if I plaster the code with `Z_CheckHEap()` all over the place:
```
--- a/src/doom/m_crispy.c
+++ b/src/doom/m_crispy.c
@@ -537,25 +537,34 @@ static void M_CrispyToggleWidescreenHook (void)
 {
     crispy->widescreen = !crispy->widescreen;

+    Z_CheckHeap();
     // [crispy] re-initialize screenSize_min
     M_SizeDisplay(-1);
+    Z_CheckHeap();
     // [crispy] re-initialize framebuffers, textures and renderer
     I_ReInitGraphics(REINIT_FRAMEBUFFERS | REINIT_TEXTURES | REINIT_ASPECTRATIO);
+    Z_CheckHeap();
     // [crispy] re-calculate framebuffer coordinates
     R_ExecuteSetViewSize();
+    Z_CheckHeap();
     // [crispy] re-draw bezel
     R_FillBackScreen();
+    Z_CheckHeap();
     // [crispy] re-calculate disk icon coordinates
     EnableLoadingDisk();
+    Z_CheckHeap();
     // [crispy] re-calculate automap coordinates
     AM_ReInit();
+    Z_CheckHeap();

     if (gamestate == GS_LEVEL && gamemap > 0)
     {
        // [crispy] re-arrange status bar widgets
        ST_createWidgets();
+    Z_CheckHeap();
        // [crispy] re-arrange heads-up widgets
        HU_Start();
+    Z_CheckHeap();
     }
 }

```

**Comment by fabiangreffrath** [comment]
Could be the wipe then, if `SCREENWIDTH` changes between the "from" and the "to" screen. :thinking:

**Comment by fabiangreffrath** [comment]
Yep, it's the wipe! The crash occurs if the screen resolution changes between the calls to `wipe_StartScreen()` and `wipe_EndScreen()`, respectively, and `wipe_ScreenWipe()` at least one tic later.

The following patch should prevent the crash:
```
--- a/src/doom/f_wipe.c
+++ b/src/doom/f_wipe.c
@@ -38,6 +38,7 @@ static pixel_t*       wipe_scr_start;
 static pixel_t*        wipe_scr_end;
 static pixel_t*        wipe_scr;
 
+static int allocated_width, allocated_height;
 
 void
 wipe_shittyColMajorXform
@@ -235,6 +236,10 @@ wipe_StartScreen
   int  height )
 {
     wipe_scr_start = Z_Malloc(SCREENWIDTH * SCREENHEIGHT * sizeof(*wipe_scr_start), PU_STATIC, NULL);
+
+    allocated_width = SCREENWIDTH;
+    allocated_height = SCREENHEIGHT;
+
     I_ReadScreen(wipe_scr_start);
     return 0;
 }
@@ -268,6 +273,9 @@ wipe_ScreenWipe
        wipe_initMelt, wipe_doMelt, wipe_exitMelt
     };
 
+    width = MIN(SCREENWIDTH, allocated_width);
+    height = MIN(SCREENHEIGHT, allocated_height);
+
     // initial stuff
     if (!go)
     {
```

**Comment by fabiangreffrath** [comment]
Easier patch that will probably achieve the same:
```
--- a/src/doom/d_main.c
+++ b/src/doom/d_main.c
@@ -526,7 +526,7 @@ void D_RunFrame()
        // [crispy] post-rendering function pointer to apply config changes
        // that affect rendering and that are better applied after the current
        // frame has finished rendering
-       if (crispy->post_rendering_hook)
+       if (crispy->post_rendering_hook && !wipe)
        {
                crispy->post_rendering_hook();
                crispy->post_rendering_hook = NULL;
```

**Comment by Zodomaniac** [comment]
>Easier patch that will probably achieve the same:

Hell Yeah! Looks like it works and fixes the bug for switching both to high-res rendering and to widescreen rendering!

**Comment by JNechaevsky** [comment]
Oh yes, seems to be fine also on my side! Holding an `ENTER` key on "Widescreen rendering" while demo sequence working fine, no crashes. :+1:

**Comment by fabiangreffrath** [comment]
Cool, guys, thanks for checking!
