### ISSUE TITLE
aspect_ratio_correction == 0 still enforces pixel aspect ratio (equal to 1) with Widescreen rendering enabled

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#525]
### Background

Version of Crispy Doom: 5.7

Operating System and version: Win 10

Game: Doom (2)

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior:

`aspect_ratio_correction == 0` still enforces pixel aspect ratio (equal to 1, as if `aspect_ratio_correction` was `2`) with Widescreen rendering enabled.

Expected behavior:

No pixel aspect ratio enforcing, stretched pixels.

**Comment by Zodomaniac** [comment]
What I propose here is to not set the framebuffer width to a widescreen resolution if aspect_ratio_correction is unset.

I will welcome your approach to fixing this, as you don't think my pull request contains the right change to the code.

**Comment by fabiangreffrath** [comment]
Ah, I think I am slowly getting what you are trying to say! Without `aspect_ratio_correction` enabled, the whole *idea* of widescreen rendering doesn't make any sense anymore, because you could literally just resize the game window as wide as you like. Right?

**Comment by Zodomaniac** [comment]
Yeah, that's right!

**Comment by Zodomaniac** [comment]
Right?
```
	if (SDL_GetCurrentDisplayMode(video_display, &mode) == 0)
	{
		// [crispy] sanity check: really widescreen display?
		if (mode.w * ah >= mode.h * SCREENWIDTH)
		{
			w = mode.w;
			h = mode.h;
		}
	}

	// [crispy] widescreen rendering makes no sense without aspect ratio correction
	if (!aspect_ratio_correct)
	{
		crispy->widescreen = 0;
	}

	if (crispy->widescreen)
```
