### ISSUE TITLE
Narrowscreen HUD (maybe even with status bar) in widescreen mode

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#530]
From the forum https://www.doomworld.com/forum/topic/67168-crispy-doom-57-update-feb-21-2020/?do=findComment&comment=2085665

**Comment by JNechaevsky** [comment]
Just FYI, in case of having a gray status bar background, even with appropriate vertical weapon placement may have an annoying thing with enabled weapon bobbing while firing: [screenshot](https://user-images.githubusercontent.com/21193394/75360268-a009ff00-58c6-11ea-8b3b-e5db9cc6b6c2.png).

**Comment by Zodomaniac** [comment]
@JNechaevsky You're right, so what remains to be suggested is 'compact' Crispy HUD with opaque or translucent figures. I'd propose a variable `crispy->compacthud`, to replace `crispy->widescreen` by `!crispy->compacthud` in the code adjusting status bar widget position.
https://static.doomworld.com/monthly_2020_02/crispy.png.006c56a591a92b088669453d3acbae17.png

**Comment by JNechaevsky** [comment]
Proper, but not really suggested approach ([screenshot](https://user-images.githubusercontent.com/21193394/75363799-ae0e4e80-58cb-11ea-8078-b4572a43df2d.png)). :stuck_out_tongue_winking_eye:

**Comment by Zodomaniac** [comment]
What I'm trying to achieve.
![crispy_compacthud](https://user-images.githubusercontent.com/15119473/75420233-a93bb000-5948-11ea-85f5-491300d812b5.png)

**Comment by fabiangreffrath** [comment]
It's clear what you are trying to achieve, thanks!

What needs to be done is: Each status bar widget has a horizontal coordinate. These coordinate are currently applied an offset `DELTAWIDTH` value, which is either `0` in regular rendering mode or some positive number in widescreen mode. You need to replace this with a new variable which is either `0`, even in widescreen mode, for your narrow view or `DELTAWIDTH` for the spread view. Whenever this variable changes, the widgets will have to get re-initialized by calling `ST_createWidgets()`.

Don't change `DELTAWIDTH` directly, though, or else you will end up with a wrongly rendered menu, intermission screen, title screen, everything!

**Comment by Zodomaniac** [comment]
@fabiangreffrath , thanks for the reply, I'm trying to move further and see that there are no functions that call `ST_createWidgets()` on change of variable `st_crispyhud`, for example. How am I supposed to mimick that?

**Comment by fabiangreffrath** [comment]
You need to add a check where the action takes place, e.g. in `R_SetViewSize()`.

**Comment by fabiangreffrath** [comment]
You need to add a check where the action takes place, e.g. in `R_SetViewSize()`.

**Comment by Zodomaniac** [comment]
Should this work for Compact HUD branch?
Should this work?

**r_main.c**
```
boolean		setsizeneeded;
boolean 	st_compacthud;
int		setblocks;
int		setdetail;

// [crispy] lookup table for horizontal screen coordinates
int		flipscreenwidth[MAXWIDTH];
int		*flipviewwidth;

void
R_SetViewSize
( int		blocks,
  int		detail )
{
    extern void ST_createWidgets(void);

    st_compacthud = crispy->widescreen && blocks <= 10; // [crispy] widescreen + narrow variation of Crispy HUD

    setsizeneeded = true;
    setblocks = blocks;
    setdetail = detail;

    if (st_compacthud)
    {
    	ST_createWidgets();
    }
}
```

**st_stuff.c**
```
extern boolean st_compacthud; // [crispy] narrowscreen HUD for widescreen, checked in R_SetViewSize()
```

**Comment by Zodomaniac** [comment]
Regular Crispy HUD with 1.2 pixel aspect ratio on 21.5/9 screen.
I think users of such screens will appreciate the Compact HUD ;)
![DOOM0001](https://user-images.githubusercontent.com/15119473/75789992-99becb80-5d7b-11ea-8894-347922ad97eb.png)

**Comment by JNechaevsky** [comment]
Whoah! :open_mouth: Absolutely, a Compact HUD is really necessary for such dimensions!

**Comment by fabiangreffrath** [comment]
It's understood!

The point is, I am absolutely against making this an intermediate screen size between "no HUD at all" and "wide Crispy HUD". First, because this will mess up the number and meaning of available screen sizes between regular and widescreen mode. Second, because once you add this, people will complain they also want the variant without face and also the translucent variant.

So, my idea is to either add another Crispness menu item (booh!) that reads "Compact Widescreen HUD" or I turn the current one into a multi-item reading "Widescreen Rendering: Off / Compact / Wide" - which is my preferred solution, although the choices are a bit misleading as they refer solely to the HUD and not the rendering itself.

**Comment by Zodomaniac** [comment]
>or I turn the current one into a multi-item reading "Widescreen Rendering: Off / Compact / Wide" - which is my preferred solution, although the choices are a bit misleading as they refer solely to the HUD and not the rendering itself.

I would prefer this solution myself, and I'd name the `Widescreen Rendering` items as `On, wide HUD`, `On, compact HUD`, `Off` - the screen space allows.

**Comment by JNechaevsky** [comment]
@Zodomaniac, wait, no, no need to make a mess with two different essences, it will be confusing for the end user. Widescreen rendering is one thing, status bar is totally different.

Screen sizes seems to be the only place for such possible changes. It may be something like...
* Standard HUD, player face, no transparency.
* Standard HUD, no player face, no transparency.
* Standard HUD, no player face, transparency.
* Wide HUD, player face, no transparency.
* Wide HUD, no player face, no transparency.
* Wide HUD, no player face, transparency.
* No HUD.

**Comment by Zodomaniac** [comment]
@JNechaevsky , if the status bar for widescreen is complemented with stone textures to the left and right, all the same HUDs would be possible for widescreen mode with compact HUD as for non-widescreen mode.

**Comment by fabiangreffrath** [comment]
> Widescreen rendering is one thing, status bar is totally different.

I beg to differ. The choice of wide vs. compact HUD is completely tied to widescreen rendering. In regular rendering this choice doesn't even make any sense. Thus, I think it is reasonable to bind the choice of wide vs. compact HUD to the general enabling of widescreen rendering.

**Comment by JNechaevsky** [comment]
Ah, hmm, looks reasonable from technical POV: this way there will be no need to repeat same HUD sizes in non-wide modes (one sizes for standard HUD, one sizes for ex-wide). But menu items for "Widescreen rendering" absolutely must indicate which HUD size will be set.

**Comment by Zodomaniac** [comment]
>But menu items for "Widescreen rendering" absolutely must indicate which HUD size will be set.

THat's what I suggested: `On (wide HUD)`, `On (compact HUD)`, `Off` :)

**Comment by fabiangreffrath** [comment]
The we all agree, it seems! :grin:

**Comment by JNechaevsky** [comment]
From my side: 
![STNA0023-420x546](https://user-images.githubusercontent.com/21193394/75856881-50678e00-5e06-11ea-8319-00f6f841f2ca.jpg)

**Comment by fabiangreffrath** [comment]
How about text messages, map statistics, player coords and these widgets? Are thex also affected by compat HUD setup or shall they remain at the screen edges? (No, no further config switch!)

**Comment by Zodomaniac** [comment]
I think they should be affected by compact setup as its very goal is to keep the HUD info out of the wide screen's far corners.

**Comment by JNechaevsky** [comment]
Not sure what to suggest, for me it's both "yes" and "no". I'll explain:
* Yes, should be affected - because this is described by feature itself, it's a logic of how wide/non-wide HUD should work.
* No, shouldn't be affected - I'm afraid that because of affection in non-wide mode, player will have extra text strings somewhere in the middle of game scene, especially in automap overlay mode. Yes, such strings are informative, and it's HUD-related stuff, but they must be at "own" places, right in the corners. Remember, it is also an UI question, which always have own, aesthetical and perception logic..

**Comment by fabiangreffrath** [comment]
```
diff --git a/src/crispy.h b/src/crispy.h
index 056360f6..346150e5 100644
--- a/src/crispy.h
+++ b/src/crispy.h
@@ -208,6 +208,14 @@ enum
     NUM_SECRETMESSAGE
 };
 
+enum
+{
+    WIDESCREEN_OFF,
+    WIDESCREEN_WIDE,
+    WIDESCREEN_COMPACT,
+    NUM_WIDESCREEN
+};
+
 enum
 {
     WIDGETS_OFF,
diff --git a/src/doom/hu_stuff.c b/src/doom/hu_stuff.c
index 536b2c80..d0888761 100644
--- a/src/doom/hu_stuff.c
+++ b/src/doom/hu_stuff.c
@@ -60,7 +60,7 @@
 #define HU_TITLEM	(mapnames_commercial[gamemap-1 + 105 + 3])
 #define HU_TITLE_CHEX   (mapnames_chex[(gameepisode-1)*9+gamemap-1])
 #define HU_TITLEHEIGHT	1
-#define HU_TITLEX	(0 - DELTAWIDTH)
+#define HU_TITLEX	(0 - HORIZDELTA)
 #define HU_TITLEY	(167 - SHORT(hu_font[0]->height))
 
 #define HU_INPUTTOGGLE	't'
@@ -69,7 +69,7 @@
 #define HU_INPUTWIDTH	64
 #define HU_INPUTHEIGHT	1
 
-#define HU_COORDX	((ORIGWIDTH - 7 * hu_font['A'-HU_FONTSTART]->width) + DELTAWIDTH)
+#define HU_COORDX	((ORIGWIDTH - 7 * hu_font['A'-HU_FONTSTART]->width) + HORIZDELTA)
 
 
 char *chat_macros[10] =
diff --git a/src/doom/hu_stuff.h b/src/doom/hu_stuff.h
index a724797f..74d66fbb 100644
--- a/src/doom/hu_stuff.h
+++ b/src/doom/hu_stuff.h
@@ -32,7 +32,7 @@
 
 #define HU_BROADCAST	5
 
-#define HU_MSGX		(0 - DELTAWIDTH)
+#define HU_MSGX		(0 - HORIZDELTA)
 #define HU_MSGY		0
 #define HU_MSGWIDTH	64	// in characters
 #define HU_MSGHEIGHT	1	// in lines
diff --git a/src/doom/m_crispy.c b/src/doom/m_crispy.c
index 8d01ab48..9d2d7f9b 100644
--- a/src/doom/m_crispy.c
+++ b/src/doom/m_crispy.c
@@ -128,6 +128,13 @@ multiitem_t multiitem_sndchannels[4] =
     {32, "32"},
 };
 
+multiitem_t multiitem_widescreen[NUM_WIDESCREEN] =
+{
+    {WIDESCREEN_OFF, "off"},
+    {WIDESCREEN_WIDE, "wide"},
+    {WIDESCREEN_COMPACT, "compact"},
+};
+
 multiitem_t multiitem_widgets[NUM_WIDGETS] =
 {
     {WIDGETS_OFF, "never"},
@@ -535,20 +542,24 @@ void M_CrispyToggleWeaponSquat(int choice)
 
 static void M_CrispyToggleWidescreenHook (void)
 {
-    crispy->widescreen = !crispy->widescreen;
+    crispy->widescreen = (crispy->widescreen + 1) % NUM_WIDESCREEN;
 
-    // [crispy] re-initialize screenSize_min
-    M_SizeDisplay(-1);
-    // [crispy] re-initialize framebuffers, textures and renderer
-    I_ReInitGraphics(REINIT_FRAMEBUFFERS | REINIT_TEXTURES | REINIT_ASPECTRATIO);
-    // [crispy] re-calculate framebuffer coordinates
-    R_ExecuteSetViewSize();
-    // [crispy] re-draw bezel
-    R_FillBackScreen();
-    // [crispy] re-calculate disk icon coordinates
-    EnableLoadingDisk();
-    // [crispy] re-calculate automap coordinates
-    AM_ReInit();
+    // [crispy] no need to re-init when switching from wide to compact
+    if (crispy->widescreen == 1 || crispy->widescreen == 0)
+    {
+	// [crispy] re-initialize screenSize_min
+	M_SizeDisplay(-1);
+	// [crispy] re-initialize framebuffers, textures and renderer
+	I_ReInitGraphics(REINIT_FRAMEBUFFERS | REINIT_TEXTURES | REINIT_ASPECTRATIO);
+	// [crispy] re-calculate framebuffer coordinates
+	R_ExecuteSetViewSize();
+	// [crispy] re-draw bezel
+	R_FillBackScreen();
+	// [crispy] re-calculate disk icon coordinates
+	EnableLoadingDisk();
+	// [crispy] re-calculate automap coordinates
+	AM_ReInit();
+    }
 
     if (gamestate == GS_LEVEL && gamemap > 0)
     {
diff --git a/src/doom/m_crispy.h b/src/doom/m_crispy.h
index 1a6a6fd6..d34bb268 100644
--- a/src/doom/m_crispy.h
+++ b/src/doom/m_crispy.h
@@ -40,6 +40,7 @@ extern multiitem_t multiitem_jump[NUM_JUMPS];
 extern multiitem_t multiitem_sndchannels[4];
 extern multiitem_t multiitem_secretmessage[NUM_SECRETMESSAGE];
 extern multiitem_t multiitem_translucency[NUM_TRANSLUCENCY];
+extern multiitem_t multiitem_widescreen[NUM_WIDESCREEN];
 extern multiitem_t multiitem_widgets[NUM_WIDGETS];
 
 extern void M_CrispyToggleAutomapstats(int choice);
diff --git a/src/doom/m_menu.c b/src/doom/m_menu.c
index 9b4a3c0d..9f036a1a 100644
--- a/src/doom/m_menu.c
+++ b/src/doom/m_menu.c
@@ -1501,7 +1501,7 @@ static void M_DrawCrispness1(void)
 
     M_DrawCrispnessSeparator(crispness_sep_rendering, "Rendering");
     M_DrawCrispnessItem(crispness_hires, "High Resolution Rendering", crispy->hires, true);
-    M_DrawCrispnessItem(crispness_widescreen, "Widescreen Rendering", crispy->widescreen, aspect_ratio_correct);
+    M_DrawCrispnessMultiItem(crispness_widescreen, "Widescreen Rendering", multiitem_widescreen, crispy->widescreen, aspect_ratio_correct);
     M_DrawCrispnessItem(crispness_uncapped, "Uncapped Framerate", crispy->uncapped, true);
     M_DrawCrispnessItem(crispness_vsync, "Enable VSync", crispy->vsync, !force_software_renderer);
     M_DrawCrispnessItem(crispness_smoothscaling, "Smooth Pixel Scaling", crispy->smoothscaling, true);
diff --git a/src/doom/st_stuff.c b/src/doom/st_stuff.c
index a230b4f9..37271725 100644
--- a/src/doom/st_stuff.c
+++ b/src/doom/st_stuff.c
@@ -140,73 +140,73 @@ extern boolean inhelpscreens; // [crispy] prevent palette changes
 
 // AMMO number pos.
 #define ST_AMMOWIDTH		3	
-#define ST_AMMOX			(44 - DELTAWIDTH)
+#define ST_AMMOX			(44 - HORIZDELTA)
 #define ST_AMMOY			171
 
 // HEALTH number pos.
 #define ST_HEALTHWIDTH		3	
-#define ST_HEALTHX			(90 - DELTAWIDTH)
+#define ST_HEALTHX			(90 - HORIZDELTA)
 #define ST_HEALTHY			171
 
 // Weapon pos.
-#define ST_ARMSX			(111 - DELTAWIDTH)
+#define ST_ARMSX			(111 - HORIZDELTA)
 #define ST_ARMSY			172
-#define ST_ARMSBGX			(104 - DELTAWIDTH)
+#define ST_ARMSBGX			(104 - HORIZDELTA)
 #define ST_ARMSBGY			168
 #define ST_ARMSXSPACE		12
 #define ST_ARMSYSPACE		10
 
 // Frags pos.
-#define ST_FRAGSX			(138 - DELTAWIDTH)
+#define ST_FRAGSX			(138 - HORIZDELTA)
 #define ST_FRAGSY			171	
 #define ST_FRAGSWIDTH		2
 
 // ARMOR number pos.
 #define ST_ARMORWIDTH		3
-#define ST_ARMORX			(221 + DELTAWIDTH)
+#define ST_ARMORX			(221 + HORIZDELTA)
 #define ST_ARMORY			171
 
 // Key icon positions.
 #define ST_KEY0WIDTH		8
 #define ST_KEY0HEIGHT		5
-#define ST_KEY0X			(239 + DELTAWIDTH)
+#define ST_KEY0X			(239 + HORIZDELTA)
 #define ST_KEY0Y			171
 #define ST_KEY1WIDTH		ST_KEY0WIDTH
-#define ST_KEY1X			(239 + DELTAWIDTH)
+#define ST_KEY1X			(239 + HORIZDELTA)
 #define ST_KEY1Y			181
 #define ST_KEY2WIDTH		ST_KEY0WIDTH
-#define ST_KEY2X			(239 + DELTAWIDTH)
+#define ST_KEY2X			(239 + HORIZDELTA)
 #define ST_KEY2Y			191
 
 // Ammunition counter.
 #define ST_AMMO0WIDTH		3
 #define ST_AMMO0HEIGHT		6
-#define ST_AMMO0X			(288 + DELTAWIDTH)
+#define ST_AMMO0X			(288 + HORIZDELTA)
 #define ST_AMMO0Y			173
 #define ST_AMMO1WIDTH		ST_AMMO0WIDTH
-#define ST_AMMO1X			(288 + DELTAWIDTH)
+#define ST_AMMO1X			(288 + HORIZDELTA)
 #define ST_AMMO1Y			179
 #define ST_AMMO2WIDTH		ST_AMMO0WIDTH
-#define ST_AMMO2X			(288 + DELTAWIDTH)
+#define ST_AMMO2X			(288 + HORIZDELTA)
 #define ST_AMMO2Y			191
 #define ST_AMMO3WIDTH		ST_AMMO0WIDTH
-#define ST_AMMO3X			(288 + DELTAWIDTH)
+#define ST_AMMO3X			(288 + HORIZDELTA)
 #define ST_AMMO3Y			185
 
 // Indicate maximum ammunition.
 // Only needed because backpack exists.
 #define ST_MAXAMMO0WIDTH		3
 #define ST_MAXAMMO0HEIGHT		5
-#define ST_MAXAMMO0X		(314 + DELTAWIDTH)
+#define ST_MAXAMMO0X		(314 + HORIZDELTA)
 #define ST_MAXAMMO0Y		173
 #define ST_MAXAMMO1WIDTH		ST_MAXAMMO0WIDTH
-#define ST_MAXAMMO1X		(314 + DELTAWIDTH)
+#define ST_MAXAMMO1X		(314 + HORIZDELTA)
 #define ST_MAXAMMO1Y		179
 #define ST_MAXAMMO2WIDTH		ST_MAXAMMO0WIDTH
-#define ST_MAXAMMO2X		(314 + DELTAWIDTH)
+#define ST_MAXAMMO2X		(314 + HORIZDELTA)
 #define ST_MAXAMMO2Y		191
 #define ST_MAXAMMO3WIDTH		ST_MAXAMMO0WIDTH
-#define ST_MAXAMMO3X		(314 + DELTAWIDTH)
+#define ST_MAXAMMO3X		(314 + HORIZDELTA)
 #define ST_MAXAMMO3Y		185
 
 // pistol
@@ -1907,7 +1907,7 @@ void ST_drawWidgets(boolean refresh)
     // [crispy] draw the actual face widget background
     if (st_crispyhud && screenblocks == CRISPY_HUD)
     {
-	V_CopyRect(ST_FX + DELTAWIDTH, 1, st_backing_screen, SHORT(faceback->width), ST_HEIGHT - 1, ST_FX + DELTAWIDTH, ST_Y + 1);
+	V_CopyRect(ST_FX + HORIZDELTA, 1, st_backing_screen, SHORT(faceback->width), ST_HEIGHT - 1, ST_FX + HORIZDELTA, ST_Y + 1);
     }
 
     STlib_updateMultIcon(&w_faces, refresh);
diff --git a/src/i_video.h b/src/i_video.h
index b58cc5af..2141c917 100644
--- a/src/i_video.h
+++ b/src/i_video.h
@@ -36,6 +36,7 @@ extern int SCREENHEIGHT;
 extern int HIRESWIDTH; // [crispy] non-widescreen SCREENWIDTH
 extern int DELTAWIDTH; // [crispy] horizontal widescreen offset
 void I_GetScreenDimensions (void); // [crispy] re-calculate DELTAWIDTH
+#define HORIZDELTA (crispy->widescreen == 1 ? DELTAWIDTH : 0)
 
 // Screen height used when aspect_ratio_correct=true.

```

**Comment by fabiangreffrath** [comment]
Closed by https://github.com/fabiangreffrath/crispy-doom/commit/e08c8a2591f276fec84379da22e6b95aa12d8a43

**Comment by JNechaevsky** [comment]
Gentlemen, I have to admit: having a compact HUD widgets (not status bar!) does not looks right, as I was afraid. It takes a placement which is't looking visually correct, and reminds combat airplane HUD ([photo](https://user-images.githubusercontent.com/21193394/75980735-22607780-5ef4-11ea-8693-7076483497c6.png)), where all widgets are placed right in front of the eyes.

I'm _not a big fan_ of such comparisons, but have a look at GZDoom as an exaple - widgets are alyas sticked near the screen corners, matters no how wide the screen is.

**Comment by Zodomaniac** [comment]
@JNechaevsky I liked your metaphor, playing as a Doomguy you should feel like controlling a combat machine, and compact HUD gives you that feeling! :D

**Comment by JNechaevsky** [comment]
:) Not exactlly, but this is a good one! In UI design there is one important thing - "a logical placement of visual objects". I.e. even if something is looking good, it must be placed and aligned good. 

Just try to remember any games which have top text line starting not from most left side of the screen, but from about 1/3 of screen. This is not correct.

As a notable example, here's a [picture](https://todayslocalmedia.com/wp-content/uploads/2019/02/paradise-bad-website-design.png) of totally wrong elemens placement.
