### ISSUE TITLE
Marking in automap breaks in widescreen mode

### ISSUE THREAD

**Issue by MoerasGrizzly** [fabiangreffrath/crispy-doom#531]
### Background

Version of Crispy Doom: 5.7

Operating System and version: Win10 1909

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line): any/all

### Bug description
https://www.youtube.com/watch?v=0l95qJ_QL0s&feature=youtu.be

The automap markers move around in widescreen dependant on zoom. They stay in a fixed place in normal rendering.

**Comment by fabiangreffrath** [comment]
This is a bug in the released version that has been fixed in commit https://github.com/fabiangreffrath/crispy-doom/commit/4a64201d47a71dcce85884eef0ffca6b33c46bde .
