### ISSUE TITLE
Allow toggleable menu items to be changed by arrow keys

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#532]
This will add some extra comfort to menu handling. The logic is:

* `Enter` key scrolls forward.
* `<` left arrow scrolls backward.
* `>` right arrow scrolls forward.
* All of them are still changes "on/off" features normally.

Technically, there is no much extra work to do. Toggleable should be changed to "slider" types, for accepting arrow keys,everything else is already in the code.

There is one thing I need to discuss before making a PR.

Features which have only two options (on/off or `1`/`0`) are still can be changed normally. Example:

```
static menuitem_t Crispness1Menu[]=
{
---    {1,"",	M_CrispyToggleCrosshairHealth,'c'},
+++    {2,"",	M_CrispyToggleCrosshairHealth,'c'},
```

However, multiple items toggling must be changed to `switch` type and have some extra conditions, otherwise variable will go out of bounds.
```
static menuitem_t Crispness1Menu[]=
{
---    {1,"",	M_CrispyToggleColoredhud,'c'},
+++    {2,"",	M_CrispyToggleColoredhud,'c'},
```
```
void M_CrispyToggleColoredhud(int choice)
{
    switch(choice)
    {
        case 0:
        crispy->coloredhud--;
        break;

        case 1:
        crispy->coloredhud++;
    }

    if (crispy->coloredhud > 2)
        crispy->coloredhud = 0;
    if (crispy->coloredhud < 0)
        crispy->coloredhud = 2;
}
```

So, speaking about extra `if` conditions, how do you think, can it be simplified? Is there any more proper approach?

**Comment by Zodomaniac** [comment]
>So, speaking about extra if conditions, how do you think, can it be simplified? Is there any more proper approach?

Yes, the remainder operation is used to cycle the variable:

void M_CrispyToggleColoredhud(int choice)
{
    switch(choice)
    {
        case 0:
        crispy->coloredhud = (crispy->coloredhud - 1) % NUM_COLOREDHUD;
        break;

        case 1:
        crispy->coloredhud = (crispy->coloredhud + 1) % NUM_COLOREDHUD;
    }
}

**Comment by JNechaevsky** [comment]
Duh, even simpler. Thanks!

**Comment by Zodomaniac** [comment]
BTW, why change this line?
```
static menuitem_t Crispness1Menu[]=
{
---    {1,"",	M_CrispyToggleColoredhud,'c'},
+++    {2,"",	M_CrispyToggleColoredhud,'c'},
```

**Comment by JNechaevsky** [comment]
1 = item can be toggled only by `Enter` key,
2 = item can be toggled by `Enter` key arrows. 

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/m_menu.c#L152

**Comment by Zodomaniac** [comment]
Thanks for clarifying!

**Comment by fabiangreffrath** [comment]
No `switch (choice)`, just

```
crispy->coloredhud = (crispy->coloredhud + (2 * choice - 1)) % NUM_COLOREDHUD;
```

**Comment by JNechaevsky** [comment]
Awesome, thanks! This will make the rest of the job as easy as possible. Meanwhile, couple of extra thoughts:

1. By using this approach, items will be switched by "move" sound, not by "pistol". Nothing wrong of course, if we are not seeking for some, err... Extra vanilla sound behavior. Common selection items, will still have a "pistol" sound.
2. Not really a bug, but mouse event handling... While I was experimenting with this in RD, I've discovered a small annoying thing: when the game is running in windowed mode and menu's cursor is placed on a toggalable item, even a small horizontal mouse movement over the game window will change toggalable item value. Not sure what to do.

**Comment by fabiangreffrath** [comment]
> 1. By using this approach, items will be switched by "move" sound, not by "pistol". 

That's okay!

> 2. Not sure what to do.

https://github.com/fabiangreffrath/woof/commit/43f666a088d9dfc71b538b4fb65d64c5084836d5

**Comment by JNechaevsky** [comment]
:heart_eyes: That is all we need, thanks again, green light is on! The only thing I can' promise - time of PR. Non-free life takes it's...time. :relieved:

**Comment by fabiangreffrath** [comment]
We are not in a hurry, and this is probably not top-notch priority. :wink:

**Comment by JNechaevsky** [comment]
Note: `choice = 0;` must be removed, i.e. function must be this:
```
void M_CrispyToggleColoredhud(int choice)
{
    crispy->coloredhud = (crispy->coloredhud + (4 * choice - 1)) % NUM_COLOREDHUD;
}
```

Otherwise, `(NULL)` will appear:
![image](https://user-images.githubusercontent.com/21193394/75903760-18d30300-5e53-11ea-90ad-4fa4129b680f.png)

**Comment by JNechaevsky** [comment]
@fabiangreffrath, I need your help. This approach have two problems:
```
crispy->coloredhud = (crispy->coloredhud + (4 * choice - 1)) % NUM_COLOREDHUD;
```

It is working fine only while scrolling forward (`>` arrow). In case of scrolling backward (`<` arrow), incorrect values start to appear. I'm ready to make a PR where we can review everything.

**Comment by fabiangreffrath** [comment]
It's always `2 * choice` , never `4` .

**Comment by JNechaevsky** [comment]
Un-uh, same problem with: 
```
{
crispy->coloredhud = (crispy->coloredhud + (2 * choice - 1)) % NUM_COLOREDHUD;
}
```

If I'm scrolling backward, `(null)` / `static` / `projected` values are appearing, matters no is there ` choice = 0` or not.

**Comment by Zodomaniac** [comment]
@JNechaevsky try 
```
{
crispy->coloredhud = (crispy->coloredhud + (2 * choice + 1)) % NUM_COLOREDHUD;
}
```

**Comment by JNechaevsky** [comment]
@Zodomaniac it's working, except it have reverse scrolling logics. While I'm scrolling `>`, it cycles through: off, both, hud texts, status bar. But while I'm scrolling `<`, it cycles through: off, status bar, hud texts, both.

**Comment by Zodomaniac** [comment]
@JNechaevsky then all that remains is to try
```
{
crispy->coloredhud = (crispy->coloredhud - (2 * choice + 1)) % NUM_COLOREDHUD;
}
```

**Comment by fabiangreffrath** [comment]
Sorry guys, my fault. Stop it, won't work. Had a brain twist.

**Comment by JNechaevsky** [comment]
Full stop, no luck on my side either. Meanwhile a funny little offtopic... Gentlemen, any ideas how to apply brightmap to this? ([photo](https://user-images.githubusercontent.com/21193394/75913762-905d5e00-5e64-11ea-859f-9916103cad9e.png)).

**Comment by fabiangreffrath** [comment]
My idea was: If you push the left arrow button, the function is called with `choice = 0` and if you push the right arrow button it gets called with `choice = 1`. Now, `2*0 - 1 = -1` and `2*1 - 1 = 1`, so there would be our decrement and increment for the `crispy->coloredhud` value.

This works fine until you pass through `0` into negative direction. Then you'll end up with `-1` value and this doesn't properly clamp into the valid range of values even if mangled with `% NUM_COLOREDHUD`. 

Sorry for the confusion!

**Comment by JNechaevsky** [comment]
Simplified my current approach a bit by moving `if` conditions inside `switch` states. This is working as it should, are we okay to proceed with this?
```
void M_CrispyToggleColoredhud(int choice)
{
    switch(choice)
    {
        case 0:
        crispy->coloredhud--;
        if (crispy->coloredhud < 0)
            crispy->coloredhud = NUM_COLOREDHUD-1;
        break;

        case 1:
        crispy->coloredhud++;
        if (crispy->coloredhud > NUM_COLOREDHUD-1)
            crispy->coloredhud = 0;
        break;
    }
}
```

**Comment by fabiangreffrath** [comment]
Yes, this is neat.

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.

**Comment by JNechaevsky** [comment]
Deleted `menu-arrow-keys` branch as no longer needed, it is implemented already.
