### ISSUE TITLE
When loading the map from command line, the HUD is messed up in case of widescreen rendering enabled

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#533]
### Background

Version of Crispy Doom: 5.7.1

Operating System and version: Win 10 Prof

Game: Doom (2)

Any loaded WADs and mods (please include full command line): `crispy-doom -skill 4`

### Bug description

Observed behavior:  1920x1200 (16:10) screen, `aspect_ratio_correct == 2`, `crispy->widescreen ==1`
![DOOM0031](https://user-images.githubusercontent.com/15119473/75869105-29b35280-5e1a-11ea-8cf9-551ad85dacb1.png)

1920x1200 (16:10) screen, `aspect_ratio_correct == 1`, `crispy->widescreen ==1`
![DOOM0034](https://user-images.githubusercontent.com/15119473/75872334-017a2280-5e1f-11ea-885c-8ff762acd612.png)

When launching game in a regular manner or playing back demos this doesn't happen.

**Comment by fabiangreffrath** [comment]
Hm, doesn't happen for me...

**Comment by Zodomaniac** [comment]
Try my config [crispy-doom-cfg.zip](https://github.com/fabiangreffrath/crispy-doom/files/4286991/crispy-doom-cfg.zip)

**Comment by fabiangreffrath** [comment]
Do you already have one of the patches (aspect_ratio_correct vs. widescreen) applied that we talked about earlier?

**Comment by Zodomaniac** [comment]
No, neither.

**Comment by fabiangreffrath** [comment]
Your config works okay for me (I had to change fullscreen to 0 and window_position to "0,1400" for specific reasons...)

**Comment by fabiangreffrath** [comment]
Hm, really puzzling. It seems to mis-calculate `DELTAWIDTH` in the case you describe, but only by a few pixels. Do you start the game on one screen and play it on a different screen then?

**Comment by Zodomaniac** [comment]
I have 2 monitors here, but the game window (the issue occurs in windowed mode as well) is on the same monitor as the one I launch the game from.
Looks like `DELTAWIDTH` corresponding to 16:9 is enforced, which is strange.

**Comment by Zodomaniac** [comment]
Turned off the second screen in video settings, the issue persists.

**Comment by Zodomaniac** [comment]
Regarding this issue: I only have it at work where the window seems to be forcefully sized 16:10 by the OS, at home it is sized 16:9. Seems like when running SDL programs in the windowed mode, the OS enforces the aspect ratio of the monitor even on non-fullscreen windows.

**Comment by fabiangreffrath** [comment]
This only affects the status bar widgets, but not the level statistics, level time and player coordinates - right?

**Comment by fabiangreffrath** [comment]
Does this fix it?
```
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -1547,6 +1547,12 @@ void I_GetScreenDimensions (void)
                        h = mode.h;
                }
        }
+       else
+       if (!crispy->post_rendering_hook)
+       {
+               extern void ST_createWidgets(void);
+               crispy->post_rendering_hook = ST_createWidgets;
+       }
 
        // [crispy] widescreen rendering makes no sense without aspect ratio correction
        if (!aspect_ratio_correct)
```

**Comment by Zodomaniac** [comment]
I will try your approach, but now I've tested on 16:10 monitor and it appears to get fixed much easier, by assuming widescreen aspect ratios begin with 16:10, not 16:9:

```
// [crispy] re-calculate SCREENWIDTH, SCREENHEIGHT, HIRESWIDTH and DELTAWIDTH
void I_GetScreenDimensions (void)
{
	SDL_DisplayMode mode;
	int w = 16, h = 9;
	int ah;

	SCREENWIDTH = ORIGWIDTH << crispy->hires;
	SCREENHEIGHT = ORIGHEIGHT << crispy->hires;

	HIRESWIDTH = SCREENWIDTH;

	ah = (aspect_ratio_correct == 1) ? (6 * SCREENHEIGHT / 5) : SCREENHEIGHT;

	if (SDL_GetCurrentDisplayMode(video_display, &mode) == 0)
	{
		// [crispy] sanity check: really widescreen display?
		if (mode.w * ah >= mode.h * SCREENWIDTH)
		{
			w = mode.w;
			h = mode.h;
		}
	}
```

So I'll submit another pull request for this, after you merge my previous one (I made the requested changes).

**Comment by fabiangreffrath** [comment]
> I will try your approach, but now I've tested on 16:10 monitor and it appears to get fixed much easier, by assuming widescreen aspect ratios begin with 16:10, not 16:9:

Erm, no. This will just mitigate the symptoms for your 16:10 screen but the problem still persists for any other screen.

The point is: If you start the game directly into a map, e.g. by running with `-warp` or `-skill` or `-record` or `-playdemo` or whatever, then the status bar widgets will get initialized before the video mode has been set up. Thus, the call to `SDL_GetCurrentDisplayMode()` fails and we proceed with the standard 16:9 settings. The status bar widgets will then be initialized with these values. What we need to do is re-init the status bar widgets ASAP if we find our video mode is not yet set up.

**Comment by fabiangreffrath** [comment]
> by assuming widescreen aspect ratios begin with 16:10, not 16:9:

You are misreading the code here. I do not assume anything.

The code just checks if the ratio of the screen's width to height (e.g. 1900:1080) is larger than Doom's own ratio (e.g. 640:480) and only then applies widescreen settings. This is to avoid that the renderer adapts its dimensions to e.g. a vertical display - it will use the default 16:9 ratio in that case.

**Comment by Zodomaniac** [comment]
OK, I still think that the default ratio should be 16:10, as it's Doom framebuffer's native aspect ratio.

**Comment by fabiangreffrath** [comment]
That doesn't matter. We are stretching to *screen* and I think the most common ratio (to use as a fallback) is still 16:9.

**Comment by fabiangreffrath** [comment]
So, does my patch work for you?

**Comment by Zodomaniac** [comment]
I can build executables at home only, so when I come home from work, I will test.
Luckily you provided me enough info to close other insignificant issues that don't require building EXEs for testing :)

**Comment by fabiangreffrath** [comment]
Hehe... :+1:

**Comment by Zodomaniac** [comment]
This bug only pops up at work on 1920x1200 monitor, so I will build EXEs in the evening and test tomorrow. :Ь

**Comment by Zodomaniac** [comment]
@JNechaevsky kindly built the EXE with your patch for me, and the issue has been resolved! For a fraction of a second I see the messed-up HUD, but it gets in place as the wipe finishes.
And to fix the issue even for the wipe time, maybe replace that 9 by 10?

**Comment by Zodomaniac** [comment]
@fabiangreffrath , this patch of yours hasn't been committed to Master yet
```
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -1547,6 +1547,12 @@ void I_GetScreenDimensions (void)
                        h = mode.h;
                }
        }
+       else
+       if (!crispy->post_rendering_hook)
+       {
+               extern void ST_createWidgets(void);
+               crispy->post_rendering_hook = ST_createWidgets;
+       }
 
        // [crispy] widescreen rendering makes no sense without aspect ratio correction
        if (!aspect_ratio_correct)
```
