### ISSUE TITLE
Calls to `sfx_oof` in m_crispy.c

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#535]
I get the point of producing a 'futility sound' - the 'oof' when trying to toggle inactive items of Crispness menu, but the pistol fire sound is also played in those cases, so 2 sounds are played, 'oof' being barely heard because of the pistol sound.
I suggest commenting all the 'oof' sound calls in `m_crispy.c`.

**Comment by fabiangreffrath** [comment]
Yep, pull request please! :wink:

**Comment by fabiangreffrath** [comment]
And, please, do not comment them, remove them. No prisoners!
