### ISSUE TITLE
960x600 instead of 640x400

### ISSUE THREAD

**Issue by samuelpaschal** [fabiangreffrath/crispy-doom#545]
Could you implement this? If you don't want to bother changing the resolution, could you give me a few hints in the source code on where I change the resolution?

**Comment by fabiangreffrath** [comment]
> Could you implement this? 

Nope, won't happen.

> If you don't want to bother changing the resolution, could you give me a few hints in the source code on where I change the resolution?

Look for `SCREENHEIGHT` and `SCREENWIDTH` and especially `crispy->hires`. Good luck!

**Comment by samuelpaschal** [comment]
Does crispy->hires changes values between 0 and 1 only?

**Comment by fabiangreffrath** [comment]
> Does crispy->hires changes values between 0 and 1 only? 

Yes, it is used a lot in bit-shifting, and any other value than 0 or 1 would mess this up currently.

> Is M_CrispyToggleHiresHook() the only place where its value is defined?

It is the only place where its value is changed at run-time, yes.

Honestly, if you are looking for a cleaner starting point, it is probably better to modify Chocolate Doom to render in your preferred resolution. The code for MBF/WinMBF/Woof! may come in handy if you are looking for the code that is affected by resolution changing.

**Comment by samuelpaschal** [comment]
Thanks, I will keep poking at it. Left shift operators turned into multiplication, right shift operators turned into division, either by 1 or 3, as defined in M_CrispyToggleHiresHook(). It crashes whenever crispy->hires == 3 (or so it seems).
https://github.com/samuelpaschal/bfgcrisp/commit/87bf35ea6730eff0f8132811bf8bfce86d18fa14#diff-9a8dbc8acf45b7a566b66fd07cc37d17

If you remember anything else I should look into, please tell.

**Comment by fabiangreffrath** [comment]
I remember the frame buffer for the loading disc icon was a bitch back then.
