### ISSUE TITLE
Mouse Sensitivity sliders going out of bounds: intentional or not?

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#546]
### Background

Version of Crispy Doom: 5.7.2 pre-release

Operating System and version: Win 7/10

Game: Doom (2)

### Bug description

Observed behavior: for each of the 3 sensitivity sliders the right limit is at 20, but the sensitivity can go beyond the slider and amount to hundreds.

Expected behavior: if enabling such high sensitivity is intentional (for speedrunners with low-sensitivity mice etc.), please adjust the slider limit.

**Comment by fabiangreffrath** [comment]
This is intentional. The thermometer stops at Vanilla's max value and then turns gray to show that it has become meaningless. That's also why the numerical values were added, btw.

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/m_menu.c#L1953
