### ISSUE TITLE
Crispy Doom appears to play the wrong external mp3s for E2M3 and E3M6.

### ISSUE THREAD

**Issue by TheMiguelSanchez** [fabiangreffrath/crispy-doom#547]
Version of Crispy Doom: 5.5.20. 

Issue is also present with 10/03/2020 build. 

Operating System and version: Win 7 64-bit Pro. 

Game: Doom (Doom II currently untested)

WAD: Doom registered v1.9

Observed behavior: When using correctly-named external MP3 music files, Crispy Doom appears to play the wrong MP3 files for levels E2M3 and E3M6. 

When playing level E2M3, d_inter.mp3 is played instead of d_e2m3.mp3

When playing level E3M6, d_e1m6.mp3 or d_e3m4.mp3* is played instead of d_e3m6.mp3

*(Both files contain the same music track)

For all other levels ingame the correct mp3 files appear to play. 

All mp3 files have been checked and they contain the correct music for the filename. All MP3s contain no metadata or tags other than the filename. 
Remuxing the files to OGG format has no effect ingame. 

All mp3 files work fine using Doomsday- files are played correctly for E2M3 and E3M6. 

Using the Ultimate Doom WAD in Crispy Doom has no effect on this issue. 

Doom II is untested- I'm not sure if the same issue arises anywhere there. 

Keep up the awesome work, guys. Crispy Doom rocks!

**Comment by fabiangreffrath** [comment]
Thanks for the report! However. this does not seem to be a Crispy specific issue. I haven't even changed the music pack code.

Could you please check if the same happens with a daily Choco build as well, so we could transfer this issue to Choco's own bug tracker?

http://latest.chocolate-doom.org/

**Comment by TheMiguelSanchez** [comment]
Hi, thanks for the response. 

Weirdly, I can't get external music files to work with the latest Choco build, but they work no problem with the latest Crispy build... I've checked the music files, they're ok, and I've checked the cfg file and the music packs folder location is correct. Not sure what's happening there...

**Comment by kitchen-ace** [comment]
I can verify that this problem exists in Chocolate Doom's current git build. Also, I'm not using a config file, I've just unzipped the ogg files into the music-packs directory.

(@TheMiguelSanchez I can also verify that external music files don't seem to work on the 3.0.0 stable release of Chocolate.)

**Comment by kitchen-ace** [comment]
The reason this happens is because Chocolate Doom checks hashes of the lumps instead of lumpnames for substituting music. Since, for example, D_INTER and D_E2M3 in doom.wad are the same file, they produce the same hash, and so Chocolate uses the same mp3 for both.

@TheMiguelSanchez I'm curious as to what mp3s you have for D_E2M3 vs D_INTER that this is a problem? Since with MIDI output they would produce the exact same music.

**Comment by fabiangreffrath** [comment]
Closing, as this has been identified as a known upstream problem.
