### ISSUE TITLE
Crispy Doom Setup won't load

### ISSUE THREAD

**Issue by IceSpyLittleEye** [fabiangreffrath/crispy-doom#551]
### Background

Version of Crispy Doom: 5.7.2 (also tried 5.7.1 and 5.64)

Operating System and version: Windows 10 ver 1903 (OS Build 18362.720)

Game: N/A

### Bug description

Observed behavior: Running "crispy-doom-setup.exe" results in a window opening that's all white before closing a second later.

Expected behavior: The grey setup menu doesn't appear. 

### More info
I tried researching myself before posting but the fixes I found did not work for me. I only have Windows Defender as an anti-virus (I tried disabling it temporarily to make sure it wasn't this) and I'm an admin with writing permissions already. I also tried doing it from the desktop just to make sure, with no success there.

I downloaded the latest version of Crispy Doom on a different computer with the same exact build of Windows, which worked perfectly fine. For some reason my main PC just doesn't work. Thinking of doing the setting up on my other PC and transferring it over to my gaming PC instead (if that'll work), but it'd be easier to do it on one PC if I could.

**Comment by fabiangreffrath** [comment]
This sounds like an issue with your windows installation to me. How am I supposed to help here?

**Comment by IceSpyLittleEye** [comment]
Sorry, just thought maybe there was something I was missing. Since I've never had an issue with anything else before, I didn't know what it could be.

**Comment by fabiangreffrath** [comment]
Sorry I couldn't help you.

**Comment by IceSpyLittleEye** [comment]
No worries. :)
