### ISSUE TITLE
Please add optional antialiasing

### ISSUE THREAD

**Issue by skyrain128** [fabiangreffrath/crispy-doom#554]
Can you add optional antialiasing??
Without AA, the graphics of game looking not so good..
Many source ports have AA option, but Crispy doesn't have it;;;
(ZDaemon is old port and have only SW renderer, but even ZDaemon has AA option..)

Crispy has smooth pixel scaling option, But why you don't add AA option??
If you add AA option, Crispy's 640x480 high-res(?) screen looks much better.

**Comment by fabiangreffrath** [comment]
Nope, the port is supposed to look exactly like it does.
