### ISSUE TITLE
Fast double tapping `3` may select shotgun

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#556]
Fast double tapping `3` key may select shotgun immediately, instead of selecting SSG first and shotgun second.

Honestly, I'm not actually sure is it safe behavior for demos/network code, but it may be pretty useful. If I'm not mistaking, same effect can be achieved by fast tapping next/previous weapon button on joyctick. 

_Suggestion №115_

**Comment by fabiangreffrath** [comment]
I don't quite understand. Do you report this as a bug that it is possible to accidently select the shotgun by double-tapping '3' or do you suggest that it should be possible to do so?

**Comment by JNechaevsky** [comment]
Oops, I'm suggesting to make it possible (if it's safe).

**Comment by fabiangreffrath** [comment]
Looks like in order to select the shotgun (instead of SSG) by pressing the key for shotgun, the SSG already needs to be `player->readyweapon` which means it will need to be at least in its lowering state.

**Comment by JNechaevsky** [comment]
...while it should be able to switch even in `raise` states. I need to dig in deeply and double check behavior of next/previous weapon buttons. 

Oh, by the way, playing on simple PC gamepad seems to be quite challenging and fun. Try to defeat Cyberdemon on E2M8 and see how much rockets you will need. But selecting weapons via next/prev. buttons is absolutely comfortable, of course, if you know how much time you need to press such buttons.

**Comment by JNechaevsky** [comment]
Hm, yeah, quick tapping trick does not working on gamepad, i.e. I can quickly cycle through from pistol to BFG (w/o waiting for every weapon to be in `readyweapon` state), but can't choose shotgun this way.

**Comment by JNechaevsky** [comment]
I'm confused. Could you please point me out to the condition, which is preventing weapon selection until `player->readyweapon` is set? But again, how next/previous buttons are allowing to quickly cycle trough all weaspons except SSG/Shothgun?

Or really, changing this logics may be totally unsafe, and it will be better to close this issue for good.

**Comment by fabiangreffrath** [comment]
That'd be here:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_user.c#L413

Interestingly, there is no key binding in Doom to select the SG if the SSG is also available. On the other hand, you can bind a key for the SSG...

**Comment by JNechaevsky** [comment]
> Interestingly, there is no key binding in Doom to select the SG if the SSG is also available. On the other hand, you can bind a key for the SSG...

Oh my, now I'm afraid to think how `wp_shotgun` can be selected at all, since there is no any `newweapon = wp_shotgun` results.

**Comment by fabiangreffrath** [comment]
The shotgun is selected if one of the two later checks in the condition are false, i.e. if you either do not own the SSG or if the SSG is already the readyweapon.

**Comment by JNechaevsky** [comment]
Ah, I see. This whole section is written not like "press `4` -> select `chaingun`", but like "cycle by pressing, select if possible". And there is more checking code: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_pspr.c#L354

Jeez, this gets even more complicated.

**Comment by JNechaevsky** [comment]
Another interesting finding, available only in `commercial` game mode (i.e. where SSG existing). Type `IDKFA` to get all weapons. Choose a pistol. Now:

* Quickly tap `nextweapon` button three times. Rocket launcher will be choosen.
* Next, quickly tap `previousweapon` button three times. Instead of pistol, SSG will be choosen.

**Comment by fabiangreffrath** [comment]
In think I remember that nextweapon just iterates through the numbers, i.e. 3-4-5, whereas prevweapon tries to catch the SG as well, i.e. 4-3-3. Are you sure you ended up with the SSG, not the SG?

**Comment by JNechaevsky** [comment]
Seems to be so. Yeah, selecting is stoping on SSG, not a SG.

**Comment by fabiangreffrath** [comment]
From the rocket launcher, one tap on prevweapon should bring you to the chaingun, the next one to the SSG and the third one to the SG - or not?

**Comment by fabiangreffrath** [comment]
Because, you cannot select the SG if the SSG wasn't selected before, right?

**Comment by JNechaevsky** [comment]
> From the rocket launcher, one tap on prevweapon should bring you to the chaingun, the next one to the SSG and the third one to the SG - or not?

> Because, you cannot select the SG if the SSG wasn't selected before, right?

True on both questions. Interesting, you may even choose a Chaingun, then very quickly tap `previousweapon` about 4-5 times, and still, SSG will be choosen. 😑

**Comment by fabiangreffrath** [comment]
If you make it to tap twice during one tic, i.e. withing 28 ms, it will be registered as only one tap.

**Comment by fabiangreffrath** [comment]
Well, what's recorded during one tic (i.e. relevant for demos and network games) is "player pressed 3" and not "player selected shotgun". The engine then checks what weapon it can raise for the pressed key - and it never decides for the shotgun if the SSG is available and not already active. 

So, I cannot curently think of a way to convince the engine to directly raise the SG if the SSG is available but not already active.

**Comment by JNechaevsky** [comment]
Me neither, honestly, thanks for explanations. In theory, we can remember what kind of shotgun was selected previously, but no, this is too much habbit-breaking thing and should not happen.

**Comment by JNechaevsky** [comment]
Let's just close and reject it. Yes, refactoring weapon selection code and allowing to choose between shoutguns may be comfortable for player, but there is one point which must be accounted: this is a part game mechanics.
