### ISSUE TITLE
IWAD Selection menu before launch game.

### ISSUE THREAD

**Issue by skyrain128** [fabiangreffrath/crispy-doom#557]
Crispy only launches Doom 2 IWAD when I don't use launcher.
So I should load other IWAD with third-party launchers like ZDL if I want to play other IWADs like Ultimate Doom.
I want I can select IWAD before launch the game. Other ports have that feature.
Can you add this feature?
![GZDoom IWAD Selection menu](https://user-images.githubusercontent.com/50762042/77307193-2dad0300-6d3c-11ea-9d9b-75ec8cca735a.png)

**Comment by fabiangreffrath** [comment]
This isn't a Windows-only port. Any launcher would have to be plaform-agnostic and run on at least Windows, MacOS and Linux. I currently don't see a way to achieve this within the Crispy code base, the result would be yet another Doom launcher project. Also, the lack of a launcher affects Chocolate Doom as well, so it would be better reported over there. In fact it already was, so it probably makes sense to bring this discussion back to life there:

https://github.com/chocolate-doom/chocolate-doom/issues/599
