### ISSUE TITLE
Just black screen

### ISSUE THREAD

**Issue by vorob1** [fabiangreffrath/crispy-doom#558]
Laptop with ATI X1800, Vista 32bit. Setup works fine, game runs just black. I can hear sounds, can move menus, but black screen.

**Comment by fabiangreffrath** [comment]
Please try to enable the `force_software_rendering` feature in the config file.

**Comment by vorob1** [comment]
> 
> 
> Please try to enable the `force_software_rendering` feature in the config file.

Yes, that helped. Dx9 cards cant do hardware acceleration here?

**Comment by fabiangreffrath** [comment]
I have no idea. We ask SDL2 to provide a suitable renderer, which in turn asks he OS and returns whatever it gets offered. If the returned hardware renderer cannot do the simplest texture scaling, then maybe a driver update would do good. However, nothing that could get fixed on the Crispy side of things. Good luck!

**Comment by JNechaevsky** [comment]
Few more questions here. @vorob1 what is your OS and video card? And do you have a graphics card drivers installed?

**Comment by JNechaevsky** [comment]
Oops, sorry, haven't noticed in first post. According to specifics, it should be able to run the game fine. Not sure about Windows Vista, though...
