### ISSUE TITLE
Crispy Boom?

### ISSUE THREAD

**Issue by kraflab** [fabiangreffrath/crispy-doom#559]
I looked around in past issues and saw this topic has come up somewhat, and it seemed like it wasn't planned but also isn't 100% off the table. It was also some years ago so I figured I'd raise the issue on its own.

Is there a possibility of adding boom compatibility to crispy?

It remains a dream to have one port handling Doom, heretic, and boom that is also speedrunner-friendly and feature-rich, and I can at least speak for the speedrunning discord that crispy boom would be an amazing achievement. 😄

On the other hand I completely understand it's kind of backwards to add support for something so far from vanilla to what is ultimately a fork of chocolate. I also recognize that this isn't "the speedrunner port" and we aren't the biggest audience.

While I'd be happy to offer support in such an endeavor, it's definitely not something I could pursue independently. I assume that this would be a pretty huge undertaking with lots of complications.

**Comment by fabiangreffrath** [comment]
It's not completely off the table, but I can only repeat what I stated on the Doomworld forum lately (cannot find the threa right now, searching is broken). The main problem is that Boom has not been implemented as a clean incremental patch on top of the Vanilla sources (granted, GIT was not yet available back then), so this is a problem per-se for a port that attempts to be exactly this for Chocolate Doom.

Boom introduced changes throughout the entire code base, including white space changes, comments and even renaming the elements of enum{}s. It's more of a rewrite than an enhancement.

What we could probably do is adding support for extended linedefs, generalized linedefs and generalized sectors. There is an issue in the tracker for some 5 years to collect some ideas, but nothing really concrete yet: https://github.com/fabiangreffrath/crispy-doom/issues/56

Also, @mfrancis95 once started a fork to implement this, but I am not sure how far this has gone, i.e.  it hasn't seen any commits in the past 2 years: https://github.com/mfrancis95/crispy-boom

Please note that even if we did the tremendous effort of adding clean support for generalized linedefs and sectors, we would still be *far* from being demo-compatible with Boom. For this, we would have to add all the dirty litte details like pushers/pullers, reduced friction, weapon changing logic, whatever, who knows, all that stuff. And by addind all this, we would have to be extremely careful not to risk demo compatibility with Vanilla, our holy grail.

You see, I am not completely opposed to the idea, but I estimate the amount of work his requires to be on a similar scale as all the accumulated work that went ino Crispy until now. You don't simply "add Boom support", you rewrite your engine. This isn't colored blood or translucent sprites...

**Comment by Zodomaniac** [comment]
The work on Crispy Boom had been started but was abandoned...
https://github.com/mfrancis95/crispy-boom

**Comment by Zodomaniac** [comment]
Maybe it would make sense to bring Crispy features into Woof?

**Comment by fabiangreffrath** [comment]
First, I don't want Woof to become non-MBF, so features are only added very carefully.
Second, it still carries severe compatibility issues with Boom 2.02 inherited from original MBF.

**Comment by drfrag666** [comment]
> What we could probably do is adding support for extended linedefs, generalized linedefs and generalized sectors.
That would be great and would allow playing Boom maps, for demos you could just not play them as you're doing now. But Crispy already loads Boom maps even if they can't be played properly and that could be misleading. I make RUDE abort now with such maps but thay can be run with the -boom parameter. That said adding all that stuff may be it's too much work unless you can copy-pasta the code from another port which added Boom support even if incomplete like an early legacy or even ZDoom. And get the code with DiffMerge comparing different old versions, just an idea.

**Comment by drfrag666** [comment]
Now i remember that Doom Retro is Boom compatible and @bradharding disabled demo playback, may be you could "suck" the code from there. I don't know how he added Boom support tough.
 Risen3D can also run Boom maps.

**Comment by drfrag666** [comment]
I've been reviewing history and it's there but Brad created his repository from scratch. There was a lot of specific DR stuff already there and there are many Boom commits. Technically it should be doable tough. May be if you create a branch and merge Brad's second initial commit resolving conflicts using head (yours) histories could become related and you could cherry-pick then.

**Comment by drfrag666** [comment]
Seems there are many differences and the files are in a different folder, i've compared with Choco 2.0.0. I see in Choco specials are referred by number and not description like in DR and others. Of course it could be ported manually but that would require quite a bit of work.
 About Legacy Boom support was added by SOM between 1.28 and 1.30 but seems the source for 1.28 is lost. They even played demos at some point according to the changelog.

**Comment by drfrag666** [comment]
> I've had a look at the Legacy 1.30 source and while it would be nice to preserve that old code this wouldn't be really useful to add Boom support to Choco forks, they copied a ton of code from Boom. What would be nice is to add a minimal clean implementation of specials required to complete the maps as fabian said. The best approach probably would be to "suck" and adjust the code from Doom retro then.

**Comment by fabiangreffrath** [comment]
Sources for Boom and MBF are available so why should we take Boom code from any other port?

**Comment by drfrag666** [comment]
You said it earlier, i was looking for an alternative subset of Boom.
> Boom introduced changes throughout the entire code base, including white space changes, comments and even renaming the elements of enum{}s. It's more of a rewrite than an enhancement.

DR looks interesting as it's based on Choco and the Git history is there, but it'd require to merge and adjust the interesting commits manually. But i think it's better than looking at Boom directly, also note that it uses enums in r_defs.h instead of numbers for specials.

**Comment by maxmanium** [comment]
If Boom compatibility will ever come to Crispy, I think it would be worthwhile to do what you said, @fabiangreffrath, and just add support for the biggest Boom additions (extended linedefs, generalized linedefs and sectors). Demo-compatibility is the biggest pain in the ass in source port development so I think a good compromise would be to forego demo compatibility aside from the three Vanilla versions, though I don't know how you'd go about preventing such a thing. Boom demo-compatibility issues can be left to ports such as PRBoom+. It would be very cool to be able to launch non-ZDoom wads with Crispy Doom (aside from those with MBF features -- that's for Woof).

**Comment by kraflab** [comment]
Gonna close this issue.

- at the time, there was no port that supported doom, heretic, and boom, and was demo compatible. But now dsda-doom satisfies this condition.
- woof now supports boom, so it satisfies the "i want a more conservative port than pr+ but still want boom" condition.

Thus, the motivation to do such a thing in crispy is less relevant, at least from my side.
