### ISSUE TITLE
Jerky bobbing with centered weapon alignment and some mods

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#564]
### Background

Version of Crispy Doom: 5.7.2

Operating System and version: Arch Linux 64-bit

Game: Doom

When using [Vanilla smooth Doom](https://soulsphere.org/random/vsmooth.zip), if Crispy's "Weapon Attack Alignment" option is set to "Centered" the chainsaw's bobbing is quite jerky. I have noticed this with other wads with Dehacked as well, such as D4V's alternate plasma gun replacement.

**Comment by fabiangreffrath** [comment]
I don't know these mods in detail, but it is possible that they re-assign the "weapon ready'" state to a different function than `A_WeaponReady()` whereas in Crispy weapon movement is only interpolated for weapons in exactly that state.

Out of interest, is it more smooth in Chocolate Doom?

**Comment by kitchen-ace** [comment]
It's fine in Chocolate, and also fine in Crispy if Weapon Attack Alignment is set to Bobbing or Off. Only Centered causes problems.

**Comment by kitchen-ace** [comment]
I believe what's happening is: since these weapons borrow frames from other places with Dehacked, those frames aren't being marked as `A_WeaponReady` in [info.c](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/info.c#L150), and so in [p_pspr.c](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_pspr.c#L1020) those frames are being centred. 

I'm not sure what the solution is though.

**Comment by fabiangreffrath** [comment]
Indeed, the code is here https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_pspr.c#L1009 and the logic is like this: If the weapon isn't in lowering or raising state, it must be in attacking state - unless its action function is `A_WeaponReady()`, then it's in its idle state.

Maybe I'll need to change this to track `player->attackdown` instead.

**Comment by kitchen-ace** [comment]
Confirmed fixed. Thanks!
