### ISSUE TITLE
Crispy errors out when player respawns after death

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#566]
### Background

Version of Crispy Doom: Latest git

Operating System and version: Win 7

Game: Doom (2)

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: when player respawns after death, Crispy errors out with this message
![Z_CheckHeap](https://user-images.githubusercontent.com/15119473/78120761-290add80-7413-11ea-9715-24314eeb3ef6.png)

**Comment by fabiangreffrath** [comment]
Hm, cannot reproduce. However, this would mean that we mesh up zone memory at some point.

**Comment by fabiangreffrath** [comment]
Okay, reproduced. There is some bug in `R_DrawViewBorder()`.

**Comment by Zodomaniac** [comment]
This also happens at starting new game when there is an in-WAD demo running.

**Comment by fabiangreffrath** [comment]
Fix is pending. Tomorrow...
