### ISSUE TITLE
New widescreen status bar bezel shows problems at high resolution

### ISSUE THREAD

**Issue by cnrm** [fabiangreffrath/crispy-doom#567]
Version tested: https://github.com/fabiangreffrath/crispy-doom/commit/11beaaed2adda01537508e8e1836070dca18740b

With low resolution rendering, the small border (green in this case) to the left and right of the status bar is a consistent solid line.
![DOOM0001](https://user-images.githubusercontent.com/5803611/78149630-340a4180-7404-11ea-87ad-223f24b5df78.png)

However, with high resolution rendering, inconsistencies appear at the left and right edges of the display that aren't present at low resolution.
![DOOM0000](https://user-images.githubusercontent.com/5803611/78150826-cf4fe680-7405-11ea-9415-dbc646534a54.png)
![bezel_left](https://user-images.githubusercontent.com/5803611/78151346-83517180-7406-11ea-9ec8-dd41d7f4b727.png) ![bezel_right](https://user-images.githubusercontent.com/5803611/78151355-851b3500-7406-11ea-9bb7-51782bb790a2.png)

This occurs in other games too (Doom, Doom II, etc.) but it's much more subtle; I chose Chex Quest as an example because it stands out easier.

**Comment by fabiangreffrath** [comment]
This is the same fix as for #566 which I will apply tomorrow.

**Comment by cnrm** [comment]
Good to know. I had a feeling it might be related. Thanks for the quick turnaround.
