### ISSUE TITLE
Crispy-specific lumps?

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#568]
### Background

Hi Fabian, I'm curious what you would think of supporting reading of a `CRISPY` lump in wads, that wad authors could use to specify values for coloured blood, sprite translucency, brightmaps, etc. That way projects which significantly modify the Doom resources could still look good with Crispy's extra visual enhancements. Supporting a Crispy-specific lump would make it easy to fix problems like https://github.com/fabiangreffrath/crispy-doom/issues/461

**Comment by fabiangreffrath** [comment]
Hm, do you mean something like the OPTIONS lump supported by MBF which people could use to forcefully enable or disable certain features of the engine? In that case this would be a text file containing a list of lines consisting of key/value pairs - most specifically all the lines starting with "crispy_" in crispy-doom.cfg.

I am not completely opposed to this idea, but currently lack the imagination for what else this could be useful - apart from adding one more niche solution. :thinking:

**Comment by fabiangreffrath** [comment]
I have to get used to the fact that you are @plumsinus now...

**Comment by kitchen-ace** [comment]
>Hm, do you mean something like the OPTIONS lump supported by MBF which people could use to forcefully enable or disable certain features of the engine?

Not exactly, rather they could specify:

* Different blood colours for different enemies, to match modified sprites
* Which Things/frames do and don't get transparency applied
* Which colours get a brightmap effect on new textures/sprites (possibly; I'm not entirely sure how brightmaps work in Crispy)
* Maybe some more stuff I'm not thinking of?

Currently those are all hard-coded and your only options are turn them on with all default values, or turn them off.

**Comment by fabiangreffrath** [comment]
Hm, sounds pretty abstract and far away at the moment. I'll keep this open for some time to see if something useful crystalizes out...

**Comment by kitchen-ace** [comment]
>Hm, sounds pretty abstract and far away at the moment.

It isn't abstract to me, and I can think of a few wads/mods/etc. that would benefit from it just off the top of my head, including Doom4Vanilla (the mod in #461). Many older projects could also benefit and it could be worthwhile to support the most well-known ones, e.g. Epic 2, Scythe 2, etc. (Far away is another issue, it's certainly not a priority feature, although *maybe* it's something I can implement if you like the idea...)

To give you an example of what I'm thinking, here's an pseudo example CRISPY lump. Obviously the syntax is completely up in the air, as is everything else.

    [TEXTURES] // texture brightmaps
    COMP201 blueandgreen
    COMP202 blueandgreen
    PIPEWALL1 nobrightmap

    [SPRITES] // sprite brightmaps
    SPR_HEAD greenonly1

    [BLOOD] // thing blood
    MT_HEAD red2yellow // we should make some new translations
    // maybe even allow user-defined translations and brightmaps?

    [TRANSLUCENCY] // thing translucency
    // translucency might need refactoring for this to work
    MT_HEADSHOT off

Again, not urgent, it's fine if you want to think about it for some time.

**Comment by kitchen-ace** [comment]
Here's an example where defining brightmaps would fix some problems: Several Doom 2 maps, as well as FreeDoom2, use the SLADRIP slime falls from Doom 1. TNT uses SLADRIP1 & 3, but not 2, for its animations. Those two are defined with brightmaps for TNT, but as a result any maps using the original doom textures look kind of funny. 

![slad](https://user-images.githubusercontent.com/47063032/89738568-c15f4180-da47-11ea-9c2c-279177735b4e.gif)

You could just un-brightmap those textures, but a better solution IMO would be to allow customizing them.

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.
