### ISSUE TITLE
Application was Unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by Fez64** [fabiangreffrath/crispy-doom#569]
### Background

Version of Crispy Doom: 5.7.2

Operating System and version: Windows 10 64-bit v 1903 build 18362.720

Game: (Doom)

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: Launching the application brings up "The application was unable to start correctly (0xc000007b)"

Expected behavior: The last build I used didn't give me this issue.

**Comment by fabiangreffrath** [comment]
Did you mix up 32bit and 64bit binaries and libraries?

**Comment by Zodomaniac** [comment]
@fabiangreffrath , I remember you asked me on Doomworld to bundle my homebrew binaries with the autobuilder's DLLs. I must say at least zlib1.dll is to be added to that. Gonna re-upload in a minute.

**Comment by fabiangreffrath** [comment]
Next release will be from the auto-builder again.

**Comment by Zodomaniac** [comment]
Re-uploaded.

**Comment by fabiangreffrath** [comment]
Should be fixed with the 5.8.0 release.
