### ISSUE TITLE
Add truecolor rendering

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#57]
As soon as the sdl2-branch is merged into Chocolate Doom's master branch, do the switch to truecolor rendering. The current hicol2 branch is a mess and should _not_ get merged, though.

**Comment by JNechaevsky** [comment]
Uh? Apparently, wrong issue closed? And what's wrong was with your music fix?

**Comment by fabiangreffrath** [comment]
> Apparently, wrong issue closed?

Oh, yes, the bug closing was because I cherry-picked a commit from your project, which closed issue 57 for russian-doom. ;)

> And what's wrong was with your music fix?

There are days when my own code makes me sick. My approach was over-engineered and yours was simply straightforward. I wanted to fix the issue on the OPL driver level at any cost, but this resulted in a more complicated and error-prone solution.

**Comment by fabiangreffrath** [comment]
Update: After more than three years, I am still cowardly hesitating to pull the switch to true-color rendering.

Pros:
 - Doom will look great!

Cons:
 - The three non-Doom games would be instantly broken and fixing them might prove non-trivial (c.f. tailored patch blending functions, in-game palette changes, etc.)
 - Doom mods with custom palettes (i.e. non-standard pain, power-up and rad-suit blending) would be broken

A compile time switch might be one solution, but I don't see a run-time option for switching between "true" (i.e. non-emulated) paletted and true-color rendering as a possible solution (I would have to duplicate each low-level rendering function for this).

**Comment by JNechaevsky** [comment]
I think I have a raw idea/suggestion about how make custom `PLAYPAL` actually working (not a `COLORMAP`, doh) in true-color. I can't explain it just a few words, so please, kick me on the weekend - I'm currently over-focused on my day job, so I can simply forgot about it.

**Comment by fabiangreffrath** [comment]
This is already implemented in the "--enable-truecolor" code path.
