### ISSUE TITLE
improper weapon attack alignment when player object isn't in firing state

### ISSUE THREAD

**Issue by unRyker** [fabiangreffrath/crispy-doom#571]
(Click image below to watch video demonstration)
[![Thumbnail](https://img.youtube.com/vi/B96GrrO0irk/0.jpg)](https://www.youtube.com/watch?v=B96GrrO0irk)
Noticed from this commit: https://github.com/fabiangreffrath/crispy-doom/commit/117fc45a9584e3d8772d4e927aa739a53e469c4b

The weapon sprite position is updated during very specific states when the player object's sprites aren't in a firing state, which is incorrect if "Weapon Attack Alignment" is set to "off" or "centered" which is meant to prevent this movement of the first person weapon sprite firing. Specifically, the weapon bobs when the player is either hurt, or the weapon bobs before the supposed firing states are finished (seen with the fists). Not tested with bobbing weapon attack alignments, but I assume that it looks normal since the weapon is always meant to be bobbing.

This might be a tricky issue as this was meant to be a solution for https://github.com/fabiangreffrath/crispy-doom/issues/564

**Comment by fabiangreffrath** [comment]
I see, thanks. I guess, I will have to check for the attack key being held down then. Though, I remember an inconsistency when the weapon is automatically switched to either the Rocket Launcher or the BFG. Anyway, I think the visual feedback for the player is still better than now.

**Comment by kitchen-ace** [comment]
Would it be any better to track weapon state changes, so that a "no state" frame preserves the behaviour of whatever the last state was?

**Comment by fabiangreffrath** [comment]
Could be the most correct solution, sure. But also sounds a bit over-engineered for a problem that boils down to: when firing do this else do that.
