### ISSUE TITLE
Crispy DooM v1.0 with HiResolution

### ISSUE THREAD

**Issue by SandMartininbox** [fabiangreffrath/crispy-doom#574]
Hello guys.
I have BFG edition of DooM 2 (Classic DooM Unity port from bethesda) and I like it very much. But it does not support multiplayer and third-party wads (Sigil, Double Impact etc ..)
The closest port to BFG Edition is Crispy DooM v1.0 (why exactly 1.0? because it is without additional menu options but with the doom engine limits removed).
And Since I'm not a programmer, I wanted to ask a question:
How difficult is it for Crispy DooM v1.0 source code to switch 640-400 to 1440-1080 (Its runs in 1920-1080 but workspace is 1440-1080) so that it looks like DooM1 / DooM2 from BFG Edition?
I would be very grateful if someone would make such a version of Crispy DooM.
Why? 
Because after Nerve Software in cooperation with id Software / Bethesda made OFFICIAL Unity Port in 2012, the 1080p resolution for Classic DooM  became official too. And it would be nice to see it in Crispy DooM 
 Thanks.

**Comment by QuartzSTQ** [comment]
I always thought about this myself, however the author has repeatedly mentioned that he won't implement any higher resolution. I myself wished for at least more multiples of the original Doom resolution. (so 640x400, 960x600, 1280x800 etc.)

Also, you mention that the Unity port doesn't support custom WADs. And while I'm pretty sure it doesn't, you also specifically mention SIGIL, and as far as I'm aware, that should be avalable as an "add-on" as part of the port itself.

**Comment by SandMartininbox** [comment]
> I always thought about this myself, however the author has repeatedly mentioned that he won't implement any higher resolution. I myself wished for at least more multiples of the original Doom resolution. (so 640x400, 960x600, 1280x800 etc.)
> 
> Also, you mention that the Unity port doesn't support custom WADs. And while I'm pretty sure it doesn't, you also specifically mention SIGIL, and as far as I'm aware, that should be avalable as an "add-on" as part of the port itself.

DooM and DooM 2 from DooM 3 BFG Edition do not support any other WADs, include SIGIL

**Comment by QuartzSTQ** [comment]
You mentioned the Unity port so I assumed that was what you were using. [In any case, the WAD used in the BFG edition port is similar, but not the same.](https://doomwiki.org/wiki/DOOM2.WAD)

**Comment by garoto** [comment]
Plenty of ports around that offer native-desktop rendering in some sort or another and support for the BFG Doom1/2 WADs should be widespread amongst the same ports in 2020.

**Comment by fabiangreffrath** [comment]
Sorry, guys, but Crispy Doom will remain limited to the double original resolution, e.g. 640x400.

There was a similar request a few weeks ago and the guy went on and created his own fork. I don't know how successful he was, but don't have high hopes given that his own source repository is not even online anymore:
https://github.com/fabiangreffrath/crispy-doom/issues/545
