### ISSUE TITLE
Missing "crispy_hires" setting in Heretic

### ISSUE THREAD

**Issue by vanfanel** [fabiangreffrath/crispy-doom#577]
Hi there! After seeing how crispyness settings are finally available for crispy-heretic, I had some fun today building and playing latest GIT Crispy.
However, I have noticed that, while crispy-doom has the High-Resolution rendering option available to be turned off on small systems like my dear Raspberry Pi, this is not the case for crispy-heretic.
I also tried manually adding `crispy_hires 0` to` crispy-heretic.cfg`, with no results at all (the setting seems to be ignored).
So, will that option and setting be included in crispy-heretic too, please?

Thanks!

**Comment by jgreen14** [comment]
I'm working on this right now. There's a couple little issues to work out still (huge/tiny mountains from the sky not getting rescaled), but hopefully I'll sort them out shortly.

**Comment by fabiangreffrath** [comment]
Fixed in https://github.com/fabiangreffrath/crispy-doom/commit/a60906529d1f0dae989b1fba07c93a78235d4027, thanks @jgreen14 !

**Comment by vanfanel** [comment]
@jgreen14 and @fabiangreffrath Whoa guys!! That was SO fast it was closed before I could reply! :dancers: 
Thanks!!!!
