### ISSUE TITLE
No Rest for the Living Hell Sky

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#579]
No Rest for the Living in Doom II 2019 Release was recently updated as follows:

- In the Add-on “No Rest for the Living”, Hell levels now use the correct hell sky texture.

I have tested the wad file included in this release in Crispy Doom, and it still has the old sky.  I was wondering if it would be possible to auto-detect the Doom II 2019 No Rest for the Living wad (checksum is diff), and, depending on the level, then load the hell sky.

**Comment by JNechaevsky** [comment]
Yeah, starting from MAP04 (Hell Mountain) sky is using Hell texture (MAP09 still using brown starport texture). 

Really odd desition, becuase AFAIR, whole NRFTL story was happening on Earth, not in Hell.

**Comment by fabiangreffrath** [comment]
Let's just fix this unconditionally if this is considered canonical behavior now.

**Comment by JNechaevsky** [comment]
Oh those modern canonicals... :/ @fabiangreffrath, give me some time please, I'll recheck every level and provide screenshots, just to be sure that everything is right.

**Comment by fabiangreffrath** [comment]
Sure, thanks! 👍

**Comment by bradharding** [comment]
I've just been confirming this myself: yep, MAP04 to MAP08 inclusive use SKY3 instead of SKY1. All other maps still use SKY1. I'm going to make the change in DR, even though I'm not a fan of it, particularly.

**Comment by JNechaevsky** [comment]
| Level | Sky | Screenshot |
| ------------------------ | ---- | ---- |
| Level 1: The Earth Base | SKY1 | [click](https://user-images.githubusercontent.com/21193394/79103483-58a3d900-7d75-11ea-9c3b-2527310d88f9.png)
| Level 2: The Pain Labs  | SKY1 | [click](https://user-images.githubusercontent.com/21193394/79103555-7b35f200-7d75-11ea-8ff6-2215c33bd03a.png) |
| Level 3: Canyon of the Dead | SKY1 | [click](https://user-images.githubusercontent.com/21193394/79103620-9d2f7480-7d75-11ea-9d58-1876424c592e.png) |
| Level 4: Hell Mountain | SKY3 | [click](https://user-images.githubusercontent.com/21193394/79103721-cbad4f80-7d75-11ea-9170-748b656222f4.png) |
| Level 5: Vivisection | SKY3 | [click](https://user-images.githubusercontent.com/21193394/79103775-e4b60080-7d75-11ea-8292-12e586980c1d.png) |
| Level 6: Inferno of Blood | SKY3 | [click](https://user-images.githubusercontent.com/21193394/79103838-feefde80-7d75-11ea-88fb-481a53eaa022.png) |
| Level 7: Baron's Banquet | SKY3 | [click](https://user-images.githubusercontent.com/21193394/79103868-10d18180-7d76-11ea-80ff-c220312d508e.png) |
| Level 8: Tomb of Malevolence | _No visible!_ | _...suggesting SKY3_ |
| Level 9: March of the Demons | SKY1 | [click](https://user-images.githubusercontent.com/21193394/79103963-44141080-7d76-11ea-80c2-c6685dcf8047.png) |

**Comment by fabiangreffrath** [comment]
Fixed in https://github.com/fabiangreffrath/crispy-doom/commit/8be600af0cc70ee39e533fc1667d6482588e8d88, thanks @JNechaevsky !
