### ISSUE TITLE
[Feature request] Crispness options for crispy-hexen?

### ISSUE THREAD

**Issue by vanfanel** [fabiangreffrath/crispy-doom#581]
Seeing how Heretic is now "complete" in crispness terms (uncapped framerate, original 320x200 resolution rendering, vsync...), will we see the same in crispy-hexen too?

**Comment by fabiangreffrath** [comment]
If you find someone who volunteers to add all this to Hexen, sure why not? Fine with me at least.

**Comment by Asais10** [comment]
Yeah I think Crispy HeXen should be a thing as it's the last game that doesn't have a middle-ground sourceport between something like Chocolate HeXen (with it's 35fps cap and it's low internal resolution) and GZDoom (with it's weird changes that have basically nothing to do with mod support, like lost souls being counted as monsters, at least you can fix that with some coding but there are other things that you can't.)

If you're wondering what the middle-ground sourceport for Strife is, it's Nightdive's official Veteran Edition.

**Comment by uralets** [comment]
> Hexen might be the easiest game to do a "Crispy 1.0" release for. Correct me if I'm wrong, but the higher resolution is already implemented. I'm not sure if the limits have been lifted. In order to match Heretic's first release, a crispness menu, uncapped framerate, vsync and smooth automap/ map coordinates might be all that is required.
> 
> Hexen doesn't really need a kill/ item/ secret count or secret found message due to the nature of the game. You also don't really need all of Crispy Doom's features, like crosshair options.

Yep, the high-res is there (manually compiled Crispy w/Hexen myself).
Mouselook would be nice. It's kinda useful from time to time in this game.

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.
