### ISSUE TITLE
NERVE.wad Support for Vanilla DOOM 2

### ISSUE THREAD

**Issue by hkight** [fabiangreffrath/crispy-doom#582]
I am trying to use my copy of NERVE.wad with the standard version of DOOM II, and there are several issues that are present. No episode select, no proper title screen, the secret exit doesn't work, etc. I understand that the episode select graphics are not present in standard DOOM II, but I fixed that manually in my copy of DOOM2.wad. Is there any way these other issues can be fixed? I'd much rather not use the BFG Edition with its many problems and downgrades.

**Comment by fabiangreffrath** [comment]
I have an idea. Let's see what I can make out of it.

**Comment by fabiangreffrath** [comment]
The main issue is that even Vanilla DOOM2.WAD contains the episode selection menu graphics lumps - but they still read the episode names of Doom 1. How can I tell that the graphics that I am going to show in the episode menu are the correct ones, i.e. "Hell on Earth" and "No Rest for the Living"?

**Comment by hkight** [comment]
The names exist in the WAD file for the BFG Edition of DOOM II.  Since Crispy already works with the BFG Edition, there'd have to be a way for Crispy to replace the assets in Vanilla DOOM II.

**Comment by fabiangreffrath** [comment]
Hm, I could rename the menu graphics lumps out of the way if the current IWAD does not contain the DMENUPIC lump.

**Comment by Zodomaniac** [comment]
There is a PWAD fix for BFG Edition that restores censored content: Make IDKFA Wolfenstein again https://forum.zdoom.org/viewtopic.php?f=19&t=53776
