### ISSUE TITLE
Crispy Heretic uncapped mouse sensitivity

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#583]
Colleagues, please give your opinions on the question if the mouse sensitivity should overflow in Crispy Heretic same as in Crispy Doom.

**Comment by fabiangreffrath** [comment]
Feel free to apply the same changes here as in Crispy Doom.

**Comment by fabiangreffrath** [comment]
Fixed in https://github.com/fabiangreffrath/crispy-doom/commit/03702cbe632924846aa6130b2afbf9480f188001
