### ISSUE TITLE
Wrong sky in NRFTL MAP04-08 when launched from command line

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#585]
### Background

Version of Crispy Doom: 5.8.0

Operating System and version: Win 7 Prof

Game: Doom 2 BFG Edition

Any loaded WADs and mods (please include full command line): `start crispy-doom -iwad doom2(2).wad -episode 2 -warp 04`

### Bug description

Observed behavior: the sky is terrestrial, cloudy.
![DOOM0097](https://user-images.githubusercontent.com/15119473/79545635-b0a24e80-8099-11ea-9320-64e0a8060874.png)

Expected behavior: the sky should be red, hellish `SKY3`.
![DOOM0099](https://user-images.githubusercontent.com/15119473/79546019-5950ae00-809a-11ea-8840-6d0d6fe03865.png)

**Comment by fabiangreffrath** [comment]
He, why? Is your nerve.wad called differently from, well, "nerve.wad"?

**Comment by Zodomaniac** [comment]
No, my nerve.wad is NERVE.WAD

**Comment by fabiangreffrath** [comment]
I see. This is because `gamemission` is set in `P_SetupLevel()` but the code deciding about the SKY flat is called earlier in `G_DoLoadLevel()`.
