### ISSUE TITLE
Is this location of the demo timer inside the reduced game window intentional?

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#587]
Maybe it would make sense to draw it in the screen corner, like the message widget?
![DOOM0097](https://user-images.githubusercontent.com/15119473/79584048-84f18980-80d6-11ea-8da9-0379047d550b.png)

**Comment by fabiangreffrath** [comment]
Yep, because then I don't have to care about clearing its background. 😁

**Comment by Zodomaniac** [comment]
OK, could you please hint me how to correctly bring it there in So Doom?

**Comment by fabiangreffrath** [comment]
You'll find everything here:
https://github.com/fabiangreffrath/crispy-doom/blob/c928c2adb7201acc548e96610a692a7e49df2c51/src/doom/st_stuff.c#L2417

**Comment by Zodomaniac** [comment]
I'm trying to apply `R_FillBackScreen()` in `ST_DrawDemoTimer`, but it doesn't help.

**Comment by Zodomaniac** [comment]
This doesn't help either

```
void ST_DrawDemoTimer (const int time)
{
	char buffer[16];
	const int mins = time / (60 * TICRATE);
	const float secs = (float)(time % (60 * TICRATE)) / TICRATE;
	const int w = shortnum[0]->width;
	const int h = shortnum[0]->height;
	int n, x;
	extern pixel_t *background_buffer; // [So Doom] for demo timer background with reduced screen sizes

	n = M_snprintf(buffer, sizeof(buffer), "%02i %05.02f", mins, secs);

	x = (SCREENWIDTH >> crispy->hires) - 2*WIDESCREENDELTA + HUD_WIDESCREENDELTA; // [So Doom] for Cockpit HUD, draw demo timer widget within the narrow screen

	R_FillBackScreen();
	if (background_buffer != NULL)
	{
	    V_CopyRect(x-n*w, 0, background_buffer, n*w, h, x-n*w, 0); // [So Doom] refresh timer background in case of reduced screen sizes
	}

	// [crispy] draw the Demo Timer widget with gray numbers
	dp_translation = cr[CR_GRAY];
	dp_translucent = (gamestate == GS_LEVEL);

	while (n-- > 0)
	{
		const int c = buffer[n] - '0';

		x -= w;

		if (c >= 0 && c <= 9)
		{
			V_DrawPatch(x, 0, shortnum[c]);
		}
	}

	dp_translation = NULL;
	dp_translucent = false;
}
```

**Comment by fabiangreffrath** [comment]
That's what you get for reverting my decisions. 😁

**Comment by Zodomaniac** [comment]
And if seriously, do you have any ideas? I cannot release So Doom's next version without the demo timer in the screen corner...

**Comment by fabiangreffrath** [comment]
It's also shown on the intermission screen. How are you going to solve this? 

I have explicitly decided against your approach so I don't have to fight with this crap.

**Comment by Zodomaniac** [comment]
I found the solution suitable for So Doom and made a release post on Doomworld :)
