### ISSUE TITLE
Building on Windows - Invalid package listed on wiki

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#589]
The wiki says to install the following package:

`mingw-w64-i686-python{2,3}-pillow`

This package is not valid in the latest mysys.  The correct package name is `mingw-w64-i686-python-pillow`.

In addition, the wiki does not mention that pandoc or zip need to be installed.

I am not sure if there is a package for pandoc.  I believe users must download it from https://github.com/jgm/pandoc and install it to /usr/bin.

**Comment by fabiangreffrath** [comment]
At least the build doesn't fail if pandoc isn't installed.

**Comment by fabiangreffrath** [comment]
I have updated the building instructions in the Wiki, thanks!
