### ISSUE TITLE
Add support for uncapped framerate

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#59]
This is currently prepared in the "uncapped" branch, thank to the outstanding effort of @AlexMax.

**Comment by Danfun64** [comment]
I'm guessing that if you are demo recording or playing on multiplayer this will force itself to turn off?

**Comment by fabiangreffrath** [comment]
This should not be necessary, as the interpolation really only affects the renderer. the game itself still "thinks" at 35 FPS. My first tests confirm that! :)
