### ISSUE TITLE
Missing M_NMARE in early IWADs hides all skill levels

### ISSUE THREAD

**Issue by zx64** [fabiangreffrath/crispy-doom#592]
When using IWADs older than the addition of Nightmare skill (1.0 and 1.1), the Choose Skill menu doesn't display any of the skill options:
![Missing skills](https://i.gyazo.com/4da62ebab0a20daf86cd784b34ae607b.png)

In Chocolate Doom, the skill options display with an invisible nightmare option:
![Chocolate Doom](https://i.gyazo.com/7acc41afa945692334450d9a4fa7adb7.png)

I think this difference stems from the `lumps_missing` check as if I comment out testing that on [this line](https://github.com/fabiangreffrath/crispy-doom/blob/c928c2adb7201acc548e96610a692a7e49df2c51/src/doom/m_menu.c#L2985) then it looks the same as in Chocolate Doom.

Thanks to the `alttext` feature we can get a slight improvement without having to remove that test.
Instead here's some potential changes to `m_menu.c`:
```menuitem_t NewGameMenu[]=
   ...
{1,"M_NMARE",	M_ChooseSkill, 'n', "Nightmare!"}
```
and then e.g. allow the alttext to override setting `lumps_missing`:
```
if (currentMenu->lumps_missing == 0)
   ...
 if (currentMenu->menuitems[i].name[0] && !currentMenu->menuitems[i].alttext)`
```

Results in this:
![alttext nightmare](https://i.gyazo.com/e9d0be31655d73c0e3c63b942f504213.png)

**Comment by fabiangreffrath** [comment]
Good idea, but please have a look at the Options menu then.

**Comment by fabiangreffrath** [comment]
I'd rather add alttext for all skill levels.

**Comment by zx64** [comment]
Like this you mean?
![all alt text](https://i.gyazo.com/72eb7054ee1beef8001c060ee2e3a222.png)

Reduces the diff to just:
```
  diff --git a/src/doom/m_menu.c b/src/doom/m_menu.c
  index 9847a155..809c0eda 100644
  --- a/src/doom/m_menu.c
  +++ b/src/doom/m_menu.c
  @@ -335,11 +335,11 @@ enum

   menuitem_t NewGameMenu[]=
   {
  -    {1,"M_JKILL",  M_ChooseSkill, 'i'},
  -    {1,"M_ROUGH",  M_ChooseSkill, 'h'},
  -    {1,"M_HURT",   M_ChooseSkill, 'h'},
  -    {1,"M_ULTRA",  M_ChooseSkill, 'u'},
  -    {1,"M_NMARE",  M_ChooseSkill, 'n'}
  +    {1,"M_JKILL",  M_ChooseSkill, 'i', "I'm too young to die."},
  +    {1,"M_ROUGH",  M_ChooseSkill, 'h', "Hey, not too rough!."},
  +    {1,"M_HURT",   M_ChooseSkill, 'h', "Hurt me plenty."},
  +    {1,"M_ULTRA",  M_ChooseSkill, 'u', "Ultra-Violence."},
  +    {1,"M_NMARE",  M_ChooseSkill, 'n', "Nightmare!"}
   };

   menu_t  NewDef =
```
(I'm assuming there's no DEH strings to localise those difficulty levels)

Fixes the Options menu having the inconsistent fonts and I've checked it against a more recent IWAD:
![doom 1.9 iwad](https://i.gyazo.com/2d0763397cb5a0f639514ed8a33ad109.png)

Shall I file a separate issue about making/including an image version of the Crispness entry in the options menu so that menu can be consistent with the classic fonts?

**Comment by fabiangreffrath** [comment]
Thank you for the patch!

> Shall I file a separate issue about making/including an image version of the Crispness entry in the options menu so that menu can be consistent with the classic fonts?

No, thanks! I will not embed a lump into the engine, and especially not a graphics lump using ID's own Doom font.

**Comment by fabiangreffrath** [comment]
> No, thanks! I will not embed a lump into the engine, and especially not a graphics lump using ID's own Doom font.

But the next Freedoom IWADs will have a graphics lump for the menu:
https://github.com/freedoom/freedoom/commit/637d2a0b9e89675c3624b5eeafd068a2f5f6dd6f

**Comment by zx64** [comment]
> I will not embed a lump into the engine, and especially not a graphics lump using ID's own Doom font.

That's fair. Do you have similar objections to runtime generation? It's possible to generate an image for "Crispness" at startup by reusing letters from M_SKILL ('C', 'i', 's', 'e') and M_HURT ('r', 'p', 'n').

**Comment by fabiangreffrath** [comment]
> That's fair. Do you have similar objections to runtime generation? It's possible to generate an image for "Crispness" at startup by reusing letters from M_SKILL ('C', 'i', 's', 'e') and M_HURT ('r', 'p', 'n').

Nope, sorry. Graphics in Doom are really just byte arrays and I would have to create new functions to tell "give me columns x to y of this graphic" and repeat this over several lumps several times to achieve the intended result. And then you would load a PWAD with a replacement font and everything will break apart. Sorry, but no.

**Comment by zx64** [comment]
That was indeed how I figured it'd be (and was prepared to grind out the requisite coordinates etc.), but you're right about PWADs ultimately making such functionality unacceptably fragile.
