### ISSUE TITLE
auto-load issues

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#595]
In the latest git, if you auto-load NERVE.WAD alongside DOOM2.WAD, the level results screen looks like this:

![nerve](https://user-images.githubusercontent.com/2666951/80154231-0718fc80-8574-11ea-9dd5-1bac67fd01d4.png)

If you use the BFG DOOM II WAD, Crispy crashes after beating a level.

If MASTERLEVELS.WAD is auto-loaded, the only accessible Master Levels map is Attack.  If you beat the level, Crispy crashes.

**Comment by fabiangreffrath** [comment]
Ah, looks like using `strcat()` to extend the lump names is a bad idea. It will add an eigth char to the name string and an additional null-byte - into an array of size 8. This kills the `wad_file` pointer which is thus having a bad day...
