### ISSUE TITLE
auto-load masterlevels.wad - cannot warp to levels

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#598]
If I auto-load masterlevels.wad and select the episode, I cannot idclev to any of the levels.  For example, idclev01 takes me to Entryway as opposed to Attack.

This is not an issue with nerve.wad.

**Comment by fabiangreffrath** [comment]
Indeed, seems like IDCLEV never worked with the Master Levels, even if loaded manually.

**Comment by buvk** [comment]
I believe it does work if you load masterlevels.wad manually.

I can reconfirm tomorrow.
