### ISSUE TITLE
Automap rotate mode - icons

### ISSUE THREAD

**Issue by icecreamoverlord** [fabiangreffrath/crispy-doom#600]
### Background

Version of Crispy Doom: 5.8.0 (latest commit)

Operating System and version: macOS High Sierra

Game: Doom

### Bug description

Rotate mode for the automap does not to work properly for icons revealed by using the IDDT cheat. The icons spin around in place, but do not rotate with the map.

![DOOM0001](https://user-images.githubusercontent.com/64403252/80351183-3c478680-88b5-11ea-9e97-f2f729f38eea.png)

**Comment by icecreamoverlord** [comment]
This does not happen if extended automap colours is turned on.

**Comment by fabiangreffrath** [comment]
Incredible, this is lurking literally for years. Thanks for the report!
