### ISSUE TITLE
Wiki guide for mac install - sdl2_mixer

### ISSUE THREAD

**Issue by icecreamoverlord** [fabiangreffrath/crispy-doom#603]
I recently followed the "OS X Compilation and Installation Guide" and all went well except for mp3 and flac playback.

It turns out the default homebrew formula for sdl2_mixer (used in Step 2C Part 4 of the guide) **no longer works with mp3 and flac**, as can be seen at https://github.com/Homebrew/homebrew-core/blob/master/Formula/sdl2_mixer.rb.

This package should be installed with an alternative brew formula + options, for example

brew install --with-mpg123 --with-flac --with-libmikmod --with-fluid-synth https://raw.githubusercontent.com/Homebrew/homebrew-core/a9114e/Formula/sdl2_mixer.rb

I think this needs be mentioned in the wiki. 
Caveat: The older formula might not work with Catalina?

**Comment by fabiangreffrath** [comment]
What exactly do you sugest should be mentioned in the Wiki?

**Comment by icecreamoverlord** [comment]
For mp3 & flac sound support, `brew sdl2_mixer` (homebrew's current way of installing the sdl2_mixer package) will not work.
Instead, install sdl2_mixer with `brew install --with-flac --with-mpg123 https://raw.githubusercontent.com/Homebrew/homebrew-core/a9114e/Formula/sdl2_mixer.rb` (or some alternative brew formula).

**Comment by fabiangreffrath** [comment]
Okay, I have updated the Wiki with your comments, thanks!
