### ISSUE TITLE
MAP33 name bug on the Automap?

### ISSUE THREAD

**Issue by quakeguy123** [fabiangreffrath/crispy-doom#61]
Hello,

To be honest i'm not sure if this is a bug in Crispy Doom or if that's considered normal behavior with Vanilla Doom.

Whenever i got to MAP33 the name of that map is displayed on the Automap as Level 1: Congo, that also happens in chocolate Doom with "Doom 2 the Way id Did"  Megawad.

Will that be fixed? It's minor, i  know.

**Comment by fabiangreffrath** [comment]
Hi there,

thank you very much for your bug report.

In Vanilla Doom there was no MAP33 and thus there was no name for this map hard-coded into the engine. That is, whenever a MAP33 was entered, the Automap would display the name of the "next best" map that was in the list of maps and that was "Level 1: Congo" of Plutonia. The only "official" IWAD that features 33 maps is DOOM2.WAD of the Doom 3 BFG Edition, and Chocolate Doom has a check to detect it and change the name of the first Plutonia map into "Level 33: Betray" then by means of Dehacked.

I could change the map name to read "Level 33: Betray" solely based on the presence of a MAP33 and independently of the IWAD being the BFG Edition DOOM2.WAD, is this what you mean?

**Comment by quakeguy123** [comment]
Hello,

I understand. 

"I could change the map name to read "Level 33: Betray" solely based on the presence of a MAP33 and independently of the IWAD being the BFG Edition DOOM2.WAD, is this what you mean?"

Yes that's exactly what i mean! Thank you for this great Source Port, it's just what i was looking for!

**Comment by fabiangreffrath** [comment]
> Thank you for this great Source Port, it's just what i was looking for!

Feels good to read that, thank you!
