### ISSUE TITLE
SHOWFPS & IDRATE cheat code don't work

### ISSUE THREAD

**Issue by skyrain128** [fabiangreffrath/crispy-doom#610]
### Background

Version of Crispy Doom: 5.8.0

Operating System and version: Windows 10 v.1903 x64

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line):
vsmooth.wad, pk_doom_sfx_20120224.wad, D1SPFX19.wad

This bug appears when no PWADs loaded, too.

### Bug description

Observed behavior: SHOWFPS & IDRATE cheat code don't work

Expected behavior:

**Comment by fabiangreffrath** [comment]
It works if you use the "narrow" widescreen HUD. Fixed in https://github.com/fabiangreffrath/crispy-doom/commit/6d9ef13f8c7b68e37dca1fc74da49060c03b7bd6
