### ISSUE TITLE
[Feature Proposal] Crispness option to use Heretic's automap line drawing in Doom

### ISSUE THREAD

**Issue by zx64** [fabiangreffrath/crispy-doom#611]
I recently noticed that Heretic draws its automap using ![Wu's line algorithm](https://en.wikipedia.org/wiki/Xiaolin_Wu%27s_line_algorithm) to get slightly smoother lines and wanted to see how it might look in Doom.

I've made a quick attempt at implementing it and it looks like this:
With extended colours: ![extended](https://i.gyazo.com/fcbe14f472d640b90ec8c73d384e8b90.png)
With default colours: ![default](https://i.gyazo.com/8e9960fd107cb60a4498ac61d76acd55.png)
In overlay mode: ![extoverlay](https://i.gyazo.com/4fa9ed77f1ce204524ea8036e963311c.png) ![defoverlay](https://i.gyazo.com/ade08096d1580cbbd816b6e264bb709a.png)
and with the feature disabled for comparison: ![disabled](https://i.gyazo.com/26955347069437bf834184bfc1cb6217.png)
Crispness menu entry: ![crispness](https://i.gyazo.com/69332edf779a8e2f692e58bb7f4009b6.png)

Is this something you'd like as a PR for code review etc.?

**Comment by fabiangreffrath** [comment]
It depends on how invasive this change is.  But if you already have the code prepared, just file the PR. If we could get away e.g. with a code pointer, that would be easy to merge.

**Comment by zx64** [comment]
Done! :-)
