### ISSUE TITLE
Flashing key doors on automap

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#613]
Hi fabian, what do you think of this? (The uneven flash duration is just because I made it with a quick screen capture, and I only applied it to yellow doors here.)

![Peek 2020-05-13 07-07](https://user-images.githubusercontent.com/47063032/81805395-c5cb9b00-94e8-11ea-89aa-742d60e37326.gif)

I've realized I really prefer the standard automap colours, but having things like coloured key doors is really useful. So this is what I came up with as a way to indicate them on the map. It's also nice if you have a complex map with a lot of visible linedefs.

I know you won't want to introduce switches for multiple extended map colours options, so I thought I'd ask a) whether you like this idea, and b) if so, whether you'd be open to restoring some of the default colours for Crispy's extended automap colours. (I will likely patch my own version of Crispy if this feature does not appeal to you.)

**Comment by fabiangreffrath** [comment]
I like this idea in general. However, we already have colored lines for keyed doors in the Extended Automap Colors mode and if I'll let them flash in classic mode then Vanilla purists will complain. What color scheme exactly would you like to suggest to apply?

**Comment by kitchen-ace** [comment]
My "ideal" colour configuration, i.e. the one I would make for myself if you rejected this entirely, would be to revert WALLCOLORS / CDWALLCOLORS / FDWALLCOLORS back to red/brown/yellow respectively, leave all the other enhancements like secret sectors, and then use flashing to differentiate the key doors from normal linedefs. 

I suppose it's largely nostalgia, but I do find the solid red better for normal walls at least since it's a more saturated colour. 

I'll make a PR with the flashing only for now, and we can go from there.
