### ISSUE TITLE
Installing Crispy Doom

### ISSUE THREAD

**Issue by mrjoe2004** [fabiangreffrath/crispy-doom#619]
### Background

Version of Crispy Doom: Either 5.6.4, 5.7.2, or 5.8.0

Operating System and version: Windows 10

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line): None

### Bug description

Observed behavior: I'm just trying to install Crispy Doom, but each time I unzip the folder i download of whichever version I download, there's a virus my virus protection program (McAfee) catches and deletes the crispy-doom.exe itself. I wouldn't think there should be a virus, but maybe there's something else I'm not understanding. I don't have much knowledge on computer programming and stuff so anything would be helpful

Expected behavior: Be able to install crispy doom

**Comment by tpoppins** [comment]
That's a false positive. Some anti-virus programs are over-zealous and McAfee doesn't have a good reputation in that respect.

Here's my own version of the latest daily build of crispy-doom.exe that [passes](https://www.virustotal.com/gui/file/a2ffdce14d7495f9605183b360e2ad4364c222a1869b336612ca2e7776b319dc/detection) virustotal.com's check (72 anti-virus programs) without a single positive:
[crispy-doom-2020-05-23-tp.zip](https://github.com/fabiangreffrath/crispy-doom/files/4671267/crispy-doom-2020-05-23-tp.zip)

To save yourself the headache in the future you may want to go into McAfee's setup and add crispy-doom.exe as an exception.

**Comment by fabiangreffrath** [comment]
Nothing more to add, thanks!
