### ISSUE TITLE
Pause Menu is too dark by defualt

### ISSUE THREAD

**Issue by quakeguy123** [fabiangreffrath/crispy-doom#62]
Hello again,

I noticed that  the Pause Menu is by default darker in Crispy Doom then in Chocolate doom.
Here are some comparison screen shots:

Crispy Doom:
![doom 2 pause menu crispy doom 2 3 windowed mode](https://cloud.githubusercontent.com/assets/3495467/7863074/67b1131a-055a-11e5-874f-33b7e6e6ca0e.png)

Chocolate Doom:
![doom 2 pause menu chocolate doom 2 1 0 windowed mode](https://cloud.githubusercontent.com/assets/3495467/7863104/942456f0-055a-11e5-840e-c59e07c7eba3.png)

I have not touched any settings besides display resolution and keyboard and mouse setup, this happens on all other wads (Doom, Final doom, etc...)

While i'm on the subject i wanted to ask if it will be possible to support official Doom 2 Master Levels wad form the Doom Classic Complete Collection on the PS3. It's Called "MASTERLEVELS.WAD". http://doomwiki.org/wiki/MASTERLEVELS.WAD I have read that Zdoom doesn't support it. I can't confirm that.

**Comment by fabiangreffrath** [comment]
> I noticed that the Pause Menu is by default darker in Crispy Doom then in Chocolate doom.

Erm, this is considered a feature of Crispy Doom and is meant to improve legibility of the menus. If you look at the Chocolate Doom screenshot, the red letters of the menu and of the status bar mix up easily. Especially with the options menu rendered in the smaller HUD font, I think it is necessary to provide a "background" for the menu. Also, if you look carefully, the background even fades to dark slowly (this is currently broken in the GIT using uncapped framerate but will be fixed shortly).

> While i'm on the subject i want [...]

Sorry, but this is not "the subject". Please file one issue on the tracker for each request, else we risk losing track of them.

**Comment by quakeguy123** [comment]
OK i understand what you mean with the darker Pause Menu. Thank you for the explanation!
I'm sorry, my mistake.

**Comment by fabiangreffrath** [comment]
Would you please file another request about adding support for the masterlevels.wad, please, so we can continue the discussion there?

I assume this issue can get closed? Are you using the GIT version or the latest 2.3 release, BTW?

**Comment by quakeguy123** [comment]
Yes, sorry i was away. You may close the issue. I'm using the latest 2.3 Release.

**Comment by fabiangreffrath** [comment]
Alright, thank you! At least this report pointed me to a bug in the fading algorithm that was introduced with merging uncapped framerate. It is closed in https://github.com/fabiangreffrath/crispy-doom/commit/9eb1c071723c48923b2b59cdadbf64d55b79ef64
