### ISSUE TITLE
Distribute as Flatpak

### ISSUE THREAD

**Issue by davidarnold** [fabiangreffrath/crispy-doom#622]
Hi!  I have Crispy built and running as a Flatpak locally.  I am volunteering to be the package maintainer for the official Flathub repo.

They typically want the author to be the maintainer, so I'd only do it with an official blessing.  If you'd rather package it yourself, I can provide the manifest JSON file that I have so far.  Happy to help however I can.

Thanks!

**Comment by fabiangreffrath** [comment]
Feel free to distribute Crispy Doom in whatever format you prefer, you've got my blessings.
