### ISSUE TITLE
A few suggestions I’d love to see added

### ISSUE THREAD

**Issue by snoggie1487** [fabiangreffrath/crispy-doom#623]
I have a few suggestions for Crispy Doom that I think would compliment everything else in it nicely.

1: Split colored blood sprites and colored marine corpses into separate options.
2: Add a crispness option for GZDoom-like rocket particle trails
3: Allow for collection of multiple computer-area-maps so that it is possible to get 100% items on maps that have multiple. (I know there’s at least one map in Doom 2 like that)
4: Add a crispness option for respawning at your most recent save instead of at the beginning of the level. (With all your weapons, equipment, health, etc.. how they were when you saved)
5: Allow switching to fists after picking up the chainsaw without having a berserk pack by pressing 1 twice.
6: On levels that do not have any secrets, items, or monsters, register that category as 100% on the ends screen instead of 0%
7: Add an option to save screenshots in a separate folder.
8: Revert back to the 5.6.1 midiproc to fix the issue with music volume being tied to SFX volume. (That issue came up only after updating midiproc in 5.6.2)

Thank you for reading my suggestions, and I hope you consider them.

**Comment by fabiangreffrath** [comment]
Hi, thanks for your suggestions!

> 1: Split colored blood sprites and colored marine corpses into separate options.

This would be another switch in the menu. 

You know, I absolutely hate micro-management and thus like to combine similar features in one switch. Also, I prefer reasonable defaults over choices for everything. What I want to avoid is a multiple-level menu puzzle where users have the ability to adjust every minor part of the engine but get lost in the course of it. :wink:

> 2: Add a crispness option for GZDoom-like rocket particle trails

No switch for the same reason as above. Also, I don't see any value in adding this questionable feature. For Revenants, a smoke trail behind a rocket means that it's following its target. For player rockets this is never possible, so why should we add this and break the metaphor?

> 3: Allow for collection of multiple computer-area-maps so that it is possible to get 100% items on maps that have multiple. (I know there’s at least one map in Doom 2 like that)

This would change the map statistics at the tally screen and would thus qualify as breaking demo playback.

> 4: Add a crispness option for respawning at your most recent save instead of at the beginning of the level. (With all your weapons, equipment, health, etc.. how they were when you saved)

Try holding the "run" button during resurrection. 😉 

> 5: Allow switching to fists after picking up the chainsaw without having a berserk pack by pressing 1 twice.

This would break demo and network compatibility.

> 6: On levels that do not have any secrets, items, or monsters, register that category as 100% on the ends screen instead of 0%

Same as above, we need to end maps with the exact same statistics as Vanilla Doom for demo compatibility.

> 7: Add an option to save screenshots in a separate folder.

This is probably something that should get implemented upstream in Chocolate Doom. That being said, isn't there already a command line option for this?

> 8: Revert back to the 5.6.1 midiproc to fix the issue with music volume being tied to SFX volume. (That issue came up only after updating midiproc in 5.6.2)

I cannot remember any changes between these two revisions that would affect midiproc?

**Comment by snoggie1487** [comment]
> > 7: Add an option to save screenshots in a separate folder.
> 
> This is probably something that should get implemented upstream in Chocolate Doom. That being said, isn't there already a command line option for this?

I can't figure our how to open the console, would you please enlighten me?
