### ISSUE TITLE
Windows Binary detected as Trojan

### ISSUE THREAD

**Issue by FlappyHands** [fabiangreffrath/crispy-doom#628]
Windows 10 Security immediately flagged the download as Trojan:Script/Woreflint.A!cl when I downloaded it. I am assuming this is a false positive, but why is it flagging it?

Version of Crispy Doom: 5.7.2

Operating System and version: Win10

**Comment by tpoppins** [comment]
Yes, it's a false positive. 

Release builds are cross-compiled on non-Windows platforms (Mac and/or Linux), according to the developer; so the chances of them to be infected with Windows-centric malware are practically nil.

User reports about anti-virus programs flagging Crispy downloads as malware [started](https://www.doomworld.com/forum/topic/67168-crispy-doom-580-update-apr-17-2020/?do=findComment&comment=2100331) around the time of this same v5.7.2 release, mostly from MS Defender on Win10 and McAfee users. For my part I never had such issues with Crispy (or its parent, Chocolate) downloads -- MS Defender on Win 7 x64 Pro, updated daily -- although I usually build from source myself.

It is still not clear what it is that triggers these false positives, but it's worth pointing out that according to VirusTotal only a small proportion (under 20%) of the 60+ anti-malware engines they employ report detections. And of those the only ones of any repute are McAfee and apparently certain versions of MS Defender/Security Essentials. I've submitted for analysis various Crispy release archives and individual execs over the past three months, and none of the most prominent AVs like Avast, AVG, Bitdefender, Comodo, Eset, FProt, Kaspersky, Symantec and Trend Micro find anything wrong with them.

The only discordant note is MS AVs. I have a MS account, so I submitted the latest Crispy release build archive (v5.8.0) to Microsoft Defender ATP team for analysis. Perhaps they'll be able to throw some light on what causes all these false positives.


In the meantime here's my own build of the latest Crispy code (as of commit 08ab7a3, June 9), built with MSYS2/GCC 10.1.0:  [crispy-doom-20200609-w32.zip](https://github.com/fabiangreffrath/crispy-doom/files/4771230/crispy-doom-20200609-w32.zip)

And here are VirusTotal reports on each of the execs included in the ZIP:
[crispy-doom.exe](https://www.virustotal.com/gui/file/c85c13fdf2e9f6a8cceb03f93eac562dcf3ea8e99ca5aa72567e7a546adb1ec6/detection) - 0/73
[crispy-setup.exe](https://www.virustotal.com/gui/file/8c413dbdbeaa24ce06a1fe928f4d578d1da576712ed96bdbf91d254ba172aa9e/detection) - 1/73
[crispy-midiproc.exe](https://www.virustotal.com/gui/file/8f16ba4fcb30330fdf552b3963abbbe312eb15645ab544688803a0c96e102aa3/detection) - 2/73

Not even McAfee could find anything to complain about. :)

HTH

**Comment by fabiangreffrath** [comment]
Nothing to add @tpoppins , thank you for the impressive elaboration. Would you like to boil it down to a few sentences so we can add it as a Wiki article?

**Comment by tpoppins** [comment]
I'm waiting for a reply from MS, perhaps we'll have some definite info on our hands.

**Comment by tpoppins** [comment]
The submission page was updated some days ago with a "we removed the detection" statement. Nothing specific as to what caused the detection in the first place. It's not clear whether the detection removed refers to a heuristics routine or merely to the specific ZIP and the files within. 

I'm not good at writing digests but would be happy to edit your take on it, Fabian. :)

**Comment by Kezxo** [comment]
Just had this happen with version 5.7.1 that I had left unzipped on my desktop. I'm using Windows Defender for Windows 10, Security intelligence version 1.321.403.0 
I reported the setup and midi files to Microsoft as a false positive.

Virustotal reports:
[crispy-doom-5.7.1-win32.zip](https://www.virustotal.com/gui/file/4fb6f773edfb9522d98560ab0cfabb24f35268737a441a8825deebf63f72a317) - 24/63
[crispy-doom-setup.exe](https://www.virustotal.com/gui/file/4c83394e4611192c6084a351e2032177c489eacb28e5c32c3167f293be7b333d) - 17/ 72
[crispy-midiproc.exe](https://www.virustotal.com/gui/file/299e052dd28f79d5a7090610957059467d1c01ef5bba7ef05baa4a60e53832fa) - 18/ 72
[crispy-doom.exe](https://www.virustotal.com/gui/file/53ad30f82c5fdf368ec05c34fd8e6e6d9015ddd77e0edf06cc0a61d48f500906) - 15/72 (Microsoft didn't detect this one)

Here are scans by hybrid analysis:
[crispy-doom-setup.exe](https://www.hybrid-analysis.com/sample/4c83394e4611192c6084a351e2032177c489eacb28e5c32c3167f293be7b333d/5f26d6a395b2446f3e6d6665)
[crispy-midiproc.exe](https://www.hybrid-analysis.com/sample/299e052dd28f79d5a7090610957059467d1c01ef5bba7ef05baa4a60e53832fa/5e640b36a8228733a4760c18)
[crispy-doom.exe](https://www.hybrid-analysis.com/sample/53ad30f82c5fdf368ec05c34fd8e6e6d9015ddd77e0edf06cc0a61d48f500906/5f26e1214d7d8969713f5d31)

**Comment by corcovatus** [comment]
Virus notifications seem to start at v.5.4

5.3 Has no positives: [VirusTotal](https://www.virustotal.com/gui/file/431f156f0300eefdbf81ac939cc05928e613616a0cd124444c1ce4bbdbe5f6ab/detection)

5.4 - 2 Detections: [VirusTotal](https://www.virustotal.com/gui/file/376d1ec4883fa5d8db9f8a5a03ee5aec70ef15c38114e3b435c107a8f3490c7a/detection)

5.5.2 -  2 Detections: [VirusTotal](https://www.virustotal.com/gui/file/78c759d4a146db6b2240c37ed27ced43f1b1719fbbfbd0120a99b2ef3bb52bf1/detection)

5.6.4 - **14 Detections:** [VirusTotal](https://www.virustotal.com/gui/file/db751abd98b8062849c55e65cbbba50ebdf1f3e6b104a0d7aaa2966357b97939/detection)

**Comment by Asais10** [comment]
Windows defender seems to not like Crispy very much, just add an exclusion. 

The latest version (as of this writing, 5.9.2) of Crispy Heretic (crispyheretic.exe, to be precise) is picked up by Defender as Trojan:Win32/Wacatac.D1!ml (silly malware names).

**Comment by fabiangreffrath** [comment]
Probably nothing I can change about this. However, there is a comment now on the http://latest.chocolate-doom.org/ page.
