### ISSUE TITLE
Disk icon showing one pixel of black background

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#630]
Disk icon showing one pixel of black background. Don't be confused about screenshots quality, they are taken from video record.

![image](https://user-images.githubusercontent.com/21193394/84569779-9632db80-ad91-11ea-8d56-7d36269e4e64.png)

It is almost impossible to see it normally, because disk icon is flashing too fast, so you may wish to add some delay into `I_FinishUpdate`, just like this:
```
void I_FinishUpdate (void)
{
    static int lasttic;
    int tics;
    int i;

+++ I_Sleep(500);

    if (!initialized)
        return;
```
_________

To fix it, we need to do two steps:

1) Reduce `LOADING_DISK_H` to `(15 << hires)` in v_diskicon.h, because disk icon is 15 pixels tall:
![image](https://user-images.githubusercontent.com/21193394/84569844-0ccfd900-ad92-11ea-9339-2ec218cb693e.png)

2) Correct vertical offset of gfx patch, because it have `-1` offset in IWAD (see screenshot above) at `SaveDiskData` in v_diskicon.c:
```
    // Draw the patch and save the result to disk_data.
    disk = W_CacheLumpName(disk_lump, PU_STATIC);
---    V_DrawPatch((loading_disk_xoffs >> crispy->hires) - WIDESCREENDELTA, loading_disk_yoffs >> crispy->hires, disk);
+++    V_DrawPatch((loading_disk_xoffs >> crispy->hires) - WIDESCREENDELTA, (loading_disk_yoffs-1) >> crispy->hires, disk);
```

Ta-da:
![image](https://user-images.githubusercontent.com/21193394/84569938-c038cd80-ad92-11ea-8d76-fab97b9b5fa3.png)

P.S. CD-ROM icon in 15x15 pixels.. :unamused:

_Suggestion №115_

**Comment by JNechaevsky** [comment]
I've made some progress here, looks likes disk drawing function can be simplified, as well as it may use proper transparent background. In short words: we don't need to read/write disk background data, we can just draw disk icon normally and do `ST_doRefresh` if necessary. But I need to do some more work before showing a working approach.

**Comment by JNechaevsky** [comment]
Here, a quick example. I'm using `updated!` print just to make sure that status bar is updated only when necessary, but not in every tic.
![Sequence 01 Still001](https://user-images.githubusercontent.com/21193394/87871537-a6a22b80-c9b9-11ea-8763-42a47390db12.png)

**Comment by fabiangreffrath** [comment]
Please remember that the loading disc icon is a Chocolate feature, so any code change that you are going to suggest here should ideally go through Choco first.

**Comment by JNechaevsky** [comment]
I know, and that's why I can't suggest for Chocolate. Here, have a look, I've made it: https://github.com/JNechaevsky/russian-doom/commit/fb8e3fad6de76a7c6e6e82d11ad4f0f8ceff56c9

This is far different way from how disk icon works in vanilla Doom. Instead of reading-keeping-writing back some data into memory, I'm drawing disk icon by common `V_DrawPatch` and making a full status bar update when it's necessary. It's simplifies disk drawing functions _a lot_, but requires a little bit more CPU power by making a full STBAR update (which we are already doing while active and overlayed automap). Also, it allows to have disk icon of any size, just like this:

![image](https://user-images.githubusercontent.com/21193394/87876833-37413180-c9e3-11ea-8a39-712772b46801.png)

So, real problem with disk icon in Chocolate is - background is reading incorrectly, it's using black color instead of transparency. I was not lucky to fix it.

**Comment by fabiangreffrath** [comment]
I think we have been there before, but then @fragglet refactored the code to how it is today, so there is little chance of this getting reverted to a different implementation again. 

https://github.com/chocolate-doom/chocolate-doom/commit/7a29515569b6543c31b1fc0b2ef4875ab75708b6#diff-1ff13a098b44596141cfa55a38e5d1ac

**Comment by JNechaevsky** [comment]
Ouch, quite a long time! I see. What should we do then, close this issue as too different from Chocolate approach, and/or start issue regarding missing icon transparency in Chocolate tracker?

**Comment by fabiangreffrath** [comment]
Would be interesting to know what Vanilla did here. On the other hand, it is such an obscure feature that I believe we have already invested too much energy on it. It works withing its merits and I am okay with it.

**Comment by JNechaevsky** [comment]
Excuse me, I haven't checked DOS executable. Yes, having a black background is a vanilla behavior:

![Sequence 01 Still002](https://user-images.githubusercontent.com/21193394/87944654-5950b780-caa8-11ea-8a42-c77c05215b76.png)

In case you are wondering about how it works in DOS version, have a look: https://github.com/JNechaevsky/russian-doom/blob/master/src_dos/i_ibm.c#L1324 (and below).

Guess we are really done here for now:
* It's a vanilla behavior and should not be changed in Chocolate Doom.
* My approach is far different and should not be applied because of code difference.
