### ISSUE TITLE
Optional demo progress bar

### ISSUE THREAD

**Issue by fx02** [fabiangreffrath/crispy-doom#64]
As I like uncapped FPS I'm using crispy for recording video demos now, but progress bar is something I don't want in my videos so I suggest to make it optional via config file.

**Comment by fabiangreffrath** [comment]
Hm, in fact I have just made it a bit thicker in one of the recent commits. After all, it's just 3 pixels high and I really find it helpful to know where I am in a demo. Like the time line in Video players.

**Comment by fabiangreffrath** [comment]
That said, I am proud and glaf that you use Crispy Doom for demo recording. The port could use a lot more testing (and actual usage, that is) for demo compatibility. ;)

Please, note, however, that you need to apply the SlopeDiv fix that I committed lately. It fixes the only one desync among the thousands of Compet-N demos that I found by running @fragglet's statcheck utility.

Also, for playback of multi-level demos you might like the "-playdemo x -warp y" feature that I recently added.

**Comment by fabiangreffrath** [comment]
I'll reduce the progress bar height back to 2px once hardware scaling is in place. Please beat me to it, should I forget about it. ;)

**Comment by Zodomaniac** [comment]
Progress bar can already be disabled via Crispness-Demos menu section.
