### ISSUE TITLE
Map panning sometimes jerky 

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#641]
### Background

Version of Crispy Doom: 5.8.0+

Operating System and version: Arch Linux 64-bit

Game: Doom

I use the numeric keypad to pan the automap with follow mode off (which registers as UP/DOWN/LEFT/RIGHT). Often, especially on a large map, it stops scrolling smoothly and moves jerkily: there's a kind of repeat delay when holding down a key, and you can't use two directions (e.g. up and right) at once. 

This doesn't happen in Chocolate Doom at all. Using other keys for map panning doesn't have this same issue, as far as I can tell. Unmapping the directional keys from other functions such as moving maybe makes it happen less, but definitely doesn't resolve the problem.

This has been a problem for a while, but I've held off reporting it because I don't know how to reproduce it properly at all. It seems to happen more often on large maps, but not always. Using two directions at once makes it more likely to happen, I think. After the panning becomes jerky, it usually doesn't go back to normal on its own, but toggling some rendering options sometimes resets it, or just exiting the game. I can't find any other settings that prevent it from going jerky.

Attached are my cfg files, in case it matters.

[crispy-doom.cfg.txt](https://github.com/fabiangreffrath/crispy-doom/files/4970204/crispy-doom.cfg.txt)
[default.cfg.txt](https://github.com/fabiangreffrath/crispy-doom/files/4970205/default.cfg.txt)

**Comment by fabiangreffrath** [comment]
Wow, this is a bit unspecific, but thanks anyway! Well, Crispy's Automap code is a bit pimped compared to Choco's, so the cause could be anywhere. What comes to mind, though, is the ability to move the map with the mouse if followmode is off. Does this make a difference?

**Comment by kitchen-ace** [comment]
Ah ha! Good thinking. Moving the mouse with follow mode off does indeed cause the jerkiness to happen immediately. It resets when follow mode is toggled. This also explains the randomness in it occuring: I use a trackball that has occasional drift, and so it's likely that the drift was causing sporadic jerkiness.

**Comment by fabiangreffrath** [comment]
Could you please check if this fixes your issue?

```
--- a/src/doom/am_map.c
+++ b/src/doom/am_map.c
@@ -773,8 +773,11 @@ AM_Responder
                // [crispy] mouse sensitivity for strafe
                m_paninc.x = FTOM(ev->data2*(mouseSensitivity_x2+5)/80);
                m_paninc.y = FTOM(ev->data3*(mouseSensitivity_x2+5)/80);
-               f_oldloc.y = INT_MAX;
-               rc = true;
+               if (m_paninc.x || m_paninc.y)
+               {
+                       f_oldloc.y = INT_MAX;
+                       rc = true;
+               }
        }
     }
     else if (ev->type == ev_keydown)

```

**Comment by kitchen-ace** [comment]
Unfortunately not.

**Comment by fabiangreffrath** [comment]
Hm, then your mouse drift leads to actual panning, which of course I don't want to suppress. I need a way to see if both mouse and keyboard add to panning and then suppress the former.

**Comment by fabiangreffrath** [comment]
Okay, how about this (this is suppoed to give keyboard input precedence):

```
--- a/src/doom/am_map.c
+++ b/src/doom/am_map.c
@@ -751,32 +751,6 @@ AM_Responder
            rc = true;
        }
     }
-    // [crispy] zoom and move Automap with the mouse (wheel)
-    else if (ev->type == ev_mouse && !crispy->automapoverlay && !menuactive && !inhelpscreens)
-    {
-       if (mousebprevweapon >= 0 && ev->data1 & (1 << mousebprevweapon))
-       {
-               mtof_zoommul = M2_ZOOMOUT;
-               ftom_zoommul = M2_ZOOMIN;
-               rc = true;
-       }
-       else
-       if (mousebnextweapon >= 0 && ev->data1 & (1 << mousebnextweapon))
-       {
-               mtof_zoommul = M2_ZOOMIN;
-               ftom_zoommul = M2_ZOOMOUT;
-               rc = true;
-       }
-       else
-       if (!followplayer && (ev->data2 || ev->data3))
-       {
-               // [crispy] mouse sensitivity for strafe
-               m_paninc.x = FTOM(ev->data2*(mouseSensitivity_x2+5)/80);
-               m_paninc.y = FTOM(ev->data3*(mouseSensitivity_x2+5)/80);
-               f_oldloc.y = INT_MAX;
-               rc = true;
-       }
-    }
     else if (ev->type == ev_keydown)
     {
        rc = true;
@@ -917,6 +891,35 @@ AM_Responder
             ftom_zoommul = FRACUNIT;
         }
     }
+    // [crispy] zoom and move Automap with the mouse (wheel)
+    else if (ev->type == ev_mouse && !crispy->automapoverlay && !menuactive && !inhelpscreens)
+    {
+       if (mousebprevweapon >= 0 && ev->data1 & (1 << mousebprevweapon))
+       {
+               mtof_zoommul = M2_ZOOMOUT;
+               ftom_zoommul = M2_ZOOMIN;
+               rc = true;
+       }
+       else
+       if (mousebnextweapon >= 0 && ev->data1 & (1 << mousebnextweapon))
+       {
+               mtof_zoommul = M2_ZOOMIN;
+               ftom_zoommul = M2_ZOOMOUT;
+               rc = true;
+       }
+       else
+       if (!followplayer && (ev->data2 || ev->data3))
+       {
+               // [crispy] mouse sensitivity for strafe
+               m_paninc.x = FTOM(ev->data2*(mouseSensitivity_x2+5)/80);
+               m_paninc.y = FTOM(ev->data3*(mouseSensitivity_x2+5)/80);
+               if (m_paninc.x || m_paninc.y)
+               {
+                       f_oldloc.y = INT_MAX;
+                       rc = true;
+               }
+       }
+    }

     return rc;

```

**Comment by kitchen-ace** [comment]
Doesn't seem like it, either. (Also `patch` didn't like this patch file for some reason, so I just moved that code block myself. There weren't any added/changed lines, other than relocating the position of that code, right?)

To be clear: as soon as there's any mouse movement when follow mode is off, whether caused by drift or not, panning with the keyboard becomes jerky until follow is toggled on and off again.

**Comment by kitchen-ace** [comment]
Also, as I would expect, commenting out [this block](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/am_map.c#L770) to disable mouse panning means that the mouse won't send the keyboard into jerky mode. I'll use this as temporary fix, it's good enough for me since I never pan with the mouse.

**Comment by fabiangreffrath** [comment]
But this us is just a workaround, not a actual fix. 
I guess I'll have to introduce a motion threshold below which mouse input is ignored.

**Comment by kitchen-ace** [comment]
>I guess I'll have to introduce a motion threshold below which mouse input is ignored.

Unless I misunderstand, that's just trying to correct for mouse drift, right? In which case I think that's just another workaround. 

The underlying issue is that panning with the mouse somehow "corrupts" keyboard panning. (At least on my system -- I'll try to check on some other computers today.)

**Comment by kitchen-ace** [comment]
What is this block actually doing?

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/am_map.c#L483

If I comment it out, keyboard panning behaves as normal even after moving the mouse.

**Comment by fabiangreffrath** [comment]
> What is this block actually doing?
> 
> https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/am_map.c#L483-L488
> 
> If I comment it out, keyboard panning behaves as normal even after moving the mouse.

It's there because there is no way to tell that you have stopped moving the mouse - it's missing a pendant to the `ev->type == ev_keyup` block in `AM_Responder()`. So, once moved, the `m_paninc` values would never get reset.

However, I think I have come up with a better solution. How about this?

```
diff --git a/src/doom/am_map.c b/src/doom/am_map.c
index 0c57d819..0238f5ed 100644
--- a/src/doom/am_map.c
+++ b/src/doom/am_map.c
@@ -241,7 +241,7 @@ static int 	lightlev; 		// used for funky strobing effect
 //static pixel_t*	fb; 			// pseudo-frame buffer
 static int 	amclock;
 
-static mpoint_t m_paninc; // how far the window pans each tic (map coords)
+static mpoint_t m_paninc, m_paninc2; // how far the window pans each tic (map coords)
 static fixed_t 	mtof_zoommul; // how far the window zooms in each tic (map coords)
 static fixed_t 	ftom_zoommul; // how far the window zooms in each tic (fb coords)
 
@@ -452,14 +452,14 @@ void AM_changeWindowLoc(void)
 {
     int64_t incx, incy;
 
-    if (m_paninc.x || m_paninc.y)
+    if (m_paninc.x || m_paninc.y || m_paninc2.x || m_paninc2.y)
     {
 	followplayer = 0;
 	f_oldloc.x = INT_MAX;
     }
 
-    incx = m_paninc.x;
-    incy = m_paninc.y;
+    incx = m_paninc.x + m_paninc2.x;
+    incy = m_paninc.y + m_paninc2.y;
     if (crispy->automaprotate)
     {
 	AM_rotate(&incx, &incy, -mapangle);
@@ -481,11 +481,7 @@ void AM_changeWindowLoc(void)
     m_y2 = m_y + m_h;
 
     // [crispy] reset after moving with the mouse
-    if (f_oldloc.y == INT_MAX)
-    {
-	m_paninc.x = 0;
-	m_paninc.y = 0;
-    }
+    m_paninc2.x = m_paninc2.y = 0;
 }
 
 
@@ -504,7 +500,7 @@ void AM_initVariables(void)
     amclock = 0;
     lightlev = 0;
 
-    m_paninc.x = m_paninc.y = 0;
+    m_paninc.x = m_paninc.y = m_paninc2.x = m_paninc2.y = 0;
     ftom_zoommul = FRACUNIT;
     mtof_zoommul = FRACUNIT;
 
@@ -771,9 +767,8 @@ AM_Responder
 	if (!followplayer && (ev->data2 || ev->data3))
 	{
 		// [crispy] mouse sensitivity for strafe
-		m_paninc.x = FTOM(ev->data2*(mouseSensitivity_x2+5)/80);
-		m_paninc.y = FTOM(ev->data3*(mouseSensitivity_x2+5)/80);
-		f_oldloc.y = INT_MAX;
+		m_paninc2.x = FTOM(ev->data2*(mouseSensitivity_x2+5)/80);
+		m_paninc2.y = FTOM(ev->data3*(mouseSensitivity_x2+5)/80);
 		rc = true;
 	}
     }
@@ -1013,7 +1008,7 @@ void AM_Ticker (void)
 	AM_changeWindowScale();
 
     // Change x,y location
-    if (m_paninc.x || m_paninc.y)
+    if (m_paninc.x || m_paninc.y || m_paninc2.x || m_paninc2.y)
 	AM_changeWindowLoc();
 
     // Update light level
```

**Comment by kitchen-ace** [comment]
Works great, thanks!
