### ISSUE TITLE
Add Heretic save game extensions

### ISSUE THREAD

**Issue by kraflab** [fabiangreffrath/crispy-doom#648]
This is a followup to the total level time tracking added to crispy heretic.

On the crispy doom side there is a system of save file extensions implemented to account for new data, which is currently missing on the heretic side.

As a result: if the player loads a save file, it won't restore the total level time, which means the total time for a loaded playthrough won't be correct on the intermission screen.

We should set up a similar system on the heretic side to account for these kinds of things.

Here is an entry point to the related logic on the doom side: https://github.com/fabiangreffrath/crispy-doom/blob/fb3dd9d2b6745e198c2c71209b2f2eae77f2425f/src/doom/p_extsaveg.c#L98-L116

I don't know how long it will be until I get to this topic, so I figured I will set up an issue to track it in case someone wants to jump on it.

**Comment by fabiangreffrath** [comment]
We could adapt this code pretty much 1:1 from Crispy Doom and keep only the "modules" that are actually necessary.

**Comment by kraflab** [comment]
Cleaning up (closing) some old issues
