### ISSUE TITLE
Missing "s" character in FPS counter

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#649]
In case of having extremely high FPS, "s" character may disappear in the right side of the screen:
![image](https://user-images.githubusercontent.com/21193394/90175034-83e41680-ddaf-11ea-9128-51e0bfd24d7d.png)

**Solution**

Just move FPS counter slightly left. To make sure it's perfectly positioned, simply print static "8888 fps" in counter for testing. You may also wish to cap counter to 9999 fps for preventing counter going out of screen bound in case of having 9999+ frames.

P.S. It's not a `timedemo` run, just testing performance on my new PC. I wonder how high framerate can be in case of having multicore CPU and GPU optimizations. Probably astronomical, but both of these will require much extra job to do.

**Comment by fabiangreffrath** [comment]
How much would I have to change the `HU_COORDX` value?

**Comment by JNechaevsky** [comment]
Changing `7` to `8` seems to be good enough for all possible four `NNNN` fps:
![image](https://user-images.githubusercontent.com/21193394/90177259-f5719400-ddb2-11ea-9a79-b70c6b9ced1b.png)
_(`0` character as well as `8` seems to be widest)_

However, just for future, using a `9` seems to enough for five `NNNNN` fps:
![image](https://user-images.githubusercontent.com/21193394/90177801-bd1e8580-ddb3-11ea-9dee-37fdd2869fd6.png)

Probably, just to make sure that "s" will never dissapear again, I would like to recommend using a `9` value, i.e.:

```
#define HU_COORDX	((ORIGWIDTH - 9 * hu_font['A'-HU_FONTSTART]->width) + WIDESCREENDELTA)
```

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/4fed0f844cab854335c9cbf368c354838f1d3916
