### ISSUE TITLE
The FPS counter is not shown in widescreen mode.

### ISSUE THREAD

**Issue by drfrag666** [fabiangreffrath/crispy-doom#650]
### Background

Version of Crispy Doom: 5.8.0

Operating System and version: Win10 1809

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: No FPS counter with showfps in wide mode.

Expected behavior: FPS counter is shown.

**Comment by fabiangreffrath** [comment]
Fixed in https://github.com/fabiangreffrath/crispy-doom/commit/6d9ef13f8c7b68e37dca1fc74da49060c03b7bd6
