### ISSUE TITLE
Game crashes when loading Chex Quest 3

### ISSUE THREAD

**Issue by StephenPs** [fabiangreffrath/crispy-doom#652]
### Background

Version of Crispy Doom: 5.8.0

Operating System and version: Windows 10 Home

Game: (Doom/Heretic/Hexen/Strife/other) Chex Quest 3

Any loaded WADs and mods (please include full command line): None

### Bug description

Observed behavior: Game crashes when loading iwad with W_GetNumForName: Floor7_2 not found!

Expected behavior: IWAD starts like normal.

**Comment by fabiangreffrath** [comment]
Hi,

thanks for your report.

However, this is not a crash, but an error message. The FLOOR7_2 flat is used as a background to draw the bezel in widescreen mode or for smaller screen sizes- and this IWAD does not provide it. Furthermore, Chey Quest 3 is explicitly ZDoom only, so it isn't even expected to run with any other source port.

**Comment by fabiangreffrath** [comment]
I am not even sure if loading chex3.wad as a PWAD for the chex.wad IWAD works, but don't expect too much.

**Comment by StephenPs** [comment]
I didn't know it was a ZDOOM wad only.
Sorry!

**Comment by fabiangreffrath** [comment]
Never mind!
