### ISSUE TITLE
(Suggestion) Explosion screenshake like in Build engine games/Smooth Doom/Doom Retro? 

### ISSUE THREAD

**Issue by Asais10** [fabiangreffrath/crispy-doom#653]
Ditto. 

AFAIK, it shouldn't break compatibility with anything.

**Comment by Asais10** [comment]
By explosions I mean the ones from the explosive barrels and rockets.

**Comment by fabiangreffrath** [comment]
This would modulate `viewx` and `viewy` for a certain time span or how does it work?

**Comment by StephenPs** [comment]
In my opinion, I think it would go too far from the aspect of this project.

**Comment by Asais10** [comment]
> 
> 
> In my opinion, I think it would go too far from the aspect of this project.

Nah I don't think so, I think any enhancement as long as it doesn't break config/savegame/netplay/demo compatibility is fitting for Crispy Doom.

**Comment by fabiangreffrath** [comment]
Sorry, but I don't see any room for this in Crispy.
