### ISSUE TITLE
(Suggestion #2) An option (or launch parameter) to automatically pistol-start each level? 

### ISSUE THREAD

**Issue by Asais10** [fabiangreffrath/crispy-doom#654]
Ditto.

**Comment by Asais10** [comment]
This obviously should also be an option in Crispy Heretic too with it's elven wand.

**Comment by kitchen-ace** [comment]
In crispy-doom-setup and crispy-heretic-setup you can set a key for Restart level/demo under Other keys, which will automatically restart the map with a pistol/wand. Crispy Doom also supports IDCLEV00.

**Comment by mikeday0** [comment]
I have coded this up for my own local version of crispy. If the team isn't opposed to adding this feature I'd be happy to clean it up and submit a PR. I must confess that it's a fairly basic implementation (I'm probably not considering all the edge cases that I should) but it seems to work well enough for my purposes.

**Comment by fabiangreffrath** [comment]
Let's see what you got. 😉

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/2bdae1750348ba92abca6c9039a0fb7ee095b9a3
