### ISSUE TITLE
Sigil not auto-loading

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#655]
Version of Crispy Doom: 5.9.0 and latest git

User KennethDK on Doomworld is reporting that Sigil is no longer auto-loading after updating from 5.8.0 to 5.9.0. I can get it to autoload, but only if the filename is all lower- or upper-case. (The case when unzipped is `SIGIL_v1_21.wad`.)

Loading it with `-file` seems to work fine.

**Comment by kbterkelsen** [comment]
KennethDK here confirming and adding some extra details:
Updated from 5.8.0 on August 26th on Manjaro Linux via AUR/git.

**Comment by chungy** [comment]
Try renaming it as `SIGIL.wad`

**Comment by fabiangreffrath** [comment]
Sigh, case-sensitive file names on Unix file systems. 🤦
