### ISSUE TITLE
(Crispy Heretic) (Suggestion #3) Improved minimal HUD?

### ISSUE THREAD

**Issue by Asais10** [fabiangreffrath/crispy-doom#656]
In Heretic, if you maximize the screen size, instead of completely removing the HUD like in Doom, it brings up a halfway-finished HUD that only seems to display the player's health and the currently equipped inventory item. 

I think it should also display armor & ammo, at least. Or maybe it should be like crispy HUD for Crispy Doom? So it displays the same stuff as the full status bar but without the background so it takes up less screen.

**Comment by kitchen-ace** [comment]
That's the vanilla HUD. 

I agree that an improved one would be better. Maybe I'll have a go at it sometime.

**Comment by baumhoto** [comment]
Hi, 

made some minimal modifications to Heretic Fullscreen HUD that at least now amor, ammo left for current weapon and collected keys are shown.

https://user-images.githubusercontent.com/1313206/103027671-94bf4880-4556-11eb-8d12-48cd11510c73.mp4

commit: https://github.com/baumhoto/crispy-doom/commit/7d6ab00f3de2be41763373b738e470ac9cb8f559

@fabiangreffrath let me know if i should open a pull request

**Comment by fabiangreffrath** [comment]
@baumhoto Although your approach looks very nice, the Crispy HUD should differ as least as possible from the regular HUD and re-use most of its already present widgets. Also, the Crispy HUD should strictly be an additional choice and not replace any of the regular HUDs. So, thank you very much for your offer, but I am looking for something different.

**Comment by Noseey** [comment]
To bring this topic forward, here a proposal from my side:

![2024-10-26 14_36_58-Heretic_ Shadow of the Serpent Riders - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/81c9f90f-0058-4802-9cff-284b28bbcac5)
![2024-10-26 14_37_28-Heretic_ Shadow of the Serpent Riders - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/6e4b7087-b541-4a71-96ca-761150daa2d7)
![2024-10-26 14_37_51-Heretic_ Shadow of the Serpent Riders - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/14e32bad-c3e9-4e4e-aa56-8e9b02c1f003)

- Only widgets from the standard hud used
- Aligns with aspect ratio
- Is optional (screenblock 12 added)

Here the differences:
[https://github.com/fabiangreffrath/crispy-doom/compare/master...Noseey:crispy-doom:master](url)

@fabiangreffrath: Would you be interested?

**Comment by fabiangreffrath** [comment]
Sorry, but this will get the same reply as any other suggestion to improve the fullscreen HUD: We cannot implement everybody's favorite HUD in Crispy.

What I am looking at is the closest pendant to the Crispy HUD in Doom but for Heretic and Hexen, i.e. the same widgets as on the status bar, at the exact same position, but without the status bar background. @JNechaevsky don't you already have something like this in Inter-Doom?

**Comment by JNechaevsky** [comment]
Not exactly like this, but...
![HTIC00](https://github.com/user-attachments/assets/7b641143-0bd2-453f-b2ba-b081a300a834)

It's a vanilla fullscreen status bar on steroids, but there is no small digits. I've made some brief experiments for implementing idea of Crispy HUD (no status bar background, but digits are on it's place) long time ago, but don't liked the result at all.

**Comment by Noseey** [comment]
> What I am looking at is the closest pendant to the Crispy HUD in Doom but for Heretic and Hexen, i.e. the same widgets as on the status bar, at the exact same position, but without the status bar background. 

In case of the heretic standard hud, having exact positions also in the crispy hud is a tough one for me. Can it at least be negotiated to relocate the jewels completely and let the remaining widgets use up the space freed by the gargoyle heads? This ensures a better visibility of the equipped weapon, which I find important.

**Comment by fabiangreffrath** [comment]
Yes I'd be fine with this approach as a compromise.

**Comment by Noseey** [comment]
Here an update on my proposal:

The Idea:
![2024-11-01 15_45_47-Heretic_ Shadow of the Serpent Riders - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/f5eff858-b65e-49c5-a7bc-f121019a410e)

How it looks:
![2024-11-01 15_45_02-Heretic_ Shadow of the Serpent Riders - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/22774ba6-65c7-4051-aa8c-c7f017cc6d2f)

Item-Bar:
![2024-11-01 15_57_10-Heretic_ Shadow of the Serpent Riders - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/c52bf88c-6efc-412d-b141-d20061839bf7)

- Height of the original widgets is preserved.
- Horizontal differences preserved between: Health <-> Ammo, Jewels <-> Item, Item <-> Armor
- Item Selector box was taken from the vanilla fullscreen hud but without transparency. (an additional compromise)

Further possible "improvements" TBD
- Move the whole hud down by ~10px
- Decrease the horizontal difference between jewels, item and armor.
- Vertically align health and armor digits with ammo.

What do you think?

**Comment by fabiangreffrath** [comment]
Thank you very much, this looks very promising already! I like how you paid attention to the original aesthetics of the status bar. 

> * Move the whole hud down by ~10px

I agree that it could make sense to move all widgets down by the height of the "chain" sprite at the bottom. 

> * Decrease the horizontal difference between jewels, item and armor, increase the difference between Healt and Ammo to aid the visual balance

I don't think that's necessary. 

> * Vertically align health and armor digits with ammo.

This could work, but I like how the item bar is currently vertically centered between the health and armor widgets.

**Comment by fabiangreffrath** [comment]
> I agree that it could make sense to move all widgets down by the height of the "chain" sprite at the bottom.

On the other hand, the Crispy HUD for Doom also has quite some gap at the bottom and it's not a problem there.

**Comment by Noseey** [comment]
For visual reference, here some screesnhots of the variations:

1) HUD shifted down by 10px (my personal favourite):
![2024-11-02 10_57_12-Heretic_ Shadow of the Serpent Riders - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/0ca0c64d-d669-46ba-9eac-d5000d294096)

2) Health and Armor aligned with Ammo (makes the HUD a tiny bit more doom-like):
![2024-11-02 11_18_02-Heretic_ Shadow of the Serpent Riders - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/e4ac072f-57ba-4767-a179-73dffc362fc1)

3) A combination of 1) and 2):
![2024-11-02 11_10_49-Heretic_ Shadow of the Serpent Riders - Crispy Doom 7 0 0](https://github.com/user-attachments/assets/fd777f6d-2d0f-4af4-b539-33d4e9194518)


> On the other hand, the Crispy HUD for Doom also has quite some gap at the bottom and it's not a problem there.

Yes, thats true. Imho, the doom-hud makes up for that by:

- having widgets vertically aligned with the top of the HUD by default
- "Interrupting" the gap with the all-ammo-widget and keys

I could also try out other variations if you like.

**Comment by fabiangreffrath** [comment]
> 1. HUD shifted down by 10px (my personal favourite since it has a nice vanishing point towards the weapon):

Yes, I think I also like this one the most. 

> I could also try out other variations if you like.

Not for me. Would you like to adjust the PR?

**Comment by fabiangreffrath** [comment]
Also, not sure if this shouldn't override the vanilla fullscreen HUD. This may not be pristine anymore, but the original HUD is just utterly worthless.

**Comment by Noseey** [comment]
> > 1. HUD shifted down by 10px (my personal favourite since it has a nice vanishing point towards the weapon):
> 
> Yes, I think I also like this one the most.
> 
> > I could also try out other variations if you like.
> 
> Not for me. Would you like to adjust the PR?

Glad to hear you like it! I will then create a PR tomorrow with variation 1). 

> Also, not sure if this shouldn't override the vanilla fullscreen HUD. This may not be pristine anymore, but the original HUD is just utterly worthless.

Functionally, I would agree that the vanilla fullscreen HUD is not very helpful. However, there might be players who have beaten the game time and again with this HUD and it is now part of their Nostalgia, so I personally would keep it in. Also, with the "green font" it has a different style, which some people may prefer. If you want, I can add that it aligns with the aspect ratio?

**Comment by fabiangreffrath** [comment]
Right. Let's keep the original fullscreen HUD untouched then.
