### ISSUE TITLE
Crusher stop limit

### ISSUE THREAD

**Issue by simc2** [fabiangreffrath/crispy-doom#657]
### Background

Version of Crispy Doom: 5.9.0

Operating System and version: Windows 8.1 x64

Game: Doom

Any loaded WADs and mods (please include full command line): 

A testwad "32crushers.wad" for Doom2 map01 is attached at the end of this report.
command line: 
crispy-doom.exe -iwad doom2.wad -file 32crushers.wad -skill 4 -warp 1

### Bug description

This is about one vanilla limit in Crispy-Doom.

It looks like that Doom "crusher stop" line actions will stop only the 30 lowest numbered crusher sectors of all the sectors having the same tag. Other crushers with the same tag will carry on crushing. Triggering any "crusher start" special to 60+ sectors with the same tag at once has no problems.

Observed behavior:
On the test level "32crushers.wad" the FLAT14 (blue) marked switch and walk over triggers on the left will start crusher actions to the 32 crushers behind the triggers. All the crushers have the same tag so any trigger will launch them all. 
The two RROCK01 (red) marked walk over triggers on the right both have W1/WR crusher stop action. Walking on them will stop only 30 of the triggered 32 crushers. The two still moving crushers on the right have the two highest sector numbers of all crushers.

Expected behavior:
The crusher stop actions to stop all the crushers...

**Test wad**: 
[32crushers.zip](https://github.com/fabiangreffrath/crispy-doom/files/5139193/32crushers.zip)

The action lines from left to right are: 
49 S1 start slow moving crusher
73 WR start slow moving crusher
25 W1 start slow moving crusher
77 WR start fast moving crusher
6 W1 start fast moving crusher
141 W1 start slow moving/DSPSTOP noise crusher
74 WR crusher stop
57 W1 crusher stop

**Comment by fabiangreffrath** [comment]
Thanks for raising this issue. Indeed, `MAXCEILINGS` is a Vanilla limit. So, what happens if a demo is recorded in Crispy with this limit removed and then played back in Vanilla - or vice versa?

**Comment by simc2** [comment]
On second thought it can be seen as the Vanilla lost soul limit Crispy-Doom do respect.
It's not a big deal. How many wads have that many crushers anyway?

Thanks for your time. Sorry for the trouble.
