### ISSUE TITLE
Idea : Have in game keys to start recording a demo, and another one to stop.

### ISSUE THREAD

**Issue by StephenPs** [fabiangreffrath/crispy-doom#658]
I think it would be a good idea to press keys to start recording a demo instead of typing in commands. Just a thought - please tell me if it conflicts with something!

**Comment by fabiangreffrath** [comment]
Thanks for sharing your idea. Unfortunately, it is only possible in Doom to start recording a demo at gametic `0`, i.e. at the moment the engine itself starts. However, in Crispy you may record and play back a demo starting at a savegame. Maybe this comes closest to what you had in mind.
