### ISSUE TITLE
In game console

### ISSUE THREAD

**Issue by StephenPs** [fabiangreffrath/crispy-doom#660]
Would it be possible to add a in game console to Crispy Doom? I would like it, but if it goes against your rules, I understand.

**Comment by fabiangreffrath** [comment]
Sorry, there won't be a console, no chance.

**Comment by StephenPs** [comment]
I'm sorry for asking too many questions that conflict what your projects goals are. I just should stop asking questions. Crispy doom is basically finished.

**Comment by fabiangreffrath** [comment]
No need to excuse! Crispy is basically finished for 5 years now and nevertheless people often find ways to improve or extend the engine within reasonable measure. Just have a look at the Changelogs for the last few releases - they're massive. And none if these changes goes against the spirit of this project. So, there is still much room left for ideas, bug not all if them will get accepted or implemented.
