### ISSUE TITLE
MASTERLEVELS.WAD causes issues with NERVE.WAD

### ISSUE THREAD

**Issue by Dark-Jaguar** [fabiangreffrath/crispy-doom#662]
### Background

Version of Crispy Doom: 5.9.1

Operating System and version: Windows 10 Biuild 2004

Game: (Doom/Heretic/Hexen/Strife/other) Doom II

Any loaded WADs and mods (please include full command line): Crispy Doom auto-loading both NERVE.WAD from my Doom II folder and Masterlevels.wad from my Doom 3 BFG directory.

### Bug description
When completing level 1 of No Rest For The Living, the game crashes with the message "W_GetNumForName: CWILV09 not found!" when it attempts to load the next level.  This bug doesn't occur on completing map 1 of either the main Doom 2 campaign or the Master Levels in campaign form.

After testing a number of times, I've determined something of the cause of this bug.  If Crispy ONLY loads doom2.wad and nerve.wad then the glitch doesn't occur.  I had to rename masterlevels.wad in my BFG directory (it's running the Doom 3 BFA mod which is why it's there) in order to prevent it from loading that file however.  It's only when masterlevels.wad gets loaded that the glitch occurs.  Perhaps a good fix might be to allow the config file to define which folders are autochecked for wads when Crispy Doom starts so I can dummy out the Doom 3 BFG check?

**Comment by fabiangreffrath** [comment]
Sorry, but I cannot reproduce. I just had Doom 2 loaded with both nerve.wad and masterlevels.wad auto-loaded, played through and finished NRFTL MAP01 and proceeded to the next map without any issues.

**Comment by Dark-Jaguar** [comment]
What method did you use to create masterlevels.wad?  Mine gets autocreated by the Doom 3 BFA mod, perhaps it is different in some critical way?  As it stands, the only long term solution I can think of is disabling Crispy Doom's scan of the Doom 3 BFG folders, at least it would be a nice flag to have under config.  I can send you a copy of it or get you a checksum if that helps.  All I can say is the issue did occur on 5.9.0 as well as the newest build, but I installed the newest one fresh without any old files present in the directory.

**Comment by fabiangreffrath** [comment]
That WAD usually isn't "made". It's an official PWAD that gets shipped with Doom Classic Complete for the Playstation Network:
https://doomwiki.org/wiki/MASTERLEVELS.WAD

**Comment by fabiangreffrath** [comment]
But that explains a lot. Could you please tell me *exactly* what error message pops up and *exactly* when it does so?

**Comment by Dark-Jaguar** [comment]
The error message in it's entirety is what I posted above.  It appears in a standard Windows error box after the program quits.  It happens after the score screen of the first level of NERVE is completed. The moment I press a button to start up the next level, the error occurs.

**Comment by Dark-Jaguar** [comment]
I noticed it was closed and checked the notes.  Thank you!  It looks like that should resolve the issue and I'll test it when I get an opportunity to.

**Comment by fabiangreffrath** [comment]
The latest build is always available here:
http://latest.chocolate-doom.org/

**Comment by Dark-Jaguar** [comment]
Your fix worked!  I am pleased to report there are no longer any issues since you took steps to make it ignore BFA's rather unofficial implementation of the masterlevels.wad.

**Comment by fabiangreffrath** [comment]
Cool, thanks for reporting back!
