### ISSUE TITLE
extras.wad

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#663]
I was curious if there are any plans to use any of the assets included in extras.wad.  extras.wad is included in the Unity version of DOOM and DOOM II.

Here is some more info on this WAD:

https://www.doomworld.com/forum/topic/67168-crispy-doom-591-update-sep-04-2020/?page=62&tab=comments#comment-2121773

DSSECRET is now used when a secret is found in the latest Unity DOOM update.

**Comment by fabiangreffrath** [comment]
I don't own any of the Unity ports and I have no plans to add support for any of their assets.

**Comment by Dark-Jaguar** [comment]
There's also the rather nuts "Ultra-Violent +" difficulty level which just kinda dumps all the multiplayer only assets into single player.  That means, among other things, dealing with an army of revenants and a spider master mind on the starting level of Plutonia.  Intersting- but unneeded in a vanilla compatible port I think.

**Comment by fabiangreffrath** [comment]
> but unneeded in a vanilla compatible port I think.

Indeed, I am not going to run behind every selling argument they come up with for a 25+ years old game.

**Comment by drfrag666** [comment]
Not interesting for me, those are only in a few maps and mainly bosses (cyberdemons). RUDE has a new skill level with double the monsters among other things.

**Comment by buvk** [comment]
I noticed that Crispy now uses DSSECRET if it is available.  I am not sure if this was always the case.

Anyways, I don't see a need to keep this "issue" open anymore.
