### ISSUE TITLE
Nerve TITLEPIC

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#664]
Latest NERVE.WAD contains TITLEPIC and INTERPIC.  If loaded as a PWAD, INTERPIC is displayed.  I was wondering if it would be possible to display TITLEPIC instead.

**Comment by fabiangreffrath** [comment]
Oh, and then I would also have to rename NERVE.wad's TITLEPIC lump out of the way if it gets auto-loaded.

**Comment by fabiangreffrath** [comment]
Does the new NERVE.WAD also contain its own INTERPIC lump?

**Comment by buvk** [comment]
Yes it does.  The contained INTERPIC is just a widescreen version of DMENUPIC found in doom2bfg.wad

**Comment by buvk** [comment]
To my knowledge, the only things introduced in nerve since the BFG release are DMAPINFO, INTERPIC and TITLEPIC.
