### ISSUE TITLE
Save file is not created

### ISSUE THREAD

**Issue by Vasyl4G** [fabiangreffrath/crispy-doom#668]
### Background

Version of Crispy Doom: crispy-doom-5.8.0-win32

Operating System and version: Windows 10

Game: Doom II

Any loaded WADs and mods (please include full command line):
standard DOOM2.WAD
crispy-doom.exe -playdemo uv1

### Bug description
I've created simple demo where I do nothing just save the game and exit.
When I create demo (with crispy-doom.exe -record uv1), save file is created.
When I play demo (with crispy-doom.exe -playdemo uv1), save file is NOT created.
Original Doom II, does create save file when I playdemo this lmp file.

Observed behavior:
Save file is not created during demo playback.

Expected behavior:
Save file is created during demo playback.

**Comment by fabiangreffrath** [comment]
OMG, this was one of the first things that I removed when I found out that merely playing back a random demo could overwrite my precious savegames.

**Comment by Vasyl4G** [comment]
Is there any way this feature could be turned on back (over config or command line switch)?
I find this feature useful in my application.
Or maybe there is any workaround to get this working?
What is the behavior of Chocolate Doom in this case?
Appreciate if you could help with this.

**Comment by fabiangreffrath** [comment]
Chocolate Doom will override your savegames. Sorry, but I will never turn this back on in Crispy.

However, it is trivial to turn this back on in the code. Just remove this single instruction here:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/g_game.c#L1264

**Comment by Vasyl4G** [comment]
Thank you a lot for fast response.
