### ISSUE TITLE
Future of Crispy Doom?

### ISSUE THREAD

**Issue by StephenPs** [fabiangreffrath/crispy-doom#669]
This was once asking a question on why people still use demo files (I finally realized the answer), but what are your goals for crispy doom? Hopefully, we can get Crispy Hexen.

**Comment by fabiangreffrath** [comment]
Regarding features, I don't have any further plans. Actually, it's like that since the 1.0 release. :wink: Nearly all of the other feature ideas came from the community - either through the Doomworld forum or through the issue tracker here. 

It would be nice, though, to be able to switch the truecolor renderer at run-time (it's a build-time switch currently), but I don't have any good idea for that for years now.

I hope that we can get more contributors for Hexen and Strife - and Heretic actually, its development has just started to gain some momentum again. The code is all there, it's in a good state, but I simply don't feel any incentive to care about it myself.

**Comment by StephenPs** [comment]
Also, I google traslated the Crispy Doom Description on the code page and got this : The heart of Roman Crispy is to pour a chocolate candle into a beautiful cup.

The name makes the 640x400 part a "combination" and defines the basics.

Please confirm again
CrispyDoom is the foundation of ChocolateDoom and has access to the Doom engine for better graphics and new features, functionality and interface. Save original games Save games with advertisements.

Selection and supervision
Crispy Doom is a website designed to provide help and support as well as powerful information about Doctor Doom for clients in need. Use a chocolate fork to plant, adjust and taste the vanilla extract.

These are the main symptoms.

The 640x400 screen was originally modified 320x200: interior design.
Browse online averages 24 to 9:
Internet Service Provider (VSync) Unlimited pricing and online development.
Average gamma correction (0.5, 1.5, 2.5, 3.5).
Remove dirt from the machine or the floor.
This size is included in the popular version of WAD "Size 3: BFG Version" and larger is included in the "Inexperienced Life" section of the NERVE.WAD file.
John Romero: Help with the last supper
In addition, they are easy to use and beautiful.

Dula
An empty species with eyes and a mouse
Register for the game.
The small HUD only displays the current level.
With the cleaning function, you can print canvas or large cloth without using HUD without tools and pens.
Various numbers, HUD characters, elbows of other animals.
Hide the gums from CrispyHUD.
It will only display the death number.
Rules for exchanging text and / or format.
Players can rely on ghosts and corpses to keep them down.
After firing, the weapon is ready to come back and start firing.
Show where the secrets were revealed.
Cards and color cards.
Continue with the final decisions. Change a few words.
Graphic design and / or listening time can be used to change the tone.
Bring it to the control section. It will allow you to adjust the player settings when the screen is closed or distorted.
Many of these signs are simply disabled and should be used as a command line on a broken page or on the "Vulnerability" page. This show demonstrates the interaction of vanilla scent with chocolate bars. Additionally, the Crispy Doom logo in the conversion file is similar to Vanilla Dodo, but not identical (see wiki section).

Crispy Roma's goal was to achieve the well-known method of "nonsense" (no progress or zedom). In addition, Crispy Doom will support and support other options, such as MBF SMMU flight buttons and emergency response, but does not include logos and logos or list lists and pinfo names. ..

Open and close, try writing text, select well with text files, copy and enlarge numbers, add parameters, formats and much more. So, by adding MBF functionality to DeHaud, Crisp supports ROM implementation. It makes the game even better. See Description below for a full list of plans and updates.

**Comment by fabiangreffrath** [comment]
What exactly?

**Comment by StephenPs** [comment]
The Readme file is what I google translated.

**Comment by StephenPs** [comment]
I also google translated the Chocolate doom description.

**Comment by 07416** [comment]
[the Google Translate comments seem entirely off-topic]
