### ISSUE TITLE
No Rest for the Living code doesn't special-case the PWAD with an all-uppercase name

### ISSUE THREAD

**Issue by chungy** [fabiangreffrath/crispy-doom#67]
Doom 3: BFG Edition from Steam downloads all the files under the base/wads directory with uppercase names (DOOM.WAD, DOOM2.WAD, NERVE.WAD), and likewise the engine (which can be built and ran on Linux) looks for them with only these names. Using "-file NERVE.WAD" causes none of the special cases for NRFTL to be triggered (changed music, level names, etc).

This actually wasn't obvious to me until I read the wiki page; I didn't realize there was supposed to be anything special done for this WAD.

**Comment by fabiangreffrath** [comment]
Dear chungy, 

thank you for taking the time to file this bug report. Could you please try to reproduce with the latest git snapshot? I think I already fixed this issue in https://github.com/fabiangreffrath/crispy-doom/commit/c35057de76db5ffa2f37ac5982d67afb9693e735 .

> This actually wasn't obvious to me until I read the wiki page; I didn't realize there was supposed to be anything special done for this WAD.

It is not strictly necessary, but it makes more fun to play with the correct music, par times, level progression and map names. ;)

**Comment by chungy** [comment]
Yes, the current tip seems to work fine with the uppercase name, thanks. Maybe it's time for a Crispy Doom 3.0 already? :P
