### ISSUE TITLE
Crispy doom setup won't open

### ISSUE THREAD

**Issue by crispydoomsetup** [fabiangreffrath/crispy-doom#670]
### Background

Version of Crispy Doom: 5.9.1

Operating System and version: Windows 10 2004

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line): N/A

### Bug description

Observed behavior: The setup crashes shortly after opening. It shows a white screen before it closes.

Expected behavior: The setup should open normally.

**Comment by fabiangreffrath** [comment]
Please make sure crispy-doom-setup is run from a location where you have write permissions.

**Comment by crispydoomsetup** [comment]
> Please make sure crispy-doom-setup is run from a location where you have write permissions.

It's in my documents folder, which I _believe_ should have write permissions

**Comment by fabiangreffrath** [comment]
DO you have the entire content of the Crispy Doom distribution (i.e. including all the DLL files) available in the same directory?

**Comment by crispydoomsetup** [comment]
> Do you have the entire content of the Crispy Doom distribution (i.e. including all the DLL files) available in the same directory?

Yeah, if I understand what you mean. All of the content from the crispy doom zip file is in the same folder, which is in my documents.

**Comment by fabiangreffrath** [comment]
Hm, is your anti-virus probably overacting?

**Comment by crispydoomsetup** [comment]
> Hm, is your anti-virus probably overacting?

No anti-virus installed aside from windows defender, which I've disabled

**Comment by fabiangreffrath** [comment]
Phew, I don't know. Maybe unzip elsewhere outside your documents directory? Desktop maybe?

**Comment by crispydoomsetup** [comment]
> Phew, I don't know. Maybe unzip elsewhere outside your documents directory? Desktop maybe?

I'll try it. I just wanna add, I'm almost certain this isn't a fault of crispy doom but something wrong with my system. I just don't really know what might have changed. I'll edit this if I can get it to work.

**Comment by crispydoomsetup** [comment]
Figured I will add, I tried out 5.9.2, the setup still doesn't open.

**Comment by fabiangreffrath** [comment]
Interesting. Does this work?

[crispy-doom-setup_20200922.zip](https://github.com/fabiangreffrath/crispy-doom/files/5259747/crispy-doom-setup_20200922.zip)

**Comment by crispydoomsetup** [comment]
> Interesting. Does this work?
> 
> [crispy-doom-setup_20200922.zip](https://github.com/fabiangreffrath/crispy-doom/files/5259747/crispy-doom-setup_20200922.zip)

Yes! It worked

**Comment by crispydoomsetup** [comment]
This is unrelated to the current issue, I didn't know if I should start a new one or not, but trying to configure Timidity++ is a pain. My file for timidity.cfg is as follows
`dir C:\Users\User\Documents\Timidity\
soundfont C:\Users\User\Documents\Timidity\SC_55_Patch93.sf2`

For some reason though it doesn't work with Crispy Doom, but when opening the timidity gui exe it works fine.

**Comment by crispydoomsetup** [comment]
There is an issue with my video card drivers, as seen using event viewer (some bug with a module named nvoglv32.dll) so this is just an issue with my system and not with crispy doom

**Comment by drfrag666** [comment]
Seems it's another SDL2 bug with some old drivers. With SDL 2.0.8 it doesn't happen AFAIK.
