### ISSUE TITLE
Widescreen assets from the Unity port display stretched.

### ISSUE THREAD

**Issue by chungy** [fabiangreffrath/crispy-doom#671]
### Background

Version of Crispy Doom: 5.9.2

Operating System and version: Arch, updated

Game: Doom

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior:

When loading the Unity (version 1.3) IWAD, the widescreen assets get squashed down into 4:3 format. These assets include the titlepic, interpic, and bunny end scene

vanilla Ultimate Doom IWAD:
![DOOM0000](https://user-images.githubusercontent.com/1094821/93916912-1c2ebe80-fcbf-11ea-9af7-e91acbdc127f.png)

Unity 1.3 IWAD:
![DOOM0001](https://user-images.githubusercontent.com/1094821/93916928-22bd3600-fcbf-11ea-8a01-6810764c34a4.png)

Expected behavior:

Either crop the assets for 4:3 display, or display the proper widescreen picture.

**Comment by drfrag666** [comment]
sponge gave some suggestions here: https://github.com/fabiangreffrath/crispy-doom/issues/665

**Comment by chungy** [comment]
I didn't even notice before either, but the status bar is all screwed up too :)

![DOOM0000](https://user-images.githubusercontent.com/1094821/95310535-5eb8d500-0841-11eb-9288-a449ddc83c6c.png)

**Comment by drfrag666** [comment]
Seems both fabian and i are burned out after adding widescreen. But hey @SmileTheory is doing the adjustments for both Crispy and Choco so i guess he'll do both PRs soon. And then i could "suck" the Choco code for RUDE (unless James wants to join the RUDE team that is ;) ). I already merged his 0.9 demo support PR BTW.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/a243b66e46f1e1492ffc20f61967968caa764d55
