### ISSUE TITLE
Strange graphical issue in Chex Quest

### ISSUE THREAD

**Issue by crispydoomsetup** [fabiangreffrath/crispy-doom#672]
### Background

Version of Crispy Doom: 5.9.2

Operating System and version: Windows 10 2004

Game: (Doom/Heretic/Hexen/Strife/other) Chex Quest

Any loaded WADs and mods (please include full command line): CHEX.deh

### Bug description

Observed behavior: Weird graphical issue in E1M2

Expected behavior: I thought it'd look normal, is this just how it looks?

![crispy-doom_2QRAFKglFR](https://user-images.githubusercontent.com/71607955/94303524-f8c47780-ff3b-11ea-83e6-f72a3eb9cf5a.png)

**Comment by fabiangreffrath** [comment]
What's strange exactly?

**Comment by crispydoomsetup** [comment]
There's a weird thing going on with the floor texture, I can't really explain it but if you look at the other teleporter in this map the floor is just a grate, meanwhile on this teleporter the floor is a grate with a weird texture mixed in.

**Comment by bradharding** [comment]
This appears to be a fault with the map itself. Sector 347 (the floor surrounding the raised teleporter) isn't closed properly. The room on the other side of the map that mirrors this one is done correctly.

**Comment by crispydoomsetup** [comment]
> This appears to be a fault with the map itself. Sector 347 (the floor surrounding the raised teleporter) isn't closed properly. The room on the other side of the map that mirrors this one is done correctly.

Ah, okay! Thank you for clarifying, I didn't know.
