### ISSUE TITLE
Widescreen rendering option is greyed out

### ISSUE THREAD

**Issue by HalfWayLambda** [fabiangreffrath/crispy-doom#675]
### Background

Version of Crispy Doom: 5.9.2

Operating System and version: Windows 10 Version 2004

Game: Doom/Doom 2

### Bug description

Observed behavior: Widescreen rendering option in the crispness menu is grayed out and can't be activated. I can't find a cause for this.

Expected behavior: Widescreen rendering shouldn't be grayed out. I haven't seen anyone else report this so I guess it's something specific to me only.

**Comment by fabiangreffrath** [comment]
What are your screen dimensions? Do you even have a wide screen?

**Comment by fabiangreffrath** [comment]
You need to have "aspect ratio correction" enabled.
