### ISSUE TITLE
(Suggestion) Doom Eternal inspired Arachnotron blood

### ISSUE THREAD

**Issue by mugmonster** [fabiangreffrath/crispy-doom#676]
so, for whatever reason, Doom Eternal gave the Arachnotrons blue blood (maybe because they have blue eyes?).  I've often thought it would be nice if the colored blood feature in Crispy wasnt limited to just 3 monsters, so I can't help but feel like this would be an opportunity to get one more usage out of it.  but I also feel like this might be divisive.  would anyone else be in favor of this?

**Comment by Asais10** [comment]
That also means that the death sprites would also need to be replaced due to them using red blood

**Comment by fabiangreffrath** [comment]
Indeed. The monsters bleeding blue blood and then dying in a pool of red blood is a no-go and so is adding replacement sprites to the port.
