### ISSUE TITLE
Sometimes MIDI musics played incorrectly

### ISSUE THREAD

**Issue by skyrain128** [fabiangreffrath/crispy-doom#677]
### Background

Version of Crispy Doom: 5.9.1

Operating System and version: Windows 10 x64

Game: (Doom/Heretic/Hexen/Strife/other) Doom II

Any loaded WADs and mods (please include full command line): vsmooth.wad, D2SPFX19.WAD, pk_doom_sfx_20120224.wad

### Bug description

Observed behavior: sometimes MIDI musics play incorrectly. some instruments have higher pitch than correct.
I was using Roland JV-1010 with MIDIMATE ex USB MIDI cable. (Sorry for my bad English grammar, It's not my native language.)

Expected behavior: MIDI music should played correctly.

**Comment by fabiangreffrath** [comment]
Music lumps are passed over to SDL_Mixer which in turn passes it over to a MIDI backend, e.g. fluidsynth or portaudio or the native MIDI synth on Windows. Thus, it's not the port's responsibility to actually render the MIDI music content.

**Comment by Silanda** [comment]
I know this has been closed but I just thought I'd add that Sigil shows a great example of this kind of problem (which I believe is inherited from Chocolate Doom). When you start the first map from the title screen, the bass line is initially missing. This is true on multiple MIDI devices using different hardware interfaces. Do the same (load the Sigil WAD) but instead start E1M1 and most of the song is initially missing or very quiet.

I'm not a programmer, and I'm probably totally off base, but are the MIDI parameters being reset when songs are changed? Ordinarily it's good practice for MIDI songs themselves to call a GM (or GS or XG depending on the target hardware) reset, and to not assume that the playback device is in a default state. I don't know how this was handled in DOS Doom, but if songs don't contain a reset, and Chocolate/Crispy Doom isn't sending any between songs either, it could lead to incorrect/unexpected parameters (volume, panning, etc) being inherited from one song to another, leading to screwy playback.

The testing I've done so far does suggest that tracks are inheriting incorrect parameters, but I'll try to capture some MIDI data and investigate exactly what's being sent to the devices.
