### ISSUE TITLE
Crispy's SFX sounds are too quite compared to Original DOS Doom II 1.9

### ISSUE THREAD

**Issue by skyrain128** [fabiangreffrath/crispy-doom#678]
### Background

Version of Crispy Doom: 5.9.2

Operating System and version: Windows 10 x64

Game: (Doom/Heretic/Hexen/Strife/other) Doom II

Any loaded WADs and mods (please include full command line): 

### Bug description

Observed behavior: Crispy's SFX sounds are too quite compared to Original DOS Doom II 1.9 (when both are in max SFX volume)

Expected behavior: Crispy's SFX sounds should be louder.

**Comment by fabiangreffrath** [comment]
Sounds are passed to SDL_Mixer and then mixed with the music and passed over to the audio backend. Nobody ever complained about that before and I have no idea how this could be even done differently.

**Comment by JNechaevsky** [comment]
@skyrain128 you may try to increase `libsamplerate_scale` from `0.650000` to `1` in your crispy-doom.cfg.

**Comment by fabiangreffrath** [comment]
Oh yes, right. I completely forgot about this step. While merely increasing the scaling value may result in sound clipping, you may want to disable using libsamplerate entirely.

**Comment by NicknineTheEagle** [comment]
SFX is Crispy Doom are quieter compared to Chocolate Doom as well so I think this is a valid issue.
