### ISSUE TITLE
(Suggestion) Extra option for colored blood, but excluding spectres and lost souls

### ISSUE THREAD

**Issue by DwarsYT** [fabiangreffrath/crispy-doom#680]
While the colored blood option for barons, hell knights, and cacodemons are fine as is, a potential extra option could be there to exclude spectres and lost souls from having their blood changed. 

I suggest this because while the effect is aesthetically sensible, the lack of fully visible blood coming from spectres can make it a bit difficult to tell if you've actually hit them in certain circumstances (like dark rooms with them.) 
As for the lost souls, having the bullet puff also makes sense aesthetically. However, sometimes when using hitscan weapons against them, it's hard to tell if the bullets hit them or the wall in certain circumstances as well.

**Comment by fabiangreffrath** [comment]
Years ago there were two switches, one for colored blood and one for "fixed" blood for Spectres and Lost Souls, just as you suggested. But then I decided that I wanted a more global feature selection and that I wanted to avoid feature micro-management at any cost. Thus I combined some very similar features into some more general switches and I don't think I will ever go back from this concept again.
