### ISSUE TITLE
Best way to use the SC-55 Music Packs?

### ISSUE THREAD

**Issue by Toonerz** [fabiangreffrath/crispy-doom#685]
Sorry if this is answered elsewhere, but, what would be the best way to use the SC-55 Music Packs (found here: [http://sc55.duke4.net/](url) ) with Crispy Doom?

The website says Crispy Doom is a supported engine, in terms of the music packs, but last time I used it, sometime back (I don't remember how I had it setup at the time), there was issues with looping, and the location of where the music files should go, if they remain in the zip or note, and other things, were not clear, so there ended up being like allot of copies of the zips and extracted files, until one of them worked.

If someone could tell me how to use these packs properly with Crispy Doom, id very much appreciate that.

**Comment by fabiangreffrath** [comment]
Please follow the instructions provided here:
https://www.chocolate-doom.org/wiki/index.php/Digital_music_packs
