### ISSUE TITLE
Cannot open some doors and switches in Doom II: Dark World WAD

### ISSUE THREAD

**Issue by saegiru** [fabiangreffrath/crispy-doom#686]
### Background

Version of Crispy Doom: commit b5c9a6a5e169fded622b20e80f50b4f33a2a0f97 (and prior)

Operating System and version: Windows 10 1909 Build 19041.572

Game: (Doom/Heretic/Hexen/Strife/other) Doom II

Any loaded WADs and mods (please include full command line): crispy-doom.exe -iwad D:/doom/wads/main/doom2.wad -file d:/doom/wads/maps/d2dw/dwdw-v1.wad

### Bug description

Observed behavior: Unable to open some doors and push some switches in this wad. First door in MAP01, exit door in MAP01, first switch in MAP02, etc. Seems to work in GZDoom, as well as on original doom executable on DOS, and MBF. Also, it crashes out when attempting to load in Chocolate Doom as well. More than likely a shared bug between both ports. WAD can be downloaded here: https://www.doomworld.com/idgames/levels/doom2/Ports/d-f/d2dw

Expected behavior: Ability to open doors and push switches.

**Comment by saegiru** [comment]
Just found out it happens on Eviternity WAD as well. Specifically noticed the switch in MAP01 here:  https://imgur.com/a/jNglsiC

There are probably others, but I stopped at that point. WAD can be downloaded here: https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/eviternity

**Comment by fabiangreffrath** [comment]
Both these WADs explicitly require a Boom-compatible port.
