### ISSUE TITLE
Things don't render unless they are close.

### ISSUE THREAD

**Issue by retro65** [fabiangreffrath/crispy-doom#690]
### Background

Version of Crispy Doom: 5.10.0

Operating System and version: Ubuntu 18.04.5 LTS

Game: 
[Doom2.zip](https://github.com/fabiangreffrath/crispy-doom/files/5454171/Doom2.zip)
Got it from [Internet Archive](https://archive.org/details/Doom-2).

Any loaded WADs and mods (please include full command line):
`crispy-doom -file mikoport.wad` (already in IWAD directory)
[mikoport.zip](https://github.com/fabiangreffrath/crispy-doom/files/5454198/mikoport.zip)

### Bug description

The sector floor is at -32743.

Observed behavior: Things (medikits, voodoo doll, and explosive barrel) are not visible at all unless very close to them. However, hitscan weapons (pistol) still work.

Expected behavior: Should be visible as long as in FOV and unobstructed.

**Comment by fabiangreffrath** [comment]
Well, I guess it has to do with this special floorheight...

**Comment by retro65** [comment]
By the way, I tested the exact same WAD in Vanilla (DOSBox). The things are properly visible there, so it is something Crispy/Chocolate specific.

**Comment by JNechaevsky** [comment]
This caused by Killough's `gzt` optimization, after commenting out following condition, sprites will appear: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_things.c#L715

But what's wrong with it then?

**Comment by turol** [comment]
Probably something overflows. Shifting signed values can easily go into undefined behavior territory.

**Comment by fabiangreffrath** [comment]
Right-hand-side of the second part of the check likely underflows.

**Comment by retro65** [comment]
An obvious guess would be that fixed point division progressively breaks as things get further from zero. I don't completely understand the code there, but I do understand some trigonometry.

Hey, we all suggested the same thing!

**Comment by retro65** [comment]
But what is a division doing there?

**Comment by retro65** [comment]
> This caused by Killough's `gzt` optimization, after commenting out following condition, sprites will appear: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_things.c#L715
> 
> But what's wrong with it then?

Also, I checked the Chocolate code, and it doesn't have that line, so the glitch is specific to Crispy.

**Comment by fabiangreffrath** [comment]
Subtracting `viewz` from both sides of the second inequality seems to solve the issue.

**Comment by retro65** [comment]
It may be helpful or at least educational to know what do the variables&constants in that expression represent, because some of them leave me kinda confused.

**Comment by retro65** [comment]
> Subtracting `viewz` from both sides of the second inequality seems to solve the issue.

So, removing `viewz - ` from the right and changing the left into `gzt - viewz`?

**Comment by retro65** [comment]
Also, why `viewheight << FRACBITS`?

That is taking the fractional part of the screen height, turning it into a whole fixed number, discarding the original whole part. Why is that done?

**Comment by fabiangreffrath** [comment]
Casting the right-hand-side to `int64_t` solves the issue as well.

```
gzt < (int64_t)viewz - FixedDiv((viewheight << FRACBITS)-viewheight, xscale)
```

Let's have a look at the numbers:

```
(gdb) p gzt
$1 = -2144600064
(gdb) p viewz
$2 = -2143158272
(gdb) p viewheight
$3 = 336
(gdb) p xscale
$4 = 65538
(gdb) p FixedDiv((viewheight << 16)-viewheight, xscale)
$5 = 22019088
(gdb) p viewz-22019088
$6 = 2129789936
```

An so 
```
-2144600064 < -2143158272 - 22019088
```
underflows to
```
-2144600064 < 2129789936
```
and thus the condition becomes `true`.

**Comment by retro65** [comment]
In general, low z position results in underflow when calculating whether the thing is visible vertically?
What is the cleanest way to fix?
I guess I'm blowing this into something huge...
