### ISSUE TITLE
Why aren't png screenshots supported

### ISSUE THREAD

**Issue by amiga1985** [fabiangreffrath/crispy-doom#695]
Version of Crispy Doom: 5.10

For some reason, png screenshots cannot be taken. There is no option for those in the crispness menu, and changing it in the config file hasn't helped. Can PNG screenshots be reimplemented in the next patch? If not, I would like to know why they are left out.

**Comment by fabiangreffrath** [comment]
He? Are you building the binaries yourself?

**Comment by amiga1985** [comment]
Yeah. I built the latest myself. Are there any libraries I'm missing or something?

**Comment by fabiangreffrath** [comment]
Well, you'll need libpng ang zlib for that.

**Comment by fabiangreffrath** [comment]
Watch out for the following line during the `./configure` phase:
```
checking for PNG... yes
```

**Comment by amiga1985** [comment]
yeah. I didn't install the development libraries for that. I think I only installed the SDL development libraries. I will do that now.

**Comment by amiga1985** [comment]
Which zlib library do I need?

**Comment by fabiangreffrath** [comment]
https://zlib.net/

**Comment by amiga1985** [comment]
Thanks! It works now!
