### ISSUE TITLE
How do I load .pk3 files?

### ISSUE THREAD

**Issue by dartharva** [fabiangreffrath/crispy-doom#696]
I wish to use [this](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion) mod that has been packed in a .pk3 format. How do I make crispy-doom load it?

### Background
Version of Crispy Doom: **5.9.2**
Operating System and version: **Windows 10**
Game: **Doom**

**Comment by fabiangreffrath** [comment]
Brutal Doom is a mod targeted at ZDoom ports. And Crispy cannot load PK3 files at all.
