### ISSUE TITLE
Music pack with custom soundfont

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [fabiangreffrath/crispy-doom#697]
https://github.com/fabiangreffrath/crispy-doom/wiki/Sound-pitch-fix-&-Music-Pack

Is this project abandoned yet again?

It worked fine by default with 5.6.0-5.7.1, and it was possible to make it work with 5.7.2-5.9.0 by copying _libmad-0.dll_ from 5.7.1. But with 5.9.1-5.9.2 this method no longer works and results in the _Mix_OpenAudioDevice_ error.

**Comment by fabiangreffrath** [comment]
Yes, this project is abandoned. Crispy now requires newer SDL libraries than what is provided by this pack.

**Comment by nbmrjuhneibkr** [comment]
Is there a chance for built-in custom soundfont support to be re-implemented in the future? It would be nice for this functionality to be fully self-contained.

Third-party software like VirtualMIDISynth is not guaranteed to always be compatible with the OS, and pre-recorded music packs can take up a lot of space.

**Comment by fabiangreffrath** [comment]
You'll need an ABI-compatible SDL2_Mixer library with fluidsynth support enabled. Unfortunately, the SDL2_Mixer library that Crispy is linked against on fraggle's auto-build server is not fluidsynth-enabled. You may try your luck with this bundle of MSYS2 libraries, but please do not consider this supported to any degree:

[Uploading SDL2_mixer-with-fluidsynth_20201123.zip…]()

**Comment by nbmrjuhneibkr** [comment]
So, if this https://github.com/chocolate-doom/chocolate-doom/issues/1155 is resolved, SF2 soundfonts will be supported by default in all Chocolate/Crispy Doom builds going forward, right?

**Comment by fabiangreffrath** [comment]
In theory yes, but I doubt this is going to happen. Fluidsynth is a pretty heavy-weight dependency that adds some requirements to the build system and further dependencies (like glib) on its own. Also, the benefit wouldn't be immediate (as with e.g. MP3 support) but would require users to add some more configuration like setting environment variables - or require the setup tool to add infrastructure for this. I doubt @fragglet is going to go this way anytime soon.

**Comment by FozzeY** [comment]
It's really unfortunate because the pack also used to fix the FLAC playback issue on Windows chocolate-doom#1178.
