### ISSUE TITLE
Don't desync when entering menus while recording demos

### ISSUE THREAD

**Issue by plumsinus** [fabiangreffrath/crispy-doom#7]
When recording a demo, pressing Escape or any other key that opens a menu will lead to the demo desyncing at that point. It would be nice if that didn't happen. PrBoom+ pauses the demo transparently (i.e. the pause is not recorded in the demo), but even just leaving the game running like in multiplayer would be fine.

**Comment by drfrag666** [comment]
In the end i've reverted all this stuff in RUDE and used a different approach, seems it's working. Instead of pausing the game i've disabled some menus.
https://github.com/drfrag666/RUDE/commit/2e60c5bd8886deff04e6ffc5b93f46616e9b0013
