### ISSUE TITLE
(Feature requests)

### ISSUE THREAD

**Issue by JuanchoES** [fabiangreffrath/crispy-doom#702]
### **Crispy Doom**  |    **crispy-doom-20201217-win32**

_1_- Why i cant bind some bindings to my mouse buttons? I want to bind the plasma rifle and the BFG to my side buttons of my mouse but i **CANT**.

_2_- The SFX sounds **low for my taste**, i want to hear the roar of the super shotgun more without raising the sound in my OS, i cant set the SFX sound higher cuz the max is 15 for some reasons.

_3_- i cant use correctly the Minor Sprite Fixing Project https://www.doomworld.com/idgames/graphics/sprfix19 WAD when playing custom wads, this **DOES NOT HAPPEN** in chocolate doom.

_4_- The secret found sound **sounds terrible**, it doesnt sounds rewarding, i really like the zdoom one https://www.youtube.com/watch?v=cgnG22K0Xq4

**Comment by fabiangreffrath** [comment]
> _1_- Why i cant bind some bindings to my mouse buttons? I want to bind the plasma rifle and the BFG to my side buttons of my mouse but i **CANT**.

Right, there is currently no way to bind specific weapons to mouse buttons.

> _2_- The SFX sounds **low for my taste**, i want to hear the roar of the super shotgun more without raising the sound in my OS, i cant set the SFX sound higher cuz the max is 15 for some reasons.

At 15 the sounds are played with their original undamped volume. However, there is no "boosting" or "overdriving" applied as other sound engines may do. All I can suggest is to adjust the music/sfx volume ratio in-game and then increase the game process's volume as a whole in your OS.

> _3_- i cant use correctly the Minor Sprite Fixing Project https://www.doomworld.com/idgames/graphics/sprfix19 WAD when playing custom wads, this **DOES NOT HAPPEN** in chocolate doom.

This is where it gets interesting. How exactly are you trying to load the Minor Sprite Fixing Project with custom WADs and how exactly does it not work?

> _4_- The secret found sound **sounds terrible**, it doesnt sounds rewarding, i really like the zdoom one https://www.youtube.com/watch?v=cgnG22K0Xq4

Crispy does not rely on external content but plays a seldomly played in-game sound (i.e. the multiplayer item respawn sound) when a secret is revealed. If you prefer ZDoom's sound, extract it from their assets and put it in a PWAD as DSSECRET lump and load this with Crispy.

**Comment by JuanchoES** [comment]
I was doing wrong with the sprite fix sorry 🤡

We may see in the future the requests 1 and 2 being added into crispy doom?

**Comment by fabiangreffrath** [comment]
Let's say, I'd not be opposed against a pull request (for Chocolate Doom!) that adds support for more mouse buttons - and for binding these to specific weapons. However, I have no plans to work on this myself currently. 

Regarding point 2, what else is the engine supposed to do other than playing sounds with full original volume?

**Comment by fabiangreffrath** [comment]
This isn't going to lead anywhere.
