### ISSUE TITLE
Widescreen assets do not fill screen

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#704]
Widescreen assets do not fill the screen.  This is especially noticeable with a widescreen hud.  The below image helps illustrate the issue (note the green on the left and right side of the hud).

![image](https://user-images.githubusercontent.com/2666951/103965094-d54fc200-5111-11eb-86f5-0e99cfff7658.png)

**Comment by fabiangreffrath** [comment]
Do you have your widescreen settings set to "Match Screen"? But even then there is some inaccurate rounding in place which leads to some obscure screen width values. Further elaboration is provided here: https://github.com/fabiangreffrath/crispy-doom/issues/521#issuecomment-587148000

**Comment by buvk** [comment]
Yes, I am using that setting.  I also experience the same issue if I set widescreen aspect ratio to 16:9.

Resolution: 1920x1080
aspect_ratio_correct 1

If I do not integer scale, the widescreen assets included with unity doom (E.g. title screen, help screen) stretch to 1912x1077.

Here is another screenshot:

![image](https://user-images.githubusercontent.com/2666951/104613698-550eec80-563c-11eb-9475-9e0a751d524a.png)

This does not occur with aspect_ratio_correct 0.

I can try to elaborate further if required.

**Comment by fabiangreffrath** [comment]
Should be fixed by https://github.com/fabiangreffrath/crispy-doom/commit/572116be34ead253ae9e7aac1264969b416ff3b7

**Comment by buvk** [comment]
Issue does not appear to be resolved.

**Comment by fabiangreffrath** [comment]
Hm, do you have high resolution rendering enabled? Do you have widescreen rendering set to 16:9?

**Comment by buvk** [comment]
This occurs with and without high resolution rendering.

Changing widescreen aspect ration from "match screen" to 16:9 resolves the issue.

**Comment by fabiangreffrath** [comment]
Ha! So, it's okay?

**Comment by buvk** [comment]
Yup, when rendering is set to 16:9, it is fine.  Widescreen assets are displayed at 1917x1080.  In-level is also displayed at 1917x1080.  The status bar appears correct.

The issue only appears now when it is set to "match screen".  Widescreen assets are displayed at 1912x1077 still.  The game itself is displayed at 1920x1077.  Not sure if this is intended or not.

**Comment by fabiangreffrath** [comment]
So, your screen's native resolution is 1920x1080, right?

**Comment by buvk** [comment]
Yep that's correct.

**Comment by fabiangreffrath** [comment]
Okay, I guess I'll better round SCREENWIDTH *down* to the nearest multiple of 4.
