### ISSUE TITLE
[suggestion?] pause key to pause demo playback

### ISSUE THREAD

**Issue by thom-wye** [fabiangreffrath/crispy-doom#706]
### Background

Version of Crispy Doom: 5.9.2

Operating System and version: win10

Game: Doom and Heretic

### Bug description

Observed behavior: during demo playback, the pause key in doom does nothing and in Heretic it brings up the game menu

Expected behavior: pause the video playback like during normal gameplay 

I actually don't know if this was vanilla behaviour, but it would make sense to me if it would work like that.

**Comment by fabiangreffrath** [comment]
Sounds  like a duplicate of https://github.com/fabiangreffrath/crispy-doom/issues/463,  right?

**Comment by thom-wye** [comment]
yeah sorry my bad
