### ISSUE TITLE
(crispy-heretic) demo fast-forward with -warp

### ISSUE THREAD

**Issue by thom-wye** [fabiangreffrath/crispy-doom#707]
### Background

Version of Crispy Doom: 5.10.0

Operating System and version: Win10

Game: Heretic

### Bug description

Observed behavior: using -warp together with -playdemo just starts the demo normally

Expected behavior: the crispy-doom behaviour where -warp fastforwards the demo to the requested level

**Comment by fabiangreffrath** [comment]
Thanks for the suggestion! This feature should be pretty straightforward to port from Doom over to Heretic, so please feel free to file a PR for this.
