### ISSUE TITLE
Suggestion: Widescreen Graphics Support?

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/crispy-doom#708]
Since Crispy has Widescreen support, I think it would be nice to see the addition of compatibility with the widescreen graphics as seen in the Unity Ports as well as GZDoom. Would this be doable?

**Comment by fabiangreffrath** [comment]
Erm, yes, that's the major new feature of the 5.10 release which is out since about a week now.

**Comment by OpenRift412** [comment]
Ohhhhhhh sorry!!
