### ISSUE TITLE
Text Colors

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/crispy-doom#709]
This is just a nitpick, but something to consider. I feel like the darkened red text color for the "SAVE GAME" option before loading a game and empty save slots as well as the yellow file name color of the quick save/quick load dialogues just feel slightly out of place. These colors of text aren't seen anywhere else in the port and feel slightly out of place, especially in other WADs that use custom menu lettering, it might mess with the design language a bit. Also the darkened red text gives more of the implication that you can't move your cursor over the option AT ALL. I'd consider reverting them to what they are in chocolate/vanilla for the sake of consistency and polish.

**Comment by fabiangreffrath** [comment]
Actually, the dark red menu entries aren't really "dark red", They are the original color, but darkened - which happens to be dark red for the IWAD menu font. For example, if you load a PWAD with a custom menu font in purple, orange or cyan, the disabled menu entries will not be dark red, but dark purple, dark orange and dark cyan. 

The yellow font color in the quick load / quick save dialogues just serves as a highlight to force people into reading that text. It uses the same color as the "A secret is revealed!" message or the colored status bar numbers.

I agree, though, that it might make sense to skip over disabled menu entries. I might give it a try, but hope you understand that this is pretty low priority for me. 😉

**Comment by OpenRift412** [comment]
> Actually, the dark red menu entries aren't really "dark red", They are the original color, but darkened - which happens to be dark red for the IWAD menu font. For example, if you load a PWAD with a custom menu font in purple, orange or cyan, the disabled menu entries will not be dark red, but dark purple, dark orange and dark cyan.

I know, I was just referring to the dimmed menu entries. I just think it would be a lot cleaner to remove the dimming effect altogether, at least on the main menu so the design remains more consistent. 

> The yellow font color in the quick load / quick save dialogues just serves as a highlight to force people into reading that text. It uses the same color as the "A secret is revealed!" message or the colored status bar numbers.

Right, but it seems a bit redundant as the fact that the save file name is already in quotes makes it stand out from the rest of the dialogue by default. I think having the new text colors focused solely around the "crispy features" of the port would probably make more sense design-wise.

> I agree, though, that it might make sense to skip over disabled menu entries. I might give it a try, but hope you understand that this is pretty low priority for me. 😉

I would disagree on that front. The sarcastic little messages you get when trying to save at the title screen or when trying to start a new game while in a network game maintain that oldschool quirkiness of games at the time. Like I said, it is only a nitpick, I just felt the need to bring it up.

**Comment by fabiangreffrath** [comment]
Hm, probably you are right. There were other more or less random "beautifications" of the Vanilla experience in the past which I eventually removed due to user request, e.g. the shaded menu background or text shadows. I  agree that everything that is inherited from Vanilla Doom should remain to look as Vanilla as possible. New features or dialogs may get some subtle colors to spice them up, though.
