### ISSUE TITLE
Capped framerate performance

### ISSUE THREAD

**Issue by phawq** [fabiangreffrath/crispy-doom#71]
Crispy Doom 3.0 with capped framerate is choppier for me than in 2.3.

**Comment by fabiangreffrath** [comment]
Could you please be a bit more specific about how you experience the performance issues? How do they manifest?

Does this happen always or only in very detailed scenes with very many monsters?
Does it also happen with the latest release of Chocolate Doom on which Crispy Doom is based upon?
Is this only related to the capped/uncapped framerate feature or do you have any other special features enabled as well?
Do you have any new sound features enabled, e.g. OPL3 emulation or randomly pitched sounds?
Does this happen with different HUD/view sizes?

**Comment by phawq** [comment]
It happens consistently, no matter what. even with different hud/view sizes
I have all special features disabled
I do not use OPL3 emulation or random pitched sounds.

I probably should have tested chocolate doom 2.2.0 before bring it up here, but the choppiness seems to be the case with that aswell compared to 2.1.0 version.

**Comment by fabiangreffrath** [comment]
If the same issue is also present in current Chocolate Doom, then I strongly believe it is related to this fix:
https://github.com/chocolate-doom/chocolate-doom/commit/d6556ee4b4d9d2c4c9ac48f998bd387f5416b75d

Before this fix, frames were accidentally rendered twice resulting in 70 fps instead of the intended 35 fps that Vanilla Doom runs with. However, this is really just a matter of identical frames being rendered and not related to the rate with which the game "thinks". Actually, it should improve performance significantly...

**Comment by phawq** [comment]
If it helps, I just tested Vanilla in dosbox, and did not experience this choppiness.

**Comment by phawq** [comment]
I'm thinking its not performance related at all, actually. As while both latest chocolate Doom and Crispy Doom are choppier in-game for me, my computer still runs perfectly smooth. I notice virtually no difference between the memory usage between older and newer versions of these ports, too. So not exactly sure why this is.

**Comment by fabiangreffrath** [comment]
I guess that the game's 35 FPS and the refresh rate of your screen are too much off of each other. Do you experience "tearing"? https://en.wikipedia.org/wiki/Screen_tearing

**Comment by phawq** [comment]
I do not experience any screen tearing. 

Even though it says 35 with SHOWFPS, It appears like its a lower framerate compared to Vanilla in Dosbox, and older versions of Chocolate and Crispy.

**Comment by phawq** [comment]
Adding "directx" as the video_driver in crispy-doom.cfg fixed the problem.

**Comment by fabiangreffrath** [comment]
Now that you mention it, I remember that both @bradharding and @fx02 once mentioned similar performance issues when video_driver was set to anything different than "directx". I have no idea if or how SDL changes this setting, though. I should have remembered this issue, but Windows is simply not part of my mind flow.

**Comment by fabiangreffrath** [comment]
I think this is fixed with the switch to SDL2 in Crispy Doom 5.0 and onward.
