### ISSUE TITLE
Suggestion: hurt floor indication

### ISSUE THREAD

**Issue by slashdevslashurandom** [fabiangreffrath/crispy-doom#710]
I would like to suggest an additional optional feature.

When enabled, the feature would provide an easy indication of when a player is standing on a damaging floor in a way where they can receive damage from it (which would be visible instantly, not just every 32nd tic). The possible options for it could be:

* disabled
* status bar face (displays the "ouch face", like in the press release beta)
* screen tint (uses the otherwise-unused palette number 1 from PLAYPAL, which is tinted slightly red)
* both

Granted, this is a purely aesthetic feature with little practicality (besides making WADs where hurt floors are added to arbitrary or unexpected sectors a bit easier to navigate?), but if possible, I would really like to see it in Crispy Doom.

**Comment by fabiangreffrath** [comment]
Hm, thanks for the suggestion, but what you are asking for is breaking with the game's visual consistency. I consider this too niche to add another menu item for it, sorry.
