### ISSUE TITLE
Recent commit breaks compiling under MSYS2

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#712]
https://github.com/fabiangreffrath/crispy-doom/commit/e674c555aa8f29d0e925ac89e9f9ae3213c110c4 breaks compiling under MSYS2.

g_game.c: In function 'G_DeferedPlayDemo':
g_game.c:2168:9: error: 'nodrawers' undeclared (first use in this function); did you mean 'numdrawsegs'?
 2168 |         nodrawers = true;
      |         ^~~~~~~~~
      |         numdrawsegs
g_game.c:2168:9: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [Makefile:495: g_game.o] Error 1
make[3]: Leaving directory '/home/buvk/crispy-doom/src/heretic'
make[2]: *** [Makefile:1115: all-recursive] Error 1
make[2]: Leaving directory '/home/buvk/crispy-doom/src'
make[1]: *** [Makefile:500: all-recursive] Error 1
make[1]: Leaving directory '/home/buvk/crispy-doom'
make: *** [Makefile:416: all] Error 2

**Comment by fabiangreffrath** [comment]
Yes, I know, I pushed a bit too early yesterday. Nothing serious, though.
