### ISSUE TITLE
(Suggestion) Support dedicated music tracks for Master Levels & NRFTL

### ISSUE THREAD

**Issue by DwarsYT** [fabiangreffrath/crispy-doom#713]
A few projects have been done or are in the works to replace the soundtracks for NRFTL and the Master Levels. The idea would be to have these levels have their own dedicated tracks that either default to regular tracks or can be written over with a WAD. This would be similar to how Episode 4 works in The Ultimate Doom, or how the repeat MIDIs work in Heretic. 

This way, it would be possible to play Doom 2 with its own soundtrack, then go to NRFTL or the Master Levels with their own MIDIs without having to swap WADs out.

**Comment by fabiangreffrath** [comment]
How are the dedicated music lumps for NRFTL and The Master Levels supposed to be named?

**Comment by DwarsYT** [comment]
I would imagine anything arbitrary would work. For example - d_mast01-22.midi for the Master Levels to go with their order on Crispy, and d_nerv01-09.midi for NRFTL.

**Comment by Arsenic-Trioxide** [comment]
Can this issue be revived? It's been dead for a while.
