### ISSUE TITLE
[REQUEST] Start Crispy Doom in base directory, not execution directory.

### ISSUE THREAD

**Issue by snoggie1487** [fabiangreffrath/crispy-doom#715]
If I set .wad files to open in Crispy Doom and double click one, it launches the game with default settings. I found Crispy Doom config files in the directory where I stored the WADs, indicating that it tried to start Crispy Doom as if the .exe was there. Most other source ports always execute in their install directory, allowing settings to be preserved. It would be really nice if this feature could make it's way to Crispy Doom, so that people like me can simply double-click a PWAD anywhere and have it work.

Thank you for taking the time to read this, have a good day.

**Comment by fabiangreffrath** [comment]
This is a bug (or feature, it depends on your point of view) inherited from Chocolate Doom, so I'd appreciate if you could move the discussion there. Thank you!
