### ISSUE TITLE
Packaging is more complete with autotools, but more binaries with CMake.  Which is preferred?

### ISSUE THREAD

**Issue by ryan-sg** [fabiangreffrath/crispy-doom#717]
Hey!  In working to create a packaged version of crispy-doom for OpenBSD, I initially just followed autotools approach, as I already had a port of chocolate-doom to work from.  I did notice only chocolate-doom and chocolate-heretic built, and was initially satisfied that this was by design.

That is, until I checked the build with CMake again, and noticed CMake builds __all__ the binaries. (hexen+strife too).

Okay, I'll rebase with CMake!  But wait, CMake __only__ builds binaries -- no docs, no icons, desktop files, or anything.

So I thought I'd look into the autotools files and notice that Hexen/Strife are mostly just commented throughout.  I've started the process of uncommenting them, but I wanted to get an idea of what is actually preferred upstream.

I found this previous issue, and looks like Debian still just follows the autotools method, only distributing Doom/Heretic binaries.  https://github.com/fabiangreffrath/crispy-doom/issues/234

Is there interest in a pull request to re-enable the entire build in autotools?  Should CMake instead be building the extra files eventually?

Thanks for a great project :)

**Comment by fabiangreffrath** [comment]
Please build the project with Autotools. The CMaje approach is not properly maintained. Game-wise only Doom and Heretic are actively developed and properly maintained, so the change to build only these two ports with Autotools was intentional. I didn't adapt this change to the Cmake build system merely because I don't actually care for it at all.

**Comment by fabiangreffrath** [comment]
NB: Note who uploads the Debian package. :wink:

**Comment by ryan-sg** [comment]
Awesome, thanks for clearing that up :)
