### ISSUE TITLE
Suggestion: Full size settings menu font

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/crispy-doom#724]
Just adding on to my previous comment from a while back regarding font colors, something else I always found weird was that the settings menu uses the small font instead of the larger font (I recall seeing other ports doing it too but that's besides the point). Did you already add this in a commit or no?

**Comment by fabiangreffrath** [comment]
The large font isn't really a font, actually. The whole menu is composed of pre-rendered graphics using the big font, but you don't have access to the individual glyphs. 

If you want the menu entries set in a big font, you'll need to provide an appropriate graphic in the M_CRISPY lump. Hint: Recent Freedoom snapshots have this.

**Comment by fabiangreffrath** [comment]
To elaborate a bit further: If one menu item graphic is missing, the whole menu will be rendered with the HUD font. Since no IWAD, except for the most recent Freedoom snapshots, contains the M_CRISPY graphic lump, the whole options menu is rendered in the HUD font. Once you provide this one missing lump from external resources, the whole menu will be rendered with the graphics lumps.

**Comment by OpenRift412** [comment]
> To elaborate a bit further: If one menu item graphic is missing, the whole menu will be rendered with the HUD font. Since no IWAD, except for the most recent Freedoom snapshots, contains the M_CRISPY graphic lump, the whole options menu is rendered in the HUD font. Once you provide this one missing lump from external resources, the whole menu will be rendered with the graphics lumps.

Yeah, I figured this out.

**Comment by fabiangreffrath** [comment]
So, how do we proceed here?

**Comment by OpenRift412** [comment]
> So, how do we proceed here?

Well perhaps you could include a PWAD in an autoload subdirectory that loads the large font by default and have the default autoload directory changed to ".\autoload\" instead of somewhere in AppData so it can be added by default in a fresh install.

**Comment by fabiangreffrath** [comment]
Thank you for providing that file! However, Crispy will neither come with nor depend on an external WAD file for additional assets. I'd rather leave Crispy as self-contained as it is and enable the user to "extend" their installations.
