### ISSUE TITLE
Super shotgun sprite bug toggle

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/crispy-doom#726]
I noticed that the super shotgun's firing sprite bug has been fixed in Crispy. Would it be possible to restore the bug and just add it as a togglable option? If so, maybe add this toggle to Woof as well?

**Comment by fabiangreffrath** [comment]
He, why exactly?

**Comment by OpenRift412** [comment]
> He, why exactly?

The main reason is that if people wanted the fix, they could load a dehacked like the one included with the [minor sprite fixing project](https://www.doomworld.com/forum/topic/62403-doom-2-minor-sprite-fixing-project-v19-release-updated-12718/).

I just think it's a bit revisionistic toward the IWADs themselves to include this change, since (to me anyway) Crispy Doom is a port that is essentially a modern shell for vanilla Doom with modern amenities (resolutions, fps, widescreen, etc.) and options to _add_ to the existing experience, but not change it. I know how pedantic that sounds, but I mostly say this stuff in the name of preservation of art, imperfections included.

**Comment by fabiangreffrath** [comment]
Crispy's objective is not preservation of bugs - we have Choco for that. 😉 My stance is that I fix obvious typos and oversights if they don't affect compatibility - and to me asynchronous nozzle sprite animations fall into the latter category. I could also argue that people who want the glitch back could load a DEH patch. 😁 

And there is no way I will revert a fix in Woof! that was introduced in MBF.
