### ISSUE TITLE
Can't run on ancient pc (The procedure entry point GetTickCount64)

### ISSUE THREAD

**Issue by vorob1** [fabiangreffrath/crispy-doom#728]
crispy-heretic-5.10.1-win32
Old laptop with GeForce 5 and Windows XP SP3
Heretic
Game won't launch and just show this error:

The procedure entry point GetTickCount64 could not be located in the dynamic library KERNEL32.dll

**Comment by JNechaevsky** [comment]
Take a try to use autobuild from http://latest.chocolate-doom.org/, it's seems to be working fine on XP Sp3.

**Comment by fabiangreffrath** [comment]
Sorry, but I won't be working on obsolete Windows version support.
