### ISSUE TITLE
[Feature Request] Triggers for fire

### ISSUE THREAD

**Issue by vanfanel** [fabiangreffrath/crispy-doom#733]
Hi,

This is not a bug but a suggestion.
Can triggers be supported as fire buttons? Currently, on an X360-compatible pad (8BitDo SN30-Pro USB) I am seeing that only buttons are detected in crispy-setup for fire/attack.
Thing is, L2 and R2 on this kind of "modern" controllers are not buttons, but triggers, so crispy-setup won't allow them to be set for fire or any other action.

**Comment by fabiangreffrath** [comment]
Everything input-related in this port is directly inherited from Chocolate Doom. So, if there is opportunity for improvement, it is usually better to discuss it over there, However, I am sure that better support for XBOX controllers has been requested before. The sheer lack of action by any of the developers might be a sign that none of us actually uses auch a controller or that there is simply not enough incentive to add specific support for them.

**Comment by fabiangreffrath** [comment]
https://github.com/chocolate-doom/chocolate-doom/issues?q=is%3Aissue+is%3Aopen+xbox
