### ISSUE TITLE
[Suggestion] Red blood for spectres with coloured blood on

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#736]
I noticed that the recent implementation of coloured blood in prboom+ lets spectres keep their red blood, while the coloured blood in Crispy gives it the same transparent fuzz effect. Since having this option toggled on in Crispy makes it more difficult to know if you hit a spectre or not at a glance, but some players might prefer it the way it is, I feel like having three options for this setting (off, on without transparent blood, on with transparent blood) is the best way to implement it.

**Comment by fabiangreffrath** [comment]
Nope, there won't be a "yes"/"no"/"maybe" switch for this. But since this has been criticized before, I am obligued to remove spectre blood altogether.

**Comment by SoDOOManiac** [comment]
> I noticed that the recent implementation of coloured blood in prboom+ lets spectres keep their red blood, while the coloured blood in Crispy gives it the same transparent fuzz effect. Since having this option toggled on in Crispy makes it more difficult to know if you hit a spectre or not at a glance, but some players might prefer it the way it is, I feel like having three options for this setting (off, on without transparent blood, on with transparent blood) is the best way to implement it.

I'm getting back to So Doom, my fork of Crispy, to practise as I'm searching for a job again.
I'll look into this as I started So Doom to add some features that Fabian rejected :)
