### ISSUE TITLE
Widescreen support for Heretic?

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/crispy-doom#737]
Would be cool if we could see Heretic in Widescreen. There's already graphics people have made to compensate for the issues with using the native ones in widescreen, so that issue solves itself. Is that doable or is there a certain hurdle in doing that?

**Comment by fabiangreffrath** [comment]
Duplicate of 
https://github.com/fabiangreffrath/crispy-doom/issues/637
