### ISSUE TITLE
Support for SIGIL music-packs

### ISSUE THREAD

**Issue by aarodynamics** [fabiangreffrath/crispy-doom#738]
### Background

Version of Crispy Doom: 20210417-win32

Operating System and version: Windows 10 20H2

Game: (Doom/Heretic/Hexen/Strife/other) Doom (SIGIL)

Any loaded WADs and mods (please include full command line): SIGIL_v1_21.wad

### Bug description

Observed behavior: I named music files in the music-packs directory d_e5m1.flac, d_e5m2.flac, d_e5m3.flac, etc and crispy-doom doesn't recognize them. 

Expected behavior: I'd hope crispy-doom would automatically look for SIGIL Episode 5 tracks in the music-packs directory. I'm trying to play higher quality versions of James Paddock's MIDI tracks.

**Comment by T-Will133** [comment]
Try to create a music config file for Sigil. To do so load Sigil into the Setup EXE, then hit Warp, then in the extra parameters, enter “-dumpsubstconfig SIGIL-Music.cfg” hit enter and it should dump a config file to read your flac files. Put it into the Music Packs folder along with the audio and it should work.

**Comment by aarodynamics** [comment]
@T-Will133 That worked! Thank you! Here's the output that I added to my doom1-music.cfg file: 
```
31e9932f8260b1e8ebd5e110af8749d46aa95365 = D_E5M1.flac
7211fc6f2f48cf1f27022690da6ed9b6363cb671 = D_E5M2.flac
f7fe0a11e9a5fe6aecdf6a36299df33dd201eaef = D_E5M3.flac
fdcbb17ba408bc90af2bc295a6f6e51dd650d247 = D_E5M4.flac
1d8a8dd6b374287b8848f2d65d4f6e0900b835e3 = D_E5M5.flac
921f7ac3bcb97e44f2c48b1ae79310848587d47b = D_E5M6.flac
e5b6631a1a657518371f61794cb7ff801ea57a68 = D_E5M7.flac
f86a6143fa0d5e38a2e09e011428bc867e3fb9a8 = D_E5M8.flac
f86a11a12f525210b973c52583841cea1fc8ec79 = D_E5M9.flac
bfac802f3fbbf9008ba0e74bfae46e5c687becb3 = D_SIGINT.flac
b7f165797cd500b351612b73267313f1df20a41e = D_SIGTIT.flac
```
