### ISSUE TITLE
Windows 8.1 mouse

### ISSUE THREAD

**Issue by fx02** [fabiangreffrath/crispy-doom#74]
Tried with v3.0 and directx driver, if I slightly touch mouse it would spin like crazy.
windib works fine but video is "jerky/slow".

Demo:
http://www.doom.com.hr/test.lmp

ps. this happens only on high resolutions 1600xYYYY or 1920xYYYY, on lower resolution it works fine.

**Comment by fabiangreffrath** [comment]
Let me guess, it's the same on Chocolate Doom?

Most probably it is a drivers issue or a problem with SDL then, which I have no chance of fixing from inside Crispy Doom.

Trivial question: Have you checked you mouse sensitivity/acceleration settings? Have you tried reducing the DPI and polling (hardware requests per second) of your mouse driver?

**Comment by fabiangreffrath** [comment]
This should be fixed upstream in the Chocolate Doom project and then merged into Crispy Doom. Most probably, it is already fixed by the switch to SDL2.
