### ISSUE TITLE
Possibly wrong translucency

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#740]
Not really happening in common cases, but take a try:

1. Run clean Crispy normally and enable translucency.
2. See how rocket explosion looks _([screenshot](https://user-images.githubusercontent.com/21193394/116666679-e9128300-a9a3-11eb-82dc-b2bc13847839.png), totally fine)._
3. Set gamma-correction level to maximum (4).
4. Quit game and remove `tranmap.dat` file.
5. Start Crispy and see again to explosion _([screenshot](https://user-images.githubusercontent.com/21193394/116666733-fd568000-a9a3-11eb-8859-b865753195e1.png), now it's notably darker!)_

Why this is happening: when we are composing a default transparent filter map based on `PLAYPAL`, we must call `I_SetPalette` (https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_data.c#L1102). 
However, `I_SetPalette` uses a `usegamma` variable, and briefly speaking -- the higher gamma level is set, the lower available colors are available in `R_InitTranMap` generation.

To fix this problem, we can use an initial (read: zerofied) gamma level, something like this in `R_InitTranMap`:
```
static void R_InitTranMap()
{
    int lump = W_CheckNumForName("TRANMAP");
+++ const int originalgamma = usegamma;

    // If a tranlucency filter map lump is present, use it
```
Now, before we calling `I_SetPalette`, we are setting gamma level to `0`:
```
+++	    usegamma = 0;
	    I_SetPalette(playpal);
	    // [crispy] background color
	    for (i = 0; i < 256; i++)
	    {
```
And after map file was generated, we are restoring gamma level to the needed level:
```
	free(fname);

+++     usegamma = originalgamma;
	W_ReleaseLumpName("PLAYPAL");
```

That's it. I believe it is safe to operate with `usegamma`, since game Doom loop is not started yet, and graphical window is not appeared.

**Comment by fabiangreffrath** [comment]
Good catch, thank you! Would you please file a PR for this?

**Comment by JNechaevsky** [comment]
Thanks! Sure, gladly, but only in the evening.

**Comment by fabiangreffrath** [comment]
No problem, this was wrong for years, so a few hours more won't matter. 😉 Please don't forget to add a small comment.

**Comment by JNechaevsky** [comment]
Of course, just thought about that. Are we okay to use following comments? I'm a bit worried about them, because despite of technically everything seems to be correct (including `const`!), I may wrong in spelling, and since this is not RD, having a "Russian English" definitely not a good way to go.

I'm also not sure about using a word/variable `original`, it's a proper term here, but can't find more appropriate one. Any ideas, please?

```
const int originalgamma = usegamma; // [crispy] remember original gamma level
```

```
// [crispy] set gamma-correction to zero so I_SetPalette can use a full color range
usegamma = 0;
```

```
// [crispy] restore original gamma level
usegamma = originalgamma;
```

**Comment by fabiangreffrath** [comment]
We only need the second comment, the rest is obvious. The wording is perfect!

**Comment by JNechaevsky** [comment]
All done here, fixed in https://github.com/fabiangreffrath/crispy-doom/pull/741. Hooray!
