### ISSUE TITLE
Wrong Episode names for Doom 2 unity iwad.

### ISSUE THREAD

**Issue by hackneyed-one** [fabiangreffrath/crispy-doom#742]
### Background

Version of Crispy Doom: Compiled from source. Latest commit was 2e0bf14 on Apr 30, 2021.

Operating System and version: Linux. Ubuntu 20.04.2 LTS.

Game: Doom2.wad from Unity v1.3

Any loaded WADs and mods (please include full command line): Just crispy-doom, doom2.wad (from unity 1.3) and nerve.wad in the current working directory. No previous config file. From console I run "./crispy-doom -config test.cfg"

### Bug description

Observed behavior: I wanted to check out the widescreen assets support for the Unity iwads but when I run doom2.wad (from unity v1.3) with nerve.wad in the same directory and start a new game it presents "Knee-Deep in the Dead" and "The Shores of Hell" as the 2 available episodes in the same big red font as if I was looking at doom.wad. Selecting either one starts "Hell on Earth" and "No Rest for the Living" respectively so its only cosmetic. It's probably got something to do with the Unity port iwad supporting Doom wads and episode lumps or whatever in addons for Doom 2.

Expected behavior: Obviously the expected behavior would be what happens when using the retail doom2.wad (v1.9) showing a smaller font with the proper names.

**Comment by fabiangreffrath** [comment]
Oh my, that's a complicated story. The Doom 2 IWAD did always contain the episode name graphics for Doom 1's episode selection menu - but of course they were never shown. Back then when the BFG Edition IWADs were released, the first two episode menu graphics in the Doom 2 IWAD were modified to match "Hell on Earth" and "No Rest for the Living", respectively. So, the decision was made to only show the graphic lumps if they are (a) from PWAD or (b) from a BFG Edition IWAD, which was identified by the presence of the DMENUPIC graphic lump - or render them in the HDU font else. Now it seems that the Unity IWADs still contain the DMENUPIC lump and are thus identified as BFG Edition IWADs but still contain the menu graphic lumps from Doom 1 without the adaption to read HOE and NRFTL, respectively. 😞

**Comment by hackneyed-one** [comment]
Ahh that would explain why I remember seeing the proper names in the big font before. I actually started the Unity wad a few times over a few days and didn't notice anything was wrong until I stopped to read it the other day and thought I'd gone mad for a few minutes. Interesting little hack the BFG team thought up.
