### ISSUE TITLE
Gamepad: Allow to bind gamepad buttons (and the d-pad) to weapon hotkeys

### ISSUE THREAD

**Issue by De-Seppe** [fabiangreffrath/crispy-doom#745]
### Background

Version of Crispy Doom: Crispy Doom 5.10.1
Operating System and version: Windows 10
Game: Doom
Any loaded WADs and mods: not relevant

### Bug description
Currently it is not possible to bind the directional pad (or other buttons) to weapon binds.
This is possible in the Unity port, and it makes the game a lot more playable with a controller.
Would it be possible to add "More Controls..." and "Other Keys..." to the "Configure Gamepad/Joystick" menu

**Comment by fabiangreffrath** [comment]
There is some ongoing work in Choco to improve gamepad input and I'd like to redirect you there.
