### ISSUE TITLE
The Unity Edition help page is still 4:3

### ISSUE THREAD

**Issue by inhumanesmoke** [fabiangreffrath/crispy-doom#746]
Crispy Doom displays all the correct 16:9 assets of the Unity Edition WAD except for the help page which is still 4:3.  I checked it with slade and the texture is indeed 16:9.

**Comment by JNechaevsky** [comment]
Is it happening in TNT / Plutonia? I've just checked last versions of these IWAD's, `HELP` lumps are still 320x200 there (however `TITLEPIC` and `INTERPIC` are 426x200).

**Comment by inhumanesmoke** [comment]
I'm using the Unity Ultimate Doom, doom.wad.  It's the HELP1.png.  The
texture is 426x200 but still displayed in 4:3.

**Comment by inhumanesmoke** [comment]
Sorry, not png.  Just looked at the downloadable assets from Bethesda to
find the name.  It is a doom graphic file.

**Comment by inhumanesmoke** [comment]
I figured it out.  It was caused by Doom Minor Sprite Fixing Project mod.
Sorry for the inconvenience.

**Comment by JNechaevsky** [comment]
Just though about possible replacement. :) Yep, full screen graphics from Sprite Fixing Project is not very friendly with wide screen assets,
