### ISSUE TITLE
Inherited from Chocolate Doom: SFX volume depends on Music volume

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#75]
Please comment here if you decide to make your own fix or wait till Chocolate Doom team fixes it and use their fix.
I noticed this bug trying to turn off music to zero volume, and the game sounds disappeared too.
Sounds like that SFX volume gets multiplied by music volume, SFX volume being less or equal to music volume as a result (equal when SFX volume slider is at maximum).

**Comment by fabiangreffrath** [comment]
Hi,

no, Crispy Doom won't get "its own" fix for this. If I *could* fix this, I would fix it in Choco first and then merge the change. This is nothing in which Crispy should deviate from Choco.

Also, I think SDL2 already has a fix for this built-in, so this will be fixed as a side-effect of switching to SDL2. This is currently prepared in the https://github.com/chocolate-doom/chocolate-doom/tree/sdl2-branch branch.

**Comment by bradharding** [comment]
> Also, I think SDL2 already has a fix for this built-in, so this will be fixed as a side-effect of switching to SDL2.

I don't believe it does, unfortunately.

**Comment by fabiangreffrath** [comment]
Oh, I was sure I have "read this somewhere". :-/

**Comment by Zodomaniac** [comment]
BTW, what's the difference between free look and vertical aiming?
I enabled vertical aiming, but the projected crosshair still auto-aims
vertically.

2015-10-14 13:00 GMT+03:00 Fabian Greffrath <notifications@github.com>:

**Comment by fabiangreffrath** [comment]
"free look" merely means that you can look around freely, it doesn't affect shooting in any way. "vertical aiming" means that you can shoot into the direction you are looking if autoaiming does not guide your shot.

I admit this is confusing and added the option for "direct aiming", i.e. no autoaiming at all, to the vertical aiming menu entry.

But, please, let's not derail this issue report any further and discuss different topics elsewhere.

**Comment by Zodomaniac** [comment]
For some reason it works correctly now! :)

**Comment by AlexMax** [comment]
I'm working on a fix for this in chocolate-doom/chocolate-doom#862.

**Comment by fabiangreffrath** [comment]
So, this will still be necessary with SDL_Mixer2?

**Comment by AlexMax** [comment]
Yes.  The underlying problem is with Windows Vista+'s playing of MIDI music, and SDL_mixer does not have any sort of workaround for it.

**Comment by fabiangreffrath** [comment]
This is "about to be fixed" with the introduction (and the recent changes) to the midiproc process on Windows.
