### ISSUE TITLE
[Suggestion] Toggle flashing effect after invulnerability expires

### ISSUE THREAD

**Issue by fivefivefiver** [fabiangreffrath/crispy-doom#751]
### Background

Version of Crispy Doom: 5.9.2

Operating System and version: Windows 10 v. 2004

Game: (Doom/Heretic/Hexen/Strife/other) Doom (others may apply)

Any loaded WADs and mods (please include full command line): N/A

### Bug description

Observed behavior: Once the invulnerability powerup starts expiring, it triggers a rapidly flashing full-screen effect. This is extremely uncomfortable to look at for people with photosensitive epilepsy.

Expected behavior: Could a toggle be implemented in the options menu that would allow the player to tone down the intensity of the invulnerability effect (or turn it off entirely)?

**Comment by fivefivefiver** [comment]
Additionally: I stumbled across [this post|https://forum.zdoom.org/viewtopic.php?f=18&t=66386#p1124875] on the zdoom forums which claims it's possible to disable the inverse colormap entirely in Crispy Doom, but I can't find the option anywhere. Is this a thing?

**Comment by fabiangreffrath** [comment]
I have implemented some basic A11Y features, among others the replacement of the invulnerability colormap effect by fullbright rendering, including the removal of the flashing at the expiration period.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/d3f169b70d0ed5f31936a87c62d79f7ac541cca4
