### ISSUE TITLE
Mancubus projectiles pass through walls.

### ISSUE THREAD

**Issue by JoBergeron** [fabiangreffrath/crispy-doom#752]
### Background

Version of Crispy Doom: 5.10.1

Operating System and version: Windows 10 version 20H2

Game: (Doom/Heretic/Hexen/Strife/other) Doom 2

Any loaded WADs and mods (please include full command line): currently playing with Doom 2 in Spain only https://www.doomworld.com/idgames/levels/doom2/megawads/d2iso

Command lines is: crispy-doom.exe -file D2ISO.wad -pistolstart

### Bug description

Observed behavior: Mancubus Projectiles sometimes pass through walls. It is very rare but by map21 of the wad I'm on, I've seen it happen 3-4 times. I'm fairly certain I've seen it happen on other wads I've played as well but I'm new to Crispy Doom and I've been playing a lot of Doom 1 wads recently so it's hard to recall exactly.

Expected behavior: The walls should block the projectiles.

**Comment by fabiangreffrath** [comment]
That's a Vanilla bug and thus expected behavior: 
https://doomwiki.org/wiki/Mancubus_fireball_clipping
