### ISSUE TITLE
[Feature Request] Stretched sky and normal sky toggle.

### ISSUE THREAD

**Issue by steve-marathon** [fabiangreffrath/crispy-doom#753]
The sky texture in Crispy is stretched vertically by default. I would like to ask for a feature in the crispiness menu where you can toggle either to stretch the sky or loop it, akin to how GZDoom can do it.

**Comment by fabiangreffrath** [comment]
> The sky texture in Crispy is stretched vertically by default.

Nope, it's only stretched if you have vertical look, mouse look or weapon recoil pitch enabled.

**Comment by rfomin** [comment]
But GZDoom doesn't stretch sky with mouselook by default:
![Screenshot_Doom_20210602_215533](https://user-images.githubusercontent.com/5077629/120503266-5a06e980-c3ed-11eb-977d-4703f58c6a38.png)
I think this is a nice effect, it would be great in Crispy.

**Comment by fabiangreffrath** [comment]
So, how does it do this? Does it simply blend the top line of the sky texture into a solid color? Is this achieved by an algorithm or is this hard-coded for the IWAD sky textures?

**Comment by rfomin** [comment]
> Does it simply blend the top line of the sky texture into a solid color?

I think it does. Maybe with gradient, I'm not sure, I don't use GZDoom much. It works for any sky.
