### ISSUE TITLE
Suggestion: For the Doom II Master Levels, make sure only the IWAD is loaded; ignore the Master Level WADs when loading PWADs

### ISSUE THREAD

**Issue by Some1NamedNate** [fabiangreffrath/crispy-doom#754]
### Background

Version of Crispy Doom: 5.10.1

Operating System and version: Windows 10 version 21H1

Game: Doom II

Any loaded WADs and mods (please include full command line): `crispy-doom.exe -file btsx_e1a.wad btsx_e1b.wad`

### Bug description

Observed behavior: I have the user env var `DOOMWADPATH` set to `X:\Path\to\DoomWADs; X:\Path\to\DoomWADs\MasterLevels`.
![image](https://user-images.githubusercontent.com/33171016/120843791-60977d00-c523-11eb-90a6-a251f8f76357.png)

Expected behavior: The Master Level WADs would be ignored when loading PWADs. Unless the PWAD(s) is a visual or sound-effect mod (such as the "Text to Doom" SFX PWAD).

**Comment by fabiangreffrath** [comment]
Hm, I don't see why there should be a problem as long as the Master Levels are separated into their own Episode?
