### ISSUE TITLE
SIGIL Spritefix WAD not working when applied while sideloading SIGIL alongside DOOM IWAD

### ISSUE THREAD

**Issue by Raddatoons** [fabiangreffrath/crispy-doom#756]
### Background

Version of Crispy Doom: 5.10.2

Operating System and version: Windows 10 Home v21H1

Game: The Ultimate DOOM

Any loaded WADs and mods (please include full command line): `crispy-doom.exe -file SIGIL_v1_21_SPFX.WAD` (I normally use ZDL to load and launch WADs.)

I use the automatic SIGIL sideloading feature, and am also using the WAD autoloading feature as well.  Due to this, my file paths are a bit spiderweb-esque in an effort to organize when I want to sideload vs frontload specific WADs.
My file path for each involved file are as follows if you want to recreate it exactly:
`D:\Games\Program Files\DOOM\WAD Stuff\CRISPY IWADs\Ultimate Doom\DOOM.WAD`
`D:\Games\Program Files\DOOM\WAD Stuff\CRISPY IWADs\Ultimate Doom\SIGIL_v1_21.WAD`
`D:\Games\Program Files\DOOM\Source Ports\Crispy Doom\autoload\doom.wad\D1SPFX19.WAD`
`D:\Games\Program Files\DOOM\Source Ports\Crispy Doom\autoload\doom.wad\D1DEHFIX.DEH`
`D:\Games\Program Files\DOOM\Source Ports\Crispy Doom\autoload\SIGIL_v1_21.WAD\(empty)`
I do use custom trimmed versions of the spritefix WAD for personal preference, but the issue also applies to the unedited version.

### Bug description

Observed behavior: Replaced default textures, such as the TITLEPIC seem to be 'spritefixed' properly, however SIGIL-specific textures (specifically looking at SIGILINT, SIGILTEX, and SIGILEND) do not seem to have the fix applied to them, regardless of how I load SIGIL_v1_21_SPFX.WAD.

![DOOM0002](https://user-images.githubusercontent.com/86673970/129142508-e8c30dc6-7e81-4504-b484-4d8d7c86b0b1.png)
![DOOM0003](https://user-images.githubusercontent.com/86673970/129142542-c6d64405-851c-41a1-b3e6-9b46953ba2d7.png)

I have tried adding it to `\autoload\doom.wad\`, I have tried loading it directly through ZDL (which I believe is close enough to loading it on the command line), and I also have tried using 5.10.2's new PWAD autoloading feature to add it to `\autoload\SIGIL_v1_21.WAD\`.  None seem to apply the missing spritefixes.

Expected behavior: When loading SIGIL_v1_21.WAD with a separated DOOM IWAD (frontloading SIGIL instead of sideloading it) and applying the spritefix, the proper SIGIL exclusive textures ARE fixed, and the `\autoload\SIGIL_v1_21.WAD\` folder also successfully applies the spritefix.

![DOOM0004](https://user-images.githubusercontent.com/86673970/129142693-f2f60840-9276-4cbf-9f80-dd888cf67abf.png)
![DOOM0005](https://user-images.githubusercontent.com/86673970/129142713-626d5387-d8db-40fc-9116-785a43dfd698.png)

This leads me to believe this is an issue with how Crispy Doom automatically sideloads SIGIL onto the IWAD if they are contained in the same folder.  It's a pretty small and kinda niche issue, but I'd definitely appreciate if you could look into it.

**Comment by fabiangreffrath** [comment]
The reason why this won't work is that sideloaded WADs are always loadded last, i.e. after all PWADs added on the command line and also the ones from the autoload directories are loaded. the rationale is that e.g. SIGIL.wad override texture definitions and must thus not get loaded if another PWAD has been loaded that already overrides texture definitions itself. Also, it must not get loaded if another PWADs has already been loaded that provides E5M1, e.g. 2002ADO.wad.
