### ISSUE TITLE
Silent Sound Effects (due to libsamplerate_scale)

### ISSUE THREAD

**Issue by pmjdebruijn** [fabiangreffrath/crispy-doom#758]
### Background

Version of Crispy Doom: 5.10.3
Operating System and version: Ubuntu 20.04
Game: Doom

Any loaded WADs and mods (please include full command line):
The issue isn't reliably reproducable, so I'm unsure if this is relevant, but for completeness sake I have the following patch applied, so crispy defaults to MIDI music:

**src/i_sound.c**
```
-int snd_musicdevice = SNDDEVICE_SB;
+int snd_musicdevice = SNDDEVICE_GENMIDI;
```

### Bug description

Observed behavior:
On a clean system with ~/.local/share/crispy-doom non-existant, I often get no sound effects. This varies per user, so somehow there is variability in first startup.

So I'm wondering whether there is a race condition, as the config with no sound effects has:
    `libsamplerate_scale           0.000000`

While the working config with sound effects has:
    `libsamplerate_scale           0,650000`

What's also remarkable, is that the config writer seems to be affected by locale? As floats are written with , as opposed to . which feels a bit odd... Not sure if that's actually relevant... As I'd always expected a decimal dot to be used in config files, and the UI to respect locale.

Expected behavior:
Always having sound effects

**Comment by fabiangreffrath** [comment]
Spontaneous hack:
```patch
--- a/src/m_config.c
+++ b/src/m_config.c
@@ -24,6 +24,7 @@
 #include <ctype.h>
 #include <errno.h>
 #include <assert.h>
+#include <locale.h>
 
 #include "SDL_filesystem.h"
 
@@ -1986,7 +1987,24 @@ static void SetVariable(default_t *def, const char *value)
             break;
 
         case DEFAULT_FLOAT:
-            *def->location.f = (float) atof(value);
+        {
+            struct lconv *lc= localeconv();
+            char *dec, *notdec, *str;
+
+            if (lc->decimal_point[0] == ',')
+            {
+                dec = ",";
+                notdec = ".";
+            }
+            else
+            {
+                dec = ".";
+                notdec = ",";
+            }
+            str = M_StringReplace(value, notdec, dec);
+            *def->location.f = (float) atof(str);
+            free(str);
+        }
             break;
     }
 }
```

**Comment by turol** [comment]
In your example `dec` and `notdec` should be `const`. I'm trying to fix all of those issues, don't add more of them :)

**Comment by fabiangreffrath** [comment]
No sweat, this was really just a short hack up. We should probably just replace the first non-digit char in the `value` string with `lc->decimal_point`.

**Comment by fabiangreffrath** [comment]
Like this;

```patch
--- a/src/m_config.c
+++ b/src/m_config.c
@@ -24,6 +24,7 @@
 #include <ctype.h>
 #include <errno.h>
 #include <assert.h>
+#include <locale.h>

 #include "SDL_filesystem.h"

@@ -2482,7 +2483,26 @@ static void SetVariable(default_t *def, const char *value)
             break;

         case DEFAULT_FLOAT:
-            *def->location.f = (float) atof(value);
+        {
+            struct lconv *lc = localeconv();
+            char dec, *str;
+            int i;
+
+            dec = lc->decimal_point[0];
+            str = M_StringDuplicate(value);
+
+            for (i = 0; str[i] != '\0'; i++)
+            {
+                if (!isdigit(str[i]))
+                {
+                    str[i] = dec;
+                    break;
+                }
+            }
+
+            *def->location.f = (float) atof(str);
+            free(str);
+        }
             break;
     }
 }

```

**Comment by fabiangreffrath** [comment]
I remember we once had a similar bug report in the Choco tracker, but I am unable to find it...

**Comment by fabiangreffrath** [comment]
Nope, that was even here:
https://github.com/fabiangreffrath/crispy-doom/issues/620

Regardless what caused the changing of the locale used for float formatting, we should probably have something like the above patch in place to be extra sure.
