### ISSUE TITLE
Suggestion: better RNG option

### ISSUE THREAD

**Issue by tertu-m** [fabiangreffrath/crispy-doom#759]
I did some local experimentation with this change and I found it would be relatively easy to implement and it also seems to have a noticeable effect on gameplay (for lack of a better word, all spread fire attacks seem "more punchy", from players and enemies alike).

**Comment by pmjdebruijn** [comment]
Wouldn't this break demo playback?

**Comment by fabiangreffrath** [comment]
> I did some local experimentation with this change 

Erm, which change?

**Comment by tertu-m** [comment]
As in, making M_Random use a better RNG than the doom random table

**Comment by JNechaevsky** [comment]
You can carefully use `rand()` as `M_Random` replacement and this can make wiping / player looking direction less "formulaic", but still looking vanilla enough. Making even a small touch of `P_Random` is a direct way to demo and netgame desync.

**Comment by fabiangreffrath** [comment]
Yep, and that's why it is out of question.
