### ISSUE TITLE
When playing multiplayer demos, the player mugshot background is always green

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#76]
I think that having the correct player color in multiplayer demos fits in Crispy's philosophy of fixing bugs and raising limits, doesn't it?

**Comment by fabiangreffrath** [comment]
Well, probably. Could you please elaborate a bit more about this issue, is it documented anywhere?

**Comment by Zodomaniac** [comment]
That's what Simon Fraggle of Chocolate Doom team said about this:
This is a Vanilla Doom quirk - during demo playback the status bar face
background is always that of the green player. (Here is the screenshot
where the green enemy is seen, so the player seeing him cannot be green but
has green background of the mugshot).​
 Crispy Screen 640x400.png
<https://drive.google.com/file/d/0Bycv-h0BCyw0Wi1wV29Td3ZWNnA5M1dqc0tpRENqTXQycENz/view?usp=drive_web>
​

2015-10-23 21:54 GMT+03:00 Fabian Greffrath <notifications@github.com>:

**Comment by fabiangreffrath** [comment]
I see. I guess you do not mean "spy mode", because here the background color deliberately remains that of the spying player. Could you probably hand me over a multiplayer demo that triggers this bug, i.e. a demo recorded by someone who was not player 1?

**Comment by Zodomaniac** [comment]
Here´s a demo with 4 players, recorded by Indigo player (not the player 1)
and the map it's recorded on.
The demo is recorded in v1.666 version.
The command line of the shortcut ends
with ...\crispy-doom_3.0\crispy-doom.exe -gameversion 1.666 -merge
!cross.wad -playdemo cross4


2015-10-24 0:00 GMT+03:00 Fabian Greffrath <notifications@github.com>:

**Comment by fabiangreffrath** [comment]
I see. This is because the `*faceback` patch pointer is set in `ST_loadData()` which is called from `ST_Init()`. However, `ST_Init()` is called very early in the game initialization process in `D_DoomMain()`, even before the actual demos files are loaded. So, at this early stage `consoleplayer` is always set to `0`.

I think I'll add another call to `ST_loadGraphics()` to `ST_Start()´, which is called in `P_SpawnPlayer()`, i.e. when the actual value of `consoleplayer` is known.

**Comment by Zodomaniac** [comment]
Nice work figuring this out! Hope you will release the new version this
weekend, vertical aiming and this demo issue being fixed))

2015-10-24 15:43 GMT+03:00 Fabian Greffrath <notifications@github.com>:

**Comment by fabiangreffrath** [comment]
> Hope you will release the new version this weekend,

I wouldn't hold my breath. ;)

> vertical aiming

Vertical aiming was never broken, it just wasn't made clear that auto-aiming would still kick in if appropriate. This is now optional.

**Comment by fabiangreffrath** [comment]
Fixed in https://github.com/fabiangreffrath/crispy-doom/commit/d12c95a2a84186c818e0a72609c100b450b0141e

**Comment by Zodomaniac** [comment]
1
