### ISSUE TITLE
Heretic monsters becoming inactive if a save is loaded

### ISSUE THREAD

**Issue by SiFi270** [fabiangreffrath/crispy-doom#766]
### Background

Version of Crispy Doom: 5.10.3

Operating System and version: Windows 10 Home 20H2

Game: (Heretic)

Any loaded WADs and mods (please include full command line): None

### Bug description

Observed behavior: It's easiest to recreate in E2M1. Simply attack from your starting position, listen to the gargoyles laugh, then quickly save and load to make them stop.

Expected behavior: It's accurate to Vanilla and Chocolate Heretic, but I'd like it to be more like Crispy Doom, with monsters remembering their target even after loading.

Sorry if you've already seen me say this on Doomworld, I just got more desperate after some failed saveless runs in E4M1 of Heretic.

**Comment by fabiangreffrath** [comment]
This will need porting over of `P_ThinkerToIndex()`, `P_IndexToThinker()` and `P_RestoreTargets()` from `src/doom/p_saveg.c` to `src/heretic/p_saveg.c`, which sounds like a doable task for a new contributor *hint*.
