### ISSUE TITLE
cannot record extended demos

### ISSUE THREAD

**Issue by thom-wye** [fabiangreffrath/crispy-doom#767]
### Background

Version of Crispy Doom: 5.10.2 and older

Operating System and version: Win 10

Game: Heretic

Any loaded WADs and mods (please include full command line): no

### Bug description

Observed behavior: when starting an episode from the command line with (or without) -demoext, the demo and game stops at the m1 exit

Expected behavior: a demo continues recording past the intermission screen and into the following maps

**Comment by fabiangreffrath** [comment]
Oh, could be I accidently broke it with this commit:
https://github.com/fabiangreffrath/crispy-doom/commit/3ee72e2dd807cfd97880c3bfeeaa42af403db246#diff-6b6c6bebb3c406e102f035ec9a89cc5603e7c887d10592799374b42d8a2372eb
