### ISSUE TITLE
[Feature request] Separate the colored blood and colored corpses options

### ISSUE THREAD

**Issue by El-Juancho** [fabiangreffrath/crispy-doom#769]
I love the colored blood but i dont like the corpses one, i like having doom marines on the doom maps im playing, not deathmatch players haha, i would like to have 2 options to choose and not only one please, thanks.

**Comment by fabiangreffrath** [comment]
I try to avoid feature micro-management and a crowded Options menu.

> i like having doom marines on the doom maps im playing, not deathmatch players haha

Consider them as your coops who died in previous attempts on the map. 😉

**Comment by rzhxiii** [comment]
Couldn't this go through the same process as spectre/ lost soul blood (poll to remove it entirely)?

**Comment by FozzeY** [comment]
What about a config option?
