### ISSUE TITLE
Crispy 3.2 is not reporting as Chocolate Doom 2.2.1

### ISSUE THREAD

**Issue by NickZ** [fabiangreffrath/crispy-doom#77]

**Comment by fabiangreffrath** [comment]
Sorry?

**Comment by fabiangreffrath** [comment]
@NickZ Could you please elaborate what exactly you consider an issue here?

**Comment by fabiangreffrath** [comment]
This bug report still makes no sense to me. Please re-open if you care enough to explain it to me with a bit more detail.

**Comment by fabiangreffrath** [comment]
I guess I know now what you meant and I believe it is fixed by this commit:
https://github.com/fabiangreffrath/crispy-doom/commit/946566ae01f8aa56bc549ec49c8bf97b81d34755
