### ISSUE TITLE
What is the resolution that's used when the widescreen option is enabled?

### ISSUE THREAD

**Issue by crispydoomsetup** [fabiangreffrath/crispy-doom#771]
Sorry to put this here!! I wanted to ask this question, but did not know where to go so I thought I could submit it here. I was just wondering, what is the resolution that's used when the widescreen rendering is enabled? I know when it's off that the resolution is 640x400. I have a 16:9 monitor, so I tried finding it out on my own and ended up getting 711.1x400.

**Comment by fabiangreffrath** [comment]
To be precise, it depends! :grin: 

No, seriously, the pixel ratios are as follows:
```
16:10 = 768x400
16:9 = 852x400
21:9 = 1120x400
```

For "match screen" it does exactly that and attempts to scale the framebuffer up to match your hardware resolution aspect ratio. The formula behind this can be found here:

https://github.com/fabiangreffrath/crispy-doom/blob/a3b7534cfe4b142a0b46180d7edf9b10a5df9e12/src/i_video.c#L1555
