### ISSUE TITLE
feature request, channel forwarder for wii u

### ISSUE THREAD

**Issue by jazzyjangles** [fabiangreffrath/crispy-doom#774]
hello if able can you please create a channel forwarder, to add a crispy doom channel to the wii u home screen? 

### Background

Version of Crispy Doom:

Operating System and version:

Game: (Doom/Heretic/Hexen/Strife/other)

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior:

Expected behavior:

**Comment by fabiangreffrath** [comment]
Sorry, but I don't even understand what you are talking about.

**Comment by Pedro-Beirao** [comment]
https://github.com/thearst3rd/crispy-doom-u
this is probably what you are looking for

**Comment by fabiangreffrath** [comment]
If there is already a dedicated fork for Wii-U, allow me to close this request.
