### ISSUE TITLE
[Feature Request] Allow users to set a sound font easily

### ISSUE THREAD

**Issue by Mechanical-sanity** [fabiangreffrath/crispy-doom#786]
So I really wanted to use this sc-55 sound font that I had, but it did not work very well with crispy doom. I did the environment variable setup, and it did not work as well as other source ports like prboom plus or gzdoom.

**Comment by rfomin** [comment]
Download the latest daily build of Crispy Doom from http://latest.chocolate-doom.org/, then unzip [fluidsynth-pack-crispy.zip](https://github.com/fabiangreffrath/crispy-doom/files/7585861/fluidsynth-pack-crispy.zip) into the Crispy folder, overwriting everything. Now you can customize the Fluidsynth soundfont path in crispy-doom-setup.exe utility or config and it will work.

**Comment by fabiangreffrath** [comment]
This has literally been added some two weeks ago.

**Comment by Mechanical-sanity** [comment]
> Download the latest daily build of Crispy Doom from http://latest.chocolate-doom.org/, then unzip [fluidsynth-pack-crispy.zip](https://github.com/fabiangreffrath/crispy-doom/files/7585861/fluidsynth-pack-crispy.zip) into the Crispy folder, overwriting everything. Now you can customize the Fluidsynth soundfont path in crispy-doom-setup.exe utility or config and it will work.

Where will I be able to find the fluidsnyth pack again? Will it be included in the next version of crispy doom?

**Comment by rfomin** [comment]
> Where will I be able to find the fluidsnyth pack again? Will it be included in the next version of crispy doom?

You can use the same fluidsynth pack with the next versions of Crispy Doom.
