### ISSUE TITLE
Config File Paths on macOS

### ISSUE THREAD

**Issue by aaronmmarks** [fabiangreffrath/crispy-doom#788]
### Background
Version of Crispy Doom: 5.10.3
Operating System and version: macOS 12.0.1
Game: Doom
Any loaded WADs and mods (please include full command line): n/a

### Bug description
Observed behavior: Crispy Doom writes a single config file to ~/Application Support/crispy-doom/crispy-doom.cfg

Expected behavior: Read/write CFG files in subfolders with the name of the WAD exactly how autoload already works. 
For example, config/doom.wad/crispy-doom.cfg, config/doom2.wad/crispy-doom.cfg, config/plutonia.wad/crispy-doom.cfg, and config/tnt.wad/crispy-doom.cfg
This would allow for separate config files depending on the WAD which would in turn allow for using separate Music Packs and more.

**Comment by fabiangreffrath** [comment]
This implies that you'll have to reconfigure key bindings, screen size, etc. for every new IWAD that you load. Is this really what you want? Also, what is the setup tool supposed to do about this? Ask not only which game but also which IWAD you are going to configure? Not really, or?

**Comment by mikeday0** [comment]
You should look into using the `-config` and `-extraconfig` command line options for this purpose.

**Comment by fabiangreffrath** [comment]
Yes, right.
