### ISSUE TITLE
Thy flesh consumed doesnt appear ingame

### ISSUE THREAD

**Issue by EmeraldTuxedo56** [fabiangreffrath/crispy-doom#789]
### Background

Version of Crispy Doom:5.9.2

Operating System and version: Windows 10 Education

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line):Doom.wad

### Bug description

Observed behavior: episode four wont load when double clicking on the wad to open it

Expected behavior: it would load

**Comment by fabiangreffrath** [comment]
Well, for me it does. Are you sure you actually have the Ultimate Doom IWAD? How many bytes is your doom.wad file?

![DOOM0002](https://user-images.githubusercontent.com/6449237/143821952-6f6b9878-6fe9-4af1-986f-d62d89c43496.png)

**Comment by fabiangreffrath** [comment]
Doesn't seem to be a problem the port could solve.
