### ISSUE TITLE
sprites visible in sectors with no headroom

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#79]
If `(sec->floorheight == sec->ceilingheight)`, things in these sectors should not be visible at all. However, Vanilla Doom draws them nevertheless, which leads to glitches like this one (the Medikit):

![doom01](https://cloud.githubusercontent.com/assets/6449237/11811963/1b7964b6-a339-11e5-8a73-a58c2bace4e6.png)

**Comment by fabiangreffrath** [comment]
Proposed patch, no idea if too invasive:

```--- a/src/doom/r_things.c
+++ b/src/doom/r_things.c
@@ -807,6 +807,9 @@ void R_AddSprites (sector_t* sec)
     // Well, now it will be done.
     sec->validcount = validcount;
        
+    if (sec->floorheight == sec->ceilingheight)
+       return;
+
     lightnum = (sec->lightlevel >> LIGHTSEGSHIFT)+extralight;
 
     if (lightnum < 0)      

```

**Comment by bradharding** [comment]
Hi Fabian. Which map in Freedoom is the above screenshot from (so I can check this problem in DR as well)?

**Comment by fabiangreffrath** [comment]
This is the new MAP06 (i.e. MAP03 from Jenesis). From the start, just IDCLIP and move backwards through two rooms.

However, I am sure you won't see this glitch in DR, because you already use Boom code for rendering and Boom has implemented proper clipping for situations like this. But, anyway, please tell me your findings. ;)

**Comment by fabiangreffrath** [comment]
Regarding my patch, this is just an immediate fix. I would prefer proper clipping, of course.

**Comment by bradharding** [comment]
> But, anyway, please tell me your findings. ;)

You're right. It clips fine.

BTW, Freedoom 0.10 is looking much nicer!

**Comment by fabiangreffrath** [comment]
Surprisingly, this little patch gets the clipping perfectly right, even in extreme cases as in the test map at http://greffrath.com/~fabian/spriteclip.wad .

```
--- a/src/doom/r_segs.c
+++ b/src/doom/r_segs.c
@@ -653,7 +653,7 @@ R_StoreWallRange
            ds_p->silhouette = SIL_BOTTOM;
            ds_p->bsilheight = frontsector->interpfloorheight;
        }
-       else if (backsector->interpfloorheight > viewz)
+       else //if (backsector->interpfloorheight > viewz)
        {
            ds_p->silhouette = SIL_BOTTOM;
            ds_p->bsilheight = INT_MAX;
@@ -665,7 +665,7 @@ R_StoreWallRange
            ds_p->silhouette |= SIL_TOP;
            ds_p->tsilheight = frontsector->interpceilingheight;
        }
-       else if (backsector->interpceilingheight < viewz)
+       else //if (backsector->interpceilingheight < viewz)
        {
            ds_p->silhouette |= SIL_TOP;
            ds_p->tsilheight = INT_MIN;
```
I am sure, however, that this radical patch is much too invasive, so further research is required.

**Comment by fabiangreffrath** [comment]
Hm, the patch seems to do the right thing. Honestly, I see no reason why sprites should be clipped by floors and ceilings only if they are above or below `viewz`, respectively.

Seems to be just another speed optimization? Or does anybody else have another idea?
