### ISSUE TITLE
Support for -fast launch parameter for Crispy Heretic/ Hexen

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#790]
### Background

Version of Crispy Doom: 5.10.3

Operating System and version: Windows 10 (32-Bit)

Game: (Heretic/Hexen)

Any loaded WADs and mods (please include full command line): N/a

### Bug description

Observed behavior: N/a

Expected behavior: N/a

According to https://doomwiki.org/wiki/Parameter#-fast, neither Heretic nor Hexen support this command. I tested it in both games and can confirm that this is true. If this is something that can be implemented without breaking too much stuff, I feel like it would make for a nice enhancement as it allows much more flexibility in terms of difficulty settings.

Edit: I thought about it a little bit more, and this can be expanded even further, to include all unique difficulty properties (double ammo for Doom, maybe an expanded "-respawn", half damage, keys shown on the automap for Heretic, auto-using Quartz Flasks/ Mystic Urns for Heretic and Hexen) as optional launch parameters, that way people could "choose" their own difficulty level. Again, no idea how much of this could be feasible or within the scope of the port.

**Comment by fabiangreffrath** [comment]
Contributors welcome!

**Comment by FozzeY** [comment]
How should an attempt to record a demo with additional options be handled? I'm thinking either refuse to start or print a warning and record a demo anyway.

**Comment by fabiangreffrath** [comment]
Refuse to start, just like the `-pistolstart` parameter. We must not record demos that don't play back in other ports.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/8bb1ccff060193ff1952a6d598eab0e983d4ef03
