### ISSUE TITLE
Sigil/NRFTL/Masterlevels Autoload doesn't override TITLEPIC lump

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/crispy-doom#792]
I noticed a small oversight where if I have say, widescreen assets in masterlevels.wad, nerve.wad, or sigil_v1_21.wad autoload subfolders folders while also having those respective WADs loaded in Crispy's base directory (so they'll show on the episode menu), they will just use the assets found in those autoload folders, instead of overriding them with what's found in the IWAD and the IWAD's respective autoload folder. 

For example:
![image](https://user-images.githubusercontent.com/29780788/145729491-61926e90-5d57-460a-9ce5-34abfd700a54.png)

Also, these additional episode options still appear when loading a custom PWAD as well.
Example seen with Back to Saturn X Episode 1:
![image](https://user-images.githubusercontent.com/29780788/145729531-b27c9432-dbf5-41b3-8d94-fe2cca470d2a.png)

**Comment by fabiangreffrath** [comment]
> I noticed a small oversight where if I have say, widescreen assets in masterlevels.wad, nerve.wad, or sigil_v1_21.wad autoload subfolders folders while also having those respective WADs loaded in Crispy's base directory (so they'll show on the episode menu), they will just use the assets found in those autoload folders, instead of overriding them with what's found in the IWAD and the IWAD's respective autoload folder.

It's not an oversight, I have been explicitly asked to add autoload support for sideloaded WAD files here:
https://github.com/fabiangreffrath/crispy-doom/issues/756

> Also, these additional episode options still appear when loading a custom PWAD as well. Example seen with Back to Saturn X 

That's be https://github.com/fabiangreffrath/crispy-doom/issues/754 . I guess I should fix that...

**Comment by fabiangreffrath** [comment]
Would it help if we had two separate command line parameters: `-nosideload` to prevent automatic loading of nerve.wad/masterlevels.wad/sigil.wad alongside the corresponding IWADs and `-noautoload` to prevent automatic loading of the files from the autoload directories?
