### ISSUE TITLE
DSSTNMOV sound crackles and I don't know why

### ISSUE THREAD

**Issue by thekovic** [fabiangreffrath/crispy-doom#794]
### Background

Version of Crispy Doom: 5.10.3

Operating System and version: Windows 10

Game: Doom 2

Any loaded WADs and mods (please include full command line): d64-snd.wad and light-test.wad (custom WADs, download link below)
[wads.zip](https://github.com/fabiangreffrath/crispy-doom/files/7721760/wads.zip)

### Bug description

Observed behavior: The sound DSSTNMOV is crackling and I don't know why. I exported the sound from Audacity as a 11kHZ, 8-bit, unsigned PCM .WAV file and used Slade 3 to import into the WAD file and convert to Doom Sound. As far as I'm aware, this meets all the requirements for sound format to play back correctly in Vanilla Doom. Here's a video with how it sounds: https://www.youtube.com/watch?v=IlJgLUsBGTE

Expected behavior: Sound that doesn't crackle. Use WADs I have disclosed above to comfortably test (light-test.wad is a map which spawns you in front of a button which makes a floor lower which makes the DSSTNMOV sound).

**Comment by fabiangreffrath** [comment]
Before I dig deeper into this, how does the same sound perform in other Doom engines, e.g. PrBoom+ or Woof?

**Comment by thekovic** [comment]
It crackles very noticeably in Woof 8.1.0. It crackles in PrBoom+ 2.6.1 too but much more quietly, it might not have been noticeable if I didn't crank up my volume to the max. I also tested GZDoom 4.2.4a where the sound didn't crackle.

**Comment by rfomin** [comment]
I tried vanilla Doom v1.9 in Dosbox and there are the same "crackles".

**Comment by fabiangreffrath** [comment]
Your sound is 1 ms shorter than the Vanilla pendant and has some ms of silence at the beginning and end. Maybe these subtle details already make the difference.

**Comment by thekovic** [comment]
Shouldn't a shorter sound mean that there's less chance for it to overlap though? I tried padding the sound with more silence to make it the same length as the vanilla sound and that didn't help. I haven't tried stretching it so that it's the same length while being non-silent the whole duration.

**Comment by thekovic** [comment]
Update: I made the new sound as long as the vanilla one but this time I did by slowing the sound down slightly rather than by padding it out with silence. There's a <1ms margin of error in the length now and it crackles much less now
[DSSTNMOV.zip](https://github.com/fabiangreffrath/crispy-doom/files/7739420/DSSTNMOV.zip)

**Comment by fabiangreffrath** [comment]
Turns out to be more of a problem with the sound sample than with the engine.
