### ISSUE TITLE
[Feature] Add option to toggle quicksave/-load confirmation

### ISSUE THREAD

**Issue by valsu** [fabiangreffrath/crispy-doom#795]
Feature request: Add an option to enable/disable the quicksave and quickload confirmation dialog.

**Comment by valsu** [comment]
I see this is the only open issue here without any comment. Will this be a "wontfix"?

**Comment by fabiangreffrath** [comment]
I'll probably implement it like this: 
https://github.com/fabiangreffrath/woof/commit/f567b7ab911f87c5b0c59b23eaa81eda3c57c2e8

**Comment by valsu** [comment]
> I'll probably implement it like this: [fabiangreffrath/woof@f567b7a](https://github.com/fabiangreffrath/woof/commit/f567b7ab911f87c5b0c59b23eaa81eda3c57c2e8)
Hey, that's great. I use Woof too, but didn't even notice that you implemented true quicksave just recently. Looking forward to having it in Crispy as well :+1:

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/7e2d78deff5bad4db062cfc80074bc353c217dd1
