### ISSUE TITLE
"Configure Keyboard" does not seem to work

### ISSUE THREAD

**Issue by dftf-stu** [fabiangreffrath/crispy-doom#803]
### Background

**Version of Crispy DOOM:** 5.10.3
**Operating System:** Windows 10 Version 21H2 (64-bit; non-ARM)
**Game:** DOOM II (DOOM2.WAD)

**Any loaded WADs and mods** (please include full command line):
**DOOM2.WAD** (inside the same folder as the _Crispy DOOM_ app files, launched via the "Save parameters and launch DOOM" option)
OR
**32OF64-V.WAD** (via command: "[path to crispy-doom.exe]" -IWAD "[path to DOOM2.WAD]" -file "[path to 32OF64-V.WAD]")

### Bug description

**Observed behaviour:**

Using the _crispy-doom-setup.exe_ executable, I reconfigured the keyboard controls via the "Configure Keyboard" option:

1. I pressed the DELETE key on controls I don't want mapped, which changes the mapping to "(none)" in the UI.
2. I then assigned new keys to certain other controls, and then saved the changes.
3. I then went back into the _crispy-doom-setup.exe_, back to "Configure Keyboard", and confirmed all the changes I made were retained.
4. And the "crispy-doom.cfg" file was successfully created inside the same folder.

However, when I start a DOOM game, it ignores virtually all of the mapping changes I made.
The only mappings that do work are for actions that are not configured by-default, such-as "previous weapon" and "next weapon".
But all other default mappings (such as CTRL for shoot, SPACEBAR for use) still function as-such, even-though I've set them not to.

**Expected behaviour:**

The key choices I make should be honoured in the game, and not disregarded and the default controls used instead.

For example, if I turn-off all the default alternate movement bindings (A, S, D and W) to "(none)", then I would expect these to all become non-functional in the game.  If I remap SHOOT from CTRL to something like Z or X, then CTRL should no-longer shoot and only the key I have assigned should then work.

I'm guessing that I perhaps don't understand how this feature works -- maybe users have to use a certain command-line argument to actually use their own customised controls?  Though, if so, I'd argue this is a bit illogical: surely most people would expect once you re-map controls, that those controls should then be used for all WADs going-forwards?

(As a workaround, for me to achieve what I would like (for my customised controls to get used in all future WADs I load), could anyone confirm that, were I to delete the "default.cfg" file, and then rename "crispy-doom.cfg" to "default.cfg", would that work?)

Thanks

**Comment by dftf-stu** [comment]
As an update: I have also tried using the "Configure Gamepad/Joystick" option.

If I setup each action, then press **T** to test, then all the mappings work correctly.

However, if I then press ESC to return to the main menu, then "Save parameters and launch DOOM", then none of them do.

(I'd not have thought something as simple as reconfiguring controls could be so dang awkward!  I think I'll just keep the default controls, and then use _JoyToKey_ to map my controller-buttons to the default keyboard ones.  Seems easier!)

**Comment by tpoppins** [comment]
> However, when I start a DOOM game

This is the key moment. It looks like the method you use to start Crispy does not set the working/current dir/folder correctly. You can go about it in various ways but the best way is to find a frontend, most of them will set the correct working dir automatically. 

ZDL is one of the more popular ones, originally for ZDoom but can be made to work with other ports too. For the past 20 years I used George Reagan's [Doomer](https://www.mediafire.com/file/5x6fa5iochxiqk6/Doomer1.2jSetup.zip/file). His site is long gone but that's a link to the last version (v1.2j) I kept archived. Looks old-fashioned but still works fine under Win7 x64, except for the Stats functions (those need an old version of MS Access installed). Supports all four classic IWADs, Heretic, Hexen and custom cmd-lines. Can handle WAD/DEH lists with thousands of entries easily. Optional preview of the entire command line before actually running it - great for troubleshooting.

Alternatively, you can create a shortcut to the Crispy exec with the cmd-line switches you want in the "Target" field and the dir/folder where the exec resides in the "Start In" field.

The location of the Crispy folder may be a factor as well. Unless you run everything under an Administrator account I wouldn't recommend putting Crispy (or Doomer) under %Program Files% or %Program Files (x86)%.

Tip#1: you don't need to specify the path to the IWAD if you keep your IWADs in the same dir/folder as Crispy -- but then you need to current/working dir set properly when you run it. You could keep your IWADs in another dir and set up the environment variable %DOOMWADDIR% pointing to it. Here's a tutorial on setting up system environment variables on Windows: [link](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/). It deals with %PATH% as an example but the same method works for any other %var%.

Tip#2: %DOOMWADPATH% does the same for PWADs.

If after all this you still have trouble with the working dir get [Process Hacker](https://processhacker.sourceforge.io/). It's kind of a Task Manager for the power user. Double-click on the Crispy process in the Processes list; the first tab (General) will have lots of info about the exec, including Current Directory. You can go on troubleshooting from there.

**Comment by dftf-stu** [comment]
Hi @tpoppins, thanks for the reply.

I tried launching DOOM in two ways, as a test.

First, I put the official "DOOM2.WAD" inside the same folder as the _Crispy DOOM_ app files, into a folder I have full-write permissions on (inside my _Downloads_ folder) and then used the "Save parameters and launch DOOM" option.  If you only have one .WAD file inside the same folder, it defaults to that.  But that didn't work.

I also tried as a test putting the _Crispy DOOM_ folder onto an external USB flash-pen, formatted as FAT32, which does not support any file or folder permissions.  I then tried launching a custom WAD as follows:
**"E:\Crispy DOOM\crispy-doom.exe" -IWAD "E:\Crispy DOOM\WADs\DOOM2.WAD" -FILE "E:\Crispy DOOM\WADs\32OF64V.WAD**
(I renamed the final WAD to remove the hyphen, incase it would be mistook for a command-line argument)

In both cases, my customised keyboard controls get ignored, and only the defaults are used.  Apparently (according to something I read elsewhere) this is actually _the expected behaviour_ and you have to add **-CONFIG** to the command-line, and then the settings file you want.  So it would be:
**"E:\Crispy DOOM\crispy-doom.exe" -IWAD "E:\Crispy DOOM\WADs\DOOM2.WAD" -FILE "E:\Crispy DOOM\WADs\32OF64V.WAD -CONFIG "E:\Crispy DOOM\crispy-doom.cfg"**

If so, then I would argue that this is a super-confusing way to go about it.  Whichever DOOM WAD you're playing, you're going to always use the same controls, surely?  I mean, unless you're going for something radically-different, like that _Sonic_ mod, then anything-else is going to involve shooting, strafing, running, opening doors, using switches and so-on.  So for most users, once you've set the controls how you like them, you'll then use them in every future DOOM WAD.

So I would expect when I make changes here, and save them, they should always get used:

![CrispyDOOMKeyboardConfig](https://user-images.githubusercontent.com/83965343/148054612-d57899a9-b1e0-4280-8609-d2688201ec39.png)

Not doing so makes the app feel broken.

**Comment by dftf-stu** [comment]
For anyone else looking to map a game-controller, it's honestly easier to just stick with the default controls, and then use the third-party app _JoyToKey_ to then do the mapping.  Here's my mapping to a PS1/PS2 era controller (with Analog mode off):

![CrispyDOOMMappingViaJoy2Key](https://user-images.githubusercontent.com/83965343/148056546-f684b4f0-4242-4fe2-9180-cf1f896f7acd.png)

You'll still need to use your keyboard for things like accessing the menu, saving and loading games, and zooming in and out on the Automap, but it'll cover all the main controls you need in-game.

**Comment by tpoppins** [comment]
> I then tried launching a custom WAD as follows:
> **"E:\Crispy DOOM\crispy-doom.exe" -IWAD "E:\Crispy DOOM\WADs\DOOM2.WAD" -FILE "E:\Crispy DOOM\WADs\32OF64V.WAD"**

Are you entering this in a command-prompt session (Command Prompt under Programs -> Accessories in Windows), from the Run... dialog box on the Start menu or as part of a batch file? Whichever way you're doing it, it's not going to work properly because the Working Directory is not set with the cmdline you use.

Here is how it should be done properly. For the sake of simplicity let's assume your Crispy is in E:\CRISPY so that we don't need quotation marks.

Open Command Prompt from Start menu or by running CMD.EXE from the Run... box. Change to E:\CRISPY
`cd e:\crispy`
or type "cd<space>" and drag the Crispy folder from Windows Explorer into the Command Prompt window.
Now you have E:\CRISPY as the Working Dir. The cmdline will be
_crispy-doom -iwad wads\doom2.wad -file wads\32of64v.wad_

Run... box: you need to employ the [START](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start) command to be able to set the working dir in this case:
`start /d e:\crispy e:\crispy\crispy-doom.exe -iwad wads\doom2.wad -file wads\32of64v.wad`

Batch file:
```
@echo off
e:
cd crispy
crispy-doom -iwad wads\doom2.wad -file wads\32of64v.wad
```

There's a fourth way - creating a shortcut to crispy-doom.exe - which I covered in my first post.

Now do you really want to muck with all these command lines when you could be using a frontend, click a couple of buttons and do zero typing?


> I renamed the final WAD to remove the hyphen, incase it would be mistook for a command-line argument
That was not necessary since cmd-line arguments are always preceded with <space>+hyphen.

**Comment by dftf-stu** [comment]
@tpoppins I created myself a "TEST" folder at the root of my "C" drive earlier (C:\TEST), removed all permissions, added the "Everyone" group, gave it full-access to that folder, and all subfolders, and then did some testing in there.  I created two folders, one called "CRISPY", another "Crispy DOOM", and extracted the latest ZIP download into both.  I tried using both batch files, and shortcuts, and **had no issues**: my customised controls **worked**.  (I was also able to configure by game-controller in-app, too!)

So clearly there was an issue in where my other two folders were located.

One of them was just in my **Downloads** folder, which is a location a user would have full-write access on by-default.  So there should be no issue there.  I also ensured the folder was not marked as "read-only".  It seems the issue there was that the _Ransomware Protection_ feature in the _Windows Security_ app was blocking the app from working fully, as I would have to create an exception for it.  (I'm not sure why it was allowed to create the "crispy-doom.cfg" and "default.cfg" files to begin with, as such actions should have been blocked).  Because I launch DOOM into Full Screen mode, I was missing the alert in the bottom-right to advise of an issue.

For the one that was inside **"C:\Program Files (x86)\Crispy DOOM"**.  I created the folder, removed all permissions (and took ownership), and then gave the "Everyone" group full-access to that folder, and all subfolders.  It turns-out the issue with that location was that Windows had created copies of the .CFG files inside "C:\Users\Me\AppData\Local\VirtualStore\Program Files (x86)\Crispy DOOM" and would always refer those files each-time.  I deleted the "Crispy DOOM" folder inside of that latter location and, from then, changes I made within the "C:\Program Files (x86)\Crispy DOOM" folder did work.

(As for the folder on my FAT32 flash-drive: not sure what went wrong there, but must have been something I was doing, as clearly there would be no file-permissions at-all there, and _Windows Security_ does not by-default do its _Ransomware Protection_ feature on external-drives, only usually a selection of your local user-profile folders.  Maybe something was set as read-only?  That's all I could think of...)

**SUMMARY (to help others)**

If you run _Crispy DOOM_ from one of your default Windows user-account folders (Documents, Desktop, Downloads, etc), go into Windows Security then "Virus & threat protection" then "Manage Ransomware Protection".  If it's on, you'll likely need to go to "Allow an app through controlled folder access" and add "crispy-doom.exe" and "crispy-doom-setup.exe" to it.

If you run _Crispy DOOM_ from inside one of the _Program Files_ folders, and your account is not an admin one, you may need to change the permissions on the "Crispy DOOM" folder to give it full-permissions.  If your keyboard remappings still don't work, bring up the Windows "Run" box, type in **%localappdata%\VirtualStore** and click OK.  Browse into the _Program Files_ folder you put _Crispy DOOM_ in, and if you see a folder with the same name (e.g. CRISPY) then delete it.  The app should now work.

If you run _Crispy DOOM_ from an external drive formatted with FAT32 or exFAT, the only thing to check is that the folder you put "Crispy DOOM" into is not marked as read-only.  If it's formatted as NTFS, you'll again have to set permissions on the folder to ensure you have full-write access.

**Comment by fabiangreffrath** [comment]
I guess the problem is the space character between "Crispy" and "Doom" in the directory name.
