### ISSUE TITLE
Don't skip-over single-barrel shotgun when using "Next Weapon"

### ISSUE THREAD

**Issue by dftf-stu** [fabiangreffrath/crispy-doom#805]
### Background

Version of Crispy Doom: **5.10.3**
Operating System: **Windows 10 Version 21H2 (64-bit; non-ARM)**
Game: **DOOM**
Any loaded WADs and mods: **DOOM2.WAD** (though could apply to any WAD)

### Feature suggestion

Observed behaviour:

I use the "Previous Weapon" and "Next Weapon" controls, as I play using a controller (as someone who grew-up with _PlayStation DOOM_ and _Final DOOM_, it's what I'm used to).

In _DOOM2_ WADs, if I currently have the pistol selected, and then use "Next Weapon" it skips-over the shotgun (single-barrel shotgun) and goes to the super-shotgun (double-barrelled shotgun).  You then have to press "Previous Weapon" to change to the single-barrel variant.

Expected behaviour:

It would be nice if when using "Next Weapon", there was an option added to make the order go:
Fist -> Chainsaw -> Pistol -> Shotgun -> Double-Barrelled Shotgun

**Comment by fabiangreffrath** [comment]
The "Next Weapon" feature is meant to emulate pressing the number buttons in increasing order in Doom.exe. This means after pressing "2" to select the Pistol, you press "3" and this will select the SSG if it's available instead of the SG. IIRC you'll have to press "3" again to select the SG if the SSG is currently available, which is emulated by pressing "Prev Weapon".

**Comment by dftf-stu** [comment]
Sure, but I mean technically you could argue in that method, doing a "previous weapon" shouldn't ever bring up the regular shotgun as you have to press 3 twice for that.  But clearly when you are on weapon 3, you have created an exception in the code to say something like "if on slot 3 and current weapon is super shotgun then press 3 again, else goto 2".

So in a similar fashion, could you not make it so if you're on the pistol, then do Next Weapon, the code would press 3 twice internally, then once on the next use?

As far as I can remember, the original DOS DOOM didn't offer a "previous weapon" or "next weapon".  It was only movement, strafe lock, run lock, shoot and use that you could put on a controller; weapon selection still had to be done on your nearby keyboard.  So there is no set "vanilla order" that must be followed here.

Yet in the console-ports of DOOM II (or Final DOOM), where they would always change weapons in a cyclical order, the shotgun would always come before the super-shotgun.  Seems odd not to do it the same way, especially given surely those who choose to use a controller to play are more-likely going to be those who grew-up with console DOOM?
