### ISSUE TITLE
[Feature] Allow weapon-changing while paused

### ISSUE THREAD

**Issue by dftf-stu** [fabiangreffrath/crispy-doom#806]
### Background

Version of Crispy Doom: **5.10.3**
Operating System and version: **Windows 10 Version 21H2 (64-bit; non-ARM)**
Game: **DOOM**

### Feature suggestion

Current behaviour:

It's not possible to change weapon while the game is paused.

Suggested behaviour:

It would be nice if an option for this could be added, so that, while the game was in "PAUSE" mode, as the user pressed "Previous Weapon" or "Next Weapon" you would see the weapons change at the bottom of the screen.  Then when you un-pause, you are ready to fire the weapon you changed to.

For those of us who use controllers, is this perhaps something that could be added as an option?  It would certainly make things easier than having to suddenly duck into a different room, or constantly circle-strafe, until the one we want comes-up!

Thanks

**Comment by fabiangreffrath** [comment]
Sorry, but if this wasn't possible in Vanilla Doom, I won't implement it in Crispy Doom either. Otherwise, you could record a demo in which you switch weapons during pause and it will desync when played back in any other port.

**Comment by dftf-stu** [comment]
> Sorry, but if this wasn't possible in Vanilla Doom, I won't implement it in Crispy Doom either.

I thought the whole point of Crispy was to add certain enhancements, but nothing that would make DOOM not feel like DOOM, such as 3D polygon character models, ray-tracing and so-on.

Surely this would fall in-line with only being a minor additional that doesn't radically change the game?

Regarding your demo concern, okay, maybe you could relegate it to being a command-line option only, and explicitly note in the documentation "using this switch will disable demo recording".  I've no intention of ever recording demos, so that wouldn't concern me...

**Comment by fabiangreffrath** [comment]
> I thought the whole point of Crispy was to add certain enhancements, but nothing that would make DOOM not feel like DOOM, such as 3D polygon character models, ray-tracing and so-on.

Not quite. Crispy doesn't change game logic or game physics or generally anything that would risk demo or netgame compatibility. There are like three exceptions and they are guarded in the code to get forcefully disabled if required. So, strictly speaking, 3D polygon models and raytracing would be more in line with the project goals than the change that you requested. 😉 

> Surely this would fall in-line with only being a minor additional that doesn't radically change the game?

Radical enough to break demo compatibility. As an example, changing the death sequence for the Imp by only one tic is also not a radical change, but it will break the whole game logic. Same with weapon changing during pause.

> Regarding your demo concern, okay, maybe you could relegate it to being a command-line option only, and explicitly note in the documentation "using this switch will disable demo recording". I've no intention of ever recording demos, so that wouldn't concern me...

Sorry, but do you have an idea how many command line switches Crispy would have if I added one for each rejected feature request that went against the project goals?

Again, sorry, but no.
