### ISSUE TITLE
"-wandstart -record" is allowed in Heretic

### ISSUE THREAD

**Issue by FozzeY** [fabiangreffrath/crispy-doom#807]
### Background

Version of Crispy Doom: Latest master, compiled on MSYS2 32-bit.

Operating System and version: Windows 10 64-bit.

Game: Heretic.

Any loaded WADs and mods (please include full command line): `crispy-heretic.exe -wandstart -record wandstart`
### Bug description

Observed behavior: Demo recording starts and completes normally.

Expected behavior: Heretic should not allow demo recording with custom parameters such as `-wandstart` and exit with an error message.

The cause of the issue I discovered is that in Heretic, unlike Doom, `G_RecordDemo` has its own call of `G_InitNew`, therefore the `CheckCrispySingleplayer` within `G_DoLoadLevel()` is called before `demorecording` is set to `true`.
https://github.com/fabiangreffrath/crispy-doom/blob/f9ff18da66ed901002810fc65014fe2c6a524928/src/heretic/g_game.c#L2094
https://github.com/fabiangreffrath/crispy-doom/blob/f9ff18da66ed901002810fc65014fe2c6a524928/src/heretic/g_game.c#L2151

Unfortunately, I'm not yet familiar enough with the overall structure to suggest a fix.

**Comment by mikeday0** [comment]
It should error out when you advance to the next level.

**Comment by fabiangreffrath** [comment]
So, it prevents desyncing multi-level demos at least. Anyway, the checks in the code should get moved a bit in order to error out as soon as possible if invalid options are given,

**Comment by mikeday0** [comment]
I say pull `G_DoLoadLevel` out of `G_InitNew` and then call it after the appropriate demo recording and playback variables have been set. It needs more testing, but this appears to do the trick:
<details><summary>Diff:</summary>
<p>

```diff
diff --git a/src/heretic/g_game.c b/src/heretic/g_game.c
index eefe96b1..61d2ebdc 100644
--- a/src/heretic/g_game.c
+++ b/src/heretic/g_game.c
@@ -1768,6 +1768,7 @@ void G_DoLoadGame(void)
     }
     // Load a base level
     G_InitNew(gameskill, gameepisode, gamemap);
+    G_DoLoadLevel();
 
     // Create leveltime
     a = SV_ReadByte();
@@ -1822,6 +1823,7 @@ void G_DeferedInitNew(skill_t skill, int episode, int map)
 void G_DoNewGame(void)
 {
     G_InitNew(d_skill, d_episode, d_map);
+    G_DoLoadLevel();
     gameaction = ga_nothing;
 }
 
@@ -1912,7 +1914,7 @@ void G_InitNew(skill_t skill, int episode, int map)
     memset(localcmds, 0, sizeof(localcmds));
     memset(netcmds, 0, sizeof(netcmds));
 #endif
-    G_DoLoadLevel();
+    // G_DoLoadLevel();
 }
 

@@ -2149,6 +2151,8 @@ void G_RecordDemo(skill_t skill, int numplayers, int episode, int map,
         *demo_p++ = playeringame[i];
 
     demorecording = true;
+
+    G_DoLoadLevel();
 }
 
 
@@ -2225,6 +2229,8 @@ void G_DoPlayDemo(void)
     {
       netdemo = true;
     }
+
+    G_DoLoadLevel();
 }
 
 
@@ -2276,6 +2282,8 @@ void G_TimeDemo(char *name)
     {
       netdemo = true;
     }
+
+    G_DoLoadLevel();
 }
```

</p>
</details>

**Comment by fabiangreffrath** [comment]
I'd rather factor the checks for the extra parameters out into a separate function and call this at the appropriate places, i.e. D_ConnectNetGame(), G_RecordDemo(), G_DoPlayDemo() and G_TimeDemo().

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/8bb1ccff060193ff1952a6d598eab0e983d4ef03
