### ISSUE TITLE
[Feature] Offer different formats for "Show Level Stats"

### ISSUE THREAD

**Issue by dftf-stu** [fabiangreffrath/crispy-doom#808]
### Background

Version of Crispy Doom: 5.10.3
Operating System: Windows 10 Version 21H2 (OS Build: 19044.1415) x64
Game: freedoom1.wad

### Feature suggestion

**Observed behaviour:**

If the user enables the "Show Level Stats" feature (ESC > Options > Crispness > Navigational > set "Show Level Stats" to "Always"), then their [k]ills made, and [i]tems and [s]ecrets found so-far for that map are shown.

For example, for C1M1 in freedoom1.wad (their equivalent of E1M1), when played on "Extreme Carnage", if they had killed 3 enemies, collected 6 items, but not yet found any secrets, they might see:
**K** 3/36
**I** 6/35
**S** 0/2

**Suggested behaviour:**

It would be nice to have an option where the user could change how the stats are displayed.

For example, I'd like "remaining only".  In that case, the stats would only count-down the number left for each on that map, to 0:
**K** 33
**I** 29
**S** 2

Or how-about a "as percentages" option, which would work the same as the "Finished" end-of-map stats screen:
**K** 8%
**I** 17%
**S** 0%

Or maybe just an option called "all or nothing" where it only reveals if you've found all of each count or not?  So assume I did find both secrets in the example map, but still had outstanding kills or items to collect, I might see:
**K** No
**I** No
**S** Yes

Thanks

**Comment by fabiangreffrath** [comment]
I like the idea. This would need a "Level Stats Format" menu item which offers the four different choices. Any takers?
