### ISSUE TITLE
Long wall error wad

### ISSUE THREAD

**Issue by AnotherLife** [fabiangreffrath/crispy-doom#81]
Can you test this wad that someone posted at prboom+ thread?
https://www.dropbox.com/s/e8u1yp83y4de5vl/longwall.wad?dl=0
It is broken in 3.2

It is the same issue as I reported to Doom Retro by the way, it should help:
https://github.com/bradharding/doomretro/issues/195

**Comment by fabiangreffrath** [comment]
Thank you very much for this bug report! 

I think this issue is already fixed in Crispy Doom since commit https://github.com/fabiangreffrath/crispy-doom/commit/e8a640cde3defd80872d2f3f63537b30af505ec0 .
