### ISSUE TITLE
Crash with SoundFont loaded

### ISSUE THREAD

**Issue by Gragt** [fabiangreffrath/crispy-doom#812]
### Background

Version of Crispy Doom: 5.10.3, latest commit (bf2343)

Operating System and version: Fedora 35

Game: Doom

Any loaded WADs and mods: only DOOM2.WAD

### Bug description

Observed behavior: When a SoundFont is loaded, Crispy-Doom launches normally and correctly plays the music with the selected SoundFont. But it promptly crashes as soon as the music should change with the error: “The process was killed by SIGSEGV: Segmentation fault”—sometimes no error message is given.

So far, this happens with *any* SoundFont, regardless of size, loaded either through the configuration menu or by setting the SDL_SOUNDFONTS variable. Crispy-Doom doesn’t crash with OPL3 emulation nor if MIDI is selected but no SoundFont is provided.

It is possible to warp to any level on startup and play normally, but it will crash as soon as it attempts to load another music track.

Expected behavior: Crispy-Doom doesn’t crash on music change when a SoundFont is loaded.

**Comment by fabiangreffrath** [comment]
Seems like the following bug is still not fixed in Fedora's SDL2_Mixer package:
https://www.fluidsynth.org/news/2021/01/23/sdl2-mixer-bug/

**Comment by fabiangreffrath** [comment]
No reply for three months.

**Comment by Gragt** [comment]
Silly me, I thought I had replied. Sorry!

In any case, the problem isn't with Crispy Doom but a Fedora dependency.
