### ISSUE TITLE
[Feature] Allow an option to force static-lighting

### ISSUE THREAD

**Issue by dftf-stu** [fabiangreffrath/crispy-doom#813]
### Background

Version of Crispy Doom: 5.10.3
Operating System: Windows 10 Version 21H2 (x64; non-ARM)
Game: DOOM2

### Feature suggestion

**Observed behaviour:**

Some areas in some _DOOM_ maps can feature dark areas.  While this is clearly by-design, it can make such parts difficult-to-see on some types of displays, or for users who prefer their screens to be less-bright overall.

**Suggested behavior:**

Consider adding a "force static lighting" option, similar to what the _Game Boy Advance_ port of _DOOM_ offered.  Code-wise I'd suspect all that option did when enabled was to run the "IDBEHOLDL" cheat on a constant loop (or maybe it gave the player one right at the start of each map, and alter their duration to match a _Berserk Pack_ -- 122,713,351 seconds)?

(I did check in the "crispy-doom.cfg" to see if such an option already exists; the closest one I found was "a11y_sector_lighting", but this made no-difference on the maps I tested.  I assume it likely disables _flashing_ light-effects, but I can't find a reference anywhere that explains what each option actually does.)

**Comment by fabiangreffrath** [comment]
> difficult-to-see on some types of displays

This sounds like the exact kind of use case for Gamma correction (press F11). This, and the IDBEHOLDL cheat should be enough to mitigate your issues, right?

> a11y_sector_lighting

This merely disables sectors changing their light levels for players who suffer from photosensitivity.

**Comment by JNechaevsky** [comment]
May I add my two cents, please?

> difficult-to-see on some types of displays
>
> This sounds like the exact kind of use case for Gamma correction (press F11). This, and the IDBEHOLDL cheat should be enough to mitigate your issues, right?

Well, not exactly, from my experience. Back in February 2020 I was playing Unity Edition on my cell phone while traveling on train. It was shiny winter day, and while sun was shining on phone's display, it was barely visible. Gamma-correction or brightness can't help in this case, because black/dark colors/areas are still black/dark. Unity, however, offers an useful feature - "Level Brightness', which is operating not with game colors, but with sector brightness.

Have a look, I have replicated it: https://github.com/JNechaevsky/russian-doom/commit/e237e65dca2669df0b78272638fabae3d158c680. It's not exact values/implementation as it was done in Unity, but it works just fine.

**Comment by fabiangreffrath** [comment]
Interesting idea, thanks @JNechaevsky. Is there any reason why you didn't just add the value to the `extralight` variable?

**Comment by JNechaevsky** [comment]
Honestly, I haven't thinked about it. If I'm getting things right, value `1...4` should be added here https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_main.c#L1045 ? 

Also, in current approach we can use an actual value of possible sector brightness (`0...255`), which is a bit more easy-to-understand.

**Comment by JNechaevsky** [comment]
Yeah, just tried `1...4` approach for `extralight` and compared them screenshot-by-screenshot with my current approach: pictures are absolutely same with both approaches, yay! Definitely worth to update the code, this will simplify things a bit. Thank you!

**Comment by fabiangreffrath** [comment]
You should be able to add up to `16` to `extralight` for an IDBEHOLDL effect.

**Comment by JNechaevsky** [comment]
Got it, thanks! Just need to think twice - is it really necessary. 

From one side: not really, this feature is not about permanent IDBEHOLDL effect, it should help to lit dark game areas in dark displays / real light conditions _(oh my, what a wording...)_. Even value `4` is bright enough and keeping some reasonable darkness. 
From another: well, why not, if user want it or need it, they can get it. IDBEHOLDL is not a hack but existing thing, and typing it every 2 minutes is not comfortable way to go. But again, always having no diminished lighting in the game is not a nice way, softly speaking.

P.S. Speaking about colors, now I have a whole Color Options menu (video is available [here](https://twitter.com/JNechaevsky/status/1444915928614031360)). Most of sliders aren't critically necessary, but Color Intensity can help to tweak game picture on displays with bad matrix. But it's a different topic, will gladly discuss it in another issue if you wish.
