### ISSUE TITLE
Sometimes MIDI music played incorrectly

### ISSUE THREAD

**Issue by skyrain128** [fabiangreffrath/crispy-doom#814]
### Background

Version of Crispy Doom: 5.10.3

Operating System and version: Windows 11

Game: (Doom/Heretic/Hexen/Strife/other) Doom 2

Any loaded WADs and mods (please include full command line): No custom command lines, No any mods, but I loaded Crispy Doom with ZDL

### Bug description

Observed behavior: Before I mentioned, MIDI music played incorrectly in Crispy Doom.
I use Roland JV-1010
This bug appears on latest release too.
This bug doesn't appear on Vanilla Doom or PrBoom+
I've recorded video in this time, but if I upload them here, It cannot be played (It says file is broken)

Expected behavior:
MIDI music should played correctly

**Comment by skyrain128** [comment]
https://user-images.githubusercontent.com/50762042/149171307-fd330857-efbb-4784-a974-b99b797a1f43.mp4


https://user-images.githubusercontent.com/50762042/149171322-88a09a89-b20c-4c04-bf01-785200949af3.mp4

**Comment by rfomin** [comment]
Try the latest daily build from this page: http://latest.chocolate-doom.org/
Recently, Windows MIDI support has been redesigned.

**Comment by skyrain128** [comment]
The MIDI bug is fixed in the latest daily build.
Also the latest build can adjust the music volume in option.

**Comment by fabiangreffrath** [comment]
Alright, let's close it then. Thanks!
