### ISSUE TITLE
[Suggestion] Expand number of controller-mappable actions

### ISSUE THREAD

**Issue by dftf-stu** [fabiangreffrath/crispy-doom#821]
### Background

Version of Crispy Doom: **5.10.3**
Operating System: **Windows 10 21H2**
Game: DOOM
Any loaded WADs and mods: N/A

### Feature suggestion

**Current behaviour:**

I primarily play _DOOM_ using a controller.

This mostly works well, as all of the main in-game controls are available, and it is also possible to navigate the menus with "Fire/Attack" acting as ENTER/Y and "Use/Open" acting as ESCAPE/N.

However:

- The **Automap** is very-limited: users can bring it on-screen, but that's it.  For all other features, such as Zoom In, Zoom Out, Follow Mode and Rotate Mode, they have to resort to using the keyboard.
- It's not possible to **Pause** the game, as this function cannot be mapped.  (You _can_ bring-up the _Menu_, which _effectively_ is like doing a _Pause_, though the background-music still plays, and I think while in the _Menu_ the timer still counts-up?)
- Nor is it possible to use the **Quick Save** and **Quick Load** feature.

**Suggested behaviour:**

(1) I would suggest adding the following new general mappings: "Pause", "Quick Save", "Quick Load".  The latter-two can be supported with a controller, as after pressing it only a Y or N response is needed: "Fire/Attack" can answer "Y" and "Use/Open" can answer "N".

(2) It should be possible to map the same controller button to both an Automap control (with the exception of "display Automap", which must be a unique button) and a non-Automap control.  When in the Automap, the Automap-function mapping would take precedence.  For example, outside of Automap view I might use **R2** as "Strafe Right".  When in the Automap though, this would become "Zoom In" and would not perform the strafe-right command.

(3) Assuming 2 is possible, then please add the following Automap mappings: "Zoom In", "Zoom Out", "Follow Mode", "Rotate Mode", "Overlay Mode", "Mark location" and "Clear all marks".

(4) A revamp of the "Configure Gamepad/Joystick" screen might be helpful to keep all the commands visible within the screen (to avoid scrolling-down).  One way to achieve this would be to group them by-category, and have the categories displayed to the left, which then changes the options shown on the right.

I've done some mock-up screenshots to show how this could look:

![CrispyDOOM_ControllerConfig1](https://user-images.githubusercontent.com/83965343/151068151-727dd712-6563-40cf-94e6-72c4d83abb88.png)

![CrispyDOOM_ControllerConfig2](https://user-images.githubusercontent.com/83965343/151068171-a9b23f2d-5f13-4258-9751-97baba813269.png)

![CrispyDOOM_ControllerConfig3](https://user-images.githubusercontent.com/83965343/151068179-817f4625-8bef-4520-95bc-94d0a12e11ac.png)

**Comment by fabiangreffrath** [comment]
Proper controller support (as e.g. Woof! has it) is a regular request. However, this would have to get implemented upstream at Chocolate Doom, because it would be in no way Crispy specific. There are already several such request over at the Choco tracker, and there is even a PR to improve the situation, but currently nobody is actively working on this. Me neither.
