### ISSUE TITLE
[Suggestion] Allow skip confirmation for Quick Load and Quick Save

### ISSUE THREAD

**Issue by dftf-stu** [fabiangreffrath/crispy-doom#822]
### Background

Version of Crispy Doom: **5.10.3**
Operating System: **Windows 10 21H2**
Game: DOOM
Any loaded WADs and mods: N/A

### Feature suggestion

**Current behaviour:**

When a user presses **F6** to Quick Save, they are asked to confirm:

> Quicksave over your game named
> "Example Title 1"?
> Press Y or N.

Similarly, when pressing **F9** to Quick Load, they are asked to confirm:

> Do you want to Quickload the game named
> "Example Title 1"?
> Press Y or N.

**Suggested behaviour:**

It would be nice to have an option to skip the confirmation -- so just answer "Y" on-behalf-of the player automatically.

So when F6 is pressed, it would instantly save (all the user would see is "GAME SAVED." in the top-left), and when they press F9 it would go straight to the "screen-melt".

This would be consistent with how most modern emulators work with their "save-states": no confirmation, just instant.

I'd suggest within the "crispy-doom.cfg" file, two lines could be added:
- quickload_confirmation 1
- quicksave_confirmation 1

When a value is set to "0", _Crispy_ would answer "Y" on the player's behalf and skip the prompt.
(Similar to how the "show_endoom" option skips a post-quit message when set to 0.)

Thanks

**Comment by fabiangreffrath** [comment]
> So when F6 is pressed, it would instantly save (all the user would see is "GAME SAVED." in the top-left), and when they press F9 it would go straight to the "screen-melt".

This is currently prepared, but without a config switch. Just plain quicksave/quickload:
https://github.com/fabiangreffrath/crispy-doom/pull/818

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/47e80fd3a5ad0d8e7cde1686aa46e3869039ed2d
