### ISSUE TITLE
[Suggestion] Add feature to create batch-file for user

### ISSUE THREAD

**Issue by dftf-stu** [fabiangreffrath/crispy-doom#823]
### Background

Version of Crispy Doom: **5.10.3**
Operating System: **Windows 10 21H2**
Game: DOOM
Any loaded WADs and mods: N/A

### Feature suggestion

**Current behaviour:**

If a user wants to start a custom "DOOM MOD" they'll need to know a series of commands in-order-to get it to load.

In some cases this can be quite simple, for example:
- crispy-doom.exe -IWAD DOOM2.WAD
- crispy-doom.exe -IWAD DOOM.WAD -FILE EXAMPLE.WAD

However once you have multiple WADs to contend-with, and "DEH" files, things can get very-complicated to those of us who are not as-experienced with how this sort of thing works!

**Suggested feature:**

It would be nice to see a feature in the app where it would create a "Batch File" containing the correct command-line for the user; all the user would do is select the relevant files, then ask the app to create the .BAT file.

Here's how it could work:

(1) In the ZIP file downloads (the ZIP you download the _crispy-doom_ app in), add some empty folders called "IWAD", "PWAD" and "DEH".
Users would then place files of those types into each respective folder from each PWAD they download.

(2) Then within the _crispy-doom-setup.exe_ app they could find a feature called something-like "Batch-File Creator", like this:

![CrispyDOOM_BatchFileCreator](https://user-images.githubusercontent.com/83965343/151077789-dae2bb9b-08ec-4155-aab9-1e6cb39f8416.png)

(3) Assuming the user has put the correct files in the correct folders, they would simply press ENTER on an _IWAD_, _PWAD_ or _DEH_ field to bring-up a scrollable-list of all files with that extension within that folder, then press ENTER to select it.
- They can press DEL or RETURN to clear an entry back to "(none)".
- They can use PAGE UP and PAGE DOWN to re-order the PWAD list.

(4) In the "Save folder" they can optionally type a name of a folder for all saves to go into.  If left at "(none)", the save files will simply go into the main folder, where all the _Crispy DOOM_ app files are.

(5) In the ".BAT Name", they enter what they want the batch-file to be called.  This field, along with the IWAD one, would both be mandatory.

(6) They press **C** to create the .BAT file.

Using the data I entered in my example screenshot, a file called **StartDOOMZero.bat** would be created.

Inside that file would be the following line:
**start crispy-doom.exe -IWAD IWAD\DOOM2.wad -merge -file PWAD\DoomZeroHQMusic.WAD PWAD\DOOMZERO.wad PWAD\Widescreen.wad -deh DEH\DOOMZERO.deh -SAVEDIR SAVES\DOOMZERO**

The .BAT file would be created at the root-level folder (the same one where all the _Crispy DOOM_ app files are).  This eliminates the need to give full paths, as the "working-directory" will default to "the folder where the .BAT was launched from".

Thanks

**Comment by fabiangreffrath** [comment]
Sorry, but no. This project is about developing a Doom source port. A "bat file creator" would be a separate project.
