### ISSUE TITLE
[Suggestion] Show extended stats for maps

### ISSUE THREAD

**Issue by dftf-stu** [fabiangreffrath/crispy-doom#824]
### Background

Version of Crispy Doom: **5.10.3**
Operating System: **Windows 10 21H2**
Game: DOOM

### Feature suggestion

**Observed behaviour:**

There is an option within _Crispy DOOM_ a player can enable to display some stats for the current map: kills made of total; items found of total and secrets found of total (if any).

These are enabled under Menu > Options > Crispness > Navigational > "Show level stats".

**Suggested feature:**

It would be great to see an option added titled "Show stats type" with options of "Map end tallies" or "Tallies and pickups".

"Map end tallies" would retain the current behaviour, only showing kills, items and secrets.

"Tallies and pickups" would display the remaining totals of those items in a map -- for example:
![CrispyDOOM_ShowSuperStats](https://user-images.githubusercontent.com/83965343/151155534-92865ea0-734a-4a4c-b019-5c4a75ec69a6.png)
**NOTE:** obviously you would use the same, nicer font as for the current stats (in the top-left) and not my example one!

For those of us who like to ensure we're fully stocked-up before the next map, this feature would be a nice time-saver as it would allow us to see if there is actually anything worth re-exploring the map to get.

**Notes:**
- **Ammo:** lowercase = smaller pickup type (e.g. "rkt" = "one loose rocket"); capitals = larger pickup type (e.g. "RKT" = "box of rockets")
- **Health:** 1 = Health Bonuses; 10 = Stimpacks; 25 = Medikits; 100 = Berserks + Supercharges; 200 = Megaspheres
- **Armor:** 1 = Armor Bonuses; A = standard armor (green); M = Megaarmor (blue) 
- For maps which do not include any of a particular item (e.g. there is no **blue key** in the _Plutonia_ map in my example), maybe hide such stats, rather than display them with a zero value, to make the display tidier?

Thanks

**Comment by fabiangreffrath** [comment]
Sorry I have to close another elaborate feature request by you, but this is just no. I am not going to turn the automap into a map statistics overview. This is better suited for a documentation site such as Doomwiki.

Apart from this, the sheer number of widgets this would introduce would be a nightmare to maintain. Also, there is no distinction between regular letters and capitals in Doom's HU font, so some of your ideas simply cannot get implemented as suggested.

Sorry, but this is really not the direction I want Crispy Doom to go. It has never been about "as much as possible" but about subtle changes that make the game a bit more pleasant.

**Comment by dftf-stu** [comment]
> Sorry, but this is really not the direction I want Crispy Doom to go. It has never been about "as much as possible" but about subtle changes that make the game a bit more pleasant.

Would you mind perhaps summarising what kind of suggestions you _are_ interested in?

I got the impression that as long as it's something that "adds to" the gameplay, but doesn't alter it, so demo playback would not break, then it should be valid.  Indeed in a previous reply you said adding something like ray-tracing actually would be closer to the goals of this project than something else I'd previously suggested.

But that strikes me as odd: such a feature would be for the GPU-accelerated ports, not one focused on software-rendering using only the CPU?

So could you perhaps offer some ideas around what kind of suggestions you're open to, or perhaps point me in the direction of another source-ports that are similarly not GPU-accelerated, as my laptop only has a weak on-board Intel HD chip, so I'd like to avoid all DirectX and OpenGL reliant ports.

Thank you!

**Comment by fabiangreffrath** [comment]
That raytracing thing was a joke with a core of truth. Of course I am not seriously considering to add or accept a raytracing renderer - but the massive changes that a new renderer is likely to introduce are probably more in line with the demo sync preserving policy of Crispy than a single line change that affects game physics.

Honestly, the project is in development for >7 years now and I am not eagerly waiting anymore for someone to suggest more and more features to implement. I don't yet dare to say that Crispy has reached its general mission goal but it's converging towards this. The latest changes during the 5.10 development phase were much more subtle than previously. I am not yet saying that Crispy is in maintenance mode, but actually it's not far from it.
