### ISSUE TITLE
70FPS framerate mode

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#83]
Currently, we have the choice between two evils: Either we select capped framerate at 35fps which somehow feels sloppy and coarse, or we chose uncapped framerate which feels smooth but in turn renders more frames than the screen could ever display and burns our CPUs and batteries.

What I am thinking of is a compromise, i.e. a rendering mode which displays twice the original framerate with interpolation. With 70fps we are closer to the refresh rate of most modern screens and simply doubling the frames rendered per game tic shouldn't be too complicated to implement. 

@AlexMax I am adding you to this ticket since you have implemented the original uncapped framerate mode in Crispy and might have an immediate idea how to achieve this.

Thanks!

**Comment by vanfanel** [comment]
But please, keep uncapped framerate option.

**Comment by fabiangreffrath** [comment]
Don't worry, it will be strictly optional, i.e. an addition to capped/uncapped
