### ISSUE TITLE
[Question] About the new quicksave changes...

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/crispy-doom#831]
Will these new changes to how quicksaving works be a toggle as was suggested in #795, or will it be the only option going forward?

**Comment by fabiangreffrath** [comment]
No, there will be no toggle. I don't like toggles. 

I am going to leave this as the only option forward. It's in line with how about any other game behaves and actually turns quicksave into something quick. Maybe I am even going to use it myself now.

**Comment by OpenRift412** [comment]
> No, there will be no toggle. I don't like toggles.
> 
> I am going to leave this as the only option forward. It's in line with how about any other game behaves and actually turns quicksave into something quick. Maybe I am even going to use it myself now.

Alright. Well in that case, I would highly recommend having the quicksaves occupy the standard save slots instead of having a single exclusive slot just for quicksaves. It's a bit of a digression of the feature and kind of limits its usefulness.

**Comment by fabiangreffrath** [comment]
You mean that you'd still have to select a quicksave slot when using quickload or quicksave the first time in a session, but from then on no further questions are asked? This sounds like a fair middle ground between Vanilla behaviour and the more radical change as has been introduced in Woof!.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/7e2d78deff5bad4db062cfc80074bc353c217dd1
