### ISSUE TITLE
Heretic/ Hexen widescreen assets/ WidePix issues

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#836]
### Background

Version of Crispy Doom: 5.10.3

Operating System and version: Windows 10 (32-bit)

Game: (Heretic/Hexen)

Any loaded WADs and mods (please include full command line): WidePix/ heretic_ws.wad/ hexen_ws.wad

### Bug description

Observed behavior: Not sure if this is a port issue or an asset issue, but I thought I'd post it anyways.
Most widescreen assets work fine, but e2end in Heretic crashes the game with an "Invalid fullscreen graphic". By default this is a .png, but converting it to the proper format doesn't seem to make a difference.
In both Heretic and Hexen, none of the widescreen weapon sprites work.

Expected behavior: if this is an issue with the way the port handles it (which I doubt it is considering the assets were made with GZDoom in mind), it might be worth looking into. If it is an asset issue, both me and the other people who made these types of .wads need to improve their wad-making skills. Thought I'd post it anyways since I saw nobody else mentioning this.

**Comment by fabiangreffrath** [comment]
@mikeday0 Could you please have a look at this?

**Comment by rzhxiii** [comment]
I just remembered that this might be even messier to diagnose.
I made this thread: https://www.doomworld.com/forum/topic/127157-editing-custom-skies-into-heretic-crispy-heretic/.
Long story short, at least one graphical glitch was caused by a bug in Slade.
So this could either be caused by the assets themselves, by Slade or be an implementation issue.
Sorry for the headache I'm causing, I wish I knew more about this type of stuff.
I'm going to keep on testing and tweaking until a solution is found, but I'm afraid I'm not really available today.

**Comment by fabiangreffrath** [comment]
So, is this still an issue?

**Comment by mikeday0** [comment]
As far as fullscreen graphics go, the original Heretic/Hexen only supports 320x200 images in a linear raw format. Raw in this context means that the graphic is encoded as an array of 64000 (i.e. 320 * 200) one-byte palette index values which get directly fed to the screen buffer. I recently added support to Crispy for fullscreen graphics in patch format, which in turn enables support for the wide fullscreen assets. The fullscreen patch has to be exactly 200 pixels high and at least 320 pixels wide, otherwise an error is called. (@fabiangreffrath Is that a reasonable check, or am I being too restrictive?) There is no support currently for png.

> Also the widescreen weapon sprites from https://www.doomworld.com/forum/topic/64778-heretic-minor-sprite-fixing-and-widescreen-friendly-project-v10-release/ seem to be working properly.

Yes, these are the sprites I tested with.  @rzhxiii Can you share the other widescreen sprites that you are having trouble with?

**Comment by fabiangreffrath** [comment]
> @fabiangreffrath Is that a reasonable check, or am I being too restrictive?

Sounds reasonable to me.

**Comment by mikeday0** [comment]
>Edit: did some more quick testing, converting e2end with an older version of Slade made it display properly (although that also screwed up the palette, so it's definitely an issue with that application, not Crispy nor WidePix).

Apparently the `E2END` graphic is supposed to use its own special palette `E2PAL`. I'm not well versed in Slade, but I'm wondering if you can specify it to use this instead of `PLAYPAL` when converting the e2end png.

**Comment by rzhxiii** [comment]
So I did more testing.
The good news: the implementation seems to work perfectly. The HUD always worked, and so did titlepic, intermission screens, etc. The issues were caused by my own (and other's) lack of knowledge + conversion shenanigans.
Essentially, in order for the weapon sprites to work, they require two additional files in the .wad (S_START and S_END). This is probably common knowledge. I didn't know about the E2PAL thing, going to try it out real quick as well, but I think it's safe to assume that this issue can be closed.

**Comment by JNechaevsky** [comment]
> I'm wondering if you can specify it to use this instead of PLAYPAL when converting the e2end png.

It is possible to apply `E2PAL` with some tricky way. Here's how, I will use `HELP1` gfx to demonstrate:

1. Choose `E2PAL` palette lump, then right click on it and select "Palette > Add to custom palettes".
![image](https://user-images.githubusercontent.com/21193394/152823654-72421387-a958-422d-8320-45610ff5b28c.png)

2. Name it something like "E2PAL".

3. Set global palette to new "E2PAL":
![image](https://user-images.githubusercontent.com/21193394/152823992-78765e11-6c78-4b32-8339-b6594ed94e4c.png)

4. Now import any kind of PNG lump supposed to be `E2END` lump.

5. Convert newly imported graphics via "Graphic > Convert to..." and choose:
* Doom Flat (Paletted).
* Current graphic: Existing / Global.
* Converted graphic: E2PAL.
* Transparency flag does not seems to be needed.
![image](https://user-images.githubusercontent.com/21193394/152825451-fcf28cfb-8a88-4d7b-88f1-bc2978888304.png)

6. All done, the result:
![image](https://user-images.githubusercontent.com/21193394/152825231-6688aab0-5dc2-4155-a573-87b04b8b90f0.png)
