### ISSUE TITLE
(Heretic/Hexen) Crispy Settings reset when saving settings in crispy-setup

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/crispy-doom#838]
Seems like crispy-setup doesn't take Heretic and Hexen's crispy settings into account when saving changes, you may want to look into that.

**Comment by mikeday0** [comment]
You sure about Heretic? I can repeat this with Hexen but not Heretic. Also I can see why this is broken: I failed to bind the crispy variables in src/setup/compatibility.c. Sorry about that!
