### ISSUE TITLE
Incorrect vertical offset in sky when switching free look on in game

### ISSUE THREAD

**Issue by plumsinus** [fabiangreffrath/crispy-doom#84]
Hi Fabian, funny bug I just noticed. If you start Crispy Doom with freelook off, and then turn it on in the Crispness menu, the offset on the sky will be too low. If you mouselook up with the Crispy HUD (or just no statusbar), you will be able to see the sky tile. This seems to persist until you exit and restart the program.

No more info about the crashing problem yet, sorry.

Screenshot, in case that wasn't clear:
![doom00](https://cloud.githubusercontent.com/assets/5642091/12789359/81db3fb4-ca6b-11e5-8d5c-ffa66f13d6d6.png)

**Comment by fabiangreffrath** [comment]
Incredibly good catch, thank you very much for noticing!
