### ISSUE TITLE
Strafe On doesn't allow strafing in Heretic

### ISSUE THREAD

**Issue by Lippeth** [fabiangreffrath/crispy-doom#840]
### Background

Version of Crispy Doom:
5.11 (Also 5.10.3)

Operating System and version:
Windows 10 64x 21H1

Game: (Doom/Heretic/Hexen/Strife/other)
Heretic

Any loaded WADs and mods (please include full command line):
none

### Bug description

Observed behavior:
Holding Strafe On intercepts look movement but doesn't allow strafing with key or mouse.

Expected behavior:
Holding strafe key and/or mouse button allows strafing.

**Comment by fabiangreffrath** [comment]
Please check if you have set "Options -> Mouse Sensitivity -> Horizontal: Strafe" set to `0`.

**Comment by fabiangreffrath** [comment]
@mikeday0 Seems like we indeed need to explicitly bind these settings as well in the setup tool.

**Comment by fabiangreffrath** [comment]
9cb9604d903d3767f92d17ed91b9a9daf5870ed8
