### ISSUE TITLE
[Suggestion] Mouse wheel to scroll through the inventory in Hexen

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#842]
### Background

Version of Crispy Doom: N/a

Operating System and version: N/a

Game: Hexen

Any loaded WADs and mods (please include full command line): N/a

### Bug description

Observed behavior: N/a

Expected behavior: N/a

Since this is already a thing in Heretic, I thought it would be nice to have it in Hexen as well.

**Comment by fabiangreffrath** [comment]
This was added to Chocolate Heretic in inherited from there. Please request implementation for Chocolate Hexen.

https://github.com/chocolate-doom/chocolate-doom/commit/e9e76ede1b18ad4fa5d5816419d1e334f7752cf9
