### ISSUE TITLE
crispy-strife not building 

### ISSUE THREAD

**Issue by ConHuevosGuey** [fabiangreffrath/crispy-doom#843]
### Background
Latest git

Operating System and version:
Linux Slackware 15.0

### Bug description
Crispy strife does not build alongside the other binaries of crispy-doom when using the readme build commands.  I'm unsure what the issue is but after performing the following commands:

`  autoreconf -fiv
 ./configure
 make`

All binaries are built EXCEPT strife.

**Comment by fabiangreffrath** [comment]
The secret magic command is
```
cd src
make -C strife
make crispy-strife
```

**Comment by ConHuevosGuey** [comment]
Thanks.  Didn't see anything about this in the Readme's.

**Comment by fabiangreffrath** [comment]
That's because Crispy Strife doesn't even officially exist. So, psst. 😉

**Comment by ConHuevosGuey** [comment]
Thanks again.
