### ISSUE TITLE
[Bug] Jumping while being crushed causes clipping issues

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/crispy-doom#844]
### Background

Version of Crispy Doom: 5.11.1

Operating System and version: Windows 7 Home Premium

Game: Doom

Any loaded WADs and mods: None

### Bug description

Observed behavior: Attempting to jump while being crushed (by a crushing ceiling) will make the player clip into the floor. It appears that upon jumping, the player's Z coordinate begins to depend on the ceiling height instead of the floor height.

Expected behavior: Crushing should play out as normal, as it would if the player were not to jump, therefore not triggering this bug.

**Comment by MrAlaux** [comment]
As a follow-up, I believe I have a fix for this:
Just prevent jumping altogether if `mo->ceilingz - mo->floorz` isn't greater than `mo->height`, which is what should be happening when the player is being crushed. I could probably make a PR for something so simple, but I really don't want to mess it up.

**Comment by fabiangreffrath** [comment]
Sorry, but this won't help either. The crusher may catch you mid-air and then this condition branches into the `else` case and calculates `thing->z` from `thing->ceilingz` and `thing->height` instead of `thing->floorz`:

https://github.com/fabiangreffrath/crispy-doom/blob/dc865155ea9dddd2138fbac6661565e0b6c169e8/src/doom/p_map.c#L655

However, I am too coward to change anyting in `p_map.c`, so I'll just fix `player->viewz` to never get below `player->mo->floorz` - so rendering will be fixed but game physics remain untouched. (Consider a player running into a crusher from an elevated platform.)

**Comment by fabiangreffrath** [comment]
> (Consider a player running into a crusher from an elevated platform.)

Or an Archvile jump in a crusher. No, player's `thing->z` must not get changed, but I can make sure that their `viewz` does never fall below floor level.

**Comment by tpoppins** [comment]
> but I can make sure that their `viewz` does never fall below floor level.

Not the best idea. Player's view dropping through the floor when dying under a door is one of the coolest vanilla bugs/features, and this change quashes it to accommodate a zdoom-like crutch?

IMO this change should have an 'if (crispy_jump)' guard somewhere.

**Comment by fabiangreffrath** [comment]
Alright, understood. I'll revert this commit and add an extra condition to jumping to check available headroom.

**Comment by tpoppins** [comment]
Weird, I just got around to testing the reverted commit and it didn't seem affect the aforementioned bug. Perhaps the bug takes a different codepath?

Test demo: [scion-death-under-door.zip](https://github.com/fabiangreffrath/crispy-doom/files/8120806/scion-death-under-door.zip)
Requires [SCION.WAD](https://www.doomworld.com/idgames/levels/doom/s-u/scion). You can fast-forward to the player picking up the yellow key.

Sorry for the false alarm, Fabian.

**Comment by fabiangreffrath** [comment]
Never mind! It feels better anyway to add some extra restriction to a non-canonical Crispy feature than to dick around in some original Vanilla code. 😉
