### ISSUE TITLE
SIGIL E5M8 Boss Death flags active

### ISSUE THREAD

**Issue by Raddatoons** [fabiangreffrath/crispy-doom#845]
### Background

Version of Crispy Doom: 5.11.1

Operating System and version: Windows 10, 21H2

Game: Doom

Any loaded WADs and mods (please include full command line): -file SIGIL_v1_21.wad

### Bug description

Observed behavior: I was recently playing `SIGIL_v1_21.wad` on HNTR, but when I reached the final level, the game unexpectedly cut to the end when I defeated the Spiderdemon boss.

I have not tested this on HMP or UV, where a Cyberdemon will also spawn, to see how it affects the boss flags.

I have observed this bug in multiple source ports, the main ones being Woof!, Crispy Doom, and PrBoom+.  I wasn't sure if it was a shared piece of code between these source ports causing the issue or if they each have unique issues, but I am intending to make unique bug reports for each one.

Expected behavior: I think it was designed for any source port's non-vanilla (>4) episodes to have boss flags inactive by default for their respective final levels, but I believe those flags have been enabled on accident.  Using `SIGIL_COMPAT_v1_21.wad` does not have this issue as it has specific DEHACKED flags to disable the Spiderdemon's boss death flags on E3M8.

**Comment by fabiangreffrath** [comment]
Yep, this shows how well developed Sigil is. A commercial add-on for Doom, by one of the creators of Doom, but unfortunately incompatible with... Doom. 😉 

By default, in Vanilla Doom, a boss action is triggered if a boss monster is killed on any map 8 - with no further checks for type of monster for episode > 4:

https://github.com/chocolate-doom/chocolate-doom/blob/9546b2f0392a606bb6220671741525ba40480685/src/doom/p_enemy.c#L1660

In Crispy, I have fixed this at least for the side-loaded SIGIL.WAD. But if you explicitely load is as a PWAD on the command line, this check fails so far. I will fix it by extending it to any PWAD called SIGIL that provides a fifth episode.

https://github.com/fabiangreffrath/crispy-doom/commit/e68a08d10911875f9380d4ecbd27ce00821b236c#diff-5ba161a44e06f3c5d19696d5f3afe9a5bf35bdeb9a1b087ceb274b8b1e4b3301L1717
