### ISSUE TITLE
[Suggestion] Removing Heretic ambient sound limit

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#847]
### Background

Version of Crispy Doom: N/a

Operating System and version: N/a

Game: Heretic

Any loaded WADs and mods (please include full command line): N/a

### Bug description

Observed behavior: at the moment, Crispy Heretic keeps the vanilla ambient sound limit as described in https://doomwiki.org/wiki/Heretic_ambient_sound_things

Expected behavior: if it is possible to remove it without breaking compatibility, this could make for a nice enhancement.

**Comment by JNechaevsky** [comment]
A minute of attention, please! There is interesting bug in Heretic ambient sounds, described at [DoomWiki](https://doomwiki.org/wiki/Heretic_ambient_sounds_stop_playing). Really not noticeable until you know about it, but once you know...

Article says that it is not safe for demos to fix it, and this absolutely correct if we touch `P_Random` call. However, it is still possible to fix it safely. I've made and debuging print example and fixing commit here: https://github.com/JNechaevsky/inter-doom/issues/240

**Comment by fabiangreffrath** [comment]
Thank you for the heads up! Sorry, but I doubt that the fix you applied is really demo compatible. By preventing `AmbSfxTics` from becomming `0` at this point, you prevent the `switch` command in `P_AmbientSound()` from being skipped and thus `P_Random()` is being called more often than without your fix.

I'd suggest to turn `P_Random()` in `P_AmbientSound()` into a function pointer that points to `P_Random()` first (and gets reset to it in `P_InitAmbientSound()`) and then to `Crispy_Random()` (or whatever you call it) once the fix becomes necessary.

**Comment by JNechaevsky** [comment]
Thanks for explanation! I must be extremely lucky by not having desyncs in original shareware/registered/retail demos then. Better I just follow your approach, it is always safe. ☀️
