### ISSUE TITLE
[Feature] Autoload for Hexen

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/crispy-doom#853]
It seems that other than Doom or Heretic, Hexen does not support the autoload feature yet. Neither autoload nor music pack entries are created in the ini. Tested with latest binaries (v5.11.1).

**Comment by mikeday0** [comment]
Hmm, I can't seem to reproduce this. If I run crispy-hexen with a non-existent crispy-hexen.cfg, the file is created with autoload_path and music_pack_path on lines 28 and 29. Are those variables completely missing from your crispy-hexen.cfg?

**Comment by NightFright2k19** [comment]
I was using x64 builds [compiled by atsb](https://github.com/atsb/source-port-builds/releases). Apparently those are not really complete. With the ones from this repo, entries are made. Therefore, false alert.
