### ISSUE TITLE
[Bug/Feature] Radsuit tint on automap

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/crispy-doom#855]
Not sure right now if it was like that in the original game, but it doesn't look right:
When the Radiation Suit is active and you switch to automap view, the green tint does not disappear. (Maybe the intention of this is to know when radsuit is wearing off while walking around in automap view, but the usefulness is still questionable.)

**Comment by fabiangreffrath** [comment]
The green radsuit tint is a palette effect and thus affects everything that is drawn on screen (in contrast to e.g. the invulnerability effect, which is a colormap based).
