### ISSUE TITLE
[Bug] Crispy Doom: Cutscene rendering broken in truecolor

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/crispy-doom#857]
In latest Crispy Doom 5.11.1 truecolor builds, cutscene graphics panels (e.g. PFUB1/PFUB2 at the end of ep.3) are rendered in a blue tint, ignoring the actual game palette.

**Comment by fabiangreffrath** [comment]
Actually, it doesn't have that much to do with the game palette. It is just that in truecolor mode, each pixel is a four byte tupel holding the ARGB values - whereas in palette mode each pixel is a single byte holding the palette index. Without the fix I applied yesterday, the palette index would get written into the ARGB tupel, occupying only the lowest byte, i.e. the B/blue value, thus rendering the scene entirely in shades of blue.

**Comment by NightFright2k19** [comment]
Something learned, then. It didn't seem to happen with any other cutscene panel, just the ep.3 scroller. With that fixed, my Ultimate Doom test run with the truecolor build is complete, and it was literally the only issue I was able to find. Currently going through a Doom 2 PWAD to see if there's anything worth reporting there. So far, everything is very smooth, no crashes or weird behavior.

**Comment by NightFright2k19** [comment]
In the meantime:
Ep.3 scroller tint issue in truecolor confirmed to be fixed with latest snapshot.

**Comment by fabiangreffrath** [comment]
💪
