### ISSUE TITLE
Heretic staff sprite bug/ oversight when attacking + moving with minimal HUD

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#858]
### Background

Version of Crispy Doom: N/a

Operating System and version: N/a

Game: Heretic

Any loaded WADs and mods (please include full command line): N/a

### Bug description

Observed behavior: If you use the staff (the equivalent to Doom's fist) while moving backwards, or diagonally, or in random directions, with the max screen size (minimal hud), there's a chance that the offset of the sprite might be moved further enough to the left, that the right end of the sprite is displayed on the screen. This is technically either vanilla behaviour or a Chocolate Doom bug, not sure since it also happens in Chocolate Doom, but I don't have a DOSBox version to test on the go.

Expected behavior: not sure if anything can be done about this, widescreen assets fix the issue in 4:3 aspect ratio, and I guess this is something that would fit the Heretic Minor Sprite Fix project better.
![HTIC05](https://user-images.githubusercontent.com/82729328/158493437-43e38ba9-b538-469f-8480-a7ea932651b8.png)
This is the only screenshot I could grab with my bindings, because moving backwards, attacking and taking a screenshot at the same time is uncomfortable, but I feel this illustrates the issue better than I can describe it.

**Comment by fabiangreffrath** [comment]
Sorry, but there is really nothing that the port could do about this. If the sprite is too short to the right side, that what it is. What's needed is a more complete sprite, but as you already pointed out yourself, that's a matter for a different project and nothing that the source port could fix.

**Comment by rzhxiii** [comment]
Yep, much as I suspected.
No point in keeping this open then.
