### ISSUE TITLE
[Feature] Hexen: Support for widescreen replacement sprites

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/crispy-doom#859]
Current Hexen builds still have issues with some widescreen replacements for some weapon sprites.

Some of the patch columns contain posts >128px, causing the graphics to be drawn at wrong locations. This vanilla limitation has been already lifted for Doom and Heretic, but is still missing in Hexen.

**Comment by fabiangreffrath** [comment]
That'd be DeepSEA tall patches, right? No problem. Could you post some example sprites here?

**Comment by mikeday0** [comment]
> That'd be DeepSEA tall patches, right? No problem. Could you post some example sprites here?

[hexwide.zip](https://github.com/fabiangreffrath/crispy-doom/files/8289307/hexwide.zip)

I don't think they are in DeePSea format actually. I first ported over the DeePsea support and they still didn't render correctly. I have to implement the full crispy-doom or crispy-heretic R_DrawColumn function in order for them to look right.

**Comment by NightFright2k19** [comment]
Here some extracted examples. Not all of these might be problematic, but some of them definitely are
![FAXEO0](https://user-images.githubusercontent.com/54737241/158876167-94469f48-a41e-40fc-983a-7f66b7708656.png)
![FHMRB0](https://user-images.githubusercontent.com/54737241/158876172-f728ddda-cb44-42f2-b7fa-a2b55389ac7f.png)
![FHMRC0](https://user-images.githubusercontent.com/54737241/158876174-f5199b06-9b61-4f53-a54f-3b956c4193ce.png)
![FAXEB0](https://user-images.githubusercontent.com/54737241/158876175-66427eab-0047-4313-8fae-c969ced5fa45.png)
![FAXEC0](https://user-images.githubusercontent.com/54737241/158876176-decd3407-f4f3-44f5-b1dd-9a557ebe472d.png)
![FAXEN0](https://user-images.githubusercontent.com/54737241/158876177-f7b00740-1f09-4c72-a25d-20ce5eeaf484.png)
.

**Comment by NightFright2k19** [comment]
After doing a quick test, I found the following:
- Heretic's BARBACK still won't be centered automatically when using [0,0] offsets on a widescreen replacement.
- Hexen widescreen weapons now show no glitches any more.

So there's still something wrong with widescreen recognition in Heretic. Statusbar is the only thing I can test there since the weapons don't really have any special measures in widescreen mode.

**Comment by fabiangreffrath** [comment]
> * Heretic's BARBACK or Hexen's H2BAR still won't be centered automatically when using [0,0] offsets on a widescreen replacement.

That's expected. This will need adaption of the code snipped I linked to here:
https://github.com/fabiangreffrath/crispy-doom/pull/861#issuecomment-1074487058

**Comment by NightFright2k19** [comment]
Alright. Then the part mentioned in this issue is definitely covered.
