### ISSUE TITLE
[Suggestion] Autoload doom-all shouldn't affect FreeDoom

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/crispy-doom#860]
Stuff in autoload doom-all folder shouldn't affect FreeDoom. It's meant for general stuff that spans across all Doom games, but... in FreeDoom, everything is different.

Examples: 
- You put a Doom widescreen statusbar in there, FreeDoom will have the wrong statusbar (unless you put a customized one in freedoom1.wad/freedoom2.wad folders, that is). 
- You put PerK's enhanced sound replacements in there, FreeDoom will use those sounds instead, not its custom ones.
- Smooth weapons (vsmooth.wad) will screw up FreeDoom's weapons as well.

I just don't see a case where it makes sense to use any content from the original Doom games with FreeDoom as well. There'll be conflicts. Yes, it's supposed to be a Doom 1+2 replacement, but it looks and sounds different and whatever you put in doom-all autoload, you don't want it to be active in FreeDoom. 

Maybe there could be a freedoom-all dir instead, but since there's only two wads available, its usefulness would be limited.

**Comment by fabiangreffrath** [comment]
I am loading the UDM3 palette through autoload/doom-all, and I think this should apply to Freedoom as well.

**Comment by NightFright2k19** [comment]
I guess it depends on what you want to do. Right now, I only have PerK's sounds in doom-all. Anyway, I want to avoid placing the same file(s) in four different subdirs (doom, doom2, plutonia, tnt) due to limitations of the autoload system. 

Of course, one could always say: "When playing Freedoom, just delete or rename the doom-all folder." That works fine ofc, but the idea of autoload should be a fire-and-forget approach. GZDoom solved this by having a doom.id autoload dir which works for any Doom game except for Freedoom.

**Comment by fabiangreffrath** [comment]
I see. On the other hand, explicitly supporting the two Freedoom IWADs (let's just ignore freedm.wad) would mean to merely duplicate the (Freedoom-compatible) stuff that is already in doom-all.

**Comment by NightFright2k19** [comment]
Now it works just the way I was hoping for. Thanks a lot!
