### ISSUE TITLE
[Feature] Support for ITEMS/KILLS/SECRETS Unity icons

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/crispy-doom#862]
Instead of showing I/K/S letters, Crispy Doom could display the stats icons from the Unity port (provided in extras.wad) if they are found, e.g. when autoloaded.

Icons look as follows (ITEMS/KILLS/SECRETS):
![ITEMS](https://user-images.githubusercontent.com/54737241/159236556-3d92892b-29bc-400c-8c37-31ad725b0bd3.png) ![KILLS](https://user-images.githubusercontent.com/54737241/159236557-b01867bb-b7ef-4a3a-ab29-b83ce2e089ea.png) ![SECRETS](https://user-images.githubusercontent.com/54737241/159236559-cc499848-0a04-469b-b4ee-3e10e3c6b2cc.png)

**Comment by NightFright2k19** [comment]
Exactly as stated - ITEMS, KILLS, SECRETS.

**Comment by fabiangreffrath** [comment]
Now I understand. 😆

**Comment by fabiangreffrath** [comment]
Could you make this ominous extra.wad available somewhere?

**Comment by rfomin** [comment]
> Could you make this ominous extra.wad available somewhere?

[extras.zip](https://github.com/fabiangreffrath/crispy-doom/files/8333262/extras.zip)

**Comment by NightFright2k19** [comment]
It has the icons for the weapons wheel in it plus two crosshair icons besides the three graphics posted above. I guess the rest in that wad is useless for this port.

**Comment by fabiangreffrath** [comment]
Hm, these icons are 11px high and thus 3px higher than the usual HU text widget line, which means the badly overwrite each other.

**Comment by fabiangreffrath** [comment]
![grafik](https://user-images.githubusercontent.com/6449237/159908224-3f38efbe-ce02-40d5-8d9c-b94293aff282.png)

**Comment by NightFright2k19** [comment]
Maybe increase the gaps between each line by 4-5px in case icons are used? I don't know what that will look like, though.

**Comment by NightFright2k19** [comment]
OK, compromise suggestion:
Completely trash the idea with the icons in favor of a Woof-style K/I/S widget sitting on the top left of the statusbar. Doesn't need to look exactly the same and can use the regular Doom font (even though it might be a bit big).
