### ISSUE TITLE
Launch error: "W_GetNumForName: M_LOADG not found"

### ISSUE THREAD

**Issue by V0du** [fabiangreffrath/crispy-doom#863]
Version of Crispy Doom: 5.11.1

Operating System and version: Windows 10 64bit ver. 21H1

Error occurs while trying to load the TNT Revilution wad (tntr.wad).

Launch command line: crispy-doom.exe -iwad "wads\tntr.wad" -deh "wads\tntr.deh"

**Comment by rzhxiii** [comment]
Not an issue, tntr.wad is not an IWAD.
Proper command line should be something like:
-iwad tnt.wad -file tntr.wad -deh tntr.deh
