### ISSUE TITLE
[Feature] Autoload folder for hexdd.wad/ Hexen Deathkings

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#864]
Version of Crispy Doom: N/a

Operating System and version: N/a

Game: Hexen

Any loaded WADs and mods (please include full command line): -file hexdd.wad

### Bug description

Observed behavior: the expansion for Hexen has no autoload folder at the moment, meaning stuff like unique widescreen assets (just the title pic is different as far as I'm aware) and MIDI replacements (like the WIP Raven Midi Pack 2) have to be loaded manually

Expected behavior: pretty self-explanatory, if possible. I decided to jump on this opportunity since Hexen's been getting some love lately :P

**Comment by NightFright2k19** [comment]
Of course it has one, like any other PWAD. If it doesn't, it's created automatically. I am using it by myself right now.

**Comment by rzhxiii** [comment]
Strange, I created a hexdd.wad folder in the appdata folder but it doesn't load anything. That's why I thought there's an issue here.
Is there a command line like -autoload *folder path* that needs to be used to create the folder by running the .exe instead of creating one manually?

**Comment by rzhxiii** [comment]
> Maybe I am overlooking something, but I don't think the per-pwad autoload feature has been implemented yet for Heretic and Hexen. Just the iwad autoload.

That was the way I remembered it as well, which is why I created this request. @NightFright2k19 can you clarify on how you got it working?

**Comment by NightFright2k19** [comment]
I checked again and have to admit you are right - it doesn't work. Apparently I overlooked the title screen and just cared about the ingame stuff, which works since it takes the widescreen assets from the hexen.wad autoload folder. So yeah, this should be done.
