### ISSUE TITLE
[Bug] All ghosts glitch of Vanilla Doom

### ISSUE THREAD

**Issue by cyberdemon2004** [fabiangreffrath/crispy-doom#867]
### Background

Version of Crispy Doom: 5.11.1

Operating System and version: N/A

Game: (Doom/Heretic/Hexen/Strife/other) Doom 2 version 1.9.

Any loaded WADs and mods (please include full command line):  N/A.

### Bug description

Observed behavior: 'All ghosts effect is being triggered at many places in Doom 2, version 1.9, in master levels as well.

Expected behavior:
Please fix this 'all ghosts glitch' effect bug permanently.

**Comment by fabiangreffrath** [comment]
Well, no, I guess. Because emulating this bug is part of being demo compatible with Vanilla Doom.

**Comment by cyberdemon2004** [comment]
Its super annoying because I go for 100% kills and secrets and its triggered almost everywhere in my map.

Moreover, this bug 

> Well, no, I guess. Because emulating this bug is part of being demo compatible with Vanilla Doom.



> Well, no, I guess. Because emulating this bug is part of being demo compatible with Vanilla Doom.

This is a super annoying bug, I hate it because I go for 100% kills and secrets and I have trusted Crispy Doom for years now.

Please fix it.

**Comment by cyberdemon2004** [comment]
> Well, no, I guess. Because emulating this bug is part of being demo compatible with Vanilla Doom.

Or at least, please add the feature of *entirely removing of intercepts limit* so it will be an option for the users to on or off intercepts limit.

**Comment by cyberdemon2004** [comment]
> Well, no, I guess. Because emulating this bug is part of being demo compatible with Vanilla Doom.

Also, it states on doom wiki as well as fandom that this all ghosts glitch is a static limit of Doom engine. Also I read that *Crispy Doom removes the static engine of Doom engine.* 

This means that Crispy Doom only removes few static limits and not all... Why is this so ?

**Comment by fabiangreffrath** [comment]
Well, the static limit indeed is removed, i.e. your game will not crash anymore if the intercepts limit is vastly exceeded. But the effects of exceeding the limit on the Vanilla engine are nevertheless emulated.

See, there are different kinds of limits: For example, there are limits to the number of textured wall segments or sprites being rendered at the same time and there is the visplane limit which would crash the engine for no apparent reason. All of these limits are indeed removed in Crispy. But there are also other limits which merely trigger a glitch in the engine when they are hit, e.g. the spechits and the intercepts limits. However, emulating these glitches is part of being 100% compatible with the original Vanilla Doom, which is an explicit mission goal of Crispy Doom. If I were to remove these glitches, it would be possible to record a demo with Crispy Doom which would desync in Vanilla Doom and vice versa - and this would be considered as a severe bug in Crispy Doom.

I like to see the intercepts limit as a design flaw in the engine which is triggered by a design flaw in the map. Try to reduce the number of linedefs crossed by the line of sight by introducing e.g. height variations. This has been requested before and there is no way I remove this from Crispy, sorry.

**Comment by JNechaevsky** [comment]
I was writing an explanation, but Fabian did it faster. 😤

I'll just add two cents then: yes, this overflow can be used for mapping tricks. Have a look at decino's walkthrough of Not Even Remotely Fair - Episode 1, MAP31: 
https://www.youtube.com/watch?v=FTq0-FvBSlE&t=3387s. He made some comments why fixing it will make level impossible to finish. 

I also would like to recommend to watch his analysis video regarding intercepts, there are some additional explanations: https://www.youtube.com/watch?v=-IYfwCWZeD0
