### ISSUE TITLE
Mouse does not go backward.

### ISSUE THREAD

**Issue by doggodanubus** [fabiangreffrath/crispy-doom#868]
### Background

Version of Crispy Doom:

Git version pulled today. 

Operating System and version:

Fedora 35 64 bit 
Fedora release 35 (Thirty Five)

Game: (Doom/Heretic/Hexen/Strife/other)

Doom2

Any loaded WADs and mods (please include full command line):

crispy-doom -file fartnokr.wad -warp 01 -skill 4

### Bug description

Observed behavior:

I cannot get the mouse to go backward. It works with keyboard but not mouse.

Expected behavior:

Pulling the mouse backward makes the player move backward.

**Comment by fabiangreffrath** [comment]
Do you have Options->Mouse Sensitivity-> vertical set to some value >0? Do you have novert enabled on the setup tool?

**Comment by doggodanubus** [comment]
Der "Allow vertical mouse movement" needs to be on. Thanks, sorry to bother you.
