### ISSUE TITLE
[Request] Exclude non-Doom games from truecolor compilation

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/crispy-doom#869]
(Note: This is mostly relevant for those that compile 64-bit builds.)

Right now, if you want a full set of executables with Doom in truecolor, you would have to make a compilation pass with truecolor enabled. While doing so will yield a functional Doom executable, any other game (Heretic, Hexen, Strife) will look like a mess since they don't support that feature. That means you would have to make another compilation run (if you want 64-bit binaries for example) without truecolor and only take Heretic/Hexen/Strife binaries from there. This seems overly complicated.

Suggested solutions:
1) Even if you set --enable-truecolor, the only game that will compiled in truecolor would be Doom while the other binaries will still be generated as well, but 8bpp only. If that is possible, that is.
2) Alternatively, add _crispy_truecolor_ var for non-Doom games as well and set it to 0 by default (that switch would have to work, though).
3) Also possible would be to provide precompiled 64-bit binaries as well, then one would only have to pick the Doom binaries after truecolor compilation and discard the rest without having to recompile. (I am aware this is already an option for those that are OK with 32-bit binaries.)

**Comment by mikeday0** [comment]
I'm not able to test this at the moment but I think you can use "out-of-tree" builds to make this less of a headache. From a fresh git clone, it would be something like this:
```
autoreconf -fi
mkdir build; cd build
../configure
cd ..
mkdir build-truecolor; cd true-color
../configure --enable-truecolor
```
Then from there you `cd` to either the `build` or `build-truecolor` directory, and then run `make` as usual. The truecolor and regular build outputs will be stored within those respective folders and will be completely separate from one another. You still have to do two compilation passes (I'm not sure you can get around that), but at least you won't have to worry about files getting overwritten.

**Comment by NightFright2k19** [comment]
Seems like a fair compromise. Will try and see if that works for me. One day there's hopefully going to be an ingame menu option to switch between 8bpp and 32bpp, then all of this won't be an issue any more.

**Comment by mikeday0** [comment]
Hmm. Try passing `--disable-fonts` as a flag to both `../configure` steps.

**Comment by mikeday0** [comment]
Out-of-tree builds work just fine on Linux, so this must have something to with the MinGW environment maybe? I just tested the procedure outlined in my first comment and it worked perfectly.

**Comment by NightFright2k19** [comment]
I don't really have MinGW properly installed on my system. Basically placed a fully operational folder in my C: dir and that's it. Shouldn't make a difference, though. Building without subdirs worked fine so far. 
Is there any specific package that needs to be downloaded before, maybe? I mean, anything besides what's outlined in the guide.

**Comment by mikeday0** [comment]
I highly doubt it's something you did. If I had to guess, it has something to do with passing bare file names to that Python script.

Still curious, did `--disable-fonts` get you past this error?

**Comment by fabiangreffrath** [comment]
Does your `<name>` contain a space character?

**Comment by NightFright2k19** [comment]
I couldn't try the font disabling thing yet since it's late here, but will do tomorrow morning.
The <name> part is just _firstname.lastname_, no spaces in it.

**Comment by NightFright2k19** [comment]
So, good news! I was able to successfully compile everything the way you suggested:

```
cd crispy-doom
autoreconf -fi
mkdir build; cd build
../configure --disable-fonts
make
strip src/*.exe
cd ..
mkdir build-truecolor; cd build-truecolor
../configure --disable-fonts --enable-truecolor
make
strip src/*.exe
```
Keeping everything separate is definitely an improvement. Guess this is as good as it can get unless there'll be official 64-bit builds (even if only available through Github Actions like in Woof!, it would be something) and/or 32bpp rendering implementation.

**Comment by mikeday0** [comment]
In this case it's not so mysterious, the `--disable-fonts` flag (unsurprisingly) disables building of the fonts in the src/textscreen/fonts folder. That's where your compilation was failing before. 

I don't think this will cause any problem. As far as I can tell the built fonts (the *.h files in that directory) are included in the repository so this step is only needed if you plan to modify the source font .png files. The fonts are used by the setup tool and the endoom screen.

**Comment by NightFright2k19** [comment]
Weird that this is the only thing that doesn't work from subdirs, but at least it doesn't prevent successful compilation.
So, for the time being, I guess that's a solution I can live with.

**Comment by mikeday0** [comment]
I wish I had a better answer for you, but the autotools stuff is a bit out of my league. Whatever the issue is, it'll need to be fixed upstream on chocolate. @fabiangreffrath I'm thinking the textscreen/fonts/Makefile.am might need something like this?

```diff
diff --git a/textscreen/fonts/Makefile.am b/textscreen/fonts/Makefile.am
index 130486b7..9b96125a 100644
--- a/textscreen/fonts/Makefile.am
+++ b/textscreen/fonts/Makefile.am
@@ -6,13 +6,13 @@ noinst_DATA = $(FONT_HDRS)
 if HAVE_FONTS

 small.h: small.png convert-font
-       $(srcdir)/convert-font small small.png small.h
+       $(srcdir)/convert-font small $(srcdir)/small.png $(srcdir)/small.h

 normal.h: normal.png convert-font
-       $(srcdir)/convert-font normal normal.png normal.h
+       $(srcdir)/convert-font normal $(srcdir)/normal.png $(srcdir)/normal.h

 large.h: large.png convert-font
-       $(srcdir)/convert-font large large.png large.h
+       $(srcdir)/convert-font large $(srcdir)/large.png $(srcdir)/large.h

 endif

```
Just a stab in the dark.

**Comment by NightFright2k19** [comment]
I will experiment with that modification and see if it gets the job done.

**Comment by NightFright2k19** [comment]
After applying your fix manually, I can say it works and you don't need the --disable-fonts parameter any more in that case.

**Comment by mikeday0** [comment]
Thanks for testing that out!

Having thought about this a little more, allow me to suggest another approach. You could do the regular build in-tree and the truecolor build out-of-tree. Then I think if you run `make` from the root crispy-doom directory it should build everything all in one go since `make` will recurse into all sub-folders.

```
autoreconf -fi
./configure
mkdir build-truecolor; cd build-truecolor
../configure --enable-truecolor --disable-fonts
cd ..
make
```

... or something like that.
