### ISSUE TITLE
A surprise from John Romero (limit-removing sourceport-requiring E1M8 replacement) revealed a bug: crash when loading a savegame when Fast Monsters option is set

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#87]
John Romero has recently released a replacement for E1M8 boss map:
https://www.doomworld.com/idgames/levels/doom/Ports/d-f/e1m8b

The description text file says
1) it needs a limit-removing sourceport to run
2) it's been tested with Crispy Doom!

I encountered a crash when loading a savegame if the game with this level has been launched with Fast monsters option (from Setup Warp tab or with a shortcut ...\crispy-doom.exe -iwad doom.wad -merge e1m8b.wad -skill 4 -fast -warp 18, doesn't matter).
The crash occurs either instantly on loading or after entering a certain sector. I tried loading games saved when running with or without fast monsters, but this didn't reveal any reliable difference.
Here I upload the savegames. The savegame named 'E1M8_NEW' can be played till a certain sector, and savegames 'E1M8NEW_FAST' and 'E1M8NEW_REG' crash immediately when loading if the game's running with fast monsters.
IMPORTANT: The crashes occur only if I load from the menu. If I add -loadgame (s) to the shortcut command line (where s=0,2 or 3 as the numbers of these savegames), the game runs well!  
[doomsavs.zip](https://github.com/fabiangreffrath/crispy-doom/files/132997/doomsavs.zip)

**Comment by fabiangreffrath** [comment]
> 2) it's been tested with Crispy Doom!

Cool, he? :)

> I encountered a crash when loading a savegame

Well, then it's apparently not been tested so well, he?

**Comment by Zodomaniac** [comment]
The crash occurs only if fast monsters option is on...probably Romero didn't test the map with fast monsters.

**Comment by fabiangreffrath** [comment]
It shouldn't make a difference, and it doesn't in Choco.

**Comment by Zodomaniac** [comment]
Well...this map isn't even supposed to run with Choco, as the description says limit-removing sourceport is required.
Have you tried loading from the menu and from the shortcut?

**Comment by Zodomaniac** [comment]
Try to launch game with -fast parameter and then load any game from the menu.

**Comment by fabiangreffrath** [comment]
Yes, I can confirm this. Has this ever happened for other maps as well?

**Comment by Zodomaniac** [comment]
I haven't tried any other maps that require limit-removing sourceports.
Nice that you were able to reproduce the bug)
