### ISSUE TITLE
[Bug] SFX don't work after .cfg line gets corrupt (with system language that uses Cyrillic?)

### ISSUE THREAD

**Issue by solek1312** [fabiangreffrath/crispy-doom#870]
### Background

Version of Crispy Doom: Crispy Doom 5.11.1

Operating System and version: Ubuntu 20.04.4 LTS

Game: Heretic

### Bug description

Observed behavior: When I launch game, first time it works fine, next times SFX don't work, so I have to delete "crispy-heretic.cfg". The particular line seems to be "libsamplerate_scale". I think it has to do with the fact Cyrillic script uses "0,000" float format instead of "0.000", because when I delete the line it launches fine, but every time it launches, it updates the file so I have to delete the file or the line again.

Expected behavior: SFX should work I guess

**Comment by mikeday0** [comment]
I believe this issue has already been reported and should be fixed in the next release. See: 2435843

**Comment by fabiangreffrath** [comment]
Yes, this is already fixed.
https://github.com/fabiangreffrath/crispy-doom/commit/2435843ccd797d6bd70fa41872b92657cf6e98dc
