### ISSUE TITLE
Cannot move the map when i turn on the overlay mode

### ISSUE THREAD

**Issue by El-Juancho** [fabiangreffrath/crispy-doom#872]
### Background

Version of Crispy Doom: Crispy Doom 5.11.1

Operating System and version: Windows 10 Pro

Game: Doom II

### Bug description
I dont know if this is a bug but when i turn off follow mode on the minimap and i enable the overlay i cannot move the map, it works well when i disable it.

**Comment by fabiangreffrath** [comment]
That's because when follow mode is disabled, the map doesn't follow your movement anymore. 🤷

**Comment by El-Juancho** [comment]
oh, I forgot to say that I move with the arrow keys to move the map, it works when i disable the overlay mode.

**Comment by El-Juancho** [comment]
https://user-images.githubusercontent.com/70743149/165088753-1d49e83b-4268-495e-b11d-55dec0079e92.mp4

**Comment by fabiangreffrath** [comment]
I guess that's because we have different key bindings for moving the map and moving the player:

https://github.com/fabiangreffrath/crispy-doom/blob/0ab96c0565d9379b2de2a814ac427ee6bc6e7b2b/src/doom/am_map.c#L782-L803

**Comment by mikeday0** [comment]
I've been messing with adding the automap overlay to Hexen and I was wondering about this restriction as well. PrBoom-Plus and DSDA-doom allow you to pan the automap in overlay mode, but Crispy does not. I'm curious, what's the reasoning behind this?
