### ISSUE TITLE
Possibility of generating tarballs with autoreconf already run

### ISSUE THREAD

**Issue by tslilc** [fabiangreffrath/crispy-doom#874]
### Background

Version of Crispy Doom: 5.11.1

Operating System and version: Linux / N.A.

Game: N.A.

Any loaded WADs and mods (please include full command line): N.A.

### Bug description

Not technically a bug, rather a request. Upon downloading downloading and extracting `crispy-doom-5.11.1.tar.gz`, before building one must run `autoreconf -i`. Would it be possible for upstream to release source files where this has already been done so that downstream doesn't need to have `autoconf` present at build time?

Observed behavior:
```
tar xf crispy-doom-5.11.1.tar.gz
cd crispy-doom-5.11.1
autoreconf -i
./configure --flags
```

Expected behavior:
```
tar xf crispy-doom-5.11.1.tar.gz
cd crispy-doom-5.11.1
./configure --flags
```

**Comment by fabiangreffrath** [comment]
The source tarball is besically a snapshot of the GIT repository at the time of release - and this does never contain any pre-generated files (at least not in the context of the build system). Sorry, but I don't have any plans to change this.

**Comment by tslilc** [comment]
No problem, thanks for your time and consideration.
