### ISSUE TITLE
Chex autoload folder cannot read chex.deh

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#876]
### Background

Version of Crispy Doom: 5.11.1 (built locally from commit 94eb9eb)

Operating System and version: Windows 10 (32-bit)

Game: Doom

Any loaded WADs and mods (please include full command line):  -iwad chex.wad -savedir .\savedir\chex

### Bug description

Observed behavior: chex.deh in the autoload folder C:\Users\username\appdata\roaming\crispy-doom\chex.wad does not get detected any longer, resulting in the .exe closing with the message attached; this happens with both truecolor and regular builds

![chex](https://user-images.githubusercontent.com/82729328/167592210-0ee50310-0817-4b97-a3e0-c7ad8482685e.PNG)

Expected behavior: not sure how this happened, since it used to work without any issues in the past, but Chocolate Doom does not read the file either (not sure if Choco was ever able to); stuff like REKKR Sunken Land still works fine.

**Comment by fabiangreffrath** [comment]
You don't have to auto-load chex.deh. Just put it next to your chex.wad IWAD and all should be fine.
