### ISSUE TITLE
Support for Boom's ANIMATED and SWITCHES lumps, and maybe MBF sky transfers

### ISSUE THREAD

**Issue by plumsinus** [fabiangreffrath/crispy-doom#88]
There are a few limit-removing maps that make use of ANIMATED and SWITCHES lumps from Boom to avoid having to rename textures to get the right animations. This is particularly the case in maps that use a texture pack such as cc4-tex, so that the map author doesn't need to include any of the textures in their map. PrBoom+ supports this on `-complevel 2` and other non-Boom modes.

[This map](https://www.dropbox.com/s/iaxl7w63crgblai/skcrpnch.wad?dl=0) is the latest example I played, it requires [cc4-tex.wad](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/cchest4) loaded with it. Original Doomworld post [here](https://www.doomworld.com/vb/post/1550445). If you want a more direct example I will make one.

A somewhat similar feature is the sky transfer linedef action from MBF, which PrBoom+ supports in `-complevel 9` and gets included in some limit-removing maps. I guess it works in ZDoom or if the player plays the map in cl9 anyhow.

**Comment by fabiangreffrath** [comment]
> There are a few limit-removing maps that make use of ANIMATED and SWITCHES lumps from Boom

Well, one might argue that as soon as a map makes use of Boom features it isn't merely limit-removing anymore but in fact a Boom map. However, I think that the features you requested are not very critical and should not even remotely endanger demo compatibility. Moreover, they should be rather straightforward to implement, so I'll take this into consideration (but I won't make any promises about a timely progress of their implementation).

**Comment by plumsinus** [comment]
>Well, one might argue that as soon as a map makes use of Boom features it isn't merely limit-removing anymore but in fact a Boom map.

I would tend to agree, but I've seen enough maps that use this kind of hybrid that I thought it'd be worth asking about. The sky transfers might be too intrusive a change to implement, but maybe not. 

I don't think they would affect demo compatibility, since demos recorded on PrBoom+ that use the SWITCHES/ANIMATED lumps can be played back on Crispy, and vice versa.

**Comment by fabiangreffrath** [comment]
Support for ANIMATED and SWITCHES lumps turns out as nearly trivial to implement. I'll have a go at it, but cannot promise to land before the 3.3. release. Will have a look at sky transfers soon.

**Comment by fabiangreffrath** [comment]
OK, got sky transfers running. They don't animate, though. :/

**Comment by Danfun64** [comment]
Sometimes it gets confusing seeing which boom/mbf features are implemented and which aren't. Can you explain what criteria allows a boom or mbf feature to be ported to crispy (bex naming and the animated lump, switches lump and sky transfers) but which ones won't be ported (complete bex support?)

**Comment by fabiangreffrath** [comment]
I admit that this is very confusing and I don't have a definite answer to this question myself. As a rule of thumb, I will add features that do not require major rewrites of Vanilla code or even replacement of (parts of ) the Choco code base. Bonus points if you can point me to a map that uses specific Boom features but is Vanilla-compatible else.

**Comment by plumsinus** [comment]
Since I think Fabian and I are mostly on the same page with regards to Crispy Doom...

BEX Naming, ANIMATED/SWITCHES, and Sky transfers are all aethetic-only, don't affect demo compatibility, were fairly easy for Fabian to implement (I think?), and are features that are used in otherwise limit-removing maps with some regularity. 

Complete BEX support would break demo compatibility, and while there probably are some old wads that used BEX Dehacked but only limit-removing map construction, I doubt there are many and it's not a thing that gets made anymore. 

Like Fabian said, there are no definite answers, just things that make a feature more or less likely to make it in. Things can also change; he might decide that full BEX support is worth doing in the future, or, that MBF sky transfers are too much of a change from Chocolate Doom.

**Comment by fabiangreffrath** [comment]
> Since I think Fabian and I are mostly on the same page with regards to Crispy Doom...

Yes, most probably. The words you have chosen describe pretty well what I was going to say in my previous reply! (Though full BEX support would not necessarily endanger demo compatibility, but this is just a nuance).

**Comment by Danfun64** [comment]
Thanks your your answers @fabiangreffrath and @plumsinus. They helped clear things up.
