### ISSUE TITLE
[Solved]I cannot save setup of crispy doom/heretic/hexen.

### ISSUE THREAD

**Issue by Borondir-Udalraph** [fabiangreffrath/crispy-doom#880]
### Background

Version of Crispy Doom:All

Operating System and version:windows 10 Pro

Game: Doom/Heretic/Hexen

### Bug description

Older version like 5.9.1 have no this problem.It seems that cfg file is not generated.How to fix it?

**Comment by mikeday0** [comment]
In the DW thread, the user said they fixed this by using English characters for the file path. Presumably the original path to the crispy-doom folder contained unicode characters I'm guessing? @Borondir-Udalraph if you don't mind can you share some more details about what you did? Thanks!

**Comment by rfomin** [comment]
This is a known issue on Windows. We fixed it on PrBoom+/Woof with this: https://github.com/fabiangreffrath/woof/blob/master/win32/win_fopen.c

**Comment by Borondir-Udalraph** [comment]
> In the DW thread, the user said they fixed this by using English characters for the file path. Presumably the original path to the crispy-doom folder contained unicode characters I'm guessing? @Borondir-Udalraph if you don't mind can you share some more details about what you did? Thanks!

Not much details can be told.I just move them out from my chinese folder......

**Comment by mikeday0** [comment]
> This is a known issue on Windows. We fixed it on PrBoom+/Woof with this: https://github.com/fabiangreffrath/woof/blob/master/win32/win_fopen.c

I definitely think this should be added to Choco/Crispy. On the surface it seems straightforward to implement.

> Not much details can be told.I just move them out from my chinese folder......

Thanks for the follow-up.

**Comment by fabiangreffrath** [comment]
> I definitely think this should be added to Choco/Crispy.

That'd be Choco and I would merge it into Crispy then.

**Comment by rfomin** [comment]
I made PR: https://github.com/chocolate-doom/chocolate-doom/pull/1463

**Comment by Winins0** [comment]
I'm having the same issue with the latest version of Crispy. Has the change not been committed yet?

**Comment by mikeday0** [comment]
When you say latest version, are you referring to the released version? (5.11.1) This change is in master as of about 6 days ago, but it hasn't made its way yet to an official release.
