### ISSUE TITLE
[Suggestion] Update icon design

### ISSUE THREAD

**Issue by philikiwan** [fabiangreffrath/crispy-doom#881]
I've noticed that the icons haven't been updated in a while. Instead of doing a drastic change, I find that simply rounding them while keeping the the "D" and the wrench out of bounds, they could look nicer and integrate better with other programs in modern operating systems.
Below is a quick scratch to illustrate what I mean:

![crispy-icons](https://user-images.githubusercontent.com/104274507/168460193-ec0262c3-cbdc-44aa-be5e-427bb44d92a3.png)

**Comment by fabiangreffrath** [comment]
I like these new icons! Could you please file a PR to replace the current ones in the `data` directory?

@JNechaevsky Is there anything that needs to be considered when creating the `doom.ico` and `doom8.ico` variants?

**Comment by philikiwan** [comment]
Sure, here's the PR #882 
I used as a base the 512x512 PNGs posted in a previous issue by @JNechaevsky 
I gave the wrench some extra stroke so that it stays visible on small sizes

**Comment by philikiwan** [comment]
I would have loved to use the D from the original doom logo and break it like a crispy chip, but I don't know if you're open to such a change and if we're allowed to do that (due to copyright issues?
Something similar to this:

![crispy-d](https://user-images.githubusercontent.com/104274507/168615357-b53de4f0-a83c-4d80-a50a-8fcb7eea4d59.png)
)

**Comment by fabiangreffrath** [comment]
We cannot use any of the original artwork, but I would be open to such an idea based on the current icon design. If you have any neat ideas, please feel free to show them up, I am interested. Thanks!

**Comment by philikiwan** [comment]
Alright, I'll see if I can come up with something and suggest it. Is the source of the original icon still available?

**Comment by philikiwan** [comment]
Here's my attempt to modernize the icon without using the original artwork. I used the same color palette and pixelated it. I only broke a single piece of it because breaking it too much doesn't look good on small sizes. The current one looks good even at 32x32.
![crispy-icon](https://user-images.githubusercontent.com/104274507/168642789-1fedd6c3-2cfe-4a11-baf3-32a3c590d21e.png)

**Comment by philikiwan** [comment]
Another option
![New Project(2)](https://user-images.githubusercontent.com/104274507/168649408-ed92dab2-e1ea-49ff-a6ac-36f8be4c179c.png)

**Comment by philikiwan** [comment]
A quick scratch for crispy-setup:
![crispy-setup](https://user-images.githubusercontent.com/104274507/168733012-bf0319ce-a010-4b40-9018-3d95a4f6d6b7.png)

**Comment by fabiangreffrath** [comment]
I like your approach with the broken out corner from yesterday and the setup icon a lot more than the variant with the circle of crisps in the background. :+1:

**Comment by JNechaevsky** [comment]
> @JNechaevsky Is there anything that needs to be considered when creating the doom.ico and doom8.ico variants?

Oops, nothing special. Icon file may contain icons with different sizes and color depths. Small sizes like 16x16 are needed to use in cases when common icon is "very detailed" and downscaled version can't preserve such details. Here's a good example of Oracle VM Virtual Box icon:

Big version (128x128) with texts and logo: 
![изображение](https://user-images.githubusercontent.com/21193394/168882718-512796f8-50f6-4b5d-8947-3a549f657f70.png)
 
Small version (24x24) w/o texts and logo - such details simply will not look good in small icon:
![изображение](https://user-images.githubusercontent.com/21193394/168882930-9e01584e-b87f-4689-b9a3-6ad0f356ca8b.png)

Both icons are inside one .ico file, which size to draw is choosen by Windows OS.

As about color depth, starting from Windows 8.1 it is no longer possible for user to choose a screen color depth, it's always 32 bit, icons are using 32 bpp depth as well. In Windows 7 and below it was possible to set 16 bpp, 256 colors and, AFAIR, 16 colors mode, and icons were using such modes respectively.

So, `doom8.ico`, should contain just a 8/4 bpp icons, while `doom.ico` will be just fine with 32 dpp version(s).

**Comment by philikiwan** [comment]
Thanks for the tips @JNechaevsky .
I also did some extra polish to the icons. Shadows are now rougher in order to improve look on small sizes, and the transition between the colors is now better instead of being a straight line. I also used another gear as a base, this one looks "crispier", the old one was too smooth.
![crispy-doom](https://user-images.githubusercontent.com/104274507/168888637-f2db4ebd-c15f-46bc-9b84-c61564392c83.png)

**Comment by philikiwan** [comment]
On a second thought, I think it would be better to just a single color. When highlighting the icon, the blue part of the icon isn't as clear as it is when not highlighted. Check at the below picture. I find the second one to be much sharper, what do you think?
![menu](https://user-images.githubusercontent.com/104274507/168892577-0b7506e4-1f7d-4a88-88e6-816458732243.png)

**Comment by philikiwan** [comment]
Here's my final suggestion:
![crispy-g](https://user-images.githubusercontent.com/104274507/168896668-01e82809-3917-4e9c-8f7b-3a18072c6a0a.png)

**Comment by mikeday0** [comment]
This is fine work! I hope that once the Doom icons are done you will consider doing a similar revamp for Heretic and Hexen. 😀

**Comment by fabiangreffrath** [comment]
To be all honest, I liked the two-colored version better than the latter approach. Could you try to add an outline in order to improve contrast when highlighted?

**Comment by philikiwan** [comment]
After doing some tests, it seems like the outline doesn't scale well when resized. It also looks ugly, and we lose the nice shadow:
![crispy-highlight-stroke](https://user-images.githubusercontent.com/104274507/169090798-489fb587-efe7-4471-aa6c-eaf8beb86556.png)

An option we have is to add a circle such as the below. It fixes the highlight problem, but I find that the icon loses some of it's charm this way:
![crisp-circle](https://user-images.githubusercontent.com/104274507/169092308-e985a09b-9ff8-4762-a477-5cd84ffdc848.png)

I think we'll have to compromise somewhere. I personally like the golden one because I think that most users will see the icon in either 32x32 or 48x48, and at this size, the one with the blue shade doesn't have a big advantage over the golden one.

**Comment by fabiangreffrath** [comment]
I'm bad at artwork. What do the friends/other devs say?

**Comment by JNechaevsky** [comment]
I would like to vote for cyan/orange colors and icon, suggested in post: https://github.com/fabiangreffrath/crispy-doom/issues/881#issuecomment-1129211602. Looks absolutely lovely in both design and coloring aspects! 🔥

**Comment by mikeday0** [comment]
I also prefer the two-tone. Honestly I don't find this: 
![image](https://user-images.githubusercontent.com/43701387/169106721-5ff407cd-af88-40d6-be95-430aae1b6d03.png)
to be objectionable at all. It's easy for me to distinguish between the blue of the highlight and the blue in the icon. Of course, I definitely acknowledge that across different screens, levels of visual acuity, etc. that there might be some loss of definition for some users.

**Comment by fabiangreffrath** [comment]
So, I think we have a decision. @philikiwan could you update your PR, please?

**Comment by philikiwan** [comment]
Done, updated PR #882 
@JNechaevsky, since we're using the same design regardless of size, I assume we don't need to place several icons in the ico, is that correct?

**Comment by JNechaevsky** [comment]
Yep, absolutely. 128x128 size should be enough for everyone and Windows will do down-scaling by itself.

**Comment by philikiwan** [comment]
@fabiangreffrath, just hold on just a sec.
@JNechaevsky, I just noticed that I can't get transparency for 8bit ICOs ?

**Comment by JNechaevsky** [comment]
Here you go: [icons8bpp.zip](https://github.com/fabiangreffrath/crispy-doom/files/8720019/icons8bpp.zip)
You can, probably it's an icon editor issue. 16, 8 and 4 bpp icons may have a transparency, but can't have a smooth alpha channel. Same as sprites in Doom. 😊

**Comment by philikiwan** [comment]
@JNechaevsky Thanks a lot!
@fabiangreffrath I've finalized the PR.

**Comment by mikeday0** [comment]
Just curious, what tool do you all use to create icons?

**Comment by philikiwan** [comment]
I used [photopea](https://www.photopea.com/) for those

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/1e8dabf5fb3b3a58b0bc863892cfbfac7acf8a43
