### ISSUE TITLE
Toggles for auto-run and vertical mouse movement in Hexen

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#885]
### Background

Version of Crispy Doom: built locally from commit [78d0ebd](https://github.com/fabiangreffrath/crispy-doom/commit/78d0ebd518effedb753b736f434b32286a18f8b6)

Operating System and version: N/a

Game: Hexen

Any loaded WADs and mods (please include full command line): N/a

### Bug description

Observed behavior: at the moment Hexen is lacking these, while both Doom and Heretic have them. The only way to enable auto-run and disable vertical mouse movement is through the set-up tool. Not sure if there are other functionality keys missing from Hexen (or Heretic) but I guess they can also be mentioned here. I guess the set-up tool for Hexen could be restructured a little bit (are the weapon 5-8 keys really necessary considering vanilla Hexen only has 4 weapons for class?).

Expected behavior: not much to add, I'm mostly testing Crispy Heretic and Hexen and if I notice anything that could make for a nice improvement to bring them up to par with Crispy Doom I'll mention them.

**Comment by rzhxiii** [comment]
I was able to get both auto-run and novert toggles working by copying https://github.com/fabiangreffrath/crispy-doom/commit/89196b5a76c3351eb45bf28f6797c437d3838ee2 and https://github.com/fabiangreffrath/crispy-doom/commit/31fcdda112e5831811a04b2b3d67f2118491ff79 almost entirely. It seems that S_StartSound(NULL, sfx_switch); needs to be removed from both toggles for it to compile, otherwise it errors out. Of course, this means no sound for the toggles. I'm going to try to find a suitable replacement, so nothing definitive yet + I'm almost scared of making a pull request but if everything goes right I could probably do this myself. With all credits going to kraflab of course, since it's their code.

**Comment by fabiangreffrath** [comment]
Please try `S_StartSound(NULL, SFX_DOOR_LIGHT_CLOSE);`

**Comment by rzhxiii** [comment]
That works perfectly, I've been somewhat testing it out.
The sound matches the other options (of course it does).
The messages display properly.
Permanent mouselook takes precedence over vertical mouse movement.
I've also taken the liberty of modifying the setup tool so now Hexen only has weapon keys for weapons 1-4, Heretic for 1-7 (unlike the chainsaw, the gauntlets don't get selected if you press 8, not sure if this is the way to do it though or if it would be cleaner to mimic Doom in this case) and Doom and Strife 1-8 (for chainsaw/ sigil respectively).
I also noticed a different issue while testing it however, for which I will be opening another, well, issue.
Still got to figure out how to open up pull requests 😅

**Comment by fabiangreffrath** [comment]
> Still got to figure out how to open up pull requests 😅

Good luck! Looking forward to your contribution.
