### ISSUE TITLE
[Hexen] Armor display broken in widescreen

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#890]
### Background

Version of Crispy Doom: built locally from [eb016d4](https://github.com/fabiangreffrath/crispy-doom/commit/eb016d4c43d3c953f26dfcd04db70594d23ad404)

Operating System and version: Windows 10 (32-bit)

Game: Hexen

Any loaded WADs and mods (please include full command line): N/a

### Bug description

Observed behavior: 

In widescreen, the armor display gets broken as the armor gets damaged.
Playing as the Cleric with all 4 armor items, this starts happening when the armor class goes under 7, and the widgets get moved around with every point of damage taken to the A.C.
Attached are screenshots of how it looks in 16:9 compared to 4:3

![HEXEN01](https://user-images.githubusercontent.com/82729328/172146246-96214877-4bc4-4a38-aa52-14e5511d244b.png)
![HEXEN02](https://user-images.githubusercontent.com/82729328/172146259-0dd4eb42-d6a7-4425-bfe0-791e6b2f0509.png)

Expected behavior: the widescreen widgets probably need some adjusting to stay in place, matching the way they look in 4:3.

**Comment by mikeday0** [comment]
Thanks for the report! I see the cause of this issue and will submit a fix this evening.
