### ISSUE TITLE
[Hexen][Bug] Automap & screen border visual glitch in low res rendering

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#896]
### Background

Version of Crispy Doom: built from 6ce2f78

Operating System and version: Windows 10 (32 Bit)

Game: Hexen

Any loaded WADs and mods (please include full command line): N/a

### Bug description

Observed behavior: If playing in low resolution, a visual glitch can be triggered by opening the automap and closing it.
The papyrus/ tan/ sand colour of the automap seems to override the grey colour of the screen border.
This happens regardless of the Crispy settings enabled (apart from the resolution).
This happens regardless of loaded WADs (it happens even with no PWADs).
This does not happen in high resolution rendering.
This does not happen in the latest versions of Chocolate Hexen (autobuilt).
I've attached multiple screenshots below, running different configs (perhaps way too many 😋)

![HEXEN02](https://user-images.githubusercontent.com/82729328/172921766-9a7d531b-d229-4671-adad-8621d789bced.png)
![HEXEN00](https://user-images.githubusercontent.com/82729328/172921772-18cda2c9-c34f-4e9f-9d3c-4ae1c3cf14a6.png)
![HEXEN01](https://user-images.githubusercontent.com/82729328/172921777-de4442a7-53f4-423c-a9b0-e1a545d05e8b.png)
![HEXEN04](https://user-images.githubusercontent.com/82729328/172921919-3336c4d8-8d04-4ac0-8238-e042dbc9a03e.png)
![HEXEN06](https://user-images.githubusercontent.com/82729328/172921926-4d837aaa-9f7f-41d3-9e3d-56976b8a292e.png)
![HEXEN00](https://user-images.githubusercontent.com/82729328/172921928-2427c44c-3234-446d-a09b-256089d3418a.png)
![HEXEN01](https://user-images.githubusercontent.com/82729328/172921930-80cfc4d3-0f40-448f-b3d1-737fa51f5b00.png)

Expected behavior: again, not much to add here, so I'm simply going to thank everyone that ever contributed to this port. I owe you all a beer.

**Comment by mikeday0** [comment]
Thanks! I'm surprised I missed this. I confess I probably don't check the low-res mode as much as I should.

Here's the culprit:
https://github.com/fabiangreffrath/crispy-doom/blob/545ca953ea7bb499badd2ccfba1fda234ae73d7b/src/hexen/r_main.c#L612-L613

@fabiangreffrath Do you recall the reason you added this? I'm wondering if it could be removed for Hexen.

**Comment by fabiangreffrath** [comment]
Well, its elaborated a bit in the commit message, but I guess we can just omit this for low-res mode  - which I, admittedly, also never check for anything. 😁 

https://github.com/fabiangreffrath/crispy-doom/commit/eb448c70b7105cb0586d1171be1b170d2ace08f8

**Comment by mikeday0** [comment]
In that case I would argue that you could remove it entirely because:
https://github.com/fabiangreffrath/crispy-doom/blob/545ca953ea7bb499badd2ccfba1fda234ae73d7b/src/hexen/r_main.c#L595
... will always make `viewheight` an even number if `crispy->hires` is 1.

**Comment by fabiangreffrath** [comment]
Yes, you are right, please remove the offending line.
