### ISSUE TITLE
[Heretic][Hexen] Setup tool overrides invert Y axis option

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#899]
### Background

Version of Crispy Doom: built from https://github.com/fabiangreffrath/crispy-doom/commit/5d04447dbe3e714e21b8d9c1fe19291a14cc71e2

Operating System and version: Windows 10 (32-bit)

Game: Heretic/Hexen

Any loaded WADs and mods (please include full command line): N/a

### Bug description

Observed behavior: if a player uses the invert Y axis option, then exits out of the game and runs the setup tool, regardless of whether any changes are made or not, saving the new settings will override this option, resulting in normal Y axis during the next session.

Expected behavior: I'm assuming this has something to do with this option being game .exe exclusive and the setup tool not recognizing it, defaulting to normal Y axis behaviour. Again, I have 0 idea of what I'm talking about so it might be something else.

**Comment by mikeday0** [comment]
I think Doom does this as well. Regardless, it should be fixed now via 3cbae012. Thanks for the report!

**Comment by fabiangreffrath** [comment]
Thanks for taking care of this @mikeday0 !
