### ISSUE TITLE
Crispy Doom doesn't show intentional HOMs

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/crispy-doom#900]
### Background

Version of Crispy Doom: master build

Operating System and version: Windows 10

Game: Doom

Any loaded WADs and mods (please include full command line): crispy-doom -iwad doom.wad -file wow.wad 

### Bug description

Observed behavior: There is an "illusio-pit" in the Wow level (https://doomwiki.org/wiki/Wow) with an intentional HOM effect that doesn't show up in Crispy due to this code: https://github.com/fabiangreffrath/crispy-doom/blob/5d04447dbe3e714e21b8d9c1fe19291a14cc71e2/src/doom/r_main.c#L1123-L1130

Expected behavior: I suggest disabling HOM detection by default.

**Comment by fabiangreffrath** [comment]
Yes, right. It was intended to hide some common mapping errors, but now it stands in the way to even detect them. I'll revert it back to Vanilla behavior.
