### ISSUE TITLE
[Feature/ Suggestion] Multiple save slot pages for Heretic/Hexen

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#903]
### Background

Version of Crispy Doom: latest autobuild

Operating System and version: Windows 10 (32-bit)

Game: Heretic/Hexen

Any loaded WADs and mods (please include full command line): N/a

### Bug description

Observed behavior: since Doom recently got 8 pages of save slots, I thought it would be nice if Heretic and Hexen were also brought in line with this change. The problem is, I took a look at the way Doom saves are implemented, the way Heretic saves are implemented (by which point I began to worry), then I took a look at the way Hexen saves are implemented and I promptly shut off my computer and went to sleep. This is definitely out of my league at the moment 😂

Expected behavior: not sure how good it would look to have 8x8 pages like in Doom, Heretic's 8 save slots already take up the whole screen, maybe reverting back to vanilla's 6 save slots for page and displaying the page number + pgup/ pgdown next to the "Save Game"/ "Load Game" titles for all three games might look better, but that's only a suggestion.

**Comment by mikeday0** [comment]
Done! See #956 and #952.

**Comment by fabiangreffrath** [comment]
🥳 Yay, thank you @mikeday0 !
