### ISSUE TITLE
Automap background scrolls with player

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#910]
### Background

Version of Crispy Doom: built from https://github.com/fabiangreffrath/crispy-doom/commit/b5e02d6f53219ec6117753a9db165be1f00d8cfc

Operating System and version: Windows 10 (32-bit)

Game: Doom/Heretic/Hexen (haven't tested with Doom, happens with both Heretic and Hexen)

Any loaded WADs and mods (please include full command line): N/a

### Bug description

Observed behavior: the automap background now scrolls in sync with player movement.
This happens regardless of other Crispy settings (e.g.: uncapped framerate)

Expected behavior: the background behaviour should emulate vanilla.

**Comment by mikeday0** [comment]
@rzhxiii Did this start with b5e02d6?

**Comment by rzhxiii** [comment]
I believe so, yes.
This commit hasn't been included in the autobuilds yet and those don't have this issue (at least in Hexen's case, but I'm assuming this is a shared problem between all games).

**Comment by fabiangreffrath** [comment]
Oh, @JNechaevsky could you please have a look then?

**Comment by JNechaevsky** [comment]
Ah, probably this should be done:
```
void AM_clearFB(int color)
{
    int i, j;
    int dmapx;
    int dmapy;
    int x1, x2, x3;

    if (followplayer)
    {
---     dmapx = (MTOF(plr->mo->x) - MTOF(oldplr.x));    //fixed point
---     dmapy = (MTOF(oldplr.y) - MTOF(plr->mo->y));
+++     dmapx = (MTOF(plr->mo->x) - MTOF(oldplr.x)) >> FRACTOMAPBITS;    //fixed point
+++     dmapy = (MTOF(oldplr.y) - MTOF(plr->mo->y)) >> FRACTOMAPBITS;
```

I need to double check, really not familiar with this parallax effect.

**Comment by JNechaevsky** [comment]
Figured it out: https://github.com/fabiangreffrath/crispy-doom/pull/911

Extra suggestion: probably worth to disable parallax in rotate + non-follow mode as well, it looks even more nauseating.

**Comment by JNechaevsky** [comment]
There are more! 😜 Which are working in non-follow mode:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/heretic/am_map.c#L356-L357

**Comment by mikeday0** [comment]
Oh no! :facepalm: I will take a look at fixing that this evening. Apologies to anyone who may have lost their lunch because of my lack of due diligence.
