### ISSUE TITLE
Windows xp does not have the required api for crispy to run

### ISSUE THREAD

**Issue by goreal818** [fabiangreffrath/crispy-doom#913]
Version of Crispy Doom: 5.11.1

Operating System and version: Windows XP 32bit service pack 2

Game; Doom

When I attempt to launch the game I get the error "The procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll"

The game doesn't launch because of this and apparently windows xp simply doesn't have the required API

**Comment by fabiangreffrath** [comment]
>  windows xp simply doesn't have the required API

Yes.

**Comment by JNechaevsky** [comment]
Indeed. It is still possible to run on XP, but this will require Service Pack 3 ([screenshot](https://user-images.githubusercontent.com/21193394/179455402-26144562-b5ac-4a64-8c81-eeff2bd543be.png)).

**Comment by rfomin** [comment]
> Indeed. It is still possible to run on XP, but this will require Service Pack 3 ([screenshot](https://user-images.githubusercontent.com/21193394/179455402-26144562-b5ac-4a64-8c81-eeff2bd543be.png)).

Nope. ([screenshot](https://user-images.githubusercontent.com/5077629/179459971-15d8a27d-97fd-40ce-b7cb-28b8d4a1346e.png)) It is possible to build Crispy Doom for Windows XP with MSVC, if there is interest.

**Comment by JNechaevsky** [comment]
Hm, I was trying to run latest build from http://latest.chocolate-doom.org/

**Comment by rfomin** [comment]
I ran the latest release. I think Fabian built it in MSYS2.

**Comment by fabiangreffrath** [comment]
Yes, releases are built with MSYS2. The development builds on http://latest.chocolate-doom.org/ are built with ancient an compiler and linked with ancient SDL libraries.
