### ISSUE TITLE
CI improvements 

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#919]
Since I have lost my ability to build release binaries on Windows (self built binaries triggers company's new AV and I have been in awkward situations because of this), I want the CI system to take over this part - just as it does in Woof. Also, I'd prefer the solution of maintaining a separate `Changelog` file instead of ending it into the `Readme` file for each release. Any volunteers?

**Comment by rfomin** [comment]
I can copy Woof's MSYS solution, but change it for autotools builds (Crispy's cmake build doesn't seem to have packaging).

**Comment by fabiangreffrath** [comment]
Yes, right, we need to call the tools in `pkg/win32` for Crispy.

**Comment by rfomin** [comment]
It seems `pkg/win32` only expects a 32-bit build. Do we need 64-bit builds?

**Comment by mikeday0** [comment]
How does the CHANGELOG.md work? Does GitHub automatically parse the entries in the file and report out the new additions since the last release?

**Comment by rfomin** [comment]
> How does the CHANGELOG.md work? Does GitHub automatically parse the entries in the file and report out the new additions since the last release?

The contents of `CHANGELOG.md` will simply be copied to an entry on the "Releases" page. https://github.com/fabiangreffrath/crispy-doom/blob/be1eff37e269421a54d235ba9bb174bdbe00d170/.github/workflows/release.yml#L77

The changelog can be generated from commit messages, but I think it would require a lot of manual editing anyway.

**Comment by mikeday0** [comment]
Thanks for the explanation! So `CHANGELOG.md` should get refreshed after every release, it does not accumulate all of the changes over the life of the project.
