### ISSUE TITLE
Implement MBF's distinction between `basetic` and `gametic`

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#92]
This would replace the current pause/unpause dance that happens when a menu is opened while recording a demo. 

It is commented in MBF's source code with encouraging words such as

```
All of this complicated mess is used to preserve demo sync.
```

and from the looks of it, it is very error-prone and will be painful to implement.

So, in the end I might not even attempt it at all. But let's keep this issue open as a reminder that I once considered it.

**Comment by plumsinus** [comment]
Truthfully I don't see it being worth the effort. Most people who are serious about demos either use PrBoom+ which already handles menus well and is usually the port of choice for playing back demos, or Chocolate (or Vanilla) for authenticity. The pause in menus is a good failsafe so you don't break your demo while recording, I don't think too much more is really necessary.

Of course, if you feel ambitious in the future, don't let me stop you!

**Comment by fabiangreffrath** [comment]
I am pretty sure that fiddling around with the gametics messes up network compatibility with both Choco and older versions of Crispy. So, until there is a definite answer to this question, I won't consider this issue anymore.

**Comment by fabiangreffrath** [comment]
I am closing some old issues that I consider irrelevant by now. Feel free to reopen with a comment if you disagree.
