### ISSUE TITLE
[Suggestion] Add Heretic & Hexen icons

### ISSUE THREAD

**Issue by kiwaph** [fabiangreffrath/crispy-doom#923]
As a follow-up to #881, I created new icons for the Heretic & Hexen binaries in the same spirit. I didn't use the original H from the games titles since these are complex shapes and are probably copyrighted.
Let me know if you have any interest in this:

![h-icons](https://user-images.githubusercontent.com/108686199/184531373-49c0a082-cd4a-459d-b196-4a780720874b.png)

**Comment by rzhxiii** [comment]
I really like these, but I feel Hexen should have it's icon based around X rather than H.
Another idea would be to have similar color schemes to the fonts of the games themselves, since the blue/ orange scheme comes from Doom's logo.
So I feel that a green H and a red X might fit better.

**Comment by fabiangreffrath** [comment]
> I really like these, but I feel Hexen should have it's icon based around X rather than H. Another idea would be to have similar color schemes to the fonts of the games themselves, since the blue/ orange scheme comes from Doom's logo. So I feel that a green H and a red X might fit better.

Exactly what I was just about to write. 👍

**Comment by kiwaph** [comment]
Here's a first scratch. There's still room for improvement, but is this the concept you had in mind?

![heretic_hexen](https://user-images.githubusercontent.com/108686199/184635791-9768f4f1-6c29-475e-b24a-77cf15744a84.png)

**Comment by kiwaph** [comment]
Red heretic:

![red_heretic](https://user-images.githubusercontent.com/108686199/184637644-d200e3b6-420d-4182-a13e-c6fb00ea24d8.png)

**Comment by JNechaevsky** [comment]
Maybe it is worth to try to make Hexen icon completelly red (w/o gradient), while keep Heretic icon completelly green? In everything else it is absolutelly amazing job. 👍

**Comment by kiwaph** [comment]
@JNechaevsky sure we can try that. I was also playing around with different shapes for the X and H, what do you think of those shapes, better?

![cut](https://user-images.githubusercontent.com/108686199/184638573-0ab25d62-9eb0-4e39-8b5c-a32cabc5e6eb.png)

**Comment by mikeday0** [comment]
Firstly, thank you for doing this! Very nice work.

I would prefer to see the overall shape of the letters have some similarity to the originals. FYI, Chocolate recently updated their icon designs and stayed pretty true to the original games:
![image](https://user-images.githubusercontent.com/43701387/184639298-11baa58e-3f6e-4bd7-9a09-40c60dab82be.png)

Also, I definitely vote green for Heretic and red for Hexen.

**Comment by kiwaph** [comment]
I could do them using the original letter shapes, but I'm not sure if we can do this due to copyright issues. Maybe someone could shed some light on this?
On another note, I personally prefer the first, more primitive shapes, since they go better with the D we used for doom. The originals are too complex (as shapes) and I think we would be straying away from the simplicity of the doom icon.
Anyway, here's a quick scratch:

![original](https://user-images.githubusercontent.com/108686199/184643451-496bf292-2bba-4213-8b2d-cdde12a15a46.png)

**Comment by kiwaph** [comment]
All 3 icons next to each other:

![3icons](https://user-images.githubusercontent.com/108686199/184645151-e2c98d29-a594-4c06-abb9-249163d00a3d.png)

**Comment by mikeday0** [comment]
I definitely support making the Heretic/Hexen icons simpler. I didn't mean to imply that they should look exactly the same as the original, sorry! I just think it would be good if the design of the new icons had some visual callback or link  to the originals. For example on Heretic, maybe the H should have the same asymmetry (the high horizontal bar). Or on Hexen, make the X have that same skewed appearance.

**Comment by kiwaph** [comment]
Thanks for clarifying! I love this idea of using simple shapes but still be reminiscent of the originals. Let me see if I can come up with something

**Comment by kiwaph** [comment]
What do you think?

![simple-shapes](https://user-images.githubusercontent.com/108686199/184654065-2aa4dc32-caa8-4185-acfd-523aa2c5cd0e.png)

**Comment by kiwaph** [comment]
Slight revision:

![crispier](https://user-images.githubusercontent.com/108686199/184660247-e45ccef5-bfdb-4833-9c54-ed793fdced2b.png)

**Comment by mikeday0** [comment]
Outstanding! I prefer the wider break myself. It matches the Doom icon better.

**Comment by kiwaph** [comment]
Thank you for the kind comments! Glad you guys liked them!

**Comment by kiwaph** [comment]
@fabiangreffrath I'll be waiting for your confirmation in order to finalize them, in case you decide to proceed.

**Comment by fabiangreffrath** [comment]
I am fine with the icons, thanks for these! What us still needed, though, is the code and build system support to build each game with its own icon.

**Comment by kiwaph** [comment]
Building stuff in C is not my field of expertise, so feel free to discard the below if it's irrelevant.
[I tried to give it a shot](https://github.com/kiwaph/crispy-doom/commit/8ba5d28d228f29cff043bfbc852712edc5ee78b3). 

What I couldn't figure out is the use of icon.c in i_video.c. Is this the icon that shows up on the window's titlebar? I built the heretic.c & hexen.c files using the python tool, but I didn't find a use for them. I'm guessing, adding a check in i_video.c to see which game is running, and use the appropriate file.

**Comment by mikeday0** [comment]
I think the code to support game-specific icons should probably come upstream from Chocolate. That project's new icons are waiting for that to be implemented as well. @fabiangreffrath or @fraggle may already be working on it. If not, feel to submit a PR there! Or, I could have a go at it when I get some time this weekend.

**Comment by fragglet** [comment]
It's probably not a lot of work to add the app specific icons - just compile in the appropriate icon.c file for each game. If you put a separate icon.c in each game directory that'll make it even easier.

**Comment by fragglet** [comment]
Also, did you folks forget there's a set of Crispy Doom icons that match the Choco ones?

https://github.com/chocolate-doom/chocolate-doom/issues/1020#issuecomment-557849165

**Comment by fabiangreffrath** [comment]
Yes, indeed I completely forgot about these. Maybe because they haven't been added as the games' individual icons in Choco for the past three years.

**Comment by kiwaph** [comment]
Source file, for reference: [heretic-hexen.zip](https://github.com/fabiangreffrath/crispy-doom/files/9379754/heretic-hexen.zip)

**Comment by kiwaph** [comment]
Strife icon in the same vein

![strife](https://user-images.githubusercontent.com/108686199/186968673-36faefe2-778f-41df-a9e2-3df05cd806e3.png)

**Comment by kiwaph** [comment]
Strife icon in the same vein

![strife](https://user-images.githubusercontent.com/108686199/186970776-3ec20647-be44-45d8-85de-3a972e22fdaa.png)

**Comment by kiwaph** [comment]
@mikeday0, I just noticed that your icon code has been merged upstream on chocolate. Thanks for doing that. Does it need any modifications to work on crispy?

**Comment by fabiangreffrath** [comment]
Now we will need another PR to add these Heretic, Hexen and Strife icons in PNG and ICO formats, respectively.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/38c566612c61d0d7380937da4c93ea183c2ad5e4

**Comment by rzhxiii** [comment]
Nitpicking here, but I just noticed all the crispy-setup.exe(s) use the same icon.
Lowest of the low priorities, but it would be nice to have them recoloured eventually.

**Comment by fabiangreffrath** [comment]
Technically, it's all the exact same binary, just given different names.
