### ISSUE TITLE
Fleshless monster?

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#925]
### Background

Version of Crispy Doom: 5.11.1

Operating System and version: Win 7

Game: Doom 2 v1.666

Any loaded WADs and mods: `start crispy-doom -iwad doom2v16.wad`, skill Ultra-Violence, then IDCLEV30

### Bug description

I saved this game in So Doom 5.9.2 but the only difference should be the extended part of the savegame.
[doomsav2.zip](https://github.com/fabiangreffrath/crispy-doom/files/9401236/doomsav2.zip)

A Knight and a Baron have been spawned by the Icon of Sin.

Observed behavior: The Baron appears to be fleshless: my rockets and bullets fly through him!

Expected behavior: the shots fired at the Baron should hit him, bullets should strike blood splatters out of him, and rockets should explode hitting him.

**Comment by slashdevslashurandom** [comment]
This sounds like [a known bug in Doom](https://doomwiki.org/wiki/Ghost_monster). If so, then it's unlikely to be fixed, since Crispy Doom aims for gameplay and demo compatibility with vanilla, and that includes preserving the original game's bugs.

**Comment by fabiangreffrath** [comment]
>  [a known bug in Doom](https://doomwiki.org/wiki/Ghost_monster)

Unlikely on an IoS map.

**Comment by fabiangreffrath** [comment]
Does the same savegame load in SoDoom with the monster intact?

**Comment by SoDOOManiac** [comment]
> Does the same savegame load in SoDoom with the monster intact?

No, in So Doom and Crispy Doom 5.9.2 the monster is also fleshless.

**Comment by fabiangreffrath** [comment]
> Unlikely on an IoS map.

Whereas... there is no crusher on MAP30 but the Baron could have been telefragged. Is there an Archvile on the map that could have resurrected him? (Sorry, can't load the savegame right now.)

**Comment by SoDOOManiac** [comment]
> Whereas... there is no crusher on MAP30 but the Baron could have been telefragged. Is there an Archvile on the map that could have resurrected him? (Sorry, can't load the savegame right now.)

The kill stats without smart totals are 0/1+2 at that moment: 0 is that no monsters were killed, 1 is the initial revenant below the Icon of Sin, and +2 are the extraspawned Knight and Baron.
Could the ghost monster appear by being spawned by Icon of Sin on a moving floor?
![DOOM0015](https://user-images.githubusercontent.com/15119473/186136756-948569ce-85de-45c4-a78a-3a838f957699.png)

**Comment by fabiangreffrath** [comment]
Hm, would be intresting to know if the Baron was "fleshless" even before the game was saved. However, I don't think this has to do with the level design. Doom2's MAP30 may be one of the most played maps ever and this issue would have been brought up before.

**Comment by SoDOOManiac** [comment]
Much later I discovered that the v1.666 IWAD I was using was damaged.
I copied it from the undamaged source (not preserving any of the damaged copies, which was probably my mistake) and tried loading the savegame with several Crispy Doom and So Doom versions.
The fleshlessness bug is gone and the mystery is solved :)
