### ISSUE TITLE
[Suggestion] Provide Linux binaries with next release

### ISSUE THREAD

**Issue by kiwaph** [fabiangreffrath/crispy-doom#927]
I've noticed that chocolate-doom provides Linux binaries with every release while crispy only offers binaries for Windows. The only option for Linux users is to either compile from source, or use older versions from the repos.

**Comment by Pedro-Beirao** [comment]
Crispy on brew is up to date.
Still it would be nice to have Linux and macOS binaries

**Comment by fabiangreffrath** [comment]
To be honest, I expect Linux users to either install their distribution's packages or build their own. Also, "one does not simply distribute Linux binaries" with more complex dependencies than libc. What if the libraries I build against break ABI relative to the ones installed on your system?

**Comment by kiwaph** [comment]
Fair points. I'm aware of the difficulties involved in the distribution of linux binaries, however, I've noticed that some projects offer distribution specific binaries (mostly for LTS distros such as Ubuntu/Mint or Debian stable). I doubt that this is a priority for the project for the time being, but since there are 3~4 releases per year, I thought that this might be done without being a burden?

**Comment by kiwaph** [comment]
Fair points. I'm aware of the difficulties involved in the distribution of linux binaries, however, I've noticed that some projects offer distribution specific binaries (mostly for LTS distros such as Ubuntu/Mint or Debian stable). I doubt that this is a priority for crispy-doom for the time being, but since there are 3~4 releases per year, might this be done without being a burden?

**Comment by kiwaph** [comment]
I just noticed that crispy-doom's on flathub. On second thought, the flatpak is probably the best solution for users who can't compile.
