### ISSUE TITLE
Crispy Doom won't run with rekkrsa.wad as the IWAD

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#928]
### Background

Version of Crispy Doom: 5.11.1

Operating System and version: Windows 10

Game: Ultimate Doom

Any loaded WADs and mods (please include full command line): `start crispy-doom -iwad rekkrsa.wad`

### Bug description

Observed behavior: the command prompt for BAT files opens and closes not launching Crispy Doom.

Expected behavior: according to [this commit](https://github.com/fabiangreffrath/crispy-doom/commit/0371cab9e3515bd5986b42d4e6a0b03cb310231b) rekkrsa.wad should load as an IWAD (sa=standalone).

**Comment by fabiangreffrath** [comment]
This happens because sigil.wad is sideloaded and their TEXTURE lumps clash. If you pass the -nosideload parameter, it should work.
