### ISSUE TITLE
[COMPILATION ERROR] SDL_Mixer.h not found despite SDL2_Mixer properly added.

### ISSUE THREAD

**Issue by Ch0wW** [fabiangreffrath/crispy-doom#931]
### Background

Version of Crispy Doom: 5.11.1

Operating System and version: Windows 10 21H2, MSVC 2022

Game: Any

Issue: SDL_Mixer.h unable to be found despite properly setting CMake.

Observed behavior: Projet doesn't compile some important parts of the project.

Expected behavior: Project should compile.?

![image](https://user-images.githubusercontent.com/2938006/186914503-9a4b1ae1-3e98-4753-93a5-c32a28f0bce8.png)

The issue is because of a slight naming error: According to the main CMakeLists.txt file, we can see the variable `ENABLE_SDL2_MIXER`, variable set also in crispy-doom's CMakeLists.txt file. However, in many subprojects, it's seen as `ENABLE_SDL2_mixer`, which... Isn't really the same value name, hence the fact it's impossible to compile on MSVC.

![image](https://user-images.githubusercontent.com/2938006/186914626-b63806eb-114b-4277-9fe3-51327a12b1ae.png)

I can't make a pull request, but it's a super trivial fix: rename all instances of `ENABLE_SDL2_mixer` to `ENABLE_SDL2_MIXER`. Project should compile now.

**Comment by mikeday0** [comment]
This has been fixed upstream by https://github.com/chocolate-doom/chocolate-doom/pull/1494. Crispy will inherit the fix the next time Chocolate is merged in.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/ff3a9a5f3822d54c95e0534195c9155f8e46f229
