### ISSUE TITLE
[Suggestion] Hide face background when status bar is hidden during single player sessions

### ISSUE THREAD

**Issue by kiwaph** [fabiangreffrath/crispy-doom#933]
I find that there is no need for the face background to be visible during single player sessions when the status bar is hidden. Without the status bar context, the HUD looks much better without the gray cubic background. Also easily implemented.
Below are some before/after screenshots:

![01](https://user-images.githubusercontent.com/108686199/187076106-f7fddcbb-a38e-4530-a9eb-d30af2b8b7d1.jpg)
![02](https://user-images.githubusercontent.com/108686199/187076109-00154ed3-ea28-41a5-a0df-f4fd870c8b59.jpg)
![03](https://user-images.githubusercontent.com/108686199/187081007-83c006d2-a4d3-4e86-9b35-eaf153c576c3.jpg)
![04](https://user-images.githubusercontent.com/108686199/187076654-1fc9118e-bafc-4311-b317-4b756428ad01.jpg)

**Comment by fabiangreffrath** [comment]
This has been done like this on purpose, to prevent the player face from mixing into the weapon sprite. Please don't try to convince me differently, I have tried all combinations and this is the one I could live with best. 😉
