### ISSUE TITLE
Doom and Setup icons show small on Windows with View-Extra large icons, unlike Heretic & Hexen

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#937]
### Background

Version of Crispy Doom: 5.12.0

Operating System and version: Win 10

Game: Doom, Heretic, Hexen

### Bug description

Observed behavior: Doom and Setup icons are small
 with View-Extra large icons setting.

Expected behavior: All icons from the GitHub release should display large with View-Extra large icons setting.

![crispy-icons-windows](https://user-images.githubusercontent.com/15119473/188119450-24b94312-4ce8-4c69-ab59-6610aa5f8365.png)

**Comment by kiwaph** [comment]
I'm not able to test on Windows right now, could you possibly let me know if you're facing the same issue with the attached icons, or do they look better?
[icons.zip](https://github.com/fabiangreffrath/crispy-doom/files/9479860/icons.zip)

**Comment by kiwaph** [comment]
Could you please try to reproduce the issue with the attached icons and let me know if you get different results? Thanks
[icons.zip](https://github.com/fabiangreffrath/crispy-doom/files/9481325/icons.zip)

**Comment by SoDOOManiac** [comment]
@kiwaph Yes, these icons display properly, they're big when View->Extra large icons setting is chosen, unlike the icons currently embedded in Crispy Doom and Setup executables.
![icons and execs](https://user-images.githubusercontent.com/15119473/188274386-c93fcc53-1b20-47d5-8189-75bd56f180ea.png)

**Comment by kiwaph** [comment]
@SoDOOManiac, thanks for pointing that out.
@fabiangreffrath, PR #939 has the updated icons, however I'm not able to compile and test the executables on a windows machine.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/2f97d6a8fb478cff3598c1f4adf43b360d625d90
