### ISSUE TITLE
No MIDI reverb

### ISSUE THREAD

**Issue by skyrain128** [fabiangreffrath/crispy-doom#940]
### Background

Version of Crispy Doom: 5.12.0

Operating System and version: Windows 11

Game: (Doom/Heretic/Hexen/Strife/other) The Ultimate DOOM

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: No reverb effects in-game MIDI in Crispy Doom
With Chocolate Doom, It's fine

https://user-images.githubusercontent.com/50762042/188300335-1a80cfc5-49cd-4538-9f31-f49ab970d1f8.mp4

https://user-images.githubusercontent.com/50762042/188300338-03cb2fda-ec6a-4ab9-9845-8fd0aae67316.mp4

Expected behavior: MIDI should play with reverb effects

**Comment by rfomin** [comment]
Are you using VirtualMIDISynth or something like that?

**Comment by skyrain128** [comment]
> 

I use Roland JV-1010

**Comment by rfomin** [comment]
There was additional reverb reset in this PR https://github.com/chocolate-doom/chocolate-doom/pull/1493

Can you please test Crispy Doom 5.11.1: https://github.com/fabiangreffrath/crispy-doom/releases/tag/crispy-doom-5.11.1

**Comment by skyrain128** [comment]
> There was additional reverb reset in this PR [chocolate-doom#1493](https://github.com/chocolate-doom/chocolate-doom/pull/1493)
> 
> Can you please test Crispy Doom 5.11.1: https://github.com/fabiangreffrath/crispy-doom/releases/tag/crispy-doom-5.11.1

It's fine in 5.11.1

**Comment by rfomin** [comment]
> It's fine in 5.11.1

According to @ceski-1 the current behavior is correct and the reverb should be reset. There is full description: https://github.com/fabiangreffrath/woof/pull/706#issue-1345396916

Chocolate Doom 3.0.0 uses SDL_Mixer for native Windows MIDI with a buggy implementation that doesn't reset properly and doesn't support SysEx messages.

**Comment by fabiangreffrath** [comment]
As far a I understand it, reverb is only reset at the end of a song and thus isn't carried over to the next one anymore - which sounds correct to me.

**Comment by ceski-1** [comment]
@skyrain128 Would you mind checking the reverb and chorus levels for the channels once E1M1 starts playing for both Chocolate Doom and Crispy Doom?

Here are the steps:
1. Hold the Volume knob and push the Value knob. Now you're in edit parameter mode.
2. Rotate the Category/Bank knob to PRESET-E. This is actually Reverb in edit mode.
3. Rotate the Part/Patch knob through the 16 channels. They should all be 40.
4. Rotate the Category/Bank knob to WAVE-EXP. This is actually Chorus in edit mode.
5. Rotate the Part/Patch knob through the 16 channels. They should all be 0.

**Comment by skyrain128** [comment]
> @skyrain128 Would you mind checking the reverb and chorus levels for the channels once E1M1 starts playing for both Chocolate Doom and Crispy Doom?
> 
> Here are the steps:
> 
>     1. Hold the Volume knob and push the Value knob. Now you're in edit parameter mode.
> 
>     2. Rotate the Category/Bank knob to PRESET-E. This is actually Reverb in edit mode.
> 
>     3. Rotate the Part/Patch knob through the 16 channels. They should all be 40.
> 
>     4. Rotate the Category/Bank knob to WAVE-EXP. This is actually Chorus in edit mode.
> 
>     5. Rotate the Part/Patch knob through the 16 channels. They should all be 0.

Chocolate Doom : Reverb 100, Chorus 0
Crispy Doom : Reverb 40, Chorus 0

**Comment by ceski-1** [comment]
> Chocolate Doom : Reverb 100, Chorus 0 Crispy Doom : Reverb 40, Chorus 0

Reverb 40 and Chorus 0 is correct. Is it possible that the JV-1010 doesn't follow midi specifications?

Please do a factory reset and then GM initialization, and then check the default reverb and chorus (don't run Doom yet). Refer to the steps in the [manual](https://www.roland.com/us/support/by_product/jv-1010/owners_manuals/), pages 21 and 46.

I have a feeling the JV-1010 boosts the reverb higher than other midi devices. Compare the music recordings for the [JV-1010](https://www.wavetable.nl/files/comparison/games/Doom/E1M1/Doom%20-%20E1M1%20%5BRoland%20JV-1010%5D.mp3) and the [SC-55](https://www.wavetable.nl/files/comparison/games/Doom/E1M1/Doom%20-%20E1M1%20%5BRoland%20SC-55%5D.mp3).

**Comment by rfomin** [comment]
> > Chocolate Doom : Reverb 100, Chorus 0 Crispy Doom : Reverb 40, Chorus 0
> 
> Reverb 40 and Chorus 0 is correct.

If @skyrain128 is using Chocolate Doom 3.0.0, he has a completely different MIDI implementation (midiproc.exe) that doesn't reset the reverb.

**Comment by fabiangreffrath** [comment]
Sorry, if I completely miss the point of the discussion, but how is it possible that *not* resetting properties like reverb between songs is deemed as the correct behaviour? For example, the E1M1 music *must* sound exactly the same if started from the menu, i.e. right after `d_intro` has been played, or if started from the command line with e.g. `-warp 1 1`.

**Comment by ceski-1** [comment]
Vanilla Doom does some resets already. I captured the output:
- Startup: GM System On, then Reset All Controllers and Volume 100 (scaled by music slider) but just for the channels used by the first song that will play
- Song Change: All Notes Off and All Sound Off for the channels used by the previous song, then Reset All Controllers and Volume 100 (scaled by music slider) for the channels used by the next song
- Shutdown: All Notes Off, All Sound Off, and Reset All Controllers for every channel, then GM System Off

Reset All Controllers is misleading as it only resets some settings. It doesn't reset volume, pan, reverb, chorus, and many others.

The original Doom music sounds fine despite not doing a full GM reset between levels because their structure is simple: they don't touch reverb and chorus, while volume and pan appear to be carefully defined at the beginning of each midi file. So Vanilla Doom gets away with an incomplete solution and sounds the same whether you manually start a game or use `-warp`.

However, today there are many wads with custom midi files from various sources and not every music composer followed the same precautions. Additionally, there's music that uses Roland GS features (an extension of GM) and SysEx messages (not present in the original Doom music). These custom midis can cause problems and require a more robust solution than Vanilla Doom.

Until recently, most source ports did no resets at all when using PortMidi or native midi, which is less than what Vanilla Doom already does. The first fix I wrote was simple and easy to integrate into many source ports. But a more complete solution is similar to what I just did for PrBoom+.

**Comment by rfomin** [comment]
> Additionally, there's music that uses Roland GS features (an extension of GM) and SysEx messages (not present in the original Doom music).

By the way, do you know PWADs with such MIDIs? I want to use them for tests.

Personally, I agree that this needs to be fixed, but perhaps people are used to the way music sounded in the past. Also a lot of music written for MS GS Wavetable Synth which has no reverb/chorus.

**Comment by ceski-1** [comment]
Here's a few:

Alien Vendetta D_BETWEE MAP04
```
F0 41 10 42 12 40 00 7F 00 41 F7 (GS Reset)
F0 41 10 42 12 40 01 33 50 3C F7 (Master Reverb Level set to 80)
F0 41 10 42 12 40 01 34 50 3B F7 (Master Reverb Time set to 80)
F0 41 10 42 12 40 1B 1C 00 09 F7 (Ch. 12 Pan set to 0)
F0 41 10 42 12 40 01 10 03 02 01 03 02 02 03 04 02 02 00 00 00 00 00 00 17 F7 (Voice Reserve tweaks to avoid notes cutting off)
```

Alien Vendetta D_THEDA3 MAP24
Yamaha XG music file. Sounds good with Yamaha S-YXG50 VSTi (software), MU80 (hardware), etc. Sounds poor with Roland/MS.
```
F0 7E 7F 09 01 F7 (GM System On, fail-safe for non-XG devices)
F0 43 10 4C 00 00 7E 00 F7 (XG System On)
F0 43 10 4C 02 01 00 01 01 F7 (Reverb type changed to HALL 2)
F0 43 10 4C 02 01 5A 01 F7 (Variation connection, effects applied system-wide)
F0 43 10 4C 30 4E 03 00 F7 (Allow simultaneous sounds for drum note 78)
F0 43 10 4C 30 4F 03 00 F7 (Allow simultaneous sounds for drum note 79)
```

Alien Vendetta (using avmidi.wad) D_DEAD MAP10
```
F0 7F 7F 04 01 7F 7F F7 (Master Volume at max: 16383)
```

Some others:
Speed of Doom D_SHAWN2 MAP19
Sunlust D_ADRIAN MAP25

I also have a wad I made where each map is a different midi CC#, SysEx, RPN, etc. When I finish it and write some documentation I'll share it. It makes it easy to rapidly test what's broken in different source ports.

**Comment by rfomin** [comment]
> Here's a few:

Thanks for these.

> When I finish it and write some documentation I'll share it. It makes it easy to rapidly test what's broken in different source ports.

Code-wise, the most advanced MIDI support in the ZDoom family. Most other ports use SDL_Mixer/midiproc or similar without SysEx.

**Comment by mikeday0** [comment]
Would it be reasonable to have the reverb, chorus, etc. reset values as config file variables? The defaults for these variables would be the values called out in the midi spec. No harm in giving knowledgeable users the ability to tweak to their preference.

**Comment by ceski-1** [comment]
@mikeday0 Yes, that could be an option. [Here are the changes](https://github.com/ceski-1/crispy-doom/commit/b695669e2c9aff6fdf42f43608d31e5655a7181f) if @fabiangreffrath wants to do that. Preference still goes to the midi file if it contains custom reverb or chorus settings. Example:

https://user-images.githubusercontent.com/56656010/188742651-423dbc52-c733-4ad1-bee6-606e30eedf01.mp4

**Comment by fabiangreffrath** [comment]
Erm, wow, thank you! Could you please file a PR for this? @rfomin seen this?

**Comment by fabiangreffrath** [comment]
https://github.com/chocolate-doom/chocolate-doom/commit/2ca5c793d6bc52ba2fda3cfe41d7adfeae20499c
