### ISSUE TITLE
[Suggestion] Implement "default difficulty" option in the menu

### ISSUE THREAD

**Issue by kiwaph** [fabiangreffrath/crispy-doom#941]
I assume that most people play using one specific difficulty for most of their playthroughs. Could we add a "default difficulty" selector which would let the chosen difficulty be pre-selected in the "Choose skill level" menu? The default being "Hurt me plenty".

![diff01](https://user-images.githubusercontent.com/108686199/188311132-92575321-3906-49d7-8883-7bf1221b8554.png)
![diff02](https://user-images.githubusercontent.com/108686199/188311136-1db6b93f-d3e1-40f9-8e69-72c13e22037b.png)

**Comment by kiwaph** [comment]
[Implementation suggestion](https://github.com/kiwaph/crispy-doom/commit/b6235160817d0a764e5559314aca8d1a61fc1b32)

**Comment by JNechaevsky** [comment]
Another instance you may wish to take care about is: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/d_main.c#L2152
It sets 3rd skill level while using `-warp` or `-record` command line parameter without `-skill` given.

**Comment by kiwaph** [comment]
@fabiangreffrath, 10be8200de109015e77e37293f5c72a4e86ba1df
@JNechaevsky, thanks for pointing it out, i'll check it out.

**Comment by fabiangreffrath** [comment]
I think I would accept this. Please file a PR, thanks!

**Comment by kiwaph** [comment]
#943

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/c2e163d232524a2fd1d24d837af5025a6ea07d3f
