### ISSUE TITLE
[Suggestion] Hexen savegame default name

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#942]
Again, for feature parity (sorry for spamming these lately :P)
The main issue is that Hexen doesn't have episodes like Doom or Heretic and maps don't necessarily come in the order they're listed.
My idea would be to use the following convention if this gets implemented:
Hub X - Player Class
I checked it out, and the longest possible combination, which is Hub X - Fighter is still below the character limit.
This could be a nice little nod to Hexen's unorthodox structure with the Hub system and the multiple playable classes.
Again, I tried to see if I can do it myself, but I don't know enough to pull it off and I don't have the time to learn how to do it either unfortunately, not for a few months at least.

**Comment by fabiangreffrath** [comment]
Probably not the hub, but something similar could be achieved with `P_GetMapName(gamemap)` (c. f. automap code) and `PlayerClass[consoleplayer]`.

**Comment by rzhxiii** [comment]
Awesome, this is perfect, I just tried it out.
Thank you for implementing it, and so quickly as well.
