### ISSUE TITLE
[Bug] Desynced Flat Animations from Vanilla/Unity Port

### ISSUE THREAD

**Issue by andrikpowell** [fabiangreffrath/crispy-doom#954]
### Background

Version of Crispy Doom: 5.11.1 Stable

Operating System and version: Windows 11 21H2

Game: Doom 2

Any loaded WADs and mods (please include full command line):
-merge 200lnmv.wad -dehlump

### Bug description

Observed behavior: flat animation is offset by one frame compared to Vanilla Doom / Unity Port.

Expected behavior: flat animation should be synced up to Vanilla Doom / Unity Port.

Ok this is a bit of a long one.

**Let me start by how flat animations work in Vanilla Doom from my rigorous testing.**
- Flat animation timing is synced exactly every time you load up a map, regardless of map if you have a flat that changes from _blue>red>yellow>green_, when you load the map and it starts on _blue_ once, it will always start on _blue_.
- The timing of the flat animation is based upon on the lump order of the WAD. This means you can change the timing / first frame of the flat animation in the game, by moving where the first flat lump of the animation is. For example: say a WAD begins with FF_START, F_SKY1, and then SLIME01 with the first slime animation frames SLIME02-04 after. now say when you load the map, the level starts with the flat as _blue_, everytime you reload the map, it'll always be blue at the start. Now say you move SLIME01-SLIME04 above F_SKY1. When you load the map now it the flat that starts on map load is now _green_. Everytime you reload the map or any map in the mapset, the flat will always start on _green_.
- The flat animation order is determined locally per wad archive. This means that the lump order nor flat animation doesn't change depending on if you load wads before or after the wad with the FLAT lumps.
- Textures work in a similar way however instead of lump order, it is based on the order of textures in the TEXTURE1 lump. however they seem to be synced correctly in all ports, unlike flats at the moment.

**Now what does Chocolate/Crispy Doom do incorrectly?**

In Vanilla Doom / Unity Port, the FF_START lump is counted in the lump order, whereas in Crispy Doom, it is not. This will lead to flat animations desyncing because of how the flat animations work specifically with lump order.

**Why is this an issue?**

I have a map from an upcoming megawad that syncs the flat animations with the texture animations that works correctly in Vanilla Doom, but not Crispy Doom. It has 6 frames for both the flat and the texture that go like this: Blue>Blue>Red>Red>Yellow>Yellow. They sync correctly in Vanilla Doom, but not Crispy Doom, because of how Vanilla Doom considers FF_START as a flat coming before F_END.

**How can you test?**

200lnv.wad is a test for the megawad. MAP25 is the map that features the animated flat and textures. You can delete the FF_START lump at the beginning of the wad or leave it there, and the flat animation will never sync up in Crispy Doom.

If you run the map in Vanilla (patched with 200lnv.deh) or in the unity port, you will see that either having FF_START or removing it, will in fact change the flat animation.

**Explanation Video:**
[https://www.youtube.com/watch?v=co5h-fwx6Ho](https://www.youtube.com/watch?v=co5h-fwx6Ho)

**Test WAD Download:**
[200 line massacre WIP](https://drive.google.com/file/d/1BnPfeUwtcBema0FYAqGwE15f9Z7QleOy/view?usp=sharing)

**Comment by fabiangreffrath** [comment]
Thanks for the report! However, in general it is not necessary to duplicate Chocolate Doom bug reports here. I merge the Choco code base regularly, so whatever fix is applied there will also end up here sooner or later.
