### ISSUE TITLE
Network game doesn't run smoothly

### ISSUE THREAD

**Issue by skyrain128** [fabiangreffrath/crispy-doom#959]
### Background

Version of Crispy Doom: 5.12.0

Operating System and version: Windows 11 x64

Game: (Doom/Heretic/Hexen/Strife/other) DOOM II

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: When I started a network game, the game lags though there's no other players than me (local client).
This bug appears only in Crispy Doom. I also tested Chocolate Doom and Woof but the bugs does not appear.

Expected behavior:

The network game should run smoothly.

**Comment by fabiangreffrath** [comment]
This is a timing bug in the network code that becomes apparent when uncapped framerate is enabled. If you disable uncapped framerate, the issue should disappear and the game runs smooth again.

**Comment by fabiangreffrath** [comment]
I don't remember why the fix from Woof didn't make it back into Crispy. Do you @rfomin ?

**Comment by rfomin** [comment]
> I don't remember why the fix from Woof didn't make it back into Crispy. Do you @rfomin ?

I wasn't sure about it. We haven't had any complaints since then, so maybe everything is fine: https://github.com/fabiangreffrath/woof/pull/577

**Comment by fabiangreffrath** [comment]
> I wasn't sure about it. We haven't had any complaints since then, so maybe everything is fine: [fabiangreffrath/woof#577](https://github.com/fabiangreffrath/woof/pull/577)

But this also had changes to `GetAdjustedTime()`. Do you think the following naive patch could work, or will any more changes be required?

```patch
--- a/src/d_loop.c
+++ b/src/d_loop.c
@@ -717,7 +717,20 @@ void TryRunTics (void)

     if (new_sync)
     {
+        if (uncapped)
+        {
+            // decide how many tics to run
+            if (realtics < availabletics-1)
+                counts = realtics+1;
+            else if (realtics < availabletics)
+                counts = realtics;
+            else
+                counts = availabletics;
+        }
+        else
+        {
        counts = availabletics;
+        }

         // [AM] If we've uncapped the framerate and there are no tics
         //      to run, return early instead of waiting around.
```

**Comment by rfomin** [comment]
> But this also had changes to `GetAdjustedTime()`. Do you think the following naive patch could work, or will any more changes be required?

Yes, I think this patch could work. Changes to `GetAdjustedTime()` were needed in Woof due to custom game speed and fastdemo, I think it's not needed in Crispy.

**Comment by fabiangreffrath** [comment]
Applied, thanks! Let's see how it works out...
