### ISSUE TITLE
Crispy Heretic crashes if shareware Heretic is used

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#961]
### Background

Version of Crispy Doom: 5.12.0

Operating System and version: Windows 10 (32 Bits)

Game: Heretic

Any loaded WADs and mods (please include full command line): heretic1.wad (both autoloaded and set with -iwad)

### Bug description

Observed behavior: when using either locally built or autobuilds of Crispy Heretic with heretic1.wad, Crispy crashes with the following error:

![Capture](https://user-images.githubusercontent.com/82729328/196794371-79357dd9-6eaa-4297-8791-ab7e70f8686c.PNG)

This doesn't happen with Chocolate Heretic.

Expected behavior: Not sure if it's really a bug or some functionality was removed some time ago, so if shareware Heretic isn't supported by Crispy there's no issue to fix here, I just found it a bit strange that it would crash.

**Comment by fabiangreffrath** [comment]
Hm, just downloaded the 1.2 shareware version and it works for me.

**Comment by rzhxiii** [comment]
Yep, tracked it down, it's because the engine still loads the content of the heretic.wad autoload folder even if heretic1.wad is used as the IWAD. Not sure if it's worth fixing since shareware Heretic is merely a curiosity at this point.

**Comment by JNechaevsky** [comment]
Small historical text string comes to mind: "You can't use `-file` in Shareware version. Register!", so probably it is worth to disable any autoloads for Shareware versions at all.

**Comment by fabiangreffrath** [comment]
Oh, right! We have done that in Doom already, time to add it to Heretic as well.
