### ISSUE TITLE
Multiplayer: Talking to Individual Players Doesn't Work. Every Player Receives Message Instead

### ISSUE THREAD

**Issue by Machine400** [fabiangreffrath/crispy-doom#964]
Background
Version of Chocolate Doom: 11.1

Operating System and version: Windows

Game: (Doom/)

Any loaded WADs and mods (please include full command line):

Bug description: Multiplayer Talking Issue
Observed behavior: When playing in a 3 or 4 player deathmatch, pressing G, I, B, or R then entering a message and sending it goes to all players and not just to the specified player.

Expected behavior: Pressing G brings up the talk cursor and should only go to G player, but it is going to every player. Same happens when trying to talk to Indigo, Brown, and Red.

**Comment by mikeday0** [comment]
Crispy inherits this from Chocolate, so there is no need to also open this issue against Crispy.
