### ISSUE TITLE
Disable Instant-Raise/Lower Sector Interpolation

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/crispy-doom#965]
Was playing [a certain WAD](https://www.doomworld.com/forum/topic/132407-knee-deep-in-kdizd-released-its-kdizd-for-doom2exe-public-build-2-is-out/) and noticed in the title demo (MAP17) that the instant-raising/lowering sectors trick is interpolated, ruining certain effects. This seems to be an issue exclusive to Crispy, as Woof and PrBoom-plus UMAPINFO don't seem to do this.

**Comment by mikeday0** [comment]
One possible fix, adapted from Woof! and prboom-plus:
```diff
diff --git a/src/doom/r_bsp.c b/src/doom/r_bsp.c
index 5a449f01..3c047ec5 100644
--- a/src/doom/r_bsp.c
+++ b/src/doom/r_bsp.c
@@ -256,7 +256,8 @@ void R_MaybeInterpolateSector(sector_t* sector)
 {
     if (crispy->uncapped &&
         // Only if we moved the sector last tic.
-        sector->oldgametic == gametic - 1)
+        sector->oldgametic == gametic - 1 &&
+        sector->specialdata)
     {
         // Interpolate between current and last floor/ceiling position.
         if (sector->floorheight != sector->oldfloorheight)
```
This takes care of the issue with KDiKDi but I'm wondering if it might break something else. @fabiangreffrath Any thoughts?

**Comment by fabiangreffrath** [comment]
Looks reasonable, PR please. 👍
