### ISSUE TITLE
Capped framerate: menu organization

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#979]
Currently the menu item says 'Uncapped framerate' which is misleading in some cases: e.g. when framerate is actually capped by `crispy->fpslimit`.

I would merge the Uncapped framerate and VSync menu items into one and call the resulting menu item just
Framerate: (vanilla/capped/uncapped/vsync)

and add a menu item to change the framerate cap value in game (default 60 fps).

**Comment by mikeday0** [comment]
I originally implemented the frame limit by mapping it to the `crispy->uncapped` variable. Fabian did not agree with this approach so the decision was made to introduce the the `crispy->fpslimit` variable instead. It is config file only because it is considered an advanced or power-user option.

**Comment by fabiangreffrath** [comment]
Hm, I think we should just disable the vsync config flag if framerate capping is enabled.

**Comment by rfomin** [comment]
Many games (especially on consoles) have a 30 fps cap with vcsync enabled to prevent tearing. Why not just make a frame limiter menu item without connecting to vsync, like in DSDA-Doom?
![image](https://user-images.githubusercontent.com/5077629/210170873-3ddd1006-7fbb-423d-910f-c6be336d8f7b.png)
I think users who want to tinker with this know how it works.

**Comment by fabiangreffrath** [comment]
> Why not just make a frame limiter menu item without connecting to vsync, like in DSDA-Doom?

Volunteers? 😁

**Comment by rrPKrr** [comment]
>I would merge the Uncapped framerate and VSync menu items into one and call the resulting menu item just
Framerate: (vanilla/capped/uncapped/vsync)

Whatever you guys decide to do from here please consider that framerate limiter and v-sync aren't mutually exclusive settings. Ie, you can use v-sync and capped framerate values that != refresh rate simultaneously. So Framerate: capped/uncapped/vsync doesn't make much sense. I am on a variable refresh rate monitor for example, so I'd want to use v-sycn on + uncapped framerate + fps limiter that is set to below max refresh rate values. So framerate/v-sync combined into one setting would cause only inconvenience.

**Comment by rfomin** [comment]
> Volunteers? 😁

So should I add a new menu item type (preferable) or add this to the setup tool?

**Comment by SoDOOManiac** [comment]
At first I thought when @mikeday0 said
>It is config file only because it is considered an advanced or power-user option

that the new menu item is not gonna happen, so I took my own approach in my fork So Doom:
changed the wording to make sense for the user and made `crispy->vsync == 2` correspond to capping FPS with config value (if it's non-zero) without vsync.
I also added a guard so that the user cannot set `crispy->vsync` to 1 (vsync on) in case of forced software rendering
https://github.com/SoDOOManiac/So-Doom/commit/a5adcfca3876f023b644c211f76ea698da81d7c4

In the code it looks bogus but for the user it's clear:
![DOOM0000](https://user-images.githubusercontent.com/15119473/210199427-442cba75-8073-42b8-8134-930d33e88ef6.png)
![DOOM0002](https://user-images.githubusercontent.com/15119473/210199428-9c0208ad-9b44-4c6a-a973-3a2a08c1a86a.png)

**Comment by fabiangreffrath** [comment]
I think we can only add boolean choices to the menu, so the actual FPS cap value will have to be set in a different config variable. I don't even know what a reasonable default value would be for this config key?

**Comment by SoDOOManiac** [comment]
> I think we can only add boolean choices to the menu, so the actual FPS cap value will have to be set in a different config variable. I don't even know what a reasonable default value would be for this config key?

Yes, in So Doom I still use `crispy_fpslimit` for the actual value and added an extra value 2 to `crispy_vsync` for capping to `crispy_fpslimit` value without vsync (that's bogus when reading the code but works for the player using the menu).

**Comment by rfomin** [comment]
> actual FPS cap value will have to be set in a different config variable

I suggest setting the actual FPS cap value in the menu and adding a new menu item type for it. Or at least in the setup.

**Comment by fabiangreffrath** [comment]
> Yes, in So Doom I still use `crispy_fpslimit` for the actual value and added an extra value 2 to `crispy_vsync` for capping to `crispy_fpslimit` value without vsync (that's bogus when reading the code but works for the player using the menu).

We have just been asked to uncouple framerate limiting from vsync here.

**Comment by SoDOOManiac** [comment]
> I suggest setting the actual FPS cap value in the menu and adding a new menu item type for it. Or at least in the setup.

I agree with adding a setup setting for FPS cap.
Then how will we handle VSync menu item: make its togglability condition `crispy->usefpslimit` or how this new variable is called?

**Comment by mikeday0** [comment]
I’m working on this. Will submit a PR later today.
