### ISSUE TITLE
New Year issue: LETITSNOW cheat to work in multiplayer

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#984]
If I understand correctly LETITSNOW starts snowing only for the player who called it, so why not enable it in multiplayer, demos and multiplayer demos?

**Comment by fabiangreffrath** [comment]
This would mean to change the network protocol to send additional tic commands. I don't think so. It's a gimmick after all and cheats do always work locally.

**Comment by SoDOOManiac** [comment]
I probably described my point in a misleading way. I mean LETITSNOW to work only locally in multiplayer and demos, just like SHOWFPS/IDRATE does, displaying FPS does work in multiplayer.

**Comment by fabiangreffrath** [comment]
Ah, I think you'll only have to modify this line then:
https://github.com/fabiangreffrath/crispy-doom/blob/6908b5000b08ae2c5470c96382ed73c89656a97c/src/doom/st_stuff.c#L1169
