### ISSUE TITLE
Warnings when building on Windows

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#986]
When building on Windows, the following warnings are issued. Can that be critical?

**Doom:**
`r_plane.c: In function 'R_DrawPlanes':
r_plane.c:421:46: warning: unknown conversion type character 't' in format [-Wformat=]
  421 |  I_Error ("R_DrawPlanes: drawsegs overflow (%td)",
      |                                              ^
r_plane.c:421:11: warning: too many arguments for format [-Wformat-extra-args]
  421 |  I_Error ("R_DrawPlanes: drawsegs overflow (%td)",
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
r_plane.c:425:46: warning: unknown conversion type character 't' in format [-Wformat=]
  425 |  I_Error ("R_DrawPlanes: visplane overflow (%td)",
      |                                              ^
r_plane.c:425:11: warning: too many arguments for format [-Wformat-extra-args]
  425 |  I_Error ("R_DrawPlanes: visplane overflow (%td)",
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
r_plane.c:429:45: warning: unknown conversion type character 't' in format [-Wformat=]
  429 |  I_Error ("R_DrawPlanes: opening overflow (%td)",
      |                                             ^
r_plane.c:429:11: warning: too many arguments for format [-Wformat-extra-args]
  429 |  I_Error ("R_DrawPlanes: opening overflow (%td)",
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Hexen:**
`r_plane.c: In function 'R_DrawPlanes':
r_plane.c:409:52: warning: unknown conversion type character 't' in format [-Wformat=]
  409 |         I_Error("R_DrawPlanes: drawsegs overflow (%td)",
      |                                                    ^
r_plane.c:409:17: warning: too many arguments for format [-Wformat-extra-args]
  409 |         I_Error("R_DrawPlanes: drawsegs overflow (%td)",
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
r_plane.c:414:52: warning: unknown conversion type character 't' in format [-Wformat=]
  414 |         I_Error("R_DrawPlanes: visplane overflow (%td)",
      |                                                    ^
r_plane.c:414:17: warning: too many arguments for format [-Wformat-extra-args]
  414 |         I_Error("R_DrawPlanes: visplane overflow (%td)",
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
r_plane.c:419:51: warning: unknown conversion type character 't' in format [-Wformat=]
  419 |         I_Error("R_DrawPlanes: opening overflow (%td)",
      |                                                   ^
r_plane.c:419:17: warning: too many arguments for format [-Wformat-extra-args]
  419 |         I_Error("R_DrawPlanes: opening overflow (%td)",
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**src:**
`make[3]: entering catalog «/home/GordonFr33m4n/crispy-doom/src»
  CC       crispy.o
  CC       i_main.o
  CC       i_system.o
i_system.c: In function 'I_Realloc':
i_system.c:355:57: warning: unknown conversion type character 'z' in format [-Wformat=]
  355 |         I_Error ("I_Realloc: failed on reallocation of %zu bytes", size);
      |                                                         ^
i_system.c:355:18: warning: too many arguments for format [-Wformat-extra-args]
  355 |         I_Error ("I_Realloc: failed on reallocation of %zu bytes", size);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC       m_argv.o
  CC       m_misc.o
m_misc.c: In function 'M_StringDuplicate':
m_misc.c:767:54: warning: unknown conversion type character 'z' in format [-Wformat=]
  767 |         I_Error("Failed to duplicate string (length %zu)\n",
      |                                                      ^
m_misc.c:767:17: warning: too many arguments for format [-Wformat-extra-args]
  767 |         I_Error("Failed to duplicate string (length %zu)\n",
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

`w_file_win32.c: In function 'W_Win32_OpenFile':
w_file_win32.c:111:5: warning: implicit declaration of function 'free' [-Wimplicit-function-declaration]
  111 |     free(wpath);
      |     ^~~~
w_file_win32.c:111:5: warning: incompatible implicit declaration of built-in function 'free'
w_file_win32.c:32:1: note: include '<stdlib.h>' or provide a declaration of 'free'
   31 | #include "z_zone.h"
  +++ |+#include <stdlib.h>
   32 |`

There are no warnings about Heretic, surprisingly,

**Comment by rfomin** [comment]
These warnings are MSYS2/MinGW specific, I don't think it's worth fixing. By the way, there are hundreds of MSVC warnings.
