### ISSUE TITLE
Personal messages to specific players are broadcasted to all players

### ISSUE THREAD

**Issue by SoDOOManiac** [fabiangreffrath/crispy-doom#987]
### Background

Version of Crispy Doom: Latest git https://github.com/fabiangreffrath/crispy-doom/commit/d2fafb59da03a83c86fc732b82d00a408b4c4874

Operating System and version: Win 7, Win 10

Game: Doom 2

Any loaded WADs and mods (please include full command line): None

### Bug description

Observed behavior: all players see the personal message for the specific player (in this case, the message is for the indigo player, but the green one sees it)

![DOOM0001](https://user-images.githubusercontent.com/15119473/210203916-d5307e6a-137b-4a2b-8ed8-ee4017373b35.png)

Expected behavior: only the addressed player should see the message.

**Comment by fabiangreffrath** [comment]
Duplicate of https://github.com/chocolate-doom/chocolate-doom/issues/1546

**Comment by SoDOOManiac** [comment]
Sorry, didn't guess to check upstream
