### ISSUE TITLE
No seamless OGG/FLAC looping in Crispy Doom 5.12.0

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [fabiangreffrath/crispy-doom#993]
### Background

Version of Crispy Doom: 5.12.0 (win32 and win64 builds)

Operating System and version: Windows 8.1 x64

Game: Doom/Doom2

Any loaded WADs and mods (please include full command line): none

### Bug description

How to reproduce:
1. Download OGG or FLAC music pack from https://sc55.duke4.net/games.php#doom
2. Extract it to %appdata%\crispy-doom\music-packs
3. Enable OGG/FLAC music in crispy-doom-config
4. Start Crispy Doom, load E1M1, wait until d_e1m1 track is supposed to loop

Observed behavior: music should loop seamlessly.

Expected behavior: music tracks loop either too late or too early.

It looks like this issue did not exist in Crispy Doom 5.11.1 (or it was less noticeable).

**Comment by mikeday0** [comment]
Already fixed via  https://github.com/chocolate-doom/chocolate-doom/pull/1531 in Chocolate. It will be in the next official Crispy release.
