### ISSUE TITLE
Hexen doors spinning wildly with uncapped framerate

### ISSUE THREAD

**Issue by jackrjli** [fabiangreffrath/crispy-doom#997]
### Background

**Version of Crispy Doom:** Latest master ec27c51063bfb82820b5a700fa1a0c76f6f4ef91 (also tried in 5.12.0)

**Operating System and version:** Fedora 37

**Game:** Hexen

**Any loaded WADs and mods (please include full command line):** hexen.wad (simply launched crispy-hexen with hexen.wad in the same directory)

### Bug description

**Observed behavior:** Sometimes in Hexen I encounter doors that are supposed to slowly rotate 180 degrees when used, but are instead continuously spinning several times a second. When this happens, the door can be walked through as if it were not there.

I don't know how to reproduce this, but it persists through saves/loads, so here's a save right in front of a door where this is occurring: [savegames.zip](https://github.com/fabiangreffrath/crispy-doom/files/10541145/savegames.zip)

The key thing to note is that this only happens when uncapped framerate is enabled. If you load the save with the original 35fps cap, the door behaves normally. If you then enable uncapped framerate and reload the save, the door will spin.

**Expected behavior:** Door should be solid and not moving upon loading the save.

**Comment by mikeday0** [comment]
Thanks for the report, and the save files! Should be all fixed now.
